### ISSUE TITLE
list index out of range when using summary_plot

### ISSUE THREAD

**Issue by olivier-s-j** [shap/shap#10]
I'm using XGBoost for a classification problem (latest version 0.7).  As parameter for XGBoost I'm setting `param['num_class'] = 5` as I have 5 classes. My data has 25 features. I use XGBoost to get the shap values by doing: `bst.predict(xg_test, pred_contribs=True)`. From XGBoost's documentation I can conclude that `n_features + 1` shap values should be returned (per sample). However what is being returned is `(n_features+1) * num_class` (which is 130 for my problem. Because of this, `summary_plot `gives an error as I provide it with 25 feature names. 

It this intended? Or should one for example select the range of 25 features from the 130 features that correspond to the correct class? E.g.: `shap_values[:,:len(xg_test.feature_names)] `for the first 25 values.

**Comment by slundberg** [comment]
Good question. I should update the docs, but yes you should just use each chunk of 25 individually. XGBoost with 5 classes really has 5 models, one for each class, so you need to explain each one.

**Comment by slundberg** [comment]
We recently updated XGBoost to pre-shape the multi-class output into a num_instance x num_class x (n_features+1) matrix. So this should help clarify future uses.
