### ISSUE TITLE
Can SHAP give row-wise importance? 

### ISSUE THREAD

**Issue by JoshuaC3** [shap/shap#100]
What I wish to know is, can SHAP give some measure of how much influence a training row had? This could be either on the trained model or afterwards, on a single prediction.

Many thanks

**Comment by slundberg** [comment]
Sounds similar to influence functions (https://arxiv.org/pdf/1703.04730.pdf). Right now the shap package does not support that (unless you are willing to view training your model as a function of every sample, but that is prohibitively expensive). I know there is work in the stats literature about influence functions for trees. There might be a connection between influence functions and SHAP values. ...seems like there should be. But unless I am just unaware that's not a solved problem.

**Comment by JoshuaC3** [comment]
Thanks for the prompt reply. Now you mention it, I remember reading about Influence Functions and think this is what I had in mind. I will close, but continue my search and comment with anything noteworthy!

**Comment by JoshuaC3** [comment]
It seems there is a very recent paper, [Finding Influential Training Samples for Gradient Boosted Decision Trees](https://arxiv.org/abs/1802.06640) looks to be very relevant. I looks like they make efficiencies in leave-one-out training by assuming that the structure does not change and then refit just the leaves.

They have chosen CatBoost as their default GBM model, which I see you are now [integrating](https://github.com/slundberg/shap/issues/58) with. Here is the github [repo](https://github.com/bsharchilev/influence_boosting).

**Comment by slundberg** [comment]
Great! That was a paper on my reading list, it looks like a direct
application of the first paper for GBDT models.
