### ISSUE TITLE
Errors when using Deep and GradientExplainers to explain multiple inputs with different types

### ISSUE THREAD

**Issue by zhoukai1105** [shap/shap#1001]
**I have a question to use SHAP to explain the result of my CNN model. My CNN models take 2 inputs with different types. One is an image, and another is a feature vector. I trained and tested the model by taking both of them into account. No problem with establishing the model.

When I tried to use SHAP to explain the result for those two inputs simultaneously, it doesn't work. I actually have tried both deepexplainer and gradientexplainer. 
I searched online and found SHAP is able to support explanation of multiple supports shown in following posts:**

[(https://github.com/slundberg/shap/blob/master/notebooks/gradient_explainer/Multi-input%20Gradient%20Explainer%20MNIST%20Example.ipynb)](url)
[https://github.com/slundberg/shap/issues/439](url)

**The model is like this** 

n_features = 10
input_feat = Input((n_features,))
input_tensor = Input(shape=(50,60, 1)) 

c3 = Conv2D(32, (3, 3), activation='relu', padding='same') (input_tensor) 
c3 = Conv2D(32, (3, 3), activation='relu', padding='same') (c3)
c3 = Conv2D(32, (3, 3), activation='relu', padding='same') (c3)
p3 = MaxPooling2D((2, 2)) (c3)

f_repeat = RepeatVector(6*7)(input_feat)
f_conv = Reshape((6, 7, n_features))(f_repeat)
p3_feat = concatenate([p3, f_conv], -1)

c3 = Flatten()(p3_feat)  
c3 = Dense(512)(c3)
outputs = Dense(2, activation='softmax')(c3)
model = Model(inputs=[input_tensor, input_feat], outputs=[outputs])

model.summary()
  
**I trained model by substituting a list including 2 inputs:**

model.fit([x_train, feature_train], y_train, batch_size=1000, epochs=1, shuffle=True)

**Once it is done, I was trying using SHAP to explain both inputs by following codes,**

explainer = shap.GradientExplainer(model, [x_train, feature_train])
shap_values = explainer.shap_values([x_test[:3], feature_test[:3]])

 **The error popped out like:**

 
  File "<ipython-input-7-f66bf2624c25>", line 1, in <module>
    shap_values = explainer.shap_values([x_test[:3], feature_test[:3]])

  File "C:\Users\kaz10003\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\deep\__init__.py", line 119, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

  File "C:\Users\kaz10003\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\deep\deep_tf.py", line 284, in shap_values
    diffs = model_output[:, l] - self.expected_value[l] - output_phis[l].sum(axis=tuple(range(1, output_phis[l].ndim)))

AttributeError: 'list' object has no attribute 'sum'

** I currently used tensorflow 1.15. I was trying to upgrade to 2.1, and the same error was obtained.**

**Any body has any idea to help me out. Thanks a lot in advance!!!!!!**

**Comment by zhoukai1105** [comment]
Update: Actually I added "np.array()" in line 284, deep_tf. The problem is solved.  GradientExplainer does give the result of shap values, but deepExplainer get stuck with gradually increased memory (no error and warning)

**Comment by stillmatic** [comment]
I ran into this same issue. Will make a PR.
