### ISSUE TITLE
Partial Dependence Plot structure is really different from other plots

### ISSUE THREAD

**Issue by alessio-greco** [shap/shap#1004]
The partial_dependence_plot function is really different from others, needing the model as input, but no shap_values.
Since all of the other plot functions need shap_values as input, I find it strange why the "basic structure" of this one is so different ( needing a "model" input and not even using it if a "shap_values" are passed)

**Comment by markusloecher** [comment]
On the same note, I would very much like an examle of using the function _partial_dependence_plot()_ and a short note on the difference to _dependence_plot()._
Thanks!

**Comment by leon-dae** [comment]
Under shap-master/notebooks/overviews/ there is a notebook called "An introduction to explainable AI with Shapley values.ipynb" where the partial_dependence_plot is used. Maybe this helps.

**Comment by XtremeCurling** [comment]
I'm wondering the same thing - why is the structure of the PDP plotting function so different from the other plotting functions? Is there a specific reason for it, or could it be modified to match the structure of the other plotting functions?

In particular, I'm manually modifying my `shap_values` into feature groups for interpretability (this is a hard requirement for my use-case). This works fine for all the other plotting functions that take `shap_values` as inputs, but not for PDP.
