### ISSUE TITLE
Summary plot type "compact_dot" not working

### ISSUE THREAD

**Issue by alessio-greco** [shap/shap#1005]
"shap.summary_plot(shap_values_0.values,  plot_type="compact_dot")" is not working, but all other plot types are. Is this a normal behaviour?

shap_values_0.values is a N_Samples x N_Feature numpy array ( shap_values_0 is a pandas dataframe )

**Comment by christabella** [comment]
I believe this is only available for TreeExplainer, which has a `.shap_interaction_values()` method
(looking at the docs at https://shap.readthedocs.io/en/latest/).

Instead of accepting SHAP values, compact_dot plot needs a 3D array of interaction values.
