### ISSUE TITLE
Additivity of multiclass examples

### ISSUE THREAD

**Issue by tstearns26-zz** [shap/shap#1009]
Is there any reason to think that a one versus all tree model (e.g. https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/XGBoost%20Multi-class%20Example.ipynb)

would have shap additivity?

**Comment by adityalahiri** [comment]
@slundberg Can you please address this? Are you implying that shap additivity holds by plotting the shap values in the way they are?

**Comment by slundberg** [comment]
SHAP views models as functions, and a multi-output model is really a set of functions that (potentially) share some parameters. So you will get a different set of SHAP values for each function output, and these SHAP values will add up that output value (plus to expected_value offset). Hope that helps clarify!

**Comment by adityalahiri** [comment]
So, in a OneVsAll multi class setting, the SHAP values for each model will be different right? And there is no additive property among the SHAP values of the different models for each class in a OneVsAll setting?
