### ISSUE TITLE
KernelExplainer not working with CatBoostRegressor and Pool

### ISSUE THREAD

**Issue by harshalchaudhari35** [shap/shap#1014]
Dear Scott, 

Not sure if this a duplicate but I couldn't find a working example of this usecase.
I'm trying to use the KernelExplainer with CatBoostRegressor. The TreeExplainer works fine but I would like to see the model agnostic explainations for this as well.

Small snippet I'm using
```
model = CatBoostRegressor(Pool(X_train, Y_train, categorical_feature_indices)
explainer = shap.KernelExplainer(model.predict, X_test) 
shap_values = explainer.shap_values(X_test)
```

I'm getting the error
Traceback (most recent call last):
  File "main.py", line 153, in <module>
    main()
  File "main.py", line 147, in main
    shap_values = explainer.shap_values(X_test, nsamples=len(X_test))
  File "/usr/lib/python3.8/site-packages/shap/explainers/kernel.py", line 211, in shap_values
    explanations.append(self.explain(data, **kwargs))
  File "/usr/lib/python3.8/site-packages/shap/explainers/kernel.py", line 236, in explain
    self.varyingInds = self.varying_groups(instance.x)
  File "/usr/lib/python3.8/site-packages/shap/explainers/kernel.py", line 428, in varying_groups
    num_mismatches = np.sum(np.invert(np.isclose(x_group, self.data.data[:, inds], equal_nan=True)))
  File "<__array_function__ internals>", line 5, in isclose
  File "/usr/lib/python3.8/site-packages/numpy/core/numeric.py", line 2257, in isclose
    xfin = isfinite(x)
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Instead if I pass the Pool of dataset as such 

```
explainer = shap.KernelExplainer(model.predict, X_test) 
shap_values = explainer.shap_values(Pool(X_test, Y_test, cat_features=categorical_features_indices))
```
I get this error
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 150, in main
    shap_values = explainer.shap_values(Pool(X_test, Y_test, cat_features=categorical_features_indices))
  File "/usr/lib/python3.8/site-packages/shap/explainers/kernel.py", line 180, in shap_values
    assert x_type.endswith(arr_type) or sp.sparse.isspmatrix_lil(X), "Unknown instance type: " + x_type
AssertionError: Unknown instance type: <class 'catboost.core.Pool'>

Not sure on how to use categorical features in KernelExplainer. TreeExplainer on the other hand when passed the Pool() works just fine. The example notes show a usecase of one-hot-encoding but I'm not using that here.

Thanks

**Comment by harshalchaudhari35** [comment]
#761 also refers to a similar issue.

**Comment by harshalchaudhari35** [comment]
@slundberg any updates on this?

**Comment by slundberg** [comment]
KernelExplainer explains any python function that takes a numpy array as input. So you can't use a Pool object as input. To deal with this you just need to wrap the cat_boost_model.predict call with a small function that converts the incoming numpy array to a pool object, then just explain that new wrapped function.

**Comment by harshalchaudhari35** [comment]
Okay I see. When you say need to wrap the function, not sure how to do that? Could you elaborate more with an example of sorts?

**Comment by slundberg** [comment]
something like:

```
def call_catboost(X):
    return model.predict(Pool(X, cat_features=categorical_features_indices))
shap.KernelExplainer(call_catboost, X_test)
```

**Comment by harshalchaudhari35** [comment]
Okay I tried this but maybe I'm doing something wrong

```
import catboost
from catboost import *
import shap
from catboost.datasets import *



train_df, test_df = catboost.datasets.amazon()
y = train_df.ACTION
X = train_df.drop('ACTION', axis=1)
cat_features = list(range(0, X.shape[1]))
model = CatBoostClassifier(iterations=300, learning_rate=0.1, random_seed=12)
model.fit(Pool(X, y, cat_features=cat_features), verbose=False, plot=False)

def call_catboost(X):
    return model.predict(Pool(X, cat_features=cat_features))

explainer = shap.KernelExplainer(call_catboost, X).shap_values(X)
```

This generates the following error:
Provided model function fails when applied to the provided data set.
Traceback (most recent call last):
  File "temp.py", line 18, in <module>
    explainer = shap.KernelExplainer(call_catboost, X).shap_values(X)
  File "/lib/python3.8/site-packages/shap/explainers/kernel.py", line 97, in __init__
    model_null = match_model_to_data(self.model, self.data)
  File "/lib/python3.8/site-packages/shap/common.py", line 89, in match_model_to_data
    out_val = model.f(data.data)
  File "temp.py", line 16, in call_catboost
    return model.predict(Pool(X, cat_features=cat_features))
  File "/lib/python3.8/site-packages/catboost/core.py", line 373, in __init__
    self._init(data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
  File "/lib/python3.8/site-packages/catboost/core.py", line 954, in _init
    self._init_pool(data, label, cat_features, text_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
  File "_catboost.pyx", line 3377, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3416, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3318, in _catboost._PoolBase._init_features_order_layout_pool
UnboundLocalError: local variable 'new_data_holders' referenced before assignment

Would really appreciate if you can show an example with my sample dataset as above

**Comment by slundberg** [comment]
In that example you can do:
```
def call_catboost(X):
    return model.predict(pd.DataFrame(X, dtype=np.int64, columns=cols))
```
But for CatBoost I really recommend using TreeExplainer since it is way faster.

**Comment by harshal-c** [comment]
Okay, I manage to get it working by excluding the Pool Object. For some reason, the shap values generated are describing it as a classification problem, whereas I'm doing a regression. is there a way to specify in the function it is a regression problem? I know internally it identifies using iml.Model object. Any ways to specify it explicitly?

**Comment by harshalchaudhari35** [comment]
@slundberg here is a quick example of what I'm working with 

```
import catboost
from catboost import *
import shap
from catboost.datasets import *
from sklearn.svm import SVR
import matplotlib.pyplot as plt

train_df, test_df = catboost.datasets.amazon()
y = train_df.ACTION
X = train_df.drop('ACTION', axis=1)
X = X.iloc[:100,:]
y = y.iloc[:100]
cat_features = list(range(0, X.shape[1]))
model = CatBoostClassifier(iterations=300, learning_rate=0.1, random_seed=12)
model.fit(Pool(X, y, cat_features=cat_features), verbose=False, plot=False)
# clf.fit(X, y)

def call_catboost(y):
    return pd.DataFrame(y)

explainer = shap.KernelExplainer(call_catboost, X)
shap_values = explainer.shap_values(X)

shap.summary_plot(shap_values, X, plot_type="bar")

plt.show()
```
![bar_plot](https://user-images.githubusercontent.com/24657672/75045522-53d05080-54bb-11ea-9eab-bd701cdeff49.png)

The bar plot is generated shows classification whereas it should be regression. Any thoughts on how to fix this behaviour?

**Comment by slundberg** [comment]
I would just do
```
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
shap.summary_plot(shap_values, X, plot_type="bar")
plt.show()
```

The issue you are seeing is because you are not calling catboost inside "call_catboost" you just returned the original dataset (which is treated like a multi-output model output)

**Comment by harshal-c** [comment]
@slundberg sorry, but my original question is about using KernelExplainer to get the model agnostic SHAP values. As previously, suggested by you to use the call_catboost() wrapper function I have tried to do that, as essentially what it expects is a "dummy" function which would return the predictions array. In my understanding, it should work if provided with the function that does this but it doesn't seem to understand it as a regression problem

**Comment by slundberg** [comment]
I see. I think the issue here is that KernelExplainer does not care if it is a classification or a regression problem. It just sees a multi-output problem. The summary plot takes the liberty of naming the outputs "Class X", so perhaps that's the real issue here, that the plot should not assume all multi-output explanations are "classes"

**Comment by harshal-c** [comment]
@slundberg Indeed. Any workaround for this? Are the outputs of the SHAP relevant and correct? i.e regardless of the summary_plot(), could I use my own plotting to get the bar graphs by adding up the shap values?

**Comment by harshal-c** [comment]
@slundberg any updates on this?
