### ISSUE TITLE
DeepExplainer returns error as Explanations do not sum up to the model's output

### ISSUE THREAD

**Issue by sakura7621** [shap/shap#1015]
I use **DeepExplainer** for stock data with LSTM.
It returns an error as **Explanations do not sum up to the model's output! Please post as a github issue**.

> AssertionError              Traceback (most recent call last)
<ipython-input-16-203dec3ae627> in <module>
1   explainer = shap.DeepExplainer(model, X_train)
----> 2    shap_values = explainer.shap_values(X_test)
/opt/conda/lib/python3.6/site-packages/shap/explainers/deep/init.py in shap_values(self, X, ranked_outputs, output_rank_order)
117         were chosen as "top".
118         """
--> 119         return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
/opt/conda/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
283             for l in range(len(X)):
284                 diffs = model_output[:, l] - self.expected_value[l] - output_phis[l].sum(axis=tuple(range(1, output_phis[l].ndim)))
--> 285                 assert np.abs(diffs).max() < 1e-4, "Explanations do not sum up to the model's output! Please post as a github issue."
286         if not self.multi_output:
287             return output_phis[0]
AssertionError: Explanations do not sum up to the model's output! Please post as a github issue.

The full source code here (including data, model): https://github.com/chaupmcs/DeepExplainerReturnsError/blob/master/DeepExplainer%20returns%20error%20with%20Stock%20data.ipynb

Thanks.

**Comment by bernatcp** [comment]
Hello,

I am also interested in this, because I have just had the same problem (also an LSTM model and DeepExplainer, python 3.7.1, tensorflow 1.15.0).

Moreover, I would also like to say that my first approach to explain this LSTM model was using tensorflow2 and Gradient Explainer, and in spite of that it gave me no error, the explanations were inconsistent. I considered It was my fault (i.e. a bug in my code, I am just learning to use SHAP in DeepLearning after using it for a while in Ensemble Trees), but when I repeated the script with tensorFlow 1.15 and DeepExplainer I had the AssertionError, so maybe there is a problem there too. 

Thanks for this great tool.

**Comment by sizhe1987** [comment]
Hi,

Same problem here. Just a very simple DNN programmed in Tensorflow 1.15. Used DeepExplainer then got the error there. Haven't tried Gradient Explainer yet but Tree explainer seems fine.

**Comment by bernatcp** [comment]
It seems (I read it in another issue) that the latest versions of SHAP included this assertion. The problem might be something related to the floating point error and the assertion that is too small (but I don't know...). 
In my case, using the SHAP 0.31 (i.e. a version of SHAP without the assertion error) solved this problem. 

Hope it helps.

**Comment by slundberg** [comment]
This new check is there to make sure nothing goes wrong with some unsupported network operator. You can always turn it off with `check_additivity=False` but the best solution would be to share an example notebook we can use to debug what might be causing the issue. I'll keep trying to track any errors down I find myself of course, and update that error message to be more helpful

**Comment by bernatcp** [comment]
Thanks @slundberg for the answer.

I work with unshareable data (from banks, utility companies, etc.) and I am not able to easily share an example notebook. 

Regarding the check_additivity=False, a workmate tried it with no success (I think it was our fault), this is why we downgrade the shap library. I will check it again.

Thank you for this library, is by far the explanatory approach that has given me better results.
