### ISSUE TITLE
which method is best for subsampling?

### ISSUE THREAD

**Issue by prathyushapatel** [shap/shap#1018]
For subsampling, there are 2 methods shap.sample(data,K) and shap.kmeans(data,K).
Which of them is better?
What's the ideal K size when my dataset is contains 50000 rows

**Comment by HughChen** [comment]
`shap.sample` basically is just a random sample of the data (via `sklearn.utils.resample`) and `shap.kmeans` uses kmeans to try to represent the data in a more averaged way.  Both are provided to allow you to subsample the data you will use as background data.

My impression is that using a random sample is unbiased but will require more samples to give you a "good" background data set.  The downside of kmeans is that it might be biased but will converge faster.  An additional downside of kmeans is that it is typically harder in the presence of categorical variables where finding the mean is not as straightforward.

As for the ideal K size, I don't believe there is an ideal size, and it will depend on your model and data distribution.  You can always try running for different sizes of background data (for both kmeans and sample) and see when the SHAP values converge.
