### ISSUE TITLE
Making tqdm optional

### ISSUE THREAD

**Issue by AbdealiLoKo** [shap/shap#1019]
I'm trying to run shap in a server for some users in a production pipeline.
And it was unusual for `tqdm` to be a rquired dependency here.
https://github.com/slundberg/shap/blob/master/setup.py#L104

For cases when we are going to run shap in an automated setup with no manual intervention, it would be nice to not have tqdm - because it adds the additional overhead of installing and maintaining this dependency.
Not to mention the additional logs tqdm generates for the progress. (Which as I understand it can be made "silent" for KernelExplainer but not LinearExplainer)

**Comment by jvac06** [comment]
Can we also make these available for other explainer types i.e. trees?
