### ISSUE TITLE
Stacked force plot visualisation bug?

### ISSUE THREAD

**Issue by alexcoca** [shap/shap#1020]
Hi @slundberg,

First, thanks for your work on this library, it's amazing!

I was experimenting with explaining an SVM multiclass classification on the Wine dataset. When playing with the stacked force plots,  I selected the the `effects` of a particular as the `y` axis and also sorted the `x` in ascending order for the same value. I'm nonetheless puzzled, as my expectation is that the I'm displaying the shap values, but this doesn't seem the case? 

In the image attached, you can see that shap value for instance `2` is `0.1588` but the point I clicked on is at the bottom of the through whereas the the shap value for instance `15` which comes before this is `0.1049`. Yet, the `y` value of `15` on the graph is higher than the `y` value of `2`... I would be grateful if you could explain what this plot displays in case I am confused... The only way this could occur is if the feature effect was calculated with respect to different "baseline" values for the two instance, but this cannot be the case since we start with the same value as the separate force plots show ...

![image](https://user-images.githubusercontent.com/30216068/73351867-d3397e00-4287-11ea-9f47-99d377943da4.png)

Thank you in advance!

**Comment by slundberg** [comment]
Thanks for catching this! It looks like the bold numbers on the left don't change when you select a single feature. I will have to see about how to fix the JS

**Comment by alexcoca** [comment]
Hi @slundberg ,

Thanks for getting back to me! When I investigated, the bold numbers seemed correct - they just represent the classifier output and correspond to what is displayed in the individual force plots below. My lack of understanding about what is going on arised from the fact that I thought that this plot should have displayed the effects (aka shap values) of the `flavanoids` feature when the `x` axis is sorted in increasing order according to the `flavanoids` feature value. However, when I click on the plot, data point `15` with a smaller shap value was displayed above (meaning towards more positive y values) 
data point `2` with a larger shap value compared to point `15`, which I didn't understand ...

**Comment by slundberg** [comment]
@alexcoca I just pushed a fix. Let me know if that addressed the problem for you (remember to both refresh the notebook's webpage and restart shap after removing the JS code cell to get the new JS code embedded and loaded.

**Comment by alexcoca** [comment]
Hi @slundberg ,

Sorry for the delay, I was away for a bit. I can confirm the issue is now fixed! Thanks ever so much for your support and this great library!
