### ISSUE TITLE
Modelling piecewise function

### ISSUE THREAD

**Issue by ghost** [shap/shap#1023]
How did we can explain model for modelling piecewise function with essential discontinuity ?
For example, we have data with one feature and  target, and that target have discontinuity intervals, for example, domain of definition function is [-5, -2] and [2, -5] with discontinuity on interval [-2, 2], how SHAP can explain feature importance on discontinuity interval in such case ? Do you have any experiments or teorethical approach ?

**Comment by slundberg** [comment]
I am not sure I entirely follow, but if you have a simple Python example that is best. Function discontinuities should not matter for SHAP's applicability.
