### ISSUE TITLE
Add NGBoost support in TreeExplainer

### ISSUE THREAD

**Issue by GitAnalyst** [shap/shap#1025]
Hey, there is a new tree algorithm in town called Natural Gradient Boosting - [NGBoost](https://stanfordmlgroup.github.io/projects/ngboost/). It doesn't have documentation yet, but its main appeal is that it brings probabilistic predictions, which is something new for regression tasks. It would be great to add this to TreeExplainer support, it follows Scikit-Learn conventions.
Example:
```python
import shap
import ngboost
from ngboost.learners import default_tree_learner
from ngboost.distns import Normal
from ngboost.scores import MLE

dataset = load_boston()
X, y = dataset.data, dataset.target

model = NGBRegressor(Base=default_tree_learner, Dist=Normal, Score=MLE).fit(X, y)
print(type(model))
```
Returns type:
```
<class 'ngboost.api.NGBRegressor'>
```
TreeExplainer returns an exception:
```python
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
```
```
Exception: Model type not yet supported by TreeExplainer
```

Model predicts as usual:
```python
X_sample = X[0:3,:]
ngb.predict(X_sample) # point predictions
```
And for each observation we can predict probability distribution:
```python
dist = ngb.pred_dist(X_sample)
print(dist.loc[0:3]) # mean (same as point prediction)
print(dist.scale[0:3]) # standard deviation associated to point prediction
```

**Comment by slundberg** [comment]
Thanks for bringing this up. I have actually been slow about merging and editing #983 which will handle this. But it is now merged so 
```
ngb = NGBRegressor().fit(X_train, Y_train)
explainer = shap.TreeExplainer(ngb, X, model_output=0)
shap_values = explainer.shap_values(X)
shap.dependence_plot(0, shap_values, X)
```
will now explain the first parameter of the distribution (which for a normal distribution is the mean).
