### ISSUE TITLE
Call of the shap_values() raises ValueError

### ISSUE THREAD

**Issue by i-zaitsev** [shap/shap#1026]
I have the following model that uses `SGDClassifier`:
```python
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier()
X, y = create_dataset()  # pandas data frame and numpy array, respectively
sgd.fit(X, y)
mean, cov = X.mean(), X.cov()
exp = shap.LinearExplainer(sgd, (mean, cov))
shap_values = exp.shap_values(X)
```
It is very similar to the example provided in the README. However, I am getting the error:
```
ValueError: Length of passed values is <num_of_rows>, index implies <num_of_cols>
```
I cannot understand what it really means. I've tried to transpose the matrix but in this case, I am getting the error:
```
ValueError: operands could not be broadcast together with shapes ...
```
Do you know what it could be?

**Comment by slundberg** [comment]
Thanks for posting! I think it was because the mean and cov you passed were Panda's objects (that's how I got it to fail) and the explainer was expecting numpy arrays. I just pushed a fix to unwrap Panda's objects automatically now.

**Comment by i-zaitsev** [comment]
Ok great! Thank you very much for such a prompt response! :)
