### ISSUE TITLE
Features were not shown on shap force plot.

### ISSUE THREAD

**Issue by Galileo1020** [shap/shap#1027]
When I ploted the shap force plot, it did not show any features.
I used less features and trained model with the same algorithm. The shap force plot could show some features on it.
So I think the reason is that the number of features are too large.
Is there any way to make shap force plot show features even the number of features are large?

**Comment by slundberg** [comment]
Could you share a small self contained example and make sure the problem does not change when `matplotlib=True`? I don't know of any feature limit for force_plot other than browser memory (I have used thousands of features just fine).
