### ISSUE TITLE
How to deal with models from type lightgbm.sklearn.LGBMRegressor?

### ISSUE THREAD

**Issue by MarkiesFredje** [shap/shap#103]
Looking at shap/tree.py, i notice a check for str(type(model)).endswith("lightgbm.basic.Booster'>")
However, the models I have trained are of type lightgbm.sklearn.LGBMRegressor.

Would it be possible to add support for  lightgbm.sklearn.LGBMRegressor and lightgbm.sklearn.LGBMClassifier?

Pending that, do you see any workaround on my end you would advise?

**Comment by slundberg** [comment]
Thanks for pointing this out. Just pushed an update to fix this. It will be on pypi as 0.17 once the travis builds finish.
