### ISSUE TITLE
plot_type="compact_dot" not working anymore

### ISSUE THREAD

**Issue by grassoste** [shap/shap#1030]
Hi, 
at the moment (Python 3.7.5 and shap 0.34) when using the command summary_plot on the interaction values (`shap.summary_plot(interaction_vals, X, max_display=5, plot_type="compact_dot")`) I get a "normal" summary, similar to the one for shap values. 
When removing the option `plot_type` or with `plot_type="dot"` instead I get the correct graph. Given the command runs smoothly no error is produced.
Looking at the documentations and older commits this should be a novel bug. In previous versions of shap (not sure from which one) there was no issue.

**Comment by slundberg** [comment]
The `compact_dot` unrolls the interaction effects and main effects and puts them all as rows of the plot (try setting max_display=50` to see what I mean). It seems to be working for me.

**Comment by grassoste** [comment]
Sorry you are right! That's exactly the expected behavior. I totally misunderstood #501 and apparently my interactions are fairly low compared to the main effect so it looked identical to the normal one. My bad.

**Comment by slundberg** [comment]
great. no problem
