### ISSUE TITLE
Issues regarding waterfall_plot on multi-class classification

### ISSUE THREAD

**Issue by ivan-marroquin** [shap/shap#1031]
Hi,

I have Python 3.6.5 and I am using Shap version 0.34.0 on a windows machine.  The model was trained using XGBClassifier from xgboost 0.90. The trained model consists of six classes.

I noticed these issues:
a) When using command: shap.waterfall_plot(shap_explainer.expected_value, shap_values[0], features= pd_test_inputs.iloc[0,:], feature_names= feature_names, show= True)

gives this warning message: 

waterfall_plot requires a scalar expected_value of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.expected_value, shap_values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.expected_value[0], shap_values[0][0], X[0]).

However, the command: print(" shap explainer Expected Values ", shap_explainer.expected_value) gives a single numerical value.

is it possible that shap_explainer.expected_value is not working? It seems that this command should generate an array with # samples equal to # classes

b) When using command: shap.waterfall_plot(shap_explainer.expected_value[0], shap_values[0], features= pd_test_inputs, feature_names= feature_names, show= True)

gives this warning message: The waterfall_plot can currently only plot a single explanation but a matrix of explanations was passed!

However, "shap_values[0]" and "pd_test_inputs" are matrices of # samples x # features, and according to docstrings the command waterfall_plot should be able to handle them.

c) When using the command: shap.waterfall_plot(shap_explainer.expected_value[0], shap_values[0][0], features= pd_test_inputs.iloc[0,:], feature_names= feature_names, show= False)

produces the waterfall plot. But, how this command can compute the evidence of all other features when only one was provided (features= pd_test_inputs.iloc[0,:])? Also, what does the values on the vertical axis mean? What about the values in the plot itself? 

The expected value is -1.70, it seems that the position of E[f(X)] is incorrect along the x-axis.

I attached a zip file to reproduce the reported incident. Hope this helps,

Ivan

[testing_shap_waterfall_plot.zip](https://github.com/slundberg/shap/files/4160945/testing_shap_waterfall_plot.zip)

**Comment by slundberg** [comment]
Thanks for the bug report! I fixed (a) just now. It was because the single number you were passing was a zero dimensional numpy array, so it mistakenly thought it was an array not a number. As for (b) can you try again on the master version of shap? I think that was fixed by a recent patch I gave for another issue you mentioned.

**Comment by ivan-marroquin** [comment]
Hi @slundberg 

thanks for the quick turn around. Could you elaborate on my questions for item (c).

**Comment by ivan-marroquin** [comment]
Hi @slundberg 

I just download the latest master version and installed using "python setup.py install" command.

The expected_value is now an array with # elements equal to # classes.

Tested command in (a) and gave this output: 

waterfall_plot requires a scalar expected_value of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.expected_value, shap_values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.expected_value[0], shap_values[0][0], X[0]).

I think this is the expected behavior

Tested command in (b) and gave this output: The waterfall_plot can currently only plot a single explanation but a matrix of explanations was passed!

So, I think that the waterfall_plot can't still handle matrix - If it is the case, I guess the doctsting needs to be updated

I would like to have your explanations on how the command in (c) works and is able to produce a graphic display that includes all features.

Ivan

**Comment by slundberg** [comment]
Good point I'll update the docs. As for (c) you are giving the value of all the features since `pd_test_inputs.iloc[0,:]` is all the features for the first sample.
