### ISSUE TITLE
SHAP for revealing interdependence of word positions

### ISSUE THREAD

**Issue by octolis** [shap/shap#1032]
Hi,
thank you for your great package! 
I'm working on the following task. I have a dataset of biological sequences (strings containing ~100-150 letters, every letter is considered as a word and every sequence is a 'sentence'). I've trained a biGRU that is able to distinguish between an original sequence and a sequence with a slightly perturbed order of symbols. I was able to find that some of the positions within the sequences are more important (e.g. having the higher weights) for the prediction. Now what I need is to find whether some of the important positions are interdependent. My question is if it is possible to use SHAP for such a problem and, if yes, I'd appreciate any hints or considerations on the implementation.

**Comment by slundberg** [comment]
Interaction effects are what you want, but those are only implemented right now for TreeExplainer. You could compute the interaction values manually by following the equations in https://rdcu.be/b0z70 or you can wait since we are doing more work on that. Sorry that's not a great answer :)

**Comment by octolis** [comment]
Thank you for your answer!
