### ISSUE TITLE
How to re-scale Shapley values to the original dataset magnitude?

### ISSUE THREAD

**Issue by ghbacct** [shap/shap#1033]
### Question
If I've used a `MinMaxScaler` to normalize my target variable between `[-1, 1]`.  

How can I re-scale the Shapley values, so that their magnitude is proportional to that of the target variable `y` in the unscaled dataset?

### Motivation
Naively using `inverse_transform` on the `shap_values[0]` matrix does not work, since if I understand correctly the Shapley values represent a change in `y_i`, due to the value of `X_ij`.

However the fact that she Shapley values are scaled to a different range than the target variable makes interpreting them non trivial, especially when looking at the absolute impact of a feature in a `dependence_plot` or a `force_plot`.
 
### For reference
The Shapley values were generated using a `KernelExplainer` on an MLP Regression problem. Scaling of both the independent variables and target variable is generally considered necessary for `MLP Regressors` to converge.

**Comment by slundberg** [comment]
MinMaxScaler is just a linear transformation of the output value, so you can apply the inverse of that transform to the SHAP values and the expected_value to get what you want. (the SHAP values units are the units of the model output you are explaining)

**Comment by ghbacct** [comment]
Thank you @slundberg, much appreciated!

Is there a way to handle this issue generically? 
Ex. when scaling the target variable using a `StandardScaler`?

**Comment by slundberg** [comment]
I would think that just calling inverse_transform on the shap_values should always work (just remember to also call it on the expected_value). This should always work if the transformation is linear, however if the transformation is not linear then it gets way more complicated, and you have to use DeepExplainer or do something special (like just explain the untransformed model output).

**Comment by Lihi-Gur-Arie** [comment]
@slundberg, I manage to inverse transform shap values with x_scaler.inverse_transform(shap_values) , but how should i scale back the expected_value?

**Comment by derHeinzer** [comment]
> MinMaxScaler is just a linear transformation of the output value, so you can apply the inverse of that transform to the SHAP values and the expected_value to get what you want. (the SHAP values units are the units of the model output you are explaining)

@slundberg Are you sure about that? I have been thinking the shap values describe the impact of a feature (value) on the prediction. Hence a value of 0 means "no impact at all". On the other hand inverse transforming a value of 0 (with the default min max scaler feature range of (0,1)) leads to the smallest fitted value which can be anything. The way I see it, inverse transforming a shap value of 0 should yield 0 as well.
An other case are negative shap values, which may be valid even if the target variable is min max scaled with feature range (0,1). Inverse transforming negative values with such a scaler, is not reasonable imho.

**Comment by derHeinzer** [comment]
an appropriate way would be to devide by the scale_-attribute of the transformer object to rescale the shap values to the original order of magnitude.
