### ISSUE TITLE
Installation error in virtualenv on Linux

### ISSUE THREAD

**Issue by lrdsouza** [shap/shap#1036]
Hi, I'm trying to install the SHAP package in a virtual environment that I use on a computer at my university, but the following error appears:

`Collecting shap
  Using cached shap-0.34.0.tar.gz (264 kB)
Requirement already satisfied: numpy in ./virtual/lib/python3.6/site-packages (from shap) (1.17.3)
Requirement already satisfied: scipy in ./virtual/lib/python3.6/site-packages (from shap) (1.3.1)
Requirement already satisfied: scikit-learn in ./virtual/lib/python3.6/site-packages (from shap) (0.21.3)
Requirement already satisfied: pandas in ./virtual/lib/python3.6/site-packages (from shap) (0.25.3)
Requirement already satisfied: tqdm>4.25.0 in ./virtual/lib/python3.6/site-packages (from shap) (4.36.1)
Requirement already satisfied: joblib>=0.11 in ./virtual/lib/python3.6/site-packages (from scikit-learn->shap) (0.14.0)
Requirement already satisfied: python-dateutil>=2.6.1 in ./virtual/lib/python3.6/site-packages (from pandas->shap) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in ./virtual/lib/python3.6/site-packages (from pandas->shap) (2019.3)
Requirement already satisfied: six>=1.5 in ./virtual/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas->shap) (1.12.0)
Building wheels for collected packages: shap
  Building wheel for shap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/leonardo/virtual/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tzo_jona/shap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tzo_jona/shap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-g05zm_5w
       cwd: /tmp/pip-install-tzo_jona/shap/
  Complete output (71 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/shap
  copying shap/__init__.py -> build/lib.linux-x86_64-3.6/shap
  copying shap/datasets.py -> build/lib.linux-x86_64-3.6/shap
  copying shap/common.py -> build/lib.linux-x86_64-3.6/shap
  creating build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/kernel.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/pytree.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/explainer.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/linear.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/permutation.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/partition.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/gradient.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/tree.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/mimic.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/sampling.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/bruteforce.py -> build/lib.linux-x86_64-3.6/shap/explainers
  creating build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/maple.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/lime.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/coefficent.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/treegain.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/random.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  creating build/lib.linux-x86_64-3.6/shap/explainers/deep
  copying shap/explainers/deep/deep_pytorch.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
  copying shap/explainers/deep/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
  copying shap/explainers/deep/deep_tf.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
  creating build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/waterfall.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/embedding.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/colors.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/summary.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/force.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/force_matplotlib.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/partial_dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/__init__.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/monitoring.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/image.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/decision.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/bar.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/colorconv.py -> build/lib.linux-x86_64-3.6/shap/plots
  creating build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/plots.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/measures.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/__init__.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/experiments.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/methods.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/metrics.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/models.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  creating build/lib.linux-x86_64-3.6/shap/plots/resources
  copying shap/plots/resources/logoSmallGray.png -> build/lib.linux-x86_64-3.6/shap/plots/resources
  copying shap/plots/resources/bundle.js -> build/lib.linux-x86_64-3.6/shap/plots/resources
  copying shap/tree_shap.h -> build/lib.linux-x86_64-3.6/shap
  running build_ext
  numpy.get_include() /home/leonardo/virtual/lib/python3.6/site-packages/numpy/core/include
  building 'shap._cext' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/shap
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/leonardo/virtual/include/python3.6m -I/home/leonardo/virtual/lib/python3.6/site-packages/numpy/core/include -c shap/_cext.cc -o build/temp.linux-x86_64-3.6/shap/_cext.o
  shap/_cext.cc:3:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ERROR: Failed building wheel for shap
  Running setup.py clean for shap
Failed to build shap
Installing collected packages: shap
    Running setup.py install for shap ... error
    ERROR: Command errored out with exit status 1:
     command: /home/leonardo/virtual/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tzo_jona/shap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tzo_jona/shap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-33kyy1ha/install-record.txt --single-version-externally-managed --compile --install-headers /home/leonardo/virtual/include/site/python3.6/shap
         cwd: /tmp/pip-install-tzo_jona/shap/
    Complete output (71 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/shap
    copying shap/__init__.py -> build/lib.linux-x86_64-3.6/shap
    copying shap/datasets.py -> build/lib.linux-x86_64-3.6/shap
    copying shap/common.py -> build/lib.linux-x86_64-3.6/shap
    creating build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/kernel.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/pytree.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/explainer.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/linear.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/permutation.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/partition.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/gradient.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/tree.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/mimic.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/sampling.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/bruteforce.py -> build/lib.linux-x86_64-3.6/shap/explainers
    creating build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/maple.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/lime.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/coefficent.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/treegain.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/random.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    creating build/lib.linux-x86_64-3.6/shap/explainers/deep
    copying shap/explainers/deep/deep_pytorch.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
    copying shap/explainers/deep/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
    copying shap/explainers/deep/deep_tf.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
    creating build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/waterfall.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/embedding.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/colors.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/summary.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/force.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/force_matplotlib.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/partial_dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/__init__.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/monitoring.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/image.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/decision.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/bar.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/colorconv.py -> build/lib.linux-x86_64-3.6/shap/plots
    creating build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/plots.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/measures.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/__init__.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/experiments.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/methods.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/metrics.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/models.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    creating build/lib.linux-x86_64-3.6/shap/plots/resources
    copying shap/plots/resources/logoSmallGray.png -> build/lib.linux-x86_64-3.6/shap/plots/resources
    copying shap/plots/resources/bundle.js -> build/lib.linux-x86_64-3.6/shap/plots/resources
    copying shap/tree_shap.h -> build/lib.linux-x86_64-3.6/shap
    running build_ext
    numpy.get_include() /home/leonardo/virtual/lib/python3.6/site-packages/numpy/core/include
    building 'shap._cext' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/shap
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/leonardo/virtual/include/python3.6m -I/home/leonardo/virtual/lib/python3.6/site-packages/numpy/core/include -c shap/_cext.cc -o build/temp.linux-x86_64-3.6/shap/_cext.o
    shap/_cext.cc:3:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/leonardo/virtual/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tzo_jona/shap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tzo_jona/shap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-33kyy1ha/install-record.txt --single-version-externally-managed --compile --install-headers /home/leonardo/virtual/include/site/python3.6/shap Check the logs for full command output.`

Grateful for the help

**Comment by Karen0103** [comment]
Hi, I came across the same issue. How did you solve it?
Thanks!

**Comment by lrdsouza** [comment]
Hi Karen,
Unfortunately I had to contact the server administrator to install the `python-dev` package, as this package contains the header files you need to create python extensions.
If you have administrator permissions then `sudo apt-get install python-dev` or `sudo apt-get install python3-dev`.

**Comment by Karen0103** [comment]
Thank you for your quick response. It solves the problem. 
Appreciate it. @lrdsouza

**Comment by vaibhavkumar049** [comment]
Hi @lrdsouza , I tried installing python3-dev but I am still getting this error Is there any other reason for that?

**Comment by vaibhavkumar049** [comment]
Collecting shap
  Using cached https://files.pythonhosted.org/packages/a8/77/b504e43e21a2ba543a1ac4696718beb500cfa708af2fb57cb54ce299045c/shap-0.35.0.tar.gz
Requirement already satisfied: numpy in ./env/lib/python3.6/site-packages (from shap)
Requirement already satisfied: pandas in ./env/lib/python3.6/site-packages (from shap)
Requirement already satisfied: scikit-learn in ./env/lib/python3.6/site-packages (from shap)
Requirement already satisfied: scipy in ./env/lib/python3.6/site-packages (from shap)
Requirement already satisfied: tqdm>4.25.0 in ./env/lib/python3.6/site-packages (from shap)
Requirement already satisfied: python-dateutil>=2.6.1 in ./env/lib/python3.6/site-packages (from pandas->shap)
Requirement already satisfied: pytz>=2017.2 in ./env/lib/python3.6/site-packages (from pandas->shap)
Requirement already satisfied: joblib>=0.11 in ./env/lib/python3.6/site-packages (from scikit-learn->shap)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas->shap)
Building wheels for collected packages: shap
  Running setup.py bdist_wheel for shap ... error
  Complete output from command /home/surd-tech/MyCode/RIAttrition/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kqoy2oxv/shap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqb0cyrhcpip-wheel- --python-tag cp36:
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/shap
  copying shap/__init__.py -> build/lib.linux-x86_64-3.6/shap
  copying shap/common.py -> build/lib.linux-x86_64-3.6/shap
  copying shap/datasets.py -> build/lib.linux-x86_64-3.6/shap
  creating build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/sampling.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/kernel.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/additive.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/partition.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/linear.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/mimic.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/tf_utils.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/tree.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/pytree.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/explainer.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/permutation.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/bruteforce.py -> build/lib.linux-x86_64-3.6/shap/explainers
  copying shap/explainers/gradient.py -> build/lib.linux-x86_64-3.6/shap/explainers
  creating build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/treegain.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/maple.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/coefficent.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/random.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  copying shap/explainers/other/lime.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
  creating build/lib.linux-x86_64-3.6/shap/explainers/deep
  copying shap/explainers/deep/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
  copying shap/explainers/deep/deep_tf.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
  copying shap/explainers/deep/deep_pytorch.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
  creating build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/colors.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/__init__.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/force.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/colorconv.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/embedding.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/image.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/text.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/bar.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/force_matplotlib.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/monitoring.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/summary.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/waterfall.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/partial_dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
  copying shap/plots/decision.py -> build/lib.linux-x86_64-3.6/shap/plots
  creating build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/experiments.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/__init__.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/measures.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/models.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/metrics.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/methods.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  copying shap/benchmark/plots.py -> build/lib.linux-x86_64-3.6/shap/benchmark
  creating build/lib.linux-x86_64-3.6/shap/plots/resources
  copying shap/plots/resources/logoSmallGray.png -> build/lib.linux-x86_64-3.6/shap/plots/resources
  copying shap/plots/resources/bundle.js -> build/lib.linux-x86_64-3.6/shap/plots/resources
  copying shap/tree_shap.h -> build/lib.linux-x86_64-3.6/shap
  running build_ext
  numpy.get_include() /home/surd-tech/MyCode/RIAttrition/env/lib/python3.6/site-packages/numpy/core/include
  building 'shap._cext' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/shap
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/surd-tech/MyCode/RIAttrition/env/include -I/usr/include/python3.6m -I/home/surd-tech/MyCode/RIAttrition/env/lib/python3.6/site-packages/numpy/core/include -c shap/_cext.cc -o build/temp.linux-x86_64-3.6/shap/_cext.o
  x86_64-linux-gnu-gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for shap
  Running setup.py clean for shap
Failed to build shap
Installing collected packages: shap
  Running setup.py install for shap ... error
    Complete output from command /home/surd-tech/MyCode/RIAttrition/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kqoy2oxv/shap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0rm_0csp-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/surd-tech/MyCode/RIAttrition/env/include/site/python3.6/shap:
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/shap
    copying shap/__init__.py -> build/lib.linux-x86_64-3.6/shap
    copying shap/common.py -> build/lib.linux-x86_64-3.6/shap
    copying shap/datasets.py -> build/lib.linux-x86_64-3.6/shap
    creating build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/sampling.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/kernel.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/additive.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/partition.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/linear.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/mimic.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/tf_utils.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/tree.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/pytree.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/explainer.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/permutation.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/bruteforce.py -> build/lib.linux-x86_64-3.6/shap/explainers
    copying shap/explainers/gradient.py -> build/lib.linux-x86_64-3.6/shap/explainers
    creating build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/treegain.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/maple.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/coefficent.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/random.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    copying shap/explainers/other/lime.py -> build/lib.linux-x86_64-3.6/shap/explainers/other
    creating build/lib.linux-x86_64-3.6/shap/explainers/deep
    copying shap/explainers/deep/__init__.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
    copying shap/explainers/deep/deep_tf.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
    copying shap/explainers/deep/deep_pytorch.py -> build/lib.linux-x86_64-3.6/shap/explainers/deep
    creating build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/colors.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/__init__.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/force.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/colorconv.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/embedding.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/image.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/text.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/bar.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/force_matplotlib.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/monitoring.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/summary.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/waterfall.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/partial_dependence.py -> build/lib.linux-x86_64-3.6/shap/plots
    copying shap/plots/decision.py -> build/lib.linux-x86_64-3.6/shap/plots
    creating build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/experiments.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/__init__.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/measures.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/models.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/metrics.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/methods.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    copying shap/benchmark/plots.py -> build/lib.linux-x86_64-3.6/shap/benchmark
    creating build/lib.linux-x86_64-3.6/shap/plots/resources
    copying shap/plots/resources/logoSmallGray.png -> build/lib.linux-x86_64-3.6/shap/plots/resources
    copying shap/plots/resources/bundle.js -> build/lib.linux-x86_64-3.6/shap/plots/resources
    copying shap/tree_shap.h -> build/lib.linux-x86_64-3.6/shap
    running build_ext
    numpy.get_include() /home/surd-tech/MyCode/RIAttrition/env/lib/python3.6/site-packages/numpy/core/include
    building 'shap._cext' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/shap
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/surd-tech/MyCode/RIAttrition/env/include -I/usr/include/python3.6m -I/home/surd-tech/MyCode/RIAttrition/env/lib/python3.6/site-packages/numpy/core/include -c shap/_cext.cc -o build/temp.linux-x86_64-3.6/shap/_cext.o
    x86_64-linux-gnu-gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/surd-tech/MyCode/RIAttrition/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kqoy2oxv/shap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0rm_0csp-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/surd-tech/MyCode/RIAttrition/env/include/site/python3.6/shap" failed with error code 1 in /tmp/pip-build-kqoy2oxv/shap/

**Comment by lrdsouza** [comment]
@vaibhavkumar049 
Hi, Vaibhav! It seems that your problem is related to the GNU Compiler Collection (gcc). I am not sure what it is, it may be that some file is corrupted.
Please, try this:
`sudo apt update`
`sudo apt upgrade`
`sudo apt install gcc python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev g++`
Source: [gcc: error trying to exec 'cc1plus': execvp: No such file or directory](https://stackoverflow.com/questions/39455741/gcc-error-trying-to-exec-cc1plus-execvp-no-such-file-or-directory/46856024)

**Comment by vaibhavkumar049** [comment]
@lrdsouza thanks for your quick response , I needed to install g++
