### ISSUE TITLE
"IndexError: list index out of range"

### ISSUE THREAD

**Issue by okunahe** [shap/shap#1038]
I have a problem with "IndexError: list index out of range" by running of this line with shap-0.34.0 :
explainer = shap.DeepExplainer(model, padded_docs_train)

Here is the full error message:

IndexError Traceback (most recent call last)
in ()
1 import shap
2
----> 3 explainer = shap.DeepExplainer(model, padded_docs_train)
4
5 num_explanations = 25

/home/olya/env/lib64/python3.7/site-packages/shap/explainers/deep/init.py in init(self, model, data, session, learning_phase_flags)
78
79 if framework == 'tensorflow':
---> 80 self.explainer = TFDeepExplainer(model, data, session, learning_phase_flags)
81 elif framework == 'pytorch':
82 self.explainer = PyTorchDeepExplainer(model, data)

/home/olya/env/lib64/python3.7/site-packages/shap/explainers/deep/deep_tf.py in init(self, model, data, session, learning_phase_flags)
79 if str(type(model)).endswith("keras.engine.sequential.Sequential'>"):
80 self.model_inputs = model.inputs
---> 81 self.model_output = model.layers[-1].output
82 elif str(type(model)).endswith("keras.models.Sequential'>"):
83 self.model_inputs = model.inputs

IndexError: list index out of range

Do you have any idea, why I'm getting this error or how could I solve this problem ?

**Comment by sky1122** [comment]
I have same problem!! If you fix the problem please tell me! thanks a lot

**Comment by JichenGuo** [comment]
same problem! If you fix it, please tell me! Thank you very much in advance!!

**Comment by thatlittleboy** [comment]
I'm closing this issue as non-reproducible for now

For anyone else facing this issue, please raise a new GH issue, and please provide a **Minimal working reproducible example** that demonstrates the problem clearly.
