### ISSUE TITLE
Plot not displaying in jupyter notebook

### ISSUE THREAD

**Issue by ritviksahajpal** [shap/shap#104]
Thanks for a great package! I had a query about when I tried running one of the sample scripts by creating a new jupyter notebook in PyCharm. When I run the code, it does not display any plot. Any ideas on what might be going wrong? I am using python 3.6 and latest shap.

![image](https://user-images.githubusercontent.com/2277375/40700386-4b0a2914-63a7-11e8-9fb3-d6c0c95c2e90.png)

**Comment by slundberg** [comment]
My best guess is that PyCharm does not support javascript output (https://youtrack.jetbrains.com/issue/PY-14534). You could try using the dependence_plot and summary_plot since they don't rely on javascript.

**Comment by ritviksahajpal** [comment]
thanks @slundberg this is helpful.
