### ISSUE TITLE
NPM module for shap visualizations

### ISSUE THREAD

**Issue by SachinVarghese** [shap/shap#1040]
@slundberg Thanks for this awesome library and the work you are doing on model explanations. It has been hugely insightful for the community.

I would like to use some of the visualizations that you have created in react, in a separate javascript project and hence would like to know if these visualizations are in the npm registry as a module.

If not, I am happy to contribute towards **publishing this to an npm module** so that 
- more developers benefit from your work 
- repo gets more traction and contributions to the visualizations

**Comment by rooom13** [comment]
Any updates on its current status?

**Comment by SachinVarghese** [comment]
Hey @rooom13, I haven't received any response on this, unfortunately. But I do see a lot of interest in this. May I ask what your use case is with this requirement. Hopefully, we can work towards a common solution.

**Comment by rooom13** [comment]
Hi @SachinVarghese My use case was to use the the module as a chart component. E.g, in React just import it like `import AdditiveForceExplainer from "shap"` and use it as a component passing props.

Actually using the component from [here](https://github.com/slundberg/shap/blob/master/javascript/visualizers/AdditiveForceVisualizer.jsx) does the workaround

**Comment by slundberg** [comment]
Hey sorry I have been out sick for month. I would happy if you want to make this into a npm. I have not release an npm module...but would the format fit well inside the SHAP git repo?

**Comment by SachinVarghese** [comment]
Hi, @slundberg Hope you are well now. 
So the idea is that these three imports [here](https://github.com/slundberg/shap/blob/master/javascript/index.jsx#L4) come from an npm module.
```
import SimpleListVisualizer from './visualizers/SimpleListVisualizer';
import AdditiveForceVisualizer from './visualizers/AdditiveForceVisualizer';
import AdditiveForceArrayVisualizer from './visualizers/AdditiveForceArrayVisualizer';
```

 And they could be a separate folder as an npm package within this repo maintained here. I am happy to submit a PR to show how this could be utilized both by notebooks in this repo and external projects. Let me know your thoughts.

**Comment by slundberg** [comment]
That would be great, thanks!

**Comment by peterpoliwoda** [comment]
Hey guys, speaking of utilisations, how would one show a those plots in a react front-end using this npm package? I've got the explainability plots showing up in the notebook and can get the shap values generated in the python backend. I'd like to show a force plot on the front-end now, is there any example somewhere I could find to get this working? 
Would passing the shapvalues to the AdditiveForceVisualizer create a plot component on the front-end?

**Comment by SachinVarghese** [comment]
Yeah, pass the shap values as props to the `AdditiveForceVisualizer` react component. See the component props for details.

```jsx
import { AdditiveForceVisualizer } from "shapjs";

export default function App() {
  const shapProps = {}; //Provide shap props here
  return  <AdditiveForceVisualizer {...shapProps} />;
}
```
Also will close the issue now since the relevant PR #1147 is merged.
