### ISSUE TITLE
dependence plot with interaction values not working

### ISSUE THREAD

**Issue by cmottac** [shap/shap#1050]
Dear all,
I am trying to create a dependence plot with the shap_interaction_values. This doesn't seem to work.
For instance, cell 10 in this [example notebook](https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Fitting%20a%20Linear%20Simulation%20with%20XGBoost.ipynb) produces an error:
> IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2500,) (2,)

Could you please help me on that?
Thank you in advance,
Carlo

**Comment by j-schneider** [comment]
Was having the same issue, but including: interaction_index=None solved it:
`shap.dependence_plot((8,1), shap_interaction_values, X_test,interaction_index=None)`

**Comment by cmottac** [comment]
@j-schneider thank you so much. This solves my issue.
However, I believe that this should be made explicit in the code, to prevent others to fall in the same problem. @slundberg if I can contribute to this, please let me know.
