### ISSUE TITLE
PyTorch DeepExplainer, RNNs, and Element-Wise Multiplication

### ISSUE THREAD

**Issue by u500** [shap/shap#1057]
Two issues, they could be related:

1. If I use an RNN-based module in my model, the following error comes up when trying to compute shap values: "RuntimeError: cudnn RNN backward can only be called in training mode".

2. Assuming I replace the RNN above with a CNN, if I perform element-wise multiplication (for example, a simple attention mechanism for classification), the resulting shap values fail their additivity check (diffs > 1e-2, sometimes much larger).

Simple example:

x: (batchsize, timesteps, in_dim)

```conv = nn.Conv1d(in_dim, out_dim, kernel_size=1)    # kernel_size of 1 just for illustration
W = nn.Linear(out_dim, 1)
output = nn.Linear(out_dim, 1)

h = conv(x.transpose(-1, -2)).transpose(-1, -2)    #  (batchsize, timesteps, out_dim)
a = W(h)    #  (batchsize, timesteps, 1)
a = F.softmax(a, dim=1)    #  Issue still arises when excluding this line
```

This fails (shap values incorrect, diffs > 1e-2):

```
c = (h * a).sum(dim=1)
y = output(c)
```

This works, but is not helpful (shap sum correct, diffs < 1e-7):

```
c = (h + a).sum(dim=1)
y = output(c)
```

I'm just wondering if I'm missing something basic since this seems pretty straightforward. I don't think a more involved full working example is required since it seems like I might not be understanding something fundamental about how DeepExplainer is operating, but I would be happy to provide one if necessary.

Thank you.

**Comment by gabrieltseng** [comment]
Hi!

In general, the DeepExplainer checks for modules to figure out how a gradient should be calculated (so `F.softmax` won't work, but `nn.Softmax` would).

However, it's not immediately obvious to me why it still doesn't work with that line commented out. Could you send a more complete example?

Also, how are you running the additivity checks?

Thanks!

**Comment by AlkaSaliss** [comment]
I had the same error using RNN based model, but moving the model and data to CPU fixed the error in my case

**Comment by isaacmg** [comment]
I'm having a similar problem. Shap doesn't seem to work with a LSTM/GRU when on the GPU.

**Comment by leckie-chn** [comment]
From [this thread](https://discuss.pytorch.org/t/cudnn-rnn-backward-can-only-be-called-in-training-mode/37622) we know that on GPU the model needs to set itself into training mode with `model.train()` after `model.eval()`.

But in the code https://github.com/slundberg/shap/blob/e8a5d2c31e1aab45d4e0fbb69e68f0cde46a3503/shap/explainers/_gradient.py#L384 shap manually set `model.eval()` @gabrieltseng any reasons why setting model in evaluation mode here?

**Comment by gabrieltseng** [comment]
Hi @leckie-chn - DeepLIFT measures the effect of the inputs on model predictions. Some layers (dropout, batchnorm) behave differently in training time and inference time, so the calculated shap values would not reflect the model predictions at inference time if the shap values are calculated with the model in training mode.

This being said, if the model doesn't have any layers which behave differently at train and inference time then it would be safe to remove this line.

**Comment by Zihengmax** [comment]
I faced the same error using RNN based model, is there any possibility to RNN on GPUbesides moving the model and data to CPU
