### ISSUE TITLE
TFDeepExplainer not working with 1-layer NN + Softmax

### ISSUE THREAD

**Issue by Zahlii** [shap/shap#1059]
Using TF 2.1.0  + SHAP ~HEAD

Minimum failing example:

```python

import pandas as pd
import numpy as np
import tensorflow as tf
from shap import DeepExplainer

x = pd.DataFrame(
    {
        "B": np.random.random(size=(100,)),
    }
)
y = x.B
y = y.map(lambda zz: chr(int(zz * 2 + 65))).str.get_dummies()

d = tf.keras.models.Sequential()
d.add(tf.keras.layers.Dense(y.shape[1], input_shape=(x.shape[1],), activation="softmax"))
d.summary()
d.compile(loss="categorical_crossentropy", optimizer="Adam")
d.fit(x.values, y.values, epochs=2)

e = DeepExplainer(d, x.values)
print(e.shap_values(x.values))
```

    /usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py:236 grad_graph  *
        x_grad = tape.gradient(out, shap_rAnD)
    /usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py:1029 gradient
        unconnected_gradients=unconnected_gradients)
    /usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/imperative_grad.py:77 imperative_grad
        compat.as_str(unconnected_gradients.value))
    /usr/local/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py:141 _gradient_function
        return grad_fn(mock_op, *out_grads)
    /usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py:352 custom_grad
        return op_handlers[op.type](self, op, *grads)
    /usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py:449 softmax
        in0 = op.inputs[0]

    TypeError: 'NoneType' object is not subscriptable

It indeed seems the op's input is None.
However, I couldn't find out yet at which point it is set to None.

**Comment by Zahlii** [comment]
I verified that all inputs are not None before calling `x_grad = tape.gradient(out, shap_rAnD)`. Inside this function, somewhere the inputs are lost. Note that this also happens when we define Softmax() as an extra layer.

**Comment by slundberg** [comment]
Thanks! It turned out to be because in TF 2.1 they stopped providing the `inputs` parameter to gradient operators for lots of built-in functions whose default gradient methods don't need them. That's a problem for us since we do need them. I was finally able to get around it by carefully changing the name of the operators before the c++ check is done to strip unneeded inputs. I will push a fix as soon as I think it is stable

**Comment by Zahlii** [comment]
Hi, 
Just a small comment - I re-tested it with TF2.0.1, and I'm still seeing the same issue, so I guess this was changed pre-2.1 already.
Seems like here? https://github.com/tensorflow/tensorflow/commit/b4224fe34ec994846ce3166d9735c8036e9dfc4e

**Comment by slundberg** [comment]
I pushed a fix to master that should address this: https://github.com/slundberg/shap/commit/9df1fde942b6a0536f297826cfa221a756d66b2a (it fixes the problem on my machine) Thanks again for noting this with a nice simple example!
