### ISSUE TITLE
Shape Mismatch in Image_Plot Function for GradientExplainer Example

### ISSUE THREAD

**Issue by gokhanozbulak** [shap/shap#1060]
In regards of 'GradientExplainer example Vgg16' in [1], I have confused about shape mismatch for 'image_plot' function. Although it's stated in [2] that shapes of both shap values and image tensor should match, it's not the case for the example. Could anybody spot a light if I miss something, please?

[1] https://github.com/slundberg/shap
[2] https://github.com/slundberg/shap/blob/master/shap/plots/image.py

**Comment by slundberg** [comment]
It is because in that example we are explaining an internal layer of the network that has already been downsampled. So the "inputs" that are explained are internal nodes.

**Comment by gokhanozbulak** [comment]
When I do a shape checking as below, I see different shapes for 'shap_values' and 'to_explain':

print(np.array(shap_values).shape, to_explain.shape)
shap.image_plot(shap_values, to_explain, index_names)

The print output is as follows:

((2, 2, 56, 56, 128), (2, 224, 224, 3))

I was expecting the first shape to be same as the second one. In other words, what I expect to see:

shap_values: (2,2,224,224,3)
to_explain: (2,224,224,3)

According to the descriptive comment of image_plot function, both shap_values and to_explain variables should have same shape:

Parameters
    ----------
    shap_values : [numpy.array]
        List of arrays of SHAP values. Each array has the shap (# samples x width x height x channels), and the
        length of the list is equal to the number of model outputs that are being explained.
    pixel_values : numpy.array
        Matrix of pixel values (# samples x width x height x channels) for each image. It should be the same
        shape as each array in the shap_values list of arrays.

I'm missing something but couldn't figure out.
