### ISSUE TITLE
What exactly is shapley value in SHAP method?

### ISSUE THREAD

**Issue by vaishkiva** [shap/shap#1064]
Hi @slundberg 
I see that in the SHAP method there is a Shapley value calculated for every feature in every row. What exactly is this Shapley value? When I have say 0.03 as Shapley value for one feature and -0.07 for other what exactly this 0.03 and -0.07 signify and how is it calculated?

Can these Shapley values be used to calculate percentage contribution of feature towards final prediction?

Please help me out!

**Comment by vaishkiva** [comment]
@slundberg 
Can you give me some clarity on this? Why some shapley values are negative and others positive?

**Comment by jacekblaz** [comment]
It depends on expleiner and arguments. Post snippet of code that produce this output. If you want to you can also read:

- [A Guide for Making Black Box Models Explainable by Molnar](https://christophm.github.io/interpretable-ml-book/shap.html)

- [Documentation](https://shap.readthedocs.io/en/latest/)

- [Explainable AI for Trees: From Local Explanations to Global
Understanding by Lundberg et al.](https://arxiv.org/pdf/1905.04610.pdf)

**Comment by detrin** [comment]
@thatlittleboy Candidate for closing I think.

**Comment by dsgibbons** [comment]
@detrin agreed. This is not an issue and should be closed.
