### ISSUE TITLE
When can we use Sampling explainer?

### ISSUE THREAD

**Issue by vaishkiva** [shap/shap#1065]
Hi @slundberg 

when can I use a sampling explainer. Is it possible to use a Sampling explainer for random forest and other tree-based models?

What does the Sampling explainer actually do?

**Comment by slundberg** [comment]
SamplingExplainer works for any python function so yes. It estimates SHAP values by sampling random permutations of the features. Like kernel explainer it gets more accurate when you have more samples. It converges with enough samples to the same final values as KernelExplainer (or TreeExplainer) but comes with different computational trade offs.

**Comment by vaishkiva** [comment]
@slundberg 
In that case if i have to use SHAP for some medical data, and use SamplingExplainer with 1000 samples out of 40000 records, wont I get incorrect results. And my shap is taking almost 2 hours for 1000 samples out of 40000 records. 

And does Sampling explainer use 1000 samples to predict shap values for rest of records?

**Comment by slundberg** [comment]
SamplingExplainer can be slow. But if you are using 1000 samples that will be for each of the 40000 records, which means 1000 * 40000 samples. How many samples you need per record depends on how many features are in your model. The best way to test this is see how close an explanation with 1000 samples is to one with 10000 samples. If it is always close then you are good with 1000 samples.

**Comment by vaishkiva** [comment]
Thanks @slundberg for the explanation 
So I have to use shap.sample(X, 1000) and shap.sample(X, 10000) and see which one gives closer results. And for this I need to run the one with original sample i.e., 40000 samples and see the results for comparison right?
