### ISSUE TITLE
ValueError: Operation 'switched_dropout_3/dropout/mul_1' has no attr named '_XlaCompile'.

### ISSUE THREAD

**Issue by tobiasharren** [shap/shap#1077]
Hello,

I am having a bit of trouble with both the DeepExplainer and the GradientExplainer. I think I know roughly what the problem is, but I can't seem to find out how to fix it.

I use a MultitaskRegressor Model from Deepchem (based on Keras), which consists of the following layers:
[<tensorflow.python.keras.engine.input_layer.InputLayer object at 0x7efc92f7fb38>, <tensorflow.python.keras.layers.core.Dense object at 0x7efc92f7f390>, <tensorflow.python.keras.engine.input_layer.InputLayer object at 0x7efcd66d9908>, <deepchem.models.layers.SwitchedDropout object at 0x7efc92f7ff28>, <tensorflow.python.keras.layers.core.Dense object at 0x7efc92f340f0>, <deepchem.models.layers.SwitchedDropout object at 0x7efc92f440b8>, <tensorflow.python.keras.layers.core.Dense object at 0x7efc92efdb70>, <deepchem.models.layers.SwitchedDropout object at 0x7efc92f44438>, <tensorflow.python.keras.layers.core.Dense object at 0x7efc92ede9b0>, <deepchem.models.layers.SwitchedDropout object at 0x7efc92f44da0>, <tensorflow.python.keras.layers.core.Dense object at 0x7efc92e81a58>, <tensorflow.python.keras.layers.core.Reshape object at 0x7efc92f7fdd8>]

I added a new reshape layer on top, so the output has only one dimension (I only have one output, so thats ok)
I also checked that my inputs have the right format, so the call to session.run in deep_tf will be correctly executed and returns the expected values

output = tf.reshape(self.model.model.output, [-1, 1])

(the strange notations are due to deepchems and my classes)

The problem lies probably with this SwitchedDropout Layer.
The Deepchem Definition is: 

class SwitchedDropout(tf.keras.layers.Layer):
  """Apply dropout based on an input.

  This is required for uncertainty prediction.  The standard Keras Dropout
  layer only performs dropout during training, but we sometimes need to do it
  during prediction.  The second input to this layer should be a scalar equal to
  0 or 1, indicating whether to perform dropout.
  """

  def __init__(self, rate, **kwargs):
    self.rate = rate
    super(SwitchedDropout, self).__init__(**kwargs)

  def call(self, inputs):
    rate = self.rate * tf.squeeze(inputs[1])
    return tf.nn.dropout(inputs[0], rate=rate)

I can build the DeepExplainer/GradientExplainer without issue, but when I try to get the shap values I get the following error message:

  File "/EXT/Tobha/.conda/envs/test_BA_Tobias_std_deepchem-2-3-0_py36_20200114/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2639, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'switched_dropout_3/dropout/mul_1' has no attr named '_XlaCompile'

As far as I have understood dropout layers should not be used in shap, since they are only used for training. But since this layer was written to explicitly also be used in prediction this probably leads to the problems. 
Are there any ideas on how I can bypass this?

I use tensorflow 1.14 and the newest shap version from conda with python 3.6

Thanks in advance for any help.

best regard Tobias

**Comment by krkaufma** [comment]
I am also using tensorflow 1.14 and the newest shap version from conda with python 3.6.8. I am using DeepExplainer on an Xception CNN.

Same error when trying to get the shap_values. 

One example error: InvalidArgumentError: Operation 'predictions_1/Softmax' has no attr named '_XlaCompile'.
