### ISSUE TITLE
ImportError: assert_import

### ISSUE THREAD

**Issue by shamitb** [shap/shap#1078]
I did 
!pip install git+https://github.com/slundberg/shap.git 
from Jupyter
Then I get an error on 
import shap
/anaconda/envs/azureml_py36/lib/python3.6/site-packages/shap/__init__.py in <module>
     12 from .explainers.gradient import GradientExplainer
     13 from .explainers.linear import LinearExplainer
---> 14 from .explainers.partition import PartitionExplainer, TokenMasker, ImageMasker
     15 from .explainers.bruteforce import BruteForceExplainer
     16 from .explainers.permutation import PermutationExplainer

/anaconda/envs/azureml_py36/lib/python3.6/site-packages/shap/explainers/partition.py in <module>
      6 from tqdm.auto import tqdm
      7 import queue
----> 8 from ..common import assert_import, record_import_error, safe_isinstance
      9 
     10 try:

ImportError: cannot import name 'assert_import'

**Comment by ibuda** [comment]
I did same thing as you did, but could not reproduce your error.
However, maybe installing from git repo is not the way to do it?
Did you try the default install methods?
