### ISSUE TITLE
Using External Datasets with SHAP?

### ISSUE THREAD

**Issue by andymancodes** [shap/shap#108]
Hi,

I am a bit confused about using SHAP. I have  a dataset, with X and y (a regression problem). X has 8-10 features. I see that before using shap,

*shap.dataset is done.  --> does shap link with the dataset here?

How could I use shap with my own dataset?

Sorry if this seems too naive.

**Comment by slundberg** [comment]
SHAP is designed to explain the predictions of an ML model you have trained. What type of model are you using?

**Comment by andymancodes** [comment]
@slundberg thanks for the reply, I am using a regression model..

**Comment by slundberg** [comment]
Oh I think get your question now. shap.datasets just has a few example data sets. To use your own data just the load your feature matrix as a numpy array or pandas data frame, and your labels as a numpy array. In all the examples X is the feature matrix and y is the label vector.
