### ISSUE TITLE
No output from shap.force_plot()

### ISSUE THREAD

**Issue by RohinMahesh** [shap/shap#1080]
I am not getting any output from force_plot. Here is my code:

explainer = shap.TreeExplainer(cboost)
shap_values = explainer.shap_values(X_test)

shap.initjs()
shap.force_plot(explainer, shap_values, X_test)

**Comment by ibuda** [comment]
Please provide the shap version and the dataset so we could reproduce your issue. Thank you.

**Comment by ArpitSisodia** [comment]
check shap values, chances are all of them are 0. u will not get any plot then.
