### ISSUE TITLE
Model Type not yet supported by TreeExplainer

### ISSUE THREAD

**Issue by Dola47** [shap/shap#1084]
Hi All,

I am working on a machine learning framework, where we internally have our xgboost model, we use the functions of the xgboost to train our model internally in our framework and so on.

I tried to use our model in shap.TreeExplainer, but I think shap explainer is expecting only to have xgboost as a model not our framework model, and I do not want to instantiate a model in jupyter notebook for example, but I want to call our model and explain it. So, is there is anyway to submit our model to be explained by shap because at the end of the day it is acutally an xgboost model.
![Capture](https://user-images.githubusercontent.com/45386621/75880032-cd056700-5e1c-11ea-8281-fe69c894a111.PNG)

**Comment by stephenpardy** [comment]
Does your internal framework have a way to get the underlying booster object? E.g. something like `.get_booster()`? If so you could pass that to TreeExplainer.

**Comment by Dola47** [comment]
It has but it is the worst solution because I have to define a specific route for the Xgboost to be convenient with SHAP. I was just asking if there is another way to overcome this issue, such that I can submit the model normally in its current implementation as in LIME.

**Comment by alexcoca** [comment]
Hi @Dola47 ,

I guess that the only route into this would be to carefully check what the `TreeEnsamble` in `tree.py` class needs in order to produce a correct representation of your model. On the surface of it, it seems that `model` could be a dictionary, which could contain the data from your model that will be used to create the internal representation of the tree. I'm not sure if it's any easier for you to access the model state and construct the representation as opposed to simply getting the booster. You'd have to carefully check that the tree representation created from your dictionary is correct. 

On a more general note, `xgboost` library itself implements the path-dependent feature perturbation algorithm (basically what you run if you instantiate your explainer as `TreeExplainer(mymodel)` which is optimised using Open MP (so distributes explanations). If it's any easier, you could call `.predict(X_explain, pred_contribs=True)` on the xgboost model and get the explanations that way. 

I hope this helps.

**Comment by Dola47** [comment]
@alexcoca Thanks a lot for your response. Can you provide more clarification regarding the last point you mentioned. If I can use directly the .predict function out of SHAP on my model. What is the difference then between calling the TreeExplainer on my model and not calling it. I mean what I going to lose out of the normal procedure of SHAP, if I directly called the .predict function on my model

**Comment by alexcoca** [comment]
Hi @Dola47 ,

What I mean is that  assuming `model` is an `xgboost` model, the following will give you the same result. That is, 

```python 
shap_output = model.predict(X, predict_contribs=True)
shap_values = shap_output[:, :-1]
expected_value = shap_output[0, -1]
```

will give exactly the same result as 

```python 
from shap import TreeExplainer
explainer = TreeExplainer(model)
shap_values = explainer.shap_values(X)
expected_value = explainer.expected_value
```

I'm a assuming you have a single-output model (aka that `shap_values` returned by calling the `shap_values` method returns `np.ndarray` not `list`).

**Comment by Dola47** [comment]
@alexcoca  So, what I got that shap_values is returning nothing except the model probabilities of the rows sent to it. And, that the expected_value is nothing excepted accessing these probabilities, and 
I can acquire these values internally from my model and then provide then directly to shap.force_plot?

Am I right?

**Comment by alexcoca** [comment]
I'm struggling to understand what you mean by _shap_values is returning nothing except the model probabilities of the rows sent to it. And, that the expected_value is nothing excepted accessing these probabilities_.

If you trained your objective with the objective `binary:logistic` or `binary:logitraw` than the units of the shap values returned when calling `model.predict(X, predict_contribs=True)` are in the margin space (aka before we apply the transformation to convert to probabilities). Note that all xgboost does when trained with `binary:logistic` is to compute the margin `m` first and then apply `1/1+e(-m)`  to output a probability when you call `model.predict(X)`. So you are likely to notice an expected value that can be any real number, not a number in `[0, 1]` as would be the case if the model probabilities were explained. 

`xgboost` implements an algorithm that can only provide explanations of the raw model output (that is, we explain the leaf value `m`, not the probabilities returned by the model). So what you obtain by making that `.predict` call above is a a set of shap values along with an expected value that statisfy `model_output - expected_value = sum(shap_values)` for every instance. `model_output` is in the leaf output for our instance. So the shap values you obtain with this method have nothing to with the probabilities returned by your model, they explain the inverse logit transformation of those probabilities. 

So by the above I wanted to make clear that the shap values returned do not have probability units, they are in margin space. 

Indeed, we can just take those values and the expected value and do a force plot.

**Comment by Dola47** [comment]
@alexcoca Great, does the same exist if I use the Booster with objective: multi:softprob ?

**Comment by alexcoca** [comment]
I have not dealt with multiclass clasification, so @slundberg might have to confirm that my expectations are correct. I would expect this to also work and that the explanations sum to the logits for each class. I would also expect to get a list of 2D array of shape `(X.shape[0], X.shape[1] +1)` with len equal to the number of output. However, from the `xgoost` docs one finds out that:
s
_pred_contribs (bool) – When this is True the output will be a matrix of size (nsample, nfeats + 1) with each record indicating the feature contributions (SHAP values) for that prediction. The sum of all feature contributions is equal to the raw untransformed margin value of the prediction. Note the final column is the bias term._

So it's not clear if this is supported.  What is the shape of the output you obtain if you call `model.predict(X, predict_contribs=True)` on your multi-output model?

**Comment by Dola47** [comment]
@alexcoca  I got an error when I just used predict_contribs=True

`/mnt/c/ubuntu/envs/usecase/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    462                 mgr = init_dict({data.name: data}, index, columns, dtype=dtype)
    463             else:
--> 464                 mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
    465 
    466         # For data is list-like, or Iterable (will consume into list)

/mnt/c/ubuntu/envs/usecase/lib/python3.6/site-packages/pandas/core/internals/construction.py in init_ndarray(values, index, columns, dtype, copy)
    167     # by definition an array here
    168     # the dtypes will be coerced to a single dtype
--> 169     values = prep_ndarray(values, copy=copy)
    170 
    171     if dtype is not None:

/mnt/c/ubuntu/envs/usecase/lib/python3.6/site-packages/pandas/core/internals/construction.py in prep_ndarray(values, copy)
    293         values = values.reshape((values.shape[0], 1))
    294     elif values.ndim != 2:
--> 295         raise ValueError("Must pass 2-d input")
    296 
    297     return values

ValueError: Must pass 2-d input`

**Comment by alexcoca** [comment]
That stack trace seems to have nothing to do with xgboost or shap.

**Comment by Dola47** [comment]
I have only this error when I make  predict_contribs=True.
I got the results normally after removing the predict_contribs= True.
I get usually 2 column with the probabilities of each class.
Or you think that it should work normally even if I am using softprob, and predict_contribs=True?

**Comment by alexcoca** [comment]
I suggest raising an issue on the xgboost github then. I'm surprised to see pandas errors given xgboost runs in C++ and has nothing to do with pandas. I don't know what context you're running this in, but I presume you might do something to the output of xgboost that causes this error.

**Comment by Dola47** [comment]
@alexcoca  Really thanks a lot for your responses.  I will try to figure out the problem. I might reach you back after solving the current issue. Many thanks.

**Comment by Dola47** [comment]
Hi @alexcoca ,

I think you might try to help me right now. I just got the results out of the booster.predict when I set the predict_contrib to True. It worth noting, that to overcome some errors I have to flatten the results out of model.predict as shown here 
![Capture2](https://user-images.githubusercontent.com/45386621/80627467-3df98180-8a50-11ea-89e5-f7a233c0e84f.PNG)

Moreover, the output is too extremely big it is 19490872 rows and 1 columns, here is the results.
Is that normal?
![Capture](https://user-images.githubusercontent.com/45386621/80627542-697c6c00-8a50-11ea-8353-24efb054c630.PNG)

I do not really understand precisely what these numbers in the current result stands for, but it seems that they are not the normal probabilities of the Booster, because I have a lot of negative numbers. 

Can you now reformat to me the modifications I should do to be able to prepare the results to be submitted to the SHAP plot functions?

**Comment by stephenpardy** [comment]
See alexcoca's [comment](https://github.com/slundberg/shap/issues/1084#issuecomment-618401222) above. When you run:

`shap_output = model.predict(X, predict_contribs=True)`
`shap_values = shap_output[:, :-1]`

You get the SHAP values. `shap_output` is a numpy array that has size of nrowsXncols+1- the extra column is for the average output of the model. 

You can pass `shap_values` from the above lines directly to the SHAP plotting tools, no other flattening or preparations required.

**Comment by Dola47** [comment]
@stephenpardy @alexcoca 

So, I overcame all of the errors I was facing currently.

I just followed your steps the results I got are like that:

shap_output come out to be of shape ( 28166, 2, 346), given that the data submitted to it were of shape (28166, 345). I have now a 2 class classification problem so I do not know if this is correct or it should come out to be of shape (28166, 346)!!. 

NOTE: For this point after the discussion with Philip from XGBoost forum we found out that the result is correct. You might have a look here: [https://discuss.xgboost.ai/t/valueerror-must-pass-2-d-input-when-setting-predict-contribs-to-true/1573/14](url)

A screenshot of the output of shap_output is here:
![Capture](https://user-images.githubusercontent.com/45386621/80645601-aace4500-8a6b-11ea-922a-9c920779c5c2.PNG)

Shap_values come out to be of shape (28166, 345). For only one of the classes. I got the results by applying shap_output [:,0,:-1] A screenshot of the output is here:
![Capture1](https://user-images.githubusercontent.com/45386621/80645709-c9344080-8a6b-11ea-8ca8-7628b4cdae33.PNG)

expected_value come out to be of shape (345). For only one of the classes. However, the expected value for each of the classes should be a single value something is missing in this calculation!! I just get the result by applying shap_output [:,0,-1] A screenshot of the output is here:
![Capture2](https://user-images.githubusercontent.com/45386621/80645802-eec14a00-8a6b-11ea-9cb3-bdbee6b065f1.PNG)

Now, I got the results but in this specific way we are separating the shap_output and shap_values for each class!. How can I submit them to be plotted then and keep the contribution of every feature for each of the classes?

**Comment by Dola47** [comment]
@alexcoca @stephenpardy @slundberg 

1- I still do not know hot to get the expected value correctly in my case, for the 2 class classification problem.

2- I got 2 arrays in shap_values, that's okay as it's a 2 classes classification problem. I plotted the results of each class separately, however, what I found out that the features is not the same between both classes. Furthermore, when I used the KernelExplainer for my model as well the features of each class were the same. What is the difference?

3- Are the classes exactly the same as in my model. In my model the classes are class0 as SCRAP class 1 as OKAY. I am not sure if the arrays in the shap_value list is aligned with my model classes. Such that the first array in the shap_values is for the SCRAP class, and the second array in the shap_values is for OKAY class.

**Comment by alexcoca** [comment]
Hi @Dola47 ,

1 + 2: `shap_output [:,0, -1]` will give you an array which you can average to get the expected value for class 0. Note that all the values in the array `shap_output[:, 0, -1]` are equal - they represent the same number but are repeated so that the algorithm can return one single tensor. The same applies for the expected value of the other class: do `shap_output[:, 1, -1].mean()` or simply `shap_output[:, 1, -1][-1]` to obtain the desired expected value. So you will have two floats representing the expected value, one for class 0, one for class 1.

3.  when you index `shap_output[:, 0, :-1]` you obtain the shap values that explain the output of your model at index 0, when you index `shap_output[:, 1, :-1]` you explain the model output at index 1. So the middle index represents the class. So, yes, the output is aligned with your model classes and you will have shap values explaining the margin assigned to SCRAP when you do `shap_output[:, 0, :-1]` and OKAY when you do `shap_output[:, 1, :-1]`.

**Comment by Dola47** [comment]
@alexcoca  Thanks a lot so I was just want to be sure that to calculate the expected value I have to use .mean().

I still have one question which is not answered in the shap_output I got 2 arrays. In the case of the KernelSHAP the features being used in the 2 arrays are exactly the same. So, for example if I plotted the top 50 features from each array, the features are the same, the plot even looks exactly the same but they are inverted versions of each other. So, it appears that class 0 is the negative values of class 1. Is that correct? The expected values as well are the same but negative versions of each other?

The difference in the case of the predict_contrib from the XGBoost model, that when I plot the features being used in each of the arrays, they are not the exactly the same features some of them are different. Accordingly, the plot does not look as well to be inverted versions from each other. Is that also okay? The Expected value for each class is different from each other, for class 0 it is negative and for class 1 it is positive but they are not the same number as in the case of SHAPKernel?

**Comment by alexcoca** [comment]
Your observations about the KernelShap output seem correct: intuitively, I would expect that if a feature makes a positive contribution for class 0, then the contribution for class 1 must be of opposite sign and equal magnitude.

Getting expected values of opposite signs from xgboost is correct: one class will have negative margin and the other positive margin, so it is correct that the expected values have opposite signs. I find it counterintuitive that the shap values are not negated versions of each other, maybe @slundberg can explain why.

**Comment by Dola47** [comment]
The values of the expected value of each class in case of the Xgboost is not the same as well, and that explain why at the end the expected value of each class is not the negated version of the other class.

I could say that in the case of the Xboost there is some randomness, the features being used in each class is not the same, their magnitudes is not the same, the values in the expected values is not a repeated version of each other, and accordingly the expected value of each class after using. mean() is not the same. The question is that okay in case of Xgboost or there is something wrong?

One more question, do we have a specific way through which I can access the features with their weights that come out of the summary_plot. I want to attach them to a DataFrame.
