### ISSUE TITLE
shap.depenence_plot to multi page pdf

### ISSUE THREAD

**Issue by hucklebarryreese** [shap/shap#1086]
Greetings,
I have searched the doc, but cannot find anything on my use case.  I have a for loop that returns a shap.dependence_plot for every field in the data.  However, when I try to save to pdf, it only saves the first plot.  I have no issue when I leave the show=True parameter blank.  I am able to view all plots.  However, when saving to pdf, I switch show=False, and only the first plot is returned in the pdf.  I want a mult page pdf with all plots.  Are you able to help?

````python
def shap_dependence_report(shap_values, X_shap,  X_shap_disp, col1, alpha):  
    import shap  
    shap.dependence_plot(ind=col1,  
 shap_values=shap_values[1],  
                    features=X_shap,  
                    display_features=X_shap_disp,  
                    interaction_index=col1,  
                    alpha=alpha,  
                    show=False,  
                )  

cols = X_shap_disp.columns[~X_shap_disp.columns.isin(['obfsc_field'])]
for col in cols:
    shap_dependence_report(shap_values, X_shap,  X_shap_disp, col, alpha=0.5)
    plt.savefig("data/reports/dependence_plot.pdf")
````

**Comment by alvaroof** [comment]
Hello there,

have you tried to use the pdfpages option in matplotlib? it allows you to append new pages to an existing pdf with new visualizations and even label them. 

Actually this, given the reporting nature of the shap package, would be like an useful addition to the library.

Hope it helps.

```python
import datetime
import numpy as np
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt

# Create the PdfPages object to which we will save the pages:
# The with statement makes sure that the PdfPages object is closed properly at
# the end of the block, even if an Exception occurs.

cols = X_shap_disp.columns[~X_shap_disp.columns.isin(['obfsc_field'])]
with PdfPages('multipage_pdf.pdf') as pdf:
    for col in cols:
        shap_dependence_report(shap_values, X_shap,  X_shap_disp, col, alpha=0.5)
        plt.title('Dependence Plot for: ', col)
        plt.savefig()
        plt.close()
```
