### ISSUE TITLE
shap.summary_plot for interactions, ValueError: Width and height specified must be non-negative

### ISSUE THREAD

**Issue by adima** [shap/shap#109]
Hello, 
I've had this problem on real data, but for the sake of demonstration here's an artificial example:
```
import numpy as np
import shap 
shap.initjs()

ft = np.array(list("abcdefghij"))
shap.summary_plot(np.random.rand( *(20, 11, 11) ), np.random.rand( *(20, 10) ),
 ft, plot_type='violin', max_display=10 )

```
this produces error below and the plot of 2 first feature interactions, although I would prefer the interactions of all 10 features. 

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-5-5e5b004d0462> in <module>()
>       7 ft = np.array(list("abcdefghij"))
>       8 
> ----> 9 shap.summary_plot(np.random.rand( *(20, 11, 11) ), np.random.rand( *(20, 10) ), ft, plot_type='violin', max_display=5 )
>      10 
> 
> ~/anaconda3/lib/python3.6/site-packages/shap/plots.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot, layered_violin_max_num_bins)
>     361         for i in range(1, max_display):
>     362             ind = sort_inds[i]
> --> 363             pl.subplot(1, max_display, i + 1)
>     364             proj_shap_values = shap_values[:, ind, np.hstack((sort_inds, len(sort_inds)))]
>     365             proj_shap_values *= 2
> 
> ~/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py in subplot(*args, **kwargs)
>    1048 
>    1049     fig = gcf()
> -> 1050     a = fig.add_subplot(*args, **kwargs)
>    1051     bbox = a.bbox
>    1052     byebye = []
> 
> ~/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py in add_subplot(self, *args, **kwargs)
>    1072                     self._axstack.remove(ax)
>    1073 
> -> 1074             a = subplot_class_factory(projection_class)(self, *args, **kwargs)
>    1075 
>    1076         self._axstack.add(key, a)
> 
> ~/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_subplots.py in __init__(self, fig, *args, **kwargs)
>      71 
>      72         # _axes_class is set in the subplot_class_factory
> ---> 73         self._axes_class.__init__(self, fig, self.figbox, **kwargs)
>      74 
>      75     def __reduce__(self):
> 
> ~/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py in __init__(self, fig, rect, facecolor, frameon, sharex, sharey, label, xscale, yscale, axisbg, **kwargs)
>     486             self._position = mtransforms.Bbox.from_bounds(*rect)
>     487         if self._position.width < 0 or self._position.height < 0:
> --> 488             raise ValueError('Width and height specified must be non-negative')
>     489         self._originalPosition = self._position.frozen()
>     490         # self.set_axes(self)
> 
> ValueError: Width and height specified must be non-negative

**Comment by slundberg** [comment]
Hmm. I don't get the error in my notebook. What version of shap do you have installed? (Also I think the violin plot type is not supported yet for the interactions, just the dot type)

**Comment by adima** [comment]
The shap version is 0.17.1, matplotlib version is 2.1.2. The error persists on both my ubuntu and osx machines. I use python3 from anaconda. Conda version is 4.4.10.

**Comment by slundberg** [comment]
Looks like a new bug in matplotlib https://github.com/matplotlib/matplotlib/issues/11123

I get it now after updating to matplotlib 2.2
