### ISSUE TITLE
Summary plot for a multi-input network?

### ISSUE THREAD

**Issue by BengWord2Vec** [shap/shap#1092]
Experiencing "AttributeError: 'list' object has no attribute 'shape'":

### summarize the effects of all the features
shap.summary_plot(shap_values, [X11, X22])

![image](https://user-images.githubusercontent.com/44710948/76163821-ca22b300-6149-11ea-995c-e068891b1a51.png)

Can you please help me with this?

**Comment by ibuda** [comment]
Your features parameter is a list with only two values, whereas shap_values, I assume, has a lot more. Either pass as many values as you have in shap_values, or select the two respective values from sha_values and pass them as arguments.
For more details see doc strings of the method, with more focus on (# samples x # features):
```
Signature:
shap.summary_plot(
    shap_values,
    features=None,
    feature_names=None,
    max_display=None,
    plot_type=None,
    color=None,
    axis_color='#333333',
    title=None,
    alpha=1,
    show=True,
    sort=True,
    color_bar=True,
    plot_size='auto',
    layered_violin_max_num_bins=20,
    class_names=None,
    class_inds=None,
    color_bar_label='Feature value',
    auto_size_plot=None,
)
Docstring:
Create a SHAP summary plot, colored by feature values when they are provided.

Parameters
----------
shap_values : numpy.array
    For single output explanations this is a matrix of SHAP values (# samples x # features).
    For multi-output explanations this is a list of such matrices of SHAP values.

features : numpy.array or pandas.DataFrame or list
    Matrix of feature values *(# samples x # features)* or a feature_names list as shorthand
```
