### ISSUE TITLE
could not execute shap values

### ISSUE THREAD

**Issue by Idanzinner** [shap/shap#1096]
~/venvs/avatrade/lib/python3.6/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate, check_additivity)
    325 
    326         if check_additivity and self.model_output == "margin":
--> 327             self.assert_additivity(out, self.model.predict(X))
    328 
    329         return out

~/venvs/avatrade/lib/python3.6/site-packages/shap/explainers/tree.py in assert_additivity(self, phi, model_output)
    436         else:
    437             val = self.expected_value + phi.sum(-1)
--> 438             assert np.max(np.abs(val - model_output) / (np.abs(val) + 1e-2)) < 1e-2, err_msg
    439 
    440 

AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub.

**Comment by LEMTideman** [comment]
Similar problem as what is reported in issues #887  #941 and #903
