### ISSUE TITLE
is there an API for a pypmml.model.Model object？

### ISSUE THREAD

**Issue by mrlittleyo** [shap/shap#1099]
i found shap can't recognize the pypmml.model object, when i used my python to load a "pmml" model by pypmml,for example:explainer=shap.TreeExplainer(model) i got "Exception: Model type not yet supported by TreeExplainer: <class 'pypmml.model.Model'>"

**Comment by zwag20** [comment]
I'm having the same issue, has there been a solution to this?

**Comment by sashankchittoory** [comment]
Hi Team, I am facing the same issue
Any feature added to support PMML models or can PyPmml Model type can be converted to XGBModelType
