### ISSUE TITLE
Minor copy/paste errors in LGBM classification notebook

### ISSUE THREAD

**Issue by alvinthai** [shap/shap#11]
Hi,

I noticed that the description under the **Explain Predictions** header in the [LGBM classification notebook](https://slundberg.github.io/shap/notebooks/Census+income+classification+with+LightGBM.html#Explain-predictions) was copied over from the Keras notebook and doesn't apply.

EDIT: Description also doesn't apply under the [Visualize a single prediction](https://slundberg.github.io/shap/notebooks/Census+income+classification+with+LightGBM.html#Visualize-a-single-prediction) header

**Comment by slundberg** [comment]
Thanks! I'll fix that
