### ISSUE TITLE
Scale of input features and distribution of prediction model f().

### ISSUE THREAD

**Issue by muhlbach** [shap/shap#110]
Dear Mr. Lundberg,

As an economist, I’m truly enjoying reading your papers on SHAP because they allow me to interpret the typical black box models. However, two questions have come to my mind:

1) How does your measure of the attribute effect (\phi) take into account the scale of the input features? Most often you standardize the input features by subtracting mean of dividing by the standard error, but I cannot find anything in your paper on this.

2) How is the estimator of the attribute effect (again \phi) affected by the distribution of the prediction model f()? It does not seem that you impose some distributional assumptions, nor any IID assumptions  on the features/samples.

Looking forward to reading your answer!

Best, Nicolaj

**Comment by slundberg** [comment]
Good questions!

1. The SHAP values (phi values) are entirely defined using changes in the model output. So SHAP values are in the units of the model output not the units of the input features. This is one reason you can meaningfully compare the SHAP values of different features to one another.

2. The definition of SHAP values makes no assumption on the distributional form of function outputs or inputs. But it does depend on the input feature distribution to compute the conditional expectations. For the sake of efficiency we often treat the input features as independent when estimating them in Kernel SHAP, or assume their dependence is captured by the tree structure in Tree SHAP. The NIPS paper has more details on why assuming feature independence is used as an approximation.

**Comment by muhlbach** [comment]
Thanks your the super cool (and fast) answers!

1) I see, makes sense. Cool!

2) Okay, so to compute the SHAP values, you need to estimate the feature distribution. Two questions arise: 
2a) Have you looked at your feature distribution? I assume it would typically by either normal or log-normal?
2b) Have you looked at the distribution of the SHAP-values? I guess it will the depend on the feature distribution.

**Comment by slundberg** [comment]
The feature distribution is not explicitly estimated, but the conditional expectations are computed with respect to the training data set, so the training set defines the feature distribution. In the `TreeExplainer` the original ensemble tree model keeps track of the dataset via how many samples went down each branch of each tree. This is all we need for our expectations so you don't need to separately provide a training dataset. For the `KernelExplainer` it needs to explicitly integrate over features sampling from some background reference set. Often for the sake of speed this background set is just a single sample (like the mean of the feature values), but it can be more samples to better approximate not knowing the value of a feature. Hope that helps!

Your two subquestions seem very dataset specific, so I am not sure how to answer them without reference to specific model and training dataset.

**Comment by muhlbach** [comment]
Once again, thank you for excellent answers!
