### ISSUE TITLE
A question about KernelExplainer input

### ISSUE THREAD

**Issue by shangwen777** [shap/shap#1109]
Hi Scott,

I was a bit confused about the input of KernelExplainer. I wrote a prediction call function for Learning Fair Representation Algorithm:

def prediction(M_nk, w, N, k):
    yhat = np.zeros(N)
    for i in range(N):
        for j in range(k):
            yhat[i] += M_nk[i, j] * w[j]
        yhat[i] = 1e-6 if yhat[i] <= 0 else yhat[i]
        yhat[i] = 0.999 if yhat[i] >= 1 else yhat[i]
    return yhat

def call_FLR(X_test):
    dists= distances(X_test, v, alpha, Ns, d, k)
    M_nks = M_nk(dists, Ns, k)
    M_ks = M_k(M_nks, Ns, k)
    yhat = prediction(M_nks, w, Ns, k)
    return yhat

explainer = shap.KernelExplainer(call_FLR(X_test), X_test, link = 'logit')

But I got an error message as below. Could you please advise?

Thank you!

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-e13bf243e4ac> in <module>()
----> 1 explainer = shap.KernelExplainer(call_FLR(X_test), X_test, link = 'logit')

~/libraries/nb_env/lib64/python3.6/site-packages/shap/explainers/kernel.py in __init__(self, model, data, link, **kwargs)
     95         self.keep_index_ordered = kwargs.get("keep_index_ordered", False)
     96         self.data = convert_to_data(data, keep_index=self.keep_index)
---> 97         model_null = match_model_to_data(self.model, self.data)
     98 
     99         # enforce our current input type limitations

~/libraries/nb_env/lib64/python3.6/site-packages/shap/common.py in match_model_to_data(model, data)
     87             out_val = model.f(data.convert_to_df())
     88         else:
---> 89             out_val = model.f(data.data)
     90     except:
     91         print("Provided model function fails when applied to the provided data set.")

TypeError: 'numpy.ndarray' object is not callable

**Comment by shangwen777** [comment]
ahh... I figured it out. I should use the function call_FLR instead of the results call_FLR(X_test) as the input. 

Thanks!

**Comment by XiangBu** [comment]
> 

Thanks for your explanation! Can StackingClassifier be explained by KernelExplainer? Thx!
![image](https://user-images.githubusercontent.com/46986985/145702646-a5a79bc8-34a9-4dee-8675-659d63a25307.png)
