### ISSUE TITLE
ValueError: left cannot be >= right

### ISSUE THREAD

**Issue by PrashantSaikia** [shap/shap#111]
Hey Scott,

First of all, SHAP works almost seemlessly, or at the very least, smoothly, with Python, unlike a lot of libraries that require a lot of initial struggle to get started with. So, thanks for that. 👍 :)

I am facing an issue with the `summary_plot` module. My dataset has feature names that can be a bit lengthy (I can shorten them manually, but my boss doesn't want me to alter the feature names for some reason). I think that's the reason I am getting this `ValueError: left cannot be >= right`. It does plot the figure with the correct feature names though, but it stops the code flow. Do you know any workaround for the matplotlib implementation of `summary_plot` (the `tight_layout()` module to be precise), which is what causes this error?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-b8a918e5bdf1> in <module>()
      1 shap_values = shap.TreeExplainer(model).shap_values(pd.DataFrame(X_train, columns=X.columns))
----> 2 shap.summary_plot(shap_values, pd.DataFrame(X_train, columns=X.columns))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\plots.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot, layered_violin_max_num_bins)
    616     pl.ylim(-1, len(feature_order))
    617     pl.xlabel(labels['VALUE'], fontsize=13)
--> 618     pl.tight_layout()
    619     if show:
    620         pl.show()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\pyplot.py in tight_layout(pad, h_pad, w_pad, rect)
   1364     """
   1365     fig = gcf()
-> 1366     fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
   1367 
   1368 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\figure.py in tight_layout(self, renderer, pad, h_pad, w_pad, rect)
   2274             self, self.axes, subplotspec_list, renderer,
   2275             pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
-> 2276         self.subplots_adjust(**kwargs)
   2277 
   2278     def align_xlabels(self, axs=None):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\figure.py in subplots_adjust(self, *args, **kwargs)
   2086 
   2087         """
-> 2088         self.subplotpars.update(*args, **kwargs)
   2089         for ax in self.axes:
   2090             if not isinstance(ax, SubplotBase):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\figure.py in update(self, left, bottom, right, top, wspace, hspace)
    239             if self.left >= self.right:
    240                 reset()
--> 241                 raise ValueError('left cannot be >= right')
    242 
    243             if self.bottom >= self.top:

ValueError: left cannot be >= right

```

**Comment by slundberg** [comment]
Glad the package has been helpful for you so far. Could you post a simple example that shows the problem? One guess is that adding a newline in the feature name might help. But a simple example will help sort it out.

**Comment by PrashantSaikia** [comment]
Here's a minimum viable code to illustrate the issue:

```
from sklearn.model_selection import train_test_split
import xgboost
import shap
import numpy as np
import matplotlib.pylab as pl
import pandas as pd

dataset = [[23, 46, 0], [42, 84, 1], [33, 66, 2]]
dataset = pd.DataFrame(dataset, columns=['This is another very hugely tremendously loooonnnnngggg feature name that causes problems', 'This is a very hugely tremendously loooonnnnngggg feature name that causes problems', 'Output'])

# Comment the above dataset definition and uncomment the dataset definition below
#dataset = pd.DataFrame(dataset, columns=['Feature 1', 'Feature 2', 'Output']) # Short feature names do not case problems for summary_plot

X = dataset.loc[:, dataset.columns != 'Output']
y = dataset['Output']
y = y/max(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=7)







from sklearn import preprocessing 
for f in X_train.columns: 
    if X_train[f].dtype=='object': 
        lbl = preprocessing.LabelEncoder() 
        lbl.fit(list(X_train[f].values)) 
        X_train[f] = lbl.transform(list(X_train[f].values))

for f in X_test.columns: 
    if X_test[f].dtype=='object': 
        lbl = preprocessing.LabelEncoder() 
        lbl.fit(list(X_test[f].values)) 
        X_test[f] = lbl.transform(list(X_test[f].values))

X_train.fillna((-999), inplace=True) 
X_test.fillna((-999), inplace=True)

X_train=np.array(X_train) 
X_test=np.array(X_test) 
X_train = X_train.astype(float) 
X_test = X_test.astype(float)

d_train = xgboost.DMatrix(X_train, label=y_train, feature_names=list(X))
d_test = xgboost.DMatrix(X_test, label=y_test, feature_names=list(X))






params = {
    "eta": 0.01,
    "objective": "binary:logistic",
    "subsample": 0.5,
    "base_score": np.mean(y_train),
    "eval_metric": "logloss"
}

model = xgboost.train(params, d_train, 5000, evals = [(d_test, "test")], verbose_eval=100, early_stopping_rounds=20)





shap_values = shap.TreeExplainer(model).shap_values(pd.DataFrame(X_train, columns=X.columns))
shap.summary_plot(shap_values, pd.DataFrame(X_train, columns=X.columns))
```

**Comment by slundberg** [comment]
Hmmm... it doesn't crash for me. What version of matplotlib and SHAP do you have?

**Comment by PrashantSaikia** [comment]
Oh! I am using version 2.2.2 of matplotlib, and 0.18.1 of shap.

**Comment by slundberg** [comment]
Same here, so I am not sure what is different. You are running this in a
Jupyter notebook right? What OS? (I am on a Mac)

**Comment by PrashantSaikia** [comment]
I am on Windows 10. Yes, I'm using Jupyter notebook within Anaconda 5.2.0 with Python 3.6.3

**Comment by slundberg** [comment]
Seems like we have very similar version of everything except the OS. Without being able to reproduce it I can't suggest a good fix, but if you find something that helps address it let me know and we can merge it in.

**Comment by PrashantSaikia** [comment]
Hi Scott. There's another (unrelated to this) issue that I would like to ask you about. In shap.dependence_plot(), how do I change the x and y axes limits? Like, if I want to "zoom into" a plot, or show a part of the plot, how do I do that?

**Comment by slundberg** [comment]
They are matplotlib plots so you can set show=False and then keep adjusting
the plots (like with xlim)

**Comment by PrashantSaikia** [comment]
Hi Scott. Changing the xlim worked for `shap.dependence_plot()`. But how do I do this for `shap.summary_plot(shap_interaction_values, X)`? I tried `plt.xlim(-1,1)`, but that just plotted another figure with the specified xlims, and the shap plot below it. I need this to "zoom in" to the values for the interaction plot below - the default xlims are -5 to +5, and its not enough zoom to make the plot clear.

![shap](https://user-images.githubusercontent.com/39755678/42197439-67490842-7eb5-11e8-9903-a9307ab00d86.PNG)

I went into the definition of `summary_plot` and changed `v = max(abs(slow), abs(shigh))` to `v = min(abs(slow), abs(shigh))`, as in my plot, `slow` was 0.56 and `shigh` was 5.35. But that doesn't seem to do anything.

**Comment by slundberg** [comment]
There should be an option to control that exposed but it isn't yet. That's strange that your tweak didn't change anything. Did you check that at line 390 of plots.py what `pl.xlim((slow, shigh))` is doing?

**Comment by PrashantSaikia** [comment]
No, I didn't do that yet. But I noticed that when I restarted the jupyter notebook kernel, those tweaks worked.

I have another question about how to interpret the SHAP `summary_plot` results with non-numeric feature values, if you'd be so kind as to shed some light on it. I have a survey questionnaire dataset with user answers to questions and a rating (how good they find the product, 0 to 10). I'm interested to know how the answers correlate to the scores the users are giving to the product. I'm showing a portion of the `Score` column and one of the questions (labelled `Q1AM1`):

```
Score | Q1AM1
7 | Trust / am confident in the company / well established / long history
8 | Good quality of billing / no issues with paperwork
8 | Contact me proactively / regularly / respond to me
8 | Trust / am confident in the company / well established / long history
5 | Don't recommend - don't discuss topic with others
7 | Fund performance / return on investment is good / stable
5 | Don't know/ not applicable
8 | Trust / am confident in the company / well established / long history
6 | Don't know/ not applicable
3 | Don't know/ not applicable
10 | Good communication / easy to reach / fast response / follow-up
...  | ...
...  | ...
```

The feature values are (obviously) non-numeric, so I'm having trouble interpreting the `summary_plot` visualization, as we don't have high or low values of non-numerical data (so we cannot say, for example, statements like: "higher values of feature `Q1AM1` lowers the score", etc).

This is the summary plot:

![download](https://user-images.githubusercontent.com/39755678/42676947-a737af54-86ac-11e8-8ed7-f5e3fefe2646.png)

How do I interpret it? For which values (user answers in the portion of data I pasted above) is the SHAP value higher or lower?

P.S.: I, later on, also converted the feature values in the dataset (taken as a pandas dataframe) from non-numeric to numeric data like this: `X = X.apply(lambda x: pd.factorize(x)[0])`, so the data portion I copied above transformed to this:

```
Score | Q1AM1
7 | 0
8 | 1
8 | 2
8 | 0
5 | 3
7 | 4
5 | 5
8 | 0
6 | 5
3 | 5
10 | 6
```

I then ran the summary plot again. The result of `summary_plot` is as follows:

![download 1](https://user-images.githubusercontent.com/39755678/42678096-72cece2e-86b0-11e8-82c4-d6ad2c9333f4.png)

The result is clearly very different from when the data was non-numeric. So, how do I interpret which user answers are "low" and which are "high"? Or, how do I interpret the `summary_plot` results in this case, basically?

**Comment by slundberg** [comment]
The important thing to keep in mind is that everything becomes a numeric value before it is given to the model. So that numeric value is what SHAP is using to decide what is a high or low value for the feature. For categorial features, the high or low nature of a value may be less meaningful. I am not sure from you you posted what changed in your model when you factorized things, but it did seems to change the model. If this is LightGBM it could be because the features are no longer categorical.

For the first summary plot are the values of the features you pass strings?

**Comment by PrashantSaikia** [comment]
Hi Scott. Thanks for your reply.

The model I used is xgboost, not LightGBM. 

Yes, in the first plot, I pass the features (user answers to questions) as is, i.e., the values of the features are strings. I'd read since that xgboost cannot handle categorical data, but it did in my case.

**Comment by slundberg** [comment]
Hmm. I don't know off-hand how XGBoost deals with string inputs, but it
must turn them into numerical values at some point. I would investigate
that to interpret the plots.

**Comment by PrashantSaikia** [comment]
Thanks a lot!

I also think the way I factorized the strings to numbers might not be the correct way to convert categorical features into numerical ones. So, I also tried making new features out of each unique feature value, and then one-hot-encoding them as new features, like so:

```
df = data[['Q1AM1']]
df2 = (pd.get_dummies(df, prefix='', prefix_sep='')
               .max(level=0, axis=1)
               .add_prefix('Q1AM1-'))
```

For the portion of the dataset I pasted above, this produces the new (numeric) features as follows:
```
Q1AM1-Contact me proactively	Q1AM1-Don't know/ not applicable	Q1AM1-Don't recommend	Q1AM1-good/stable	Q1AM1-Good communication	Q1AM1-Good paperwork	Q1AM1-Trust/am confident
0				0					0			0			0				0			1
0				0					0			0			0				1			0
1				0					0			0			0				0			0
0				0					0			0			0				0			1
0				0					1			0			0				0			0
0				0					0			1			0				0			0
0				1					0			0			0				0			0
0				0					0			0			0				0			1
0				1					0			0			0				0			0
0				1					0			0			0				0			0
0				0					0			0			1				0			0
```

I then ran SHAP on this data, and got the following plot:

![capture](https://user-images.githubusercontent.com/39755678/42854878-92522b42-8a70-11e8-98a8-59586b910fb8.PNG)

Do you think this is the correct way to handle categorical data? If yes, I'm still not sure how to interpret the results - to me, it basically says, "these feature _values_  are more important", but does not say which of the (original) _features_ are important. Am I right? If it so happens that most of the constructed one-hot-encoded features happen to be from one or two of the original features, then we could say that those one or two original features are more important - but what if that's not the case? I'm just thinking aloud/pondering.

**Comment by slundberg** [comment]
Depending on the number of categories either way is fine (one hot with
thousands of categories is often bad in XGBoost). But this one hot might be
easier to interpret.

**Comment by PrashantSaikia** [comment]
Hey Scott,

How do I flip the axes of SHAP dependence plots?

Like, in the figure below:
![1](https://user-images.githubusercontent.com/39755678/44504206-0bb94d80-a6cd-11e8-87a4-22305ede6195.png)
how do I put `Client Age` on x-axis and `NonAdoptedOrphan` on y-axis?

I am doing the dependence plots like so:

```
for i in feature_list:
    shap.dependence_plot(i, shap_values, X)
```
and it displays the plots in an uncontrolled fashion - i.e., I don't have control over which feature is on x-axis and which on y-axis. For ex, for another feature, `Client Tenure`, it plotted in the desired manner with `NonAdoptedOrphan` on y-axis:
![2](https://user-images.githubusercontent.com/39755678/44504260-779bb600-a6cd-11e8-9511-ef66ff3ecb35.png)

I want the same for the plot with `Client Age`. How do I do that?

When I plot `shap.dependence_plot("NonAdoptedOrphan", shap_values, X)`, it plots the first plot; and when I plot `shap.dependence_plot("Client Age", shap_values, X)`, it plots the following:
![3](https://user-images.githubusercontent.com/39755678/44504666-779cb580-a6cf-11e8-9b07-ed7fe6b31ae6.png)

So, its plotting the selected feature (in double quotes) against the most important feature according to the SHAP values, am I right? So, how do I get it to plot against any feature I want?

-----------------------------------------------------------------------------------------------------------------

I am able to have this control when I plot the "SHAP main interaction value" plots like so:

```
features = ['NonAdoptedOrphan', 'Client Age']
for i in features:
    for j in features:
        shap.dependence_plot (
            (i, j),
            shap_interaction_values, X.iloc[:2000,:],
            display_features=X.iloc[:2000,:]
        )
```

which plots 4 figures for each of the permutations of the features in the feature-list. So I get both the following plots:

![5](https://user-images.githubusercontent.com/39755678/44504862-ddd60800-a6d0-11e8-9552-a279f9996817.png)
![6](https://user-images.githubusercontent.com/39755678/44504863-ddd60800-a6d0-11e8-9653-0240087fcc02.png)

I want to know if its possible to have a similar control in the aforementioned case.

**Comment by slundberg** [comment]
Just to be clear in the first figure you share Client Age is the color bar not the y-axis, the y-axis is the SHAP value (i.e. impact) of NonAdoptedOrphan. If you want to control the color bar you can use the `interaction_index` keyword argument. Hope that helps!

**Comment by PrashantSaikia** [comment]
Yes, it does! Thanks for that. 

If you'd be so kind, could you please shed some light on what is the difference between the 2 figures below? What does each mean?

![a](https://user-images.githubusercontent.com/39755678/44576994-8912ba00-a7c2-11e8-967a-4c0554a99fd9.png)
![b](https://user-images.githubusercontent.com/39755678/44576995-8912ba00-a7c2-11e8-9c10-4b5a27514694.png)

**Comment by slundberg** [comment]
I should caution that you should probably retrain your model on several bootstrap resamples of your dataset and make sure these patterns are consistent before assuming they are real relationships (they are real to the model of course, but you want to make sure the model is capturing real patterns in the data). 

Given that warning, the first plot seems to imply that the model output (log-odds?) drops between 59-67. The second plot shows that the model has found a very weak interaction effect where being orphaned has a different impact on the model output depending on your age.
