### ISSUE TITLE
questionable YearMade vs SalePrice for Kaggle bulldozer dependence plot

### ISSUE THREAD

**Issue by parrt** [shap/shap#1112]
Hi Scott!! Heh, I'm trying to compare SHAP to a variety of techniques as I work on my own for partial dependence.  I have a case, with enclosed code/results, that I think does not get the right answer. I'm hoping that I am simply not using SHAP properly.   This is a real data set so impossible to know the true answer, but I think the results from SHAP are implausible.  ALE, for example, shows a plausible result which is that older bulldozers are worth less:

<img width="150" alt="Screen Shot 2020-03-19 at 10 21 29 AM" src="https://user-images.githubusercontent.com/178777/77095672-79258100-69cb-11ea-8f1c-a8b63e7a3e21.png">

Here is what `shap.dependence_plot()` shows (with marginal plot on the left):

<img width="330" alt="Screen Shot 2020-03-19 at 10 23 57 AM" src="https://user-images.githubusercontent.com/178777/77095922-d28db000-69cb-11ea-99a2-e2778a74e52d.png">

That partial dependence plot looks pretty random.

I enclose a small 10k sample of the bulldozer data set and complete file to exhibit this behavior. Here are the most important lines (Bulldozer RF OOB R^2 0.81).

```python
shap_test_size=300
rf = RandomForestRegressor(n_estimators=150, n_jobs=-1,  max_features=0.9,min_samples_leaf=1, oob_score=True)
rf.fit(X, y)

explainer = shap.TreeExplainer(rf, data=shap.sample(X, 100),
                               feature_perturbation='interventional')
shap_values = explainer.shap_values(X.sample(n=shap_test_size),
                                    check_additivity=False)

shap.dependence_plot("YearMade", shap_values, X.sample(n=shap_test_size),
                     interaction_index=None, ax=axes[1], dot_size=5,
                     show=False, alpha=.5)
```

I'm hoping that I'm doing something obviously wrong.

[bulldozer10k.zip](https://github.com/slundberg/shap/files/4356060/bulldozer10k.zip)

**Comment by swsmr** [comment]
First I thought this could be due to the obvious correlation of YearMade and age (maybe the model only took age for example in each tree).

However, I think you ran into DataFrame.sample() using random_state=None as default, leading to different samples being drawn at each call ;-)

**Comment by parrt** [comment]
Hi @swsmr, do you mean the `X.sample(n=shap_test_size)`? Isn't that just getting a sample of rows and sending it to `dependence_plot()`?  Yes, each run would get diff samples but that shouldn't matter.

**Comment by swsmr** [comment]
Yes, but this way you plot the SHAP values for different x values / rows than you used for calculating. In my understanding, `shap.dependence_plot()` just plots `shap_values[:, i]` vs. `X[:, i]`.

**Comment by parrt** [comment]
Oh Shoot! You're right. Gotta reuse same sample from explainer in the plot. thanks for catching that.  I'll give it a shot.  Confirmed. closing report. all looks fine now:
<img width="311" alt="Screen Shot 2020-03-25 at 8 56 19 AM" src="https://user-images.githubusercontent.com/178777/77557110-97c9c300-6e76-11ea-953a-88f77b6bd1c7.png">
