### ISSUE TITLE
How to connect it with fronend?

### ISSUE THREAD

**Issue by vaibhavkumar049** [shap/shap#1115]
I have a Flask backend and a vue front end, I want to render this graph in the front end, any idea how should I approach 
![Screenshot from 2020-03-23 15-21-38](https://user-images.githubusercontent.com/36812649/77304317-460c2600-6d1a-11ea-95ab-6a36db0584d6.png)

**Comment by ibuda** [comment]
you can use the following snippet to save it to an image and display it on your website:
```
import matplotlib.pyplot as pl

shap.summary_plot(shap_values, X, show=False)
plt.savefig("shap.png", dpi=1000, bbox_inches='tight')
```

**Comment by vaibhavkumar049** [comment]
for this particular graph we need to do this 

`shap.force_plot(explainer.expected_value[1], shap_values[1], data_for_prediction,show=False,matplotlib=True)
plt.savefig('sahp.png',dpi=1000,bbox_inches='tight')`

@ibuda thank you
