### ISSUE TITLE
does it possible for shap to recognize  PMMLForestClassifier object load by sklearn_pmml_model package,since shap can recognize PMMLLinearRegression object created by sklearn_pmml_model pacjage

### ISSUE THREAD

**Issue by mrlittleyo** [shap/shap#1123]
i use sklearn_pmml_model to read a LinearRegression PMML like this:
from sklearn_pmml_model.linear_model import PMMLLinearRegression
lr= PMMLLinearRegression("./Iris.pmml") 
 #note that  iris.pmml is created by sklean2pmml with LinearRegression model
and the lr can be recognized by shap
but the result is not good for randomforest when i run this:
from sklearn_pmml_model.ensemble import PMMLForestClassifier
clf = PMMLForestClassifier("./Iris.pmml")
 #note that  iris.pmml is created by sklean2pmml with RandomForestClassifier model
the clf can't be recognized by shap
#Exception: Unknown input to Tree constructor!

**Comment by alexcoca** [comment]
No, the PMMLForestClassifier is not supported by the library.
