### ISSUE TITLE
how much memory does it take for the NHANES-I dataset with tree shap calculation for thousands of sub-trees xgboost model?

### ISSUE THREAD

**Issue by rayeaster** [shap/shap#1125]
@slundberg 

in the paper ["Consistent Individualized Featue Attribution For Tree Ensembles"](https://arxiv.org/pdf/1802.03888.pdf), it mentioned NHANES-I dataset as following quote:

> To explore these visualizations we trained an XGBoost Cox proportional hazards model on survival data from the classic NHANES
> I dataset [18] using the NHANES I Epidemiologic Followup Study
> [7]. After selection for the presence of basic blood test data we
> obtained data for 9,932 individuals followed for up to 20 years after
> baseline data collection for mortality. Based on a 80/20 train/test
> split we chose to use 7,000 trees of maximum depth 3, η = 0.001,
> and 50% instance sub-sampling. We then used these parameters
> and trained on all individuals to generate the final model.

just curious how much memory will tree shap algorithm take to complete the `summary_plot` calculation for entire dataset?

Thanks

**Comment by alexcoca** [comment]
I guess you can try and use a memory profiler to find that out, depending on your setup, your IDE might have one (Intellij PyCharm professional has one) but you can also get plug-ins for free IDEs such as Spyder. 

The memory consumption would also depend on the algorithm selected. For the path-dependent perturbation, the calculation takes O(D^2 + M) memory for each tree, where D is tree depth and M is number of input features.
