### ISSUE TITLE
Does SHAP DL explainer works for object detection frameworks like Mask R-CNN?

### ISSUE THREAD

**Issue by krzysztoffiok** [shap/shap#1127]
I'm looking for XAI that would work for object detection task, not simple classification.

So i'm using not only a classification CNN like ResNet-101 but a whole framework like Mask R-CNN.

Can SHAP help me?

**Comment by ividal** [comment]
@krzysztoffiok I've only seen this addressed here: https://github.com/slundberg/shap/issues/550

Did you find any other way?
