### ISSUE TITLE
Force plot not displaying values with large number of points (also questions about plot adjustment)

### ISSUE THREAD

**Issue by Jakedismo** [shap/shap#113]
Hello,

I've been testing shap for sometime now and I run into a problem, the force_plot() function isn't displaying graph in plot if I want to check variable effects. Works with output value but it doesn't display datapoint values correctly. I'm running different regression models with 1 output valuea and 22 training variables with 10000 lines of data (timeseries).
Is there a way to adjust the plots (size etc.) or some other solution with JS parameters (running out of allocated memory perhaps)? I'm not that familiar in displaying plots in JS in python (usually I use matplotlib).
![image](https://user-images.githubusercontent.com/32139094/41275689-603cabd0-6e2a-11e8-928e-29313a2c2a7f.png)

**Comment by slundberg** [comment]
Hmm... if you do `shap.force_plot(shap_values[:100,:],
X_test.iloc[:100,:])` does that work?
