### ISSUE TITLE
Difference Between SHAP in XGBoost and shap.TreeExplainer?

### ISSUE THREAD

**Issue by sandrawing** [shap/shap#1130]
Hi,

Thanks for the wonderful package! I noticed that using pred_contribs=True on XGBoost predict function, we can get also get the SHAP values. So are the values from XGBoost the same as those from shap.TreeExplainer in shap package? Do they have the same meaning? What is the difference between SHAP values in XGBoost and shap.TreeExplainer?

Thanks!

**Comment by alexcoca** [comment]
Hi @sandrawing ,

If you check `L230-L233` [here](https://github.com/slundberg/shap/blob/master/shap/explainers/tree.py) you will see that they should be the same. I don't think there should be a difference betwen the two.

**Comment by sandrawing** [comment]
Thanks a lot!! I totally understand!
