### ISSUE TITLE
shap.TreeExplainer(model).shap_interaction_values(X) does not work 

### ISSUE THREAD

**Issue by moijk-arko** [shap/shap#114]
Hey, 

I fitted a xgboost model on simulated data. Everything works fine including shap.TreeExplainer(model).shap_values(X). However, when when I want the interaction values by shap.TreeExplainer(model).shap_interaction_values(X) I get the following error: predict() got an unexpected keyword argument 'pred_interactions'. 

Any idea how I can solve this? Thanks in advance :)

p.s. I have the latest versions of xgboost and shap installed

**Comment by slundberg** [comment]
My guess is you have an old version of XGBoost installed. Do you have 0.71?

**Comment by moijk-arko** [comment]
You were right, thanks! For some reason I couldn't update xgboost with pip but instead I had to update xgboost manually in anaconda enviornment. Everything works fine now

**Comment by slundberg** [comment]
Great!
