### ISSUE TITLE
possible bug in unwound_path_sum

### ISSUE THREAD

**Issue by haifengl** [shap/shap#1142]
If one_fraction != 0, total won't be updated and thus return 0.

**Comment by slundberg** [comment]
Do you mean: ?https://github.com/slundberg/shap/blob/cde70feb211443cfbd9f599fcded8fe00b9d6a3d/shap/tree_shap.h#L377-L390

I don't quite follow what you are pointing out.

**Comment by haifengl** [comment]
Sorry, I missed something.
