### ISSUE TITLE
SHAP version in Anaconda is not updated for the last release

### ISSUE THREAD

**Issue by tjiagoM** [shap/shap#1144]
Hi, the title is self explanatory, but the version available in anaconda: https://anaconda.org/conda-forge/shap

Is not the last release, yet. Could you please update it? :) Thanks!

**Comment by LEMTideman** [comment]
See issue #1093

**Comment by tjiagoM** [comment]
Ups, I've missed that form my search, sorry and thanks @LEMTideman !
