### ISSUE TITLE
TreeSHAP in Java

### ISSUE THREAD

**Issue by haifengl** [shap/shap#1146]
Hi, we have implemented TreeSHAP in Java (https://github.com/haifengl/smile/blob/04f2cac7f0fa44cbfc7c30ca3da7ed8215aa7bb2/core/src/main/java/smile/regression/RegressionTree.java#L337). In addition, there are Scala, Kotlin and Clojure API to use it.

Can you please add a link in your README so that people with JVM can find it? Thanks!

**Comment by slundberg** [comment]
Great! Is there a self contained example I can point people to? (That would be more helpful than the taw code I think)

**Comment by haifengl** [comment]
I will add some examples in the project [website](http://haifengl.github.io/). Since this is a new feature, the new webpages will go live with next release. I will ping you then.

BTW, how to calculate TreeSHAP for classification? TreeSHAP values of each feature on every class posterior probability?

**Comment by slundberg** [comment]
Great. Yes, each class is a different output of the model, so you get an explanation for each class.

**Comment by haifengl** [comment]
Thanks. We support classification algorithms now.

**Comment by haifengl** [comment]
Hi, our implementation of TreeSHAP is released. Some examples can be found at http://haifengl.github.io/feature.html#tree-shap

Thanks!

**Comment by haifengl** [comment]
@slundberg Have you added the link to our implementation? If so, I will close this ticket. Thanks!
