### ISSUE TITLE
ValueError: feature_names mismatch - shap_values error on League of Legends demo notebook

### ISSUE THREAD

**Issue by meenaparam** [shap/shap#115]
Hi @slundberg,

Thanks for your package, which I'm just starting to learn to use. 

I was running a demo notebook ([shap/notebooks/League of Legends Win Prediction with XGBoost.ipynb](https://github.com/slundberg/shap/blob/master/notebooks/League%20of%20Legends%20Win%20Prediction%20with%20XGBoost.ipynb)), but couldn't get the SHAP values to calculate - it gives “ValueError: feature_names mismatch” when trying to running cell 4.

Someone has already spotted this issue on Stackoverflow ([https://stackoverflow.com/questions/50711382/why-am-i-getting-a-valueerror-feature-names-mismatch-when-specifying-the-feat](https://stackoverflow.com/questions/50711382/why-am-i-getting-a-valueerror-feature-names-mismatch-when-specifying-the-feat)).

I used that guidance to help me, but thought I would flag this to help other new users, particularly as other demo notebooks might also have this problem.

Specifically, I changed the last two lines of cell 2 to add in the `feature_names` option:

```
dt = xgb.DMatrix(Xt.values, label=yt.values, feature_names=X.columns)
dv = xgb.DMatrix(Xv.values, label=yv.values, feature_names=X.columns)
```

and then I changed cell 4 to use a Pandas dataframe with named columns instead:

```
shap_values = shap.TreeExplainer(model).shap_values(pd.DataFrame(Xv, columns=X.columns))
```

I can submit a PR, but thought it might be faster for your team to check your demo notebooks.

**Comment by slundberg** [comment]
Thank you for pointing out the problem! I'll push a fixed notebook as soon as I can (likely next week).
