### ISSUE TITLE
RuntimeError: The size of tensor a must match the size of tensor b

### ISSUE THREAD

**Issue by haroldks** [shap/shap#1153]
Hello,

I'm trying to use shap with a pytorch model but I'm coming to a runtime error with those line.
The code : 

` 
import shap
background =  X_train[np.random.choice(X_train.shape[0], 100, replace=False)]  
e = shap.DeepExplainer(model, torch.from_numpy(background))
shap_values = e.shap_values(torch.from_numpy(X_test[0:5]))
`

The error :

> RuntimeError: The size of tensor a (57) must match the size of tensor b (28) at non-singleton dimension 1

And it seems that the issue comes from the line 357 in deep_torch.py.

Thanks.

**Comment by soheilsadeghi90** [comment]
I'm having the same problem. I'm using a simple custom neural network in pytorch. Forward pass and training were completed with no issue. But I still get this size mismatch error.

**Comment by matheusherique** [comment]
I'm getting this same error with ResNet152

**Comment by kaurrachneet6** [comment]
I am having the same error. Is this issue resolved?

**Comment by Balthus1989** [comment]
The same for me. Any news about this issue?

**Comment by RigCor7** [comment]
I think my solution may help you, this it the [link](https://github.com/slundberg/shap/issues/2511)
