### ISSUE TITLE
Background dataset in SamplingExplainer

### ISSUE THREAD

**Issue by zzzbobml** [shap/shap#1157]
I'm not sure why background dataset is used in SamplingExplainer. In the referenced paper, missing features are replaced with values from other samples, so there should not be a need for averaging over missing features.   

Could you, please, explain?

Thank you,

**Comment by alexcoca** [comment]
What referenced paper are talking about? Surely, if the missing values are replaced with values from other samples, we need access to those samples (i.e., a background dataset where we can take them from)?

**Comment by zzzbobml** [comment]
It might just be an issue with terminology then. 

The paper mentioned is 
“An Efficient Explanation of Individual Classifications using Game Theory”, Erik Strumbelj, Igor Kononenko, JMLR 2010
where they replace random feature values with values taken from other samples.

**Comment by alexcoca** [comment]
Hi @zzzbobml, it is definitely a terminology issue. The values in the `data` argument are used to perform the replacements you mention. This happens in the `sampling_estimate` method of `SamplingExplainer` class.
