### ISSUE TITLE
Regression Coefficients Analog

### ISSUE THREAD

**Issue by ThinkHolger** [shap/shap#1163]
I would like to use XGBoost for a regression problem, but I would need the individual component values as well.

In linear regression you have coefficient vectors that you can just simply multiply with the observations xi to calculate the individual yi and the sum(yi) yields the predicted value. Is there an equivalent to the SHAP values or is this completely different? 

Thanks and congrats on your research!

**Comment by slundberg** [comment]
The SHAP values of a linear model are `coeff_i * (x_i - E[x_i])` ... so
they are a mean centered version fo the the coefficient times the data
values, and they add up to the model output (plus the expected model
output). So for XGBoost SHAP values still exist, but of course coeff does
not.

**Comment by ThinkHolger** [comment]
Thanks Scott for your quick reply!

So I should be able run a linear regression model and then use the KernelExplainer to compare the shape values as 'shapi=coeff_i * (x_i - E[x_i])' ?

**Comment by ThinkHolger** [comment]
I get them to match, but it looks hacky. They shap values look like they are range scaled. Is there a 'correct' way to achieve the below example?

df = pd.DataFrame()
df['x1'] = [0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
df['x2'] = [0, 0, 0, 1, 0.6, 0.6, 1, 1, 0, 0]
df['x3'] = [1, 1, 0, 0, 0, 0, 0, 1, 1, 1]
df['y'] = 2 * df['x1'] + 3 * df['x2'] + 6 * df['x3']
x_columns=['x1','x2','x3']

reg = LinearRegression().fit(df[x_columns], df['y'])
explainer = shap.KernelExplainer(reg.predict, df[x_columns])
shap_values = explainer.shap_values(df[x_columns], nsamples=200, l1_reg=0.0001)
shap_values=pd.DataFrame(data=shap_values,columns=x_columns)
print('X*coef')
print(df[x_columns].multiply(reg.coef_))
print('raw shap values')
print(shap_values)
print('shifted shap values')
print(shap_values.subtract(shap_values.min()))

**Comment by l-longo** [comment]
Hi @slundberg, I was wondering how you came up with the formula: `shap = coeff_i * (x_i - E[x_i])`. Is there formal proof to link the linear model's coefficients to SHAP?
