### ISSUE TITLE
Error getting when reproducing the code in NHANES I Survival Model

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#117]
Could you please tell me where you have initialise X_display here? Or could you please give me an example to reproduce below line?  

# we pass display_features so we get text display values for sex
shap.dependence_plot("Sex", shap_values, X, display_features=X_display)

Thank you.

**Comment by slundberg** [comment]
Thanks for pointing out the problem! I just updated the notebook to load the display version of the data with `X_display,y_display = shap.datasets.nhanesi(display=True)`
