### ISSUE TITLE
SOS. Please Help. Shap DeepExplainer is taking extremely long time with no results

### ISSUE THREAD

**Issue by niloofardadras** [shap/shap#1170]
Hi,
have tensor model which i trained with estimator API. I have 3 hidden layers and hidden units "500/250/100". my input is a 100 row dataframe which i have created list of column values from it to create x_train_list.  also x_test is 1 row dataframe converted to list again.
I am trying to calculate Shap values with following part of code.

               sess=tf.Session()
                saver=tf.train.import_meta_graph('model.ckpt-3000.meta')
                saver.restore(sess,tf.train.latest_checkpoint('1/'))

                graph = tf.get_default_graph()
                op=sess.graph.get_operations()
                input=graph.get_tensor_by_name('enqueue_input/Placeholder:0')
                output=graph.get_tensor_by_name('ArgMax:0')
  
                explainer = shap.DeepExplainer(model=(input,output),data=x_train_list,session=sess)
                print("explainer done")
                shap_values = explainer.shap_values(x_test_list)
                sess.close()

so the running code does not even print "explainer done" and it keeps running without giving any print or results.

also I gave a shot at method used https://github.com/slundberg/shap/issues/280  (tensorflow estimator support #280 ) but still the same issue is created.

it has been around 6 hours now and no results yet!!! is this due to my model size? could you please help?

**Comment by niloofardadras** [comment]
closing as it seems like the package would not support estimator API

**Comment by songzhiyong** [comment]
> closing as it seems like the package would not support estimator API

how did you fix it? or is there any other way to use this package with estimator
