### ISSUE TITLE
Performance for large scale usage

### ISSUE THREAD

**Issue by psmgeelen** [shap/shap#1177]
Hi @slundberg , 
Firstly, congrats on your awesome package, its a gamechanger in DataScience. 

I am looking at running SHAP on many models (10.000s). I was wondering whether there are ways of improving the speed of the KernelExplainer in particular. My questions are:
* To what extend is the process threaded?
* Could the calculatins be executed in parrallel in e.g. Numba or some CUDA based technology?
* Does it allow for distributed computing.

My questions relate not just to how the package is now, but also whether it would make sense to start developing that. I am not the most proficient programmer, but I would definitely like to contribute to your project/package. 

Again, thank you sooo much for your time and for contributing in the field of DS the way you are!

Regards
Pieter

PS: I hope I didnt missappropiated the "issues".

**Comment by mirekphd** [comment]
@psmgeelen : thanks to @RAMitchell CUDA work there is now a GPU implementation at least for tree-based algos. Have a try yourself, you may be pleasantly surprised by the performance improvements): here's a reproducible performance test using our CUDA 10.1 py38 container: https://github.com/slundberg/shap/issues/1650#issuecomment-748482915.

**Comment by psmgeelen** [comment]
@mirekphd, very cool and thanks for the headsup! Just to be clear, the kernel explainer is not supported?
