### ISSUE TITLE
Questions about SHAP value (shapley weight part)

### ISSUE THREAD

**Issue by miaekim** [shap/shap#118]
Hello, 

I am trying to understand how SHAP equation derived in an intuitive way.

![default](https://user-images.githubusercontent.com/2246216/41510359-03e29c86-7218-11e8-8a10-5d30e6d8f1e0.PNG)

I would like to focus on weight part ![2](https://user-images.githubusercontent.com/2246216/41510395-be93d59a-7218-11e8-8676-deaaa3001d4b.PNG), how the weight has been implemented.

Shapely value regression equally weights the regressions based on the number of possible models. So if there are M number of features, 

the total weight of 

- selecting 1 feature is 1/M
- selecting 2 feature is 1/M
- ...
- selecting |S| features is 1/M
- ...
- selecting M feature is 1/M

and the total number of case of selecting |S| features is (M Combination S) * (S factorial).
I used Combination because |S| doesn't care about the order of S.
![codecogseqn](https://user-images.githubusercontent.com/2246216/41510572-f71b39fa-721b-11e8-90cd-19d20a0c12c4.png)

But the paper shows 
![codecogseqn 1](https://user-images.githubusercontent.com/2246216/41510581-30100114-721c-11e8-92da-f385ec0831d3.png)

as the weight. I couldn't find the proof for deriving the weight. How the weight in paper derived and what am I missing?

Thanks for reading.

**Comment by slundberg** [comment]
Good question. `(M combination S)` should be `(M-1 combination S)` since the feature `i` is not in the set we are choosing from. That when multiplied by `1/M` gives the desired answer.
