### ISSUE TITLE
Interpreting a single prediction in case of imbalanced dataset

### ISSUE THREAD

**Issue by pranut** [shap/shap#1183]
@slundberg Great work on SHAP!

Building off on this issue:
https://github.com/slundberg/shap/issues/946

I am working on a binary classification problem and wanted to see if the following scenario could exist. Suppose, I am using XGBoost for training, in case of a highly imbalanced dataset, the average expected or base value for probability is 0.3 i.e., the dataset has much more 0s than 1s.

Now suppose, XGBoost returns the probability for a prediction as 0.4 and I am thresholding the probability at 0.5, so the prediction is still a 0.

Would this affect interpretation of SHAP values to explain the 0 prediction compared to the case when the base value is 0.5 in a balanced dataset and the model output probability is 0.4 again resulting in the prediction of 0 (i.e., <0.5)?

Thanks!

**Comment by desertnaut** [comment]
SHAP does not know anything about thresholding, which is a process external to the ML model itself, let alone about a "baseline" of 0.5 in a hypothetical balanced dataset; in all examples, you'll see that what is of concern is the *probabilistic* output of a classifier, not the "hard" class prediction of 0/1. As nicely put in the Cross Validated thread [Reduce Classification Probability Threshold](https://stats.stackexchange.com/questions/312119/reduce-classification-probability-threshold):

> Choosing a threshold beyond which you classify a new observation as 1 vs. 0 is not part of the *statistics* any more. It is part of the *decision* component.

 In what you describe, what you get are explanations about the difference between your prediction of 0.4 and the expected probability value of 0.3.
