### ISSUE TITLE
calling shap.TreeExplainer() in a loop for individual trees

### ISSUE THREAD

**Issue by markusloecher** [shap/shap#1184]
When calling `shap.TreeExplainer()` in a loop, the following observation is puzzling: if I explicitly call `tree.predict()`, in the loop, the `shap.TreeExplainer(tree)` prints its message "*Setting feature_perturbation ...*" for each iteration in the for loop, which "proves" to me that it is being executed each time. But not when the `tree.predict()` is commented out. In that case, the message is printed only once, and I am worried that `shap.TreeExplainer(tree)` is not really executed every time?

[A short notebook is posted here](https://github.com/markusloecher/shap/blob/master/Explore/RandomForestSHAP.ipynb)

**Comment by slundberg** [comment]
That is odd. I think it must have to do with the warnings package or with how Jupyter is dealing with repeated stderr outputs...but I don't know. It is really executed since `print(id(explainer))` changes through the loop.

**Comment by markusloecher** [comment]
Thanks, that is very good to know!
