### ISSUE TITLE
"NameError: name 'Model' is not defined" when running example

### ISSUE THREAD

**Issue by samupino** [shap/shap#1186]
I'm trying to run the [MNIST example notebook](https://slundberg.github.io/shap/notebooks/deep_explainer/Front%20Page%20DeepExplainer%20MNIST%20Example.html) on a Kaggle notebook.

I'm importing keras through the tensorflow submodule, so I changed the initial imports by adding `tensorflow.` at the beginning:
```
import tensorflow.keras as keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
```

I would like to explicitly pass the layers of the network to explain, but when I run the line
```
e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)
```

I get the following error
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-4ea374755383> in <module>
     10 #e = shap.DeepExplainer(model, background)
     11 # ...or pass tensors directly
---> 12 e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)

/opt/conda/lib/python3.6/site-packages/shap/explainers/deep/__init__.py in __init__(self, model, data, session, learning_phase_flags)
     78 
     79         if framework == 'tensorflow':
---> 80             self.explainer = TFDeepExplainer(model, data, session, learning_phase_flags)
     81         elif framework == 'pytorch':
     82             self.explainer = PyTorchDeepExplainer(model, data)

/opt/conda/lib/python3.6/site-packages/shap/explainers/deep/deep_tf.py in __init__(self, model, data, session, learning_phase_flags)
    105             if type(model) is tuple or type(model) is list:
    106                 assert len(model) == 2, "When a tuple is passed it must be of the form (inputs, outputs)"
--> 107                 self.model = Model(model[0], model[1])
    108             else:
    109                 self.model = model

NameError: name 'Model' is not defined
```

My libraries versions are:
```
> print(tensorflow.__version__)
2.1.0
> print(tensorflow.keras.__version__)
2.2.4-tf
> print(shap.__version__)
0.35.0
```

I am probably missing something obvious, sorry but I am new to Python. I would like to understand if it is a version issue or something else and how to solve it.

**Comment by kevinioi** [comment]
It looks like there are a few errors and incomplete lines in the deep_tf.py module.  
This line just needs to be changed to:
`self.model = keras.Model(model[0], model[1])`

**Comment by samupino** [comment]
Thank you, modifying the following lines solved this particular issue

```
90 - import keras
90 + import tensorflow.keras as keras

107 - self.model = Model(model[0], model[1])
107 + self.model = keras.Model(model[0], model[1])
````

**Comment by yzclaire** [comment]
I received the same error message " name 'Model' is not defined"   when trying to make image_plots. Is the updates available in more later version of SHAP? Thank you.

```
# select a set of background examples to take an expectation over
background = x_train[np.random.choice(x_train.shape[0], 100, replace=False)]

# explain predictions of the model on four images
e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)

shap_values = e.shap_values(x_test[1:5])

# plot the feature attributions
shap.image_plot(shap_values, -x_test[1:5]).
```


Here is my version:
print(tensorflow.__version__)
print(tensorflow.keras.__version__)
print(shap.__version__)

2.4.0-dev20200721
2.4.0
0.35.0

**Comment by mesgithu** [comment]
history=model. fit_generator(
        train_generator,
        steps_per_epoch=1427,
        epochs=25,
        test_data=test_generator,
        test_steps=420)

but i got this error.NameError                                 Traceback (most recent call last)
<ipython-input-5-687f90c724d0> in <module>
      2 import tensorflow as tf
      3 
----> 4 history=model.fit_generator(
      5         train_generator,
      6         steps_per_epoch=1427,

NameError: name 'model' is not defined

**Comment by SumitSinghRawat25** [comment]
![Untitled](https://user-images.githubusercontent.com/87383067/125823306-571e89c0-2653-488f-99fb-89e1d1504dd2.png)
can you help me in this

**Comment by atifwebsite** [comment]
file=open("model.pkl",'wb')
pickle.dump(model, file)


NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_26304/1380011602.py in <module>
      1 file=open("model.modle",'wb')
----> 2 pickle.dump(model, file)

NameError: name 'model' is not defined

how to solve this error

**Comment by amudha-vit** [comment]
model.compile(
  loss='categorical_crossentropy',
  optimizer='sgd',
  metrics=['accuracy']
)

NameError: name 'model' is not defined

how to solve this error

**Comment by Marx-wrld** [comment]
NameError in Python often occurs because you have written a variable in your code, but you haven't told python what that variable is. e.g - name = 'Bob'
In your situation, the name model has not been defined on what it really is.

**Comment by ANIKETNAVADKAR143** [comment]
validation_steps=28,

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-3-b01e4ac73f9f>](https://localhost:8080/#) in <module>
----> 1 history = model.fit_generate(
      2         training_set,
      3         steps_per_epoch=80,
      4         epochs=10,
      5         validation_data=test_set,

NameError: name 'model' is not defined


help me with this ????

**Comment by ANIKETNAVADKAR143** [comment]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-3-b01e4ac73f9f>](https://localhost:8080/#) in <module>
----> 1 history = model.fit_generate(
      2         training_set,
      3         steps_per_epoch=80,
      4         epochs=10,
      5         validation_data=test_set,

NameError: name 'model' is not defined
![Capture](https://user-images.githubusercontent.com/111845871/219645193-e080c2d7-d4f7-4667-8ba7-a46eb6c1a9b8.PNG)

**Comment by sontaya512** [comment]
NameError                                 Traceback (most recent call last)
[<ipython-input-38-9923c69c8986>](https://localhost:8080/#) in <cell line: 1>()
----> 1 fc, se, conf = model_fit.forecast(len(test_df), alpha=0.05)  # 95% conf

NameError: name 'model_fit' is not defined

**Comment by Priya-gawhane** [comment]
18 # Get activations for a specific layer
     19 layer_name = 'block5_conv3'  # Replace with desired layer
---> 20 intermediate_layer_model = Model(inputs=model.input,
     21                                  outputs=model.get_layer(layer_name).output)
     22 intermediate_output = intermediate_layer_model(x)
     24 # Generate heatmap

NameError: name 'Model' is not defined
