### ISSUE TITLE
SHAP DeepExplainer with TensorFlow 2.1.0 LSTM various errors

### ISSUE THREAD

**Issue by MathiesW** [shap/shap#1193]
Hi,
I am using SHAP 0.35.0 with TensorFlow 2.1.0 and an LSTM model "model". Depending on how I call the DeepExplainer, I get different errors:

1. calling shap.DeepExplainer(model, x_train) results in **LookupError: gradient registry has no entry for: shap_TensorListStack** and **err: 'TFDeepExplainer' object has no attribute 'between_tensors**
2. calling shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), x_train) results in **NameError: name 'Model' is not defined**. This error refers to the line self.model = Model(model[0], model[1]) in deep_tf.py.

Any suggestions?

**Comment by maxammann** [comment]
https://github.com/slundberg/shap/issues/885#issuecomment-564778328

**Comment by MathiesW** [comment]
Alright, thank you. I did not see the post by Lundberg. I will stick to the workaround of using TF 1.15 until a new version of SHAP is released.
