### ISSUE TITLE
Can shap_values() be used one new row at a time?

### ISSUE THREAD

**Issue by ghost** [shap/shap#1194]
I am using CHAP to explain LightGBM for a binary classification problem. After training the model, I wanted to see if I can use CHAP to explain the 7th row of the test data. So I did the following:

![Screen Shot 2020-05-01 at 8 48 24 PM](https://user-images.githubusercontent.com/25801835/80854481-987c1480-8bed-11ea-9986-5d8d3983bcdd.png)

Two questions here:

(1) Is this a valid use of CHAP?
(2) How is the base value determined, since I just passed one row of the data to CHAP?

Note that the test data had not gone through the model before the 7th row was passed to CHAP.

**Comment by stephenpardy** [comment]
I think this is a totally valid use of SHAP. The base value in TreeExplainer is determined by the model itself - and so depends on whatever build data you used.
