### ISSUE TITLE
Difference between shap.sample and n_samples

### ISSUE THREAD

**Issue by athenawisdoms** [shap/shap#1197]
Hi, I am using the `KernelEstimator` on a XGBoost model trained on a training dataset `X_train` of shape `(1000000, 50)` and test dataset `X_test` of shape `(100000, 50)` so this is going to take a long time. `TreeEstimator` is way better for this purpose, but I am just exploring `KernelEstimator` and using the XGBoost model as an example.

In order to reduce the computation time, I came across the possibilities of using

    shap_values = explainer.shap_values( shap.sample(X_test, 100) )

and the `nsamples` parameter in

    shap_values = explainer.shap_values(X_test, nsamples=100)

What is the difference between the 2 different code above?

Also, should we be passing the training data set `X_train` or the test data set `X_test` when using `explainer.shap_values()`?

Additionally, when creating the summary set `X_summary` using `shap.kmeans(X_test, n_clusters)`, how do we decide on the number of clusters, for say when we have 50 features?

Thank you!

**Comment by HughChen** [comment]
`shap.sample` just subsamples a data set.  So for your first line it's just explaining 100 `X_test` samples.

`nsamples` is a parameter relevant to KernelExplainer and SamplingExplainer that gives you better estimates of the shap values as the `nsamples` increases.
