### ISSUE TITLE
DeepExplainer returns extremely high shap values for conv1d model on spectral input data

### ISSUE THREAD

**Issue by philibb** [shap/shap#1203]
Hi Scott,

thanks for the great work. 

Unfortunately I am having some trouble with the DeepExplainer. For my multi-class tensorflow.keras.sequential (tf 2.1) model (12 classes with softmax output) the DeepExplainer returns shap values in the range of -20 to +20. And most of the shap values are close to zero.

The input data to the model is a light absorption spectrum, so neighbouring features/channels in the spectrum are strongly correlated:
![data](https://user-images.githubusercontent.com/23077713/81412761-a3322e80-9144-11ea-9163-8036e0e89e88.PNG)

The model I use contains following layers: Reshape (adding a dim for Conv1D), Conv1D, MaxPooling1D, Dropout, Flatten, Dense.

And following actitivations: ReLu and Softmax in the output layer.

As background I use 1000 datapoints (distributed in a stratified manner along the classes).

I tried calculate shap_values for 30 datapoints from the 1000 background datapoints, but also for 30 completely new datapoints. Always with the same result. The shap values are always ridiculously high (-20,+20) with most of them being close to zero.

The distribution of predicted probabilites for all classes are visualized in this plot:
![hist](https://user-images.githubusercontent.com/23077713/81412824-bb09b280-9144-11ea-9b7f-f346d749f3cc.PNG)

I am wondering what might be the cause for these high shap values. To demonstrate I also attached the shap summary dot plot:
![dots](https://user-images.githubusercontent.com/23077713/81412836-c1982a00-9144-11ea-87e1-88f5f4b10e69.PNG)

My guesses are/were:

- the shap values are not properly scaled (e.g. logit output) or
- the correlated input features are a problem or
- the model partially overfits and therefore a small shift in the input space causes a complete different model-output screwing up the shap values or
- using the same datapoints for background and then shap-value-calculation is a problem

In comparison my xgboost model on a pca transform of the same input data is working great with the TreeExplainer.

I would be super thankful, if you have a suggestion what might cause this problem.

Thanks in advance and best wishes
Philipp

Btw: 
I think the following import is missing in the DeepExplainer 'from tensorflow.keras.models import Model' as I got an exception when using the tuple model-formulation saying: 
NameError: name 'Model' is not defined

**Comment by wangxq36** [comment]
Can you share your code?
