### ISSUE TITLE
Loky crashes when calculating shap values with a large scikit-learn RF model

### ISSUE THREAD

**Issue by akuhnregnier** [shap/shap#1204]
## Problem - cannot parallelise `shap_values()` using joblib (loky)

When using the [loky](https://loky.readthedocs.io/en/stable/) parallel backend from [Joblib](https://joblib.readthedocs.io/en/latest/) with a scikit-learn `RandomForestRegressor`, calling the `TreeExplainer.shap_values()` method crashes the worker processes:

> joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGSEGV(-11)}

However, this _only_ happens when passing an existing `TreeExplainer` instance to the worker processes, for a model above a certain size/complexity. 

The module that `loky` uses for serialisation doesn't seem to matter either, as the same error occurs with or without `cloudpickle`, which is used by `loky` by default, but can be turned off using:
```
from joblib.externals.loky import set_loky_pickler
set_loky_pickler('pickle')
```

Interestingly, using the joblib `multiprocessing` backend for the same cases where the above error occurs (using the loky backend) results in a situation where the worker processes never terminate, without any CPU utilisation.

#### Create the `TreeExplainer` within each worker function

Giving the workers the `RandomForestRegressor` instance and then re-creating a `TreeExplainer` within each worker function resolves the issue (as far as I can tell).

#### Don't use loky

Additionally, other means of initiating multi-processing don't seem to be affected by this (unpickled vs. newly created `TreeExplainer`) at all; these work as expected for example: 
 - `multiprocessing.Pool`
 - dask distributed [`LocalCluster`](https://docs.dask.org/en/latest/setup/single-distributed.html)

The same is true for threading, but there isn't any speed-up of course.

### Failing cases

I have only tested this using `RandomForestRegressor`.
I observed the error for a training dataset with 1,000,000 rows and 2 or 20 columns, and a `RandomForestRegressor` with `max_depth=12`, and `n_estimators=200`:
```
RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=12, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)
```
Depending on the training dataset `X` (uniformly distributed random data), the number of leaves in the 200 trees varied:
 - 1,000,000 rows by 2 columns: (mean ± std) 2531 ± 82, min. 2296, max. 2729 leaves
 - 1,000,000 rows by 20 columns: (mean ± std) 4080 ± 5, min. 4063, max. 4094 leaves

The target variable `y` for the regression was always a simple linear function of the input features.

### Example code

A short script to recreate the error:
```
import os
from functools import partial
from multiprocessing import Pool
from time import time

import numpy as np
from joblib import Parallel, delayed, parallel_backend
from scipy.stats import describe
from shap import TreeExplainer
from sklearn.ensemble import RandomForestRegressor


def get_shap_values(explainer, X, y, samples, est=None):
    """Using a saved copy of a model, calculate SHAP values.
    Args:
        explainer (shap TreeExplainer):
        X (array-like): Training data.
        y (array-like): Training target.
        samples (int): Number of samples to compute SHAP values for.
        est (Tree-Estimator): If given, a new TreeExplainer will be constructed and
            used, meaning that `explainer` is not used.
    """
    if est is not None:
        print("Constructing new explainer")
        # Construct a new TreeExplainer.
        explainer = TreeExplainer(est, feature_perturbation="tree_path_dependent")
    else:
        print("Re-using explainer")

    start = time()
    values = explainer.shap_values(X[:samples], y[:samples])
    shap_time = time() - start
    return (
        values,
        " ".join(map(str, ("PID:", os.getpid(), "time taken for SHAP", shap_time))),
    )


if __name__ == "__main__":
    np.random.seed(1)

    N = int(1e6)
    col = 2
    n_estimators = 200
    max_depth = 12
    cores = 4
    pass_explainer = True  # True triggers the error.

    X = np.random.random((N, col))
    est = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth)

    factors = np.linspace(0, 1, X.shape[1])
    y = sum(
        X[:, i] * factor + np.random.random(X.shape[0]) * 0.8
        for i, factor in enumerate(factors)
    )
    feature_names = [f"feature {i}" for i in range(len(factors))]

    print("Fitting model (this may take a while)...")
    with parallel_backend("threading", n_jobs=cores):
        est.fit(X, y)

    print(est)
    print(describe([tree.get_n_leaves() for tree in est.estimators_]))

    if pass_explainer:
        explainer = TreeExplainer(est, feature_perturbation="tree_path_dependent")
        est = None
    else:
        explainer = None

    shap_func = partial(get_shap_values, explainer, X, y, 10, est=est)

    # The simplest case - no multi-processing.
    results = (shap_func(),)
    print("No multiprocessing - done.")

    # Using the python multiprocessing backend works.
    with Pool(processes=cores) as pool:
        async_results = [pool.apply_async(shap_func) for i in range(cores)]
        results = [async_result.get() for async_result in async_results]
    print("Multiprocessing Pool - done.")

    # The failing case - the loky executor.
    with parallel_backend("loky", n_jobs=cores):
        results = Parallel()(delayed(shap_func)() for i in range(cores))
    print("Loky - done.")
```

Please see https://gist.github.com/akuhnregnier/d2af98b4efea0eadcc9ee47ef38eefeb for a short command line script to re-create the error:
```
python multi_proc_shap.py -N 1000000 --cols 20 --cores 2 --estimators 200 --max-depth 12 --backend loky --pass-explainer
```
Note that this will store the training data and the trained model in the `tempfile.gettempdir()` temporary directory (in the `shap_multi_data`) folder to speed up re-running of tests with different multi-processing methods for the same model.

Please see this file for package versions used (the issue persists after installing `shap` from the `master` branch): https://gist.github.com/akuhnregnier/d2af98b4efea0eadcc9ee47ef38eefeb#file-environment-yml

The code was run on:
```
Linux 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I'm not sure what is going wrong here, and if it is exclusively related to `Joblib`, or to `shap` as well. If you think this issue doesn't belong here but rather with `Joblib`, feel free to close it. 

A short caveat in the documentation to alert users to this quirk might be useful.

**Comment by christabella** [comment]
I was also running into the hanging (processes never terminate) issue with`multiprocessing`.

```
from multiprocessing import Pool
from tqdm import tqdm
from functools import partial


shap_values = []
with Pool() as p:
    shap_values = list(tqdm(p.imap(partial(explainer.shap_values, nsamples=5, l1_reg="aic"), 
                                               data.iloc[:,:].values, 
                                               chunksize=10),
                                        total=data.shape[0]
                                       )
                                  )
```

or

```
from tqdm.contrib.concurrent import process_map  # or thread_map

shap_values = process_map(partial(explainer.shap_values, nsamples=5, l1_reg="aic"), 
                                               data.iloc[:,:].values,
                                       )```

**Comment by RichardScottOZ** [comment]
Thanks for that.
