### ISSUE TITLE
image_plot doesn't return anything regardless of "show" argument.

### ISSUE THREAD

**Issue by Justus-M** [shap/shap#1209]
The description in image_plot.py says 
"show : bool
        Whether matplotlib.pyplot.show() is called before returning. Setting this to False allows the plot to be customized further after it has been created."

However, image_plot is a procedure that doesn't seem to return anything so how can you customize the plot further?

**Comment by midhunharikumar** [comment]
I'm facing the same issue.
`shap.image_plot(shap_values[:3],width=800,show=False)`  shows the image (in jupyter). Using `plt.savefig()` saves a blank image.

**Comment by midhunharikumar** [comment]
This issue seems to be due to Jupyter lab and its inline matplotlib display. When I move the script out of Jupyter to a standalone script `plt.savefig()` works as expected along with `show=False` .
