### ISSUE TITLE
Auto-display in Jupyter Notebook when running via python script

### ISSUE THREAD

**Issue by vaughnkoch** [shap/shap#121]
This works great:
```
import shap
shap.initjs()
shap.force_plot(...)
```

But, if you're running the above code in a script, then it will not output anything to the notebook, e.g.
```
%run shap_display_script.py
```

Since `force_plot` returns a python HTML object, it doesn't display inside the script unless you wrap it in display, like so:

```
from IPython.display import display
display(shap.force_plot(...))
```

When I tried out the example in a script, the code ran but just output the JS symbol. It took me a while to narrow down the problem to the fact that display was missing.

Even better, the IML code could call display directly if it detects a notebook. I'm using code that can do that detection, happy to share.

**Comment by slundberg** [comment]
Thanks for the info! And yes, please share the code you are using to detect the notebook. We can dump that into IML.

**Comment by vaughnkoch** [comment]
Here's the code I'm using. I modified it from the stackoverflow answer. There is probably a more robust way of doing it, especially using something other than the singleton to cache it.

```
# Returns True if the current execution context is an IPython notebook, e.g. Jupyter.
# https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

# Singleton cache
IN_IPYNB = None

def in_ipynb():
  if IN_IPYNB is not None:
    return IN_IPYNB

  try:
    cfg = get_ipython().config
    if str(type(get_ipython())) == "<class 'ipykernel.zmqshell.ZMQInteractiveShell'>":
    # if cfg['IPKernelApp']['parent_appname'] == 'ipython-notebook':
      # print ('Running in ipython notebook env.')
      return True
    else:
      return False
  except NameError:
    # print ('NOT Running in ipython notebook env.')
    return False
```

**Comment by slundberg** [comment]
Just wanted to say thanks! ...I have been busy so I am not sure when it might get dumped in but it is good to have the code here.

**Comment by andrejastojic** [comment]
Is there a way to display shap.force_plot in RStudio via reticulate library?

Thanks in advance!

**Comment by slundberg** [comment]
I don't think RStudio supports HTML rendering, but I am no R expert.

**Comment by andrejastojic** [comment]
Thanks!
