### ISSUE TITLE
Pull requested checks fail

### ISSUE THREAD

**Issue by YotamElor** [shap/shap#1212]
Hi,

Just submitted a pull request and one of the checks failed. The failure has nothing to do with the changes I made. I also notice that several few other pull requests failed similarly.

Please advise,
Thank you,
Yotam

**Comment by lrjball** [comment]
Hi @YotamElor, I think you are referring to the decode issue in Xgboost, like in #1215. It should be fixed in PR #1220

**Comment by YotamElor** [comment]
Thank you
