### ISSUE TITLE
Negative SHAP expected value

### ISSUE THREAD

**Issue by mayur29** [shap/shap#1213]
Hi Scott,

Thank you for this wonderful library. I have a question regarding expected value property of explainer. 

In your notebook Census income classification with LightGBM

![image](https://user-images.githubusercontent.com/6712151/82123832-b2942600-979b-11ea-9d4c-f854a4dde240.png)

What does this array mean for expected value , how can value be negative here

**Comment by thoo** [comment]
The negative is probably coming from log loss.

**Comment by waterknows** [comment]
Yes. It should be equal to model.predict(X, raw_score = True).mean()
