### ISSUE TITLE
how to figure out whether the model works in the right way or not?

### ISSUE THREAD

**Issue by chansource** [shap/shap#1227]
Hi，since the shap gives an insight into how the change of the features affect the  prediction of the model, is there any criterion to figure out wether the model work in the right way? 

For example, if the shap says that  mortality decreases with age, the model maybe wrong. But it is difficult to know how should the prediction changes with the feature in practice. So i wander whether there is any criterion can help.

Furthermore, if the model is not right , is there any common tools can point out  how to fix ?

thank you in advance for your help.
@slundberg

**Comment by InterferencePattern** [comment]
This would require significant domain knowledge and is unfortunately beyond the scope of a general model-explaining tool.

**Comment by detrin** [comment]
@chansource This is where the art of doing Data Science comes in. Without the domain knowledge the tools are just tools. What I do usually is use those rules for reducing dimensionality before the whole ML exercise. For example when performing binning you can use `monotonic_trend` http://gnpalencia.org/optbinning/tutorials/tutorial_binary.html

@thatlittleboy CFC
