### ISSUE TITLE
(Paper): Implementation differences KernelShap with shapley sampling values

### ISSUE THREAD

**Issue by Toekan** [shap/shap#123]
Hi,

I've been digging a bit deeper into the SHAP paper and the shapley sampling values paper and would like to understand the differences better, so I have several questions:

1. Both SHAP and shapley sampling values use the expectation value conditional on the features in a given subset of features over the data distribution to integrate out the non-included ("toggled off") features. Is that correct? If so, what are the theoretical differences between SHAP values and shapley sampling values?

2. Shapley sampling values are calculated by sampling both from the data distribution and permutation of features distribution at the same time. KernelShap on the other hand, does not sample the data distribution, but does sample the permutation distribution and then calculates the model outcomes for that feature subset over the whole given dataset? (which could be the training set, kmeans of the training set or just the mean). If so, in theorem 2, the equivalent of sampling from all possible permutations is sampling a number of z' from the Z space, which is possible vectors in the M-dimensional binary space? f(h_x(z')) is then calculated by integrating out the whole given background dataset for the features not included in z'. The final step is then to solve a linear regression where f(h_x(z')) are the 'y-values' and z' the M-dimensional independent variable space and the SHAP values the coefficients to be solved. Is this correct?

3. If 2 is correct, is it correct that you need a minimum of M+1 samples of the permutation space to be able to solve the linear regression? 

I hope these questions make sense and thanks for the package again. :)

**Comment by slundberg** [comment]
Good questions.

1) At a high level, the Štrumbelj and Kononenko paper on shapley sampling values is where using Shapley values to explain machine learning models was first introduced, while our work on SHAP values represents a unification of these ideas with several other approaches and associated improvements in their estimation and justification. I think they don't do a conditional expectation but just an expectation without conditioning on other features (equivalent to the feature independence assumption of Kernel SHAP). They also reference a different older set of properties for the uniqueness of Shapley values that are less applicable to ML interpretation (for example they don't use the consistency property). So the values they estimate are the same as Kernel SHAP while the estimation method they use (Shapley sampling) is different and based on the original definition by Shapley. I should note that we used the term SHAP values to distinguish Shapley values (which could apply to any definition function of subsets) from Shapley values applied to conditional expectations. We even have a SamplingExplainer object now that is an improved version of the Shapley sampling values approach.

2) Correct, with the small clarification that the Shapley kernel has infinite weights that effectively eliminate two of the free parameters before the linear regression. I should also note that because Kernel SHAP separates the sampling from the expectations is can also support a non-linear link function.

3) Well, only if you have no regularization. By default Kernel SHAP will try and use L1 regularization, so if you have 10000 features where only a few matter than you don't need 10001 samples.

Hope that helps!

**Comment by snowde** [comment]
I have spent a few days looking at some of these papers and implemented some practical techniques. In the process, I came to a few conclusions regarding the issue of multicollinearity damping feature importance. 

Without removing features you can make significant use of column subsampling techniques (LightGBM  - params["bagging_fraction"] = 0.20). Second, you can further correct for multi-collinearity-dampening by mean adjusting variable A's aggregate absolute shapely values with the product of all other variable's to variable A correlations. Thus when a variable has a low Shapley value, but many others are slightly correlated with it, as opposed to not correlated with it, it will have a higher absolute aggregate adjusted value. Once I create something more formally, I will add it here.

**Comment by slundberg** [comment]
@snowde Thanks for the comments! Bagging features does seem like it would spread credit among correlated features. I would also be interested in anything you come up with for post-adjusting the importances. A formally motivated way to do that would be useful in many circumstances.

**Comment by snowde** [comment]
**Effectively**: Adjust for the fact that variables with low abs(SHAP) might be correlated with variables with high values.

**Result**: Smaller discrepancies between features, more stable with different feature selections and randomness (i.e. changes of bagging and feature fractions as well as seeds), won't mistakenly get rid of a feature that might have causal, albeit substitutable, importance   

To test it:
1. Tried multiple fraction alternatives.
2. Averaged over multiple retakes for different seeds
3. Take the product of the relative (to max) portion of subject variable's SHAP_abs values and the associated correlation
      a)  `shap_fin["SHAP_Corr_Corrrected"].loc[c] = shap_fin["SHAP_Corr_Corrrected"].loc[c] + (shap_fin["SHAP_abs"].loc[b]/shap_fin["SHAP_abs"].max())*v`
    
```

import shap
import lightgbm as lgb

df = loadit

X_train = df[df["is_test"]==False].drop(cols_drop,axis=1)
y_train = df[df["is_test"]==False]["Churn"]

X_test = df.loc[df.is_test, :].drop(cols_drop, axis=1)
y_test = df.loc[df.is_test, :]["Churn"]

d_train = lgb.Dataset(X_train, label=y_train)
d_test = lgb.Dataset(X_test, label=y_test)

splits = 5 
f = -1
for seeds in [15,1,6,7,2]:
    f = f +1
    print(seeds)
    params["feature_fraction_seed"] = seeds
    
    params["random_seed"] = seeds + 1
    
    params["feature_fraction"] = 0.2
    params["bagging_fraction"] = 0.2
    
    model = lgb.train(params, d_train, verbose_eval=1000)

    shap_values = shap.TreeExplainer(model).shap_values(df.drop(cols_drop, axis=1))

    shap_fram = pd.DataFrame(shap_values[:,:-1], columns=list(X_train.columns))

    shap_new = shap_fram.sum().sort_values().to_frame()

    shap_new.columns = ["SHAP"]

    shap_new["SHAP_abs"] = shap_new["SHAP"].abs()

    direction = df.corr()["Churn"].to_frame()
    direction.columns = ["corr"]
    shap_new = pd.merge(shap_new, direction, left_index=True, right_index=True, how="left")

    shap_new["abs_corr"] = shap_new["corr"].abs()
    
    if f==0:
        shap_fin = shap_new
    else:
        shap_fin = shap_fin + shap_new

shap_fin.loc[:,["SHAP","SHAP_abs","corr","abs_corr"]] = shap_fin.loc[:,["SHAP","SHAP_abs","corr","abs_corr"]]/splits

cors_all  = df.corr()[df.corr().index.isin(list(shap_fin.index))].abs()
for b in cors_all.iloc[:,2:].columns:   # iloc to remove feature id columns
    cora = df.corr()[df.corr().index.isin(list(shap_fin.index))][b].abs()
    for c, v in zip(cora.index, cora.values):
        shap_fin["SHAP_Corr_Corrrected"].loc[c] = shap_fin["SHAP_Corr_Corrrected"].loc[c] + (shap_fin["SHAP_abs"].loc[b]/shap_fin["SHAP_abs"].max())*v
```

**Comment by Toekan** [comment]
Scott, thanks for the answers on my question!

**Comment by mateisc** [comment]
@slundberg concerning your answer to Toekan's question 3:

"3. Well, only if you have no regularization. By default Kernel SHAP will try and use L1 regularization, so if you have 10000 features where only a few matter than you don't need 10001 samples."

Theorem 2 in your NIPS '17 paper specifies $\Omega(g) = 0$ which would mean "no regularization". If we add regularization (e.g. L1 as you mention), do we still get the SHAP values by solving the weighted linear regression?

Also, from Section "5.1 Computational Efficiency" of the paper I understand that Kernel SHAP is better than Shapley sampling "particularly when regularization is added to the linear model (Figure 3)". This suggests again that regularization is applied to the weighted linear regression giving the SHAP values of g (which again, to my understanding, does not fit to Theorem 2). 

Did I get anything wrong?

**Comment by slundberg** [comment]
@mateisc great questions! If you want to exactly compute Shapley values with weighted linear regression then you need to completely enumerate all subsets of features. In practice you won't do that if you have more than 10 or 15 features so you will instead sample from the Shapley kernel. This results in an unbiased approximation of the Shapley values. But, as is typical for regression, you can achieve lower error by introducing some bias. L1 regularization adds bias towards sparse solutions (which are expected for many high dimensional problems). You are right that with L1 regularization you now have a biased estimate of the Shapley values, but it now has lower variance and will still converge to the correct values in the limit of many samples (assuming your regularization term scales with sample size).
