### ISSUE TITLE
tree_path_dependent warning, even when set explicitly. 

### ISSUE THREAD

**Issue by gsbowlin** [shap/shap#1236]
Https://github.com/slundberg/shap/blob/master/shap/explainers/tree.py

Issue is on line 113

```python
        if self.data is None:
            feature_perturbation = "tree_path_dependent"
            warnings.warn("Setting feature_perturbation = \"tree_path_dependent\" because no background data was given.")
```

In my case, data is `None`, but I set  `feature_perturbation = "tree_path_dependent"`

But the error fires because it is not specific enough, should be 

```python
if self.data is None and feature_perturbation != "tree_path_dependent":
```

**Comment by InterferencePattern** [comment]
Changed in Pull Request #1267
