### ISSUE TITLE
Bug in ax argument for dependence_plot

### ISSUE THREAD

**Issue by fonnesbeck** [shap/shap#1239]
There is a bug in the optional `ax` argument that prevents dependence plots being generated on a grid of subplots. For example, the following:

```python
fig, axes = plt.subplots(3, 3, figsize=(12,10))

for i,ax in enumerate(axes.flatten()):
    variable = feature_importance.loc[i, 'Feature Id']
    shap.dependence_plot(variable, shap_values, X_test, 
                         ax=ax, interaction_index=None)
```

Generates this output:

![image](https://user-images.githubusercontent.com/81476/83156010-7d56d480-a0c7-11ea-8684-5c6e0ed9a73c.png)

So, the first subplot is generated as expected, but none of the subsequent plots work. I have confirmed that `feature_importance` is a DataFrame with a long list of feature IDs in the "Feature Id" column. Not sure why it would generate one, but not the others. I have also confirmed that I can generate any dependence plot by itself, not using the `ax` argument. There are no exceptions thrown.

Running shap 0.35.0 on Python 3.8.2

**Comment by nocluebutalotofit** [comment]
I encountered a similar issue.

**Comment by rakke** [comment]
@fonnesbeck: Have you tried adding this:
`shap.dependence_plot(...., show=False)`

**Comment by yuxichen2435** [comment]
@fonnesbeck I encountered the issues, and was able to solve it with the solution mentioned by @rakke.

**Comment by fonnesbeck** [comment]
This was so long ago I can't even remember the issue very well, so let's accept @rakke 's solution and close this. Thanks.
