### ISSUE TITLE
SHAP with multi-class classification

### ISSUE THREAD

**Issue by remyels** [shap/shap#1242]
Hi there,

I'm working on using SHAP with multi-class classification. More specifically, I'm using one-vs-all via neural networks that I have trained myself.

Is there a way to limit the explanations of any given observation to its respective classifier?

My model function, which I have passed to `shap.KernelExplainer`, returns an array of probabilities, and each of those probabilities corresponds to the output of one classifier. Isn't SHAP supposed to know which of those labels is of interest, i.e. which corresponds to the class of interest, as is the case for LIME? I couldn't find anything in the documentation regarding this, which is why I have decided to ask...

Thank you!

**Comment by bhrigs** [comment]
Hi, if I have understood your question correctly:

based on the class label you want to focus on, you would change the indices of the expected_value[] and shap_values[] below.  

for class 1: `shap.force_plot(explainer.expected_value[1], shap_values[1][29,:], X_exp.iloc[29,:], link="logit")`

for class 2: `shap.force_plot(explainer.expected_value[2], shap_values[2][29,:], X_exp.iloc[29,:], link="logit")` 

Also refer to [https://www.youtube.com/watch?v=m4el1KDTEV8](url)

If this is not what you are looking for, can you post some code and context to understand the question better.

**Comment by MACILLAS** [comment]
I am also working on a multi-class classification problem and I've got a pretty silly question...

I have classes [A, B, C] and SHAP gives me a list (class 0, class 1, class 2) of nd.arrays. So how do i know which class corresponds to which nd.array? (ie. Is class A --> class 0?)

**Comment by maerzm** [comment]
> Hi, if I have understood your question correctly:
> 
> based on the class label you want to focus on, you would change the indices of the expected_value[] and shap_values[] below.
> 
> for class 1: `shap.force_plot(explainer.expected_value[1], shap_values[1][29,:], X_exp.iloc[29,:], link="logit")`
> 
> for class 2: `shap.force_plot(explainer.expected_value[2], shap_values[2][29,:], X_exp.iloc[29,:], link="logit")`
> 
> Also refer to [https://www.youtube.com/watch?v=m4el1KDTEV8](url)
> 
> If this is not what you are looking for, can you post some code and context to understand the question better.

I also have a multiclass classification problem with 5 classes. I get the probabilities.
Trying the above method I get this error: IndexError: too many indices for array

with this:
shap.force_plot(explainer.expected_value, shap_values[0,:], X.iloc[0,:])
I still get this error:
TypeError: list indices must be integers or slices, not tuple

This works:
shap.force_plot(shap_explainer.expected_value[0], shap_values[0], X_test)
but I need individual explanations 

I would appreciate any suggestion

**Comment by Daanielvb** [comment]
looks like they changed the order of the params for multi-class problems @maerzm. Not sure why
