### ISSUE TITLE
non-column features with SHAP

### ISSUE THREAD

**Issue by noklam** [shap/shap#1246]
Is it possible to group multiple "features" as one feature and pass it to the shape package? For example, can I group multiple columns as one "hyper-column"? I am interested in use case where my input is a graph/multiple columns (only interested in the sum of the columns, also as a mean to speed up)

From my understanding, SHAP is based on permutation of features and assign credits with n-features interaction. So I think it is possible to group features (i.e., when shuffling we always shuffle the group features together).

**Comment by sunshinejnjn** [comment]
try my commit here with feature_groups
#1897
