### ISSUE TITLE
shap.TreeExplainer() is not working when we use Xgboost.fit function.

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#125]
We can get the predicted output when we use xgboost.fit and train model. But It doesn't work when I try to run this code
`shap_values_xgb = shap.TreeExplainer(xgb_clf).shap_values(test.as_matrix())`

**Comment by DiliSR** [comment]
```
param_distribs = {
        "n_estimators": stats.randint(3, 40),
        "max_depth": stats.randint(3, 40),
        "learning_rate": stats.uniform(0.05, 0.4),
        "gamma": stats.uniform(0, 10),
    }
rnd_search = RandomizedSearchCV(xgb.XGBClassifier(random_state=42), 
                                param_distributions=param_distribs, return_train_score=True,
                                n_iter=100, cv=5, scoring='roc_auc', random_state=42, n_jobs=-1)
# this will take a long time
rnd_search.fit(data_train_X, data_train['died_hosp'])
```

```
cv_rlt = rnd_search.cv_results_
pd.DataFrame(sorted(list(zip(cv_rlt["mean_test_score"], cv_rlt['mean_train_score'], cv_rlt["params"])), 
                    key=lambda x: x[0], reverse=True), columns=['X-val scores', 'Train scores', 'Params'])

xgb_clf = rnd_search.best_estimator_
xgb_clf.fit(data_train_X.as_matrix(), data_train['died_hosp'].as_matrix())
with open('../models/xgb_clf_final_round.pkl', 'wb') as f:
    pickle.dump(xgb_clf, f)
```
```
with open('../models/xgb_clf_final_round.pkl', 'rb') as xgb:
    xgb_clf = pickle.load(xgb) 
```

```
class Xgb_clf(BaseEstimator, ClassifierMixin):
    def fit(self, X, y=None):
        return xgb_clf
    def predict_proba(self, X):
        return xgb_clf.predict_proba(X)  
```
`xgb_pipeline.fit(train.as_matrix())`

```
sample_xgb_correct_survived,index_xgb_correct_survived = get_test_sample(xgb_pipeline, correct=True, survived=True, seed=48, count=10)
result_xgb_correct_survived = xgb_pipeline.predict_proba(sample_xgb_correct_survived)
result_xgb_correct_survived
```
Up to here it is working. I got the output of "result_xgb_correct_survived"
`shap_values_xgb = shap.TreeExplainer(xgb_clf).shap_values(test.as_matrix())`

in here I got an error. ValueError: feature_names mismatch

**Comment by DiliSR** [comment]
Could you please tell me the reason. I can predict and get the results from my model. But I can't explain it using SHAP TreeExplainer

**Comment by slundberg** [comment]
Usually feature_names mismatch is because you trained on a dataframe with column names but are trying to explain a numpy array without those names. XGBoost complains because the feature names don't match. Does `shap.TreeExplainer(xgb_clf).shap_values(test)` work?

**Comment by DiliSR** [comment]
shap.TreeExplainer(xgb_clf).shap_values(test)
No this didn't work. it gives that error. Feature names mismatch. But I get the predicted results for new instances. Only this line is not working.

**Comment by DiliSR** [comment]
Model is working properly. I can get the results. Only SHAP explainer is not working. :/

**Comment by slundberg** [comment]
Hmm, well for XGBoost the core algorithm is merged into the XGBoost binary. So in the package we call `xgb_clf.get_booster().predict(test, pred_contribs=True)`. Does that give the same error?

I would suggest making sure you have something that works for the `xgb_clf.get_booster().predict` method. If that works and the TreeExplainer doesn't then I can see if there is a bug.

**Comment by DiliSR** [comment]
I am using here

```
xgb_clf = rnd_search.best_estimator_
xgb_clf.fit(data_train_X.as_matrix(), data_train['died_hosp'].as_matrix())
with open('../models/xgb_clf_final_round.pkl', 'wb') as f:
    pickle.dump(xgb_clf, f)
```

xgb_clf.fit method. Model is working for that as well finely. But to get xgb_clf.get_booster() I need to use xgboost.train(). But still I am trying to change it for that. But I couldn't. My question is your SHAP package is compatible only for the output of xgboost.train(). What about the output of xgb_clf.fit() ?

**Comment by slundberg** [comment]
xgb_clf.fit() is a method of XGBClassifier that follows the sklearn api. shap does support XGBClassifier, but to better debug your error I suggest you use XGBClassifier's get_booster() method to get the raw XGBoost booster object (the same one you get with xgboost.train()) and make sure you can make predictions with that.

**Comment by DiliSR** [comment]
I fixed this one. Thanks

**Comment by slundberg** [comment]
Great!

**Comment by rakash** [comment]
@DiliSR  - can you tell me how you got Shap values for sklearn api(xgbclassifier) ?
