### ISSUE TITLE
summary_plot truncating feature names

### ISSUE THREAD

**Issue by franroma-720** [shap/shap#1254]
I have rather long feature names in the data set I am using. The summary_plot function is cutting off the names of the features on the y axis. Is there a way around this? I have tried several different versions of the shap package (0.29.3, 0.30.0, 0.35.0) and get the same results each time.

Code and screenshot are below.

```python
# Feature importance by SHAP value on training data
explainer = shap.TreeExplainer(bst)
shap_values = explainer.shap_values(X_train,1)

# Summary plot of importance by SHAP value - higher SHAP values represent higher risk of falling
shap.summary_plot(shap_values, X_train, plot_type='dot', max_display=features_list_g.shape[0])
```

![Screen Shot 2020-06-05 at 3 59 37 PM](https://user-images.githubusercontent.com/66493446/83917904-ade0e300-a745-11ea-83f0-d3d53312057d.png)

I have used this package before to produce summary plots without this issue although I do not have a record of which shap package version I was able to do that under. See screenshot below for example:
![Screen Shot 2020-06-05 at 3 59 54 PM](https://user-images.githubusercontent.com/66493446/83917933-b9cca500-a745-11ea-8b07-ad17f99dde57.png)

**Comment by bluemandora** [comment]
I got the same issue while using plt.savefig(). The plot is fine while using plt.show()

**Comment by vinciabhinav** [comment]
You can pass **plot_size** parameter to summary_plot . refer [here](https://github.com/slundberg/shap/blob/93dc2a1e446616fb0858b2ec108f80e4969ba6d9/shap/plots/summary.py#L48)

**Comment by franroma-720** [comment]
That worked! Thank you! I didn't realize there was a new parameter to control for that.

**Comment by Mahmedturk** [comment]
Hi @franroma-720 
how were you able to fix this issue? I am facing the same thing but could not fix with the plot_size argument.

**Comment by robertpknight** [comment]
@Mahmedturk I assume I'm too late to help, but I solved this by using `plt.savefig("test.png",bbox_inches='tight')`
