### ISSUE TITLE
Error: "ufunc 'isfinite' not supported for the input types"

### ISSUE THREAD

**Issue by ori-katz100** [shap/shap#1269]
Hi,
I am using shap.KernelExplainer, since I have custom-made models. I wrote a function that returns a float64 array of the predicted probabilities for my models. The shap.KernelExplainer works, but when I try to calculate explainer.shap_values I get the above error. 

What could be the problem?

**Comment by Nithanaroy** [comment]
Hi @ori-katz100 
How did you resolve this?

**Comment by LeeRock** [comment]
Hi @ori-katz100
How did you resolve this?
