### ISSUE TITLE
SHAP inner workings for an XGBoost classification model 

### ISSUE THREAD

**Issue by srujan741** [shap/shap#1273]
I have been spending some time recently in trying to understand the shapley values and how they are calculated in the SHAP package. The TreeSHAP works well for non linear models like XGBoost but i am having some difficulties with the intuition behind the methodology for Gradient boosted trees where the trees are trained to predict residuals that contribute as correction values to the base estimate of the log odds. From my understanding the shapley values are calculated for each tree and averaged in a random forest where all the trees have an equal say. How are the shapley values calculated in the boosting scenario? Help with this is much appreciated.

**Comment by stephenpardy** [comment]
Short answer: in gradient boosting the SHAP values for each tree is added together instead of averaged liked they are for Random Forests.
