### ISSUE TITLE
Interpreting SHAP values and baselines in TreeExplainer

### ISSUE THREAD

**Issue by ICNoog** [shap/shap#1281]
I am trying to interpret my model (LightGBM regression task) using SHAP, but am confused about what I can actually learn from the output.

I have a regression model that is predicting yield and want to try and find what the model is basing the prediction on, and understand if I can do controlled trials (in the real world) and see the effect of changing features to improve yield.

![Screen Shot 2020-06-22 at 14 49 02](https://user-images.githubusercontent.com/67270785/85284336-ae90ad80-b497-11ea-958e-3754f2065025.png)

So for the above example, feature 2 is bringing down my prediction by -0.73, I understand that the SHAP value is a mean contribution of that feature, but considering it is a numeric feature, how can I understand from this what the impact of increasing or decreasing the value of feature2 will be on my yield? My current understanding of the maths behind this is that all coalitions of features with and without feature2 are measured and then the effect of having feature2 at this value or 'not having feature 2' - which I interpret as giving it the mean value, is measured and the average of these two changes in prediction are the SHAP value.

I want to now know if I increase feature 2 to 350, will my prediction increase/decrease?  If I 'remove it' (does this mean make it the mean of the dataset?) then does it increase/decrease? Surely the negative value means that it will increase?

Any help is much appreciated

**Comment by vinciabhinav** [comment]
Please look into dependence plots : 

- https://slundberg.github.io/shap/notebooks/plots/dependence_plot.html
- see Section : A more complete picture using partial dependence plots [here](https://github.com/slundberg/shap/blob/master/notebooks/general/Explainable%20AI%20with%20Shapley%20Values.ipynb)
