### ISSUE TITLE
Warning: unrecognized nn.Module

### ISSUE THREAD

**Issue by ChenXiao61** [shap/shap#1282]
When I load the fine-tuned model "Efficient-B0", occurred 
"Warning: unrecognized nn.Module: Conv2dStaticSamePadding
Warning: unrecognized nn.Module: MBConvBlock" 
How can I solve this problem?

**Comment by vinciabhinav** [comment]
Your model is probably not supported. [ line 228 in below file ] 
See the list of supported model layers here: https://github.com/slundberg/shap/blob/fc30c661339e89e0132f5f89e5385e3681090e1f/shap/explainers/deep/deep_pytorch.py#L362

**Comment by tamnva** [comment]
I am still facing the same problem with the LSTM network created with pytorch 

"lib\site-packages\shap\explainers\_deep\deep_pytorch.py:243: UserWarning: unrecognized nn.Module: LSTM
  warnings.warn(f'unrecognized nn.Module: {module_type}')"

**Comment by RoyiAvital** [comment]
Any chance to add the `Flatten` and `Identity` layers?
