### ISSUE TITLE
Why exist a difference between Random Forest and Gradient Boosting using TreeExplainer?

### ISSUE THREAD

**Issue by KaikeWesleyReis** [shap/shap#1283]
Hello, 

I'm trying to use `summary_plot` from SHAP in a **binary** classification. The tutorial works well for Gradient Boosting:

![image](https://user-images.githubusercontent.com/32513366/85350488-a6f0f900-b4d7-11ea-8cca-37459c133264.png)

But the **EXACTLY SAME CODE** doesn't work for Random Forest:
![image](https://user-images.githubusercontent.com/32513366/85350552-cb4cd580-b4d7-11ea-97d8-a64cb3b7073c.png)

This output appears to `summary_plot` as "multi-output" and I really don't understand... Can someone say what is happening? It's a problem with Random Forest?

A funny fact: the generated list from RandomForestClassifier is a mirror, look at both  `summary_plot`:

![image](https://user-images.githubusercontent.com/32513366/85350739-50d08580-b4d8-11ea-8215-87bd5ef88f50.png)

The `[1]` is the inverse of `[0]`. Just Why? I can say that shap_values[0] is related to class 0 and shap_values[1] to class 1?

Btw, I really love this module!

**shap version = 0.34.0
Models library = sckit-learn**

**Comment by HughChen** [comment]
My guess is that for XGBoost it's explaining the output margin of the trees which is related to the probability of the positive class and for the RandomForestClassifier it's treating the binary prediction as predicting two classes (the probability of the positive class and the probability of the negative class).

You can probably just use one of the two for the RandomForestClassifier and it should be analogous to the XGBoost explanations.

**Comment by KaikeWesleyReis** [comment]
> My guess is that for XGBoost it's explaining the output margin of the trees which is related to the probability of the positive class and for the RandomForestClassifier it's treating the binary prediction as predicting two classes (the probability of the positive class and the probability of the negative class).
> 
> You can probably just use one of the two for the RandomForestClassifier and it should be analogous to the XGBoost explanations.

You're actually right: the two outputs are opposite: the SHAP values for negative class [0] is equal to minus positive class [1]. I just analyzed one of them, thanks!

**Comment by HughChen** [comment]
Great to hear!
