### ISSUE TITLE
Tensorflow2.2  tensors_blocked_by_false  recurse for ever 

### ISSUE THREAD

**Issue by linchundan88** [shap/shap#1286]
Environment: tensorflow2.2, shap 0.35,  model:keras built-in Inception-v3 

Test1: close eager mode,  
when executing e = shap.DeepExplainer(model, background)
deep_tf.py tensors_blocked_by_false  recurse for ever.

Test2: open eager mode(by default)
  RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by linchundan88** [comment]
tensorflow2.0 eager mode.

  when executing shap_values = e.shap_values(img_input), the following occurs:

    TypeError: Expected float32 passed to parameter 'filter' of op 'Conv2D', got <tf.Variable 'conv2d_1/kernel:0' shape=(3, 3, 
3, 32) dtype=float32> of type 'ResourceVariable' instead. Error: custom_record_gradient() takes 4 positional arguments but 5 were given

**Comment by linchundan88** [comment]
DeepExplainer 

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

check_additivity=False

It runs OK now.

**Comment by Alessiobrini** [comment]
@linchundan88 does this mean that SHAP doesn't integrate with Tf 2.X yet?
