### ISSUE TITLE
Densenet with shap: Warning: unrecognized nn.Module: _Transition

### ISSUE THREAD

**Issue by sahithyaravi** [shap/shap#1288]
When I use the densenet121 model from pytorch,  with DeepExaplainer shap throws two warnings:
Warning: unrecognized nn.Module: _Transition
Warning: unrecognized nn.Module: _DenseBlock.

I understand that this does not mean that the explainer has failed and shapely values are still calculated.  
But does this warning affect the shapely value calculation?

**Comment by xioahua** [comment]
I meet the same issue, are there some effects on Shapley value results?
