### ISSUE TITLE
Shap value doesn't match with lgbm model output

### ISSUE THREAD

**Issue by DwightTRAX** [shap/shap#1293]
Hi!

I'm having a problem similar to Issue [#669](https://github.com/slundberg/shap/issues/669).
I used LGBM regression model and the following is the parameters setting for the trained lgbm model.
------------------------------------------------------------------------------------
```
lgb_reg_params = {
            'objective': 'regression',
            'min_data_in_leaf': 500,
            'num_leaves': 275,
            'num_iterations': 100
        }
lgb_valid = lgb.Dataset(X_valid, y_valid)
            lgb_reg_params['num_iterations'] = 5000
            valid_params['valid_sets'] = [lgb_valid]
            valid_params['valid_names'] = ['validation']
            valid_params['verbose_eval'] = 0
            valid_params['early_stopping_rounds'] = 5
```
------------------------------------------------------------------------------------
I've showed two sample records as reference.
We can see
the first record(j=10):
visualizer's prediction is around 5.66e+35
the model prediction is 1061.48
the second record(j=100):
visualizer's prediction is around -3.02e+32
the model prediction is 9231.95
There are some points I'd like to mention:
1. the model is lightgbm regression model and currently I rely on the lgbm native api
2. the matrix data is scipy sparse matrix
3. the feature space is around 34k 

Couldn't figure why. Any help is appreciated. Thanks :)

![Screen Shot 2020-06-25 at 10 01 14 PM](https://user-images.githubusercontent.com/7435562/85822663-4a3c4b00-b730-11ea-841a-437881ee8d93.png)
![Screen Shot 2020-06-25 at 10 01 26 PM](https://user-images.githubusercontent.com/7435562/85822680-51fbef80-b730-11ea-8da4-778b9b86506a.png)

**Comment by OnkarMulay** [comment]
Can you use the same value of j and then send the output?
Make sure you either use 10 or 100

**Comment by DwightTRAX** [comment]
@OnkarMulay As I know, once I try less than 100. It's working.

**Comment by MasonLi** [comment]
@DwightTRAX What do you mean by less than 100？ Use less than 100 features to train the model or explain less than 100 samples per time?
