### ISSUE TITLE
MNIST DeepExplainer demo doesn't work

### ISSUE THREAD

**Issue by leszekmp** [shap/shap#1297]
Copied and pasted the demo code directly into a new notebook. Model trained successfully, but section with DeepExplainer code doesn't run. Error message: "keras is no longer supported, please use tf.keras instead." Tried adding "import tensorflow as tf" to code, but that didn't work.

**Comment by vinciabhinav** [comment]
It works for me : https://www.kaggle.com/avvinci/shap-test/

**Comment by ghost** [comment]
@vinciabhinav What version of Keras and version of Tensorflow did you use?

**Comment by leszekmp** [comment]
Keras is 2.4.3; Tensorflow is 2.2.0.

**Comment by albertlis** [comment]
I have the same issue. I'm running notebook on Google Colab. Keras: 2.4.3, Tensorflow 2.4.0. If I change imports to `tensorflow.keras` I receive next error:
<pre>
AttributeError                            Traceback (most recent call last)
<ipython-input-14-9e7c1776c6c9> in <module>()
      6 
      7 # explain predictions of the model on three images
----> 8 e = shap.DeepExplainer(model, background)
      9 # ...or pass tensors directly
     10 # e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)

2 frames
/usr/local/lib/python3.6/dist-packages/shap/explainers/_deep/__init__.py in __init__(self, model, data, session, learning_phase_flags)
     82 
     83         if framework == 'tensorflow':
---> 84             self.explainer = TFDeep(model, data, session, learning_phase_flags)
     85         elif framework == 'pytorch':
     86             self.explainer = PyTorchDeep(model, data)

/usr/local/lib/python3.6/dist-packages/shap/explainers/_deep/deep_tf.py in __init__(self, model, data, session, learning_phase_flags)
    126             self.session = _get_session(session)
    127 
--> 128         self.graph = _get_graph(self)
    129 
    130         # if no learning phase flags were given we go looking for them

/usr/local/lib/python3.6/dist-packages/shap/explainers/tf_utils.py in _get_graph(explainer)
     44         return explainer.session.graph
     45     else:
---> 46         return explainer.model_output.graph
     47 
     48 def _get_model_inputs(model):

AttributeError: 'KerasTensor' object has no attribute 'graph'
</code>

**Comment by albertlis** [comment]
I solved it. This library has poor TensorFlow v2 support. You need change version to v1 to run it. If you have TF v2 just add these lines:
```python
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
and it works but there is still warning : `keras is no longer supported, please use tf.keras instead`. To disable it you need to change imports from `keras` to `tensorflow.keras`.
