### ISSUE TITLE
shap.common.SHAPError: Additivity check failed in TreeExplainer! is thrown sometimes

### ISSUE THREAD

**Issue by giancarloGiuffra** [shap/shap#1298]
Hi, I have set up a simple example with the sklearn.ensemble.RandomForestClassifier. When I run it, sometimes it throws the error mentioned in the title. The code is the following:

```python
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import shap

X, y = shap.datasets.adult()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)
print('training model...')
model = RandomForestClassifier(n_estimators=5, max_depth=10, random_state=7)
model.fit(X_train, y_train)
print('...done')

print('shap values...')
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
print('...done')
```

The complete error is:
```
Traceback (most recent call last):
  File "/Users/gianca/shap/main.py", line 17, in <module>
    shap_values = explainer.shap_values(X)
  File "/Users/gianca/shap/venv/lib/python3.7/site-packages/shap/explainers/tree.py", line 344, in shap_values
    self.assert_additivity(out, self.model.predict(X))
  File "/Users/gianca/shap/venv/lib/python3.7/site-packages/shap/explainers/tree.py", line 467, in assert_additivity
    check_sum(self.expected_value[i] + phi[i].sum(-1), model_output[:,i])
  File "/Users/gianca/shap/venv/lib/python3.7/site-packages/shap/explainers/tree.py", line 463, in check_sum
    raise SHAPError(err_msg)
shap.common.SHAPError: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was 0.116977, while the model output was 231584178474632390847141970017375815706539969331281128078915168015826259279872.000000. If this difference is acceptable you can set check_additivity=False to disable this check.
```
Two notes:
1. Why the error reports a value that can certainly not be the model output? `This check failed because for one of the samples the sum of the SHAP values was 0.116977, while the model output was 231584178474632390847141970017375815706539969331281128078915168015826259279872.000000.`
2. I have run the same exact script and sometimes it does not throw the error, other times it throws it with a different a different value for the model output.

I suppose randomness is used in the calculation of the shap_values, right? Otherwise I cannot explain this behavior.

I am using a Macbook Pro 2014, 2.6GHz  Intel Core i5 dual core, RAM 8 GB 1600 MHz DDR3. Operating System Catalina.

I am happy to help, thanks.

**Comment by h-un** [comment]
Hello.I'm facing the exact same problem with RandomForestRegressor.
Although I'm not so sure about this, it seems to be all good when the training data is below a certain size and starts to raise the check failing error when I tried to increase the training data.

**Comment by sparvaneh** [comment]
I have a similar issue with both training and test data. I am getting the following exception with scikit-learn=0.23.2 and shap=0.37.0

Exception: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was 0.626204, while the model output was 0.710000. If this difference is acceptable you can set check_additivity=False to disable this check.
