### ISSUE TITLE
feature engineering + interactions, possible?

### ISSUE THREAD

**Issue by dexter4455** [shap/shap#1299]
Hi,

I couldn't find an answer to this situation, which i thought is very common: having feature importance for raw feature and the engineered features:

Let's say i have raw data [following are feature columns]:
a,b,c, d, e
then i have a pipeline with a transformer that ingests the raw and creates new features:
a*b*c/e, d/e, a+b+c
i would like to see the feature importance of:
a, b, c, d, e, a*b*c/e, d/e, a+b+c
For a kernel explainer. 

I can't input: "a, b, c, d, e, a*b*c/e, d/e, a+b+c" to shap, as it'll zero all the engineered features (as they happen as a second step).
How can i go about it?

Is it ok to calculate
1. shap_values for for a,b,c,d,e
2. shap values for a*b*c/e, d/e, a+b+c
then concatenate them + mean abs them to get the importance? (i don't think it's ok, but want to verify).

Thank you!

P.S.
How does this align with the assumption of feature independence of SHAP? ( i assume it'll put SHAP importance value of 0)

**Comment by Drfengze** [comment]
Hi dexter4455, I am also curious about this question, do you have an idea about this now? 

Moreover, I have another question, if the engineered feature is derived from a sub-model (machine learning or process model), how to explain the results from SHAP?
