### ISSUE TITLE
TreeExplainer warning shows regardless of the perturbation setting

### ISSUE THREAD

**Issue by Thomas9292** [shap/shap#1301]
**Describe the bug**

When initializing a `TreeExplainer` without background data, a warning that the `feature_perturbation` setting is set to `'tree_path_dependent'` shows regardless of whether the `feature_perturbation` setting is already set to `'tree_path_dependent'`.

```
Setting feature_perturbation = "tree_path_dependent" because no background data was given.
```

**Versions**

```
Python 3.7.9
shap==0.35.0
```

I'll write up a PR over the coming days.

**Comment by InterferencePattern** [comment]
This is already addressed in PR #1267
