### ISSUE TITLE
How to calculate SHAP values for simple MLP Neural Network?

### ISSUE THREAD

**Issue by pplonski** [shap/shap#1304]
I'm building [AutoML](https://github.com/mljar/mljar-supervised) package where I provide SHAP explanations for different models. I have a problem with SHAP explanations for Neural Networks ([issue](https://github.com/mljar/mljar-supervised/issues/112)). The NN that I construct is simple Multi-Layer Perceptron with 2 hidden layers. The computation of SHAP values takes a lot of time (several hours) for very small datasets.

Below simple example: 

```python
import numpy as np
import pandas as pd
import keras
import shap
from sklearn import datasets

from keras.optimizers import SGD
from keras.models import Sequential
from keras.layers import Dense

print(keras.__version__) 
print(shap.__version__)

n_features = 10


X, y = datasets.make_classification(
            n_samples=1000,
            n_features=n_features,
            n_informative=4,
            n_redundant=1,
            n_classes=2,
            n_clusters_per_class=3,
            n_repeated=0,
            shuffle=False,
            random_state=0,
        )

model = Sequential()
model.add(Dense(10, activation="relu", input_dim=n_features))
model.add(Dense(10, activation="relu", input_dim=n_features))
model.add(Dense(1, activation="sigmoid"))
model.compile(optimizer=SGD(), loss="binary_crossentropy")
model.fit(X, y)

explainer = shap.KernelExplainer(model.predict_proba, X)
shap_values = explainer.shap_values(X)
```
```
keras version = 2.3.1
shap version = 0.35.0
```

On this simple dataset, computing SHAP values take > 8 hours. What is the faster way to compute the SHAP values? For other algorithms (Xgboost, CatBoost, Extra Tress, LightGBM, Random Forest, Linear Regression) all computations are under 1 minute.

**Comment by pplonski** [comment]
any update on this one

**Comment by tkmamidi** [comment]
any update, please?

**Comment by Daanielvb** [comment]
In my case, I'm not even able to run the KernelExplainer on a jupyter notebook. It crashed using all the RAM.

I'm using MLP + TF-IDF on a 3000 samples and ~9000 words vocabulary. What do you suggest?
