### ISSUE TITLE
Main and interaction effects components of SHAP values

### ISSUE THREAD

**Issue by madmy016** [shap/shap#1315]
My understanding is that SHAP values account for both the main effect of a variable and the interaction effects of the variable with other variables in every combination as dictated by the model to be explained.  I use SHAP values on CatBoost models.  Is there any way to split a SHAP value of a variable for a sample into two values — one for the main effect and another for the interaction effects?

**Comment by shiva24yv** [comment]
@madmy016  interesting thought, I am currently working on the same - as a workaround - i have come up with the following logic - 
For a variable say v1, we could get the interaction with every other n-1 variables. So for each row in data - we could subtract the shap value of v1 with the sum of interaction of v1 with n-1 variables. 

But, this would be possible if the interaction of v1 with v1 is zero. I don't see that in the interaction_plots. 

Were you able to come up with a solution ?
