### ISSUE TITLE
Support for TensorflowExtended (TFX) Keras model and tfrecords input?

### ISSUE THREAD

**Issue by nadgirsanket** [shap/shap#1319]
I am trying to run a TensorFlowExtended (TFX) pipeline that uses tf.keras model.

The inputs to the model are produced from a TensorFlow transform (TFT) output in the form of tfrecords.

Does Shap support tfrecords inputs? If so, is it possible to get some examples?

If not, is there any plan to support it?

I would love to get Shap working with TFX pipeline but haven't been able to do so.

I'm using the below versions
```
tfx==0.21.2
tensorflow==2.1.0
shap==0.35.0
```

**Comment by ConfuzedCoder** [comment]
@nadgirsanket  have you found any solution?
