### ISSUE TITLE
Multiple Classes - only gives you a single class 

### ISSUE THREAD

**Issue by danielad-k** [shap/shap#1326]
Hello when I try to use summary_plot for feature importance with tf.Keras neural net (with Deep Explainer), I only just the the feature importance for one class?

![image](https://user-images.githubusercontent.com/53984115/88056483-a1b2b880-cb2e-11ea-8557-f7f397d7c4c9.png)

versus what I am expecting: 

![image](https://user-images.githubusercontent.com/53984115/88056389-74660a80-cb2e-11ea-9e16-480e266e13ee.png)

Thank you.

**Comment by amjass12** [comment]
what happens if you get rid of the [0] from `shap_values_v[0] `

By specyfiying [0], you are reaquessting to view feature importance for the first class
