### ISSUE TITLE
Saving the Results of a shap.summary_plot as a Pandas Dataframe

### ISSUE THREAD

**Issue by cschiri** [shap/shap#1329]
To summarize the shapely values into a plot we use:

`shap.summary_plot(shap_values, X, plot_type="bar")`

Is there any way we could save the results of this summarization exercise to a Pandas DataFrame?

I tried this method:

`frame = pd.DataFrame(shap_values, columns=X.columns)`

But, it failed. Any ideas on what can be done to save the results?

**Comment by snassimr** [comment]
+ 1

**Comment by hlnicholls** [comment]
Did you find an answer to this? I would also be interested
