### ISSUE TITLE
Error with 'pip install shap' on both linux and mac

### ISSUE THREAD

**Issue by Deepak280888** [shap/shap#133]
I am trying to install SHAP in my anaconda environment. But I run into error with gcc. See the error below and attached is the image of the error. Any help is appreciated! Thanks! 
**gcc: error trying to exec 'cc1plus': execvp: Permission denied**
![screen shot 2018-06-27 at 9 52 35 am](https://user-images.githubusercontent.com/40639302/41988101-f6fbf7b2-79ef-11e8-833b-82ad62584920.png)

**Comment by Deepak280888** [comment]
The issue is with my linux machine. I was able to figure out and could install the package. Closing the issue. Thanks!

**Comment by slundberg** [comment]
Great!
