### ISSUE TITLE
TreeExplainer error with sklearn 0.23.1

### ISSUE THREAD

**Issue by mosala777** [shap/shap#1337]
I'm getting the following errors when using TreeExplainer

> Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._forest.RandomForestClassifier'>

> Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._gb.GradientBoostingClassifier'>

Currently using sklearn 0.23.1. Could it be an update related error?

**Comment by lrjball** [comment]
What version of shap are you using? Can you try updating to the latest version, the newer version of sklearn moved some of the models which has since been added to shap. Anything from 0.32.0 or above should work I think, but best to try the latest 0.36.0 if possible
