### ISSUE TITLE
SHAP Hierarchical Clustering

### ISSUE THREAD

**Issue by parmleykyle** [shap/shap#134]
Hi Scott,

I’m a PhD student in plant breeding (Agronomy) where I’m using SHAP values to understand how different physiological traits (predictors) are responsible for the amount of seed a plant produces (response). I’m having good success with your approach using it to analyze a random forest model to identify important predictors. Anyways, I’m wanting to export the clustering information and order from the central figure using shap.force_plot but not sure how to do this. I appreciate your work on this approach and how easy it is. This allows someone like myself who isn’t an expert in data science to unravel complex ML algorithms. 

Thanks in advance.

**Comment by slundberg** [comment]
Glad you have found it useful! The clustering is just based on scipy which you can run manually:

```
import scipy.cluster
D = scipy.spatial.distance.pdist(shap_values[:,:-1], 'sqeuclidean')
clustOrder = scipy.cluster.hierarchy.leaves_list(scipy.cluster.hierarchy.complete(D))
```

**Comment by liuyanguu** [comment]
Dear Scott, I am replicating your very nice plots in R and have a related question about clustering in the `force_plot`. It is very nice to cluster features with similar effects. So far I just let the observations follow the order of clustering (method = "centroid", corresponds to squared Euclidean). 
I am not sure how you did it in `hclust_ordering`, especially the part "# merge clusters, rotating them to make the end points match as best we can". It seems more than just a clustering? Thank you again for your kind help and advice. Cheers. 
![image](https://user-images.githubusercontent.com/11966330/54880461-357d5300-4e1b-11e9-9361-b3c615e1a8e9.png)

**Comment by gadquinonez** [comment]
Thanks for your contribution with your work Scott. I am doing my master's paper on customer segmentation using HDBSCAN after reducing dimensionality  with UMAP. I understand SHAP values explain the impact of a feature on a target variable. I want to use SHAP values to understand witch feature explains a cluster the most. Should I do a tree regression for example and then use SHAP values? What would yo recommend me? Thanks a lot!
