### ISSUE TITLE
running time question of shap_values if with model_output = "logloss" in explainer

### ISSUE THREAD

**Issue by sarahnguvt** [shap/shap#1341]
Hi @slundberg, firstly thank you for the tool it is great! I have a question about the running time of ```shap_values``` when specifying model_output = "logloss" in explainer

I tested based on [this notebook](https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Explaining%20the%20Loss%20of%20a%20Model.ipynb), if I call shap_values on the entire X (not only 10 records), the estimated running time is like below:
```  0%|                   | 31/32561 [00:38<664:35] ```

I also tested with my own model by:
```explainer = shap.TreeExplainer(model, X, feature_dependence="independent", model_output="logloss")```
where **model** is a XGBoost model, and **X** is of shape (6588, 95)
 
Then I would like to get shap values with ```explainer.shap_values``` on a larger sample (32938, 95), and the estimated running time is as below:
```1%|                   | 371/32938 [01:52<163:51]```

I also tried to pass this dataset (32938, 95) into the explainer, and calling ```shap_values``` on the same dataset gave me an estimated running time of more than 800 minutes. I understand my model has a lot of features, so I would like to get your view on 1) given the data size and # of features whether the running time is as expected when calculating shap values on logloss? and 2) do you have any suggestion on how this may get faster? I am running on a quite powerful server, while if on your original notebook you did not experience slow run time as I did, please kindly suggest as well. Thanks!

**Comment by tkmamidi** [comment]
Any update on this, please?
