### ISSUE TITLE
shap interaction values with one hot encodings 

### ISSUE THREAD

**Issue by hiyamgh** [shap/shap#1342]
Hello,

In my data, I have one hot encoding for my categorical columns. However, for the purpose of SHAP, In order to get meaningful insights of these one hot encoded columns, I have **SUMMED** the shap values of each one hot encoded columns, as suggested in this issue [https://github.com/slundberg/shap/issues/397](https://github.com/slundberg/shap/issues/397).

Now, I want to do SHAP interaction values for my decision plot. How should I transform it so it handles one hot encodings ?

**Comment by slundberg** [comment]
You will want to do the same summation be now it will be over the k x k sub-matrix corresponding to the k one-hot encoded values.

**Comment by hiyamgh** [comment]
So I checked the ```shap_interaction_values``` in my data and it has the following shape: 

```(348, 19, 19)``` as my data has 348 records and 19 columns. 7 of these columns are categorical.  As far as I understand, I must transform it into ```(348, 12, 12)```. If this is true then:

Should I add the k * k sub matrices of each of the k one hot encoded, meaning:

```shap_interaction_values[12] + shap_interaction_values[13] + ...``` but that will still result in a ```(19,19)``` sub matrix. Could you please clarify ?
