### ISSUE TITLE
Additivity check failed in TreeExplainer for ExtraTreesClassifier

### ISSUE THREAD

**Issue by goolig** [shap/shap#1346]
Using ExtraTreesClassifier. If i turn off check_additivity probability from model!= probability in force_plot.

Exception:
shap.common.SHAPError: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was 1.008443, while the model output was 1.000000. If this difference is acceptable you can set check_additivity=False to disable this check.

The target attribute is binary, data contains ~10K features, mostly binary.

Code:
```
clf = ExtraTreesClassifier(n_jobs=-1)
clf.fit(X_train,y_train)
explainer = shap.TreeExplainer(clf)
explainer.shap_values(X_train)

```

**Comment by goolig** [comment]
Changed to use the background data:
`explainer = shap.TreeExplainer(clf,data=X_train)`
And got an exception that np.isnan cannot operate on floats. 
Casted all features to int, now it works.

**Comment by gulf1324** [comment]
I was struggling with this problem. Thank you so much.
