### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by carterl92** [shap/shap#135]
I get the error below when I am trying to !pip install shap.

"Failed building wheel for shap
auto-ml 2.9.10 has requirement lightgbm<2.1,>=2.0.11, but you'll have lightgbm 2.1.1 which is incompatible."

How do I fix this issue? 

-Carter

**Comment by slundberg** [comment]
I don't think shap directly depends on auto-ml so I am not sure why that would come up. Perhaps upgrading auto-ml would help?

**Comment by carterl92** [comment]
Thank you, I had to update auto-ml but also download the VC++ build tools to fix the installation.
