### ISSUE TITLE
Training/Validation

### ISSUE THREAD

**Issue by shmousavi65** [shap/shap#1363]
Hi,

1- what is the best way to find general feature importance using shap? should I find the shap values for the whole data set or just the validation (or test)?

2-I'm training a model using XGBoost and 5 fold cross validation. I want to analyse the feature importance.
What is the best way to do that? 
The way that I'm doing that now is to feed the whole data (train+validation) to each 5 models (and find the shap values for each model for the whole data) and finally find the mean of those shap values. The final mean would be again a matrix of size (num_of_data * num_of_features).

Thanks!

**Comment by Lamiane** [comment]
Hi! I'm new to SHAP but maybe you can use some of my knowledge/intuitions. :)

1. I think you should use the whole dataset. Why? Recently I've made a small experiment and seen that it doesn't matter if I calculate SHAP values for the whole dataset or the training set only - the SHAP values for a specific sample are exactly the same. And if you want to have a general feature importance then I guess it's better to average over more data than less data.
2. The feature importance that you get with SHAP is always model-dependant - it explains the model and not how important are these features in the real world. So the answer to your question depends on what is the model that you want to explain? If you want to explain a single model out of the 5 then calculate SHAP values only for this single model. If you want to combine these models into an ensemble then calculate the SHAP values of the ensemble and not the single models.
