### ISSUE TITLE
TreeExplainer shap value discrepancies with Random Forest classifier predictions

### ISSUE THREAD

**Issue by nlabreche** [shap/shap#137]
Hi,

I am a fan of shap for explaining model predictions. Unfortunately, I've encountered instances where the shap values add up to something very different than what the model predicts. I've reproduced the issue below by applying a Random Forest classifier to the adult census income dataset.

```
import shap
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train,X_test,Y_train,Y_test = train_test_split(*shap.datasets.adult(), test_size=0.2, random_state=0)
clf = RandomForestClassifier(random_state=0, n_estimators=30)
clf.fit(X_train, Y_train)
predicted = clf.predict_proba(X_test)
shap_values = shap.TreeExplainer(clf).shap_values(X_test)

#looking for cases where the sum of the shap values strongly disagrees with the Random Forest predictions.
for i in range(len(predicted)):
    shap_sums = np.round([shap_values[j][i].sum() for j in range(len(shap_values))], decimals=2)
    max_diff = np.round(np.max(np.abs(shap_sums - predicted[i])), decimals=2)
    if abs(max_diff) > 0.2:
        print("Data index: " + str(i), "Maximum difference: " + str(max_diff),\
              "Forest predictions: " + str(predicted[i]), "Shap value sums: " + str(shap_sums))
```

The output:
Data index: 314 Maximum difference: 0.43 Forest predictions: [0.16666667 0.83333333] Shap value sums: [0.6 0.4]
Data index: 397 Maximum difference: 0.31 Forest predictions: [0.68333333 0.31666667] Shap value sums: [0.37 0.63]
Data index: 573 Maximum difference: 0.23 Forest predictions: [0.65 0.35] Shap value sums: [0.42 0.58]
Data index: 580 Maximum difference: 0.27 Forest predictions: [0.66666667 0.33333333] Shap value sums: [0.4 0.6]
Data index: 581 Maximum difference: 0.46 Forest predictions: [0.73333333 0.26666667] Shap value sums: [0.27 0.73]
Data index: 610 Maximum difference: 0.29 Forest predictions: [0.51301587 0.48698413] Shap value sums: [0.22 0.78]
Data index: 913 Maximum difference: 0.43 Forest predictions: [0.73333333 0.26666667] Shap value sums: [0.3 0.7]
Data index: 990 Maximum difference: 0.4 Forest predictions: [0.7 0.3] Shap value sums: [0.3 0.7]
Data index: 998 Maximum difference: 0.24 Forest predictions: [0.63333333 0.36666667] Shap value sums: [0.87 0.13]
Data index: 1251 Maximum difference: 0.21 Forest predictions: [0.33444444 0.66555556] Shap value sums: [0.54 0.46]
Data index: 1686 Maximum difference: 0.24 Forest predictions: [0.475 0.525] Shap value sums: [0.71 0.29]
Data index: 1785 Maximum difference: 0.37 Forest predictions: [0.5 0.5] Shap value sums: [0.87 0.13]
Data index: 2112 Maximum difference: 0.4 Forest predictions: [0.27777778 0.72222222] Shap value sums: [0.68 0.32]
Data index: 2205 Maximum difference: 0.27 Forest predictions: [0.42914721 0.57085279] Shap value sums: [0.7 0.3]
Data index: 2296 Maximum difference: 0.3 Forest predictions: [0.16666667 0.83333333] Shap value sums: [0.47 0.53]
Data index: 2440 Maximum difference: 0.3 Forest predictions: [0.36666667 0.63333333] Shap value sums: [0.07 0.93]
Data index: 2443 Maximum difference: 0.27 Forest predictions: [0.42914721 0.57085279] Shap value sums: [0.7 0.3]
Data index: 2555 Maximum difference: 0.24 Forest predictions: [0.36666667 0.63333333] Shap value sums: [0.13 0.87]
Data index: 2868 Maximum difference: 0.23 Forest predictions: [0.16666667 0.83333333] Shap value sums: [0.4 0.6]
Data index: 3027 Maximum difference: 0.23 Forest predictions: [0.4 0.6] Shap value sums: [0.63 0.37]
Data index: 3200 Maximum difference: 0.21 Forest predictions: [0.33444444 0.66555556] Shap value sums: [0.54 0.46]
Data index: 3231 Maximum difference: 0.37 Forest predictions: [0.8 0.2] Shap value sums: [0.43 0.57]
Data index: 3396 Maximum difference: 0.23 Forest predictions: [0.73333333 0.26666667] Shap value sums: [0.5 0.5]
Data index: 3554 Maximum difference: 0.26 Forest predictions: [0.67380952 0.32619048] Shap value sums: [0.41 0.59]
Data index: 3677 Maximum difference: 0.24 Forest predictions: [0.475 0.525] Shap value sums: [0.71 0.29]
Data index: 4168 Maximum difference: 0.4 Forest predictions: [0.27777778 0.72222222] Shap value sums: [0.68 0.32]
Data index: 4898 Maximum difference: 0.34 Forest predictions: [0.26222222 0.73777778] Shap value sums: [0.6 0.4]
Data index: 5205 Maximum difference: 0.37 Forest predictions: [0.3 0.7] Shap value sums: [0.67 0.33]
Data index: 6141 Maximum difference: 0.27 Forest predictions: [0.66666667 0.33333333] Shap value sums: [0.4 0.6]
Data index: 6478 Maximum difference: 0.32 Forest predictions: [0.38055556 0.61944444] Shap value sums: [0.7 0.3]

**Comment by slundberg** [comment]
Thank you for pointing that out! I'll get back here when I sort it out.

**Comment by slundberg** [comment]
Thank you again! This has to do with the definition of feature splits, sklearn uses `<=` while the code uses the `<` convention (like XGBoost does). The SHAP values to sum up to the output of a leaf in the model, just the wrong leaf when the feature value exactly lands on a threshold.

Note sure why this didn't come up before, but I will add a flag to use less than or equal for the sklearn models.

**Comment by matthewvowels1** [comment]
When I run this code I get something very different... Any idea why?

Output:

Data index: 0 Maximum difference: 0.76 Forest predictions: [1. 0.] Shap value sums: [ 0.24 -0.24]
Data index: 1 Maximum difference: 0.76 Forest predictions: [1. 0.] Shap value sums: [ 0.24 -0.24]
Data index: 2 Maximum difference: 0.76 Forest predictions: [0.93333333 0.06666667] Shap value sums: [ 0.17 -0.17]
Data index: 3 Maximum difference: 0.76 Forest predictions: [0.46666667 0.53333333] Shap value sums: [-0.29  0.29]
Data index: 4 Maximum difference: 0.76 Forest predictions: [0.53333333 0.46666667] Shap value sums: [-0.23  0.23]
Data index: 5 Maximum difference: 0.76 Forest predictions: [0.83333333 0.16666667] Shap value sums: [ 0.07 -0.07]
Data index: 6 Maximum difference: 0.76 Forest predictions: [0.93333333 0.06666667] Shap value sums: [ 0.17 -0.17]
...
