### ISSUE TITLE
Attribute error: Module "shap" has no attribute KernelExplainer

### ISSUE THREAD

**Issue by mckennapep** [shap/shap#1375]
I have installed shap and have the most recent version (0.35.0). However when I try to use KernelExplainer or TreeExplainer, the error is returned and it says shap has no attribute KernelExplainer. I tried uninstalling and reinstalling shap and it still did not work. I tried this for both python 3.7.4 and python 3.6.0. 

rf = MLPRegressor()
rf.fit(X_train, Y_train)
rf_shap_values = shap.KernelExplainer(rf.predict, X_test)

**Comment by lrjball** [comment]
Try this simple example and see what output you get:
```python
from sklearn.neural_network import MLPRegressor
import shap
import numpy as np

print(shap.__version__)

X_train = np.array([1, 2, 3]).reshape(-1, 1)
y_train = [0, 1, 1]

rf = MLPRegressor()
rf.fit(X_train, y_train)
explainer = shap.KernelExplainer(rf.predict, X_train)
print(explainer.shap_values(X_train))
```

This works fine for me, and hopefully it will for you as well!
