### ISSUE TITLE
Exception: Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._forest.RandomForestRegressor'>

### ISSUE THREAD

**Issue by navroz-lamba** [shap/shap#1379]
![Screen Shot 2020-08-24 at 10 56 59 PM](https://user-images.githubusercontent.com/67918990/91112584-2306e900-e6a1-11ea-9635-4ab9fa3db5af.png)
![Screen Shot 2020-08-24 at 10 51 40 PM](https://user-images.githubusercontent.com/67918990/91112595-29956080-e6a1-11ea-964d-75eca9c04cc0.png)

I have also added the screenshot of the model that I am using.
I keep on getting this error. 

Exception: Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._forest.RandomForestRegressor'>

**Comment by slundberg** [comment]
Not sure why it is failing since the same setup works for me. I have shap 0.36.0 and sklearn 0.23.2

**Comment by lrjball** [comment]
Yeah I think this is an issue with an older version of shap (0.31.0 and below) as sklearn changed the import paths of some of the models, which has since been updated in shap. Try updating to the latest version of shap and see if you are still getting the issue

**Comment by navroz-lamba** [comment]
Thank You guys! 



Updating to Shap 0.36.0 solved the error.



Thanks for your help again!



- Navroz Lamba






---- On Sat, 29 Aug 2020 19:15:47 -0700 lrjball <notifications@github.com> wrote ----




Yeah I think this is an issue with an older version of shap (0.31.0 and below) as sklearn changed the import paths of some of the models, which has since been updated in shap. Try updating to the latest version of shap and see if you are still getting the issue

**Comment by arjunko** [comment]
![image](https://user-images.githubusercontent.com/78132920/114606616-1a5b3580-9cb9-11eb-8b69-e82f17fc5dbf.png)

![image](https://user-images.githubusercontent.com/78132920/114606326-c4868d80-9cb8-11eb-8778-f8e07620a613.png)

Hello Sir, I have the same issue even though my shap version 0.36.0 and sklearn version 0.24.1  i had an error in Adaboost model classifier. Kindly help on this.

**Comment by bettasimousss** [comment]
I just had this issue, after patching sklearn with scikit-learn-intelex to speed up SVM. As a result, SHAP tree explainer did not recognize random forest so I had to unpatch back

**Comment by vivekruhela** [comment]
Hi,

I am using the latest version of shap. Still, I am facing the same problem (screenshot attached). Any suggestions??

![Screenshot from 2022-08-23 12-11-56](https://user-images.githubusercontent.com/13174913/186088893-7f7f85ce-6cf8-4d91-bff8-d0a4a120af02.png)
