### ISSUE TITLE
SHAP Decision Plot X-Axis meaning for regression 

### ISSUE THREAD

**Issue by YasmineHamdar** [shap/shap#1380]
In the decision plots, it is not quite clear what do the x-axis values represent in the case of regression. In classification, they are  log-odds. Are they the actual model output value like the actual value of the target variable in regression? Are they something else like some probability? Are they the sum of SHAP values? What are they?
![SHAP_acc_local](https://user-images.githubusercontent.com/36507032/91059578-9291bf80-e632-11ea-9a77-7f4e8238765c.png)

**Comment by slundberg** [comment]
The x-axis units are the same units as the output of the regression model (and the same as the SHAP values). In case it is helpful the x-axis is the same here as in the waterfall plot, and it essentially shows how the features impacts (SHAP values) take us from the base value (expected model output over the background dataset) to the current model output.

**Comment by YasmineHamdar** [comment]
Hello,

What do you mean  (and so the same as the SHAP values)? Do the SHAP values have units the same as the output regression model? Don't SHAP value regression signify an increase in accuracy?

**Comment by slundberg** [comment]
Sorry I fixed a typo. You can compute the SHAP values of anything you can execute, but most commonly you explain the output of the model, so a SHAP value of +2.2 means it causes the model output to increase by 2.2 when we set that feature's value to the value it has for the current instance we are explaining (as opposed to averaging the model output over all the feature values in the background dataset).

**Comment by YasmineHamdar** [comment]
Hello,

So you mean that in any regression model (Tree based model for example), the SHAP value simply means an increase/decrease in the predicted target variable? If so, what about all the resources online which mention that SHAPely value regression signifies how much an increase in R2 score each predictor variable caused. The meaning of SHAP values in regression is not very well documented as in classification, that is why it is kind of tricky to figure out. Your help is appreciated.

Resources are here:
https://mpra.ub.uni-muenchen.de/72116/1/MPRA_paper_72116.pdf
https://christophm.github.io/interpretable-ml-book/shapley.html
https://www.displayr.com/shapley-value-regression/

**Comment by slundberg** [comment]
The Shapley regression values are from a paper in 2001 that used the Shapley values to explain linear models. They retrained the model on all subsets of data and used the change in R2 value to compute the Shapley values. That was the first paper that ever used Shapley values in statistics (that I know of), but it is a bit different from the SHAP package. The first thing is that SHAP can explain any model output using Shapley values (not just the R2), and it is targeted at explaining local predictions not a global measure of feature importance (which is R2). By default SHAP explains the log-odds output of a classification model or the raw output of a regression model.

The basic point is that the Shapley values are a way of allocating credit, but you can apply them to explain many possible model outputs, and you can perturb a model in various ways. R2 is not a typical output we explain, but you could, and we normally don't "hide" features by retraining a whole model without them (but you could). shap.maskers.* in the new API represents ways to hide features, while the function or model you pass to the explainers determines what model output we explain.
