### ISSUE TITLE
Follow up question on TreeSHAP runtime (KDD presentation 2020)

### ISSUE THREAD

**Issue by TGalaxy** [shap/shap#1385]
Thanks for the awesome presentation this morning. Our team is interested in applying TreeSHAP to explain LightGBM in production. However we have very strict requirement on runtime latency - down to ms scale per transaction. Of course the runtime depends on the LGBM complexity and computing resource. But is there any benchmark study done on TreeSHAP runtime to give a ballpark idea? Our engine is written in C. Is there any direct plug in from the SHAP package in C if C might be faster than python? Thanks!

**Comment by slundberg** [comment]
Great questions. A couple thoughts:
1. You can directly integrate with the C++ version of TreeSHAP by importing https://github.com/slundberg/shap/blob/master/shap/tree_shap.h into your code base. It should be self explanatory based on how https://github.com/slundberg/shap/blob/master/shap/_cext.cc uses it. You will need to build a sklearn style representation of the LightGBM model though, and there is not support yet for the "categorical splits" the LightGBM does in tree_shap.h.
2. There is a path dependent version of TreeSHAP inside LightGBM, I don't recall if it is exposed through the C++ bindings, but it is worth a look.
3. You can always try the approximate=True flag to make TreeSHAP even faster, and it is a reasonable approximation for large ensembles.
4. I don't have careful C++ level runtimes. But you run those tests please share them back here :)

**Comment by ManuelZ** [comment]
Is there an available recording of your hands-on tutorial "Intelligible and Explainable Machine Learning: Best Practices and Practical Challenges" please?
@slundberg

**Comment by slundberg** [comment]
Not sure. We are checking with the organizers.

**Comment by TGalaxy** [comment]
Hi @slundberg, I'd like to follow up on our earlier conversations:
I did a quick benchmark in python env and the option approximate = True gave significant faster runtime. Using LGBM with 800+ trees, max_depth of 7 and 700+ features, approximate = True & feature_perturbation = interventional took 0.2ms compared to 39ms when approximate = False. We are very interested in moving forward with the approximate option. 
(1) I wasn't able to locate the documentation, but how does approximate = True save time? Does it look at a limited number of trees?
(2) I wonder if you have any suggestions on how to save the SHAP explainer and load it later in C++ env for real time processing? 
say after we finish this step,
`explainer = shap.TreeExplainer(model,df.sample(n=1000),feature_perturbation="interventional")`
Thanks!

**Comment by estellerambier** [comment]
Hey @TGalaxy! 
I am running into similar challenges in my current project. I want to gain insight into a random forest with 500 dependent variables (I know it looks like a bad fit, but it does a great job ;)). 

I could also drive the running time down with `approximate=True`. Though I was concerned by the quality of the approximation. So I benchmarked the differences between the returned values of the TreeExplainer **with** and **without** the parameter `approximate=True`. The short answer is that they are very different. Mainly the approximated version gives middler results, which was already a consequence of the relatively high dimension, but get emphasized with the approximation of the shap values.
Looking at [how](https://arxiv.org/pdf/2010.06734.pdf) the shap values are approximated, it makes sense to have something very different. Regardless of this difference, the approximate values gave me good insights into the business value of my model. I could drive conclusions and validate the quality with domain experts. So in this case and as far as I could verify, different didn't mean incorrect.

You can find an answer to your first question in [this](https://github.com/slundberg/shap/issues/323) issue.

I am curious to hear about the real-time processing in a C++ env!
