### ISSUE TITLE
Getting py4j error on shap 0.36 and spark 2.x

### ISSUE THREAD

**Issue by ashishjwr** [shap/shap#1387]
I installed SHAP 0.36. It only works with spark 3.0 ( py4j 0.10.9). Can we also have support for spark 2.x ( which uses py4j 0.10.7) ? I get the following error with Spark 2.4.5 and SHAP 0.36

```
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\py4j\java_gateway.py", line 1152, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "C:\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by QuentinAmbard** [comment]
This is working fine with spark 2.4 and 3.0. The notebook example I gave works with spark 3.0 because I'm using the latest API but shap works with models in 2.4 or 3.0. Please use the notebook in #1313 for an example. 
Please provide more details on what you think is not working exactly
