### ISSUE TITLE
DeepExplainer: how to load a Tensorflow CNN model(.pb file)

### ISSUE THREAD

**Issue by xiewenjing1170** [shap/shap#1390]
I'd like to  use SHAP to interpret a Tensorflow CNN model (.pb file). But I don't know how to load the model.  
 "  if framework == 'tensorflow', (input : [tf.Tensor], output : tf.Tensor) A pair of TensorFlow tensors (or a list and a tensor) that specifies the input and output of the model to be explained. Note that SHAP values are specific to a single output value, so the output tf.Tensor should be a single dimensional output (,1)."

**Comment by slundberg** [comment]
I have worked a lot with TF model serialization, but can you just load the model into TF first then pass the constructed graph to SHAP?

**Comment by xiewenjing1170** [comment]
@slundberg Thanks for your reply. I have loaded the model into TF and constructed graph. But the graph couldn't be passed to SHAP. I loaded the model as follows:
def load_model(model_filepath):
    print("Loading trained model...")
    with tf.Session() as sess:
        graph_def = tf.GraphDef() 
        with tf.gfile.FastGFile(model_filepath, 'rb') as f: 
            graph_def.ParseFromString(f.read()) 
            tf.import_graph_def(graph_def, name='') 
            #print(graph_def)
            return graph_def
......

background = x_test
model = load_model(model_path)
 e = shap.DeepExplainer(model, background)
 
I got the error:
 File "./DeepExplainer.py", line 139, in <module>
    main()
  File "./DeepExplainer.py", line 132, in main
    e = shap.DeepExplainer(model, background)
  File "D:\AppStudy\Anaconda3.0\envs\python36\lib\site-packages\shap\explainers\deep\__init__.py", line 80, in __init__
    self.explainer = TFDeepExplainer(model, data, session, learning_phase_flags)
  File "D:\AppStudy\Anaconda3.0\envs\python36\lib\site-packages\shap\explainers\deep\deep_tf.py", line 83, in __init__
    from tensorflow.python.ops import gradients_util as tf_gradients_impl
ImportError: cannot import name 'gradients_util'

**Comment by remindchobits** [comment]
Hello, I got the same problem too, have you solved it?

**Comment by vyse8** [comment]
I am also receiving the same issue. Has there been an update on this?
