### ISSUE TITLE
waterfall & bar plot broken with matplotlib>=3.3.0

### ISSUE THREAD

**Issue by yuuuxt** [shap/shap#1391]
tested on `shap==0.35.0` and `shap==0.36.0`.
with `matplotlib==3.2.2` plots work well.
to reproduce: have `matplotlib>=3.3.0` and run this [sample notebook](https://github.com/slundberg/shap/blob/master/notebooks/general/Explainable%20AI%20with%20Shapley%20Values.ipynb).
broken plot samples: 
![broken_waterfall](https://user-images.githubusercontent.com/3153534/91641204-67093d80-ea55-11ea-8af5-59a300c7e9b7.png)
![broken_bar](https://user-images.githubusercontent.com/3153534/91641208-6b355b00-ea55-11ea-8ac5-3c12f342f403.png)

**Comment by slundberg** [comment]
Thanks! That explains why some others had seen those layout issues.

**Comment by slundberg** [comment]
The issue turned out to be that matplotlib started "merging" tick marks that we at the same location in 3.3. And this broke a lot of the overlays we were using to draw multi-color labels. It is now fixed :) (by adding 1e-8 to the second copy of the tick marks)

**Comment by yuuuxt** [comment]
Thanks for your quick response and the fix! :)
