### ISSUE TITLE
Import error on modules from shap.plots

### ISSUE THREAD

**Issue by rsarai** [shap/shap#1392]
Hello folks, 

I'm trying to use the `heatmap` plot and I'm having a few import issues:
```python
import shap
shap.plots.heatmap(shap_values)
# AttributeError: module 'shap.plots' has no attribute 'heatmap'
```

I also tried to import the module directly:
```python
import shap.plots._heatmap
heatmap(shap_values)

# ----> 8 from .. import Explanation
# ImportError: cannot import name 'Explanation' from 'shap' 
```

Am I missing something? Is there any reason specific reason to use relative imports [here](https://github.com/slundberg/shap/blob/df4334a700e419a0623acde497c12e48029946fe/shap/plots/_heatmap.py#L8). From what I know these import problems can be mitigated by replacing relative imports with absolute imports

I'm using the version: 0.36.0

**Comment by lrjball** [comment]
What version of python are you using, and what OS? I can't replicate this on Ubuntu with python 3.8.2.
```python
>>> import shap
>>> shap.plots.heatmap
<function heatmap at. .. >
```
Maybe try a fresh install in a new environment and see if the issue persists? Also, where are you running the code from? If it is from your own directory called shap.plots or from somewhere inside the shap project then that may explain the import issues

**Comment by rsarai** [comment]
Hey @lrjball, thanks for the quick response

I'm using Python 3.7.5 and I'm also using ubuntu. I'm using the code in a notebook with lib installed via pip (I don't have the code on my local notebook directory). I will try a fresh install and let you know.

**Comment by rsarai** [comment]
Closing because the issue was solved by doing a fresh install, thanks!
