### ISSUE TITLE
How to change  color_bar size of shape .summary_plot() 

### ISSUE THREAD

**Issue by pythonamateu** [shap/shap#1394]
Hello, I got an easy problem that I can't change the font size of the color bar, for example, the font size of default output "Feature value".
![image](https://user-images.githubusercontent.com/52752198/91664104-9c7a5d80-eb1f-11ea-9030-29ec710e0207.png)
I am looking forward to your reply.

**Comment by yuyongsheng1990** [comment]
I am looking forward to your answer, too

**Comment by AlanConstantine** [comment]
Please see: https://github.com/slundberg/shap/issues/594#issuecomment-1206481300

**Comment by AlanConstantine** [comment]
> Hello, I got an easy problem that I can't change the font size of the color bar, for example, the font size of default output "Feature value". ![image](https://user-images.githubusercontent.com/52752198/91664104-9c7a5d80-eb1f-11ea-9030-29ec710e0207.png) I am looking forward to your reply.

you can see: https://github.com/slundberg/shap/issues/594#issuecomment-1206481300

**Comment by kedhar1992** [comment]
shap.summary_plot(shap_values, plot_type='violin', color_bar=False) 
cbar = plt.colorbar()
cbar.ax.tick_params(labelsize=15)
cbar.ax.tick_params(direction='out', length=6, width=2,  grid_alpha=0.5)

**Comment by thatlittleboy** [comment]
The currently recommended solution is suggested above, which is to set `show=False`, 

then you can customize whatever aspect of the plot you want, including the colorbar.

**Comment by Xovee** [comment]
or you can just edit the source codes in your local directly
