### ISSUE TITLE
Dependence plots with unscaled feature values

### ISSUE THREAD

**Issue by insuquot** [shap/shap#1396]
There's a similar question [here](https://github.com/slundberg/shap/issues/1033), except they scaled the target so I don't think it applies to my issue.

I scaled 90% of my features with `StandardScaler`, the other 10% of features were left as-is since they're binary. My target variable is binary. I fit a logistic regression model and am using `LinearExplainer`. Per the example notebooks:
```python
explainer = shap.LinearExplainer(model, train_x, feature_perturbation="interventional")
shap_values = explainer.shap_values(train_x)
```
The summary plot looks good. But when I use dependence plots, the x-axis (and if there's an interaction feature on the color bar) of most features are, of course, in standardized units.

I'm new to shap, so I'm not sure of the appropriate way to get the x-axis and color bar units displaying in their original, unscaled units. Does it make sense to `inverse_transform` the features and leave the `shap_values` as-is? Should I also run the `shap_values` through the `inverse_transform` I used for the features? Or some other method?

**Comment by slundberg** [comment]
This is a good question I'll answer here for future reference. When you standardize features you are applying a bunch of univariate transformations to each input feature. Whenever you have investable transformations that apply to each feature independently you can always just invert them to get SHAP value in the original input space. I added a notebook example to address this: https://github.com/slundberg/shap/blob/master/notebooks/tabular_examples/linear_models/Explaining%20a%20model%20that%20uses%20standardized%20features.ipynb
