### ISSUE TITLE
Get SHAP running with Angular 2.x

### ISSUE THREAD

**Issue by mfizia** [shap/shap#1403]
Hello there,

we are trying to get this project working with Angular.
We tried to implement the simple example from javascript/build/index.html in our app, but we failed.

My first question is, does it run in an Angular 2.x app?
My second question is, does anyone have a little more information, hint, documentation or how-to for getting this running with Angular?

We installed SHAP via `npm i shapjs`

Maybe someone could help us.

**Comment by slundberg** [comment]
The code right now is mostly just d3, wrapped in a bit of React. I am sure you could rewrap it in an Angular element, but it would take some dev work. If you do end up making it work please share for the benefit of others :)
