### ISSUE TITLE
Error : version of tensorflow

### ISSUE THREAD

**Issue by XuLw** [shap/shap#1405]
I want to know what **version of tensorflow** is used in shap. 

I want to use shap to analyze a cnn model based on tensorflow. But encountered some problems, these problems seem to be caused by the tensorflow version. So I would like to ask whether this tool can be used to analyze tensorflow-based cnn models? What version of tensorflow does the current tool use? Looking forward to your reply. Thanks a lot.
**error** :
![image](https://user-images.githubusercontent.com/31442809/91998899-6383f800-ed6e-11ea-949e-e898b7f6938c.png)
Please reply if you see this issue.

**Comment by slundberg** [comment]
We try to support for 1 and 2, but it looks like `model` is None in your example, so some other issue is going on outside shap.
