### ISSUE TITLE
How to combine shap with the autoencoder

### ISSUE THREAD

**Issue by cmzuo11** [shap/shap#1409]
Dear author,

I am the naive one to the explanation of deep learning models, and am curious about how to give the feature importance of autoencoder or variational autoencoder, maybe here, I am interested in the relationship between the input features and the learned suppressed latent code. Could you please give me some ideas about how to handle this problem?

Thanks so much for your kind help!

zuo

**Comment by cherepanovic** [comment]
any news on this issue?

**Comment by burgersmoke** [comment]
I was just doing some literature review on this topic.  I see that there is an Arxiv paper and some code related to this question.

https://arxiv.org/pdf/1903.02407.pdf

https://github.com/ronniemi/explainAnomaliesUsingSHAP

**Comment by cherepanovic** [comment]
@burgersmoke the single paper and github library which I also could find

**Comment by bakachan19** [comment]
@cmzuo11 I am also interested in doing the same. Any guidance that you might provide? thanks!
