### ISSUE TITLE
Column ordering shap values 

### ISSUE THREAD

**Issue by Rupam07** [shap/shap#1410]
Hi, 

I have a dataset for which I want to get the feature importance using shap_values and hence I would like to know that is the column ordering for the shap_values array same as the column order of my dataframe?

I do know that shape of training data == shape of shap_values 

But I just want to confirm if the columns of the training data df are for suppose:
Column_1 | Column_2 | Column_3 | Column_4 | Column_5 | Column_6

Will my numpy array shap_values array have the same column ordering as well?

**Comment by slundberg** [comment]
yep!
