### ISSUE TITLE
Understanding shap.decision_plot

### ISSUE THREAD

**Issue by amaa11** [shap/shap#1415]
Dear all,
Recently I started using SHAP. I really liked the way they explain the contribution of each feature in the model.
I somehow face difficulty to understand the decision plot.
Is it local explainability? or global?.
I would be thankful if someone explain the plot below because I am a bit confusing about the base value and the model output.
Usually I see in decision plot. all the lines starting at zero point and then they separate based on feature contribution. Is it always like that? Because my plot is different in this case.
And also, does the blue color means positive influence and  the red is negative?
Many thanks in advance for any sharing ideas with me to understand the plot.
Regards 
![Screenshot from 2020-09-09 11-11-35](https://user-images.githubusercontent.com/43352625/92579274-4a5ada00-f28d-11ea-8e9b-ed168cf46a0e.png)

**Comment by slundberg** [comment]
I responded here https://stackoverflow.com/questions/63812481/understanding-shap-decision-plot so closing this :)
