### ISSUE TITLE
Visualizations for large numbers of features

### ISSUE THREAD

**Issue by jimmy-hawkfish** [shap/shap#1418]
Hey @slundberg!

First off, thanks for the awesome package and great work. Currently I have summary plots that are laggy due to a large number of features. I did notice that overall the SHAP values are relatively sparse. I was wondering if you had any ideas around post processing the SHAP values to get more performant visualizations. (I know I can subset the features upstream but that's slightly awkward for my use case).

**Comment by slundberg** [comment]
How many samples/features are we talking about? I did spend some effort to make things run quick for many samples, but for summary plots usually there are only 20 or so plotted at a time.
