### ISSUE TITLE
Memory Leaks in TreeExplainer due to unclosed child processes

### ISSUE THREAD

**Issue by tgrondier** [shap/shap#142]
Hi Scott,

I think I have identified a problem in the implementation of TreeExplainer that produces huge memory leaks on some devices.

Here is a sample code:

```
#imports
...
model_names_list = #list of models

def start():

    for model_name in model_names_list:
        #pickle model from disk
        ...
        shap_values = shap.TreeExplainer(model).shap_values(data)

        #pickle shap values to disk
        ...

       #end of loop, no side effects

if __name__ == "__main__":
    start()


```

On one of my servers (Ubuntu 16.04.4 , Kernel Linux 4.4.0-1052-aws), the `shap.TreeExplainer(model).shap_values(data)` will leave behind a list of idle child processes which are not garbage collected, each occupying a non insignificant chunk of memory until the program shuts down, sometimes taking the server down with it. The more TreeExplainers you use, the longer the list of idle child processes get, and they don't always get cleared on program exit. Here is an example of what I am saying:

![image](https://user-images.githubusercontent.com/5384645/42284256-3b8db034-7fac-11e8-9483-b7395d6f4b13.png)

You can see that there are a bunch of processes that are idle but occupy memory; they stay idle and often stay alive after the execution of the script.

It doesn't happen on my personal devices (Windows 10 version 10.0.17134 Build 17134 and Ubuntu 16.0.1 Kernel 4.15.0-24-generic. All devices are running either Python 3.5 or 3.6), which is why I looked into the code of the library and came accross what I believe to be the cause of the bug: https://github.com/slundberg/shap/blob/d79965b976de9d200a4e698fdbcbc608089ae232/shap/explainers/tree.py#L174 and https://github.com/slundberg/shap/blob/d79965b976de9d200a4e698fdbcbc608089ae232/shap/explainers/tree.py#L233. 

It appears ot me that the pools should call ```pool.join()``` after ```pool.close()``` to avoid similar issues, as shown for example in https://stackoverflow.com/questions/38271547/when-should-we-call-multiprocessing-pool-join . 

I'm unfortunately not able to check on my side and do a pull request in the near future, so I was hoping you could look into it.

**Comment by tgrondier** [comment]
![image](https://user-images.githubusercontent.com/5384645/42285396-c9c6fed4-7faf-11e8-8daa-3629a618fbc5.png)

Here is an screenshot of processes not being cleared after execution

**Comment by slundberg** [comment]
Thanks for pointing this out, and suggesting a potential solution! I'll add the `pool.join()` call as suggested in the SO post.

**Comment by tgrondier** [comment]
Hey Scott, 

I updated shap to the latest version via pip and I can confirm that this behaviour is gone. Thank you for the great work !
