### ISSUE TITLE
Use SHAP with custom class neural network

### ISSUE THREAD

**Issue by Simb94** [shap/shap#1424]
Hello,

I'm trying to explain the behaviour of a custom neural network using SHAP (the class of the custom neaural network is called foo and have a method predict that have as parameter np.array to masquerade the output).

The structure of the neural network is:
Layer (type)                    Output Shape         Param #     Connected to                     

input_1 (InputLayer)            [(None, 72, 57, 34)] 0                                            
__________________________________________________________________________________________________
one_hot_encoder (OneHotEncoder) (None, 72, 57, 55)   0           input_1[0][0]                    
__________________________________________________________________________________________________
learnable_background (Learnable (None, 72, 57, 63)   32832       one_hot_encoder[0][0]            
__________________________________________________________________________________________________
sequential (Sequential)         (None, 72, 57, 512)  32768       learnable_background[0][0]       
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 72, 57, 1)    513         sequential[0][0]                 
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 72, 57, 1)]  0                                            
__________________________________________________________________________________________________
multiply (Multiply)             (None, 72, 57, 1)    0           dense_1[0][0]                    
_                                                                                    input_2[0][0]  

As u can see this network have 2 input layer (one of the two is connected to the last layer and it is intended to exclude few points from the 57*72).
With shap 0.36.0 and TF 2.1.0 i have an issue trying to apply the DeepExplainer and KernelExplainer to this model because the neural network is wrapped in a custom container class and DeepExplainer seems not able to recognize the model type

code for DeepExplainer:
explainer = shap.DeepExplainer(model_, [background, target_1])
error:
AssertionError: <class 'foo'> is not currently a supported model type!

and i'm not able to use KernelExplainer as well because the method does not want a list as input.

Code:
explainer = shap.KernelExplainer(model_.predict, [background, target_1])
error:
AssertionError: Unknown type passed as data object: <class 'list'>

Can u help me to solve this problem? Do you need some additional information?

Thanks

**Comment by HughChen** [comment]
Hi Simb94,

Extending DeepExplainer might be a bit more complicated.  If you wanted to try out KernelExplainer, I believe it expects `data` to be a 2D array.  This means that even deep models that use images as inputs don't work naively.  Instead, you can just transform the data to be 2D (nsamples, nfeatures) and define a prediction wrapper that transforms a given sample into the format your model expects and then calls predict (here's an [example](https://github.com/slundberg/shap/blob/master/notebooks/kernel_explainer/ImageNet%20VGG16%20Model%20with%20Keras.ipynb)).
