### ISSUE TITLE
Would It be possibile to add link='logit' option to waterfall_plot? (suggestion)

### ISSUE THREAD

**Issue by almirb** [shap/shap#1429]
Hello!

I'm using SHAP for some explanations and It's very very nice and useful! Thanks!
I switched from force_plot to waterfall_plot to suit my needs.... but I'm missing the **link='logit'** option.

Would It be possible to add this option in future?
Thanks on advance!

**Comment by slundberg** [comment]
Great idea! Putting this in the enhancements section

**Comment by jonnor** [comment]
Related to https://github.com/slundberg/shap/issues/1532
