### ISSUE TITLE
Using group names in visualizations

### ISSUE THREAD

**Issue by mizukasai** [shap/shap#143]
Hello, 

I am trying to explain a model that works on dummified categorical features. What I understood from the code is that we can use `groups` and `group_names` to specify what features go together. So I used this and got the right number of `shap_values`. But the problem comes when I try to `force_plot` this function does not consider the group_names at all.
Do you have suggestions on how to handle categorical features in visualizations?

**Comment by slundberg** [comment]
Ah! Good question. You need to use the `feature_names` keyword argument to `force_plot` for that.
