### ISSUE TITLE
Code for summary_plot

### ISSUE THREAD

**Issue by BrunoBarre** [shap/shap#1432]
Hi, I searched for the code in github for the summary_plot, but didn't find anything in either the plots or the explainers directory.

I would just like to see how it really works so as to copy/paste it and change minor things.
By the way, you could add reference code links in the documentation website, like with [summary_plot documentation](https://shap.readthedocs.io/en/latest/generated/shap.summary_plot.html#shap.summary_plot).

Thanks a lot!

**Comment by BrunoBarre** [comment]
My goal is to modify the tickslabels of the colorbar ("High" and "Low"), for example to translate them in German.

They seem to be hardcoded on the ._labels.py file. Would it be possible to add two parameters for the beeswarm function, something like :
color_bar_label_low=labels["FEATURE_VALUE_LOW"] and color_bar_label_high=labels["FEATURE_VALUE_HIGH"]

Like the parameters : color_bar_label=labels["FEATURE_VALUE"].

thanks a lot :+1:

**Comment by BrunoBarre** [comment]
I finally managed to do it with :

```
#Do every cases, and check whether it's a colorbar, then test every combination to have the right one (fastidious...)
    for i in range(len(plt.gcf().get_children())) :
        fc = plt.gcf().get_children()[i]
        for j in range(len(fc.get_children())) :
            fcc = fc.get_children()[j]
            if hasattr(fcc, "set_ticklabels") :
                print(i, j, fc, fcc, "\n")

i = 2 ; j = 8
plt.gcf().get_children()[i].get_children()[j].set_ticklabels(["Niedrig", "Hoch"])
```



But I think it would be more convenient if some parameters in the summary_plot function could be added :+1:

**Comment by mikelgg93** [comment]
If you plan to use just German, check the _labels.py file in PythonXXX>Lib>site-packages>shap>plots>_labels.py
