### ISSUE TITLE
A bug when running the tutorial  Mnist DeepExplainer under Keras Framework

### ISSUE THREAD

**Issue by AllenWu18** [shap/shap#1448]
Hi, I just run the tutorial Mnist DeepExplainer code under Keras, the version of all the dependency packages are: Keras 2.3.1, Tensorflow 1.13.1, and shap 0.36.0. After training the network, it shows the error:
" Dimension i in both shapes must be equal, but are 10 and 1. Shapes are [?,10] and [?,1]...."

So how should I solve the problem except upgrading the version of tf....
THX a lot!

**Comment by wrk666** [comment]
I have also encountered such an issue, have you successfully solved it?
