### ISSUE TITLE
making it easier to initialize Explanations

### ISSUE THREAD

**Issue by antonkulaga** [shap/shap#1453]
When I average shap values from 5 different lightgbm models (and thus explainers) I cannot initialize Explanation through explainers so I would prefer to initialize it separately in the code. However, I failed to port its initialization from __call__method of the TreeExplainer

**Comment by slundberg** [comment]
Sorry it proved a challenge to init them easily. We are working on finalizing the object, so if you have suggestions let me know! For your specific case I added support for the arithmetic operations on the Explanation objects directly, so you can now do:
```
sum(list_of_5_explanation_objects) / 5
```
(on the master branch of the code)

**Comment by antonkulaga** [comment]
@slundberg any plans to release v0.36.1 anytime soon? This feature looks really useful
