### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by wprazuch** [shap/shap#1456]
I tried to implement LSTM explainability using shap and used this[ notebook](https://github.com/slundberg/shap/blob/master/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.ipynb) . However, in line:

`shap_values = explainer.shap_values(x_test[:10])`

I receive following error:
`site-packages\shap\explainers\_deep\deep_tf.py in anon()
    352                     shape = list(self.model_inputs[i].shape)
    353                     shape[0] = -1
--> 354                     data = X[i].reshape(shape)
    355                     v = tf.constant(data, dtype=self.model_inputs[i].dtype)
    356                     inputs.append(v)

TypeError: 'NoneType' object cannot be interpreted as an integer`

My tf version is 2.3.0

Does anyone have the same problem?

**Comment by mxhofer** [comment]
Yes, same issue here. I tried to prepend `tensorflow.` to all the keras imports to use tensorflow instead of plain keras, but got the same error. 

tf version 2.3.0. shap version 0.36.0.

**Comment by Kamalnor** [comment]
Same issue here

**Comment by guanzhuo-qiao** [comment]
Same issue here. Does anyone have a solution for this error?

**Comment by YouzhiHe** [comment]
I met same issue. Is three a solution? thank you！

**Comment by YouzhiHe** [comment]
Same issue here. Does anyone have a solution for this error?

**Comment by hugokitano** [comment]
still looking for an answer on this too!

**Comment by milletml-celonis** [comment]
Same issue here. @slundberg any chance you could take a look at this?

**Comment by mihailyanchev** [comment]
Hi all, I ran into the same issue and after reading as much as I could find, it seems to be due to the fact that keras leaves the model input dynamic with None type -> (None, 12, 16) for example.

On a similar thread, someone suggested having the model input fixed, but it might be a problem if you want to use train and test sets with different shapes. This solution worked out for me https://stackoverflow.com/questions/47940040/how-to-set-input-shape-of-a-trained-model-in-keras

Hope this helps!

**Comment by JichenGuo** [comment]
Same issue. Did anyone solve it? Many thx in advance!

**Comment by NASSERABDELLAH** [comment]
one of your functions return 'None' verify all your loops calculations and functions 
![fezfefezfef](https://user-images.githubusercontent.com/72876481/129987667-644bba3b-5e39-4fad-9d55-976f5dc89ad9.PNG)

**Comment by SunnyW4869** [comment]
same issue here using deep explainer
shap version 0.40.0
tensorflow 2.4.1

**Comment by corazzon** [comment]
Same issue here

**Comment by ry44an** [comment]
> one of your functions return 'None' verify all your loops calculations and functions ![fezfefezfef](https://user-images.githubusercontent.com/72876481/129987667-644bba3b-5e39-4fad-9d55-976f5dc89ad9.PNG)

repl.it kid

**Comment by ry44an** [comment]
> Same issue. Did anyone solve it? Many thx in advance!

me not tell

**Comment by joshua-xia** [comment]
some issue happened on my environment, any solution for this critical issue? Thx

**Comment by mihailyanchev** [comment]
> some issue happened on my environment, any solution for this critical issue? Thx

Check if you have upgraded your version of tensorflow.

**Comment by joshua-xia** [comment]
> > some issue happened on my environment, any solution for this critical issue? Thx
> 
> Check if you have upgraded your version of tensorflow.

Yes, I am using tensorflow 2.x. I downgrade tf to 1.15.0, 
The following warning happened when training:

 The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

and the following error happened when execute: shap.DeepExplainer(model, x_train[:100]):

FailedPreconditionError: Attempting to use uninitialized value lstm_1/kernel
	 [[node lstm_1/kernel/read (defined at home/xiaxiaohua/anaconda3/envs/ai-lab/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

I am using:
Keras  2.1.6
tensorflow                   1.15.0
tensorflow-gpu               1.15.0

Anybody provide the proper environment which can run this demo successfully? I am eager to show this demo to product manager. thx very much!
