### ISSUE TITLE
Will the SHAP be able to process the time-series data?

### ISSUE THREAD

**Issue by dongdyang** [shap/shap#146]
**The current SHAP is be able to process the data like this: (one input -> one output).**

But I am wondering **is it able to process the data like (multi input -> one output)?**
The scenario is Text Processing. I want to know which word is more importance.
At the same time, I need to take the order of words into account.

In this way, the model's input will be one word at one time. Finally, after all words in a sentence have been processed, one output is generated.

The question is Will the current SHAP support it? I try to find something in the source code, but nothing is found. Might be it is for my carelessness. Sorry for bothering again.

**Comment by slundberg** [comment]
Truly variable length inputs are not supported, but they can be mimicked by feeding in a constant length vector that is larger than the longest sentence context. For a text processing example check out: https://github.com/slundberg/shap/blob/master/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.ipynb

**Comment by shamitb** [comment]
Is this appropriate?
https://medium.com/datadriveninvestor/time-step-wise-feature-importance-in-deep-learning-using-shap-e1c46a655455

**Comment by ph0123** [comment]
> is appropriate?

No. I run it, and there are some errors :D

**Comment by annezhangxue** [comment]
> Is this appropriate?
> https://medium.com/datadriveninvestor/time-step-wise-feature-importance-in-deep-learning-using-shap-e1c46a655455

I ran the code and unfortunately it also doesn't work out
