### ISSUE TITLE
gradient registry has no entry for: shap_LeakyRelu

### ISSUE THREAD

**Issue by Yufei-Z** [shap/shap#1463]
could you support leakyrelu, which is a new activiation function

**Comment by mzakharocsc** [comment]
This hack to at least get past the runtime error if a model contains LeakyRelu 

```python
shap.explainers._deep.deep_tf.op_handlers["LeakyRelu"] = shap.explainers._deep.deep_tf.op_handlers["Relu"]
```

**Comment by detrin** [comment]
We do support it now https://github.com/shap/shap/blob/1ccbf672399d3467e4e4433894ed00e4f067e258/shap/explainers/_deep/deep_pytorch.py#L390

@thatlittleboy Candidate for closing.
