### ISSUE TITLE
Using Shap with an AutoTrackable object (from loading a saved model)

### ISSUE THREAD

**Issue by tcaffrey** [shap/shap#1474]
I'm using tensorflow 2 and have a model saved which I've been loading into a notebook. Loading the model returns an AutoTrackable object which I've been using to return predictions using the 'predict' model signature. 

`model = tf.saved_model.load(export_dir = model_dir)`
`model`
`<tensorflow.python.training.tracking.tracking.AutoTrackable>`

However, I've not been able to use this AutoTrackable object within a Shap explainer and couldn't see a similar problem posed online. For what I'm doing I have to load saved models into the notebook I'm working within. Any help or advice on what I'm doing wrong would be greatly appreciated.

**Comment by alielabridi** [comment]
@tec-88 were you able to find a solution to how to use DeepExplainer with SignatureDef and AutoTrackable objects?

**Comment by jashdoshi07** [comment]
Hey, @tcaffrey were you able to resolve this issue?
