### ISSUE TITLE
how can we get the exact number?

### ISSUE THREAD

**Issue by WEIFZH** [shap/shap#1476]
Hi, thanks for ur tool, I have a question: how to get the mean absolute value of the SHAP values for each feature(exact number)? I hope to redraw the feature importance figure, looking forward to ur reply!

**Comment by HughChen** [comment]
If you have `shap_values` calculated by any explainer in the shap package it should be a numpy array of shape `(# samples, # features)`.  You sould be able to just do `np.mean(np.abs(shap_values),0)`.  Hope that helps!

**Comment by WEIFZH** [comment]
> If you have `shap_values` calculated by any explainer in the shap package it should be a numpy array of shape `(# samples, # features)`. You sould be able to just do `np.mean(np.abs(shap_values),0)`. Hope that helps!

Thank you very much!

**Comment by desertnaut** [comment]
Shouldn't we close this now?

**Comment by ZhangTP1996** [comment]
Shouldn't it be `np.mean(np.abs(shap_values), 1)`？This is the same with the results of shap.summary_plot
