### ISSUE TITLE
plot_type bar for summary_plot

### ISSUE THREAD

**Issue by tobiasraabe** [shap/shap#148]
Hi all,

first, thanks for your package. It really helps me a lot.

One of the examples in the README runs ``shap.summary_plot(shap_values, X, plot_type="bar")`` to produce bars with the average absolute shap value over all samples for all features. I want to do the same for a binary classification problem, but the produced graph is empty. Is this plot option not available for this kind of problem? If so itentionally, why does it not make sense to produce this graph? It looks like ``dot`` and ``violin`` are the only valid options here and ``bar`` is a fallback for multiclass problems. 

https://github.com/slundberg/shap/blob/95a5c1aab5a3f5110b722be438deee3995970804/shap/plots.py#L329-L336

OT: You check the type of the object by using ``str(type(...))`` in line 334. It is more canonical and maybe easier for you if you use ``isinstance(shap_values, list)`` instead. ([Link](https://stackoverflow.com/questions/152580/whats-the-canonical-way-to-check-for-type-in-python))

**Comment by slundberg** [comment]
Hmm...it should work for binary classification, just like anything else. Could you post a short example of the problem?

Also...good point for the list type comparison, I use the string comparison in many places where I don't want to assume that the type is defined (for example a LightGBM type on a system without LightGBM installed) and so the format was copied over here.

**Comment by tobiasraabe** [comment]
Everything works fine for me now. I probably made a silly mistake and used an old version. My bad. Sorry for taking your time.
