### ISSUE TITLE
How do you use `force_plot` html in a web application?

### ISSUE THREAD

**Issue by navdeep-G** [shap/shap#1492]
* I am trying to use the rendered HTML from the following code:

```
shap.force_plot(expected_value, shap_values, input_df[nput_cols])
output_file = f"{tmp_path}/shap_pd.html"
shap.save_html(output_file, plot, False)
```
However, when I try to render the saved HTML in my web application, I get:

```
Visualization omitted, Javascript library not loaded!
Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security. If you are using JupyterLab this error is because a JupyterLab extension has not yet been written.
```

Is there anyway to bypass this? 

Thanks

**Comment by lrjball** [comment]
It looks like your web app is blocking javascript. If there is no way of unblocking it then the other option you have is generating the force plot using `matplotlib=True` and then saving that image, although it won't be interactive.
