### ISSUE TITLE
Clarification when applying Tree SHAP

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#150]
Hi,

When plotting SHAP interaction plots, we use a normalized dataset to get interaction values. When plotting interaction plots can we use denormalized dataset. Because we need to know the real value ranges. For an example age( 20,30,40 etc. Not the normalized values ) Will it be a problem?

`shap_values_xgb = shap.TreeExplainer(xgb_clf).shap_values(data_test.as_matrix())`
`shap_interaction_values = shap.TreeExplainer(xgb_clf).shap_interaction_values(data_test.as_matrix())`

```
shap.dependence_plot(
    ("age", "sex"),
    shap_interaction_values,data_test2,
    display_features=data_test
)

```
Here we use data_set2 , which is not normalized dataset. But we have used shap_interaction_values which made of normalized data set. Will it be an issue?

Hope that you understand my question.

**Comment by slundberg** [comment]
If mean you want to use the non-normalized data for the `display_features` then that is fine. Since XGBoost only depends on the rank of the data any rank preserving normalization will have no effect on the model.

**Comment by DiliSR** [comment]
Hi,
 display_features function is working for only categorical data. But not for continuous data. Is that so? But the continuous data will also be different after normalization and before normalization.

**Comment by slundberg** [comment]
display_features should work for all types of inputs. Is there an example where it's not for you?
