### ISSUE TITLE
TreeExplainer support for DenseData

### ISSUE THREAD

**Issue by brunofacca** [shap/shap#1512]
First, thank you for creating and maintaining this awesome library.

I've tried to use KMeans to select a number of weighted samples to use as background data for TreeExplainer:
```
background_data = shap.kmeans(fold_data_pack.train_features, 100)
explainer = shap.TreeExplainer(
    model=trained_model,
    data=background_data,
    feature_perturbation='interventional',
)
```
...and it failed with:
```
  File "/home/redistributor/.pyenv/versions/3.8.5/lib/python3.8/site-packages/shap/explainers/_tree.py", line 93, in __init__
    raise Exception("Unsupported masker type: %s!" % str(type(self.masker)))
Exception: Unsupported masker type: <class 'shap.utils._legacy.DenseData'>!
```

Is DenseData not supported for `TreeExplainer`? Is there any other way of passing weighted observations (i.e., those that represent a larger number of points have a higher weight) to `TreeExplainer`?

Thank you!

**Comment by fior-di-latte-byte** [comment]
I'm having the same issue with `KernelExplainer`.

**Comment by fedetaladriz** [comment]
Use the `.data` attr of DenseData

**Comment by brunofacca** [comment]
Thank you for the suggestion, @fedetaladriz. But doesn't `.data` return the observations but ignore the weights?

**Comment by Muennighoff** [comment]
How did you fix this? :)

**Comment by survivebycoding** [comment]
> Use the `.data` attr of DenseData

How are you doing this? What did you change in the code of the OP?

**Comment by survivebycoding** [comment]
> Thank you for the suggestion, @fedetaladriz. But doesn't `.data` return the observations but ignore the weights?

how did you fix the code?
