### ISSUE TITLE
model_output='log_loss' support for multiclass objectives

### ISSUE THREAD

**Issue by brunofacca** [shap/shap#1515]
I'm trying to use TreeExplainer with `model_output='log_loss'` with either: 
* XGBoost with `multi:softprob` objective or
* LightGBM with `multi:softprob`objective 

... and getting the following error:
```
  File "/home/redistributor/.pyenv/versions/3.8.5/lib/python3.8/site-packages/shap/explainers/_tree.py", line 152, in __init__
    raise Exception("Model does not have a known objective or output type! When model_output is " \
Exception: Model does not have a known objective or output type! When model_output is not "raw" then we need to know the model's objective or link function.
```

By looking at [_tree.py](https://github.com/slundberg/shap/blob/master/shap/explainers/_tree.py#L564-L578), it seems that those objectives are not supported. Is that correct? If so, are there any workarounds I can use to calculate SHAP values for with the above multiclass objectives?

Thank you

**Comment by ftatarli** [comment]
Hey @brunofacca, wondering if you found out something related to this. I'm facing the same issue. Thanks!

**Comment by brunofacca** [comment]
Sorry @ftatarli, I haven't.
