### ISSUE TITLE
nan SHAP values in the XGBOOST implementation

### ISSUE THREAD

**Issue by ihadanny** [shap/shap#152]
can you please review https://github.com/dmlc/xgboost/issues/3333 ?
when unique_path[i].pweight  == 0 did you mean for 0 contrib to be added?

**Comment by slundberg** [comment]
Thanks for pointing that out. I'll try and fix it soon.

**Comment by sergeyf** [comment]
I just ran into this issue. Just confirming: is it safe to replace the nans with 0?

**Comment by slundberg** [comment]
@sergeyf Unfortunately not, the only option right now is to fall back to the approximate Saabas method `approximate=True`. Other deadlines have prevented me tackling this yet...

**Comment by sergeyf** [comment]
Gotcha, thank you.

**Comment by ddearauj** [comment]
I ran into this issue as well, but adding the `approximate=True` still resulted in some nan values

**Comment by slundberg** [comment]
@ddearauj if you have a small sharable example of that it would be helpful.

**Comment by ddearauj** [comment]
@slundberg I will try to anonymize my dataset. What is the best way to send this?

**Comment by slundberg** [comment]
If you don't want it online you can just email it to me directly (email is on my papers). I am away for the next two weeks, but I'll see if I can reproduce it if you share an example.

**Comment by Kodiologist** [comment]
@slundberg My lab at Mount Sinai is hoping to use SHAP with XGBoost for variable selection and interpretation in a new paper, but this bug is turning out to be a bit of a showstopper. We end up with models where up to 92% of observations have NaN for the SHAP of at least one feature. I'm looking into fixing the bug using the hints at dmlc/xgboost#3333. Any more I should know before diving into XGBoost's SHAP code? I know R and Python well and I'm halfway-competent in C++ (I know C better), but I haven't worked on R–C++ or Python–C++ interfaces before. My lab mostly uses R.

**Comment by astrixg** [comment]
Hi, is there any update/fix on this issue? Kind of stuck in my progress. Can anyone explain why 0 is not a suitable replacement for the NaN values?

**Comment by slundberg** [comment]
A fix was already merged into the latest XGBoost master. Not sure if it is
in a released version yet or not.

**Comment by IvanUkhov** [comment]
For those looking at this issue, XGBoost 0.81 does not include the fix, but it will presumably be available in the next release.

**Comment by astrixg** [comment]
Thanks, I was able to use the fix through the XGBoost master available here.

**Comment by ravi-fractal** [comment]
Hi astrixg,
I am  also facing the same problem and trying to look for a solution. Can you please let me know the steps you followed to fix this issue.

Thanks in advance.

**Comment by IvanUkhov** [comment]
Here are the steps:

https://xgboost.readthedocs.io/en/latest/build.html

First you build the library and then install the package.

**Comment by IvanUkhov** [comment]
Yay! Released!

https://github.com/dmlc/xgboost/releases

**Comment by slundberg** [comment]
Great! I am going to close this now :)
