### ISSUE TITLE
Differences in machine learning and statistical methods

### ISSUE THREAD

**Issue by launis** [shap/shap#1520]
A bit of a philosophical question ...

In general, the differences between Predictive Machine Learning and Statistical Inference are due to different use cases. Machine Learning models are designed to create predictions, and Statistical Inference also explain the relationships between features. However, the boundary between Statistical Inference and Predictive Machine Learning is not clear, and different definitions can be given for both. Is Machine Learning really statistics by another name?

The power and algorithms of Machine Learning are strong compared to traditional Statistical Models. Machine Learning has not been able to replace Statistical Inference because it does not explain the relationships between the variables accordingly. However, I ask, if this is changing? Will Machine Learning be used more in the future instead of Statistical Models / Statistical Inference as the explainability of machine learning models improve, as with this excellent SHAP model?

**Comment by michaelamoako** [comment]
Interesting discussion topic.. perhaps this could be moved to Discussions? https://github.com/slundberg/shap/discussions/1462#discussion-21069
