### ISSUE TITLE
can't import shap after install 

### ISSUE THREAD

**Issue by celinexuzhang** [shap/shap#1522]
hi! I m having issue import SHAP, after conda install. PLEASE HELP! THANK YOU!

Error message: 

ImportError                               Traceback (most recent call last)
<ipython-input-64-efbb001a1501> in <module>
----> 1 import shap

C:\Program Files\Anaconda3\lib\site-packages\shap\__init__.py in <module>
     35     from .plots.monitoring import monitoring_plot
     36     from .plots.embedding import embedding_plot
---> 37     from .plots.partial_dependence import partial_dependence_plot
     38     from .plots.bar import bar_plot
     39     from .plots.waterfall import waterfall_plot

C:\Program Files\Anaconda3\lib\site-packages\shap\plots\partial_dependence.py in <module>
      7     warnings.warn("matplotlib could not be loaded!")
      8     pass
----> 9 from mpl_toolkits.mplot3d import Axes3D
     10 import numpy as np
     11 import pandas as pd

C:\Program Files\Anaconda3\lib\site-packages\mpl_toolkits\mplot3d\__init__.py in <module>
----> 1 from .axes3d import Axes3D

C:\Program Files\Anaconda3\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py in <module>
     27 import matplotlib.transforms as mtransforms
     28 from matplotlib.axes import Axes, rcParams
---> 29 from matplotlib.axes._base import _axis_method_wrapper
     30 from matplotlib.transforms import Bbox
     31 from matplotlib.tri.triangulation import Triangulation

ImportError: cannot import name '_axis_method_wrapper' from 'matplotlib.axes._base' (C:\Program Files\Anaconda3\lib\site-packages\matplotlib\axes\_base.py)

**Comment by lrjball** [comment]
What version of matplotlib do you have installed?
try:
```python
import matplotlib
print(matplotlib.__version__)
```

**Comment by celinexuzhang** [comment]
> What version of matplotlib do you have installed?
> try:
> 
> ```python
> import matplotlib
> print(matplotlib.__version__)
> ```

I used conda install(re-install), and installed the 3.3.1 ( which is weird since there is a 3.3.2 just made available, I need to figure that out...), however, for now, I fixed this this issue by re-start the kernel in Notebook. Thank you!

**Comment by lrjball** [comment]
No worries, glad you got it sorted
