### ISSUE TITLE
Erroneous line of code in deep_tf.py

### ISSUE THREAD

**Issue by lrjball** [shap/shap#1527]
https://github.com/slundberg/shap/blob/491d46a540d16fb5a9868de6be2913599c850167/shap/explainers/_deep/deep_tf.py#L154

This line is in `deep_tf.py` but contains both typos and references to objects which don't exist. Does anyone know what it is supposed to say/if it is even needed? Seems to have been introduced in 9df1fde942b6a0536f297826cfa221a756d66b2a by @slundberg

**Comment by thatlittleboy** [comment]
Not an issue anymore, the code line has been commented out.
