### ISSUE TITLE
AttributeError: 'Explanation' object has no attribute 'cohorts'

### ISSUE THREAD

**Issue by sreeram004** [shap/shap#1528]
I was following the [example ](https://shap.readthedocs.io/en/latest/example_notebooks/plots/bar.html)from the docs to create cohort bar plot.

I ended up with this error,

`AttributeError: 'Explanation' object has no attribute 'cohorts'`

I could see that the explanation object doesn't have attribute cohort on inspection.

Is this a bug?

I'm using the latest release in pypi : 0.36.0

**Comment by arsine1996** [comment]
the same, were you able to resolve it?

**Comment by sreeram004** [comment]
no
