### ISSUE TITLE
Cannot install shap on pycharm 

### ISSUE THREAD

**Issue by Rupam07** [shap/shap#1530]
Hi, 

I am trying to install shap using the pip, project interpreter in PyCharm but due to some reason it wont allow me to. There isn't an option to search and install it separately 

Tried doing it multiple times but keeps failing. Is there any other way I can fix this? Seems like I am stuck with this issue forever. Please help me with this

<img width="250" alt="Screen Shot 2020-10-16 at 9 12 43 AM" src="https://user-images.githubusercontent.com/48689684/96282575-c41e6b80-0f8f-11eb-98c2-f4441f0c6172.png">
<img width="917" alt="Screen Shot 2020-10-16 at 9 13 13 AM" src="https://user-images.githubusercontent.com/48689684/96282655-d5677800-0f8f-11eb-9508-31a4f0c332be.png">

**Comment by lrjball** [comment]
It looks like your pycharm project is set up using R instead of Python. You can either install shap using `pip install shap` from the terminal in pycharm (note: it looks like you are using the python console, not the terminal), or you can do 'file > settings > project > python interpreter > install > search for shap' after setting up a python project in pycharm.

**Comment by Rupam07** [comment]
I used the terminal in order to install the shap library but that does not work. How can I change the project setup to Python instead of R? 

I think I tried both pip and project interpreter installation but that did not work so I guess that should be the first guess of project setup in R

**Comment by lrjball** [comment]
Take a look at this guide for setting up a python project in pycharm: https://www.jetbrains.com/help/pycharm/creating-and-running-your-first-python-project.html
Then see this one for installing packages: https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html

**Comment by Rupam07** [comment]
I just checked the links and the respective environment and it shows that the project is running on python 3.8 so I think that clears the question of it running in R 
<img width="993" alt="Screen Shot 2020-10-16 at 6 32 42 PM" src="https://user-images.githubusercontent.com/48689684/96325615-02427c00-0fde-11eb-83b6-88797625cc52.png">

Tried installing the shap library through the python interpreter but it wont show an options to do so 
<img width="918" alt="Screen Shot 2020-10-16 at 6 35 02 PM" src="https://user-images.githubusercontent.com/48689684/96325655-52b9d980-0fde-11eb-8d54-8d96708f8340.png">

**Comment by lrjball** [comment]
Click on 'Manage Repositories'. Which repos are showing up? It should show either pypi or conda repo depending on which one you are using.

**Comment by Rupam07** [comment]
<img width="823" alt="Screen Shot 2020-10-17 at 8 16 06 AM" src="https://user-images.githubusercontent.com/48689684/96346514-06f44800-1051-11eb-8054-99b5827d0914.png">
It says default

**Comment by nicornk** [comment]
From the screenshot it looks like you are using conda. From the Readme of the repo it is visible that you need to use conda-forga channel:

https://github.com/slundberg/shap#install

Try adding conda-forge to your Pycharm Repositories.

**Comment by Rupam07** [comment]
Okay that worked
Thank you!!
