### ISSUE TITLE
How to show the mean |SHAP value| data label within the summary plot ( for multiclass output using lightgbm)

### ISSUE THREAD

**Issue by celinexuzhang** [shap/shap#1531]
Hello! Thank you for the awesome package. I try have better understanding of this..... 

Is there a way to see the SHAP value in summary plot? My summary plot looks like this- 
![image](https://user-images.githubusercontent.com/13789560/96308680-70c90f00-0fc9-11eb-8dc2-99b8e8eacc46.png)
For example: **what's the mean|shap_value| of F1 for class 0? Is there a way I can show the data label in the summary plot? 
If not, can I manually calculated the mean value based on the shap_value output? How?** 
For example shap value nd-array output looks like this:
 [ array ( [ [ 0.1, 0,2. 0.3 .....,0.9,0.8,0.5],
                 [0.11, 0,12. 0.13 .....,0.19,0.18,0.15],
                 ...... [0.201, 0,202. 0.203 .....,0.209,0.208,0.205]]),
   array ( [ [ 0.12, 0,22. 0.32 .....,0.92,0.82,0.52],
                 [0.21, 0,22. 0.23 .....,0.29,0.28,0.25],
                 ...... [0.301, 0.302, 0.303 .....,0.309,0.308,0.305]])]
**Does 0.1, 0.2 in shap_value[0][0] corresponding to F1 and F2, which is order by feature importance? or it corresponding to features order from the input dataset ?
To Manually calculate F1 average shap impact to class 0, is something like : (0.1+0.11+....+0.201)/Total # of obs , correct?**

Thank you! I appreciate it!

**Comment by AndreasThinks** [comment]
I think what you're going for is:
`shap.summary_plot(shap_values[1], X_test)
`

Otherwise you are computing the shap values for both the positive and negative class.
