### ISSUE TITLE
link='logit' option for summary_plot

### ISSUE THREAD

**Issue by felixchretien** [shap/shap#1532]
Should be a feature for shap.summary_plot: from showing log odds to probabilities. It makes a big difference to explain a model to a non-data scientist.

**Comment by ukky17** [comment]
Without the `link='logit'` option, one workaround would be to use `model_output='probability'` to initiate the explainer (https://github.com/slundberg/shap/issues/756#issuecomment-522273358). I guess the following code is a solution.

```
# X: data, model: xgboost classifier

explainer = shap.TreeExplainer(model, model_output='probability', data=X)
shap_values = explainer.shap_values(X)
shap.summary_plot(shap_values, X)
```
