### ISSUE TITLE
What is the best approach to use shap to explain a time series model from gluonts. 

### ISSUE THREAD

**Issue by MariPlaza** [shap/shap#1547]
We train a deep AR model for several time series using gluonts. Now we want to use SHAP to explain the model. What is the best approach to do it.

It is my first time using SHAP.

**Comment by michaelamoako** [comment]
@MariPlaza to clarify, are you looking to calculate time-step wise feature importance, referring to a model that takes a 3D input(samples, time step, features) and looking for an output of 3D data containing (feature importance, time steps, features)?

Or are you referring to a deep AR model that has a single value column (with each value corresponding to a different time), and that is predicting m values for a future time:

'2018-08-01 00:00:00' 5
'2018-08-01 00:05:00' 6
'2018-08-01 00:10:00' 4
….
'2018-09-30 00:00:00' 12

And are predicting values for some future data (i.e: 12 values for the midnight hour of  '2018-10-01 00:00:00' taking 5 minute timesteps)

I've seen the former explored in a few different ways (i.e: https://medium.com/datadriveninvestor/time-step-wise-feature-importance-in-deep-learning-using-shap-e1c46a655455)

At a high-level, SHAP aims to produce the feature importance of each feature, and how these importance values contribute to the model's output. In the case of the latter, how would you think about the 'features' that you want to assign importance to, and the output being explained? 

This discussion could also be helpful: https://github.com/slundberg/shap/discussions/1464

**Comment by michaelamoako** [comment]
@MariPlaza to clarify, are you looking to calculate time-step wise feature importance, referring to a model that takes a 3D input(samples, time step, features) and looking for an output of 3D data containing (feature importance, time steps, features)?

Or are you referring to a deep AR model that has a single value column (with each value corresponding to a different time), and that is predicting m values for a future time:

'2018-08-01 00:00:00' 5
'2018-08-01 00:05:00' 6
'2018-08-01 00:10:00' 4
….
'2018-09-30 00:00:00' 12

And are predicting values for some future data (i.e: 12 values for the midnight hour of  '2018-10-01 00:00:00' taking 5 minute timesteps)

I've seen the former explored in a few different ways (i.e: https://medium.com/datadriveninvestor/time-step-wise-feature-importance-in-deep-learning-using-shap-e1c46a655455)

At a high-level, SHAP aims to produce the feature importance of each feature, and how these importance values contribute to the model's output. In the case of the latter, how would you think about the 'features' that you want to assign importance to, and the output being explained?

**Comment by desertnaut** [comment]
@michaelamoako would you mind removing the duplicate comment?
