### ISSUE TITLE
Deepexplainer fails with tf2.3, ok with 2.2

### ISSUE THREAD

**Issue by mshearer0** [shap/shap#1548]
AttributeError: 'DataFrame' object has no attribute 'dtype'

**Comment by mactone** [comment]
Add **.values.astype('float')** will help on this AttributeError

shap.initjs()
data_for_prediction = X_test.iloc[0:1,:].**values.astype('float')**
background = X_train.iloc[0:100,:].**values.astype('float')**
explainer = shap.DeepExplainer(model, background)
shap_values = explainer.shap_values(data_for_prediction)
shap.force_plot(explainer.expected_value[0], shap_values[0], data_for_prediction)

**Comment by codecx07** [comment]
How would you get a force_plot for a set of values? Also, this method gives an error

>  TypeError: Object of type EagerTensor is not JSON serializable
