### ISSUE TITLE
"Keras LSTM for IMDB Classification" tutorial error

### ISSUE THREAD

**Issue by hugokitano** [shap/shap#1551]
In this tutorial (https://slundberg.github.io/shap/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html?fbclid=IwAR1CDBZxupBF4lKYGWW6l9KwTgrjbim2c8X0HQJfyVXWr2MIwOskBHZJvvY), the following line throws an error. Any idea what it is?

```
shap_values = explainer.shap_values(x_test[:10])
TypeError: 'NoneType' object cannot be interpreted as an integer
```

There is a warning "keras is no longer supported, please use tf.keras instead" one line earlier. I replaced all instances of keras in the code with tf.keras, but the warning and error persist.

**Comment by michaelamoako** [comment]
Maybe the same issue as in #1544  ?

**Comment by The-ttj** [comment]
Hello, I have the same problem as you, and I tried my best to solve it, but I failed. Could you tell me how to solve this problem? thank you!!

**Comment by venergiac** [comment]
the same here on standard tutorial Keras LSTM for IMDB Sentiment Classification

'NoneType' object cannot be interpreted as an integer

**Comment by ghost** [comment]
The example is not reproducible, kindly try the example as it is in Google colab, it is causing lots of errors related to incompatible tensorflow versions ,what is the target tensorflow or keras versions for deep explainer object

**Comment by loewenm** [comment]
I can confirm that running this code in Google Colab produces errors (multiple in fact, but two are warnings not related to SHAP).

The only line of code that I altered from the example above was including:

`!pip install shap`


I indeed get the same error as mentioned above. Here's a bit more information:


`
keras is no longer supported, please use tf.keras instead.
Your TensorFlow version is newer than 2.4.0 and so graph support has been removed in eager mode. See PR #1483 for discussion.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-d0b49e7ececc> in <module>()
      6 # explain the first 10 predictions
      7 # explaining each prediction requires 2 * background dataset size runs
----> 8 shap_values = explainer.shap_values(x_test[:10])

4 frames
/usr/local/lib/python3.7/dist-packages/shap/explainers/_deep/__init__.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    122             were chosen as "top".
    123         """
--> 124         return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)

/usr/local/lib/python3.7/dist-packages/shap/explainers/_deep/deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    306                 # run attribution computation graph
    307                 feature_ind = model_output_ranks[j,i]
--> 308                 sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
    309 
    310                 # assign the attributions to the right part of the output arrays

/usr/local/lib/python3.7/dist-packages/shap/explainers/_deep/deep_tf.py in run(self, out, model_inputs, X)
    363 
    364                 return final_out
--> 365             return self.execute_with_overridden_gradients(anon)
    366 
    367     def custom_grad(self, op, *grads):

/usr/local/lib/python3.7/dist-packages/shap/explainers/_deep/deep_tf.py in execute_with_overridden_gradients(self, f)
    399         # define the computation graph for the attribution values using a custom gradient-like computation
    400         try:
--> 401             out = f()
    402         finally:
    403             # reinstate the backpropagatable check

/usr/local/lib/python3.7/dist-packages/shap/explainers/_deep/deep_tf.py in anon()
    356                     shape = list(self.model_inputs[i].shape)
    357                     shape[0] = -1
--> 358                     data = X[i].reshape(shape)
    359                     v = tf.constant(data, dtype=self.model_inputs[i].dtype)
    360                     inputs.append(v)

TypeError: 'NoneType' object cannot be interpreted as an integer
`

**Comment by loewenm** [comment]
Just found this, which might be the answer that we're looking for...

https://github.com/slundberg/shap/issues/1456#issuecomment-727025282

**Comment by loewenm** [comment]
Here's how you fix the errors discussed above, even when using Google's Colab.
_Tested as of 1-June-2021_

**1. Install SHAP**
The latest shap and tensorflow are compatible; however, there's a catch as discussed immediately below. Simply `!pip install shap` and then import shap and _Bob's your uncle_.

**2. Downgrade TensorFlow Functionality**
SHAP deepexplainer does not work properly with TensorFlow2.0. Consequently, you need to downgrade TF functionality to TF 1.x functionality.

Read how here: https://www.tensorflow.org/api_docs/python/tf/compat/v1/disable_v2_behavior

or simply include the following code before any models/graphs. I stick it right after I import all my libraries near the very top.

```
from tensorflow.compat.v1.keras.backend import get_session
tf.compat.v1.disable_v2_behavior()

```

**3. Specify Input Shape in Model**
Relatively simple, just ensure you have a separately specified input shape layer as opposed to specifying it in the first embedding/dense/lstm, etc. layer. I'm not sure if this step is required, but I was getting strange input shape errors until I separated this out.

import said layer via `from tensorflow.keras.layers import InputLayer`

model should now look like the following:
```
model = Sequential()
model.add(InputLayer(input_shape=(maxlen,))) # << this here
model.add(Embedding(max_features, 128))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))
```


**4. Ensure you initialize the Javascript in every cell where you're displaying these beautiful charts**

```
# init the JS visualization code
shap.initjs()
```

This should work as I've run it multiple times with no issues. I hope it helps. 

P.S.: If you have any experience adapting SHAP to multivariate, timeseries models, please look at my [discussion page](https://github.com/slundberg/shap/discussions/1997#discussion-3369910).

**Comment by mihailyanchev** [comment]
@slundberg Hi and thanks for your great effort! Is there a plan for this to get fixed for tf 2.x. This is also related to this [issue](https://github.com/slundberg/shap/issues/1456).
