### ISSUE TITLE
Not able to install using pip install shap

### ISSUE THREAD

**Issue by IamAVB** [shap/shap#156]
I am getting an error saying system needs Visual C++ 14.0 redistribution file. Even though I have later version installed. I installed v14.0 as it told. But still I am getting same error. Please let me know how I can install it. Can I install shap through conda?.

**Comment by slundberg** [comment]
This is similar to #96 where the problems all center around various ways windows compiling can break. I don't have a window's box so I can't give direct feedback. @fredtony had a good suggestion in #96 to just avoid compiling and so turn off the support for sklearn models and LightGBM interaction effects.

**Comment by slundberg** [comment]
As of v0.20.1 there are now x64 Window's wheels on PyPI for Python 3.6 and 3.7 :) Let me know if they don't work.
