### ISSUE TITLE
Issue with shap, slicer==0.0.3 and Databricks

### ISSUE THREAD

**Issue by alexandrateste** [shap/shap#1567]
Hello,
I have a process in which I programmatically spin up a Databricks Spark job, from an Airflow job.
The Airflow settings are as follows:
`databricks_operator_json = {

    'new_cluster': {

        'spark_version': '6.4.x-cpu-ml-scala2.11',
        'node_type_id': 'm4.large',
        'aws_attributes': {

            "availability": "ON_DEMAND",
            "ebs_volume_type": "GENERAL_PURPOSE_SSD",
            "ebs_volume_count": 1,
            "ebs_volume_size": 100,
            "instance_profile_arn": "<arn_info>"
        },

        'spark_env_vars': {
            'PYSPARK_PYTHON': '/databricks/python3/bin/python3',
        },
        'spark_conf': {"spark.hadoop.fs.s3a.credentialsType": "AssumeRole",
                       "spark.hadoop.fs.s3a.stsAssumeRole.arn":
                           "arn:aws:iam::{}".format(assume_role)},
        'num_workers': 1
    },
    "timeout_seconds": 3600,
    "libraries": [{
        "pypi": {
            "package": "sklearn_pandas>=2.0.1",
            "repo": "https://pypi.org/project"
        },
    },
        {
            "pypi": {
                "package": "sklearn==0.0",
                "repo": "https://pypi.org/project"
            },
        },
        {
            "pypi": {
                "package": "joblib",
                "repo": "https://pypi.org/project"
            },
        },
        {
            "pypi": {
                "package": "numpy>1.18.0",
                "repo": "https://pypi.org/project"
            },
        },
        {
            "pypi": {
                "package": "scikit-learn>=0.23",
                "repo": "https://pypi.org/project"
                # Changed because of n_features_in_
            },
        },
        {
            "pypi": {
                "package": "slicer",
                "repo": "https://pypi.org/project"
            },
        },
        {
            "pypi": {
                "package": "shap",
                "repo": "https://pypi.org/project"
            },
        },
    ],
    "spark_python_task": {
        "python_file": <file_path>,
        "parameters": [<list_of_variable>]
    }
}`

When I run this, I get the following error on the Databricks side:
`'Library installation failed for library due to user error for pypi {\n  package: "slicer==0.0.3"\n  repo: "https://pypi.org/project"\n}\n. Error messages:\njava.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, slicer==0.0.3, --index-url, https://pypi.org/project, --disable-pip-version-check) exited with code 1.   Could not find a version that satisfies the requirement slicer==0.0.3 (from versions: 0.0.5)\nNo matching distribution found for slicer==0.0.3\n for library:PythonPyPiPkgId(slicer,Some(0.0.3),Some(https://pypi.org/project),List())`

When I checked this morning, I noticed that slicer is now at version 0.0.5 and shap at version 0.37.0. Both were released yesterday (2020-11-04).
So, I tried the above again, but with `slicer==0.03` and `shap==0.36.0`, but got the same error. I also noticed [here](https://github.com/slundberg/shap/blob/master/setup.py#L116), that shap requires slicer==0.0.3, but that version doesn't seem to be found on pypi by Databricks.

So, could you please help me figure out what to change to allow for the shap library to get programmatically properly installed in Databricks clusters?

Note that this whole process was working just fine until this morning, i.e. right after the new versions of slicer and shap were released.

Thank you for your help.

**Comment by jonnor** [comment]
shap requires a specific version of slicer, specified in the requirements. So the best when installing shap is to only specific the `shap` version, and not that of `slicer`. This avoids accidentally creating a situation with unresolvable versions.

Can you try depending only on the latest `shap==0.41.0`, and see if that fixes it?
