### ISSUE TITLE
Issue with the sum of Shap values of each classes and summary_plot

### ISSUE THREAD

**Issue by DavidGomezRomero** [shap/shap#1574]
Hi, 

I am using DeepExplainer as explainer to obtain my shap_values : 

`X = X_train_scaled_model`
`explainer = shap.DeepExplainer(model, X)`
`shap_values = explainer.shap_values(X)`

Then I used summary_plot to observe the impact of each feature on my model. 

`shap.summary_plot(shap_values, class_names=Hours_lst, max_display=10,plot_size=(10,9),show=False)`

![Figure_2](https://user-images.githubusercontent.com/59099630/98568771-c388a480-22b1-11eb-8183-5d954aec1854.png)

I decided to sum all the Shap values of each classes in order to remove the legend (sure there is a better way) , but I did not find the same result as above (Feature 2 take a new value) : 

`shap.summary_plot(np.array(shap_values).sum(axis=0),plot_size=(10,8), plot_type="bar", max_display=10,show=False)`

![Figure_1](https://user-images.githubusercontent.com/59099630/98568769-c2f00e00-22b1-11eb-88bf-60bf629e16a6.png)

Does anyone have any idea what is happening here?

**Comment by annezhangxue** [comment]
Hi, I think it is because your X is 3D, (number of samples, number of features, number of time steps), the number of features calculated in shapely values are not real number of features, but (number of features * number of time steps). so you cannot merge the photo by summing up

**Comment by ky66** [comment]
This shap_values thing returned from DeepExplainer is not in the same format as the other shap_values which have base values and data. Makes drawing a beeswarm plot for DeepExplainer very confusing.
