### ISSUE TITLE
AttributeError: 'Explanation' object has no attribute 'base_value' (possible typo in code)

### ISSUE THREAD

**Issue by Jakobhenningjensen** [shap/shap#1576]
Having the following code

```python
from lightgbm import LGBMClassifier as LGBM
import shap

model = LGBM(objective="binary",is_unbalance=True) #Basemodel
model.fit(X_train,y_train)

explainer = shap.TreeExplainer(model)
shap_values = explainer(X_train)
shap.summary_plot(shap_values,X_train) #AttributeError: 'Explanation' object has no attribute 'base_value'
```

with the error being in 

```
 426     if str(type(shap_values)).endswith("Explanation'>"):
    427         shap_exp = shap_values
--> 428         base_value = shap_exp.base_value
    429         shap_values = shap_exp.values
    430         if features is None:
```

My object `shap_values` have the attribute `base_values` but it seems like the code looks for `base_value` (without an "s")

Is this intentional or should the code indeed be:

```python
if str(type(shap_values)).endswith("Explanation'>"):
         shap_exp = shap_values
         base_value = shap_exp.base_values #before: base_value = shap_exp.base_value
         shap_values = shap_exp.values
         if features is None:
```

If I change the source-code to that above, it seems to be working

**Comment by Jakobhenningjensen** [comment]
Closed since the typo was my mistake

**Comment by JonasGlow** [comment]
Seems to me that this typo is still in effect. I have the same error when trying to produce a summary plot with an explanation object. Is there already a pull request for this? Otherwise I would make one.
If it is an error on my side please let me know!
