### ISSUE TITLE
a python-3.9 wheel ?

### ISSUE THREAD

**Issue by stonebig** [shap/shap#1577]
there is "only" Python-3.6 3.7 3.8 wheels on pypi

**Comment by Bougeant** [comment]
At the moment, `shap` requires `numba` which is expected to be compatible with Python 3.9 in mid-December (https://github.com/numba/numba/issues/6345)

**Comment by Bougeant** [comment]
numba and llvmlite should now have support for Python 3.9

**Comment by SvenSchiffner** [comment]
@slundberg Can we do anything to help with a wheel release for python 3.9?

**Comment by jonnor** [comment]
This should now be fixed, thanks to the above PR. This issue can be closed. CC @slundberg
