### ISSUE TITLE
expected_values don't match with average predicted values

### ISSUE THREAD

**Issue by shiva-z** [shap/shap#1579]
Hey @slundberg 
I was trying to calculate the expected_value myself for an `XGBClassifier` using
`model.predict(np.array(data), output_margin=True).mean(0)`
and I noticed what I get is different from the expected value of the `TreeExplainer`
I added these print statements to the code where the expected value is being calculated when background data is given:
```
        elif data is not None:
            try:
                print("calculating the expected value")
                print(self.model.predict(bg_data))
                print(model.predict(np.array(bg_data), output_margin=True))
                self.expected_value = self.model.predict(self.data).mean(0)
```
and I noticed the predictions are different see below (compare first rows of the 2 matrices for example):
```
[[0.50148935 0.31990169 0.41877652]
 [0.4698704  0.39677595 0.44904187]
 [0.47815893 0.34442024 0.43754147]
 ...
 [0.3985514  0.29108709 0.41749447]
 [0.38635505 0.31985228 0.38447442]
 [0.43250207 0.31819766 0.41023449]]

[[0.6613597  0.08682984 0.49197805]
 [0.70940477 0.01240239 0.59388113]
 [0.68149745 0.03193641 0.5466868 ]
 ...
 [0.00638983 0.93218887 0.16855425]
 [0.0196622  0.9706851  0.12387896]
 [0.02899235 0.9706851  0.16125679]]
```
first matrix is the prediction of `self.model` which is a `TreeEnsemble` instance created using `model` and `model`
 is an `XGBClassifier` instance. I was wondering why their results are different. Thanks

**Comment by desertnaut** [comment]
Could you please try to post a reproducible example?
