### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by merciabcs** [shap/shap#158]
Hi, I was not able to install shap. First it was complaining about Visual Studion buildtools which I installed (latest version) and now I have this error:

Installing collected packages: shap
  Running setup.py install for shap ... error
    Complete output from command c:\programdata\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\simwxz\\AppData\\Local\\Temp\\pip-install-53kyuidh\\shap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\simwxz\AppData\Local\Temp\pip-record-0l8hjpv0\install-record.txt --single-version-externally-managed --compile:
    c:\programdata\anaconda3\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\shap
    copying shap\datasets.py -> build\lib.win-amd64-3.6\shap
    copying shap\plots.py -> build\lib.win-amd64-3.6\shap
    copying shap\__init__.py -> build\lib.win-amd64-3.6\shap
    creating build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\deep.py -> build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\gradient.py -> build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\kernel.py -> build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\mimic.py -> build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\pytree.py -> build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\sampling.py -> build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\tree.py -> build\lib.win-amd64-3.6\shap\explainers
    copying shap\explainers\__init__.py -> build\lib.win-amd64-3.6\shap\explainers
    running build_ext
    numpy.get_include() c:\programdata\anaconda3\lib\site-packages\numpy\core\include
    building 'shap._cext' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\shap
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\lib\site-packages\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include" /EHsc /Tpshap/_cext.cc /Fobuild\temp.win-amd64-3.6\Release\shap/_cext.obj
    _cext.cc
    c:\programdata\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by slundberg** [comment]
Seems like an issue with PyConfig. If you don't need the C++ part of the package you can change the build like in #96. Sorry I am not familiar with Python builds on windows.

**Comment by slundberg** [comment]
As of v0.20.1 there are now x64 Window's wheels on PyPI for Python 3.6 and 3.7 :) Let me know if they don't work.
