### ISSUE TITLE
Using ragged tensors

### ISSUE THREAD

**Issue by bhavaygg** [shap/shap#1581]
hello,

i am trying to get features importance and since my features are of variable length i used ragged tensors. 
```
explainer = shap.DeepExplainer(keras_model,ragged_x_test)
shap_values = explainer.shap_values(ragged_x_test[:5])
```

using `deepexplainer` i get the following error 
```
/usr/local/lib/python3.6/dist-packages/shap/explainers/_deep/deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    286             phis = []
    287             for k in range(len(X)):
--> 288                 phis.append(np.zeros(X[k].shape))
    289             for j in range(X[0].shape[0]):
    290                 if (hasattr(self.data, '__call__')):

TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by duarteharris** [comment]
Hello @Chokerino.

From what I could gather from https://github.com/slundberg/shap/issues/885 and https://github.com/slundberg/shap/issues/1198 , DeepExplainer has not supported TF/Keras >= 2.0 for a year, and I suspect that's what's happening, but it's assuming you're using TF or tf.keras >= 2.0.

**Comment by bhavaygg** [comment]
@duarteharris yea the version is above 2.0. Is there any other way to get feature importance for my case?

**Comment by duarteharris** [comment]
I might be wrong about this, but I believe that it will depend on the algorithm that you're using, and what are you using it for. 

If your algorithm's requires DeepExplainer, then no; you'll have to wait for DeepExplainer to be integrated with TF and/or tf.keras >= 2.0.  I'm currently in this situation.

If it doesn't, GradientExplainer, KernelExplainer, or some other might, and I mean _might_, work.
