### ISSUE TITLE
 local variable 'values' referenced before assignment

### ISSUE THREAD

**Issue by Liufeiran123** [shap/shap#1586]
call shap.plots.beeswarm(shap_values, max_display=20)
show below error  
 File "/usr/local/lib/python3.7/site-packages/shap/plots/_beeswarm.py", line 57, in beeswarm
    order = convert_ordering(order, values)
UnboundLocalError: local variable 'values' referenced before assignment

**Comment by chrislill** [comment]
@xingbow explains this issue in #1460. The fix is to send an explanation object to the beeswarm plot, rather than a numpy array of shap values.

**Comment by Liufeiran123** [comment]
thank you very much

**Comment by thatlittleboy** [comment]
Closing as duplicate of #1460
