### ISSUE TITLE
Explaining YOLOv3 predictions

### ISSUE THREAD

**Issue by shebna06** [shap/shap#1589]
Hi! Thanks for crafting the shap library and continuously improving it. 

I have a YOLOv3 model and I want to explain its predictions using DeepExplainer. However, YOLOv3 model predictions shape is a list of numpy arrays. When I plug it in the shap DeepExplainer, I am getting this error:

AssertionError: The model output must be a vector or a single value!

I understand it must have something to do with the shape of the model's prediction. I'm wondering if SHAP can handle YOLO for now or are there plans to include it in the future? Thanks a lot.

**Comment by MaxwellHogan** [comment]
@shebna06 how did this go for you?
