### ISSUE TITLE
xgboost not installed in binder env

### ISSUE THREAD

**Issue by raybellwaves** [shap/shap#1598]
Firstly, thanks for this awesome library.

I was pleasantly surprised to see a binder button at the top of the repo for me to quickly try and learn.

I tried the plots/waterfall.ipynb notebook (https://shap.readthedocs.io/en/latest/example_notebooks/plots/waterfall.html)

but it seems xgboost isn't installed in the environment:

![image](https://user-images.githubusercontent.com/17162724/99582509-3380e400-29b0-11eb-8f78-ccec70bb31c2.png)

**Comment by raybellwaves** [comment]
I took a deeper look here https://github.com/raybellwaves/shap-binder

It seems the notebook may also be out of date.

```
explainer = shap.Explainer(model, X)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/shap/explainers/_linear.py in supports_model_with_masker(model, masker)
    268         try:
--> 269             Linear._parse_model(model)
    270         except e:

/srv/conda/envs/notebook/lib/python3.7/site-packages/shap/explainers/_linear.py in _parse_model(model)
    255         else:
--> 256             raise Exception("An unknown model type was passed: " + str(type(model)))
    257 

Exception: An unknown model type was passed: <class 'xgboost.sklearn.XGBClassifier'>

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-1-ae84e18a2a15> in <module>
      7 
      8 # compute SHAP values
----> 9 explainer = shap.Explainer(model, X)
     10 shap_values = explainer(X)

/srv/conda/envs/notebook/lib/python3.7/site-packages/shap/explainers/_explainer.py in __init__(self, model, masker, link, algorithm, output_names, feature_names, **kwargs)
     97 
     98                 # use implementation-aware methods if possible
---> 99                 if explainers.Linear.supports_model_with_masker(model, self.masker):
    100                     algorithm = "linear"
    101                 elif explainers.Tree.supports_model_with_masker(model, self.masker): # TODO: check for Partition?

/srv/conda/envs/notebook/lib/python3.7/site-packages/shap/explainers/_linear.py in supports_model_with_masker(model, masker)
    268         try:
    269             Linear._parse_model(model)
--> 270         except e:
    271             return False
    272         return True

NameError: name 'e' is not defined
```

There are a few issues related to notebooks in here: https://github.com/slundberg/shap/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+notebook (https://github.com/slundberg/shap/issues/1592; https://github.com/slundberg/shap/issues/1544; https://github.com/slundberg/shap/issues/1551; https://github.com/slundberg/shap/issues/1440 (I think); https://github.com/slundberg/shap/issues/1070; https://github.com/slundberg/shap/issues/1309; https://github.com/slundberg/shap/issues/1297; https://github.com/slundberg/shap/issues/181).

**Comment by raybellwaves** [comment]
My two cents: the notebooks are moved out of the package and into a separate repo e.g. slunderberg/shap-examples; shap-[dev/contrib]/shap-examples where it's easier to maintain the notebooks with additional packages.

**Comment by fomightez** [comment]
My fork , branch `mybinder_support`, currently here makes this notebook work in launches from MyBinder-served sessions. 
Go to [my fork here](https://github.com/fomightez/shap/tree/mybinder_support) and click the '`launch binder`' badge there.
(Or simply [click here](https://mybinder.org/v2/gh/fomightez/shap/27b17a15b72c668c248b8cd968caf5d41077457f?urlpath=%2Fdoc%2Ftree%2Fnotebooks%2Fapi_examples%2Fplots%2Fwaterfall.ipynb) to launch.)

Then you should be able to run the entire notebook.
