### ISSUE TITLE
Distribution in summary plot

### ISSUE THREAD

**Issue by kodonnell** [shap/shap#16]
Interested in me submitting a PR for this? We've used it internally to make it more interpretable. If the lowest kde subplot is for variable X, then dark blue means 'bottom 20% of X values' up to red which is 'top 20% of X values'. We find this more interpretable as e.g. in this case we can quickly see that low values of X tend to decrease SHAP values, while high values increase it, etc. Otherwise it was hard to explain to clients, especially for unbalanced kdes like the middle one (which might be 'the wrong way round').

![image](https://user-images.githubusercontent.com/8204904/35066104-5ff36e2e-fc34-11e7-8d88-e12785ea177e.png)

**Comment by slundberg** [comment]
Hey, that is a great idea! I like the way it connects the feature values to their SHAP values while still only using a single dimension.

A PR would be much appreciated. If you have any questions just let me know.

**Comment by kodonnell** [comment]
Awesome - I will submit one hopefully over the weekend.
