### ISSUE TITLE
TypeError: object of type 'NoneType' has no len() while using shap on keras

### ISSUE THREAD

**Issue by AmirHoseinSafari** [shap/shap#1603]
Hi,

I am using Keras and my model is LRCN (a combination of CNN + LSTM). 
You can see my code here:
[https://github.com/AmirHoseinSafari/LRCN-drug-resistance/blob/master/models/Bayesian_optimizer.py](https://github.com/AmirHoseinSafari/LRCN-drug-resistance/blob/master/models/Bayesian_optimizer.py
)
I am trying to run it this way:

```
    X_train2 = tf.cast(X_train, tf.float32)
    X_test2 = tf.cast(X_test, tf.float32)
    X_val2 = tf.cast(X_val, tf.float32)
    y_train2 = tf.cast(y_train, tf.float32)
    y_test2 = tf.cast(y_test, tf.float32)
    y_val2 = tf.cast(y_val, tf.float32)
```

    model.compile(
        loss=masked_loss_function,
        optimizer='Adam',
        metrics=[masked_accuracy]
    )
    
    history = model.fit(
        X_train2,
        y_train2,
        epochs=epochs,
        batch_size=128,
        verbose=2,
        validation_data=(X_val2, y_val2)
    )

    shap.initjs()

    explainer = shap.DeepExplainer(model, X_train2[:100])
    shap_values = explainer.shap_values(X_test2[:10])
    shap.summary_plot(shap_values, X_test2, plot_type='bar')`

My model is something like: 
```
model = Sequential()
model.add(Dropout(dropout2_rate))
model.add(Conv1D(filters=filterCNN1, kernel_size=kernelCNN1, activation='relu', padding='same'))
model.add(MaxPooling1D(pool_size=poolCNN1, padding='same'))
model.add(LSTM(LSTM1, return_sequences=False, recurrent_dropout=0.3))
model.add(Dropout(dropout2_rate))
model.add(Dense(dense_1_neurons))
model.add(Dropout(dropout2_rate))
model.add(Dense(12, activation='sigmoid'))
```

I am getting this error and I couldn't find any way to resolve it. Could you please help me with this?

Here is the error:

> keras is no longer supported, please use tf.keras instead.
> Traceback (most recent call last):
>   File "/Users/amir/PycharmProjects/Lab/LSTM-DR/LSTM-drug-resistance/pipe_line_gene.py", line 31, in <module>
>     train()
>   File "/Users/amir/PycharmProjects/Lab/LSTM-DR/LSTM-drug-resistance/pipe_line_gene.py", line 14, in train
>     model_gene_based.run_bayesian(df_train, labels)
>   File "/Users/amir/PycharmProjects/Lab/LSTM-DR/LSTM-drug-resistance/models/model_gene_based.py", line 578, in run_bayesian
>     Bayesian_optimizer.BO(X_train, X_test, X_val, y_train, y_test, y_val, limited, portion)
>   File "/Users/amir/PycharmProjects/Lab/LSTM-DR/LSTM-drug-resistance/models/Bayesian_optimizer.py", line 343, in BO
> <IPython.core.display.HTML object>
>     fit_with_partial(dropout2_rate=0.2, dense_1_neurons_x128=1, dense_2_neurons_x128=1, dense_3_neurons_x128=1,
>   File "/Users/amir/PycharmProjects/Lab/LSTM-DR/LSTM-drug-resistance/models/Bayesian_optimizer.py", line 192, in fit_with
>     return run_one_fold(model)
>   File "/Users/amir/PycharmProjects/Lab/LSTM-DR/LSTM-drug-resistance/models/Bayesian_optimizer.py", line 250, in run_one_fold
>     explainer = shap.DeepExplainer(model, X_train2[:100])
>   File "/Users/amir/venv/p3/lib/python3.8/site-packages/shap/explainers/_deep/__init__.py", line 84, in __init__
>     self.explainer = TFDeep(model, data, session, learning_phase_flags)
>   File "/Users/amir/venv/p3/lib/python3.8/site-packages/shap/explainers/_deep/deep_tf.py", line 97, in __init__
>     self.model_output = _get_model_output(model)
>   File "/Users/amir/venv/p3/lib/python3.8/site-packages/shap/explainers/tf_utils.py", line 83, in _get_model_output
>     if len(model.outputs) > 1:
> TypeError: object of type 'NoneType' has no len()

**Comment by duarteharris** [comment]
Hello @AmirHoseinSafari.

Full disclosure: I'm not working in the development of this library, so take what I say with a grain of salt.

I've been following this for a little while now, and, assuming you're using TF >= 2.0, as far as I can tell (see: https://github.com/slundberg/shap/issues/885, https://github.com/slundberg/shap/issues/1198, https://github.com/slundberg/shap/issues/1581),  DeepExplainer has not supported TF/Keras >= 2.0 for a year.

In the meantime I found this: https://stackoverflow.com/questions/47940040/how-to-set-input-shape-of-a-trained-model-in-keras , and it might "fix" it, but I haven't tried yet. If you do, please let me know how it went.

I hope this clarifies. 
Best regards,

**Comment by gipster** [comment]
> Hello @AmirHoseinSafari.
> 
> Full disclosure: I'm not working in the development of this library, so take what I say with a grain of salt.
> 
> I've been following this for a little while now, and, assuming you're using TF >= 2.0, as far as I can tell (see: #885, #1198, #1581), DeepExplainer has not supported TF/Keras >= 2.0 for a year.
> 
> In the meantime I found this: https://stackoverflow.com/questions/47940040/how-to-set-input-shape-of-a-trained-model-in-keras , and it might "fix" it, but I haven't tried yet. If you do, please let me know how it went.
> 
> I hope this clarifies. Best regards,

Hi  I was passing a tf.keras subclassed  model to the explainer and getting the same error. I tried the solution from stackoverflow you suggested and in my case is working :). Thanks a lot !
