### ISSUE TITLE
multivalue shap interaction values will come? > 2 players

### ISSUE THREAD

**Issue by Liufeiran123** [shap/shap#1605]
multivalue shap interaction values will come? > 2 players. on scheduler ?

**Comment by Liufeiran123** [comment]
multi feature interaction values

**Comment by detrin** [comment]
@wanghai345 I don't understand what you are referring to, could you clarify please? Are you asking for support of higher interactions in shap?

@thatlittleboy CFC due to inactivity.

**Comment by connortann** [comment]
Closing for now due to inactivity and lack of detail. Please feel free to open a new issue with more details if you have a feature request.
