### ISSUE TITLE
NameError: name 'e' is not defined` in shap/explainers/_linear.py in supports_model_with_masker(model, masker) 

### ISSUE THREAD

**Issue by juanramonua** [shap/shap#1607]
I try run https://github.com/slundberg/shap/blob/master/notebooks/plots/scatter.ipynb in Colab and locally (Python 3.8) with shap 0.37 but an error is showed:

The first cell:

`import xgboost
import shap

# train XGBoost model
X,y = shap.datasets.adult()
model = xgboost.XGBClassifier().fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X[:1000])`

show this exception:

`Exception: An unknown model type was passed: <class 'xgboost.sklearn.XGBClassifier'>

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/shap/explainers/_linear.py in supports_model_with_masker(model, masker)
    268         try:
    269             Linear._parse_model(model)
--> 270         except e:
    271             return False
    272         return True

NameError: name 'e' is not defined`

**Comment by juanramonua** [comment]
There is a similar issue in the list

**Comment by bdi2357** [comment]
I had similar issue

**Comment by haowu6027** [comment]
I got the same error when I run through this tutorial, 
https://shap.readthedocs.io/en/latest/example_notebooks/general/Explainable%20AI%20with%20Shapley%20Values.html
the class Linear cannot parse the logistic Regression model from sklearn. 
Error from this line 
explainer = shap.Explainer(model.predict, background)

Shap version 37 has this problem but version 36 don't 
And in the tutorial, the code uses the 'RM' in Boston data but uses 'AGE' in the explanation.

**Comment by Rahul12344** [comment]
Hi, I have this issue - how were you able to resolve this?

**Comment by ZijieHuang** [comment]
Hi all, I got the same issue. But when I intall shap with 0.39.0 version, problem solved. Hope this can help ;)
