### ISSUE TITLE
Target encoding and SHAP values

### ISSUE THREAD

**Issue by guidiandrea** [shap/shap#1608]
Hello,

First of all thanks for this awesome package.
I'd like to ask @slundberg a question: I've read several issues on this github about how to interpret SHAP values with one-hot encoded variables by leveraging SHAP's additivity. 
What if I have a high cardinality feature and I want to use target encoding? 
Thank you.

**Comment by jvschoen** [comment]
I am also curious about how to handle target-encoded categorical variables. It seems like this encoding technique may introduce some black-box properties and SHAP may not handle it well.

**Comment by zahs123** [comment]
Also curious here

**Comment by nilslacroix** [comment]
+1
