### ISSUE TITLE
shap==0.19.0. AttributeError: 'TreeExplainer' object has no attribute 'expected_value'

### ISSUE THREAD

**Issue by qingfeng-ui** [shap/shap#1611]
# load JS visualization code to notebook
shap.initjs()

# train XGBoost model
X,y = shap.datasets.boston()
model = xgboost.train({"learning_rate": 0.01}, xgboost.DMatrix(X, label=y), 100)

# explain the model's predictions using SHAP
# (same syntax works for LightGBM, CatBoost, scikit-learn and spark models)
explainer = shap.TreeExplainer(model)
print('1')
shap_values = explainer.shap_values(X)

# visualize the first prediction's explanation (use matplotlib=True to avoid Javascript)
shap.force_plot(explainer.expected_value, shap_values[0,:], X.iloc[0,:])

error:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\shap\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-eabbf934e662>", line 1, in <module>
    shap.force_plot(explainer.expected_value, shap_values[0,:], X.iloc[0,:])
AttributeError: 'TreeExplainer' object has no attribute 'expected_value'
shap.force_plot(explainer.expected_value, shap_values, X)
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\shap\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-17e8ee68db6f>", line 1, in <module>
    shap.force_plot(explainer.expected_value, shap_values, X)
AttributeError: 'TreeExplainer' object has no attribute 'expected_value'

**Comment by thatlittleboy** [comment]
Closing as stale, the issue shouldn't be occuring for recent versions of shap
