### ISSUE TITLE
How to single out one point in bee swarm plot ?

### ISSUE THREAD

**Issue by lcrmorin** [shap/shap#1616]
I'd like to single out one point in a bee swarm to replace an instance into the context of other intances. My idea would be somethin like this : 

sample_ind = 15
shap.plots.beeswarm(shap_values, max_display=5)
shap.plots.beeswarm(shap_values[sample_ind], max_display=5, color = 'black')

That would produce something like this :

![beeswarm_instance](https://user-images.githubusercontent.com/4086709/100766342-d564ef80-33f8-11eb-84a0-38be1a4e158b.png)

Any idea on how to perform that ? 
Any remark on why it would be / not be a good idea to do so ?

**Comment by HyukdongKim** [comment]
try this

# import libraries
import xgboost
import shap

# train XGBoost model
X,y = shap.datasets.adult()
model = xgboost.XGBClassifier().fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

import matplotlib.pyplot as pl
shap.plots.beeswarm(shap_values, show=False)
shap.plots.beeswarm(shap_values[-1:], show=False, color="black")
pl.show()
