### ISSUE TITLE
Inconsistency of threshold condition in TreeShap

### ISSUE THREAD

**Issue by RAMitchell** [shap/shap#1617]
TreeShap uses <= to evaluate thresholds, this is correct for models imported from sklearn.RandomForest but not xgboost. The prediction result is then incorrect when the feature value is the same as the split condition.

Reproducing script:

```python
import numpy as np
import xgboost as xgb
import shap

n = 2
m = 1
rng = np.random.RandomState(6)
X = rng.random_sample((n, m))
y = rng.random_sample(n)

dmat = xgb.DMatrix(X, y)
bst = xgb.train({"tree_method":"hist","lambda":0}, dmat, 1)

for t in bst.get_dump():
    print(t)

print(X)
ex = shap.TreeExplainer(bst, X)
xgb_pred = bst.predict(dmat)
print(xgb_pred)
shap_pred = ex.model.predict(X)
print(shap_pred)
```
Output:
```
0:[f0<0.892860174] yes=1,no=2,missing=2
	1:leaf=-0.137491018
	2:leaf=0.0963687375

[[0.89286015]
 [0.33197981]]
[0.59636873 0.36250898]
[0.36250898 0.36250898]
```

**Comment by slundberg** [comment]
This is supposed to be handled right now by nudging at:
https://github.com/slundberg/shap/blob/f88d4f28bc7a7a9e863d26bbf5362b1b83255c60/shap/explainers/_tree.py#L1023-L1024

Perhaps there has been some precision change?

**Comment by RAMitchell** [comment]
Didn't see that line. Isn't this the wrong direction?

If I have an xgboost split
`x < 5.0`
in xgb the instance `x = 5.0` goes right
in shap the unadjusted threshold is
`x <= 5.0`
so the instance `x = 5.0` goes left
If we adjust the shap threshold to
`x <= 4.99...`
The instance goes right like it would in xgb.
