### ISSUE TITLE
How to interpret the shap aggregated Plot?

### ISSUE THREAD

**Issue by andymancodes** [shap/shap#162]
Hi,

In the SHAP plot of my regression problem, I am getting a plot which has multiple options on both the x and y-axes. The visualizations are great, but what do they mean?

Can I localize, that these particular outputs are higher because of the impact of a particular feature?

Is there any documentation for this?

**Comment by slundberg** [comment]
I have been working on adding more docs in the python code, but there is not a section that describes what you are asking. Could you post an example of what you are looking at? I think that would help clarity things.

**Comment by andymancodes** [comment]
@slundberg thanks, consider this plot:

![gggg](https://user-images.githubusercontent.com/37308037/42985582-ba88283c-8c0f-11e8-81ab-529d09a8aeb1.PNG)

This was a regression problem with some features: At the top dropdown, I get all the features e.g. DayOftheWeek + order sample by similarity/output value options and on the left dropdown bar, I get effects of different features like Month effect.

The plot has red and blue areas.

What do they mean? e.g. in the picture, does it mean that when day of the week is between 2 and 5, month effect is higher and it puts the regression output higher?

How do I interpret:

1. Feature vs Feature Plots (e.g. Month effects vs DayoftheWeek as in the picture)
2. Feature effects on the output Values (e.g. Month effects vs sample order by value/similarity/original ordering)

Thanks for the help. These clarifications will really help me a great deal!!

**Comment by slundberg** [comment]
Sorry to late reply. For the first question, yes it does mean that when day of the week is between 3 and 4 (inclusive) the month effect is higher and it puts the regression output higher.

1. If you see meaningful patterns they are likely either interaction effects in the model or some statistical dependence between the features. If two features are tightly correlated ordering by one will be just like ordering by the other, so you will see effects. If there are interaction effects in the model then you can see pattens even when the features are independent. I would check the correlation of the features to get an idea of which case you are dealing with.
2. You are looking at how a single feature's effect is distributed across the dataset ordered in ways that might highlight patterns such as subgroups. So something you might see is that a feature is only important for a subgroup of the samples.
