### ISSUE TITLE
Several bug fix to call SHAP from EconML

### ISSUE THREAD

**Issue by heimengqi** [shap/shap#1621]
Hi, I created a PR solving issues I found when implemented SHAP functionalities into EconML #1620 , please take a look and we reply on those changes to make it work calling from EconML. 

Also I have another issue didn't solve through this PR, when I have a Explanation object and I reset the `feature_names` as a list, it can't be correctly passed through when call slicing, the way to make it work correctly is to reset as an alias of list `Alias(list of new feature_names, dimension)`, could you please handle that internally?

```
est=LinearRegression()
est.fit(x,y)
explainer=shap.Explainer(est,x[:10],feature_names=["a","b","c","d"])
shap_values=explainer(x[:10])
# change feature names
shap_values.feature_names=["a","b","c"]
# new feature name won't pass through when slicing
print(shap_values.feature_names)
print(shap_values[1].feature_names)
```

**Comment by slundberg** [comment]
Thanks @heimengqi ! I also ran into the same slicing issue and thought Harsha and Sam fixed it on the InterpretML/slicer side, but I'll check into it and see if it is a different issue or something that is not yet pushed.

**Comment by heimengqi** [comment]
Thanks @slundberg ! I currently have a solution by reset` .feature_names` as of Alias instead of a list, so it's not a blocker from our side. But please keep me posted if you could finally handle that internally, then I will update my code.

**Comment by slundberg** [comment]
Harsha just pushed support for this to slicer: https://github.com/interpretml/slicer/commit/08cc7d23eeb55fb1b0e3faa1c30c46e26d9ee157

So once it is tested with SHAP we can start getting it into tagged releases
