### ISSUE TITLE
Scatter plots fail with shap_values.display_data = Pandas dataframe

### ISSUE THREAD

**Issue by juanramonua** [shap/shap#1625]
First of all we would like to thank the team of developers for their efforts. It's a great library.

This new version of SHAP 0.37 that will generate an object to store shap_values works with list type data, NumPy and Pandas but there are times when these types are changed to generate errors. This is an example and I would like you to review the code to be compatible with these types.

Versión SHAP 0.37 (clone github 6 dic). The stable 0.37 has some other issues.

```python
import xgboost
import shap

X,y = shap.datasets.adult()
model = xgboost.XGBClassifier().fit(X, y)

explainer = shap.Explainer(model)
shap_values = explainer(X[:1000])

X_display,y = shap.datasets.adult(display=True)
shap_values.display_data = X_display.values   # NumPy

shap.plots.scatter(shap_values[:, "Age"], color=shap_values[:,"Workclass"])
```

This code work well but if we use a Pandas dataframe variable in display_data

```python
shap_values.display_data = X_display   # Pandas dataframe

shap.plots.scatter(shap_values[:, "Age"], color=shap_values[:,"Workclass"])
```

```
/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py in __getattr__(self, name)
   5137             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5138                 return self[name]
-> 5139             return object.__getattribute__(self, name)
   5140 
   5141     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'reshape'
```

**Comment by danieleongari** [comment]
Problem still present with `shap 0.42` and `pandas 2.0.2`.

I had the same problem:
```
[c:\ProgramData\Miniconda3\envs\adex310\lib\site-packages\shap\plots\_scatter.py](file:///C:/ProgramData/Miniconda3/envs/adex310/lib/site-packages/shap/plots/_scatter.py) in ?(shap_values, color, hist, axis_color, cmap, dot_size, x_jitter, alpha, title, xmin, xmax, ymin, ymax, overlay, ax, ylabel, show)
    121     # this unpacks the explanation object for the code that was written earlier
    122     feature_names = [shap_values.feature_names]
    123     ind = 0
    124     shap_values_arr = shap_values.values.reshape(-1, 1)
--> 125     features = shap_values.data.reshape(-1, 1)
    126     if shap_values.display_data is None:
    127         display_features = features
    128     else:

[c:\ProgramData\Miniconda3\envs\adex310\lib\site-packages\pandas\core\generic.py](file:///C:/ProgramData/Miniconda3/envs/adex310/lib/site-packages/pandas/core/generic.py) in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'reshape'
```
The problem is a bit different from the previous post:  `.display_data` is not the main issue.
The root problem is the DataFrame `shap_values.data` missing `.to_numpy()` before  `.reshape(-1,1)`:
indeed, when using the `KernelExplainer` the `Explanation.data` is a panda DataFrame and not a numpy array as the code believes. Is there a discrepancy in the genaration of the `Explanation` for `KernelExplainer`?

**Comment by danieleongari** [comment]
To add extra info: the problem raises with the `KernelExplainer`

**Comment by danieleongari** [comment]
Indeed the patch,
```
shap_values_mod = copy(shap_values) 
shap_values_mod.data = shap_values_mod.data.to_numpy()
shap.plots.scatter(shap_values_mod)
```
works well!

Maybe it is unusual to get a DataFrame, and this is due to the fact that I used the following common circumvention to input a Pipeline https://datascience.stackexchange.com/questions/52476/how-to-use-shap-kernal-explainer-with-pipeline-models
