### ISSUE TITLE
Different summary plots for same dataset when use tree SHAP and Kernel SHAP

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#163]
Hi,

When using Kernel SHAP for NHANESI dataset it shows that when when are we getting older, SHAP value is getting decreased. But for Tree SHAP shows that when when are we getting older, SHAP value is getting increased. This is only one example. There are many more mismatches. So what should we believe?

**Comment by slundberg** [comment]
Would you mind sharing how you ran Kernel SHAP? There are a variety of
parameters that effect it.

**Comment by DiliSR** [comment]
```
knn = sklearn.neighbors.KNeighborsClassifier()
knn.fit(X_train, y_train)
```
```
med = X_train.median().values.reshape((1,X_train.shape[1]))
explainer = shap.KernelExplainer(knn.predict_proba,med)
shap_values= explainer.shap_values(X_train, nsamples=1000)
```

**Comment by slundberg** [comment]
This seems like you are explaining very different models, so the difference could be that the KNeighborsClassifier is doing something very different than the tree model you used.
