### ISSUE TITLE
[URGENT] pip install fails on Ubuntu. No files/directories in /tmp/pip-build-JsrgB4/shap/pip-egg-info (from PKG-INFO)

### ISSUE THREAD

**Issue by ms8909** [shap/shap#1633]
<img width="763" alt="Screenshot 2020-12-09 at 1 10 20 AM" src="https://user-images.githubusercontent.com/27916695/101536053-5012a980-39bb-11eb-8120-9e7d41356481.png">

No files/directories in /tmp/pip-build-JsrgB4/shap/pip-egg-info (from PKG-INFO)

**Comment by ms8909** [comment]
@slundberg

**Comment by ms8909** [comment]
I am using python 3.6.9

**Comment by mathPi** [comment]
Can you add the verbose flag "-v" to your pip install command ?

**Comment by mathPi** [comment]
You should see an error : Python version >= 3.7 required.
This is related to https://github.com/slundberg/shap/issues/1628.

A workaround is to install numpy before installing shap.

**Comment by xGolden** [comment]
I'm seeing the same issue. Installing via requirements.txt with a frozen numpy version does not resolve.
python 3.6.8
Different combinations of shap between 0.24.0 and 0.37.0 and numpy between 1.16.3 and 1.19.4

**Comment by axsaucedo** [comment]
We're also facing this issue, it's currently our release process
