### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by hanewinckel** [shap/shap#1637]
I am not quite sure how to address this as this error appears on readthedocs. The github link does not work, and I do not see the the notebook in the current repo. So perhaps the entire document is redacted (and should be removed from readthedocs).

This minor error is on [linear tree explainer](https://shap.readthedocs.io/en/latest/example_notebooks/tree_explainer/Fitting%20a%20Linear%20Simulation%20with%20XGBoost.html)

The line:
 `shap.dependence_plot((8,1), shap_interaction_values, X_test) `
and a similar line for the depth3 plot returns an error. After some testing it appears the code should now be:
`shap.dependence_plot([8,1], shap_interaction_values, X_test,interaction_index=1) `
(i.e. passing an index as the ind argument and including an interaction index)

Elsewhere in the notebook, it appears the interaction_index has to be explicitly stated for code output to match plots.

**Comment by lrjball** [comment]
So this notebook can be found here: https://www.github.com/slundberg/shap/tree/master/notebooks%2Ftree_explainer%2FFitting%20a%20Linear%20Simulation%20with%20XGBoost.ipynb

If you update the notebook then it will be reflected in the auto-generated docs. The view in github button in the docs is added by read the docs and points to a file which is generated automatically, which it then fails to find in the repo. This button does need removing but I think there is a separate issue open for that.
