### ISSUE TITLE
"Compute importance scores" DeepExplainer Example Notebook requires DeepLIFT < 0.6.13

### ISSUE THREAD

**Issue by InterferencePattern** [shap/shap#1642]
It looks like the first DeepExplainer example is no longer compatible with the DeepLIFT library, from which it tries to pull a now-removed function called traverse_edges.

**Comment by jvmead** [comment]
this message:
```
from deeplift.dinuc_shuffle import dinuc_shuffle, traverse_edges, shuffle_edges, prepare_edges
ImportError: cannot import name 'traverse_edges'
```
can be circumvented by backdating to ```deeplift==0.6.10.0```

and the following:
```
import shap.explainers.deep.deep_tf
ModuleNotFoundError: No module named 'shap.explainers.deep'
```
can be fixed by backdating to ```shap==0.35.0```
