### ISSUE TITLE
Parallel Processing in KernelExplainer

### ISSUE THREAD

**Issue by miaekim** [shap/shap#166]
Hello slundberg!

[I can see that KernelExplainer iterates over samples(given '# samples x # features')  to get shap_value.](https://github.com/slundberg/shap/blob/master/shap/explainers/kernel.py#L199)

I think it is possible to parallel this part for better computation. What do you think?

+
I use 18k features for NN, and it takes 3 min to run `shap.KernelExplainer(...)`. So shap performance is still good but there is a room for improvement!

**Comment by JoshuaGhost** [comment]
Hi miaekim,

just some intuitive thoughts on that. They might be wrong and biased, please let me know if you have any comments.

Each time when `KernelExplaination.explain` is called (e.g. [here](https://github.com/slundberg/shap/blob/master/shap/explainers/kernel.py#L203)), there are around `nsamples` samples generated for each single instance (see from [this line](https://github.com/slundberg/shap/blob/master/shap/explainers/kernel.py#L261) on). Therefore parallelizing the instances processing might barely improve the performance. A better way instead is, IMO, designing a more generalizable feature attribution function to map your 'real' features into a interpretable feature space. Which can modify the count of interpretable features (i.e. the `M`) to as low as you want it be.

**Comment by slundberg** [comment]
@JoshuaGhost's suggestion is the best way to go about this. Since `nsamples` are passed to your evaluation function as a batch I think the best place to parallelize is inside the model evaluation function, not the KernelExplainer itself (and most NN packages already do that). That being said we are also working on NN specific approximation methods like DeepExplainer that can handle 18k inputs.

**Comment by miaekim** [comment]
Thank you @JoshuaGhost and @slundberg !!

**Comment by arilwan** [comment]
@slundberg 

Do you have any update on the "NN specific approximation.." you mentioned in your reply above? Looking for a way to speed up shap computation for a `shap.KernelExplainer(...)` taking ages...
