### ISSUE TITLE
Perhaps a misuse of numpy.sum by sum in KernelExplainer.varying_groups?

### ISSUE THREAD

**Issue by JoshuaGhost** [shap/shap#167]
Hi slundberg,

have recently inspected the code of **KernelExplainer** in file **shap/shap/explainers/kernel.py**. But i've felt little bit confused by the **varying_groups** function defined in the **KernelExplainer**. 

in both line **387** and **388** of the **kernel.py**
```
387: num_matches = sum(np.abs(x[0, inds] - self.data.data[:, inds]) < 1e-7, 0)
388: varying[i] = sum(num_matches != len(inds) * self.data.data.shape[0])
```
Maybe i've got it wrong but i think the **num_matches** after **387th** line is an _int_. That make barely sense for the **388th** line, where only a boolean sigleton to be _sum_ ed. So i assume that you are going to use _np.sum_ for the both lines, who has the axis as its second parameter and can be perhaps more resonable.

**Comment by slundberg** [comment]
Thanks! That was left over from a previous change. The sum on line 388 is totally unneeded now. I pushed an update that should make this much clearer now (though it does not change the ultimate behavior)
