### ISSUE TITLE
Variable names do not come up in the plot

### ISSUE THREAD

**Issue by vatsaldin** [shap/shap#1676]
![image](https://user-images.githubusercontent.com/1464312/102749660-6987fe00-438a-11eb-9f67-7dee6054bf90.png)

**Comment by tjiagoM** [comment]
Hi, the function `summary_plot` has a parameter called `feature_names` for that. You can see it in the docs: https://shap.readthedocs.io/en/stable/generated/shap.summary_plot.html

I'm guessing you forgot some line in your code and `X_test` is not a pandas DataFrame. Or at least a pandas DataFrame without names on the columns. Hope this helps.
