### ISSUE TITLE
TreeExplainer Expected_value in binary classification Xgboost

### ISSUE THREAD

**Issue by trikiamine23** [shap/shap#1685]
Can expected_value be different from the mean predict_proba ?

**Comment by dan11mcguire** [comment]
Yes, the expected_value is calculated in the margin space, i.e. before the inverse link function is applied.  
So for binary classification with logit link function, the expected value should be :
`np.mean(scipy.special.logit(predict_proba_preds))
`
note that this isn't the same as:
`scipy.special.logit(np.mean(predict_proba_preds))`

**Comment by trikiamine23** [comment]
Thank you @dan11mcguire for your response.

![image](https://user-images.githubusercontent.com/56306832/102917766-0a0f1880-4486-11eb-9fe9-d4ad09ee3bdd.png)

This is an example of my issue
@dan11mcguire your example gives a real number of expected_value not a probability.

**Comment by dan11mcguire** [comment]
@trikiamine23  Yes,  thats the what's supposed to happen.  
there's some other posts on this topic where slundberg maybe explains better than me, but you could search and find that.

**Comment by trikiamine23** [comment]
Do you think that this generates probability shap values that do sum up to the predictions ?

**Comment by detrin** [comment]
@thatlittleboy Candidate for closing as I don't see a relevant issue here.
