### ISSUE TITLE
Should interaction defaults to None in dependence_plot?

### ISSUE THREAD

**Issue by chrisadas** [shap/shap#169]
interaction_index="auto" has been quite useful for me, but it was very confusing in the beginning when I saw a different feature over-plotted, and can't figure out why that particular feature was there and not the others. I thought I had some misalignment in my data somewhere that was causing different feature to be plotted than the one I specifically asked for.

Defaulting to None will also speed up the initial plotting.

**Comment by slundberg** [comment]
Thanks for the suggestion! I'll think about it. What you describe makes sense.
