### ISSUE TITLE
Buggy Library 

### ISSUE THREAD

**Issue by imrankhan441** [shap/shap#1696]
In my entire data science life, I never watch a buggy library like this.

in one line explain this is one of the buggiest library ever found in PyPI.

**Comment by pford221** [comment]
This is not a helpful issue. Open source offers you no guarantee. If it's too buggy, do something about it.

**Comment by imrankhan441** [comment]
I am so sorry about my behavior. Actually, I working on a project with my teacher, and it's pushing me into a bad situation and I lost my mind. I really apologize for my behavior.
