### ISSUE TITLE
Question about `summary_plot` for binary classification

### ISSUE THREAD

**Issue by wenmin-wu** [shap/shap#1699]
Hi, I have a question about the `summary_plot` of binary classification
![image](https://user-images.githubusercontent.com/9409333/103186752-c04a8600-48fc-11eb-89d8-0cfc9c75f2ba.png)

This graph is copied from [the official wiki of shap](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/tree_based_models/Census%20income%20classification%20with%20LightGBM.html)

What does the length of the bar for `class 1` and `class 0` mean? Because for the regression problem, from the summary graph we can check which features have positive impacts and which features have negative impacts as below:
![image](https://user-images.githubusercontent.com/9409333/103186991-a198bf00-48fd-11eb-9f70-824ddc5dbaf3.png)

**Comment by zahs123** [comment]
@wenmin-wu  what is the source code in how you generated the bar plot for shap? Would be interesting to see as i am unable to get this
