### ISSUE TITLE
Why is the shap value so sparse

### ISSUE THREAD

**Issue by sunjc73** [shap/shap#1700]
I used xgboost for regression training, and found that the shap values are particularly sparse. 2000+ features only have 300 non-zero shap values, the rest are zero. Is there any parameter to control whether the shap values are sparse or not?

**Comment by pford221** [comment]
It's likely that many of the 2,000+ features were never split upon in the tree building process and thus should have SHAP values of 0. Have you tried to look at feature importance to see what the "gain" of those features with SHAP values of 0 are?

**Comment by sunjc73** [comment]
> It's likely that many of the 2,000+ features were never split upon in the tree building process and thus should have SHAP values of 0. Have you tried to look at feature importance to see what the "gain" of those features with SHAP values of 0 are?

Thank you for your reply, I will try.
