### ISSUE TITLE
TreeExplainer's shap_values do not contains intercept value, it is not consistent with the doc's description

### ISSUE THREAD

**Issue by nickyi1990** [shap/shap#171]
shap_model = shap.TreeExplainer(model)
shap_values = shap_model.shap_values(data)

shap_values.shape[1]  is equal to data.shape[1]

**Comment by nickyi1990** [comment]
how could I get the value of intercept?

**Comment by slundberg** [comment]
Sorry the docs are updated on github but not yet on the pip version. In
your example use shap_model.expected_value
