### ISSUE TITLE
summary_plot legend move

### ISSUE THREAD

**Issue by imrankhan441** [shap/shap#1710]
# **How Can I move the legend to the right side**

![move](https://user-images.githubusercontent.com/26671669/103522744-ff507c80-4ea4-11eb-97f2-25303d722ec3.png)

**Comment by SumitTetarave** [comment]
fig, ax = plt.subplots(1,1)   
fig.legend(loc='lower right')
shap_values = shap.TreeExplainer(model).shap_values(val)
p= shap.summary_plot(shap_values, val,  color_bar_label='Feature value')
fig.legend(loc='lower right')
fig.savefig("shap.pdf", format='pdf', dpi=1000, bbox_inches='tight')

# Use fig.legend() before and after shap.summary_plot(). You may restart your file, if it does not work for you. Thanks.

**Comment by TommyGiak** [comment]
> # **How Can I move the legend to the right side**
> ![move](https://user-images.githubusercontent.com/26671669/103522744-ff507c80-4ea4-11eb-97f2-25303d722ec3.png)

# Just set `show=False` in `shape.plots`

Taking the above example:
```python
fig, ax = plt.subplots()
shap_values = shap.TreeExplainer(model).shap_values(val)
p = shap.summary_plot(shap_values, ax=ax, show=False)
ax.legend(loc='lower right')
plt.show()
```
In summary I added the axes in the shap plot and set show to False. Then you can personalise the legend as you would do in matplotlib.
