### ISSUE TITLE
nameerror

### ISSUE THREAD

**Issue by MATE515** [shap/shap#1719]
NameError                     __                Traceback (most recent call last)

<ipython-input-10-65cc04153b8f> in <module>
      3 
      4 # Run object detection
----> 5 results = model.detect([image], verbose=1)
      6 
      7 # Display results

NameError: name 'model' is not defined
如何解決

**Comment by omgitsbenhayes** [comment]
Is this still providing an error? If so, can you provide more information about the _fons et origo_ of this error?
