### ISSUE TITLE
index problem with interaction .summary_plot

### ISSUE THREAD

**Issue by cbeauhilton** [shap/shap#172]
Hi! This is a fantastic package --- thank you so much!

I'm having an issue producing the SHAP interaction values summary plot, as shown in the NHANES example. All the other visualizations are working with no issues. When I use the code from the NHANES notebook, no matter how much I mess with the axis values I get an `IndexError`. I'm sure I'm missing something.

Here's the code you provided, followed by my modification to fit my dataset.

`#shap_interaction_values = shap.TreeExplainer(model).shap_interaction_values(X.iloc[:2000,:])
#shap.summary_plot(shap_interaction_values, X.iloc[:2000,:])`

`shap_interaction_values = shap.TreeExplainer(gbm).shap_interaction_values(features_imputed_df.iloc[:1900,:])
shap.summary_plot(shap_interaction_values, features_imputed_df.iloc[:1900,:])`

This throws the error:

`380         pl.figure(figsize=(1.5 * max_display + 1, 0.8 * max_display + 1))`
`381         pl.subplot(1, max_display, 1)`
`--> 382         proj_shap_values = shap_values[:, sort_inds[0], np.hstack((sort_inds, len(sort_inds)))]`
`383         proj_shap_values[:, 1:] *= 2  # because off diag effects are split in half`
`384         summary_plot(`
`IndexError: index 71 is out of bounds for axis 2 with size 71`

However, this code for the heatmap style summary plot, where the indices are set with `tmp` and `tmp2`, works with no problems:

`tmp = np.abs(shap_interaction_values).sum(0)`
`for i in range(tmp.shape[0]):`
`    tmp[i,i] = 0`
`inds = np.argsort(-tmp.sum(0))[:20]`
`tmp2 = tmp[inds,:][:,inds]`
`pl.figure(figsize=(12,12))`
`pl.imshow(tmp2)`
`pl.yticks(range(tmp2.shape[0]), X.columns[inds], rotation=50.4, horizontalalignment="right")`
`pl.xticks(range(tmp2.shape[0]), X.columns[inds], rotation=50.4, horizontalalignment="left")`
`pl.gca().xaxis.tick_top()`
`pl.savefig('interaction value summary.png', dpi=400, transparent=False, bbox_inches='tight')`
`pl.show()`
`pl.close()`

I'm using Python 3.7.0, maximally updated lightGBM, mpl, sklearn, etc., on a Windows 10 machine with Jupyter Notebook.

**Comment by cbeauhilton** [comment]
Looks like gabrielcs and I are having the same issue:

https://github.com/slundberg/shap/issues/173

**Comment by slundberg** [comment]
Thanks for pointing this out! #174 is merged now to fix this, and should be on pip soon with v0.20.2

**Comment by cbeauhilton** [comment]
Great, thank you very much!
