### ISSUE TITLE
name error

### ISSUE THREAD

**Issue by niteshkumar0205** [shap/shap#1725]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-35-8fd2b8cdf88b> in <module>
----> 1 labels = model.labels
      2 fig = plt.figure(figsize=(12,10))
      3 sns.scatterplot(df['latitude'], df['longitude'], hue = ['cluster-{}'.format(x) for x in labels])
      4 plt.legend(bbox_to_anchor = [1, 1])
      5 plt.show()

NameError: name 'model' is not defined

**Comment by omgitsbenhayes** [comment]
Can you provide more information? It's unclear to me how this relates to shap and it looks like there's a naming issue with 'model'

**Comment by GujjarSanjeeth** [comment]
have u got your answer @niteshkumar0205 ?

**Comment by niteshkumar0205** [comment]
Yup I got it
