### ISSUE TITLE
shap summary plot has different class colors in different models with the same "class_names"

### ISSUE THREAD

**Issue by rockon8765** [shap/shap#1730]
Hello 
I use shap.summary_plot to see the XGBoost and RandomForest results.
The two models have the same class_names.
![image](https://user-images.githubusercontent.com/31650358/104314928-1cc0be80-5515-11eb-9e51-bdceb5c7696c.png)

However, the color of the same class name is different between these two summary plots.  
![image](https://user-images.githubusercontent.com/31650358/104312815-18df6d00-5512-11eb-8560-091dacab664b.png)
![image](https://user-images.githubusercontent.com/31650358/104312889-33194b00-5512-11eb-9aa1-1d44fa93a77d.png)

How can I adjust the colors of legend in the same class name?

**Comment by CosimoRusso** [comment]
You can give the option `class_inds='original'` to the `shap.summary_plot()` methods. It will always keep the class labels in the same order, and thus with the same color
