### ISSUE TITLE
Install error python 3.8 on Mac OS X Big Sur

### ISSUE THREAD

**Issue by xyzQ2** [shap/shap#1756]
Worked fine previously and now receive this error on pip install shap:

Collecting shap
  Using cached shap-0.38.1.tar.gz (352 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/setup.py'"'"'; __file__='"'"'/private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-pip-egg-info-wn8rbuh_
         cwd: /private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vl/v_qqb7m90j78c3h1d_dyzx3m0000gn/T/pip-install-o84jijp9/shap_92982187dca64ab296328dcab301bb95/setup.py", line 25, in <module>
        python_target = LooseVersion(get_config_var('MACOSX_DEPLOYMENT_TARGET'))
      File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/version.py", line 304, in __init__
        self.parse(vstring)
      File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/version.py", line 312, in parse
        components = [x for x in self.component_re.split(vstring)
    TypeError: expected string or bytes-like object
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sysfri** [comment]
encountered the same problem.

**Comment by sysfri** [comment]
@qboy21 what environment is your Mac when the SHAP worked? mojave?  python3.6?

**Comment by xyzQ2** [comment]
@sysfri. Mac OS X Big Sur and Python 3.6. Literally 2 weeks ago.

**Comment by sysfri** [comment]
@qboy21 thanks, man. just got my Mac back to Mojave with time machine, fortunately anaconda is python3.6.

**Comment by xyzQ2** [comment]
@sysfri it also works on 3.7.4 as I use it at work as well. I wish I would get a response on how to resolve the error and not to rollback my python as a solution. patiently waiting.....

**Comment by xyzQ2** [comment]
@slundberg . any thoughts please? thank you.

**Comment by sysfri** [comment]
@qboy21 I think as an academic guy(first author of NATURE paper), he seems don't have much time to deal with this kind of things.

**Comment by jpgri** [comment]
Try to run this before install shap: `sudo xcodebuild -license` 
If you agree, then just install shao in you virtualenv or as system:
It worked for me after agree on the xcodebuild licence.
Mac os Big Sur 11.1,  pyenv virtualenv with python 3.7.9 and also in 3.8.2. Shap 0.38.1

**Comment by xyzQ2** [comment]
> Try to run this before install shap: `sudo xcodebuild -license`
> If you agree, then just install shao in you virtualenv or as system:
> It worked for me after agree on the xcodebuild licence.
> Mac os Big Sur 11.1, pyenv virtualenv with python 3.7.9 and also in 3.8.2. Shap 0.38.1

I appreciate the advice, it doesn't work. I will just use a previous version of python.

**Comment by xyzQ2** [comment]
downgraded python to 3.8.2. poor resolution to the issue.

**Comment by Maryom** [comment]
@qboy21 I have same issue and I can't downgrade to python 3.8.2 I can downgrade to python 3.8.7 but still SHAP is not working. Any solution?

**Comment by joanwa** [comment]
only way to make it work for me was to install the full xcode, not just the commandline tools. Otherwise I'm on

- pip 21.0.1
- Python 3.8.8

**Comment by hantoine** [comment]
For me installing gcc with Homebrew and using the following command to install shap worked:

`env CC=/usr/local/Cellar/gcc/11.2.0/bin/gcc-11 CPATH=/usr/local/include/c++/11.2.0 pip install shap`
