### ISSUE TITLE
Issue with categorical variables in LGBM

### ISSUE THREAD

**Issue by mmonges** [shap/shap#176]
Since i updated to the last version of the package (today), the TreeExplainer method does not work for categorical variables anymore. I am getting an error I was not getting before with the exact same code.

This is my code:
`data[cols_cat] = data[cols_cat].apply(lambda x: x.astype('category'))
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size = 0.2, random_state=7)

dtrain_l = lgb.Dataset(X_train, label=y_train, 
                       categorical_feature = cols_cat, 
                       free_raw_data=False)
dtest_l = lgb.Dataset(X_test, label=y_test, 
                      categorical_feature = cols_cat, 
                      free_raw_data=False)

model= lgb.train(params, dtrain_l, valid_sets=[dtest_l], verbose_eval=10, early_stopping_rounds=10)
explainer = shap.TreeExplainer(model)
`

This is the error:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-368-b35bcca2838f> in <module>()
      2 # (same syntax works for LightGBM and scikit-learn models)
      3 deb = time.time()
----> 4 explainer = shap.TreeExplainer(bestModel)
      5 #shap_values = explainer.shap_values(X_train)
      6 print(time.time() - deb)

L:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\tree.py in __init__(self, model, **kwargs)
     91             self.model = model
     92             tree_info = self.model.dump_model()["tree_info"]
---> 93             self.trees = [Tree(e, scaling=len(tree_info)) for e in tree_info]
     94         elif str(type(model)).endswith("lightgbm.sklearn.LGBMRegressor'>"):
     95             self.model_type = "lightgbm"

L:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\tree.py in <listcomp>(.0)
     91             self.model = model
     92             tree_info = self.model.dump_model()["tree_info"]
---> 93             self.trees = [Tree(e, scaling=len(tree_info)) for e in tree_info]
     94         elif str(type(model)).endswith("lightgbm.sklearn.LGBMRegressor'>"):
     95             self.model_type = "lightgbm"

L:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\tree.py in __init__(self, tree, normalize, scaling)
    380                             self.children_default[vertex['split_index']] = self.children_right[vertex['split_index']]
    381                         self.features[vertex['split_index']] = vertex['split_feature']
--> 382                         self.thresholds[vertex['split_index']] = vertex['threshold']
    383                         self.values[vertex['split_index']] = [vertex['internal_value']]
    384                         self.node_sample_weight[vertex['split_index']] = vertex['internal_count']

ValueError: could not convert string to float: '3||4'
`

**Comment by slundberg** [comment]
Sorry about that. #170 is the same issue. It has been fixed and will be released when v0.20.2 hits pip (later today).

**Comment by mmonges** [comment]
Thank you very much !

**Comment by chjq201410695** [comment]
The problem seems appear again. my version of shap is 0.24.0
