### ISSUE TITLE
summary_plot for shap_interaction_value fails with "index is out of bounds" error

### ISSUE THREAD

**Issue by hofesh** [shap/shap#178]
Fails in /shap/plots.py 
line 382:         proj_shap_values = shap_values[:, sort_inds[0], np.hstack((sort_inds, len(sort_inds)))]

Since len(sort_inds) exceeds the last index of shap_values

The error is also reproducible in the sample notebook:
https://slundberg.github.io/shap/notebooks/NHANES%20I%20Survival%20Model.html

**Comment by slundberg** [comment]
Thanks for reporting this. I think it's the same as #172 and was fixed in the release pushed out yesterday. Can you check your version of shap and try with the latest?

**Comment by WithPrecedent** [comment]
I know this is an old issue, but I've been getting this error with version 0.28.5 Strangely, I only get this error when using RandomForestClassifier, but not XGBClassifier. Everything is exactly the same and the code just drops in the random forest model with the appropriate parameters. It's part of a project where I'm trying to make a simpler interface for preprocessing, machine learning, and model evaluation (https://github.com/WithPrecedent/simplify). The specific code that gets the error is here:  https://github.com/WithPrecedent/simplify/blob/master/simple_ml/plotter.py. I get the error using the Wisconsin breast cancer data in my examples folder (https://github.com/WithPrecedent/simplify/blob/master/examples/classification_cancer.py). The exact code excerpt is nearly identical to the notebook above and code in report #172:

        tmp = np.abs(shap_interactions).sum(0)
        for i in range(tmp.shape[0]):
            tmp[i, i] = 0
        inds = np.argsort(-tmp.sum(0))[:30]
        tmp2 = tmp[inds,:][:,inds]
        plt.figure(figsize = (12, 12))
        plt.imshow(tmp2)
        plt.yticks(range(tmp2.shape[0]),
                   x.columns[inds],
                   rotation = 50.4,
                   horizontalalignment = 'right')
        plt.xticks(range(tmp2.shape[0]),
                   x.columns[inds],
                   rotation = 50.4,
                   horizontalalignment = 'left')
        plt.gca().xaxis.tick_top()

This is the last part of the traceback:

  File "C:\Users\corey\Documents\GitHub\simplify\simple_ml\recipe.py", line 130, in bake
    method()

  File "C:\Users\corey\Documents\GitHub\simplify\simple_ml\recipe.py", line 101, in _plotter
    evaluator = self.evaluator)

  File "C:\Users\corey\Documents\GitHub\simplify\simple_ml\plotter.py", line 159, in mix
    self.options[plot]()

  File "C:\Users\corey\Documents\GitHub\simplify\simple_ml\plotter.py", line 92, in heat_map
    tmp[i, i] = 0

IndexError: index 30 is out of bounds for axis 1 with size 30

Shap has been an amazing asset in my work. I appreciate your incredible efforts on it. I want to make it the central explainer of my siMpLify package, but keep running into little hiccups like this one (the other common error is that some models aren't callable). Any help would be appreciated. Thanks.
