### ISSUE TITLE
React: AdditiveForceVisualizer does not show dividers and background for input features

### ISSUE THREAD

**Issue by nilsplettenberg** [shap/shap#1786]
I used the AdditiveForceVisualizer from the javascript directory as a react component, which worked fine. However, the plot doesn't show any dividers between the feature names at the bottom.
```
<AdditiveForceVisualizer
  outNames={["Probability of flower"]}
  baseValue={0.2}
  link="identity"
  features={[
    { name: "F1", effect: 0.3, value: 1 },
    { name: "F2", effect: -0.6, value: 1 },
    { name: "F3", effect: -0.2, value: 2 },
    { name: "F4", effect: 0, value: 0 }
  ]}
/>
```
Expected result:
![image](https://user-images.githubusercontent.com/45755841/105976784-e183cb00-6090-11eb-9b1f-ce061698e314.png)
Result:
![image](https://user-images.githubusercontent.com/45755841/105976683-c618c000-6090-11eb-850a-823fed4d4e5e.png)

The console does not show any errors, I didn't modify any of the code. Am I missing anything here?

**Comment by zmzimpl** [comment]
The same problem, is whether the version is inconsistent?

**Comment by zmzimpl** [comment]
> The same problem, is whether the version is inconsistent?

Need to set labelMargin
