### ISSUE TITLE
[Question] how to get meaningful expected value with down-sampled dataset

### ISSUE THREAD

**Issue by songqiang** [shap/shap#1788]
Hello, 

I have a binary classification problem with significant class imbalance (for example, positive case to negative case is 1:1000). During model training, I down-sampled the negative cases to get a more balanced training data (positive to negative is 1:10). 

I use xgboost as my model backend and TreeExplainer as the explainer. If I use the "tree_path_dependent" feature_perturbation method, the expected value is something close to 0.1 in probability space and -2.19 in the logit space. If I pass in the down-sampled training data as my background dataset, the expected value is also around 0.1. However when presenting to the business users, it will be more intuitive to show the expected value around 0.001.

I am thinking about a few options:

1. is it possible to set the desired expected_value as an option? I can change the expected in the force_plot, but it also shift the model output accordingly, which is undesirable.

2. is it possible to pass a weight dataset when passing the background dataset? I saw this issue https://github.com/slundberg/shap/issues/1328, but it seems not doable

3. I pass a background dataset from the original population. But the problem is that the background data have to be more than 1000 samples to include one single positive sample, which makes the explaining process slow. In addition, the particular positive cases in the sampled data has significant impact on the calculated value.

Do you have suggestions on how to achieve that?

Thanks!

**Comment by JiaxiangBU** [comment]
> 2\. is it possible to pass a weight dataset when passing the background dataset?


Here is the partial solutions from https://stackoverflow.com/a/71423605/8625228

> I face the same scenario. Here is my partial solution, I hope it is beneficial to you. Here my model is XGBoost instead of a linear learner.
> 
> - I can insert the sample weight into the `xgboost.DMatrix` using the `weight`  argument. And I put this matrix into explainer to get the shap values with reweighted samples. And I do the absolute value calculation to get the bar plot for feature importances.
> - Alternatively, try the `pandas.DataFrame.sample` function to do the resampling using the `weight` argument. Next, do the similar procedure like what you do using shap package.
> 
> Both solutions works for me.
