### ISSUE TITLE
Chinese features support

### ISSUE THREAD

**Issue by GISH123** [shap/shap#1790]
Hello, I'm currently using BERT model for a 3 classes classifier for chinese texts.
Currently i'm trying to use shap's Partition Explainer, but the output will be like this:
![image](https://user-images.githubusercontent.com/4023299/106083096-e01cd600-6156-11eb-8c23-e88093759823.png)

I suspect that it's because chinese feature names can't be shown.
Or is there any other possible problem?
And may someone give a guidance on how to fix this?
Thanks in advance!

**Comment by GISH123** [comment]
I solved it, its from matplotlib text font problems, not about shap.

**Comment by bml1g12** [comment]
> I solved it, its from matplotlib text font problems, not about shap.

Please could you share the solution?
