### ISSUE TITLE
[Paper] Question about Theorem 1.

### ISSUE THREAD

**Issue by Hyungsik-Jung** [shap/shap#1792]
Hi, 

I have a question about Theorem 1 in the SHAP paper.
Aligning with the definition of the classic Shapley value, I think the numerator of the equation should be (|z'|-1)!(M-|z'|)!.
Because, the absence of the i-th feature in z' is not guaranteed. Am I wrong? 

Thank you in advance.

**Comment by slundberg** [comment]
Yes. Please check out the paper errata doc on my website for more details: https://github.com/slundberg/shap/raw/master/docs/pdfs/SHAP_NIPS_2017_Errata.pdf

**Comment by julmeran** [comment]
Hi,
i also have a question about the proof of the theorem. 

 If i understand it correctly, you proof the theorem by showing the equivalence between the Shapley Properties 1) - 4) and the "new" Properties 1) - 3) and the feature attribution methods property.

I don't understand how to map the properties from the paper to the properties from the supplementary material.

1) Efficiency fits to Local Accuracy, thats ok.
2) Symmetry is implied by Consistency as seen in supplementary material

So how to proof the remaining two properties?

3) Null Effects
4) Linearity

Thank you in advance.

**Comment by ximingwen** [comment]
My question is in theorem 1,
1.  does z' always include the i-th feature? 
2.  since z' is a subset of x', which measn |x'| <= M (all features), why do we still use M in this theorem.
Thank you very much

**Comment by julmeran** [comment]
> My question is in theorem 1,
> 
> 1. does z' always include the i-th feature?
> 2. since z' is a subset of x', which measn |x'| <= M (all features), why do we still use M in this theorem.
>    Thank you very much

@ximingwen 
As far as I understood:
1. z' can be every vector of zeros and ones, as long as the j-th component of z' is not bigger than the j-th component of x'. So z' can also be a vector full of zeros.
2. M is the amount of simplified Input features, so in this case it should be M = |x'|
