### ISSUE TITLE
Model type not yet supported by TreeExplainer: <class 'tensorflow.python.keras.engine.sequential.Sequential'>

### ISSUE THREAD

**Issue by Nestak2** [shap/shap#1796]
I am trying to use shap on an LSTM neural net I created with Keras. My imports are these:

```
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
from tensorflow.keras.models import Model, Sequential, load_model
from tensorflow.keras.optimizers import SGD, Adam
import tensorflow as tf

from tensorflow.keras.layers import *
```

And my architecture is this:

```
## model taken from here: https://www.tensorflow.org/tutorials/structured_data/time_series?fbclid=IwAR1CfmX6adoEpeVF9hqc1eNMf7AJIZM0pEzWpyMvbfFizxsa2uR97yDvgKQ#recurrent_neural_network
model = Sequential()
model.add(LSTM(32, return_sequences=False, input_shape=(n_input, X.shape[1])))
model.add(Dense(24))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mse'])

model.fit(train_generator, validation_data=val_generator, epochs=15, verbose=1,
             callbacks=[modelsave_cb])
```

Unfortunately, I get the above-mentioned error message:

`Exception: Model type not yet supported by TreeExplainer: <class 'tensorflow.python.keras.engine.sequential.Sequential'>
`

What's the source of the problem? Doesn't shap work with LSTMs and sequential? Or should I maybe import the layers in a different way, as suggested [here](https://stackoverflow.com/a/61861991/5838180)? Thanks

**Comment by andyquin** [comment]
Hi,

TreeExplainer is used to interpret decision tree based models. I think you'll have better luck making shap work on your model with DeepExplainer. 

I hope this documentation example helps: https://shap.readthedocs.io/en/latest/example_notebooks/text_examples/sentiment_analysis/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html
