### ISSUE TITLE
shap.visualize() output charts are truncated / poorly formatted

### ISSUE THREAD

**Issue by ryan-maus** [shap/shap#18]
## Environment info
Firefox 52.5.2 on Debian 9.3

[requirements.txt](https://github.com/slundberg/shap/files/1645141/requirements.txt)

## Steps to reproduce
```python
print(shap_values)
print(feature_names)
print(np.array(X))
shap.visualize(shap_values[0,:], feature_names=feature_names, data=np.array(X)[0,:])
```
Output:
```
[[-0.09046029 -0.05412534 -0.00113313]
 [-0.08825505  0.04928131 -0.00113313]
 [ 0.11093738 -0.05434655 -0.00113313]
 [ 0.10730842  0.04322589 -0.00113313]
 [-0.09046029 -0.05412534 -0.00113313]
 [-0.08825505  0.04928131 -0.00113313]
 [ 0.11093738 -0.05434655 -0.00113313]
 [ 0.10730842  0.04322589 -0.00113313]]
['TestFloatFeature', 'TestBinaryFeature']
[[0.2 2. ]
 [0.2 1. ]
 [0.4 2. ]
 [0.4 1. ]
 [0.2 2. ]
 [0.2 1. ]
 [0.4 2. ]
 [0.4 1. ]
 [0.2 2. ]
 [0.2 1. ]
 [0.4 2. ]
 [0.4 1. ]]
```
Visualize single prediction:
![shap_issue](https://user-images.githubusercontent.com/302280/35132592-939d3536-fc91-11e7-8196-5c67188d4e7a.png)

Visualize multiple predictions:
![shap_issue2](https://user-images.githubusercontent.com/302280/35132722-3b0726ba-fc92-11e7-86fb-20a7db97610c.png)

These charts are largely unreadable, unlike the README example charts.  The input data is all contrived samples just to get my workspace set up, so I've done virtually no customization aside from just installing stock packages.

**Comment by kodonnell** [comment]
Seconded. If you manually set the svg width to 100%, all is well - so easy fix @slundberg ?

![image](https://user-images.githubusercontent.com/8204904/35139073-57a5fbce-fd56-11e7-996a-41b5ca5c1f07.png)

**Comment by ryan-maus** [comment]
@kodonnell nice catch, piggybacking off that, the 'additive-force-array-ylabel' element has a large 'top' style (=184px for me) which pushes it too far down (see my second image above).

**Comment by ryan-maus** [comment]
@kodonnell correction, the `addive-force-array-ylabel` is correctly positioned, however the chart height is incorrect.  Manually setting it to ~400px makes everything line up pretty closely, and the rest of the chart is now visible:

![shap_issue3](https://user-images.githubusercontent.com/302280/35153017-6439097e-fcea-11e7-866f-9c7390e3d51b.png)

**Comment by slundberg** [comment]
Thanks for reporting this. I'll see if I can reproduce it later today.

**Comment by slundberg** [comment]
It was an issue where Chrome was happy taking `10` for a width while Firefox requires `10px`. The bug is actually in the `iml` package so `pip install iml --upgrade` should now fix it. I'll bump the dependency for `shap` soon to depend on the fix.
