### ISSUE TITLE
Kernel Crash with Catboost

### ISSUE THREAD

**Issue by ThomasWolf0701** [shap/shap#1800]
I attached both the featureMatrix and the model using pickles:
errorReproduceObjects.zip

The model uses MutliRMSE and catboost 0.24.4 and
bestModel.predict(transformedMatrix) works fine

bestModel.predict(transformedMatrix)
Out[44]:
array([[-4.84283473, -4.66173853],
[-4.03272354, -3.80896785],
[-2.61701992, -2.22272565],
...,
[-4.5486192 , -4.31635738],
[-2.81394494, -2.38203556],
[-4.02415018, -3.65515251]])

When I use the SHAP package instead of the catboost internal function I get a Kernel crash.

explainer = shap.TreeExplainer(bestModel["m"])
bestModelShap = explainer.shap_values( transformedMatrix)

Kernel died, restarting

Restarting kernel...

[SpyderKernelApp] WARNING | No such comm: f2b6ca35666511eb9cf99cb6d01cd292
[SpyderKernelApp] WARNING | No such comm: 382dbce3666711eb95589cb6d01cd292
[SpyderKernelApp] WARNING | No such comm: ee4c9163666811ebb4899cb6d01cd292

When running the catboost internal shap I get a Kernel crash when using multiple cores and an error when
using only one core:

bestModelShap = bestModel.get_feature_importance(Pool(scipy.sparse.csr_matrix(transformedMatrix)),type = "ShapValues",thread_count = 1 )

Traceback (most recent call last):

File "", line 1, in
bestModelShap = bestModel.get_feature_importance(Pool(scipy.sparse.csr_matrix(transformedMatrix)),type = "ShapValues",thread_count = 1 )

File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 2555, in get_feature_importance
fstr, feature_names = self._calc_fstr(type, data, reference_data, thread_count, verbose, model_output, shap_mode, interaction_indices,

File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 1329, in _calc_fstr
return self._object._calc_fstr(type.name, pool, reference_data, thread_count, verbose, model_output, shap_mode, interaction_indices, shap_calc_type)

File "_catboost.pyx", line 4408, in _catboost._CatBoost._calc_fstr

File "_catboost.pyx", line 4437, in _catboost._CatBoost._calc_fstr

CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/model/scale_and_bias.h:63: Internal CatBoost Error (contact developers for assistance): Asked one-dimensional bias, has 2.Non single-dimension approxes are not supported

**Comment by ThomasWolf0701** [comment]
https://github.com/catboost/catboost/commit/3e93ca0aa1c50dd4cf3727ef56a7b0db3e6c57a0 
There is now a fix for this in the catboost internal SHAP calculations

**Comment by Dan-Treacher** [comment]
Hi - I'm encountering the same kernel crashing problem when trying to calculate shapley values from a catboostregressor object trained with 'RMSEWithUncertainty'.

The calls that result in this crash are `shap.TreeExplainer(catBoostRegressorModel).shap_values(sample_data)` or `catBoostRegressorModel.get_feature_importance(sample_data, type='ShapValues')`

The crash message is `Kernel died, restarting
Restarting kernel... 
[SpyderKernelApp] WARNING | No such comm: 19988c1271ca11eb82d05405dbb01e92
[SpyderKernelApp] WARNING | No such comm: 618b635c71f111eb81395405dbb01e92
[SpyderKernelApp] WARNING | No such comm: dee9bcff71f111eb83585405dbb01e92
[SpyderKernelApp] WARNING | No such comm: b9937fa271f311eba9725405dbb01e92`

My catboost version is 0.24.4

Could you give a little more detail about the fix you mentioned and whether it could be related to this similar error?

**Comment by ThomasWolf0701** [comment]
This was the error I got when running directly in catboost (see below for more details)

/scale_and_bias.h:63: Internal CatBoost Error (contact developers for assistance): Asked one-dimensional bias, has 2.Non single-dimension approxes are not supported

So it seems to me as if the catboost error was directly related to MultRMSE

For SHAP the error was more cryptic.


Problem: Error or Kernel Crash for SHAP calculation
catboost version: 0.24.4
Operating System: Windows 10
CPU: Intel Core i7

I attached both the featureMatrix and the model using pickles:
errorReproduceObjects.zip

The model uses MutliRMSE and
bestModel.predict(transformedMatrix) works fine

bestModel.predict(transformedMatrix)
Out[44]:
array([[-4.84283473, -4.66173853],
[-4.03272354, -3.80896785],
[-2.61701992, -2.22272565],
...,
[-4.5486192 , -4.31635738],
[-2.81394494, -2.38203556],
[-4.02415018, -3.65515251]])

When running the following code I get a Kernel crash when using multiple cores and an error when
using only one core:

bestModelShap = bestModel.get_feature_importance(Pool(scipy.sparse.csr_matrix(transformedMatrix)),type = "ShapValues",thread_count = 1 )

Traceback (most recent call last):

File "", line 1, in
bestModelShap = bestModel.get_feature_importance(Pool(scipy.sparse.csr_matrix(transformedMatrix)),type = "ShapValues",thread_count = 1 )

File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 2555, in get_feature_importance
fstr, feature_names = self._calc_fstr(type, data, reference_data, thread_count, verbose, model_output, shap_mode, interaction_indices,

File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 1329, in _calc_fstr
return self._object._calc_fstr(type.name, pool, reference_data, thread_count, verbose, model_output, shap_mode, interaction_indices, shap_calc_type)

File "_catboost.pyx", line 4408, in _catboost._CatBoost._calc_fstr

File "_catboost.pyx", line 4437, in _catboost._CatBoost._calc_fstr

CatBoostError: c:/program files (x86)/go agent/pipelines/buildmaster/catboost.git/catboost/libs/model/scale_and_bias.h:63: Internal CatBoost Error (contact developers for assistance): Asked one-dimensional bias, has 2.Non single-dimension approxes are not supported

When I use the SHAP package instead of the catboost internal function I get a Kernel crash.

explainer = shap.TreeExplainer(bestModel["m"])
bestModelShap = explainer.shap_values( transformedMatrix)

Kernel died, restarting

Restarting kernel...

[SpyderKernelApp] WARNING | No such comm: f2b6ca35666511eb9cf99cb6d01cd292
[SpyderKernelApp] WARNING | No such comm: 382dbce3666711eb95589cb6d01cd292
[SpyderKernelApp] WARNING | No such comm: ee4c9163666811ebb4899cb6d01cd292

**Comment by jarandaf** [comment]
I am also getting the same error with a model trained with `RMSEWithUncertainty` loss

**Comment by jarandaf** [comment]
Building Catboost from source (https://github.com/catboost/catboost/commit/09939b4d2a74f27be7b147e9a1fa74c51b1cfdf2) seems to fix the issue (using Catboost's API method `get_feature_importance`)

**Comment by ThomasWolf0701** [comment]
> 
> 
> Building Catboost from source ([catboost/catboost@09939b4](https://github.com/catboost/catboost/commit/09939b4d2a74f27be7b147e9a1fa74c51b1cfdf2)) seems to fix the issue (using Catboost's API method `get_feature_importance`)

Yes because they fixed after i posted the issue on their Github page, but thr SHAP package probably still gives the error.

**Comment by Dan-Treacher** [comment]
@jarandaf , by 'building from source' do you mean using `catBoostRegressorModel.get_feature_importance(sample_data, type='ShapValues')` as oppose to `shap.TreeExplainer(catBoostRegressorModel).shap_values(sample_data)`?

For me, both of those calls result in the kernel crash

**Comment by jarandaf** [comment]
@Dan-Treacher I mean I compiled Catboost from source code (I don't use the latest release available 0.24.4 on PyPi/conda forge because it does not include the fix commented by @ThomasWolf0701). Check [this](https://catboost.ai/docs/installation/python-installation-method-build-from-source-linux-macos.html) for instructions.

**Comment by Dan-Treacher** [comment]
Thanks for the link @jarandaf. I've noticed that using `CatBoostRegressor` from PyPi/conda forge latest release with `loss function = RMSE` does work with the shap library, so my workaround will probably be to have two versions of the same model running simultaneously but one with `loss function = RMSEWithUncertainty` and the other with `loss function = RSME`.

I'm fairly confident that the two models should produce the same absolute value of predictions. I'll update this post when I've had the chance to try just for posterity

Update: They do not :(

**Comment by ThomasWolf0701** [comment]
In the meantime the issue was fixed and it´s working again.

**Comment by Dan-Treacher** [comment]
Can confirm that the issue I mentioned above has been fixed.
Regression models trained with `loss_function='RMSEWithUncertainty'` can now successfully have shapley values extracted
This fix occurred after I upgraded to the following library versions: `catboost==0.26`; `shap==0.39`
