### ISSUE TITLE
Deep forest support

### ISSUE THREAD

**Issue by Maryom** [shap/shap#1805]
Hey,

Thanks for your useful repo.
I need to use it with [deep forest](https://github.com/leopiney/deep-forest) I tried and I got the same error:

> AssertionError: <class 'NoneType'> is not currently a supported model type!

Is there a way to use SHAP with deep forest?

**Comment by Adarsh5harma** [comment]
> Hey,
> 
> Thanks for your useful repo. I need to use it with [deep forest](https://github.com/leopiney/deep-forest) I tried and I got the same error:
> 
> > AssertionError: <class 'NoneType'> is not currently a supported model type!
> 
> Is there a way to use SHAP with deep forest?

Hey did you find how to implement shap on deep forest?
