### ISSUE TITLE
NameError: name 'xgboost' is not defined

### ISSUE THREAD

**Issue by TMorville** [shap/shap#181]
When running the example 

```
import xgboost
import shap

# load JS visualization code to notebook
shap.initjs()

# train XGBoost model
X,y = shap.datasets.boston()
model = xgboost.train({"learning_rate": 0.01}, xgboost.DMatrix(X, label=y), 100)

# explain the model's predictions using SHAP values
# (same syntax works for LightGBM, CatBoost, and scikit-learn models)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)

# visualize the first prediction's explanation
shap.force_plot(explainer.expected_value, shap_values[0,:], X.iloc[0,:]
```
I get 

```
~/.local/lib/python3.5/site-packages/shap/explainers/tree.py in shap_values(self, X, tree_limit, **kwargs)
    128         if self.model_type == "xgboost":
    129             if not str(type(X)).endswith("xgboost.core.DMatrix'>"):
--> 130                 X = xgboost.DMatrix(X)
    131             if tree_limit == -1:
    132                 tree_limit = 0

NameError: name 'xgboost' is not defined
``` 
XGBoost is 0.72.1 and SHAP is 0.21.0 at Python 3.5.2.

**Comment by slundberg** [comment]
Strange. The import for that file is wrapped in a try catch (see below), but it seems like you can load xgboost or it would not have gotten that far. Did you get the failed to load message from below? You might just comment out the try catch part and see what fails.

https://github.com/slundberg/shap/blob/6b7519d0eb4a7c439ca05706704f628c01f9dedf/shap/explainers/tree.py#L16-L22

**Comment by valilenk** [comment]
Got the same problem in jupyter lab and it was solved when i moved import from try catch. Strange

```import numpy as np
import multiprocessing
import sys
import xgboost

have_cext = False
try:
    from .. import _cext
    have_cext = True
except ImportError:
    pass
except:
    print("the C extension is installed...but failed to load!")
    pass

#try:
#    import xgboost
#except ImportError:
#    pass
#except:
#    print("xgboost is installed...but failed to load!")
#    pass
```

**Comment by slundberg** [comment]
I tried to clean up all the import try catches so they now print errors in 3ef7c2ef5b425df23c05d7b7cbc7cab5609a2870. If you still have the same issue on master please share whatever errors they print :)

**Comment by change2014** [comment]
I too am getting the same error.

NameError                                 Traceback (most recent call last)
<ipython-input-6-0a7ddb7703b7> in <module>()
      2 # (same syntax works for LightGBM, CatBoost, and scikit-learn models)
      3 explainer = shap.TreeExplainer(model)
----> 4 shap_values = explainer.shap_values(X)

/Users/anaconda/lib/python3.6/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate)
    176             if self.model_type == "xgboost":
    177                 if not str(type(X)).endswith("xgboost.core.DMatrix'>"):
--> 178                     X = xgboost.DMatrix(X)
    179                 if tree_limit == -1:
    180                     tree_limit = 0

NameError: name 'xgboost' is not defined

**Comment by slundberg** [comment]
What verison of Python are you using? And I assume you can import xgboost
yourself fine right?

**Comment by change2014** [comment]
i am using python 3.6.0, yes i can import xgboost fine.

**Comment by ChrisMillerAscentium** [comment]
I was also experiencing this issue, and rectified it by squeezing the array of response variables. Previously, it was (N, 1), and after squeezing the array it was (N,). That might explain why it worked to train the xgboost model, but not for shap.

**Comment by slundberg** [comment]
Not sure why squeezing would impact the import of xgboost. I pushed a new version to pip with better import checking so it would be worth confirming that still is a problem.

**Comment by Remi-Boutin** [comment]
Hello everyone,
I'm having the same issue here, just by trying to reproduce your code 

`import xgboost
import shap

### load JS visualization code to notebook
shap.initjs()

### train XGBoost model
X,y = shap.datasets.boston()
model = xgboost.train({"learning_rate": 0.01}, xgboost.DMatrix(X, label=y), 100)
`

I have updated the shap package, the error is not at the same place as it was before but still remains : 
 
`
NameError                                 Traceback (most recent call last)
<ipython-input-33-407268b7eee1> in <module>()
      1 explainer = shap.TreeExplainer(model)
----> 2 shap_values = explainer.shap_values(X)
      3 shap.force_plot(explainer.expected_value, shap_values[0,:], X.iloc[0,:])

C:\conda3\lib\site-packages\shap\explainers\tree.py in shap_values(self, X, y, tree_limit, approximate)
    176                 phi = self.model.original_model.get_feature_importance(data=X, fstr_type='ShapValues')
    177 
--> 178             # note we pull off the last column and keep it as our expected_value
    179             if phi is not None:
    180                 if len(phi.shape) == 3:

NameError: name 'xgboost' is not defined
`
I do not really understand what is not working and why the comment would be the error, quite mysterious !

**Comment by change2014** [comment]
I installed shap again, and its working totally fine now. Thanks a lot.

**Comment by NematUmed** [comment]
Here, I have faced the same problem, can anyone give his opinion?

PROMPT="Enter an int value (<0 to end):"
myStack=myStack()
value=int(input(PROMPT))

while value>=0:
    myStack.push(value)
    value=int(input(PROMPT))

while not myStack.isEmpty():
    value=myStack.pop()
    print(value)

Traceback (most recent call last):
  File "C:/Users/black mamba/PycharmProjects/Except/Exception.py", line 5, in <module>
    myStack=myStack()
NameError: name 'myStack' is not defined

**Comment by hravkin** [comment]
I had the same issue. Not sure why, but reinstalling shap makes it work.
