### ISSUE TITLE
SHAP explaination in BiRNN Keras model

### ISSUE THREAD

**Issue by ph0123** [shap/shap#1816]
I write the issue here https://stackoverflow.com/questions/66150578/shap-explaination-in-birnn-keras-model

Is there any problem with that?
I read some advice. They said that add a line as below before the Deep explainer. 
shap.explainers.deep.deep_tf.op_handlers["AddV2"] = shap.explainers.deep.deep_tf.passthrough

and the error is 

`module 'shap.explainers' has no attribute 'deep'`

**Comment by gladomat** [comment]
Try this:

```
from shap.explainers.deep.deep_tf import passthrough
shap.explainers._deep.deep_tf.op_handlers['AddV2'] = passthrough
```

**Comment by ph0123** [comment]
The new error is "ModuleNotFoundError: No module named 'shap.explainers.deep'"
