### ISSUE TITLE
Deep Explainer beyond Sequential models

### ISSUE THREAD

**Issue by amir-ghasemi** [shap/shap#182]
Hi Scott,

Are there any plans to extend the Deep Explainer to Keras' functional api? I'm particularly interested in models with residual connections. Any pointers on if or how this could be achieved would be great. Thanks!

**Comment by slundberg** [comment]
You can pass any pair of input/output tensors to the model, so that should
work for the functional API and also raw tensorflow models. If you run into
any issues with that let me know. The DeepExplainer class is fairly new so
you may run into tensor flow components that are not yet supported, but we
can add.

**Comment by amir-ghasemi** [comment]
Thanks, I tried feeding the model's input and output tensors and got this error:

` 142         back_ops = tf.contrib.graph_editor.get_backward_walk_ops(
    143             [self.model_output],
--> 144             within_ops_fn=lambda op: op.type not in DeepExplainer.dependence_breakers
    145         )
    146         self.between_ops = tf.contrib.graph_editor.get_forward_walk_ops(

TypeError: get_backward_walk_ops() got an unexpected keyword argument 'within_ops_fn'`

**Comment by amir-ghasemi** [comment]
Thanks for the pointer. I'm getting an error due to tf.pad not being supported.

**Comment by slundberg** [comment]
Thanks for letting me know. I plan to address a bunch of these later this week, so I'll add that to the list.

**Comment by amir-ghasemi** [comment]
Excellent, thanks! Looking forward to using this.

**Comment by slundberg** [comment]
Support is now on the github version. I'll push a new release with it early next week.
