### ISSUE TITLE
Introduce a dependence on IPython

### ISSUE THREAD

**Issue by IvanUkhov** [shap/shap#1821]
Hello, given that IPython is used internally, would it make sense to mention it in `setup.py` so that it gets installed together with `shap`? Thank you!

**Comment by dsjstc** [comment]
Alternatively, it'd be great to have a way to separate the interactive plots from the parts that don't use ipython-- I'm right at this moment trying to create a  non-interactive batch process that generates and stores shap values.

**Comment by IvanUkhov** [comment]
It has actually been fixed in this commit:

https://github.com/slundberg/shap/commit/52052d67b899761c03396cd5f8f53ac8446e4de2

The problem should be gone in the next release.
