### ISSUE TITLE
Plans for PartitionExplainer

### ISSUE THREAD

**Issue by AnnaGierlak** [shap/shap#1826]
Hi,

When using PartitionExplainer, I get the following warning:
`explainers.Partition is still in an alpha state, so use with caution...`
Are there any plans for further development of this explainer?

And is it possible to limit the computation of Owen values only to some level of the clustering dendrogram? I don't need to know the impact of all single features used in a model, I'm only interested in total credits assigned to specific groups. On the example from here: https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/model_agnostic/Simple%20Boston%20Demo.html, complete clustering looks like this:
![obraz](https://user-images.githubusercontent.com/32520597/108356137-0aa8fe80-71ec-11eb-9867-d80d1968e0fc.png)
But suppose I'd like to cut this tree:
![obraz](https://user-images.githubusercontent.com/32520597/108356322-4cd24000-71ec-11eb-9f75-c4b8f139a998.png)
and compute the Owen values for these 5 coalitions. As I understand (please correct me if I'm wrong), credits are computed recursively starting from the top of dendrogram and moving downward. So is there a way to stop the algorithm at selected level and obtain values for coalitions rather than particular features, in order to decrease the time of computations?

**Comment by slundberg** [comment]
Hey! We are working actively on this explainer right now (largely focused on the text/image applications). In fact that warning just got taken off this week :)

As for early stopping, that is possible by setting any clusters distance (height on those plots) to a negative value. That will stop the Partition explainer from going down into those branches. The credit will then be lowered down onto all the leaf nodes in that group for the .values array and left at the internal node for the .hierarchical_values array (those are both properties of the returned explanation object).

If you do this it would be great to share a NB in the docs so others can benefit!
