### ISSUE TITLE
SHAP to explain group fairness disparity

### ISSUE THREAD

**Issue by arinath** [shap/shap#1846]
Hi Everyone,

**Sorry if this is too verbose and confusing...**

We are trying to compute the group fairness disparity at two levels in the UCI adult income dataset conditioned on the protected attribute **gender**.
1- Overall disparity between the outcomes for female - male
2- Individual contributions of features towards the overall disparity in 1 between the outcomes for female - male

For 1, We are using the Equality of Opportunity metric. Not sure if we're doing it right. We are calculating the TPR for female and male subgroups using the SHAP values for the gender feature given the prediction was true and the ground truth (target label) was true for the respective subgroups.

Sum of (TPR) shap values for female: 0.8433953656391471
Sum of (TPR) shap values for male: 0.7795657153434582
Overall Equality of Opportunity Difference by protected attribute:
Sum of (TPR) shap values for female - Sum of (TPR) shap values for male = 0.06382965029568888

For 2, also using the Equality of Opportunity metric. We are calculating the TPR **contributions** for every feature for the female and male subgroups using the SHAP values for the gender feature given the prediction was true and the ground truth (target label) was true for the respective subgroups.

We are getting TPRs for some of the features > 1. Which is expected per our approach as there are negative and positive values that when summed might result in smaller denominator. 

Sum of shap values True Positives for female and feature relationship=Not-in-family: 0.4512588840000001
Sum of shap values True Positives for male and feature relationship=Not-in-family: 0.5057941069999995
Sum of shap values Positives for female and feature relationship=Not-in-family: 0.014189712000000063
Sum of shap values Positives for male and feature relationship=Not-in-family: -5.1852701539999995
TPR for female relationship=Not-in-family 31.801835301519727
TPR for male relationship=Not-in-family -0.09754440790511598
 
The negative value is concerning, although we understand these are not really TPR but contributions of the feature towards the overall TPR by feature (calculated just as we would calculate TPR). I would appreciate if someone could validate our approach.

Thanks very much!

**Comment by arinath** [comment]
I think this post is more appropriate in the discussions section. Hence, closing as this was not an issue.

**Comment by sunshinejnjn** [comment]
Hi. May I ask what kind of model are you using (to shap with)?

**Comment by arinath** [comment]
> Hi. May I ask what kind of model are you using (to shap with)?

Logistic Regression classifier
