### ISSUE TITLE
python 3.9 installation error on shap

### ISSUE THREAD

**Issue by zmuumz** [shap/shap#1854]
C:\Python\Python39>pip install shap
Collecting shap
  Using cached shap-0.39.0.tar.gz (356 kB)
Requirement already satisfied: numpy in c:\python\python39\lib\site-packages (from shap) (1.19.5)
Requirement already satisfied: scipy in c:\python\python39\lib\site-packages (from shap) (1.6.0)
Requirement already satisfied: scikit-learn in c:\python\python39\lib\site-packages (from shap) (0.24.1)
Requirement already satisfied: pandas in c:\python\python39\lib\site-packages (from shap) (1.2.0)
Collecting tqdm>4.25.0
  Using cached tqdm-4.58.0-py2.py3-none-any.whl (73 kB)
Collecting slicer==0.0.7
  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)
Collecting numba
  Using cached numba-0.51.2.tar.gz (2.1 MB)
Collecting cloudpickle
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
Requirement already satisfied: setuptools in c:\python\python39\lib\site-packages (from numba->shap) (49.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\python\python39\lib\site-packages (from pandas->shap) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\python\python39\lib\site-packages (from pandas->shap) (2020.5)
Requirement already satisfied: six>=1.5 in c:\python\python39\lib\site-packages (from python-dateutil>=2.7.3->pandas->shap) (1.15.0)
Requirement already satisfied: joblib>=0.11 in c:\python\python39\lib\site-packages (from scikit-learn->shap) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\python\python39\lib\site-packages (from scikit-learn->shap) (2.1.0)
Using legacy 'setup.py install' for shap, since package 'wheel' is not installed.
Using legacy 'setup.py install' for numba, since package 'wheel' is not installed.
Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
Installing collected packages: llvmlite, tqdm, slicer, numba, cloudpickle, shap
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zmuum\\AppData\\Local\\Temp\\pip-install-rn_73cgm\\llvmlite_25aae9e5abee49e6906a036fa85b1d93\\setup.py'"'"'; __file__='"'"'C:\\Users\\zmuum\\AppData\\Local\\Temp\\pip-install-rn_73cgm\\llvmlite_25aae9e5abee49e6906a036fa85b1d93\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zmuum\AppData\Local\Temp\pip-record-9844vcr9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python39\Include\llvmlite'
         cwd: C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\
    Complete output (27 lines):
    running install
    running build
    got version from file C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    c:\python\python39\python.exe C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\ffi\build.py
    Trying generator 'Visual Studio 15 2017 Win64'
    Traceback (most recent call last):
      File "C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\ffi\build.py", line 191, in <module>
        main()
      File "C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\ffi\build.py", line 179, in main
        main_win32()
      File "C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\zmuum\AppData\Local\Temp\pip-install-rn_73cgm\llvmlite_25aae9e5abee49e6906a036fa85b1d93\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "c:\python\python39\lib\subprocess.py", line 368, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\python\python39\lib\subprocess.py", line 349, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\python\python39\lib\subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\python\python39\lib\subprocess.py", line 1416, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'c:\\python\\python39\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zmuum\\AppData\\Local\\Temp\\pip-install-rn_73cgm\\llvmlite_25aae9e5abee49e6906a036fa85b1d93\\setup.py'"'"'; __file__='"'"'C:\\Users\\zmuum\\AppData\\Local\\Temp\\pip-install-rn_73cgm\\llvmlite_25aae9e5abee49e6906a036fa85b1d93\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\zmuum\AppData\Local\Temp\pip-record-9844vcr9\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python\python39\Include\llvmlite' Check the logs for full command output.
WARNING: You are using pip version 20.3.4; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\python\python39\python.exe -m pip install --upgrade pip' command.

**Comment by Bougeant** [comment]
Please try again: `numba` and `llvmlite` should now have support for Python 3.9

**Comment by apnevmatikakis** [comment]
Even though the two packages mentioned above install just fine in Python 3.9.5, sahp still fails to be installed:

Collecting shap
  Using cached shap-0.39.0.tar.gz (356 kB)
Requirement already satisfied: numpy in d:\venv\ml-service\lib\site-packages (from shap) (1.20.3)
Requirement already satisfied: scipy in d:\venv\ml-service\lib\site-packages (from shap) (1.6.3)
Requirement already satisfied: scikit-learn in d:\venv\ml-service\lib\site-packages (from shap) (0.24.2)
Requirement already satisfied: pandas in d:\venv\ml-service\lib\site-packages (from shap) (1.2.4)
Requirement already satisfied: tqdm>4.25.0 in d:\venv\ml-service\lib\site-packages (from shap) (4.61.0)
Collecting slicer==0.0.7
  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)
Requirement already satisfied: numba in d:\venv\ml-service\lib\site-packages (from shap) (0.53.1)
Collecting cloudpickle
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in d:\venv\ml-service\lib\site-packages (from numba->shap) (0.36.0)
Requirement already satisfied: setuptools in d:\venv\ml-service\lib\site-packages (from numba->shap) (57.0.0)
Requirement already satisfied: pytz>=2017.3 in d:\venv\ml-service\lib\site-packages (from pandas->shap) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in d:\venv\ml-service\lib\site-packages (from pandas->shap) (2.8.1)
Requirement already satisfied: six>=1.5 in d:\venv\ml-service\lib\site-packages (from python-dateutil>=2.7.3->pandas->shap) (1.16.0)
Requirement already satisfied: joblib>=0.11 in d:\venv\ml-service\lib\site-packages (from scikit-learn->shap) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\venv\ml-service\lib\site-packages (from scikit-learn->shap) (2.1.0)
Using legacy 'setup.py install' for shap, since package 'wheel' is not installed.
Installing collected packages: slicer, cloudpickle, shap
  Attempting uninstall: slicer
    Found existing installation: slicer 0.0.3
    Uninstalling slicer-0.0.3:
      Successfully uninstalled slicer-0.0.3
    Running setup.py install for shap: started
    Running setup.py install for shap: finished with status 'error'

    ERROR: Command errored out with exit status 1:
     command: 'D:\venv\ML-Service\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\InnovationSprint\\AppData\\Local\\Temp\\pip-install-961ml_bt\\shap_f8d468ec6c734c59980152a703ae5cd1\\setup.py'"'"'; __file__='"'"'C:\\Users\\InnovationSprint\\AppData\\Local\\Temp\\pip-install-961ml_bt\\shap_f8d468ec6c734c59980152a703ae5cd1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\InnovationSprint\AppData\Local\Temp\pip-record-5n537b86\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\venv\ML-Service\include\site\python3.9\shap'
         cwd: C:\Users\InnovationSprint\AppData\Local\Temp\pip-install-961ml_bt\shap_f8d468ec6c734c59980152a703ae5cd1\
    Complete output (116 lines):
    The nvcc binary could not be located in your $PATH. Either  add it to your path, or set $CUDAHOME to enable CUDA
    Error building cuda module: TypeError('cannot unpack non-iterable NoneType object')
    WARNING: Could not compile cuda extensions
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\shap
    copying shap\datasets.py -> build\lib.win-amd64-3.9\shap
    copying shap\links.py -> build\lib.win-amd64-3.9\shap
    copying shap\_explanation.py -> build\lib.win-amd64-3.9\shap
    copying shap\_serializable.py -> build\lib.win-amd64-3.9\shap
    copying shap\__init__.py -> build\lib.win-amd64-3.9\shap
    creating build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\mimic.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\pytree.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\tf_utils.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_additive.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_exact.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_explainer.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_gpu_tree.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_gradient.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_kernel.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_linear.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_partition.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_permutation.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_sampling.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\_tree.py -> build\lib.win-amd64-3.9\shap\explainers
    copying shap\explainers\__init__.py -> build\lib.win-amd64-3.9\shap\explainers
    creating build\lib.win-amd64-3.9\shap\explainers\other
    copying shap\explainers\other\_coefficent.py -> build\lib.win-amd64-3.9\shap\explainers\other
    copying shap\explainers\other\_lime.py -> build\lib.win-amd64-3.9\shap\explainers\other
    copying shap\explainers\other\_maple.py -> build\lib.win-amd64-3.9\shap\explainers\other
    copying shap\explainers\other\_random.py -> build\lib.win-amd64-3.9\shap\explainers\other
    copying shap\explainers\other\_treegain.py -> build\lib.win-amd64-3.9\shap\explainers\other
    copying shap\explainers\other\__init__.py -> build\lib.win-amd64-3.9\shap\explainers\other
    creating build\lib.win-amd64-3.9\shap\explainers\_deep
    copying shap\explainers\_deep\deep_pytorch.py -> build\lib.win-amd64-3.9\shap\explainers\_deep
    copying shap\explainers\_deep\deep_tf.py -> build\lib.win-amd64-3.9\shap\explainers\_deep
    copying shap\explainers\_deep\__init__.py -> build\lib.win-amd64-3.9\shap\explainers\_deep
    creating build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_bar.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_beeswarm.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_decision.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_embedding.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_force.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_force_matplotlib.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_group_difference.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_heatmap.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_image.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_labels.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_monitoring.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_partial_dependence.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_scatter.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_text.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_utils.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_violin.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\_waterfall.py -> build\lib.win-amd64-3.9\shap\plots
    copying shap\plots\__init__.py -> build\lib.win-amd64-3.9\shap\plots
    creating build\lib.win-amd64-3.9\shap\plots\colors
    copying shap\plots\colors\_colorconv.py -> build\lib.win-amd64-3.9\shap\plots\colors
    copying shap\plots\colors\_colors.py -> build\lib.win-amd64-3.9\shap\plots\colors
    copying shap\plots\colors\__init__.py -> build\lib.win-amd64-3.9\shap\plots\colors
    creating build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\experiments.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\framework.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\measures.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\methods.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\metrics.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\models.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\perturbation.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\plots.py -> build\lib.win-amd64-3.9\shap\benchmark
    copying shap\benchmark\__init__.py -> build\lib.win-amd64-3.9\shap\benchmark
    creating build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_composite.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_fixed.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_fixed_composite.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_image.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_masker.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_output_composite.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_tabular.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\_text.py -> build\lib.win-amd64-3.9\shap\maskers
    copying shap\maskers\__init__.py -> build\lib.win-amd64-3.9\shap\maskers
    creating build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\image.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\transformers.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\_clustering.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\_general.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\_keras.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\_legacy.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\_masked_model.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\_show_progress.py -> build\lib.win-amd64-3.9\shap\utils
    copying shap\utils\__init__.py -> build\lib.win-amd64-3.9\shap\utils
    creating build\lib.win-amd64-3.9\shap\actions
    copying shap\actions\_action.py -> build\lib.win-amd64-3.9\shap\actions
    copying shap\actions\_optimizer.py -> build\lib.win-amd64-3.9\shap\actions
    copying shap\actions\__init__.py -> build\lib.win-amd64-3.9\shap\actions
    creating build\lib.win-amd64-3.9\shap\models
    copying shap\models\_model.py -> build\lib.win-amd64-3.9\shap\models
    copying shap\models\_teacher_forcing.py -> build\lib.win-amd64-3.9\shap\models
    copying shap\models\_text_generation.py -> build\lib.win-amd64-3.9\shap\models
    copying shap\models\_topk_lm.py -> build\lib.win-amd64-3.9\shap\models
    copying shap\models\_transformers_pipeline.py -> build\lib.win-amd64-3.9\shap\models
    copying shap\models\__init__.py -> build\lib.win-amd64-3.9\shap\models
    creating build\lib.win-amd64-3.9\shap\plots\resources
    copying shap\plots\resources\bundle.js -> build\lib.win-amd64-3.9\shap\plots\resources
    copying shap\plots\resources\logoSmallGray.png -> build\lib.win-amd64-3.9\shap\plots\resources
    creating build\lib.win-amd64-3.9\shap\cext
    copying shap\cext\tree_shap.h -> build\lib.win-amd64-3.9\shap\cext
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    numpy.get_include() D:\venv\ML-Service\lib\site-packages\numpy\core\include
    building 'shap._cext' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\venv\ML-Service\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\InnovationSprint\\AppData\\Local\\Temp\\pip-install-961ml_bt\\shap_f8d468ec6c734c59980152a703ae5cd1\\setup.py'"'"'; __file__='"'"'C:\\Users\\InnovationSprint\\AppData\\Local\\Temp\\pip-install-961ml_bt\\shap_f8d468ec6c734c59980152a703ae5cd1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\InnovationSprint\AppData\Local\Temp\pip-record-5n537b86\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\venv\ML-Service\include\site\python3.9\shap' Check the logs for full command output.

**Comment by ibrahimshibani** [comment]
This helped me resolve the issue, some core python 3.9  libraries were missing:

> sudo apt-get install python3.9-dev
