### ISSUE TITLE
common module not found

### ISSUE THREAD

**Issue by bezhvin** [shap/shap#1858]
Hi,
I am using shap version '0.38.1' and I cannot see the "common" module there. my goal is to use the densdata module from common. Is it removed from the latest version? if so is there any replacement?
Regards,
Reza

**Comment by bezhvin** [comment]
Never mind... apparently it is moved to shap.utils._legacy

**Comment by jonnor** [comment]
Good that you found it!

This issue can be closed. CC @slundberg
