### ISSUE TITLE
how to get an overall attribution from a KernelExplainer

### ISSUE THREAD

**Issue by ajbanegas** [shap/shap#1871]
Hi, I'm using a KernelExplainer to interprete my model and I'd like to display why the explainer sorted the features in that order. For example, some kind of overall score that justifies, in a numerical way, why each feature is ranked as it is.
To explain myself I attach and example of what I want to achieve. It's the explanation of a dataset made of 5 variables (A-E). The numbers between square brackets would be the overall attribution of each property.

![ANN-reg-lineal_regresion-lineal_v1_500_0 01_shapley](https://user-images.githubusercontent.com/67786260/110640655-5b8b9180-81b1-11eb-8192-97fec09c51f0.png)

As I work with a KernelExplainer, I only get back the shap values for every feature along the test samples. Thus I also wonder if I could calculate the overall score myself and how (mean, std, variance, sum... of the individual shapley value for every feature)?

Thanks for your help.

**Comment by gianmarco-terrones** [comment]
If you use `shap.summary_plot()` with `plot_type="bar"`, it will order features based on the mean absolute SHAP value. This is the mean absolute marginal contribution of a property to the difference between a prediction and the mean model prediction. The ordering of the bar plot will be the same as the ordering of the dot plot. So you can justify the feature ranking by saying that features with larger mean absolute SHAP values are, from the perspective of your model, more influential in shifting a prediction one way or the other.

Regarding calculating means and standard deviations by yourself, I'd imagine that you can take the SHAP values output by something like shap_values = e.shap_values(X_test), and do `numpy.mean` or `numpy.std` while specifying the axis that corresponds to a given feature. For example, if you have a feature that is "Income" that is in the first column, I'd think the first entry of `numpy.mean` of the shap_values with `axis=1` would give you the mean SHAP value of income.
