### ISSUE TITLE
MemoryError: Unable to allocate 184. GiB for an array with shape (24759190848,) and data type float64

### ISSUE THREAD

**Issue by caiquanyou** [shap/shap#1879]
I  use TreeExplainer and calculate the shap value and crash;
my training dataset is (22102,5000) How could I use shap on my dataset ?

**Comment by caiquanyou** [comment]
the tree model is LightGBM

**Comment by msseibel** [comment]
I don't think that you need the whole dataset.
E.g. [in the docs](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/tree_based_models/Explaining%20the%20Loss%20of%20a%20Model.html?highlight=TreeExplainer) only 10 samples are used.

**Comment by caiquanyou** [comment]
@msseibel 
> I don't think that you need the whole dataset.
> E.g. [in the docs](https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/tree_based_models/Explaining%20the%20Loss%20of%20a%20Model.html?highlight=TreeExplainer) only 10 samples are used.
But my model is multiclass of 224;
10 samples enough explain the model? Any suggest to do some explaination on multiclassification model?
Thanks!
