### ISSUE TITLE
AssertionError: ReverseV2 is not known to be either linear or a supported non-linearity

### ISSUE THREAD

**Issue by makcedward** [shap/shap#188]
I built an model by using Keras with Tensorflow backend. However, it thrown an error. So I try to figure out the root cause. 

- Download and rerun the [sample Keras LSTM notebook](https://github.com/slundberg/shap/blob/master/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.ipynb) to isolate environment issue. So assuming environment is ok
- Current SHAP still support Keras 2.1.x. Although there is warning that SHAP support Keras >= 2.2.0, it seems that can still use SHAP with Keras 2.1.x by running sample notebook
- Comparing the difference between sample notebook Keras model and my model. The sample one is a Sequential model (<keras.models.Sequential at 0x7fd2d83706a0>) when mine is Keras's engine training model (<keras.engine.training.Model at 0x7f8f6e660cc0>). 

Added sample code in [github repo](https://github.com/makcedward/nlp/blob/master/sample/nlp-model_interpretation-201808.ipynb). Please kindly advise which part do I miss?

```
AssertionError                            Traceback (most recent call last)
<ipython-input-10-dba880f8c9e3> in <module>()
----> 1 explainer = shap.DeepExplainer(pipeline.model, encoded_x_train[:10])
      2 shap_values = explainer.shap_values(encoded_x_test[:1])

/anaconda/envs/py35/lib/python3.5/site-packages/shap/explainers/deep.py in __init__(self, model, data, session)
    170                     assert self.num_variable_inputs(op) == 1, "GatherV2 can only have one varying input!"
    171                 else:
--> 172                     assert False, op.type + " is not known to be either linear or a supported non-linearity!"
    173 
    174         if not self.multi_output:

AssertionError: ReverseV2 is not known to be either linear or a supported non-linearity!
```

**Comment by slundberg** [comment]
The problem is that we explicitly list in DeepExplainer which components are supported to ensure we don't give bad explanations when a new basic component is used that we have not tested. `ReverseV2` is a very simple operation that just reverses an axis. This is easy to explain as long as you are not choosing the axis to reverse based on your input data. So I just added `ReverseV2` to the list of supported ops along with a check to make sure the axis does not depend on the inputs. I'll push that here soon, if you find other ops that not yet supported just post them. DeepExplainer is new as of this July so we are still adding in basic TF ops as they come up.

**Comment by makcedward** [comment]
@slundberg 
Thank you for your quick response. I did a quick try by comment out the checking. At least it can be run and will further evaluate whether result is expected or not .

**Comment by slundberg** [comment]
Great. You can also just add things to the `guaranteed_linearities` list
and it will assume they don't need any special handling. If you find
anything unexpected let us know. We are also working to test this out on
some LSTM models, and are keeping a list of needed improvements.

**Comment by mdaniluk** [comment]
Is it possible to support  `Pad` operation? I have following error during training Resnet50 model:
`AssertionError: Pad is not known to be either linear or a supported non-linearity!`

**Comment by slundberg** [comment]
@mdaniluk should be supported now as of 0.22

**Comment by mdaniluk** [comment]
@slundberg Thank you. But still Resnet doesn't work - `FusedBatchNorm is not known to be either linear or a supported non-linearity` 

The same with `AvgPool`

**Comment by makcedward** [comment]
@slundberg 
Thanks for update. 
I upgraded to 0.22.3 version and rerun the same code. The ReverseV2 issue gone but hitting other supporting type issues which relates to missing "TensorArrayGatherV3", "Max", "TensorArraySizeV3" and "Range".

I add those support type to guaranteed_linearities in my local for temporarily solution. Please kindly review whether SHAP can extend the support to those op.

For others, you may add those missing type by updating the following code. But please remind that it is just a temp workaround.

1. edit "shap/explainers/deep.py"
2. add missing type to "guranteed_linearities" (for version 0.22.3, it is line 32)

**Comment by slundberg** [comment]
@makcedward thanks! I had to spend some time fixing and refactoring some things after TF 1.10 but that's done now and I've added those ops to the "to-add" list. Should get them in soon.
