### ISSUE TITLE
LinearExplainer has wrong dimensions for self.coef

### ISSUE THREAD

**Issue by jmschrei** [shap/shap#189]
LinearExplainer fails when I pass in a scikit-learn LogisticRegression (or LogisticRegressionCV). I suspect that the issue is that the coefficients are unintuitively stored as a 2D array instead of a 1D one.

```python
model = LogisticRegression().fit(X[:100], y[:100])
print model.coef_
# [[-0.06917193  0.19454987  1.07939799  0.05860105 -0.77803874]]
```

The error that I get is:

```
ValueError                                Traceback (most recent call last)
<ipython-input-20-54090bf30c27> in <module>()
----> 1 shap.LinearExplainer(model, X).shap_values(X)

/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/shap/explainers/linear.pyc in __init__(self, model, data, nsamples, feature_dependence)
     70         # if needed, estimate the transform matrices
     71         if feature_dependence == "correlation":
---> 72             mean_transform, x_transform = self._estimate_transforms(nsamples)
     73             self.mean_transformed = np.matmul(mean_transform, self.mean)
     74             self.x_transform = x_transform

/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/shap/explainers/linear.pyc in _estimate_transforms(self, nsamples)
    122 
    123                 # + coef @ (Q(bar(Sui)) - Q(bar(S)))
--> 124                 mean_transform[i, i] += self.coef[i]
    125 
    126                 # + coef @ R(Sui)

ValueError: setting an array element with a sequence.
```

If I unravel the coef array I can get it to work:

```python
model.coef_ = model.coef_[0]
shap.LinearExplainer(model, X).shap_values(X)
# many numbers
```

**Comment by slundberg** [comment]
Thanks! We could treat a one column 2D matrix as a multi-class problem with one class (i.e. return a list of explanations with one array) or auto-unwrap it and treat it as just a single output. Any thoughts?

**Comment by jmschrei** [comment]
I think the first one is better. The scikit-learn people tried supporting different formats for binary classification and for univariate inputs for a while but it was a pain to maintain.

**Comment by slundberg** [comment]
If I get a chance I'll add something to deal with multi-class then. It will require adding an extra dimension to the transform tensors and making sure everything aligns correctly. (Essentially treating everything as multi-class)

**Comment by jmschrei** [comment]
Sounds like a reasonable thing to do long term. Alternatively, only allow binary classification and raise an error if a matrix of coefficients (with more than one row) are passed in.
