### ISSUE TITLE
stacked bar plotting error for multi-class model

### ISSUE THREAD

**Issue by staubda** [shap/shap#1906]
I've trained a multi-class XGBoost model like the following:
```
import xgboost as xgb

# Get data
df_train_X = ... # 10000 x 82 dataframe
df_train_y = ... # 10000 x 1 dataframe

# Train using sklearn API
params = {
    'n_estimators': 500,
    'booster': 'gbtree',
    'objective': 'multi:softprob',
    'num_class': 31,
    ...
}
model = xgb.XGBClassifier(**params).fit(X=df_train_X, y=df_train_y)
```
The training data has 10,000 instances with 82 features each, and the target variable has 31 different classes.

I'd like to produce a stacked bar plot showing overall feature importance like [this example](https://github.com/slundberg/shap/issues/367). However, when i try to create the plot like
```
import shap

explainer = shap.TreeExplainer(model)
shap_values = explainer(df_train_X)
shap.summary_plot(shap_values, feature_names=df_train_X.columns, plot_type="bar")
```
I instead get a beeswarm interaction plot like
![Screen Shot 2021-03-25 at 3 38 04 PM](https://user-images.githubusercontent.com/6806542/112552465-1ace7380-8d80-11eb-885a-8814d0f05ec6.png)

When i try to produce the plot like
```
shap.plots.bar(shap_values)
```
I get the following error:
```
IndexError                                Traceback (most recent call last)
<ipython-input-42-8c051e58575e> in <module>()
----> 1 shap.plots.bar(shap_values_tst)

/home/default_user/.conda/envs/user/lib/python3.7/site-packages/shap/plots/_bar.py in bar(shap_values, max_display, order, clustering, clustering_cutoff, merge_cohorts, show_data, show)
    157     for pos,inds in enumerate(orig_inds):
    158         if len(inds) == 1:
--> 159             feature_names_new.append(feature_names[inds[0]])
    160         else:
    161             full_print = " + ".join([feature_names[i] for i in inds])

IndexError: list index out of range
```

I am able to produce a normal looking bar plot for a single class like, e.g., the following:
```
class_ind = 5
shap.summary_plot(shap_values[:, :, class_ind], feature_names=df_train_X.columns, plot_type="bar")
```

Note: The shape of `shap_values` is `N_instance X N_feature X N_class`, whereas I was expecting `N_class X N_instance X N_feature` from the docs.

I'm using:
 - python == 3.7
 - shap == 0.39.0

Thanks for any help!

**Comment by staubda** [comment]
Update: I was able to get `shap.summary_plot` to work by passing in the `shap_values` like:
```
shap.summary_plot(
    [shap_values[:, :, class_ind].values for class_ind in range(shap_values.shape[-1])],
    feature_names=df_train_X.columns,
    plot_type="bar"
)
```
Kind of hacky but it gets the job done.

**Comment by asuccurro** [comment]
Hey @staubda,

thanks to your issue I could figure out my problem is also related to multi-class (random forest) model. 

Also, I thought to share what I found out after reading other various posts in case it is useful. I get different behavior with these two objects

`shap_obj = explainer(X1_train)`
`shap_values = explainer.shap_values(X1_train)`

And this is the plots I get with the two different objects

![Screenshot 2021-06-08 at 11-14-55 CITIID - Jupyter Notebook](https://user-images.githubusercontent.com/2011939/121159529-8e463400-c84b-11eb-8bf8-bf8b4c07d138.png)

![Screenshot 2021-06-08 at 11-14-44 CITIID - Jupyter Notebook](https://user-images.githubusercontent.com/2011939/121159571-956d4200-c84b-11eb-871d-f216a1e070e5.png)

I would expect shap_obj.values to be equivalent to shap_values but it isn't (I started using shap yesterday, still digging)

Cheers,
Antonella
