### ISSUE TITLE
TypeError: Tensors are unhashable. (KerasTensor(type_spec=TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"))Instead, use tensor.ref() as the key.

### ISSUE THREAD

**Issue by TannerGilbert** [shap/shap#1907]
When running the [GradientExplainer example](https://slundberg.github.io/shap/notebooks/gradient_explainer/Explain%20an%20Intermediate%20Layer%20of%20VGG16%20on%20ImageNet.html) I'm getting:

```
TypeError: Tensors are unhashable. (KerasTensor(type_spec=TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"))Instead, use tensor.ref() as the key.
```

when running:

```python
e = shap.GradientExplainer((model.layers[7].input, model.layers[-1].output), map2layer(preprocess_input(X.copy()), 7))
```

**Comment by RobMort** [comment]
I am having the same issue, but with the DeepExplainer. I am using multiple inputs and one output.

**Comment by bartenbach** [comment]
Looks like the Jupyter notebooks need to be updated?

**Comment by alee103** [comment]
I'm also running into this error. Has anyone successfully resolved this? I tried adding code (below) I found on another forum in response to this question. The code did not resolve my error.

`import tensorflow.compat.v1.keras.backend as K
import tensorflow as tf
tf.compat.v1.disable_eager_execution()`

**Comment by Ficiali** [comment]
> I'm also running into this error. Has anyone successfully resolved this? I tried adding code (below) I found on another forum in response to this question. The code did not resolve my error.
> 
> `import tensorflow.compat.v1.keras.backend as K import tensorflow as tf tf.compat.v1.disable_eager_execution()`

pip install tensorflow-gpu

**Comment by StarPlatinum0** [comment]
> I'm also running into this error. Has anyone successfully resolved this? I tried adding code (below) I found on another forum in response to this question. The code did not resolve my error.
> 
> `import tensorflow.compat.v1.keras.backend as K import tensorflow as tf tf.compat.v1.disable_eager_execution()`

I just add the last two lines code and it works for me

**Comment by hannahbrown7** [comment]
I am getting this error too, using tensorflow version 2.7.0 and shap version 0.40.0, did anyone find a solution? The suggestion above did not work for me

**Comment by satkr7** [comment]
I am getting the same error on using DeepExplainer on a Keras Bi-LSTM+Attention Model.
`explainer = shap.DeepExplainer(model, x_train) 
shap_values = explainer.shap_values(x_test)`

TensorFlow version 2.4.0 / 2.7.0 / 2.8.0
shap version 0.40.0.

All the suggestions on StackOverflow didn't work for me. Let me know if anyone has any solution.

**Comment by his0car** [comment]
```
import tensorflow.compat.v1.keras.backend as K
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
```
This worked for me

**Comment by TannerGilbert** [comment]
> ```
> import tensorflow.compat.v1.keras.backend as K
> import tensorflow as tf
> tf.compat.v1.disable_eager_execution()
> ```
> 
> This worked for me

I tried it out, and it seems to work inside Google Colab, but the code takes much longer than expected. If anyone is interested, you can take a look at a simple example [here](https://github.com/TannerGilbert/Model-Interpretation/blob/master/Shap/gradient_explainer_example.ipynb).

**Comment by pandeyvaibhav** [comment]
> ```
> import tensorflow.compat.v1.keras.backend as K
> import tensorflow as tf
> tf.compat.v1.disable_eager_execution()
> ```
> 
> This worked for me

worked for me, after applying this suggestion. Although model seems to run slower after this.

**Comment by Addicted-to-coding** [comment]
I am facing the same error for:
SHAP Version: 0.41.0
TensorFlow Version: 2.12.0

Adding 
import tensorflow.compat.v1.keras.backend as K
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
does not work for me. Can someone please help?

**Comment by Eluzai** [comment]
I have the same error here. I am running the model on Jupyter notebook locally, i dont have GPU installed on my computer.

**Comment by his0car** [comment]
Can you make a minimally (not) working example of that notebook?

**Comment by mainguyenanhvu** [comment]
@Eluzai have you fixed it? I cannot change the code because it in a system. I only install packages to run it. 
My conda env:
 keras-2.13.1 tensorflow-2.13.0 pandas-1.5.3

Thank you very much.

**Comment by armlesscoder98** [comment]
import tensorflow.compat.v1.keras.backend as K
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

This is also worked for me! Just run this code snip, before training the model. 
Additional this I was using keras for construction of my model, but I changed it in tensorflow api.
