### ISSUE TITLE
Question: any plans on adding pyTorch compatibility for this tool?

### ISSUE THREAD

**Issue by shgidi** [shap/shap#191]

**Comment by slundberg** [comment]
I have thought about it. It would not be too hard I think for the GradientExplainer, but for DeepExplainer it would require building a custom back propagation graph just like we do for TensorFlow. If anyone is familiar with PyTorch models (I don't use them often) and willing to give either one a shot, that would be great!

**Comment by connortann** [comment]
Closed by #262
