### ISSUE TITLE
SHAP for multiple input multiple output problems (sensors selection for physics field decoder challange)

### ISSUE THREAD

**Issue by IDoytchinov** [shap/shap#1915]
Dear all, we are working on physics guided AI where we wish to use several sensors to decode a full aerodynamics field of interest (https://royalsocietypublishing.org/doi/10.1098/rspa.2020.0097). Our decoder works well. However, we wish to optimise the sensor placement that will have the best results for decoding the aerodynamic field.

This leaves us with let's say 5- 30 or 100 input to the decoder and several thousand or hundreds of thousands of outputs. I know that SHAP was designed to check several inputs to a single output. How can we apply SHAP to our problem when we want to optimise the overall (several thousand) output decoded field quality?

i.e. study which input sensor features are most important for the 'genera' field reconstruction (minimum error at all outputs together). Multiple inputs - multiple output SHAP.

If you have any ideas or have heard of such an application of SHAP please can you let us know!?

![image](https://user-images.githubusercontent.com/80845088/112969739-d52df400-914d-11eb-9df8-99a2fbde9e26.png)

Iordan Doytchinov, Ph.D.

Postdoctoral researcher and scientific collaborator 

Ecole Polytechnique Fédérale de Lausanne (EPFL)
EPFL – TOPO
Station 18 – Bâtiment GC C2 398

CH–1015 Lausanne

Office telephone: +41216939832
Personal mobile: +33699850592

iordan.doytchinov@epfl.ch
http://topo.epfl.ch/

**Comment by alielabridi** [comment]
I have worked on a similar problem. For a single output at least, you need to take into consideration that the input fields can be extremely correlated, which will may give misleading results using most of the approximation methods for the shapley values, as for example Kernel method assumes that the input are independent. One idea to explore is to cluster the inputs fields by correlation, and use it as contribution groups. (see https://arxiv.org/pdf/1903.10464.pdf)

**Comment by IDoytchinov** [comment]
Hello Ali, thanks for the feedback. This is an interesting paper. The question is what happens when we have multiple/many outputs that we have to get right? Best,

Iordan

**Comment by alielabridi** [comment]
Hi Iordan, I am not sure how to combine multiple outputs properly, sorry. Let me know if you find a solution to it.
