### ISSUE TITLE
Local shap on Isolation Forest

### ISSUE THREAD

**Issue by LNBaud** [shap/shap#1917]
Hello,
I am currently working on trying to use shap for local explanation of isolation forest.
I use Python 3.8.5
The code I have currently written to try and have the explanation of the prediction of a specific example (here the first one of our training dataset) is the following: 
> import shap
> from sklearn.ensemble import IsolationForest
>
> X, y = shap.datasets.boston()
> clf = IsolationForest().fit(X)
> explainer = shap.Explainer(clf)
> shap_values = explainer(X)
>
> shap.plots.waterfall(shap_values[0])

However I get the issue 

> Exception: waterfall_plot requires a scalar base_values of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.base_values[0], values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.base_values[0], values[0][0], X[0]).

I have dig into it and realize that shape_values.base_values is a 2 dimension array 
.base_values =
array([[11.96895553],
       [11.96895553], .....,
       [11.96895553],
       [11.96895553]])

While it should be a 1D array. I have currently tried replacing 
> shap_values.base_values =  shap_values.base_values[:,0]  
    
However I get the error :
> IndexError: too many indices for array

Would you have any idea of how to use local explanability method for isolation forest ?
Thanks a lot

**Comment by xm4ch1n3** [comment]
Try the following:

```python
X_, y_ = shap.datasets.boston()
model = IsolationForest()
model.fit(X_)

explainer = shap.TreeExplainer(model, data=X_) # data is required if you're using interventional feature_perturbation
# or
expainer = shap.Explainer(model, masker=X_) # masker required

# calculate shap with shap_values method
shapvs = explainer.shap_values(X_, check_additivity=True) # check should be default

# use the following function for waterfall
shap.plots._waterfall.waterfall_legacy(explainer.expected_value[0], shapvs[0], features=X_[0], feature_names=X_.columns)
```

**Comment by LNBaud** [comment]
Hello @leoentersthevoid ,
I replaced "explainer.expected_value[0]" by "explainer.expected_value" and "X_[0]" by "X_.iloc[0]" and it worked thanks !
However I don't really understand the output I'm get (see below)
Because since my model is an Isolation forest I expect to have out that are 1 or -1 (with an excepted value between theses 2). However I get values around 11. 
![image](https://user-images.githubusercontent.com/44223448/113296034-3e9e3600-92f9-11eb-8f33-dbb6cab3b391.png)

Would you understand why ? 

Thanks a lot,

**Comment by xm4ch1n3** [comment]
It's a very good question, and it has to do with the fact that you're not actually explaining the labels (ie. `{-1, 1}`).
You can find more about it by reading the following issue: #1152.

**Comment by LNBaud** [comment]
Thanks a lot, 
Since It is all good now I'm closing this issue
