### ISSUE TITLE
synth_data in KernelExplainer

### ISSUE THREAD

**Issue by augustinas1** [shap/shap#192]
Hi Scott,

I was looking through KernelExplainer code and had a question about synth_data generated in add_samples() method. Each synth_data entry is assigned the current feature value if the feature is included in the considered feature subset, or the background value if the feature is 'missing'. However, current features which are equal to the background dataset values (not included in the mask as they have no effect) are left to be zero in synth_data, as set during the initial allocation of the matrix. I thought that such features should be treated similarly to the 'missing' ones, i.e. have the same values as in the background dataset, or am I missing something obvious?

Thank you!

**Comment by slundberg** [comment]
@augustinas1 Wow, I can't believe I missed that. Often it is background values of 0 that trigger that pruning rule. But it can obviously happen for non-zero values as well, in which case this would be wrong.

Thanks for pointing it out! I'll push a fix here shortly.
