### ISSUE TITLE
conda lagging releases

### ISSUE THREAD

**Issue by ravwojdyla** [shap/shap#1922]
Thank you for all the great work! I noticed that conda is lagging a bit behind with the release. Is that a known issue? Currently latest version on conda is 0.37.0, while pypi: 0.39.0.

**Comment by martomor** [comment]
Same issue here! having a problem with  slicer-0.0.7.dist-info\\METADATA'  which is not allowing me to use pip.  Conda is the only way to go for now.

**Comment by mirekphd** [comment]
Also I noticed that when you compile `shap` from sources (for GPU) and checkout the latest tag `v0.39.0`, all methods (`pip show shap`, `conda list shap` and `python -c "import shap; print(shap.__version__)"`) show the obsolete version 0.37.

As a workaround that repaired the problem I simply deleted the obsolete version's dist-info folder:

```
# workaround #3:
# remove old version info to make pip show and conda list 
# display newly installed shap version corretly
ARG OLD_SHAP_VER=0.37.0
RUN rm -rf $PY_PKGS_FOLDER/shap-${OLD_SHAP_VER}.dist-info
```

Now `pip show shap` and `conda list shap` return correct (new) version, but `shap.__version__` still the old one (not really installed).

**Comment by ravwojdyla** [comment]
Conda now has release 0.39.0, closing. Thanks.
