### ISSUE TITLE
Explaining LSTM predictions

### ISSUE THREAD

**Issue by hmodea** [shap/shap#193]
Hello Scott,

I have an LSTM network that I need to explain its predictions, is this currently possible? I don't see an example implemented for Sequence models.

**Comment by slundberg** [comment]
This LSTM example is brand new, but take a look at:
https://github.com/slundberg/shap/blob/master/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.ipynb

**Comment by PierreBiousse** [comment]
Hello Scott,

Thanks a lot for your wonderful package with Shap !

I receive this message when running the LSTM example: 
"AssertionError: Minimum is not known to be either linear or a supported non-linearity! Please post this as a GitHub issue so Minimum can potentially be included in the list of supported ops."

Do you have an idea of how I could fix it ?

Best,

Pierre

**Comment by slundberg** [comment]
@pbcacao that will be fixed in v0.23.

**Comment by jlevy44** [comment]
Will these explanations also work for Pytorch LSTM models?

**Comment by slundberg** [comment]
@jlevy44 They should, but please keep in mind that DeepExplainer and GradientExplainer are approximations, and I have not done careful testing of them on LSTMs.

**Comment by jlevy44** [comment]
Thanks! Would I need to pad sentences/sequence to the longest sentence/sequence for lstm saliency for use with SHAP?

**Comment by slundberg** [comment]
You would unless you want to use a fixed zero background which could be set to the size of each sequence you are explaining.

**Comment by blaklodge** [comment]
Hello Scott,
I'm trying to use SHAP to explain predictions using a Keras/LSTM models. 
The input time-series data is (n_samples, n_timesteps, n_features).  The output is Dense(1), just predicting a number.

`explainer = shap.DeepExplainer((lime_model.layers[0].input, lime_model.layers[-1].output), train_x)`

This generates the error:
`AssertionError: The model output must be a vector or a single value!`

The last layer is a tensor, so I also tried using to get the shape of the output:
`explainer = shap.DeepExplainer((lime_model.layers[0].input, lime_model.layers[-1].output[2]), train_x)`

This resolves the error, but it results in the explainer having all zero values, so I'm not confident this is the correct way to solve this issue.

Do yo have any suggestions to get SHAP explaining Keras/LSTM single value predictions?

Thank you, Jason.

**Comment by slundberg** [comment]
@blaklodge can you print the shape of your last layer (lime_model.layers[-1].output)?

**Comment by blaklodge** [comment]
Hi Scott,
I was able to figure out the issue with my Keras/LSTM with one output (Dense(1)).  
I am now onto trying to get SHAP to work with my Keras/LSTM time-series model that outputs a sequence, Dense(3).

I get the same error:
`AssertionError: The model output must be a vector or a single value!`

when I print the output of the shape of the last layer, it is:
`(?, 12, 3)`

Here is the code where I am calling the shap.DeepExplainer:
`explainer = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), train_x)`

Thank you so much for your help!

**Comment by slundberg** [comment]
Right now DeepExplainer only handles vector outputs, so in order to use it you will need to reshape (or slice) the output vector to only have 1D output (2D when you consider the number of samples). Hope that's helpful!

**Comment by Noohshiny** [comment]
I have a TCN (Temporal convolutional network) code written on Tf2.0. I used both GradientExplainer and DeepExplainer and for both I am getting this error:

> AssertionError: <class 'model.TCN'> is not currently a supported model type!

Would you please help me what is the problem?

**Comment by magnusvage** [comment]
> Hi Scott,
> I was able to figure out the issue with my Keras/LSTM with one output (Dense(1)).

@blaklodge how did you solve it? I have the same output, and the same error.

Last layer output:

print(best_model.layers[-1].output)
Tensor("dense_32/BiasAdd:0", shape=(1, 1, 1), dtype=float32)

Error:

explainer = shap.DeepExplainer(best_model, X_tr)
AssertionError: The model output must be a vector or a single value!

@slundberg any insights perhaps?

**Comment by annezhangxue** [comment]
I have the same error when handling GRU/LSTM sequence to sequence prediction. The output is a sequence and I get the error:
AssertionError: The model output must be a vector or a single value!

How can I fix this please?

**Comment by reddy-sachin** [comment]
Did anyone find a solution here?
