### ISSUE TITLE
check_additivity not working properly

### ISSUE THREAD

**Issue by apachaves** [shap/shap#1934]
SHAP version 0.39.0. It seems check_additivity is not working to control this check, and when the additivity raises an error, it doesn't help to include check_additivity=False as an extra function parameter.

![image](https://user-images.githubusercontent.com/3076785/114534375-3aeea580-9c4f-11eb-9caf-53f9275279a7.png)

It seems weird because in the traceback I can see the check is there in the if condition, but I already played with many combinations of function parameters and in all of them setting check_additivity=False didn't make any difference and I am still getting an error.

Any ideas of what this might be?

**Comment by sronen1** [comment]
The reason is that you need to have check_additivity in the call to shap_values, not in the class initialization. 

 def shap_values(self, X, y=None, tree_limit=None, approximate=False, check_additivity=True, from_call=False):
