### ISSUE TITLE
DeepExplainer.shap_values equal zero - Explainability different than CNN prediction

### ISSUE THREAD

**Issue by skiiz** [shap/shap#1946]
Hello,
I am trying to explain a CNN with DeepExplainer. I get mainly two problems, that I would need your help on, please. It is for my thesis project and I am very stuck, I would be very grateful for any little help or directive.

1 - With regard to a specific class (class2) I get DeepExplainer.shap_values = 0 for all input images. I find this strange as shap_values different than zero are to be found with regard to all the classes for input images of any class.

2 - When explaining (calculating shap_values) for an input of class2, shap_values (blue and red pixels) are found in a another class, even if the CNN prediction is right and predicts class2 for this input.

The CNN is labelling a heat map dataset into 10 classes. I pass a background concatenated from samples from each class to the DeepExplainer. I tried with different background sizes and the problem still arise.

My images have this shape (754,27,3)
My background consequently have this shape (x10,754,27,3)
shap_values for one input image have this shape (10,754,27,3)
I assume then that shap_values[1, : , : , :] are related to the second class (class2), those are always 0.

In the figure there is three plots of calculated shap_values. I organize my shap_values in a (10,10,754,27,3), the first index is the input image 0 for an input of the first class, 1 for an input of second. Second index is the calculated shap_values with regard to what class.
Follows the code I am using to build the background, load it to explainer, calculating shapley values. 

Figure 1 : plot of shap_values for an input of class3 with regard to class2 (zero, same case for all inputs with regard to this class)
Figure 2 : plot of shap_values for an input of class2 with regard to class2 (zero)
Figure 3 : plot of shap_values for an input of class2 with regard to class1 (we can see values)
![Unbenannt1](https://user-images.githubusercontent.com/19363395/115376649-2b330c00-a1cf-11eb-821c-7791414deff4.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/19363395/115376652-2bcba280-a1cf-11eb-8531-915096e57a0b.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/19363395/115376655-2bcba280-a1cf-11eb-8240-72c4dba73fb5.PNG)

```python
colors = [] 
for l in np.linspace(1, 0, 100):
    colors.append((245 / 255, 39 / 255, 87 / 255, l))
for l in np.linspace(0, 1, 100):
    colors.append((24 / 255, 196 / 255, 93 / 255, l))
cm = matplotlib.colors.LinearSegmentedColormap.from_list("shap", colors


names = {0: 'class1', 1: 'class2', 2: 'class3', 3: 'class4', 4: 'class5', 5: 'class6',
         6: 'class7', 7: 'class8', 8: 'class9', 9: 'class10'}


#trainImages.shape=(x10, x1, 754, 27, 3)
background = np.concatenate((trainImages[:, :, :, :, :]))

e = shap.DeepExplainer(model, background)
shapvalues=np.empty((10,10,754,27,3))

for i in range(0, 10):
        thisImage = testImages[i, j, :, :, :]
        thisImage = thisImage.reshape(754,27,3)
        thisImage = thisImage.astype('float64')

        shap_values = e.shap_values(thisImage.reshape(1, 754,27, 3))
        shapvalues[i,:,:,:,:] = shap_values

        shap.image_plot(shap_values1, thisImage.reshape(1, 754,27, 3), show=False)
        plt.savefig('COB/30_1/plot'+str(i)+str(j), dpi = 1200)
```

**Comment by AndreasDahlNielsen** [comment]
Currently having a similar problem as this, however a bit more inconsistent. So we were running a 5 fold cross validation on our dataset, and found some of the folds just returned 0 across the board in shap values. This could show that SHAP has issues with some specific values. We are currently running some tests and trying to figure out why.

**Comment by skiiz** [comment]
@AndreasDahlNielsen Hi, I was able to get better values and no more (just) zeros. Just convert it to float64 using skimage. Or divide per 255 the integers values and change cells type to float64.

```
    thisImage=skimage.img_as_float64(thisImage)
    thisImage=thisImage.reshape(1,754,27,3)
    shap_values1 = e.shap_values(thisImage)
    shapvalues[i,:,:,:,:] = shap_values1
```
