### ISSUE TITLE
Easy way to jump between aggregate force plot and individual?

### ISSUE THREAD

**Issue by cbeauhilton** [shap/shap#195]
I have a dataset with ~2k patients, attempting to classify cancer subtype with GBM and explain/interrogate with SHAP. I have found it useful to jump between the aggregate force plot and individual force plots to look at trends and specifics. However, it is time consuming to find the exact row from the aggregate to call for the single force plot.

My workflow so far has been to find an interesting case in the aggregate plot using whatever ordering seems informative, write down identifying values, then reorder the aggregate by original ordering and seek out those identifying values (with tiny movements of the mouse!), usually with a need to reduce the range a few times to "zoom in," to find the right row.

Is there a better way to do this? Or any plans to make something along the lines of "double click to investigate" (i.e. a double click on a point in the aggregate force plot will generate the individual force plot)? Or is there a way to force it to show me row number of the instance of interest as I search the aggregate plot?

E.g. here's one ordered by similarity, but the "949" only refers to the current ordering:
![image](https://user-images.githubusercontent.com/34774299/43483266-1ff7500e-94d9-11e8-89e5-bd2b4c028fef.png)

Original ordering (i.e. to find numbers of individual cases to zoom in on)
![image](https://user-images.githubusercontent.com/34774299/43483251-0d812d0a-94d9-11e8-9959-e1130c5355f9.png)

**Comment by slundberg** [comment]
I can see why that would be a painful way of finding things! Directly connecting the plots would be a lot of work, but at least reporting the original index seems reasonable. I just added a very simple alert to the iml package in 0.6.2 that reports the original index when you click. You will have to upgrade iml by hand until I push a new shap release.

**Comment by cbeauhilton** [comment]
Thank you! That will be great. I'll have time to play with it next week.
