### ISSUE TITLE
SHAP for simple neural net taking extremely long time

### ISSUE THREAD

**Issue by ky66** [shap/shap#1955]
I want to run SHAP on a simple MLP and my matrix size is 60,000 samples with each having 1,800 features. Is SHAP even feasible for such a case given the matrix size? What are ways I can make SHAP run faster. Is there anyway to make SHAP parallel? 

Thanks

**Comment by antonwnk** [comment]
It's been a while since you asked so you might have already figured this out, but, the most straightforward way to make it parallel is running it on batches of instances. SHAP values are computed independently for each instance.
