### ISSUE TITLE
shap_values in DeepExplainer not returning an Explanation Object with data and base values

### ISSUE THREAD

**Issue by ky66** [shap/shap#1957]
I am trying DeepExplainer to interpret features of a simple neural network. 
I have the following:

background = x_train[np.random.choice(x_train.shape[0], 100, replace=False)]
e = shap.DeepExplainer(network, background)
shap_values = e.shap_values(x_test[0:5])

but the shap_values returned here is not an explanation object like all the other shap_values from TreeShap and all the other models. When I want to go to a beeswarm plot and I put:

shap.plots.beeswarm(shap_values)

I get:

UnboundLocalError: local variable 'values' referenced before assignment

because my shap_values are a list returned by DeepExplainer not a Explanation object like all the other models.

Is there anyway to fix this?

What should I do?

**Comment by ethankim00** [comment]
To workaround,  you can initialize a `shap._eplanation.Explainer` object with the shap value array stored in the list. You may have to calculate the base values manually using your model and data. After initializing this object should be able to be used in the plotting functions.
