### ISSUE TITLE
Dependent plot is not working on DeepExplainer 

### ISSUE THREAD

**Issue by connect2robiul** [shap/shap#1960]
I am trying to draw a relationship plot. I model using <<shap.DeepExplainer>> .   Here only the summary plot is working. I need to draw another plot especially the relationship plot between two features.  coherence matrix is added benefit for this if possible.

**Comment by ky66** [comment]
Yeah I was trying to do a beeswarm plot for the deepexplainer and it does not work for some reason either.

**Comment by connect2robiul** [comment]
> Yeah I was trying to do a beeswarm plot for the deepexplainer and it does not work for some reason either.

So what will be soln for that?

**Comment by ky66** [comment]
Found an example of beeswarm for deepexplainer. Follow this link (https://colab.research.google.com/github/kweinmeister/notebooks/blob/master/tensorflow-shap-college-debt.ipynb#scrollTo=WRNTlt1qkEAf)
