### ISSUE TITLE
Cannot install shap

### ISSUE THREAD

**Issue by merubhanot** [shap/shap#1963]
Not sure if this is specific to me, but I see some related issues (not exactly the same) in open issues, and though I would share mine since I wasn't able to troubleshoot.

I recently got a new linux machine running AL2, and cannot install shap. It's the only package I actively use that I cannot install. My setup uses homebrew + pip3 to install. The meat of the error seems to be the following:

```
Building wheels for collected packages: shap
  Building wheel for shap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kh40mvi9/shap_047ff4e867f447bcbc17976114cb6020/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kh40mvi9/shap_047ff4e867f447bcbc17976114cb6020/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xmwuhl71
       cwd: /tmp/pip-install-kh40mvi9/shap_047ff4e867f447bcbc17976114cb6020/
  Complete output (119 lines):
  The nvcc binary could not be located in your $PATH. Either  add it to your path, or set $CUDAHOME to enable CUDA
  Error building cuda module: TypeError('cannot unpack non-iterable NoneType object')
  WARNING: Could not compile cuda extensions
```

Would love any pointers/understanding of why this package alone isn't working? I've checked that cuda seems to be installled (pip3 install cuda yields already installed), but otherwise generally don't know a lot about these internals of the install process.

**Comment by chourroutm** [comment]
With `pip3 install cuda`, you checked whether the CUDA binding for Python is installed. But CUDA is some kind of toolkit over Nvidia GPU that needs to be installed too. Use your system package manager (e.g. `apt`) to install CUDA, such as: `sudo apt install nvidia-cuda-toolkit`
I also needed to install the C++ compiler: `sudo apt-get install g++`

**Comment by merubhanot** [comment]
My issue ended up being that the installer was looking for gcc-5 specifically, somewhere, but my machine had gcc and g++ installed (gcc-7 and g++-7 specifically). So somewhere in the install, shap was looking for gcc-5, but not finding that. Symlinking gcc-5 to gcc fixed the problem.
