### ISSUE TITLE
What's the format of saved model for Explainer()?

### ISSUE THREAD

**Issue by hangzhang23** [shap/shap#1967]
Hi, I tried to use joblib to load model, which I have trained from another project. But it seems that the Explainer(model) can't recognize the loaded model and analysis it.
The error is: 

Exception: The passed model is not callable and cannot be analyzed directly with the given masker! Model: KNeighborsClassifier(n_neighbors=2)

Could you please tell me which format of model should I use for saving? Thanks

**Comment by bh-sujit-ahirrao** [comment]
Could you tell me what was the solution?
