### ISSUE TITLE
AssertionError when only explaining one image

### ISSUE THREAD

**Issue by trannel** [shap/shap#1969]
When I try to explain only one image (a numpy array with the shape (1, x, x, 3), see the example) with shap it will throw the following error:
```
  File "/.../shap_test/venv/lib/python3.7/site-packages/shap/plots/_image.py", line 73, in image
    assert labels.shape[0] == shap_values[0].shape[0], "Labels must have same row count as shap_values arrays!"
AssertionError: Labels must have same row count as shap_values arrays!
```
Explaining 2 images works fine as the example below will show. The only difference is the value of the first parameter in the shape of the input, which determines how many images are in the array.

Example: First we run shap with an array filled with 2 images, which works as intended. Next we only use one image, which will fail and throw the mentioned error.
```python
import numpy as np
import shap
import random

def predict(imgs_np):
    rand = random.uniform(0, 1)
    result = [[rand, 1-rand]]
    # result = [[0.6, 0.4]]
    return result

def explain(imgs_np):
    masker = shap.maskers.Image("inpaint_telea", imgs_np[0].shape)
    explainer = shap.Explainer(predict, masker, output_names=["good", "bad"])
    shap_values = explainer(imgs_np, max_evals=4, batch_size=1, outputs=shap.Explanation.argsort.flip[:])
    shap.image_plot(shap_values)

if __name__ == '__main__':
    random.seed(0)
    np.random.seed(0)
    img_np_2 = np.random.rand(2, 5, 5, 3)
    explain(img_np_2)
    img_np_1 = np.random.rand(1, 5, 5, 3)
    explain(img_np_1)
```

The cause for this seems to be in shap/explainers/_explainer.py line 308-310. Removing these following lines will make the example also run for only one image:
```python
if isinstance(sliced_labels, np.ndarray) and len(sliced_labels.shape) == 2:
    if np.all(sliced_labels[0,:] == sliced_labels):
        sliced_labels = sliced_labels[0]
```

Removing those lines will also fix another issue. When I uncomment the commented out line in `predict` it will no longer throw the following error:
```
  File "/.../shap_test/venv/lib/python3.7/site-packages/shap/plots/_image.py", line 75, in image
    assert labels.shape[1] == len(shap_values), "Labels must have a column for each output in shap_values!"
IndexError: tuple index out of range
```
It seems like in cases where all predictions are the same, like when I only explain one image, shap will remove one dimension in the explainer, which will later cause errors while plotting.

Libraries installed:
shap 0.39.0
opencv_python 4.5.1.48
matplotlib 3.4.1
ipython 7.22.0

**Comment by joshfriesen** [comment]
I second this, I had a very similar problem that deleting the mentioned code in _explainer.py fixed.
