### ISSUE TITLE
Calling beeswarm multiple times on same shap_values produce different graphs

### ISSUE THREAD

**Issue by EtienneT** [shap/shap#1970]
I am using the latest version 0.39.0.

Using this code snippet:

```
import shap

explainer = shap.Explainer(model)
shap_values = explainer(X)
shap.plots.beeswarm(shap_values, max_display=15)
```
If I run the beeswarm cell in jupyter notebook again, I get a completely different graph.

Also, if I change the shap_values to a DataFrame, then plot a beeswarm and then start doing operations on the DataFrame, the data is completely different than if I don't run the beeswarm.  The beeswarm is modifying the numpy array somehow.

shap_values_df = pd.DataFrame(shap_values.values, columns=X.columns)

but if I call copy, then this problem for the dataframe doesn't occur:

shap_values_df = pd.DataFrame(shap_values.values.copy(), columns=X.columns)

**Comment by ky66** [comment]
have you tried putting a seed value for your model?

**Comment by EtienneT** [comment]
> have you tried putting a seed value for your model?

Just tried it by setting random_state in XGBClassifier, the bug still happens.

**Comment by EtienneT** [comment]
@ky66 

I think I identified the problem.  Using *= or += operator on a view of a numpy array actually modify the original object.  For example:
![image](https://user-images.githubusercontent.com/265924/117659835-6db28d80-b16a-11eb-822f-30ca1363d63f.png)

There's exactly this kind of code in beeswarm:

https://github.com/slundberg/shap/blob/9411b68e8057a6c6f3621765b89b24d82bee13d4/shap/plots/_beeswarm.py#L180-L181

values is assigned from shap_values.values

https://github.com/slundberg/shap/blob/9411b68e8057a6c6f3621765b89b24d82bee13d4/shap/plots/_beeswarm.py#L59

You would need a .copy() here on the numpy array to make sure you don't modify the original array.  Or you need to avoid using *= operators because they modify the original array and not the view.

**Comment by queise** [comment]
Yes, calling
```
shap.plots.beeswarm(shap_values)
```
changes the variable `shap_values`. 

It actually adds a new feature which is the "Sum of X other features" (which should have been only temporarly created for the plot), and then if you use again the same variable `shap_values` you have an additional wrong feature which also takes a wrong name.

![image](https://user-images.githubusercontent.com/8539732/123138302-27cd3280-d455-11eb-868f-4296e20bea6a.png)

The same does not happen in other similar cases like when using `shap.plots.waterfall`, which also creates the "Sum of X other features", but does not change the variable `shap_values`.

**Comment by rene-rex** [comment]
I ran into this problem, too. Is anyone working on this? @slundberg

**Comment by JulesCollenne** [comment]
Hey everyone, I solved this issue by changing line 57 from
`shap_exp = shap_values`
to
`shap_exp = copy.deepcopy(shap_values)`

Don't forget to import the library : 
`import copy`

I hope this doesn't create new bugs, it seems to work perfectly on my tests !

**Comment by JulesCollenne** [comment]
A simple change in beeswarm's code allowed me to solve this issue only by changing line 57 from
`shap_exp = shap_values`
to
`shap_exp = copy.deepcopy(shap_values)`

You only need to import the library : 
`import copy`

That's probably not the best solution since it use a lot of memory for nothing, but it works anyway.

Edit 1 :
Changing line 59 in _beeswarm.py
`values = shap_exp.values`
to
`values = shap_exp.values.copy()`
uses less memory for the same result.

Edit 2 : 
For whoever interested in where the values are getting changed, it's in this loop on line 269 of _beeswarm.py
`    if num_features < len(values[0]):
        num_cut = np.sum([len(orig_inds[feature_order[i]]) for i in range(num_features-1, len(values[0]))])
        values[:,feature_order[num_features-1]] = np.sum([values[:,feature_order[i]] for i in range(num_features-1, len(values[0]))], 0)`

**Comment by oustella** [comment]
Sorry just to report that this behavior persists in version 0.40. Using the temporary fix above by @Iacava works fine if one doesn't want to change the source code.
```
import copy
shap.plots.beeswarm(copy.deepcopy(shap_values))
```

**Comment by Divjyot** [comment]
This is happening with Summary Plot as well. Can someone confirm this please?
