### ISSUE TITLE
Retrieve specific data point from summary/beeswarm plots

### ISSUE THREAD

**Issue by giemmecci** [shap/shap#1974]
Hi,
Is there a way to retrieve the ID of specific data points from the summary/beeswarm plots?

For example, identify what the data point pointed by the arrow in the attached picture is.

Thanks!
![summary](https://user-images.githubusercontent.com/37995198/116830252-8c16f880-ab6e-11eb-9df8-c4d7a77d6f81.png)

**Comment by ky66** [comment]
that data point has the highest shap value for that feature. So go to the SHAP value matrix and find it that way.

**Comment by giemmecci** [comment]
Yeah, that is one way, but I wondered if there was a more scalable approach (if you look at the second row, there are cases with the same SHAP values). Thanks!
