### ISSUE TITLE
SHAP plots fail for sklearn's Isolation Forest

### ISSUE THREAD

**Issue by wundermahn** [shap/shap#1978]
I'm trying to use [sklearn's Isolation Forest ](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html) to create an anomaly detection model. I want to also see the SHAP values for my model.

I am currently able to do so using the method discussed in Issue #1152. I can then use `summary_plot` to create either bar charts, or the dot charts. However, I want to be able to use `beeswarm` and others to observe the different shap values for the different "classes" (aka anomalous, not anomalous).

For example, this works fine:
```
# Isolation Forest Shap Values
isof_f = lambda x: isof.decision_function(x)
isof_explainer = shap.KernelExplainer(isof_f, shap.sample(X_te, 100))
isof_shap = isof_explainer.shap_values(X_te[:50])

# Change feature names to obscure for Github posting
shap.summary_plot(isof_shap, 
                  feature_names=['feature_{}'.format(i) for i in range(len(X_te.columns))], 
                  class_names=['Anomaly', 'Normal'], 
                  show=True, plot_type='dot')

```
![image](https://user-images.githubusercontent.com/25335672/117172124-818c7700-ad99-11eb-9eae-1e1cb92567fe.png)

However, I'm unable to use **anything** from `shap.plots`. See below:
`shap.plots.beeswarm(isof_shap, max_display=10, plot_size='auto')`

Yields:
---------------------------------------------------------------------------

> UnboundLocalError                         Traceback (most recent call last)
> <ipython-input-31-8c3d362c900a> in <module>
> ----> 1 shap.plots.beeswarm(isof_shap, max_display=10, plot_size='auto')
> 
> c:\users\wundermahn\appdata\local\programs\python\python38\lib\site-packages\shap\plots\_beeswarm.py in beeswarm(shap_values, max_display, order, clustering, cluster_threshold, color, axis_color, alpha, show, log_scale, color_bar, plot_size, color_bar_label)
>      65         #     out_names = shap_exp.output_names
>      66 
> ---> 67     order = convert_ordering(order, values)
>      68 
>      69 
> 
> UnboundLocalError: local variable 'values' referenced before assignment

Issue #1586 points us to Issue #1460 to [try and use a technique](https://github.com/slundberg/shap/issues/1460#issuecomment-770317209) to get the SHAP object, but even that fails. See below:

```
# Isolation Forest Shap Values
isof_f = lambda x: isof.decision_function(x)
isof_explainer = shap.KernelExplainer(isof_f, shap.sample(X_te, 100))
explainer_obj = isof_explainer(X_te[:50])
isof_shap = isof_explainer.shap_values(X_te[:50])
```

Yields:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-42-7bfda8b35a63> in <module>
>       2 isof_f = lambda x: isof.decision_function(x)
>       3 isof_explainer = shap.KernelExplainer(isof_f, shap.sample(X_te, 100))
> ----> 4 explainer_obj = isof_explainer(X_te[:50])
>       5 isof_shap = isof_explainer.shap_values(X_te[:50])
> 
> c:\users\wundermahn\appdata\local\programs\python\python38\lib\site-packages\shap\explainers\_explainer.py in __call__(self, max_evals, main_effects, error_bounds, batch_size, outputs, silent, *args, **kwargs)
>     203         #     self._brute_force_fallback
>     204 
> --> 205         if issubclass(type(self.masker), maskers.OutputComposite) and len(args)==2:
>     206             self.masker.model = models.TextGeneration(target_sentences=args[1])
>     207             args = args[:1]
> 
> AttributeError: 'Kernel' object has no attribute 'masker'

How can we use `shap.plots` with Isolation Forest? It seems like we are unable to do so with `KernelExplainer`, but running `TreeExplainer` with Isolation Forests yields 

> Exception: Model type not yet supported by TreeExplainer: <class 'function'>

**Comment by JonasGlow** [comment]
I don't really get your first question, but there should be no problem using an isolation forest with the TreeExplainer. It was implemented in #784 . Using this and the generated shap values you can generate beeswarm, bar, and decision plots.
