### ISSUE TITLE
beeswarm plots lack documentation

### ISSUE THREAD

**Issue by mjkanji** [shap/shap#1983]
While there is a [whole page dedicated to an example](https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/beeswarm.html) of `shap.plots.beeswarm`, the API reference lacks any reference to this function!

[https://shap.readthedocs.io/en/latest/api.html#plots](https://shap.readthedocs.io/en/latest/api.html#plots)

This is obviously problematic because some of the arguments to this function are not covered in the example page. It's also just confusing, I think, for a function to not have its documentation clearly stipulated in the API reference.

**Comment by Eduarcher** [comment]
Arrived here by searching for the exact same, I was trying to find the specific documentation of the beeswarm plot arguments.

**Comment by thatlittleboy** [comment]
The API reference page now contains a link to the beeswarm function
