### ISSUE TITLE
remove the "sum of other features" from beeswarm plot

### ISSUE THREAD

**Issue by mjkanji** [shap/shap#1984]
Maybe I'm doing it wrong, but is there a way to make it so that the `max_display` argument in `shap.plots.beewsarm` shows only the first `max_display` features, without the `sum of other features` at the bottom? 

Basically, I'm trying to replicate the look of `shap.summary_plot`, which does not have a 'row' for the sum of other features, using `shap.plots.beeswarm`.

**Comment by ghost** [comment]
Was this solved?

**Comment by mengxuanlu** [comment]
How to solve this issue, any ideas?

**Comment by connortann** [comment]
Closed by #2225, which adds a new parameter `group_remaining_features`

**Comment by tbonewmy** [comment]
@connortann Can you please enable this argument in all plots that will group remaining features? the bar plot also do this
