### ISSUE TITLE
self._traceback = tf_stack.extract_stack() when running GradientExplainer.shap_values

### ISSUE THREAD

**Issue by Abzd** [shap/shap#1988]
I'm using shap 0.39.0 on Python 3.8.8 with tensorflow 2.3.1. I want to analyze the middle LSTM layer with GradientExplainer so I first get the values of the LSTM layer using K.function then apply GradientExplainer. It seems that my code has the same logic with the demo but it doesn't work. Is that a memory leakage or some other problem?

Here is my code: 

```
to_explain = x_val[[2, 3]]

get_layer_output = K.function([model.layers[0].input], [model.layers[-4].output])
layer_output = get_layer_output(to_explain)[0]
print(layer_output.shape)

e = shap.GradientExplainer(
    (model.layers[-4].input, model.layers[-1].output),
    layer_output
)
shap_values = e.shap_values(layer_output)
```

The whole error message is below:
```
Traceback (most recent call last):
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,60,6]
         [[{{node input_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_model.py", line 251, in <module>
    shap_values = e.shap_values(layer_output)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/shap/explainers/_gradient.py", line 111, in shap_values
    return self.explainer.shap_values(X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/shap/explainers/_gradient.py", line 211, in shap_values
    model_output_values = self.run(self.model_output, self.model_inputs, X)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/shap/explainers/_gradient.py", line 324, in run
    return self.session.run(out, feed_dict)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,60,6]
         [[node input_1 (defined at /home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:541) ]]

Original stack trace for 'input_1':
  File "test_model.py", line 151, in <module>
    input_1 = Input(shape=(len_date, d_feat))
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 541, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6262, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by YuantingMaSC** [comment]
> I'm using shap 0.39.0 on Python 3.8.8 with tensorflow 2.3.1. I want to analyze the middle LSTM layer with GradientExplainer so I first get the values of the LSTM layer using K.function then apply GradientExplainer. It seems that my code has the same logic with the demo but it doesn't work. Is that a memory leakage or some other problem?
> 
> Here is my code:
> 
> ```
> to_explain = x_val[[2, 3]]
> 
> get_layer_output = K.function([model.layers[0].input], [model.layers[-4].output])
> layer_output = get_layer_output(to_explain)[0]
> print(layer_output.shape)
> 
> e = shap.GradientExplainer(
>     (model.layers[-4].input, model.layers[-1].output),
>     layer_output
> )
> shap_values = e.shap_values(layer_output)
> ```
> 
> The whole error message is below:
> 
> ```
> Traceback (most recent call last):
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
>     return fn(*args)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,60,6]
>          [[{{node input_1}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_model.py", line 251, in <module>
>     shap_values = e.shap_values(layer_output)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/shap/explainers/_gradient.py", line 111, in shap_values
>     return self.explainer.shap_values(X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/shap/explainers/_gradient.py", line 211, in shap_values
>     model_output_values = self.run(self.model_output, self.model_inputs, X)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/shap/explainers/_gradient.py", line 324, in run
>     return self.session.run(out, feed_dict)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
>     run_metadata_ptr)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
>     run_metadata)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,60,6]
>          [[node input_1 (defined at /home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:541) ]]
> 
> Original stack trace for 'input_1':
>   File "test_model.py", line 151, in <module>
>     input_1 = Input(shape=(len_date, d_feat))
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/engine/input_layer.py", line 178, in Input
>     input_tensor=tensor)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
>     name=self.name)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 541, in placeholder
>     x = tf.placeholder(dtype, shape=shape, name=name)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2143, in placeholder
>     return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6262, in placeholder
>     "Placeholder", dtype=dtype, shape=shape, name=name)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
>     op_def=op_def)
>   File "/home/yaozw/anaconda3/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
>     self._traceback = tf_stack.extract_stack()
> ```

have u solved ur issues? i get the same error when fitting a self build model, if you work this problem out, could u tell me how to fix it ?

**Comment by yuchengml** [comment]
Recently, I had this issue when using fully-connected model and solved:

- Choose the above layer output of the target. Use `model.layers[N-1].output` instead of `model.layers[N].input`

Another, you should check your model by each layer(input/output tensors). If your model have different paths for some layers, you would get this error because other paths have no input! Just think about connections in computation graph.
