### ISSUE TITLE
when converting categorical features to OHE why one of the categorical columns shows all shap values as zero.

### ISSUE THREAD

**Issue by arjunko** [shap/shap#1989]
Hello, I'm using XGB classifier model. I'm saving shap_values into .CSV file and I observed that one of the categorical columns gives all shap values as zeros. kindly help that me why it is not providing shap values.

![image](https://user-images.githubusercontent.com/78132920/117646454-69599500-b1a9-11eb-8971-23ffc3066204.png)

**Comment by peterdhansen** [comment]
Simplest explanation is that the column had no impact on the predictions.

Which makes sense if you don't drop one of the columns. If there are N categories, all the information is contained in N-1 columns.

**Comment by arjunko** [comment]
@peterdhansen Thank Sir for clearing my question. Adding to the above issue instead of using the XGB classifier, I'm using Logistic Regression Classifier with "shap.LinearExplainer" explanation. Here I got only two unique shape values for all categorical columns. Is my approach is correct or not? I'm a bit confused that why explainers produce only two unique shap values it's because of choosing the model or by explainer. Kindly clarify this. 

![image](https://user-images.githubusercontent.com/78132920/117764158-a8d7be00-b249-11eb-8528-a440943884c0.png)

**Comment by peterdhansen** [comment]
The feature has two possible values, and its a linear model so only two possible shap values.

**Comment by arjunko** [comment]
@peterdhansen  Big thank you. Your responses were cleared my queries.  Let's consider the above XGB classifier example we have categorical columns like Marital Status, Race, gender, etc.  Consider gender - Shap OHE Female columns gives shap values and Male columns give all zeros. out of these two columns(gender_famele and gender_male), how will I know/differentiate what are the Male shap values and what are the female shap values?

**Comment by peterdhansen** [comment]
there are no "male shap values" or "female shap values" just gender shap values. lets say you drop the male column, then `gender_female=0` is male and `gender_female=1` is female and you have all the shap values in one column.

For something with more categories like Marital Status, you could drop the last category before training and lose no information 

For example
```python
ms = pd.DataFrame(dict(marital_status = ['married', 'single', 'engaged', 'widowed', 'divorced']))

print(ms)
print(pd.get_dummies(ms, drop_first=True))
```
```
  marital_status
0        married
1         single
2        engaged
3        widowed
4       divorced
   marital_status_engaged  marital_status_married  marital_status_single  marital_status_widowed
0                       0                       1                      0                       0 
1                       0                       0                      1                       0 
2                       1                       0                      0                       0 
3                       0                       0                      0                       1 
4                       0                       0                      0                       0 

```

divorced gets encoded as [0,0,0,0] so you could look at the sum of the shap values of the other columns when features are all zero.

**Comment by arjunko** [comment]
@peterdhansen  Thank you so much for your all answers. It's really helped me to gain more insight knowledge in shap explainer. :-)
