### ISSUE TITLE
Question on Direction of Impact - Local Importance

### ISSUE THREAD

**Issue by BrianMiner** [shap/shap#199]
This library is fantastic, thank you for such an awesome contribution!

Take the local importance of an observation, swiped from a blog showing SHAP. One question (or suggestion) is in terms of understanding what direction one should change a given feature to increase the prediction. Below, take the variable "vertical" which is decreasing prediction with its value of 33. How can one know (without perturbing the single input and running the inference) if 20.0 or 50.0 would increase the model prediction further?

![image](https://user-images.githubusercontent.com/8807554/43607748-21ff730a-966d-11e8-85ea-6c7c8b93cc50.png)

**Comment by slundberg** [comment]
Good question. You can't know for sure from just this plot. But what you can conclude is that knowing "vertical = 33" decreases the model output. That probably means that putting in the median value for vertical would raise the prediction. If you don't already have a good idea of how moving a variable around will effect things then I would suggest running a `dependence_plot` on that feature, then you will know how the output changes as that feature changes in your dataset.

**Comment by BrianMiner** [comment]
OK, thank you. I am not sure if this is something that could be added in a programmatic manner, but FWIW one advantage of the LIME presentation is that from viewing the output you can immediately tell that being <= 30 in width led to the prediction, this increasing from 30 to say 40 should decrease the prediction.

![image](https://user-images.githubusercontent.com/8807554/43614709-9268138a-9682-11e8-8006-56ff55678905.png)

**Comment by BrianMiner** [comment]
And FTR, one of the use cases here is using the local interpretation to recommend adjustments. For example, say the model is for customer churn. If having a low variable-A contributes to an increased churn risk, can we push out a notification to take action to increase variable-A, in an automated programmatic manner. Not sure if you have heard of people using these interpretations for that sort of thing or not (there are risks of course).

**Comment by slundberg** [comment]
I would need to check the LIME implementation, but I think they are binning the data, hence the <= 30 threshold. If you want to tweak a single feature in customer churn risk then I think you should always try it out by changing that feature and rerunning the model. SHAP values summarize the impact of features over all subsets (so that, for example, two features in an AND relationship get equal credit). However if you are going to make a specific change to a single feature, then you should just test the impact of that specific change before you make it. (you could of course use SHAP to pick out promising changes to test)

**Comment by BrianMiner** [comment]
Yes you are right, LIME is binning. The binning alone doesn't always tell you how to change the variable the more I think about it.

I was trying to consider if you could take the sign of the shapley value for a given feature for a given sample (e.g if it is negative it is reducing the probability of the event labeled '1') and compare the value of the feature for that sample against the mean of the training set ....and if all these pieces of information could tell you the direction to nudge the variable in order to increase the model output. 

Maybe a better thing is to get the top features for a sample that are driving down the model output, also look at the top interaction features associated with them and use this small number of features in a traditional optimization process - if you could actually set realistic constraints on how these variables could change relative to others held constant and to each other. That seems like the real dilemma in prescriptive  analytics. Shapely values is a real contribution towards understanding the impacts though!

**Comment by slundberg** [comment]
That seems like a reasonable way to go about it. Take the top SHAP valued features and tweak them. The biggest challenge in prescriptive analytics is of course getting a causal (rather than just associational) model in the first place so that the model reflects what will happen when you intervene.
