### ISSUE TITLE
background data size limited to 100, xgboost

### ISSUE THREAD

**Issue by alberto-bracci** [shap/shap#1991]
Hi, I am working with a XGBoost model. 
I was trying to feed different background data samples to estimate the largest size I could feed the explainer while keeping runtime reasonable, when I noticed that TreeExplainer apparently limits the size to 100 samples max? 

This is weird, because I did not find any reference in the source code for ` class Tree(Explainer):`, but accessing the data through `explainer.data` seems to indicate this. 

I reproduced this behavior with a simple available shap dataset as below:

```
import pandas as pd
import shap
import xgboost 

X_adult,y_adult = shap.datasets.adult()
model = xgboost.XGBClassifier(n_estimators=100, max_depth=2).fit(X_adult, y_adult)

for i in [1,10,20,50,100,200,300,400,1000,10000]:
    explainer = shap.TreeExplainer(model,X_adult[:i],feature_perturbation='interventional',model_output='probability')
    print(f"expected size: {i}, actual size: {explainer.data.shape[0]}")
```

which returns

```
expected size: 1, actual size: 1
expected size: 10, actual size: 10
expected size: 20, actual size: 20
expected size: 50, actual size: 50
expected size: 100, actual size: 100
expected size: 200, actual size: 100
expected size: 300, actual size: 100
expected size: 400, actual size: 100
expected size: 1000, actual size: 100
expected size: 10000, actual size: 100
```

Also, the code contains a warning that should be triggered when the data size is > 1000:
```
elif feature_perturbation == "interventional" and self.data.shape[0] > 1000:
                warnings.warn("Passing "+str(self.data.shape[0]) + " background samples may lead to slow runtimes. Consider "
                    "using shap.sample(data, 100) to create a smaller background data set.")
```
 but it is never triggered in my case

**Comment by rainergo** [comment]
I have the same problem: TreeExplainer apparently limits the size to 100 samples max.

**Comment by samFarrellDay** [comment]
I just did a bunch of debugging and figured out this is also the root of my issue. @slundberg I don't know if this is intended behavior but it looks like this bit of code here:

```
        # wrap the incoming masker object as a shap.Masker object
        if safe_isinstance(masker, "pandas.core.frame.DataFrame") or \
                ((safe_isinstance(masker, "numpy.ndarray") or sp.sparse.issparse(masker)) and len(masker.shape) == 2):
            if algorithm == "partition":
                self.masker = maskers.Partition(masker)
            else:
                self.masker = maskers.Independent(masker)
```

in _tree.Explainer forces the background dataset to be 100 if a `pandas.DataFrame` is passed. It looks like you can get around this limitation by passing your own masker to data instead of a pandas.DataFrame.
