### ISSUE TITLE
How to get odds ratio based on SHAP, just like what logistic regression model did.

### ISSUE THREAD

**Issue by kingsomeWang** [shap/shap#1998]

**Comment by detrin** [comment]
@kingsomeWang I don't think shap is suitable for calculating odds ratio.

@thatlittleboy Candidate for closing?

**Comment by thatlittleboy** [comment]
It's not really clear what the question is. The SHAP values you get (by default) is in the units of the model output, if the model you are explaining is a logistic regression, then the explanations are in the units of log-odds (and the outputs are naturally additive in this space).

Explaining in other units (eg odds ratio) is tricky, probably needs some approximations..
