### ISSUE TITLE
Errors when running the notebook for "Be Careful When Interpreting Predictive Models in Search of Causal Insights"

### ISSUE THREAD

**Issue by ajsExodus** [shap/shap#2001]
Hi!
[I also posted this question on the Towards Data Science article]

I have used SHAP before, but when tried to execute the notebook the article points to (*), I got errors when trying to run `shap.utils.hclust(...)` and `shap.plots.scatter(...)`. Is there a way to find a workaround for these? 

Those particular plots are very useful and I would like to use them for my analyses. 

Also, I was not able to get the `shap.plots.force` plot shown in [https://github.com/slundberg/shap] 

I appreciate your time and help! (See below).

  -AJ

(*) [https://towardsdatascience.com/be-careful-when-interpreting-predictive-models-in-search-of-causal-insights-e68626e664b6)]

----------------------------------------------------------------------------------------------------------------------------------------------------
`clust = shap.utils.hclust(X, y, linkage="single")`

`Exception                                 Traceback (most recent call last)
<ipython-input-3-af0ff76bee89> in <module>
      4 shap_values = explainer(X)
      5 
----> 6 clust = shap.utils.hclust(X, y, linkage="single")
      7 shap.plots.bar(shap_values, clustering=clust, clustering_cutoff=1)

~/anaconda3/lib/python3.7/site-packages/shap/utils/_clustering.py in hclust(X, y, linkage, metric, random_state)
    175         return sp.cluster.hierarchy.complete(dist)
    176     else:
--> 177         raise Exception("Unknown linkage: " + str(linkage))

Exception: Unknown linkage: single`

----------------------------------------------------------------------------------------------------------------------------------------------------
`shap.plots.scatter(shap_values, ylabel="SHAP value\n(higher means more likely to renew)")`

`TypeError                                 Traceback (most recent call last)
<ipython-input-4-0af081ed1a92> in <module>
----> 1 shap.plots.scatter(shap_values, ylabel="SHAP value\n(higher means more likely to renew)")

TypeError: scatter() got an unexpected keyword argument 'ylabel'`

----------------------------------------------------------------------------------------------------------------------------------------------------
NOTE: I am using the code in [https://github.com/slundberg/shap] 

I am able to see the waterfall plot, and the `shap.plots.force(...)` plots, but not the one below ...

`shap.force_plot(explainer.expected_value[0], shap_values[0])`

As suggested by ...

`Exception: In v0.20 force_plot now requires the base value as the first parameter! Try shap.force_plot(explainer.expected_value, shap_values) or for multi-output models try shap.force_plot(explainer.expected_value[0], shap_values[0]).`

Got ...

`IndexError                                Traceback (most recent call last)
<ipython-input-8-0bddc6dd5d92> in <module>
      2 
      3 # shap.plots.force(shap_values)
----> 4 shap.force_plot(explainer.expected_value[0], shap_values[0])

IndexError: invalid index to scalar variable.`

**Comment by shadigoodarzi** [comment]
Same here. I upgraded the SHAP package to the latest version 0.39.0 and then copied the changes from 7 days ago in GitHub to the _clustering.py and _scatter.py in my environment and reloaded the module using importlib.reload(shap). shap.plots.scatter(...) worked but still getting error for this line:
clust = shap.utils.hclust(X, y, linkage="single")
Error:
Exception: Unknown linkage: single

**Comment by Mohak91** [comment]
I get the same error for linkage="single"! 

Could someone help with this issue? Thanks!

**Comment by mrastgoo** [comment]
If you are using verison 0.39.0 only "complte" is accepted as far as I know
