### ISSUE TITLE
DeepExplainer target

### ISSUE THREAD

**Issue by AlejandroTL** [shap/shap#2009]
Hello!

I'm trying to apply DeepExplainer to a NN that has many different outputs. Is there any way to apply DeepExplainer just to one of these neuron outputs instead of applying it over the whole output? Let's say I have five output neurons, how can I apply DeepExplainer just to one of them and forget about the others? I just want to focus on the explanations on how this neuron is working inside. In Captum Library there's a variable called 'target' in some functions that allows you to compute the SHAP values for just one output instead of the whole of them, it would be the same concept.

Thank you! 
Awesome work, btw! :)

**Comment by GMSL1** [comment]
The output of DeepExplainer is a list of _n_ arrays, where _n_ is your number of output neurons. So your SHAP values of your first neuron is your first element of the DeepExplainer output.

**Comment by AlejandroTL** [comment]
> 
> 
> The output of DeepExplainer is a list of _n_ arrays, where _n_ is your number of output neurons. So your SHAP values of your first neuron is your first element of the DeepExplainer output.

Thank you for your answer!

Yes, I know that, but I mean if there's any way to apply DeepExplainer to just one output neuron, because maybe the computational effort of applying it to all output neurons is too high (if I have 10 outputs neurons it would be 10x higher) and I just want one computation. But thank you anyway!
