### ISSUE TITLE
shap.plots.bar do not have 'plot_size' argument

### ISSUE THREAD

**Issue by banderlog** [shap/shap#2015]
Hi, if one wants to plot shap plots on subplots, he should set `show=False, plot_size=None` in plotting function, e.g.:

```python
# The secret in the `show=False, plot_size=None` part
fig = plt.figure(figsize=(16, 20))
ax = plt.subplot(121)
shap.summary_plot(shap_values_1, train_x, plot_type="bar", show=False, plot_size=None)
ax.set_title('title 1')

ax = plt.subplot(122)
shap.summary_plot(shap_values_2, train_x, plot_type="bar", show=False, plot_size=None)
ax.set_title('title 2')
```

But `shap.plots.bar(shap_values, show=False, plot_size=None)` throws error:
> TypeError: bar() got an unexpected keyword argument 'plot_size'

The `shap.summary_plot(shap_values, show=False, plot_type='bar')` is a bad substitution, because it gives different plot

Thus, at the moment, there is no way to plot correct shap bar plot on a subplot.

### Examples

`shap.plots.bar(shap_values, show=False)`
![image](https://user-images.githubusercontent.com/2557965/119836165-2b2ed600-bf0a-11eb-9a6b-0a1906814d0e.png)

`shap.summary_plot(shap_values, show=False, plot_type='bar')`:
![image](https://user-images.githubusercontent.com/2557965/119836184-308c2080-bf0a-11eb-9532-6913f15a9997.png)

**Comment by leon-dae** [comment]
Hi,
I had a similar problem with the old-style dependence plots. I solved it like this:
```
shap.dependence_plot(feature, shap_values[2], X, 
                     interaction_index=int_feature, show=False)
```
and in the next line do something like this
`plt.gcf().set_size_inches(fig_size_)`

Maybe this also works for the new bar plot.
