### ISSUE TITLE
DeepExplainer Attribute Error

### ISSUE THREAD

**Issue by ishaanrd** [shap/shap#2019]
.../site-packages/shap/explainers/_deep/__init__.py in __init__(self, model, data, session, learning_phase_flags)
     84             self.explainer = TFDeep(model, data, session, learning_phase_flags)
     85         elif framework == 'pytorch':
---> 86             self.explainer = PyTorchDeep(model, data)
     87 
     88         self.expected_value = self.explainer.expected_value
 
.../site-packages/shap/explainers/_deep/deep_pytorch.py in __init__(self, model, data)
 56             # also get the device everything is running on
---> 57             self.device = outputs.device
     58             if outputs.shape[1] > 1:
     59                 self.multi_output = True

AttributeError: 'tuple' object has no attribute 'device'

**Comment by enricoliscio** [comment]
Same over here when running: `shap.DeepExplainer(model, data)`
My model is a `transformers.models.bert.modeling_bert.BertForSequenceClassification`, the data is a `torch.Tensor`.
Thus, I result with a:
```AttributeError: 'SequenceClassifierOutput' object has no attribute 'device'```

Did you manage to solve it?

**Comment by hsny-dev** [comment]
Hey, I got the same error as you @ishaanrd, found nothing on the internet. Were you able to solve it? or anyone got an idea why we get this error?

**Comment by enricoliscio** [comment]
I fixed it and went further, until I hit the wall described here: https://github.com/slundberg/shap/issues/595
Apprently DeepSHAP does not support torch transformers.
