### ISSUE TITLE
SHAP with object detection models

### ISSUE THREAD

**Issue by emamangiapia** [shap/shap#2032]
Hi, is it possible to use SHAP with object detection models? Such as: faster RCNN, yolo etc. If yes, which modifications should be done?

**Comment by ameyskulkarni** [comment]
Hello 
I am also looking for the answer to this question. Do you have any update? 
Thank you

**Comment by Flippchen** [comment]
Has anyone found a solution? I want to use it with YOLOv8 segmentation and it drives me crazy that I dont find the solution/way to do it.

**Comment by Sarvi-Sardari** [comment]
I have the same issue with YOLOv8 for object detection.it is possible with shap.Explainer, but I want to use DeepExplainer or GradiantExplainer.
