### ISSUE TITLE
Shap force_plot visualization error with multiple samples

### ISSUE THREAD

**Issue by alwkynew** [shap/shap#204]
Hello,

I am testing Shap with the default classification examples, and running in Jupyter Notebook (windows).
When I run force_plot with a single sample , it plots perfectly (as below). 
![s1](https://user-images.githubusercontent.com/16995696/43693331-3eeba012-9968-11e8-9a47-f04b2daa0aae.png)

But if I try to run with more than 1 sample it doesn't show. If I try to select the boxes it gives the in the message below.
![s2](https://user-images.githubusercontent.com/16995696/43693385-7b55af66-9968-11e8-94de-69aeb22cc7eb.png)

Any suggestion on how I can fix this? 
Thank you.

**Comment by slundberg** [comment]
Seems like some type of javascript error. What browser are you using? (and can you try another one?)

**Comment by alwkynew** [comment]
Yes, BRILLIANT!

To my shame I was using Internet Explorer... changed to Chrome and it worked.

Thank you.

**Comment by slundberg** [comment]
Great! If you have issues with Edge then it might be worth following up on, but I don't think IE is worth debugging right now.
