### ISSUE TITLE
Dependence.py using version of numpy where the np.reshape `order` param is an int, not a str

### ISSUE THREAD

**Issue by kyleschiess** [shap/shap#2047]
```<ipython-input-643-c4c8809288b1> in <module>
----> 1 shap.dependence_plot("nfv",shap_values[1], X_test, interaction_index='tfp')

~/opt/anaconda3/lib/python3.8/site-packages/shap/plots/dependence.py in dependence_plot(ind, shap_values, features, feature_names, display_features, interaction_index, color, axis_color, cmap, dot_size, x_jitter, alpha, title, xmin, xmax, ax, show)
     97     # allow vectors to be passed
     98     if len(shap_values.shape) == 1:
---> 99         shap_values = np.reshape(shap_values, len(shap_values), 1)
    100     if len(features.shape) == 1:
    101         features = np.reshape(features, len(features), 1)

<__array_function__ internals> in reshape(*args, **kwargs)

~/opt/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py in reshape(a, newshape, order)
    297            [5, 6]])
    298     """
--> 299     return _wrapfunc(a, 'reshape', newshape, order=order)

...

TypeError: order must be str, not int
```

I think np.reshape is looking for `order=1`. Instead, we're just calling `1`

**Comment by defoishugo** [comment]
Hi,

The [documentation](https://shap-lrjball.readthedocs.io/en/docs_update/generated/shap.dependence_plot.html) says that the dependance_plot should be a "matrix of SHAP values (# samples x # features)". From what I see, you are feeding the function with the first element of shap_values insted of feeding it with all the shap_values.

Could you try to replace:

`shap.dependence_plot("nfv",shap_values[1], X_test, interaction_index='tfp')`

By the following line of code:

`shap.dependence_plot("nfv", shap_values, X_test, interaction_index='tfp')`

I tried on my side, with my own dataset. I had the same error than yours and was able to fix it with the previous line of code.

**Comment by clouedoc** [comment]
@defoishugo hi, this worked, many thanks 🙏
