### ISSUE TITLE
Shap value for LSTM model

### ISSUE THREAD

**Issue by MariamDundua** [shap/shap#2049]
I have lstm model named `lstm_model` and I am using shap value to explain model. have tabular data.

 ```
   import shap
    explainer = shap.DeepExplainer(lstm_model, X_train)
   shap_values = explainer.shap_values(X_test)
```

From My knowledge in order to calculate the shap value, It uses a 2^(number of features) model. I am interesting what is kind of algorithm it uses for each individual model. 
This question comes from the following fact:

When I  am plotting  of effect `x` feature on output, this effect is linear(increasing or decreasing). For example when `x` increasing the effect increasing(decreasing). What is the reason behind this?

One additional question:
Is it possible to use shap to plot partial dependence plot for LSTM model?

**Comment by SaidaSaad** [comment]
@MariamDundua  
Thanks for the post. I have problem usinfg shap in Lstm model . I am trying to apply shap in ptorch model that compose of lstm and fully connected layers.
Are you also using pytorch ?  

Thanks
Saida
