### ISSUE TITLE
Installation from conda-forge

### ISSUE THREAD

**Issue by mrandrewandrade** [shap/shap#205]
Hey @slundberg ,

I want to enable SHAP to be installed from conda, so I was going to add it to conda-forge.  Do you want to be added as a recipe maintainer ?  The consequence is that you will get emails from the conda-forge bots if there are issues.

Best,

Andrew

**Comment by slundberg** [comment]
Sounds great. Go ahead and add me. I just pushed some updates that merge the iml package into shap and so remove the issues you encountered (because iml is not loner a dependency). I think everything will be cleaner this way since we didn't end up sharing code with LIME (which motivated the initial separation into iml and shap).

**Comment by mrandrewandrade** [comment]
Thanks for the latest releases @slundberg , the checks passed for conda-forge for staged-recipes, it can take up to a week for them to merge https://github.com/conda-forge/staged-recipes/pull/6406

**Comment by slundberg** [comment]
great. thanks!

**Comment by mrandrewandrade** [comment]
Hey @slundberg, I think we are go to close this out!

So the staged-recipes PR was merged and the feedstock setup. I was able to run without issues:

```
conda config --add channels conda-forge
conda install shap
```
Which installed v0.22.2.

It also detected the version bump from your last release, and auto created a PR which I merged: https://github.com/conda-forge/shap-feedstock/pull/1 .  It updated automatically and ran via terminal.  It's also visible here: https://anaconda.org/conda-forge/shap

The following packages will be UPDATED:

    shap: v0.22.2-py27h7eb728f_0 conda-forge --> v0.22.3-py27h7eb728f_0 conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
shap v0.22.3: ################################################################################ | 100%

**Comment by mrandrewandrade** [comment]
https://github.com/slundberg/shap/pull/212

**Comment by slundberg** [comment]
@mrandrewandrade Something has gone wrong with the conda-forge process, would you mind taking a look? I think it had to do with the update for python3.7 which I didn't notice to merge right away.
