### ISSUE TITLE
demo can not work

### ISSUE THREAD

**Issue by zhaozhongfeng1990** [shap/shap#2051]
mydears:
 the demo like :
{import xgboost
import shap

# train an XGBoost model
X, y = shap.datasets.boston()
model = xgboost.XGBRegressor().fit(X, y)

# explain the model's predictions using SHAP
# (same syntax works for LightGBM, CatBoost, scikit-learn, transformers, Spark, etc.)
explainer = shap.Explainer(model)
shap_values = explainer(X)

# visualize the first prediction's explanation
shap.plots.waterfall(shap_values[0])}

can not be worked ,how can i find solution
![下载](https://user-images.githubusercontent.com/41822422/122870032-bb243c00-d35f-11eb-80ea-4f52815c90d3.png)

**Comment by zhaozhongfeng1990** [comment]
which environment   you are config

**Comment by defoishugo** [comment]
Hi @zhaozhongfeng1990,

The following code is working on my side:

```
import xgboost
import shap

X, y = shap.datasets.boston()
model = xgboost.XGBRegressor().fit(X, y)

explainer = shap.Explainer(model)
shap_values = explainer(X)

shap.plots.waterfall(shap_values[0])
```

It is producing the following vizualisation:

![Shap_plot](https://user-images.githubusercontent.com/22320492/122993390-8d62e580-d3a7-11eb-88cc-47c23397584b.png)

Could you please describe what is your problem? Could you share any error?
Also, please think to create a new Anaconda environment and share it with us if you still have the problem on your side.

**Comment by zhaozhongfeng1990** [comment]
if i use this demo ,the results is correct;when i change some code ,bug appears(for classification):

code:
row1:

# Get all the columns from the dataFrame
columns = data.columns.tolist()

# Filter the columns to remove data we do not want
columns = [c for c in columns if c not in ["Class"]]

# Store the variable we'll be predicting on
target = "Class"

X = data[columns]
Y = data[target]

# Print shapes
print(X.shape)
print(Y.shape)
ERROR:
TypeError                                 Traceback (most recent call last)
<ipython-input-5-b0a93c6f343f> in <module>
      1 lgbm=lgb.LGBMClassifier()
      2 model = lgbm.fit(X, Y)
----> 3 explainer=shap.Explainer(model)
      4 shap_values=explainer(X=X)

TypeError: __init__() missing 1 required positional argument: 'masker';

row2:

lgbm=lgb.LGBMClassifier()
import shap
model = lgbm.fit(X, Y)
explainer=shap.Explainer(model)
shap_values=explainer(X,Y)
ERROR:
TypeError: __init__() missing 1 required positional argument: 'masker'


row3:

from shap.plots._waterfall import waterfall
shap.plots.waterfall(shap_values.base_values[0])

ERROR:
Exception                                 Traceback (most recent call last)
<ipython-input-240-a472c2d2c266> in <module>
      1 from shap.plots._waterfall import waterfall
----> 2 shap.plots.waterfall(shap.plots.force(shap_values)[0])

~\anaconda3\lib\site-packages\shap\plots\_force.py in force(base_value, shap_values, features, feature_names, out_names, link, plot_cmap, matplotlib, show, figsize, ordering_keys, ordering_keys_time_format, text_rotation, contribution_threshold)
     90 
     91     assert not type(shap_values) == list, "The shap_values arg looks looks multi output, try shap_values[i]."
---> 92 
     93     link = convert_to_link(link)
     94 

Exception: In v0.20 force_plot now requires the base value as the first parameter! Try shap.force_plot(explainer.expected_value, shap_values) or for multi-output models try shap.force_plot(explainer.expected_value[0], shap_values[0]).

please help me ,THanks

**Comment by defoishugo** [comment]
Hi @zhaozhongfeng1990,

This problem is not reproductible on my side since you didn't shared the appropriates rows ("data" variable definition, imports, ...).

Moreover, your message is not correctly formatted.
Please edit it so it will be easier to read.
