### ISSUE TITLE
Jupyter notebook kernel keep restarting when loading huge dataset from BigQuery when shap was introduced

### ISSUE THREAD

**Issue by stevenzhang-support** [shap/shap#2058]
**Type**: Customer issue or a bug

**Issue**: When using shap==0.39.0 in Jupyter notebook hosted on AI platform in Google Cloud. Jupyter notebook kernel keep restarting when loading huge dataset from BigQuery. The experiment found the issue only occurred with shap lib ==0.39.0 introduced, see cell1, cell2 and cell3 , only cell2 failed to execute.

====cell1=====
```
# BQ script can be ran smoothly if limited to 3 libraries as shown below:
from google.cloud.bigquery import Client
import pandas as pd
import time

client = Client(project='XXX')
sql = “Select…..,
df = (\n",
client.query(sql)\n",
.to_dataframe(create_bqstorage_client=True)\n",
),
print(f'BQ Read Time: {round(time.time()-start, 1)}')
```

===cell2=====
```
from google.cloud.bigquery import Client
import pandas as pd
import shap #===>test if shap will block the reading data from BQ
import time

client = Client(project='XXX')
sql = \"\"\"
sql = “Select…..,
start = time.time()\n",
df = (\n",
client.query(sql)\n",
.to_dataframe(create_bqstorage_client=True)\n",
),
print(f'BQ Read Time: {round(time.time()-start, 1)}')
```
===cell3======
```
from google.cloud.bigquery import Client
import pandas as pd
import xgboost as xgb
from xgboost import XGBClassifier #====>test Xgboost
import time

client = Client(project='XXX')
sql = \"\"\"
sql = “Select…..,
start = time.time()\n",
df = (\n",
client.query(sql)\n",
.to_dataframe(create_bqstorage_client=True)\n",
),
print(f'BQ Read Time: {round(time.time()-start, 1)}')
```

**My theory**:
I think this is related to A Python "segfault" as per similar issue [1-4] which can happen when some underlying 'C' Python code extension has a bug in it and attempts to access/point to a memory address beyond reach (e.g C will segfault if attempting to access the second element of an 'array[1]' if it only has one element in it 'array[0]'). In this case it is the fault of the specific C code being run, and no addition of memory or hardware will resolve it. Therefore, I report this issue to Sharp eng in their GitHub repository.

[1] https://github.com/slundberg/shap/issues/452
[2] https://github.com/slundberg/shap/issues/1495
[3] https://github.com/slundberg/shap/issues/1053
[4] https://github.com/slundberg/shap/issues/955

**Comment by stevenzhang-support** [comment]
Hello, could any one share a kind update on this issue?

**Comment by johnpaulett** [comment]
Similar issue with consistent segfault occurring when doing a pandas `df.dropna()` on a large dataframe.  Had only run `import shap` with no usage of shap at that point.

Google Cloud AI Notebook JupyterLab, pandas 1.2.4, numpy 1.19.5
