### ISSUE TITLE
SHAP summary plot does not shows contribution of features for each classes of binary class. 

### ISSUE THREAD

**Issue by KCSajan** [shap/shap#2073]
I tried to make "plot_type = bar" summary plot for multi-class classification. For this, it worked. However, the summary plot (bar type) does not show the contribution for each class for binary class. What can be the reason? 

This is the plot for binary class. (please click the image, to see it in detail).
![stupid](https://user-images.githubusercontent.com/60316900/124371712-25b07280-dca4-11eb-837f-f1e88b5ebfa8.png)

This is the kind of plot I want in binary class (though it is for multi-class).
![download (2)](https://user-images.githubusercontent.com/60316900/124371735-67411d80-dca4-11eb-8a09-3ede0129bec6.png)

I need plot similar to this. (contribution of each feature on each class). 
![Capture](https://user-images.githubusercontent.com/60316900/124372527-36fc7d80-dcaa-11eb-806c-ab168c83bd6d.PNG)

I would be grateful if anybody could assist me with it. 
Many thanks.

**Comment by c56pony** [comment]
In the case of binary classification, the output of the model is **single**, so the summary_plot cannot be color-coded as in the case of multiple outputs. Does it make sense to interpret a single identification, A or not A, in a different color?

**Comment by KCSajan** [comment]
> In the case of binary classification, the output of the model is **single**, so the summary_plot cannot be color-coded as in the case of multiple outputs. Does it make sense to interpret a single identification, A or not A, in a different color?

Thank you for your response. But, as you can see in the last image I've uploaded, a color-coded summary_plot for binary outputs has been made. My question is why I could not get a similar figure while I was using the "standard code" to make the plot?

Well, I may not have been able to understand your question. My preliminary purpose for the summary_plot is to find the most important features and their mean SHAP values in a single bar plot for each class.

**Comment by c56pony** [comment]
If you really want to do a color-coded `summary_plot` for binary outputs, it is better to use the multiclass classification method. One of the methods suitable for this purpose is `RandomForestClassifier` of scikit-learn. Of course, you can also use xgboost or lightgbm. The sample code and its output are shown below.
```
import shap
from sklearn.ensemble import RandomForestClassifier
X, y = shap.datasets.adult()
model = RandomForestClassifier().fit(X, y)
shap_values = shap.TreeExplainer(model).shap_values(X[:100])
shap.summary_plot(shap_values, X[:100])
```
![image](https://user-images.githubusercontent.com/40843206/126844894-19783fb2-d5ff-4cbf-8e9b-6fd846665a1a.png)
However, when comparing the SHAP values of class 0 and class 1, the values are exactly the same except for the difference in sign. Therefore, I don't think this color-coded plot will serve the purpose of finding important features for each class.
In fact,
```
import numpy as np
np.allclose(shap_values[0], -1 * shap_values[1])
```
outputs `True`.
