### ISSUE TITLE
ERROR: Files/directories not found in C:/user/<folder>/Appdata/Local/pip-req-build-3mlgezzc/shap/pip-egg-info

### ISSUE THREAD

**Issue by Akshay123455667** [shap/shap#2077]
I am trying to install ibm db2 but getting below error after setting up CLI drivers.

C:/user/<folder>/Appdata/Local/pip-req-build-3mlgezzc/shap/pip-egg-info.

I tried using --no-cache-dir , still same error.
Below is config
Python 3.7
pip - 19.0.3
Windows.

Does anyone know how to resolve this ?

**Comment by cbelitz** [comment]
I had the same problem on python 3.6.8 on Mac and found some help on this thread: actions/setup-python#165

I needed to `pip install numpy` first and was then able to `pip install shap --no-cache-dir`
