### ISSUE TITLE
What is `link=logit`?

### ISSUE THREAD

**Issue by elcolie** [shap/shap#2078]
If I use my `shap_values` will contains `nan`. Without it it does raise any problem
![image](https://user-images.githubusercontent.com/18206728/124704043-9adaac80-df1d-11eb-95da-a5d2e1a2fdc6.png)

Do I need to use it?

**Comment by HajarHkm** [comment]
Hello,
I am new to this too and couldn't have the equation: [sum of  SHAP values for each sample plus explainer.expected_value equals the output of the black box model]  verified when using the logit link. 
Although I did not quite understand the reason behind this, I used identity link instead after seeing this: https://github.com/slundberg/shap/issues/350#issuecomment-445005169
