### ISSUE TITLE
 tree_limit shap_values kill notebook

### ISSUE THREAD

**Issue by oristides** [shap/shap#208]
Hello,

I tried an shap_values(self, X, tree_limit=-1)  where X is a dataset with mora than 1M lines and more than 500 trees.

 It kills my notebook.

I found out the problem is with 
elif self.model_type == "lightgbm":

            phi = self.model.predict(X, num_iteration=tree_limit, pred_contrib=True)

where tree_limit is big the Jupyter kernel will die

Then 100K dataset with same trees- same problem

Then I tried bigger with way less trees and then it worked. Not more than 32 trees.

**Comment by slundberg** [comment]
How many features are in your dataset? I.e. what is `X.shape[1]`? (Also what depth are the trees?)

**Comment by oristides** [comment]
300 features
As well with 90

**Comment by slundberg** [comment]
Ah. I think the tree depth might be the issue. I don't often use trees that deep so I might not have run into this. Any idea how many leaves are in those trees? (certainly less than 2^90) If the trees are huge there might be some memory issues. Though I thought the attribution was not in parallel and so should not take more memory with more trees.

**Comment by oristides** [comment]
When I look. The problem is with CPU. Not memory.

**Comment by slundberg** [comment]
The complexity scales with the square of tree depth times the number of leaves. It could be that the model you have has tons of very deep leaves. I would need to profile it to see for sure if that's it.

**Comment by dst1** [comment]
I have a similar problem but with much less features and depth.
For XGBoost models with depth = 15, n_rounds = 2000 and 60 features for 500K samples.

I did a benchmark, I get that it takes several minutes for depth=10 (and 50,000 samples) and I didn't wait for it to finish with depth 15 as it takes too much time:
![image](https://user-images.githubusercontent.com/22453031/44000834-9aa56d7c-9e2f-11e8-8dda-aefd453f3dd9.png)

depth 5 does take 12s on my computer so it's very reasonable..

I also see that it's mainly CPU being used, not memory.

**Comment by oristides** [comment]
Yes,

The maximum number of leaves is the default 31

**Comment by slundberg** [comment]
@oristides Was out on travel for a while and didn't follow up on this. By kills the notebook do you mean it crashes or just takes a long time to run?

@dst1 depth 15 trees can have up to 2^15 = 33,554,432 nodes in them, so I would not be surprised if things got slow when explaining hundreds of huge trees like that on 50k samples.
