### ISSUE TITLE
Unused model evaluations in Permutation explainer.

### ISSUE THREAD

**Issue by gablabc** [shap/shap#2087]
Hi, 
I am really enjoying the SHAP library, and for a while, my curiosity has driven me to analyse and understand its source code.

Currently I have been studying the Permutation explainer  and I think I found out a little problem. At the following lines https://github.com/slundberg/shap/blob/master/shap/explainers/_permutation.py#L104-L108

It appears that the same code is repeated twice. From what I understand, the intent was to have the first for-loop compute marginal contributions of the features when going forward (the first half of the rows of the array "outputs"),
and a second for-loop to compute the marginal contributions when going backward (second half of the rows of the array "outputs"). The way the code is currently implemented, the second half of the rows of "outputs" is never used. This could be sub-optimal because "outputs" stores the results of multiple model evaluations and some of them are never used when computing the Shapley values.

I just wanted to make sure that this is actually an issue and that I am not misunderstanding the code.
Thank you very much.

**Comment by sander-sn** [comment]
I've reported this in #1948 with proposed fix in #1949. This is indeed an issue for the Permutation Explainer, but it has unfortunately not been addressed yet.

**Comment by gablabc** [comment]
Thank you for bringing this to my attention. I hope that your fix gets implemented soon into shap.
