### ISSUE TITLE
Tree SHAP Sum of SHAP Values

### ISSUE THREAD

**Issue by jonathanbd135** [shap/shap#2098]
Hi,

From what I understand, the sum of SHAP values for a given instance for Random Forest Tree explainer should sum up to the probability output of the model on the instance, i.e. sum(shap_values(instance)) == predict_proba(instance).

From what I can see, this does not occur but rather the sum of the SHAP values is equal to predict_proba(instance) - base_value

Can you please explain the reason for this / how do I get SHAP values who do sum up to the probability?
Thank you very much!

**Comment by c56pony** [comment]
According to [lundberg2020](https://www.nature.com/articles/s42256-019-0138-9), the sum of feature attributions <img src=
"https://render.githubusercontent.com/render/math?math=%5Ctextstyle+%5Cphi_i%5Cleft%28f%2Cx%5Cright%29%0A" 
alt="\phi_i\left(f,x\right)
"> matches the original model output <img src=
"https://render.githubusercontent.com/render/math?math=f\left(x\right)">.
<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0Af%5Cleft%28x%5Cright%29%26%3D%5Cphi_0%5Cleft%28f%5Cright%29%2B%5Csum_%7Bi%3D1%7D%5E%7BM%7D%5Cphi_i%5Cleft%28f%2Cx%5Cright%29++%5C%5C+%0A%26%5Cmathrm%7Bwhere%7D%5Cquad%5Cphi_0%5Cleft%28f%5Cright%29%3DE%5Cleft%5Bf%5Cleft%28x%5Cright%29%5Cright%5D%0A%5Cend%7Balign%2A%7D%0A" 
alt="\begin{align*}
f\left(x\right)&=\phi_0\left(f\right)+\sum_{i=1}^{M}\phi_i\left(f,x\right)  \\ 
&\mathrm{where}\quad\phi_0\left(f\right)=E\left[f\left(x\right)\right]
\end{align*}
">
So, 
```
shap_values = shap.TreeExplainer(model)(X)
np.allclose(shap_values.values.sum(axis=1) + shap_values.base_values, model.predict_proba(X))
```
is True.
