### ISSUE TITLE
Does this work with multi-class classification (a Keras NN model)

### ISSUE THREAD

**Issue by rastash** [shap/shap#21]
I'm following your notebook with the NN example. My model output is a soft-max over some number of classes. I define the `f` in your notebook as below:
```
def f(X):
    return model.predict(X)
```
The call to `explainer.explain` succeeds. However, the call to `visualize` fails, with the error:
```
/usr/local/lib/python2.7/dist-packages/iml/visualizers.pyc in __init__(self, e)
    110         # build the json data
    111         features = {}
--> 112         for i in filter(lambda j: e.effects[j] != 0, range(len(e.data.group_names))):
    113             features[i] = {
    114                 "effect": ensure_not_numpy(e.effects[i]),

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
A simple fix?

**Comment by slundberg** [comment]
Unfortunately the visualizations are not currently designed to display multi-class outputs. So you will need to directly plot/use the `effects` property of the returned explanation object.

**Comment by slundberg** [comment]
Just for future reference I added an ImageNet example with multi-class outputs: https://slundberg.github.io/shap/notebooks/ImageNet+VGG16+Model+with+Keras.html
