### ISSUE TITLE
Additional supported ops

### ISSUE THREAD

**Issue by mdaniluk** [shap/shap#211]
Is it possible to add following operations :
* `Maximum`
* `Square`
* `AvgPool`
* `FusedBatchNorm`
?

**Comment by slundberg** [comment]
Just pushed a new refactored DeepExplainer that supports all these ops. I still need to test `FusedBatchNorm` though, so if you run into issues let me know! The changes will land in v0.23 and are on github now.

**Comment by mdaniluk** [comment]
Thanks for that! However, during computing shap values for the model with ResNet architecture (which use  `FusedBatchNorm` and `AvgPool`) have  now following error:
`TypeError: custom_grad() takes exactly 3 arguments (7 given)`

**Comment by slundberg** [comment]
Sorry that still didn't work, and for helping sort through the issues. I have run it on ResNet50 and it worked for me. Could you share the versions you are using of TF (and Keras if you use it) along with shap?
