### ISSUE TITLE
Can the number of samples passed to the explainer affect the shap value results?

### ISSUE THREAD

**Issue by Shadz13** [shap/shap#2119]
Suppose we have the following code:

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(rec_feat)  

The model is a lgbm classifier and rec_feat is a single row from the test dataframe. Shap values will be used to generate a single force plot and view the important features of rec_feat.

I am curious to understand the effect of passing a single row versus a subset of the dataframe (approx. 10k) containing rec_feat. Would the shap value change in these two scenarios?

NB: I am not evaluating summary plot, just the local instances.

**Comment by c56pony** [comment]
The value of SHAP does not change depending on the number of samples to be calculated. The interpretation is based on the learned model.
