### ISSUE TITLE
Scatter Colour with a Feature Not in the Training Data

### ISSUE THREAD

**Issue by jamesellis1999** [shap/shap#2128]
How do I colour a scatter plot with a feature that my classifier wasn't trained on?

**Comment by c56pony** [comment]
You can use `np.ndarray` or `shap.Explanation`.
The simplest way to color with a feature (ex. random numbers) is to use `np.ndarray`.
```
shap_values = shap.TreeExplainer(model)(X)
random_number = np.random.rand(X.shape[0])
shap.plots.scatter(shap_values[:, "Relationship"], color=random_number)
```
![image](https://user-images.githubusercontent.com/40843206/128940317-6c306acf-8662-4a7c-9ea0-295f2d9cc5c2.png)
If you want to label the color bar, use `shap.Explanation`.
```
random_col = shap.Explanation(values=random_number, base_values=None, data=random_number, feature_names='random')
shap.plots.scatter(shap_values[:, "Relationship"], color=random_col)
```
![image](https://user-images.githubusercontent.com/40843206/128940711-4c38bbcd-b26a-4e12-8113-c22c1d24671e.png)

**Comment by jamesellis1999** [comment]
Amazing thank you so much! 

This would be a great example to put in the documentation. 

_scatter.py could also specify that it accepts numpy arrays as input for colour.
