### ISSUE TITLE
Prediction from Light GBM not matching with that in Force Plot

### ISSUE THREAD

**Issue by deba-ds** [shap/shap#2135]
Used Light GBM predict_proba function to get predicted probabilities. And, using link="logit" to get probabilities in Force plot, but these two are not matching. Can you help?

**Comment by chloe-wang** [comment]
I'm facing the same issue. Besides, the probability calculated by force plot does not match the score predicted by the model.

**Comment by ryanwild7** [comment]
Same issue with xgboost

**Comment by alstjq3** [comment]
I have same issue, too.
