### ISSUE TITLE
Waterfall plot .base_values error

### ISSUE THREAD

**Issue by jordanvasseur** [shap/shap#2140]
Whilst trying to plot a waterfall ploit with my trained model i get the following exeption error:

````
shap.waterfall_plot(shap_values)

Exception: waterfall_plot requires a scalar base_values of the model output as the first parameter, but you have passed 
an array as the first parameter! Try shap.waterfall_plot(explainer.base_values[0], values[0], X[0]) or for multi-output 
models try shap.waterfall_plot(explainer.base_values[0], values[0][0], X[0]).

````

Then when i try to plot using the recommended approach i get the following error:

````
shap.waterfall_plot(shap_values.base_values[0], shap_values[0],X_validate_dense[0] )

AttributeError: 'numpy.ndarray' object has no attribute 'base_values'

````

It seems that the base values are extracted within the function waterfall_plot() even though the recomendation states you should enter the base values as parameter. I presumed it would work seamlessly since the Explanation output looks just like any other example I have found on the internet:

![image](https://user-images.githubusercontent.com/79868296/129558823-58f5ef0e-046e-4713-802c-d9b51b13bdf0.png)

 Is it possible to solve this error or does a workaround exist?

**Comment by stonezhng** [comment]
If you look at `shap/shap/plots/_waterfall.py`, there are two methods, one is `waterfall`, the other is `waterfall_legacy`. The `waterfall` method weirdly accepts a `shap_value` class object which can be found nowhere in the code. I guess the developers want to integrate all necessary values in this new class object but have not released the new code yet. 

 The other method `waterfall_legacy` works as documented, you manually pass the shap value, base value, etc. So my solution is to go to the source file indicated in the error log, swap the name of the two methods, thus shap.waterfall_plot will be fooled to call `waterfall_legacy`, doing the plot with all the figures you pass to it.

**Comment by ianozsvald** [comment]
Thanking @stonezhng for the tip, I iterated and found the following to work (using today's installation of `shap` via conda forge):
```
import shap
shap.__version__ # '0.39.0' installed today via conda forge
explainer = shap.Explainer(est) # est is a sklearn RandomForestRegressor
shap_values = explainer(X_test[:5]) # explain first 5 only

from shap.plots import _waterfall
_waterfall.waterfall_legacy(explainer.expected_value[0], shap_values[0].values, X_test.iloc[0])
```
where `X_test` is a Pandas Dataframe (hence using `.iloc`).

**Update** today (2021-11) I've installed version `0.40.0` from `conda` and the same issues persists (I'm using a different dataset, regression again).

**Comment by plpxsk** [comment]
> Thanking @stonezhng for the tip, I iterated and found the following to work (using today's installation of `shap` via conda forge):
> 
> ```
> import shap
> shap.__version__ # '0.39.0' installed today via conda forge
> explainer = shap.Explainer(est) # est is a sklearn RandomForestRegressor
> shap_values = explainer(X_test[:5]) # explain first 5 only
> 
> from shap.plots import _waterfall
> _waterfall.waterfall_legacy(explainer.expected_value[0], shap_values[0].values, X_test.iloc[0])
> ```
> 
> where `X_test` is a Pandas Dataframe (hence using `.iloc`).
> 
> **Update** today (2021-11) I've installed version `0.40.0` from `conda` and the same issues persists (I'm using a different dataset, regression again).

Users may prefer `explainer.expected_value[1]` for binary predictions where they want predicted probabilities for class "1" (instead of for class 0)
