### ISSUE TITLE
Tree Shap gives extremely high shap values while Kernel Shap doesn't

### ISSUE THREAD

**Issue by GrimLefourbe** [shap/shap#215]
Hello there,

I have recently been trying to evaluate SHAP and its reliability. In order to do this, I've been generating datasets with random values and labeled them according to arbitrary conditions (eg: feature_0 < 0.05, feature_1 < 0.95). I have then fitted a RandomForestClassifier from sklearn on the data and explained its predictions. It has worked fairly well for boolean conditions.

I think I ran into what seems to me like a bug with the Tree Shap algorithm. With a condition that includes an addition, the classifier starts having difficulties to predict. In turn, the TreeExplainer starts producing extremely high values while the KernelExplainer outputs values in the usual range. The Kernel Explainer is able to definitively point to the relevant features as showcased in its summary plot while the Tree Explainer's summary plot is much less definitive in its responsibilities.

Tree SHAP summary plot
![image](https://user-images.githubusercontent.com/17729035/44038945-39293e90-9f18-11e8-88a7-ccfb1098453d.png)

Kernel SHAP summary plot
![image](https://user-images.githubusercontent.com/17729035/44038964-4a633710-9f18-11e8-89c4-07e5dde3c0ba.png)

Is this expected? Is it a predictable behavior for the algorithm ?

I have also included a jupyter notebook with the necessary code for data/feature generation and other code required to reproduce the issue.

[Shap Values Tree vs Kernel.ipynb.zip](https://github.com/slundberg/shap/files/2283384/Shap.Values.Tree.vs.Kernel.ipynb.zip)

Please, let me know if you need details on how to reproduce this.

Thanks for your time and your work.

**Comment by slundberg** [comment]
Thanks for sharing your comparison! It does look like something is strange about the TreeExplainer output in your example. When I downloaded your notebook to reproduce the problem it went away if I set the model's `max_depth` to 10. This makes me think it is an instability coming from the really deep RF trees that you are building.

I am going to leave this issue open until I track down where there was an issue.

**Comment by litanli** [comment]
Hi Scott,
Any luck figuring out where this issue is coming from? I ran into the same issue using TreeExplainer(), got really high SHAP values.

**Comment by slundberg** [comment]
Just looking into it again now, and still trying to track it down. It only randomly happens with very specific (and large) trees.

**Comment by litanli** [comment]
Thanks for looking into this Scott, appreciate this tool!

I'm going to try limiting max_depth to see if that works. Do you have more specific thoughts about what causes values to be large other than trees being deep? You mention randomly, does this mean you've seen cases with large trees that doesn't run into this issue? Was there anything noticeably different about those?

**Comment by slundberg** [comment]
I have only seen it for very deep trees. By "randomly" I mean that if I try and make a simpler model that still has the same issue it goes away. You can always check to make sure things are good by checking that the sum of the SHAP values equals the margin output of the model (minus the expected value).

**Comment by slundberg** [comment]
After looking at this more it does seem to be a floating point prescision issue. I’ll post a note here when I finish implementing a more numerically stable way that fixes this.

**Comment by andrewortman** [comment]
Hi @slundberg, did you ever get around to thinking about solving this? I can probably help if you can provide some helpful pointers :)

**Comment by slundberg** [comment]
Thanks for the offer @andrewortman! I decided the best option right now was to add a check into the code to see when additivity is violated. Since this check is turned on by default, it should catch most things. If a numerical precision issue comes up then we suggest users try the feature_dependence="independent" option. This uses a different more numerically stable algorithm that is better suited to deep trees. If you are still interested in helping, I would appreciate someone looking over the new check_additivity option I added to TreeExplainer. Right now it only checks when the model's output is the margin, and it does not check LightGBM and CatBoost native explainers at the moment.

**Comment by marco-c** [comment]
I'm hitting this too, but:
- I'm using feature_dependence="independent";
- the additivity check you added is not failing.

**Comment by slundberg** [comment]
@marco-c  could you clarify the problem? If additivity is passing then it is probably working correctly.

**Comment by marco-c** [comment]
I can no longer reproduce, weird. I'll report back if I can reproduce again.
