### ISSUE TITLE
Merge Shap (Permutation) explanation

### ISSUE THREAD

**Issue by Kh-im** [shap/shap#2151]
Hello,

Let's say I have a dataset split in two parts (A & B) and one model trained on the whole dataset. I use permutation explainer on A and after on part B to generate explanation_A and explanation_B.

Can I merge the two explanations  and show a merged beeswarm for example ? If yes, what is the strategy to do that ?

THanks

**Comment by JeremiasBohn** [comment]
Explanations basically work the same as numpy arrays, so you should be able to concatenate the Explanation objects. However, this is very inefficient as numpy concatenations are not in-place, therefore a new memory block has to be allocated to which both previous arrays have to be copied to.
It would be nice if one could select the underlying structure of the explanation object somehow as it is extremely tedious to work with these objects if you don't only want to print them with the options provided by the shap library.
