### ISSUE TITLE
Figures in "Be careful when interpreting predictive models in search of causal insights" are not found

### ISSUE THREAD

**Issue by erikr** [shap/shap#2152]
The figures at [Be careful when interpreting predictive models in search of causal insights](https://shap.readthedocs.io/en/latest/example_notebooks/overviews/Be%20careful%20when%20interpreting%20predictive%20models%20in%20search%20of%20causal%C2%A0insights.html) do not render:

![CleanShot 2021-08-25 at 12 03 09](https://user-images.githubusercontent.com/1253422/130825323-38e573e3-d1fe-4458-8ad3-0d8ee2843e3c.png)

Right-clicking and selecting `Open image in new tab`, e.g. https://shap.readthedocs.io/en/latest/example_notebooks/overviews/_build/doctrees/nbsphinx/example_notebooks_overviews_Be_careful_when_interpreting_predictive_models_in_search_of_causalinsights_5_0.png, results in the following:
![CleanShot 2021-08-25 at 12 03 42](https://user-images.githubusercontent.com/1253422/130825410-02a05238-3e8a-4909-88ee-3711dc3d3f29.png)

**Comment by mtdmo** [comment]
Seeing this as well. Good to pull those figures in please 😅
