### ISSUE TITLE
numpy aliases of python builtin functions are deprecated

### ISSUE THREAD

**Issue by gw00207** [shap/shap#2159]
https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

using the aliases of builtin types e.g. np.float is deprecated. using shap in other projects that require numpy 1.20.0 therefore raises warnings.

**Comment by gw00207** [comment]
https://github.com/slundberg/shap/pull/2048

**Comment by connortann** [comment]
Closing as duplicate
