### ISSUE TITLE
Force plot not displaying 

### ISSUE THREAD

**Issue by zahs123** [shap/shap#2167]
Hi i am using VSCODE and am running this code to get a forceplot for a multclassification problem: 

```
def shap_report(pipe,data):
    #explainer = shap.TreeExplainer(model)
  
    explainer = shap.TreeExplainer(pipe.named_steps["clf"])
    shap_values = explainer.shap_values(pipe[:-1].transform(data))
    data_1 = pd.DataFrame(pipe[:-1].transform(data))
    plt.figure()
    shap.force_plot(explainer.expected_value[0], shap_values[0][0], data_1.iloc[0,:], show=False)
    plt.savefig('tester.png')
    plt.show()
    shap.summary_plot(shap_values[0], pipe[:-1].transform(data), plot_type="bar", class_names= [0,1,2,3])
```

my output is  blank. What am i doing wrong in the above?

I also tried to add matplotlib = True to above but i get this error: 
`umpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')` e.g. 

![image](https://user-images.githubusercontent.com/23192374/132531012-f6e8986b-b071-45a9-a061-34a8e8f91b03.png)

how can i get this plot to work

**Comment by IF-A-CAT** [comment]
Just use the API shap.save_html() to save the output of shap.plots.force(),and open it with Chrome or Edge
