### ISSUE TITLE
Im getting this error .I dont Know how to solve it

### ISSUE THREAD

**Issue by sanjayroshan017** [shap/shap#2168]
![error](https://user-images.githubusercontent.com/85353660/132538337-4d24079f-e847-4249-9c92-1beea3ad0de5.PNG)
![error](https://user-images.githubusercontent.com/85353660/132538536-256c0746-17fd-4a43-86d0-35b14c79da2c.PNG)

what packages should i install to use fit_model

**Comment by mukul-data** [comment]
Have you imported fit_model?
