### ISSUE TITLE
How to improve the speed of Kernel Explained?

### ISSUE THREAD

**Issue by dongdyang** [shap/shap#217]
How to improve the speed of Kernel Explained ?

I see that it processes one sample by one sample.
Are there any ways to do it faster, such as batch?

Thanks for answering!!!

**Comment by slundberg** [comment]
#200 should help here a lot by speeding up the building of internal matrices. It does build it's internal matrix one by one, but it calls the model function with a batch. So with #200 moving some of these steps to numpy things should get better.

**Comment by GrimLefourbe** [comment]
As an added note to this, I have tested the number of redundant calls made during a batch of explanations, here are the results I got:
To explain 1441 examples, 2882 calls to predict were made for a total of 14 699 641 predictions. 
Of those 14 699 641, there were 10 941 477 unique ones which means 3 758 164 were redundant.
If confirmed, that's about 25%, it's pretty significant and, I think, worth looking into if trying to speed up the KernelExplainer.

**Comment by dongdyang** [comment]
I'm not quite understanding that #200. Is it talking about squeezing the features into shorter vector, right?

Follow up question is, what do you mean by batch? Can you elaborate it?

Thanks!

**Comment by slundberg** [comment]
@tonnkie each sample in the dataset is explained one at a time, but many evaluations of the model (2000 by default) are done to explain each of those instances. Those evaluations are passed the model as a batch.

#200 just moves some processing from python to numpy to get faster execution.

@GrimLefourbe ...hmmm. Could you see if you get the same redundancy for a single sample? There should not be very many redundant calls by KernelExplainer to the model (only when we randomly sample the same set). If you have lots of samples that can have similar inputs you could consider wrapping you model evaluation function in a memoize function.

**Comment by GrimLefourbe** [comment]
Here's a notebook showing my results. The redundancy is much less significant on randomised data than it was in my previous tests but I assume it would behave worse on real data.

Unexpectedly, there still seems to be redundancy when explaining a single sample.

[SHAP Values Call overlap.ipynb.zip](https://github.com/slundberg/shap/files/2302275/SHAP.Values.Call.overlap.ipynb.zip)

I find about 6.5% of the samples to be redundant when explaining random data.

**Comment by slundberg** [comment]
@GrimLefourbe thanks for the notebook! I fixed the double call during instantiation, though that is not really going to effect things much. The real redundancy is coming from the random sampling process. Whenever there are enough samples to fill out all subsets of a given size it will do that (and so eliminate redundant samples), but if you don't have quite enough samples for a given subset size then it can't fully enumerate them, yet it is still easy to draw redundant samples.

The best fix would be to check for redundant samples when adding the samples, but I am not sure if using a dictionary would be fast enough for all use cases. I'll leave this issue open to note it is a possible improvement.

**Comment by slundberg** [comment]
I decided the dictionary would be fast enough applied to the varying groups mask, so now the latest master shows zero redundant calls.
