### ISSUE TITLE
Cannot install shap on pycharm

### ISSUE THREAD

**Issue by Hysmane** [shap/shap#2179]

**Comment by Hysmane** [comment]
pip install shap
does not work.
Thanks!!

**Comment by cbelitz** [comment]
I had a problem installing shap and found some help on this thread: https://github.com/actions/setup-python/issues/165

I needed to `pip install numpy` first and was then able to `pip install shap`

**Comment by Hysmane** [comment]
Thank you very much!!!!!!!!!
    Le lundi 27 septembre 2021, 23:23:55 UTC+2, Clara Belitz ***@***.***> a écrit :  
 
 


I had the same problem and found some help on this thread: actions/setup-python#165

I needed to pip install numpy first and was then able to pip install shap

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jonnor** [comment]
It looks like this problem has been resolved. Issue can be closed. CC @slundberg
