### ISSUE TITLE
Base and expected value in SHAP using isolation forest are outside [0, 1]

### ISSUE THREAD

**Issue by yqiu19** [shap/shap#2180]
Hi @slundberg,

I built an isolation forest model to detect anomalies and after I plot SHAP values, I noticed the expected and base values are too big:

<img width="1962" alt="WeChatf28cf92a45fbd8670789c059bb2b9454" src="https://user-images.githubusercontent.com/54509577/133457294-d91dcd8b-6822-4b42-b498-d266b4c30993.png">
<img width="1980" alt="WeChatebc0e7973c7b8de753e6a2179b7900c7" src="https://user-images.githubusercontent.com/54509577/133457309-1a96e3f4-707a-4d6e-8af0-9169c50e7594.png">

I wonder why does this happen and is there any way to solve this? Thanks!

**Comment by DiTian1993** [comment]
explainerModel1 = shap.TreeExplainer(iforest2, model_output = 'probability')

This should return the probability to you.
