### ISSUE TITLE
AttributeError: 'Kernel' object has no attribute 'masker'

### ISSUE THREAD

**Issue by luizhemelo** [shap/shap#2182]
Hi everyone!!!

I'm trying to define an explainability analysis for the "_sklearn.neighbors.KNeighborsRegressor_" and "_sklearn.svm.SVR_" models, with later obtaining explainer objects (which contain the shap values, the base values, and the data used), which will enable the plotting of _Beeswarm_ graphs.

```
x = pandas.read_csv('dataset.csv')

X_train_summary = shap.kmeans(x, 5)
background = shap.maskers.Independent(x)
explainer = shap.KernelExplainer(model.predict, X_train_summary, masker=background)
explainer_obj = explainer(x)

shap.plots.beeswarm(explainer_obj)
```

However, when running "_explainer(x)_" I am getting the following error:

```
AttributeError: 'Kernel' object has no attribute 'masker'
```

I have not been able to solve this problem at all, and I would be grateful if someone could help me.

_Specifications:
python==3.8.0
shap==0.39.0_

**Comment by bh-sujit-ahirrao** [comment]
Is there any update on this @luizhemelo ?

**Comment by luizhemelo** [comment]
Officially, no :(
But I simply used the Summary Plot function, which plots the way I want. Here's how it can be done:

```
shap.summary_plot(shap_values, X)
```

**Comment by gcoter** [comment]
I think I have the same issue with the Isolation Forest from sklearn. Here is the pseudo code of what I do:
```
model = IsolationForest()
explainer = KernelExplainer(
    model=model.decision_function,
    data=X_training.sample(n=100),
)
shap_values = explainer(X=X)
```

Then I get this error: `AttributeError: 'Kernel' object has no attribute 'masker'`

**Comment by juancq** [comment]
I am also having this issue. I worked around it by not using a shap Explanation object and passing the raw shap values to the summary plot. 
shap 0.40.0
python 3.9.9

Any plans to fix this in the code base?

**Comment by remo-help** [comment]
The KernelExplainer does not generate Explanation objects because of the masker error.

If you still want the full range of plots, you can generate an Explanation object manually, since the KernelExplainer does allow you to generate shap-values:

```
x = pandas.read_csv('dataset.csv')

X_train_summary = shap.kmeans(x, 5)
background = shap.maskers.Independent(x)
explainer = shap.KernelExplainer(model.predict, X_train_summary, masker=background)

shap_values = explainer.shap_values(X_train_summary)

explanation = shap.Explanation(shap_values, data=X_train_summary, base_values=explainer.expected_value, feature_names=OPTIONAL)


shap.plots.beeswarm(explanation)
```
To get the full range of plots you may have to generate an array of base_values with an equal number of values as your data, in this hack you only give it one base value.

Hope this helps someone.
