### ISSUE TITLE
Error in Explaining a linear regression model?

### ISSUE THREAD

**Issue by BAREJAA** [shap/shap#2184]
Hi,

I came across this in the linear regression explainer - 

"If for example we were to measure the age of a home in minutes instead of years, then the coefficients for the AGE feature would become 0.0007∗365∗24∗60=367.92."

Wouldn't this mean that a one-unit increase in age-in-minutes would have a 365∗24∗60 greater effect than a one-unit increase in age-in-years? So the coefficient for age-in-minutes should instead be  0.0007/(365∗24∗60), correct? 

Apologies if I'm making some trivial error

**Comment by reedless** [comment]
You're absolutely right, see #1587
