### ISSUE TITLE
AssertionError: Minimum is not known to be either linear or a supported non-linearity!

### ISSUE THREAD

**Issue by amirjalilifard** [shap/shap#219]
Hey,
I created a Deep Recurrent Neural Network model using Keras. Then I passed the model to Shap as following: 

```
num_layers = 3
num_hidden = 64 
layers = [GRU(num_hidden, return_sequences=True) for i in range(num_layers-1)]
layers += [GRU(num_hidden)]
layers += [Dense(40, activation='softmax')]

model.fit(X_train[0], np_utils.to_categorical(y_train[0]), epochs=300, validation_data=(X_test[0], np_utils.to_categorical(y_test[0])))
```
The model is working and is returning the classification results, yet I get the below error when I want to use:
`
explainer = shap.DeepExplainer(model, X_train[:100])`

**ERROR:**

/mnt/hd0/amir/anaconda/lib/python3.6/site-packages/shap/explainers/deep.py in __init__(self, model, data, session, learning_phase_flags)
    192                     assert False, op.type + " is not known to be either linear or a supported non-linearity! " + \
    193                                   "Please post this as a GitHub issue so " + op.type + " can potentially be " + \
--> 194                                   "included in the list of supported ops."
    195 
    196         if not self.multi_output:

**_AssertionError: Minimum is not known to be either linear or a supported non-linearity! Please post this as a GitHub issue so Minimum can potentially be included in the list of supported ops._**

What should I do to solve this problem?

**Comment by slundberg** [comment]
This should be fixed now in v0.23, but note that #225 means there is still some numerical issue somewhere I need to track down.
