### ISSUE TITLE
3D convolutional nueral networks

### ISSUE THREAD

**Issue by xuzhang5788** [shap/shap#220]
Is it possible to explain the binary classification model using the 3D convolutional neural network? Many thanks

**Comment by slundberg** [comment]
Yep, in TensorFlow or Keras you can pass any input tensor and output tensor to GradientExplainer or DeepExplainer. The trick with 3D conv networks is making sure everything fits into GPU ram.

**Comment by xuzhang5788** [comment]
Thank you @slundberg 

I still don't how to use your GradientExplainer and DeepExplainer to my problem. 

I built a 3D convolutional neural network. My training data's shape is like (nbex, gx, gy, gz, nbchannel). My data are not images, so nbchannel is not 3, is 30.  Because my data are not images, so it is hard to visilize. My problem is that I don't know if my model learned the right thing although my evaluation metrix gave us the good number and I don't think my model was overfitting. 

Any advice for me to use your library to explain my model correctly? Many thanks.

**Comment by slundberg** [comment]
Have you tried passing the input and output tensors as a pair to DeepExplainer or GradientExplainer like in the ReadMe examples? Once you have the attributions from calling `shap_values` you can visualize that however you want, though as you say `image_plot` would probably only work if you passed just a slice.

**Comment by xuzhang5788** [comment]
Thank you @slundberg 
I tried your DeepExplainer and GradientExplainer using input and output tensors. However, I am so confused about shap_values. May I use shap.force_plot for non-image data? It will be great if you have a document.

**Comment by slundberg** [comment]
Sorry I have had time to write full docs yet. That shap values are feature attributions and are the same shape as your model inputs. `force_plot` only works for 1d inputs, so you could flatten a single sample if you want and it should happily plot it.
