### ISSUE TITLE
Implementation for Multivariate Time Series Data

### ISSUE THREAD

**Issue by muhmmadzs** [shap/shap#2206]
Is it possible to use SHAP for multivariate time series classification examples? For example when we FCN model with multivariate data.

Thank you 
Your Response will be highly appreciated

**Comment by jagandecapri** [comment]
I am interested to know too whether multivariate time series data is supported. Specifically, I am working on a time-series classification where the data is of the shape `(samples, sequences, features)`.

**Comment by JichenGuo** [comment]
> I am interested to know too whether multivariate time series data is supported. Specifically, I am working on a time-series classification where the data is of the shape `(samples, sequences, features)`.

same question. Have you solved it yet :)

**Comment by jagandecapri** [comment]
@Jichen66 Nope, I was not able to solve it.

**Comment by eschibli** [comment]
There is a [fork](https://github.com/conrad-blucher-institute/shap) and [pull request](https://github.com/slundberg/shap/pull/1944) from Texas A&M that modified PartitionExplainer to allow for channel-wise partitioning of images. It should be possible to modify this to work with times series. 

I am hoping to investigate this early next month and will let  you know if I have any success.

**Comment by CCapinha** [comment]
That would be a major achievement. Thanks for time/effort.
