### ISSUE TITLE
Shap values are corrupted when 2x Beeswarm plot is executed

### ISSUE THREAD

**Issue by JEwerszumrode** [shap/shap#2207]
It seems that using `shap.plots.beeswarm(shap_values)` manipulates the shap values itself.
If you're run the same command twice, it results in 2 way diffrent plots. For Summary plot I haven't this issue.
In my case for one random feature the shap values increased significantly.

**Comment by lacava** [comment]
duplicate of #1970 

short term solution is to deep copy the Explanation:
```
import copy
shap.plots.beeswarm(copy.deepcopy(shap_values))
```

**Comment by thatlittleboy** [comment]
Closing as duplicate
