### ISSUE TITLE
Publishing automated wheels on PyPI

### ISSUE THREAD

**Issue by jklaise** [shap/shap#2230]
With the automated wheel building workflow which gives wheels for a range of systems (see Artifacs: https://github.com/slundberg/shap/actions/runs/1364867953) it would be very useful to include wheel uploading into the release process on PyPI. I guess the current process to publish is using the `deploy` job via Travis: https://github.com/slundberg/shap/blob/429fb3e0ac2ef179f1cff7e1a64b4f7b26f41eb5/.travis.yml#L27-L36
This could be extended to upload the artifacts generated after manually triggering the Github action.

This would be extremely useful to get pre-built wheels on Linux and MacOS by just running `pip install shap` avoiding the build process. I see that `cibuildwheels` makes `manylinux` wheels by default, so it would also resolve #1383.

**Comment by dashtagger** [comment]
Hi can anyone guide me on how exactly do I build the linux version of shap? I don't understand how to use this travis file.

Else if any one can direct me to a manylinux distribution whl file of shap it would be much appreciated.

**Comment by jklaise** [comment]
@dashtagger you can download pre-built wheels of version 0.40 on here (under artifacts - bdist_files): https://github.com/slundberg/shap/actions/runs/1364867953 . It's just that you have to manually download them as they're not published on PyPI (which is why I opened this issue).
