### ISSUE TITLE
Typo in plots/_waterfall.py

### ISSUE THREAD

**Issue by partiallycomplex** [shap/shap#2235]
In _waterfall.py at line 4 pyplot is aliased as pl, but is called as plt and as pl

**Comment by DouglasMesquita** [comment]
Hi. I had the same problem here. 

For now, a workaround is:

`
import matplotlib.pyplot as plt
global plt

shap.plots.waterfall(shap_values=shap_values[0], show=False)
plt.show()
`

**Comment by thatlittleboy** [comment]
Fixed by bd820c7.
