### ISSUE TITLE
_transformers_pipeline.py - Official Support Request for the Huggingface Zero-Shot Classification Pipeline 

### ISSUE THREAD

**Issue by PeterKczyk** [shap/shap#2236]
To prevent a workaround like [stackoverflow](https://stackoverflow.com/questions/69628487/how-to-get-shap-values-for-huggingface-transformer-model-prediction-zero-shot-c) I recommend to edit `_transformers_pipeline.py` accordingly and build a script.

**Comment by Greco1899** [comment]
+1. This would be really helpful!
