### ISSUE TITLE
Unknown algorithm type passed: deep!

### ISSUE THREAD

**Issue by javirandor** [shap/shap#2248]
According to the docs, when initializing an Explainer for a model using the class `shap.Explainer`, "deep" can be used as value for the attribute "algorithm" to create a DeepExplainer. However, when trying to do so the following error raises

`Unknown algorithm type passed: deep!`

I see that this is not implemented in the source code for the class. I guess it should be removed from doc or included in the initialization of the Explainer class.

Thanks.

**Comment by javirandor** [comment]
Proposed solution in: #2249

**Comment by connortann** [comment]
I believe this is now fixed, as the docstring does not include "deep" as a option:

https://github.com/shap/shap/blob/master/shap/explainers/_explainer.py#L55
