### ISSUE TITLE
What is the difference between Shapley values and shapley interaction values?

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#227]
Could you please tell me,
1.What is the difference between Shapley values and shapley interaction values? 
2.Difference between dependency plots and interaction plots. (What are the values that y axis denoted and what is the differnce between those values?)

Thank You,

Best Regards,
Dilini

**Comment by slundberg** [comment]
The Tree SHAP arXiv paper has a more complete description, which I won't repeat here. But while Shapley values allocate the credit among the all the features, Shapley interaction values allocate credit among all pairs of features. This means that SHAP interaction values give you the main effects of features along the diagonal and the pairwise interaction effects on the off-diagonals. So an interaction plot will show how impact of the second order interaction between two features changes.

**Comment by DiliSR** [comment]
I read that paper now. Thank you very much for your explanation. 
So the conclusion is interaction plots is more accurate than the dependency plots, when we need to know how the shap value varies when the value of two features are changing.

Thank you.

**Comment by roshankoirala** [comment]
> This means that SHAP interaction values give you the main effects of features along the diagonal and the pairwise interaction effects on the off-diagonals.

Is the diagonal main effect or second order self interaction? They seem to be different than the main effect we get from explainer.shap_values(X).
