### ISSUE TITLE
ModuleNotFound in waterfall plot

### ISSUE THREAD

**Issue by nevinbaiju** [shap/shap#2283]
In the waterfall plot script, matplotlib is imported as "pl". However in the code, "plt" is used which throws a modulenotfounderror.
Raised a pull request with the fix #2282.

**Comment by trianta2** [comment]
Ran into this issue today. Looks like a bug. Weird that a linter didn't catch this.

**Comment by nevinbaiju** [comment]
I think version 0.39 works fine. Or just trying the fix in #2282 will solve the issue.

**Comment by trianta2** [comment]
I'm just test driving the library, so a hack works for me:

```python
import matplotlib.pyplot as plt
shap.plots._waterfall.plt = plt
```

**Comment by nevinbaiju** [comment]
That looks like a cool workaround. :D
