### ISSUE TITLE
Recommendation on data sample to use for converting log-odds to proba

### ISSUE THREAD

**Issue by eduardcmp** [shap/shap#2284]
Hello,

I know a lot have been asked and responded about this topic but I'm looking for recommendation in terms of speed and precision.

I have built  a XGBoost binary classification model on a training dataset of 300k and I have to predict every month 200k observations. I'd like to have the contribution decomposition by feature in terms of probability (instead of default log-odds) and I've seen a data needs to be passed as kwarg. So here there're a couple things I don't understand:

Why probabilities can't be computed with feature_perturbation = "tree_path_dependant" which would be more efficient? 
Why can't I simply transform log-odds back to probability?

But my highest priority question is what data should I pass to the explainer.  Should it be a sample  from the training data without the target fea or it would be ok to sample from the test directly? Finally, what size would you recommend me (I've read the algorithm complexity is linear to the size of the sample)? 

Thanks in advance for all your work and the community you have built.

Edu

**Comment by eduardcmp** [comment]
Reading further I found it's been solved here #963

**Comment by Jing25** [comment]
> Hello,
> 
> I know a lot have been asked and responded about this topic but I'm looking for recommendation in terms of speed and precision.
> 
> I have built a XGBoost binary classification model on a training dataset of 300k and I have to predict every month 200k observations. I'd like to have the contribution decomposition by feature in terms of probability (instead of default log-odds) and I've seen a data needs to be passed as kwarg. So here there're a couple things I don't understand:
> 
> Why probabilities can't be computed with feature_perturbation = "tree_path_dependant" which would be more efficient? Why can't I simply transform log-odds back to probability?
> 
> But my highest priority question is what data should I pass to the explainer. Should it be a sample from the training data without the target fea or it would be ok to sample from the test directly? Finally, what size would you recommend me (I've read the algorithm complexity is linear to the size of the sample)?
> 
> Thanks in advance for all your work and the community you have built.
> 
> Edu

Have you figured out what data should be used? I'm also curious if the data should be training data or testing data
