### ISSUE TITLE
pyspark RandomForestRegressionModel save error AttributeError: 'TreeEnsemble' object has no attribute 'save'

### ISSUE THREAD

**Issue by trianta2** [shap/shap#2287]
I trained a `pyspark` `RandomForestRegressionModel` model and created an explainer:

```
model = ...  # train pyspark.ml.regression.RandomForestRegressionModel
explainer = shap.Explainer(model)
```

However, when trying to save the explainer:

```
with open('shaptest', 'wb') as file:
    explainer.save(file)
```

I get:

```
AttributeError: 'TreeEnsemble' object has no attribute 'save'
```

Digging around, the error is here: https://github.com/slundberg/shap/blob/9d7de4dee742ce10684400171257c66a86e4c7a6/shap/_serializable.py#L87

and `value` is of type `shap.explainers._tree.TreeEnsemble`, which is the type `shap` has defined and created/coerced from my `RandomForestRegressionModel`.

Is this expected behavior? User error? A bug?

**Comment by hipoglucido** [comment]
I have the same issue. In my case I find this error when I try log the tree explainer object to mlflow with [mlflow.shap.log_explainer](https://www.mlflow.org/docs/latest/python_api/mlflow.shap.html#mlflow.shap.load_explainer)

I don't know what to do...

**Comment by trianta2** [comment]
This was a while ago, but I believe I found that you can serialize/deserialize the explainer using regular 'ol `pickle`. I don't use `mlflow`, but if it lets you log arbitrary blobs, then just do a `pickle.dumps(obj)` on the explainer.
