### ISSUE TITLE
Waterfall plot doesn't work with uncertainty CatBoostRegressor model

### ISSUE THREAD

**Issue by ghost** [shap/shap#2289]
Hello,

I am currently trying to plot a waterfall plot with shap.
My model is a CatBoostRegressor:

```
model = CatBoostRegressor(depth=10, l2_leaf_reg=1, iterations=75, learning_rate=0.1,
                                               random_state=random_state, loss_function='RMSEWithUncertainty',
                                               posterior_sampling=True, od_type="Iter", od_wait=10)
```
The dataset I train it on is a standard dataset with a one-dimensional float target.

I explain the model as follows:
```
explainer = shap.TreeExplainer(model)                 
shap_values = explainer(df_for_shap)
```
When I try to plot a waterfall plot with

`shap.waterfall_plot(explanation)`

the program raises the exception

> Exception: waterfall_plot requires a scalar base_values of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.base_values[0], values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.base_values[0], values[0][0], X[0]).

When I print the `shap_values` variable, this is the output.

> .values =
> array([[[0.000],
>         [0.004],
>         [-0.003],
>         [0.000],
>         [0.003],
>         [0.006],
>         [-0.009],
>         [0.000],
>         [0.002],
>         [0.000],
>         [-0.014],
>         [0.000],
>         [0.001],
>         [0.004],
>         [0.016],
>         [-0.006],
>         [0.030],
>         [-0.024],
>         [-0.002],
>         [-0.022],
>         [-0.001],
>         [0.000],
>         [-0.003],
>         [-0.001],
>         [0.020],
>         [-0.007],
>         [0.006],
>         [0.006],
>         [-0.000],
>         [-0.000],
>         [0.002],
>         [-0.000],
>         [0.000],
>         [0.011],
>         [-0.001],
>         [0.007],
>         [0.001],
>         [0.006]]])
> 
> .base_values =
> array([[0.153]])
> 
> .data =
> array([[1.000, 0.000, 35000000.000, 97.000, 111.000, 70.050, 170.000,
>         520000000.000, 20800000.000, 7.000, 0.000, 0.000, 10.000, 4.000,
>         0.673, 25.000, 392.900, 0.500, 17.850, -1.000, 8.100, 15.810,
>         35.710, 0.000, -33.329, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000,
>         0.000, 0.000, 39.290, 0.000, 0.000, 6.000, 1.000]])

I tried many workarounds as the one mentioned in [this issue](https://github.com/slundberg/shap/issues/2255), but didn't have any luck. I even tried to make the numpy arrays from the ground up and assigning them to a helper object but the resulting plot was a `None`.

Any insights?

**Comment by ghost** [comment]
It seems that the custom object does work, but the returned variable is a `None` since I did not put `show = False` (I am not in a notebook environment). The problem is that in the source files there is a typo since the import statement is `import matplotlib.pyplot as pl` but if `show = False` it is referenced as `plt`. Please fix this!

**Comment by thatlittleboy** [comment]
> The problem is that in the source files there is a typo since the import statement is import matplotlib.pyplot as pl but if show = False it is referenced as plt. Please fix this!

The typo has been fixed in a previous PR.

And yes, for waterfall plot you'll need to plot for a single instance. Do `shap.plots.waterfall(shap_values[0])` instead of `shap.plots.waterfall(shap_values)`, where `shap_values = explainer(df_for_shap)` from your code.
