### ISSUE TITLE
SHAP for RNN many2many problem

### ISSUE THREAD

**Issue by makcedward** [shap/shap#229]
Thank you for the implementation. It is great work.

Recently, I am working on a seq2seq problems and it is a many2many problem. For example, the input is list of word while the output is the entity of those words. Not sure whether current release is able explain this type of problem.

**Comment by slundberg** [comment]
Thanks. The tricky part there is coming up with a good background reference distribution, and noting that if you have many outputs then you will have an explanation for each output. You could try just assuming a simple all-zeros reference value and seeing if that gives reasonable looking results. I'd be interested in how it works for you since I haven't tested on those model types yet.

**Comment by BruceBinBoxing** [comment]
> Thank you for the implementation. It is great work.
> 
> Recently, I am working on a seq2seq problems and it is a many2many problem. For example, the input is list of word while the output is the entity of those words. Not sure whether current release is able explain this type of problem.

Have you solved this problem?

**Comment by BruceBinBoxing** [comment]
> Thank you for the implementation. It is great work.
> 
> Recently, I am working on a seq2seq problems and it is a many2many problem. For example, the input is list of word while the output is the entity of those words. Not sure whether current release is able explain this type of problem.

@makcedward  Hi, have you solved problem?

**Comment by makcedward** [comment]
> > Thank you for the implementation. It is great work.
> > Recently, I am working on a seq2seq problems and it is a many2many problem. For example, the input is list of word while the output is the entity of those words. Not sure whether current release is able explain this type of problem.
> 
> @makcedward Hi, have you solved problem?

I tried but it cannot be explain unfortunately. Looking forward to have official support.

**Comment by slundberg** [comment]
@makcedward If you get a chance, sharing a simple (but compete) notebook example of what you are looking for would be helpful. Then when I (or someone else) gets time to look into this we can start with a concrete example.
