### ISSUE TITLE
How to plot force_plot of multiple samples?

### ISSUE THREAD

**Issue by VEZcoding** [shap/shap#2308]
I wish to save force_plot of multiple samples, but it saves blank png. When I try to do matplotlib = True I get an excepion:  `Exception: matplotlib = True is not yet supported for force plots with multiple samples! `

Any other ways to save the plot?

**Comment by mylg21** [comment]
你好，请问你的问题解决了吗？请指教

**Comment by zuokuijun** [comment]
I  also  get same  problem
