### ISSUE TITLE
Feature names get cropped 

### ISSUE THREAD

**Issue by Mahmedturk** [shap/shap#2309]
This question has been previously asked  in issue#1245 but the answer does not help me. I have long feature names which get cropped in the plots. How can i solve this issue?

**Comment by patebel** [comment]
You can set `show=false` in the respective plot  and then call `plt.tight_layout()` and `plt.show()` afterwards (having imported Matplotlib as `from matplotlib import pyplot as plt`). By doing so Matplotlib renders the plot such that nothing is cropped

**Comment by qwertyuu** [comment]
thanks @patebel ! You just showed me that shap used plt in the background so I can customize the plots all I want. This is very epic.
