### ISSUE TITLE
AssertionError in DeepExplainer

### ISSUE THREAD

**Issue by kilickursat** [shap/shap#2316]
Dear All,

I have applied the 1D-CNN Regression model for my dataset and I wanted to use Shap DeepExplainer for my neural network model but I have obtained the following error.
![deepexplainer error](https://user-images.githubusercontent.com/25801054/145743382-e8d1a503-a3dd-42d8-9a51-4752630d6752.png)

I would like to know how to solve that error, and could you please help me about it?

**Comment by gianmarco-terrones** [comment]
Try using a KernelExplainer instead of a DeepExplainer. It seems SHAP's DeepExplainer can't handle something in your ML model

**Comment by CloseChoice** [comment]
Thanks for your report and sorry for the late answer. Could you please provide a self contained reproducible example for us to look into?

**Comment by kilickursat** [comment]
Thanks for your reply. I even forgot I asked a question. I have figured it out.

**Comment by CloseChoice** [comment]
Thanks for the reply. If you encounter any more issues feel free to open an issue anytime.
