### ISSUE TITLE
watterfall plot didn't work with TreeExplainer

### ISSUE THREAD

**Issue by AvivaSimchon** [shap/shap#2317]
Hi
Thanks for all your explaination.
I want to use watterfall plot and I have some question:
1.if I have TreeExplainer I can't use watterfall plot.I succeded when I use Explainer.
2.why there is a difference between using force plot and watterfall plot?
for forceplot I just write:
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_train)
shap.force_plot(explainer.expected_value, shap_values[0,:], X_train.iloc[0,:])
For watterfall plot plot I need model.predict
explainer = shap.Explainer(model.predict, X)
shap_values = explainer(X)
shap.waterfall_plot(shap_values[2])

Thanks!

**Comment by tkmamidi** [comment]
Helper function [here](https://github.com/slundberg/shap/issues/2255) helped me :)
