### ISSUE TITLE
shap_values slice broken

### ISSUE THREAD

**Issue by yuuuxt** [shap/shap#2325]
in https://github.com/slundberg/shap/commit/146a667928a36a9d0bf9af5faa5a0c2bf494fdbc#diff-03b5c29fd1faa2f0c6d17ff998a8a625733c064990c6628b9207b2398ba914c1, line 326-328: 

```
 if t == Ellipsis:
    pos += len(self.shape) - len(item)
    continue
```

this part breaks code such as cohort bar plot: https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/bar.html#Cohort-bar-plot
as it is doing something like `shap_values[[True, True, False, ...]]`. `t == Ellipsis` will return a ndarray of False, hence the error occurs.

**Comment by kspieks** [comment]
+1

**Comment by lilila** [comment]
any fix?

**Comment by yuuuxt** [comment]
here is my naive fix for this issue, which looks valid and works for me:
https://github.com/yuuuxt/shap/commit/7c95fd2b48bcf9cad82b10f65e552a49b360afbd

**Comment by RicardoBarranco** [comment]
> here is my naive fix for this issue, which looks valid and works for me: [yuuuxt@7c95fd2](https://github.com/yuuuxt/shap/commit/7c95fd2b48bcf9cad82b10f65e552a49b360afbd)

Worked for me! Thanks a lot, I was struggling with this issue (Shap 0.40.0, Numpy 1.20.3, Python 3.9.7)
