### ISSUE TITLE
Error in Census income classification with LightGBM

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#233]
When we trying to run that code, it's getting an error 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-227-732b37e75278> in <module>()
----> 1 shap.force_plot(explainer.expected_value, shap_values[0,:], X_display.iloc[0,:])

AttributeError: 'TreeExplainer' object has no attribute 'expected_value'
```

**Comment by slundberg** [comment]
Thanks! Which version of shap are you using? I don't see how that could happen in the current version.

**Comment by DiliSR** [comment]
Name: shap
Version: 0.18.1

**Comment by DiliSR** [comment]
Now I upgrade it into 0.23.1. But still getting the same error

**Comment by slundberg** [comment]
Odd. When I run `shap/notebooks/tree_explainer/Census%20income%20classification%20with%20LightGBM.ipynb` I get no errors. You are just running that notebook? I would make sure you are not accidentally loading an older version

**Comment by DiliSR** [comment]
Yes, I just copy that code and paste.

**Comment by slundberg** [comment]
Well the current code sets the expected_value attribute at
https://github.com/slundberg/shap/blob/57570d1638dce9b830930ede52c6adb39e5c8edc/shap/explainers/tree.py#L53 
so my guess is you still somehow using an old version. You could put some print statements into your version at that line to make sure you are using it.
