### ISSUE TITLE
Getting blank plot when saving output of shap.force_plot in to pdf

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#234]
Hi,

I tried to save the dependency plots to pdf after adding parameter show = false. It worked.

Now I need to save the output of shap.force_plot into pdf. It doesn't allow to add show = false parameter. If I try to save the plot without adding that parameter I got a blank page.

Do you have a solution for that?

Thank you.

**Comment by slundberg** [comment]
check out #27
