### ISSUE TITLE
shap.summary_plot(title)

### ISSUE THREAD

**Issue by Arthur-Langlois** [shap/shap#2340]
Hi, for the following ```shap.summary_plot``` function, the parameter ```title``` does not work, any idea if I'm doing something wrong ? 
```shap.summary_plot(shap_values, X_train, plot_type="bar", title = 'hello' )```

**Comment by shaido987** [comment]
For anyone encountering this problem (such as me), a workaround can be found in this issue: https://github.com/slundberg/shap/issues/1641
