### ISSUE TITLE
cannot import name 'DenseData' and 'visualize' from 'shap'

### ISSUE THREAD

**Issue by rEstela** [shap/shap#2352]
When running the example code (https://libraries.io/pypi/shap):

```
from shap import KernelExplainer, DenseData, visualize, initjs
from sklearn import datasets,neighbors
from numpy import random, arange

## print the JS visualization code to the notebook
initjs()

## train a k-nearest neighbors classifier on a random subset 
iris = datasets.load_iris()
random.seed(2)
inds = arange(len(iris.target))
random.shuffle(inds)
knn = neighbors.KNeighborsClassifier()
knn.fit(iris.data, iris.target == 0)

## use Shap to explain a single prediction
background = DenseData(iris.data[inds[:100],:], iris.feature_names) # name the features
explainer = KernelExplainer(knn.predict, background, nsamples=100)
x = iris.data[inds[102:103],:]
visualize(explainer.explain(x))
```

I got the following errors:

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13492/3852576576.py in <module>
----> 1 from shap import DenseData

ImportError: cannot import name 'DenseData' from 'shap' (C:\ProgramData\Anaconda3\lib\site-packages\shap\__init__.py)

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13492/1790835437.py in <module>
----> 1 from shap import visualize

ImportError: cannot import name 'visualize' from 'shap' (C:\ProgramData\Anaconda3\lib\site-packages\shap\__init__.py)

**Comment by naingthet** [comment]
I think that documentation may be out of date, but not 100% sure. I'd suggest following the pattern from the README (see code below). This has worked fine in my experience. Hope this helps!

```
import sklearn
import shap
from sklearn.model_selection import train_test_split

# print the JS visualization code to the notebook
shap.initjs()

# train a SVM classifier
X_train,X_test,Y_train,Y_test = train_test_split(*shap.datasets.iris(), test_size=0.2, random_state=0)
svm = sklearn.svm.SVC(kernel='rbf', probability=True)
svm.fit(X_train, Y_train)

# use Kernel SHAP to explain test set predictions
explainer = shap.KernelExplainer(svm.predict_proba, X_train, link="logit")
shap_values = explainer.shap_values(X_test, nsamples=100)

# plot the SHAP values for the Setosa output of the first instance
shap.force_plot(explainer.expected_value[0], shap_values[0][0,:], X_test.iloc[0,:], link="logit")
```
