### ISSUE TITLE
Previous versions' wheels are not kept for all distributions

### ISSUE THREAD

**Issue by atos-ghassen-bchir** [shap/shap#2359]
When trying to install shap==0.39.0 (using pip), I noticed that the wheel file for distributions other than win_amd64 are not kept. One can only get the .tar.gz package and rebuild it (https://pypi.org/project/shap/0.39.0/#files).
For the latest version (0.40.0 as of today) the wheel files seem to be available for all platforms (https://pypi.org/project/shap/0.40.0/#files)

I believe wheel files for all platforms should be kept, even for previous versions.

**Comment by connortann** [comment]
The release process has been rather inconsistent for previous PyPI releases. It's now in a much better state, using cibuildwheel and a GitHub action to upload wheels for a defined set of platforms.

Pragmatically I don't think we will work on building wheels for older versions, as fundamentally older versions are not maintained. I would recommend using the latest version where possible, to benefit from numerous bug fixes.
