### ISSUE TITLE
[GPUTree] waterfall_plot requires a scalar base_values of the model output as the first parameter, but...

### ISSUE THREAD

**Issue by antonkratz** [shap/shap#2362]
Sklearn, random forest for regression. I am using `shap.explainers.GPUTree` and manage to generate an instance of `shap._explanation.Explanation`.

The problem is, global visualizations do work (`shap.plots.bar(shap_values)`, `shap.summary_plot(shap_values, x_sub, featurenames)`). **However the waterfall and force plot visualization do not work!**

For example `shap.plots.waterfall(shap_values[0])` results in:

> Exception: waterfall_plot requires a scalar base_values of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.base_values[0], values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.base_values[0], values[0][0], X[0]).

**Comment by LeandroLuque** [comment]
Hi. I have the same issue. Let me know if you find a way to plot an explanation for multiclass problem. Thx

**Comment by bernardocortez** [comment]
Same issue here with a LGBM Classifier

**Comment by rolare** [comment]
Hi, I'm not entirely sure what the problem is, but Explainers seem to have trouble handling some Sklearn like models. Anyways, pretty sure that could be investigated further, but here's a workaround (not so clean but works):
```
import shap
from types import SimpleNamespace

model = None # insert your model here
inputs = None # insert your inputs as pandas Dataframe

explainer = shap.Explainer(model) # change explainer as needed
shap_values = explainer(inputs)

# workaround...
to_pass = SimpleNamespace(**{
                          'values': np.array(shap_values[0].values),
                          'data': np.array(shap_values[0].data),
                          'feature_names': inputs.columns,
                          'base_values': shap_values[0].base_values[0]
            })
shap.plots.waterfall(to_pass)
```

**Comment by bernardocortez** [comment]
It seems this repo lacks maintenance

**Comment by karolmajek** [comment]
for 2 outputs I modified @rolare sample:

```
to_pass = SimpleNamespace(**{
                          'values': np.array(shap_values[0].values[:,0]),
                          'data': np.array(shap_values[0].data),
                          'feature_names': feature_names,
                          'base_values': shap_values[0].base_values[0]
            })

shap.plots.waterfall(to_pass)

to_pass = SimpleNamespace(**{
                          'values': np.array(shap_values[0].values[:,1]),
                          'data': np.array(shap_values[0].data),
                          'feature_names': feature_names,
                          'base_values': shap_values[0].base_values[0]
            })

shap.plots.waterfall(to_pass)
```

and I get two waterfalls as expected :tada:

Edit:
other functions don't support other types, solution for beeswarm:
```
sh = copy.deepcopy(shap_values)
sh.values=sh.values[:,:,0]  # leave only 1st y
shap.plots.beeswarm(sh)
```
