### ISSUE TITLE
Enabling the matplotlib "ax" keyword argument to plot functions

### ISSUE THREAD

**Issue by mrektor** [shap/shap#2363]
Hi all,

It would be very useful to provide in the plot API the possibility of passing the ax on which the plot has to be made

**Comment by flo-ri-an** [comment]
Yes, this would greatly simplify arranging complex layouts. Definitely something I would love to see too.

**Comment by connortann** [comment]
This would be a great enhancement. There is some discussion about the same issue on #3070 , so let's use that one to track the issue. I'll close this as a duplicate.
