### ISSUE TITLE
TreeExplainer support for IsolationForest

### ISSUE THREAD

**Issue by r0f1** [shap/shap#237]
How can I use shap to explain the output of an isolation forest?

Currently sklearn `IsolationForests` are not supported. Also the `ExtraTreeRegressor` is not supported.

**Comment by slundberg** [comment]
You are right, those have not yet been added. If you are up for a PR and
want to take a look at `tree.py` I bet they can be added without too much
work using the other sklearn tree model types as an example.

**Comment by r0f1** [comment]
Alright, thanks for the explanation.

**Comment by slundberg** [comment]
For future reference I should note that `IsolationForests` is not a typical tree model so it might take more thought to figure out if TreeExplainer makes sense there.

**Comment by parkerzf** [comment]
Any recent update on this? I have a similar need to explain isolation forest using shap value. I used kernel explainer as a quick solution. It makes sense to have a direct support. I would like to help if it makes sense. @slundberg

**Comment by slundberg** [comment]
As long as the value returned by the isolation forest is encoded in the leaf values then Tree SHAP should work. I have not looked at the format of the sklearn implementation but it might already be in that format (the format where the output is the average of values stored in the leaves). The first step would be to dig into that format and then after that to pass it into the SHAP TreeEnsemble constructor.

**Comment by parkerzf** [comment]
Makes sense, I will take a look.

**Comment by JiechengZhao** [comment]
@parkerzf @r0f1 already work with this. https://github.com/slundberg/shap/pull/784

**Comment by parkerzf** [comment]
@JiechengZhao cool, will take a look.
