### ISSUE TITLE
Logit Link Code

### ISSUE THREAD

**Issue by AllardJM** [shap/shap#238]
Hi Scott,

Is there a method that converts the log-odds output of a tree model to a probability within the force plot that is written in python (or is easy to replicate in python)? I am looking to create a visualization outside of the JS implementation and want to use probabilities instead of the log-odds. I see there is under common.py a transform function but clearly there needs to be more to it to produce the positive and 'negative' values on the probability scale.

**Comment by AllardJM** [comment]
Hi, checking in if this happens to be accessible.

**Comment by slundberg** [comment]
Hey sorry for the delay. The x-axis on the force plot is actually in log-odds space, it just has tick marks that convert the log odds to probability. So if you wanted to do something similar you just need to plot everything in log odds space, and the just update the ticks to mark probabilities (which are the the logistic transform of the log-odds, remembering to include the expected_value offset)

**Comment by AllardJM** [comment]
Hi Scott - no worries, thanks for the info, I am not sure I exactly follow.

Are you just doing something like this:

```
def inv_logit(x):
    return 1/(1+np.exp(-x))

inv_logit(shap_values[0,:])
```

and then somehow incorporating the expected value from explainer.expected_value?

For example, in my sample problem, the largest SHAP value in absolute value logit space is -0.099028 which is a negative impact on the prediction and the expected value (logit) is 0.41347859922209645

How are you presenting this?

**Comment by slundberg** [comment]
I plot the actual logit values on the x-axis. But then when making the tick
marks on the x-axis I draw inv_logit(original_tick_mark_position) for the
tick label. (Note this means the base value is still the expected value in
logit space)

**Comment by bhrigs** [comment]
Hi, I found that when a feature has negative values, link = 'logit' failed saying ValueError: input contains infinite or NaNs or number too large for float. I did a check again and my input dataset is clean in that sense. Not But when I didn't use link = 'logit', it did not throw that error. 

Is there a way to workaround this or understand what could be happening?
