### ISSUE TITLE
Feature Names not set correctly if Feature Set is too small

### ISSUE THREAD

**Issue by woldeaman** [shap/shap#2394]
When defining an explainer with set `feature_names`, the size of the dataset to calculate shap values for `X` cannot be smaller than `feature_names`, for the features in a `waterfall` plot to be displayed correctly.

```
X.shape 
>>> (500, 10)
shap_explainer = shap.Explainer(model, X, feature_names=X.columns)
shap_values = shap_explainer(X.iloc[:5])
shap.waterfall_plot(shap_values[0])  # this will not label the feature names correctly 
```

the reason is that only the array `shap_values` has its attribute `feature_names` set correctly, but not the individual rows, `shap_values[0].feature_names` only contained a single feature name of the list

**Comment by myui** [comment]
It seems when len(feature_name) matches to shap_value.shape[1], then only the first feature name is used and IndexError happens in our case.

[This line](https://github.com/slundberg/shap/blob/v0.41.0/shap/_explanation.py#L124) has a bug in a specific condition.

```py
print("shap_value1.shape: ", shap_value1.shape);
> shap_value1.shape:  (30, 30)

print("len(feature_names)=", len(X.columns));
> shap_value1.shape:  30

shap_obj = shap.Explanation(values = shap_value1,
                       base_values = expected_value1,
                       data=X.iloc[0:NSHOW_SAMPLES,:],
                       feature_names=X.columns)
```

```py
Input In [84], in <cell line: 4>()
      6 try:
      7     shap.force_plot(expected_value1, shap_value1[rowid], X.iloc[rowid], matplotlib=True)
----> 8     shap.plots.waterfall(shap_obj[rowid])
      9 except (ValueError, TypeError) as e:
     10     # 1. avoid shap library bug for ValueError: Image size of xxx pixels is too large. It must be less than 2^16 in each direction. 
     11     # 2. workaround for TypeError: https://github.com/slundberg/shap/pull/2679
     12     errmsg = ''.join(traceback.format_exception_only(type(e), e)).strip()
File /usr/local/lib/python3.8/site-packages/shap/plots/_waterfall.py:127, in waterfall(shap_values, max_display, show)
    125 else:
    126     if np.issubdtype(type(features[order[i]]), np.number):
--> 127         yticklabels[rng[i]] = format_value(float(features[order[i]]), "%0.03f") + " = " + feature_names[order[i]]
    128     else:
    129         yticklabels[rng[i]] = features[order[i]] + " = " + feature_names[order[i]]
IndexError: string index out of range
```

**Comment by vvsbiocode** [comment]
Hello. I have shap v0.46.0 (I think it is the latest for now) however the bug persists in ploting. I have 16 features.

`explainer = shap.Explainer(model5, X5,feature_names=selFeat_ABCD_uncor)
shap_values = explainer(X_test5)
shap.plots.beeswarm(shap_values)`

> ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [465], in <cell line: 1>()
----> 1 shap.plots.beeswarm(shap_values)

File /home/sultan/anaconda3/lib/python3.9/site-packages/shap/plots/_beeswarm.py:312, in beeswarm(shap_values, max_display, order, clustering, cluster_threshold, color, axis_color, alpha, show, log_scale, color_bar, s, plot_size, color_bar_label)
    309     values[:,feature_order[num_features-1]] = np.sum([values[:,feature_order[i]] for i in range(num_features-1, len(values[0]))], 0)
    311 # build our y-tick labels
--> 312 yticklabels = [feature_names[i] for i in feature_inds]
    313 if num_features < len(values[0]):
    314     yticklabels[-1] = "Sum of %d other features" % num_cut

File /home/sultan/anaconda3/lib/python3.9/site-packages/shap/plots/_beeswarm.py:312, in <listcomp>(.0)
    309     values[:,feature_order[num_features-1]] = np.sum([values[:,feature_order[i]] for i in range(num_features-1, len(values[0]))], 0)
    311 # build our y-tick labels
--> 312 yticklabels = [feature_names[i] for i in feature_inds]
    313 if num_features < len(values[0]):
    314     yticklabels[-1] = "Sum of %d other features" % num_cut

IndexError: list index out of range

**Comment by thatlittleboy** [comment]
@vvsbiocode Hi, please raise a new issue instead of riding on this one. And please provide a minimal **reproducible** example, the example you provided is not helpful since it's not reproducible.
