### ISSUE TITLE
The passed model is not callable and cannot be analyzed directly with the given masker! Model: None

### ISSUE THREAD

**Issue by seyidcemkarakas** [shap/shap#2399]
When i am using RandomForestRegressor or XGBoost, there is no problem like this. Since i am using Relevance Vector Regression i got this error.
`from sklearn_rvm import EMRVR`
`model_rvr=EMRVR(kernel="linear").fit(X, y)`
`explainer = shap.Explainer(model_rvr)`

Exception: The passed model is not callable and cannot be analyzed directly with the given masker! Model: None

Also same problem as https://stackoverflow.com/questions/71117308/exception-the-passed-model-is-not-callable-and-cannot-be-analyzed-directly-with

For Relevance Vector Regression => https://sklearn-rvm.readthedocs.io/en/latest/index.html

Any idea ?

**Comment by seyidcemkarakas** [comment]
I got it at there => https://www.youtube.com/watch?v=xDo_HJj1pck
`explainer = shap.Explainer(model_gpr.predict)`
adding .predict can solve problem

**Comment by chenz1hao** [comment]
Have you solved this issue?

**Comment by eschibli** [comment]
I don't believe SHAP has an explainer that handles support vector machines natively, so you need to pass the model's `predict` method rather than the model itself.

**Comment by seyidcemkarakas** [comment]
```
from sklearn_rvm import EMRVR
model_rvr=EMRVR(kernel="linear").fit(X, y)
explainer = shap.KernelExplainer(model_rvr.predict, X)
```
Someone replied on Stackoverflow like this and i havent check it.

> Have you solved this issue?

**Comment by slundberg** [comment]
Hey! @eschibli is right, only certain models that have custom algorithms targeted at them can be passed as non-callable objects. The SO answer is right, but just specific to kernel explainer. I would recommend the following (untested) variation:
```
from sklearn_rvm import EMRVR
model_rvr=EMRVR(kernel="linear").fit(X, y)
explainer = shap.Explainer(model_rvr.predict, X)
```

**Comment by Ericlemaire** [comment]
I got the same message with a xbgboost regressor.

**Comment by maepai-sr** [comment]
@Ericlemaire check the booster you are using, shap doesn't seem compatible with gblinear. Try using gbtree.

**Comment by mucunwuxian** [comment]
In my case, the following code worked.

```
!git clone https://github.com/shap/shap.git
%cd shap

print(['pwd'])
!pwd
print(['ls'])
!ls

# https://github.com/shap/shap?tab=readme-ov-file#tree-ensemble-example-xgboostlightgbmcatboostscikit-learnpyspark-models
import xgboost
import shap

# train an XGBoost model
X, y = shap.datasets.california()
model = xgboost.XGBRegressor().fit(X, y)

# explain the model's predictions using SHAP
# (same syntax works for LightGBM, CatBoost, scikit-learn, transformers, Spark, etc.)
explainer = shap.Explainer(model.predict, X)
shap_values = explainer(X)

# visualize the first prediction's explanation
shap.plots.waterfall(shap_values[0])
```
▼
![image](https://github.com/user-attachments/assets/0701f195-7d8b-4e94-bbeb-a1e93531d887)
