### ISSUE TITLE
How to get the feature importance for a subgroup of samples

### ISSUE THREAD

**Issue by HairongG** [shap/shap#2401]
Hi, 

I have one particular modeling problem. I can get the feature importance of the overall sample from Shap values. For the overall sample, the most important variable is say 'number of days being late in payment'. However, when I want to get the feature importance for a subset of samples, the feature importance does not make sense. The subset of samples have the same value 0 for that particular variable 'number of days being late in payment'. But this variable is still ranked the most important in this group. Is their a way to recalculate Shap values for a subset of samples without rebuilding the model?

Thank you.

**Comment by gianmarco-terrones** [comment]
Once you have an Explainer object, you can get `shap_values` for a given group of samples without rebuilding the model. For example, 

```python
e = shap.KernelExplainer(f, X_train)
shap_values = e.shap_values(X_test)
shap_values2 = e.shap_values(X_test2)
```

Here, `X_test` should be a numpy array. Its number of rows are the number of samples, and its number of columns are the number of descriptors/features for each sample.

When you say feature importance, do you mean the mean absolute SHAP value for a given descriptor? Where do you get the ranking from? From a bar plot or something?

**Comment by HairongG** [comment]
Hi,

I knew how to get to the Shap values of a particular sample. My question is this. After I calculated the Shap Values of a population, I can calculate the variable importance based on the sum of the absolute values of all variables. From that, I found that X1 is the most important variable. Then I calculated the Shap Values of a subset of that population, X1 is still most important for that subset. However, for that subset of population, the values for X1 are all 0 because that's how I segmented the population. I want to know how to find the most important variables that differentiated the predictions among the subset of population. X1 shouldn't be the most important since they are all 0. 

Hope this explains a little better.

**Comment by gianmarco-terrones** [comment]
Ah I see, thanks for clarifying. Perhaps try the following. Say your subset population is `X_test_sub`. Initialize whatever explainer you are using with `X_test_sub` rather than your whole population.

```python
e = shap.KernelExplainer(f, X_test_sub)
shap_values = e.shap_values(X_test)
```

I have never tried this, but think it might work b/c a docs page (https://shap-lrjball.readthedocs.io/en/latest/generated/shap.KernelExplainer.html) says the `data` variable is used to integrate out features. If all the instances in `data` have the same value for a given feature/descriptor, I'd imagine this integrating out doesn't proceed.
