### ISSUE TITLE
Cohort bar plot error 

### ISSUE THREAD

**Issue by aqibamajid** [shap/shap#2406]
[API doc link](https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/bar.html#:~:text=bar(shap_values%5B0%5D)-,Cohort%20bar%20plot,-%EF%83%81)

Currently trying to create a cohort bar plot as per example linked above. 

Python version : 3.7
Shap versoin : 0.40.0

Code as below :

```
import xgboost
import shap

### train XGBoost model
X,y = shap.datasets.adult()
model = xgboost.XGBClassifier().fit(X, y)

### compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X)
```

executing the example

```
sex = ["Women" if shap_values[i,"Sex"].data == 0 else "Men" for i in range(shap_values.shape[0])]
shap.plots.bar(shap_values.cohorts(sex).abs.mean(0))
```

results in following error : 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_21808/2586830402.py in <module>
      1 sex = ["Women" if shap_values[i,"Sex"].data == 0 else "Men" for i in range(shap_values.shape[0])]
----> 2 shap.plots.bar(shap_values.cohorts(sex).abs.mean(0))

~/SageMaker/bt-bb-churn-28-day/virtual_env/lib/python3.7/site-packages/shap/_explanation.py in cohorts(self, cohorts)
    298         if isinstance(cohorts, (list, tuple, np.ndarray)):
    299             cohorts = np.array(cohorts)
--> 300             return Cohorts(**{name: self[cohorts == name] for name in np.unique(cohorts)})
    301         raise Exception("The given set of cohort indicators is not recognized! Please give an array or int.")
    302 

~/SageMaker/bt-bb-churn-28-day/virtual_env/lib/python3.7/site-packages/shap/_explanation.py in <dictcomp>(.0)
    298         if isinstance(cohorts, (list, tuple, np.ndarray)):
    299             cohorts = np.array(cohorts)
--> 300             return Cohorts(**{name: self[cohorts == name] for name in np.unique(cohorts)})
    301         raise Exception("The given set of cohort indicators is not recognized! Please give an array or int.")
    302 

~/SageMaker/bt-bb-churn-28-day/virtual_env/lib/python3.7/site-packages/shap/_explanation.py in __getitem__(self, item)
    324 
    325             # skip over Ellipsis
--> 326             if t == Ellipsis:
    327                 pos += len(self.shape) - len(item)
    328                 continue

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

It's this part of the code which causes the error `shap_values.cohorts(sex)`, any ideas as why this example from the docs isn't working please? 

Many thanks!

ps - first time raising an issue, would be grateful for any feedback on this.

**Comment by rherman9** [comment]
Hi @aqibamajid, I'm experiencing the same issue with the Cohort Bar Plots and managed to hot-fix it by changing the following line:
https://github.com/slundberg/shap/blob/46b3800b31df04745416da27c71b216f91d61775/shap/_explanation.py#L326

to:
``` python 
if np.any(t == Ellipsis):
```

Not sure if this breaks anything else or the results are even valid, but the charts (and counts) look fine. Should be fine as long as you don't have any Ellipsis in your dataset.

**Comment by aqibamajid** [comment]
Hi @rherman9 

Thanks for your response. The hot-fix suggested by yourself has fixed the issue! 

The output in the example after the hot-fix does look slightly different than what is in the documents though...

With hot-fix
![Capture](https://user-images.githubusercontent.com/59210511/158612128-a3c83f9a-7185-46fe-b786-0f877b4e974b.PNG)

As per doc
![Capture](https://user-images.githubusercontent.com/59210511/158612609-624ef34d-89af-49ca-9d2a-3f8f6b414c0b.PNG)

**Comment by joshzwiebel** [comment]
I'm running into the same issue. Has anyone submitted a PR for this change? I could do it if it is not yet assigned.

**Comment by rherman9** [comment]
@joshzwiebel I did not.

**Comment by joshzwiebel** [comment]
https://github.com/slundberg/shap/pull/2492 Ive made the change. Happy to edit or receive feedback!

**Comment by slundberg** [comment]
Thanks all! The right change is to use `is` instead of `==`, and #2492 does that now.
