### ISSUE TITLE
Differences between explanations

### ISSUE THREAD

**Issue by Denisshh** [shap/shap#2407]
Hello,

Can somwone explain differences between Bar graph and Waterfall ?
Features with Shapely should be independent, so why
with dataset Boston - on waterfall - Lstat has value +5.79 and on Bar plot +4.
What of this va;ues - is independent marginal add value (that is wanted)  osr whats the differnce between  diagrams ?

Whats the differences between shap_values[0] and shap_values[1] ? (its different explanation or not ?)

What values - are in shap_values - independent or not ?
How can transform shap_values to dataframe ? (pd.dataframe results with some errors ...)

**Comment by gianmarco-terrones** [comment]
When I have called the function `shap_values`, it gives an array with one entry, that entry being a numpy array. 

```python
model = keras.models.load_model('../model.h5', compile=False)

# will try to use just 100 random rows
number_of_rows_train = X_train.shape[0]
random_indices = np.random.choice(number_of_rows_train, size=100, replace=False)
X_train = X_train[random_indices, :]

def f(X):
    return model.predict(X)
e = shap.KernelExplainer(f, X_train)

shap_values = e.shap_values(X_test) 
print(f'shap_values shape: {shap_values[0].shape}') # array of length 1, with a numpy array inside

for idx in range(num_rows): # plotting for each test instance
    f = plt.figure()
    f = shap.force_plot(e.expected_value, shap_values= shap_values[0][idx,:], features= X_test[idx,:], feature_names = descriptors, show=False)
    shap.save_html(f"plots/shap_plot_{my_names[idx]}_normalizedspace.html", f)

    test_prediction_shap = y_scaler.inverse_transform(e.expected_value + sum(shap_values[0][idx,:]))
    print(f'Using SHAP values, prediction for {my_names[idx]} is {test_prediction_shap}') 
```

So shap_values[0] is a numpy array. The number of rows of this numpy array is the number of train or test instances. The number of columns of the numpy array is the number of features/descriptors each instance has when fed into the model.

To convert to a Pandas DataFrame, something like `df = pd.DataFrame(shap_values[0])` should work.
