### ISSUE TITLE
Dependence plot shows wrong colormap with some one-hot encoded features.

### ISSUE THREAD

**Issue by PrashantSaikia** [shap/shap#241]
I have a one-hot encoded feature called `Client Occupation - Staying at home` that has values 0 and 1. When I plot the `dependence_plot` of some other feature with this feature as the interaction index, it shows the colorbar as continuous, which is wrong:

![download](https://user-images.githubusercontent.com/39755678/44640836-90220e00-a9f6-11e8-8e09-12ede0bb6bbb.png)
![download 1](https://user-images.githubusercontent.com/39755678/44640843-931cfe80-a9f6-11e8-9d5f-385756d4dceb.png)

But this does not happen for other one-hot encoded features. For example, I have another feature called `Client Occupation - Full Time`, that also has values of 0 and 1, and with this, the colors come out correctly:

![download 3](https://user-images.githubusercontent.com/39755678/44640871-ca8bab00-a9f6-11e8-9674-f8b6d2c56fa1.png)
![download 2](https://user-images.githubusercontent.com/39755678/44640872-ca8bab00-a9f6-11e8-9fee-826bda75f6b2.png)

I investigated the distribution of the values for both these features, to see if a huge difference in the proportion of 0s to 1s might be a cause:

```
from collections import Counter
Counter(X['Occupation Status - Staying at home'])
>>> Counter({0: 943, 1: 38})
```

```
Counter(X['Occupation Status - Full time'])
>>> Counter({1: 798, 0: 183})
```

Could this be the reason?

**Comment by slundberg** [comment]
Interesting. I don't know without some digging why that's happening. If you
want to look more you can check out `plots/dependence.py`. I think the
discrete plots are triggered when the passed display values are strings and
not numbers, so perhaps that's why?
