### ISSUE TITLE
Performance difference KernelExplainer model vs. function

### ISSUE THREAD

**Issue by akarpf** [shap/shap#2410]
Hi,

I am trying to reproduce/speed up the code of the following paper, which uses SHAP: https://arxiv.org/pdf/1903.02407.pdf (https://github.com/ronniemi/explainAnomaliesUsingSHAP).

I am noticing a huge difference in performance when I use KernelExplainer with a function or a model respectively. This is puzzling me.

In the paper the authors runs the KernelExplainer per feature:

```
#select feature
counter = df_top_err.index[0]
```
```
def func_predict_feature(record):
    record_prediction = autoencoder.predict(record)[:,counter]
    return record_prediction

explainer = shap.KernelExplainer(func_predict_feature, background_set)
shap_values2 = explainer.shap_values(record_to_explain, nsamples='auto')

# --- 10.933740139007568 seconds ---
```
```
print(shap_values)
[ 0.          0.          0.          0.          0.          0.
 -0.00014713  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
 -0.00012618  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.        ]
```

In the process of experimenting, trying to speed things up, I came up with the following solution, which in my opinion should be equivalent.:

```
modelsub = Model(autoencoder.layers[0].input, autoencoder.layers[-1].output[:,counter])

explainer = shap.KernelExplainer(modelsub, background_set)
shap_values = explainer.shap_values(record_to_explain, nsamples='auto')

# --- 0.8240640163421631 seconds ---
```
```
print(shap_values)
[ 0.          0.          0.          0.          0.          0.
 -0.00015826  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
 -0.00011506  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.        ]
```

The results are basically identical up to 4 places behind the decimal point. But the second variant is >10x faster. How is that possible? Or am I missing something here?

As I am having your attention already, I might as well ask you another question: Would this be the corresponding solution with DeepExplainer (using the whole data as a background set)?

```
modelsub = Model(autoencoder.layers[0].input, autoencoder.layers[-1].output[:,counter])
explainer = shap.DeepExplainer(modelsub, x_train.values)
shap_values = explainer.shap_values(record_to_explain.values[np.newaxis],check_additivity=False)

#--- 0.5212132930755615 seconds ---
```

Please note that I had to reshape the data `record_to_explain.values[np.newaxis]` and set `check_additivity=False` in order to get DeepExplainer working (might this be the problem?). It's even faster, but gives vastly different results: 

```
print(shap_values)
[ 0.     -0.0001  0.0001  0.0003 -0.      0.0001 -0.0004 -0.     -0.
   0.0001  0.      0.0001 -0.      0.     -0.0001 -0.0001  0.     -0.
  -0.0002 -0.     -0.      0.     -0.     -0.      0.     -0.0001  0.0001
  -0.      0.0002]
```

I am aware that this is not Stackoverflow, but I saw that other people here had discussed the slow performance of KernelExplainer before. The only suggestions I got from these other threads however were to reduce the size of the background set (reducing the the quality of shapley values) or to use DeepExplainer.

I would highly appreciate if you could comment on my question.

**Comment by gianmarco-terrones** [comment]
In my experience, setting `check_additivity=False` leads to bad SHAP results. It likely means DeepExplainer can't handle aspects of your model. When I have used KernelExplainer I don't have the additivity issue, so I trust the SHAP values a lot more. 

The additivity thing refers to the fact that, for any train or test instance, the mean model prediction plus the sum of SHAP values for that instance should equal the prediction for that instance.

I think KernelExplainer is slower because, as someone else explained it, "using a model agnostic method is going to come with a significant computational cost". See #1199.
