### ISSUE TITLE
How to extract information from  ``shap.utils.hclust`` to remove redundant features not only by visual inspection barplot?

### ISSUE THREAD

**Issue by julio-luna-nubank** [shap/shap#2441]
I'm using ``shap.utils.hclust`` to figure out which features are redundant.

Reproducible example:
```import pandas as pd
import numpy as np
import shap

from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

from lightgbm import LGBMClassifier

data = pd.read_csv("https://raw.githubusercontent.com/gdmarmerola/random-stuff/master/probability_calibration/UCI_Credit_Card.csv")

# getting design matrix and target
X = data.copy().drop(['ID','default.payment.next.month'], axis=1)
y = data.copy()['default.payment.next.month']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = .2, random_state = 42)

model = LGBMClassifier(random_state = 42).fit(X_train, y_train)

# compute SHAP values
explainer = shap.Explainer(model, X_test)
shap_values = explainer(X_test)

clustering = shap.utils.hclust(X_train, y_train) # by default this trains (X.shape[1] choose 2) 2-feature XGBoost models
shap.plots.bar(shap_values, clustering=clustering)
```
1. In the implementation why is [this](https://github.com/slundberg/shap/blob/46b3800b31df04745416da27c71b216f91d61775/shap/utils/_clustering.py#L110) an ``XGBRegressor`` even for classification tasks?
2. Should ``clustering`` be calculated on train or test samples?
3. My ``X_train`` has shape ``(2300,23)`` whereas clustering has ``(22, 4)`` what does the shape of that matrix represent?
4. How can I use ``clustering``to remove redundant features, beyond the bar plot visual inspection?

**Comment by sidml** [comment]
It would have been useful to have the option to remove redundant features, beyond the bar plot visual inspection.
