### ISSUE TITLE
negative shap_values for binary classification and force_plot doesn't work with 200+ features 

### ISSUE THREAD

**Issue by siteshi** [shap/shap#245]
Hi Slundberg, first of all thanks a lot for shap project. Although i got some basic understanding from the shap paper but I am facing some issues..
Here is the small description about my dataset and the algorithm 

**size of X_train_df :**  (29696, 256)
**algorithm:** catboost classifier 
**explainer shap_values of test sample#1:**   [-2.60508463e-02 -2.71288649e-02  1.07052546e-05 -1.07646180e-02 3.91583503e-03 -2.11696852e-02 ....]
**explainer.expected_value** -1.7498153454626064

1. Why for binary classification we get **explainer.expected_value** and some of **shap_values** -ve?
2. force_plot fails to plot on ipython notebook. For me it seems like force_plot is not able to handle 256 features

**Comment by slundberg** [comment]
1. The explanations are in the output space of the trees before any post-transformation, for CatBoost logistic classification that is a log odds space, hence can be negative or positive. 
2. I have used it for thousands of features so I doubt that is it. Perhaps try a simple example and make sure it works in your browser.

**Comment by siteshi** [comment]
@slundberg  thanks for the quick response. 
-ve shap value in case of catboost make sense now.
I did run for simple example and force_plot is working like charm but when I run for my dataset it doesn't display anything except a small "js" emoticons. I will debug my code to dig further.
