### ISSUE TITLE
Kernel Explainer and Class Activation Map

### ISSUE THREAD

**Issue by NTNguyen13** [shap/shap#246]
Hi, this is a question for my curiosity.

I have recently used SHAP Kernel Explainer on the result of my CNN, and I saw it quite similar to the class activation map. I'm curious about the similarity and difference of them. Could you please clarify that for me? Thank you!

**Comment by slundberg** [comment]
Well the class activation map from my understanding just averages the last convolutional channels in a global max pooling network weighted by their impact on the output of a class. If the values in the convolutional channels were SHAP values then this would be the right way to combine them to get SHAP values for a specific class. The values in the last convolution layers are not of course SHAP values, they are just the activations, but I suppose if they are mean centered then then they might behave similarly.

**Comment by NTNguyen13** [comment]
Thank you for clarification!
