### ISSUE TITLE
Accessing Shap values positive and negative

### ISSUE THREAD

**Issue by genny92cst** [shap/shap#2463]
i calculated the  shap values by this command
shap_value_single = explainer.shap_values(X = x_test.iloc[X_idx:X_idx+1,:], nsamples = 'auto')
now, when i plot
shap.force_plot(base_value = explainer.expected_value[current_label.value],
                shap_values = shap_value_single[current_label.value], 
                features = x_train.iloc[X_idx:X_idx+1,:]
                )

i get the arrowlike plot with feature names and some numbers that i thought were shapley values, but the numbers are not corresponding, and i was wondering what i dd get wrong. 
![Immagine 2022-03-28 144820](https://user-images.githubusercontent.com/71124162/160401240-9af099b1-e384-4b5b-9562-78c564051878.jpg)

**Comment by Arthur-Langlois** [comment]
The values plotted in the forceplot are the actual feature values. For this specific observation, the value of sensitivity is -1.621, its SHAP local value is the width of its own rectangular like structure.
