### ISSUE TITLE
Question - why SHAP expected value is 0.5 always for my data?

### ISSUE THREAD

**Issue by SSMK-wq** [shap/shap#2470]
I am working on a **binary classification** using random forest model, neural networks in which am using SHAP to explain the model predictions. I followed the tutorial and wrote the below code to get the waterfall plot shown below. My dataset shape is 977,6 and 77:23 is class proportion

    row_to_show = 20
    data_for_prediction = ord_test_t.iloc[row_to_show]  # use 1 row of data here. Could use multiple rows if desired
    data_for_prediction_array = data_for_prediction.values.reshape(1, -1)
    rf_boruta.predict_proba(data_for_prediction_array)
    explainer = shap.TreeExplainer(rf_boruta)
    # Calculate Shap values
    shap_values = explainer.shap_values(data_for_prediction)
    shap.plots._waterfall.waterfall_legacy(explainer.expected_value[0], shap_values[0],ord_test_t.iloc[row_to_show])

When I did `explainer.model_output`, it gives `raw` as output
This generated the plot as shown below

![image](https://user-images.githubusercontent.com/30723825/161003033-b96b3e81-c253-43c5-80df-3f467d6034cd.png)

But one thing that I realized was that **for all row indices my SHAP base value is 0.5**. Do you know what does that mean? Is this waterfall plot specific or data specific? My feature contribution adds on top of 0.5. sometimes my feature contribution takes it to 0.80 or sometimes, it ends up at 0.20 (substracts from 0.5). 

Please note that this question is not code related question. Instead, I would like to know why does SHAP base value is always 0.5 in my waterfall plot for a binary classification problem? Why cna't the base value be 0.2, 0.3 etc?

  [1]: https://i.stack.imgur.com/rFXlA.png

**Comment by buhrmann** [comment]
Same here, expected values are always ~0.5. Also, "raw" output seem to be probabilities in [0,  1] not log odds or whatever as is the case when using catboost e.g. And, or but, the final value (expected + SHAP) don't add up to the predicted probabilities of the model.

**Comment by SSMK-wq** [comment]
Did set check_additivity = True? I am not sure whether this is the solution
but it worked for me when I set this (final values matched with model
probabilities)
