### ISSUE TITLE
Shap has no attribute plots

### ISSUE THREAD

**Issue by ArpanC25** [shap/shap#2479]
Whenever i try to use shap.plots i encounter the error that shap has no attribute plots. I am using shap 0.40.0.

Is there a python version issue somewhere? I dont understand what might be the issue.

**Comment by snehankekre** [comment]
Same here. With `shap==0.40.0` I used to be able to [override](https://github.com/snehankekre/streamlit-shap/blob/1ce71502ed41d9321fca4d9a62382797ed81ccc2/streamlit_shap/__init__.py#L7) the defaults for `shap.plots.text.__defaults__ = (0, 0.01, '', None, None, None, False)` in my [package](https://github.com/snehankekre/streamlit-shap/). It used to work last month. Not sure what changed, but it doesn't work anymore.

**Comment by ArpanC25** [comment]
Hi .. i resolved this after installing matplotlib. Shap internally uses matplotlib to plot the graphs. Install matplotlib and your error should be resolved.

**Comment by snehankekre** [comment]
Thank you so much, @ArpanC25. That worked! 🤦 I'll make `matplotlib` a required dependency of my package that uses SHAP.
