### ISSUE TITLE
SHAP All Positive

### ISSUE THREAD

**Issue by rm17tink** [shap/shap#2484]
More of  a question but all my SHAP values are positive. Am I getting the values correct for the given model?  Is there a better way to get the class 1 variables for a light gbm 

```
import shap
import numpy as np

# pass in model
explainer = shap.TreeExplainer(best_booster.booster_)
shap_values = explainer.shap_values(X_train[cols_to_keep_sans_meg_1]) 

#shap values 
vals= np.abs(shap_values[1]).mean(0)

#shap.summary_plot(shap_values, X_train[cols_to_keep])

# Build a dataframe storing the SHAP
fold_importance_df = pd.DataFrame()
fold_importance_df["Feature"] = X_train[cols_to_keep_sans_meg_1].columns.values
fold_importance_df["Importance"] = best_booster.feature_importances_
fold_importance_df["shap_values"] = vals
fold_importance_df['coef'] = fold_importance_df.shap_values.map(lambda x: '+'if x>=0 else '-')
# fold_importance_df.to_csv("shap_values.csv")

fold_importance_df.sort_values(by='Importance', ascending=False).head()
```

**Comment by j-adamczyk** [comment]
It is indeed possible to have a single sign Shapley values. Consider a simple toy example: N-dimensional dataset, where positive class has nonnegative value of each feature and negative class has negative value of each feature. If you had a point with all nonnegative values, then all Shapley values would be positive for it, as all features indicate that the class should be a positive class. Of course, this will happen only for "obvious" examples, where model is 100% sure that all values of all features point to the same class.
