### ISSUE TITLE
shap_values.base_values become weird when the size of maskers is larger than 100.

### ISSUE THREAD

**Issue by yipei-wang** [shap/shap#2487]
I tried a simple model `model` with input data `x` and background data `X`. The exact SHAP is implemented as
```
explainer = shap.explainers.Exact(model, X)
shap_values = explainer(x)
```
From the paper, I expect that `shap_values.base_values[0,0]` should be equivalent to `model(X).mean()`. But the I found that this is true only if `X.shape[0]<=100`. When the number of samples in `X` is greater than 100, the reference value becomes weird and I don't know how it is calculated.

I am confounded by this phenomenon, am I doing it wrong? I really appreciate it if anyone can help me with this issue!

**Comment by AnotherSamWilson** [comment]
This is probably caused by a hard coded limitation to 100 samples in the background set:
https://github.com/slundberg/shap/issues/1991

Caused by this guy:
https://github.com/slundberg/shap/blob/b6e90c859fdfc6bc145242d9a8082d4ad844e995/shap/maskers/_tabular.py#L243
