### ISSUE TITLE
[Tree Explainer] shap.TreeExplainer.expected_value meaning

### ISSUE THREAD

**Issue by pep3e** [shap/shap#2497]
I have the following model:
RandomForestRegressor from scikit-learn with hyperparameters:
RandomForestRegressor(min_samples_leaf=1, max_features='sqrt', min_samples_split=2, warm_start=False, bootstrap=True, n_jobs=-1, oob_score=True, random_state=0)

When I create instance shap.TreeExplainer and get expected value I get: **4.513963**
When I do the mean of model.predict(X) I get: **4.474953**

How could I explain the difference and what is the meaning of the expected_value since it is not simple mean of all predicted Ys?

**Comment by easyautoml** [comment]
Hi @pep3e. I got same problem with you and make some research, the expected value is calculated from target of train set. not calculated from your predict set.
Shap will get target values saved on estimator of model. 
If you set your RandomForest's n_estimators = 1. You will get the expected value = mean (target) on your train set.
