### ISSUE TITLE
Missing matplotlib in Waterfall plot

### ISSUE THREAD

**Issue by YueCastillo** [shap/shap#2504]
I'm getting an error when trying to not show the waterfall plots:

![Screenshot from 2022-04-19 07-26-32](https://user-images.githubusercontent.com/67152592/164003259-9778266d-235c-4dff-81fd-fa44f2fe0edd.png)

The same parameter can be used with no problem for the heatmap, scatter, or bar plots:
![Screenshot from 2022-04-19 07-28-40](https://user-images.githubusercontent.com/67152592/164003628-aef9301a-12da-4252-bf79-46edb154657b.png)

**Comment by YueCastillo** [comment]
Temporary workaround in https://github.com/slundberg/shap/issues/2283#issuecomment-976950942

**Comment by thatlittleboy** [comment]
Should've been fixed already. Closing
