### ISSUE TITLE
Shap with multi-class classification 

### ISSUE THREAD

**Issue by rohithteja** [shap/shap#2509]
I am working with a multi-class classification problem with 4 classes and a random forest model. I was able to retrieve the shape values for the model and make a stacked bar plot showing all 4 classes. The bar plot shows the mean absolute shap values for each feature. Does it make sense to make two stacked bar plots, one using mean positive shap values and other with the mean negative shap values? I am a bit confused on how to do it. Most of the tutorials focus on the mean absolute shap values.
Any pointers would be helpful. Thanks a lot!

**Comment by sorenwacker** [comment]
Can you share some example code? I am stuck with a similar problem. I can get the shap values, however the shape is 3D. Now, I am not sure how to use these values.

**Comment by rohithteja** [comment]
Sure, I used the following code to create a stacked bar plot with all 4 classes:

```
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)
shap.summary_plot(shap_values, X_test, plot_type="bar",
class_names=['Low','Medium','High','Very High'], class_inds=[0,1,2,3])
```
Not sure if this would work for your case but you can try removing one class. "shap_values" variable is a list of 4 arrays (one for each class). Hope his helps!
