### ISSUE TITLE
Typo in Corollary 1 of paper "Unified Approach ..."

### ISSUE THREAD

**Issue by arilapluie** [shap/shap#251]
Dear Scott and Su-In,

I have a question about your Corollary 1 (Linear SHAP) on page 6 of your paper "A Unified Approach to Interpreting Model Predictions." Is the formula phi(i) correct? is phi(i) the SHAP value for an individual observation in that case? if it is, shouldn't the notation be: phi(i) (f, x) = w(j) (x(i) - E[x(j)])? or was phi(i) really phi(j), that is, the SHAP value for feature j? then in that case the notation is phi(j) (f,x) = w(j) (x(j) - E [x(j)]) with each element of the formula being a vector, not an individual observation?

I would greatly appreciate your answer to my question. 

Thank you,

Ariadna Martínez

**Comment by slundberg** [comment]
Thanks for pointing this out! It is a typo, `\phi_i(f,x)` should actually be `\phi_j(f,x)`. There is also a another typo (sorry!) in this equation that I should point out, `\phi_0(f,x) = b` should be `\phi_0(f,x) = b + \sum_j^M \beta_j E[x_j]` (which matters when your features are not mean centered).

**Comment by arilapluie** [comment]
Thank you, Scott! So, that \phi_j(f,x) equation is comprised of the vector wj = {w_1j, w_2j, ..., w_nj}, xj ={x_1j, x_2j, ..., x_nj}, and E[xj] = {E[xj], E[xj], ..., E[xj]}?

**Comment by slundberg** [comment]
`w_j` is just a single number, the coefficient for the jth parameter of the model. But otherwise, yes.

**Comment by arilapluie** [comment]
Thank you soooo much, Scott! Now everything is clear for me, I really appreciate your time and help!
