### ISSUE TITLE
All SHAP values are rounded to 0 in bar plot

### ISSUE THREAD

**Issue by skylerwharton** [shap/shap#2510]
Hi! Thank you for creating this fantastic library! I have a question that I was hoping you could answer: 

I'm calling `shap.plots.bar(shap_values, max_display=10)`, but the plot that is printed seems to round all of the SHAP values to `0`, instead of printing values like, for example, `0.001` or `0.0005`. Do you know what's going on here? Is there a way to instruct the function to print at least (for example) 5 decimal places? 

Thank you! 

<img width="469" alt="SHAP plot where each bar is labeled with '+0'" src="https://user-images.githubusercontent.com/3880084/164320155-ae7c3333-e148-47df-960b-f5a378efc0c5.png">

**Comment by JPK01** [comment]
Hey, I experience the same issue right now. Did you resolve this in the meantime? Your reply is highly appreciated.

**Comment by skylerwharton** [comment]
Hi @JPK01! No, I unfortunately wasn't able to resolve this issue. To get around it, I created my own graph using the raw SHAP values and matplotlib.

**Comment by JPK01** [comment]
Thanks a lot for your reply. Is there any chance you have a code example on how the manual graph can be created from the SHAP values?

**Comment by haochuan-li** [comment]
you can simply modify the source code of barplot, search for "format_value" and change to your ideal decimal numbers
