### ISSUE TITLE
shap values on time-series data

### ISSUE THREAD

**Issue by mattia-** [shap/shap#2526]
Hello,

I'm sorry if this was answered already, but I could not find any thread with a conclusive solution to my problem.

Basically, I'm trying to compute shap values on an LSTM model, which has input shape `[n_samples, n_timesteps, n_features]` and output shape `[n_samples, n_timesteps, n_outputs]`. The main difference with respect to the DeepExplainer example [here](https://shap-lrjball.readthedocs.io/en/latest/example_notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html) is that the network output retains the time axis, by outputting a value for each time step.

I tried using either DeepExplainer or GradientExplainer, but they both complain that `The model output must be a vector or a single value!` but clearly that is not the case in my example (even if` n_outpus = 1`).

Browsing through the various related issues I found, I stumbled upon [this](https://towardsdatascience.com/interpreting-recurrent-neural-networks-on-multivariate-time-series-ebec0edb8f5a) link (which, to be honest, I have not tried yet), but I was wondering if there is no officially supported way to use this kind of data within shap.

Thanks a lot!

**Comment by wiktorolszowy** [comment]
I am using GradientExplainer on LSTM models that include multiple output time points and multiple output variables, but I flatten the output to a vector (of the length ```n_timesteps*n_outputs```), already before training the LSTM models. ```n_outputs``` should not be there, as it adds a 3rd dimension, that is why you can't run the explainer when ```n_outputs=1```. So maybe you can flatten the output? Later you can recover the last dimension with ```reshape```.

**Comment by mattia-** [comment]
Thank you for your reply.

If I understood correctly (please do correct me if I'm wrong), you're suggesting something along the lines of this:
```
import tensorflow as tf
import shap
import numpy as np

def main():
    print('Loading data...')
    n_features = 3
    n_targets = 2
    n_samples = 5
    n_timesteps = 4
    train_x = np.random.random((n_samples, n_timesteps, n_features))
    train_y = np.random.random((n_samples, n_timesteps * n_targets))

    print('Build model...')
    inputs = tf.keras.Input(shape=(None, n_features))
    x = tf.keras.layers.LSTM(n_targets, return_sequences=True)(inputs)
    outputs = tf.keras.layers.Flatten('channels_last')(x)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    model.summary()

    # try using different optimizers and different optimizer configs
    model.compile(loss='MeanSquaredError',
                  optimizer='adam',
                  metrics=['accuracy'])

    print('Train...')
    model.fit(train_x, train_y,  epochs=1)  # dummy training

    # ------------------ #
    print('Computing shap values...')

    explainer = shap.GradientExplainer(model, train_x)
    shap_values = explainer.shap_values(train_x)

    print('Done')


if __name__ == '__main__':
    main()
```

Is this correct?

I'm asking because this yields a different problem: `TypeError: 'NoneType' object cannot be interpreted as an integer`, so I was wondering what I did wrong.

Thanks!

**Comment by wiktorolszowy** [comment]
there are some shape problems; you can change:

```inputs = tf.keras.Input(shape=(None, n_features))```

to 

```inputs = tf.keras.Input(shape=(n_timesteps, n_features))```

**Comment by mattia-** [comment]
Sorry for the super-late reply and thanks again for the time you spent answering my doubts!

I spent some time looking deep into this and I wanted to share what I found, in case anyone gets here googling the same thing, so here it is:

- as of June 2022, SHAP's intended use is only on stationary data; LSTM networks are handled (using the class `DeepExplainer`), but only insofar as the output is still a single value (see e.g. [this](https://shap-lrjball.readthedocs.io/en/latest/example_notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html));
- I found a different [library](https://github.com/feedzai/timeshap), based on SHAP, that can be used on time-dependent models, as the class `KernelExplainer` is expanded to handle feature-, timestep- and cell-importance; this library, however, is still limited to models with single-valued outputs;
- the only way I found to compute feature importance on time-dependent models with time-dependent outputs while at the same time keeping the missingness, local accuracy and consistency properties mentioned in the paper for the SHAP library valid, was to write custom code, using the `KernelShap` explainer on each timestep in a loop; the code I wrote is extremely tailored to my model (I just wanted something that would work quickly), but the idea is generic enough and can be applied to any other model architecture

**Comment by pedro-zenario** [comment]
> Sorry for the super-late reply and thanks again for the time you spent answering my doubts!
> 
> I spent some time looking deep into this and I wanted to share what I found, in case anyone gets here googling the same thing, so here it is:
> 
> * as of June 2022, SHAP's intended use is only on stationary data; LSTM networks are handled (using the class `DeepExplainer`), but only insofar as the output is still a single value (see e.g. [this](https://shap-lrjball.readthedocs.io/en/latest/example_notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html));
> * I found a different [library](https://github.com/feedzai/timeshap), based on SHAP, that can be used on time-dependent models, as the class `KernelExplainer` is expanded to handle feature-, timestep- and cell-importance; this library, however, is still limited to models with single-valued outputs;
> * the only way I found to compute feature importance on time-dependent models with time-dependent outputs while at the same time keeping the missingness, local accuracy and consistency properties mentioned in the paper for the SHAP library valid, was to write custom code, using the `KernelShap` explainer on each timestep in a loop; the code I wrote is extremely tailored to my model (I just wanted something that would work quickly), but the idea is generic enough and can be applied to any other model architecture

Hi! Would you be able to provide the code you wrote?

**Comment by mattia-** [comment]
Hi! Sorry, but unfortunately I can't. It was written for internal use within the company I work for, and I'm not allowed to share it

**Comment by Christian-lyc** [comment]
Hi, sorry to interrupt, I also have a problem with it. my dataset is same as yours, samples*time steps*features, but I want to explain different features, I found the official example is for time steps explanation. How can I use Deepshap or Kernelshap for feature explanation? Thank you so much

**Comment by mattia-** [comment]
Hi Christian,
sorry, I didn't quite understand what you're trying to do. Would you be able to provide a MWE highlighting your problem?

**Comment by Christian-lyc** [comment]
> Hi Christian, sorry, I didn't quite understand what you're trying to do. Would you be able to provide a MWE highlighting your problem?

Thank you so much for your reply.  As most of the LSTM use case is using the output of last time step and concatenate it with current features, which will lead to better performance. Especially in the infectious disease field, we concatenate the output of current time step (newly infected cases) with the covariates of the next time step. My data shape is same as yours [n_samples, n_timesteps, n_features]. output shape is n_samples x 1, is newly infected cases. Basicly, is regression problem. How can I use Deepshap or Kernelshap for feature explanation?

**Comment by mattia-** [comment]
I see, but what are you stuck on? Have you tried using the explainers in the library and gotten an error? In that case, what error and using what explainer? Could you provide the code you wrote (preferably as a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example))?

Also, unless this is strictly related to a time-dependent output (and, as far as I can tell, it isn't), your best course of action would be to open a new issue, since this is not the right thread to discuss unrelated problems

**Comment by oscarescuderoarnanz** [comment]
> Sorry for the super-late reply and thanks again for the time you spent answering my doubts!
> 
> I spent some time looking deep into this and I wanted to share what I found, in case anyone gets here googling the same thing, so here it is:
> 
> * as of June 2022, SHAP's intended use is only on stationary data; LSTM networks are handled (using the class `DeepExplainer`), but only insofar as the output is still a single value (see e.g. [this](https://shap-lrjball.readthedocs.io/en/latest/example_notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html));
> * I found a different [library](https://github.com/feedzai/timeshap), based on SHAP, that can be used on time-dependent models, as the class `KernelExplainer` is expanded to handle feature-, timestep- and cell-importance; this library, however, is still limited to models with single-valued outputs;
> * the only way I found to compute feature importance on time-dependent models with time-dependent outputs while at the same time keeping the missingness, local accuracy and consistency properties mentioned in the paper for the SHAP library valid, was to write custom code, using the `KernelShap` explainer on each timestep in a loop; the code I wrote is extremely tailored to my model (I just wanted something that would work quickly), but the idea is generic enough and can be applied to any other model architecture

Could you give mathematical guidelines or reference to some work that allows to carry out the implementation?
Thanks @mattia- !

**Comment by mattia-** [comment]
Hi @oscarescuderoarnanz ,

I'm terribly sorry, but to be honest I don't recall the details anymore (it's been too long :) ), and I don't have access to the code I wrote, as I moved on to a different job in the meantime.

What I do recall is this.
At each timestep, you basically compute one single step in the LSTM network and apply the regular `KernelShap` explainer, treating the hidden state and the cell state as regular features. This means that, for each timestep, you will also see how important the states are (which is kind of interesting in its own right).
The rest of the code merely made sure that I was calling the LSTM cell with the proper inputs, in particular with reference to the states. This entails storing the state values at the last call and injecting them by hand in the current call, then making sure to retrieve the values at the current step so that you can use them in the next.

Does this make any sense to you?

**Comment by cafer53** [comment]
Hi, I want to estimate the number of passengers. I separated the hourly data into columns with temporal variables. hour, day, month, day of the week, day of the month. with this data I want to estimate the number of lstm passengers. but my researches did not find anything related to lstm feature selection. It is simpler than yours because it has a single target variable. My goal is to find out to what extent the independent variables affect the target variable. Since I will add other data, it would be unreasonable to do trial and error. I will not put unnecessary variables in the model. I'd really appreciate your help.

**Comment by oscarescuderoarnanz** [comment]
Hello @cafer53 @Christian-lyc @pedro-zenario 

I have worked on a method for time series, I leave here the link to the paper where you can also find the url to the code: https://arxiv.org/abs/2407.17165

Best regards,
Oscar.
