### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by jhdxr** [shap/shap#2537]
Hi, may I know if there is plan for a new release recently? The last release is more than half year ago, and there are many commits since then. Personally I'm interested in the fix for `shap.plot.text(display=False)`. I have applied a fix locally, but it's not easy to tell others how to apply the fix. A new official release will definately help that. Thanks.

**Comment by princessofpillows** [comment]
Bumping for visibility. Release 0.40.0 has many issues and a new release would be very helpful.
