### ISSUE TITLE
TabNet Implementation

### ISSUE THREAD

**Issue by sooeun67** [shap/shap#2538]
Thanks for the amazing tool!

I was wondering if you have any implementations for [TabNet](https://github.com/dreamquark-ai/tabnet) ( I understand SHAP works with any model though) -- any kind of tutorial/examples that calculate shapely value (viz would be great) on TabNet model would be super helpful

-- small update --
I've tried applying shap using kernel explainer, which is supposed to be working with any model, but it seemed to be wrong as it returned the error that `TypeError: 'TabNetRegressor' object is not callable` -- any thoughts on this? 

<img width="816" alt="스크린샷 2022-05-10 오후 5 30 40" src="https://user-images.githubusercontent.com/32501921/167584951-91e700a5-4edc-4391-b159-e08087247a85.png">

Please note that I've attached a [colab link with full code](https://colab.research.google.com/drive/1bAXxurZEWfkCTyPeJn0YbHMrSKbneOKL?usp=sharing)
- fyi: The colab notebook/TabNet model that I've been using is [TabNet's official sample notebook](https://github.com/dreamquark-ai/tabnet/blob/develop/regression_example.ipynb)

Thanks in advance!
Sooeun

**Comment by omkarmutreja12** [comment]
Even I've the same question; Can we implement Shap on Tabnet predictions?

**Comment by MustaphaU** [comment]
TabNet has no tailored explainer like TreeExplainer for tree-based models like Random forest and boosted trees..

Edit: just found that the KernelExplainer of SHAP can be used on just about any model but you must call the explainer with the appropriate predict function of the model.

In your case @sooeun67 `shap.KernelExplainer(loaded_clf.predict, X_train)` should work. The `.predict` function was missing in your code.

**Comment by dsgibbons** [comment]
I don't understand. The notebook you attached correctly `shap_values` without raising an error:

![image](https://github.com/slundberg/shap/assets/82195909/a2f3eb52-3901-4c4c-bc1c-92f9b862a407)

Can you please provide a shorter example in a ```python formatted code block that shows this error?

**Comment by MustaphaU** [comment]
@dsgibbons I guess the error was not calling the KernelExplainer with the appropriate predict function of the loaded model. The correct call would be `shap.KernelExplainer(loaded_clf.predict, X_train)`  instead of `shap.KernelExplainer(loaded_clf, X_train)`. That was the cause of the error.
