### ISSUE TITLE
Automatically selecting the other feature in SHAP dependency plots.

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#254]
Hi,
I just need to know how you select the other feature in SHAP dependency plots. I saw that you have mentioned that you guess other feature as the strongest interaction with the plotted feature. But still, I can't understand how you guess that. Simply I feel that it is mentioned in approx_interactions function. From there I got to know "Order other features by how much interaction they seem to have with the feature at the given index.This just bins the SHAP values for a feature along that feature's value." 

Could you please explain it deeper to gain a better understanding. 

My next question is, in dependency plot, do we just use the automatically selected feature to just the color the plot? Because in your code you have used this term "  interaction_index : "auto", None, or int
 The index of the feature used to color the plot."
I read your Tree SHAP paper which is very interesting. In there I saw that you have mentioned, in dependency plot is a mix of SHAP interaction values for both the features and main effect from the feature selected to x-axis? Am I correct? As I feel, I think that automatically selected feature helps to interpret dependency plot, not only to color the plot. 

Could you please correct me if I am wrong?

Thank you in advance.

**Comment by slundberg** [comment]
1. I compute the correlation of the SHAP values in a vertical slice of the dependency plot with each other feature in the model. The one with the highest correlation is likely to have a strong interaction effect with the current feature and so is selected for coloring.

2. It is very helpful to know what interaction effects are causing the vertical dispersion, and the auto-chosen one is a good guess at the largest feature interaction. To be sure though, you would need to call shap_interaction_values

**Comment by clamdown2020** [comment]
Is it possible to choose other feature (on Y axis) instead of it automatically selecting it - if so, can you please explain how to do it ?

**Comment by slundberg** [comment]
Yep just use the `interaction_index` option.
