### ISSUE TITLE
Is it possible to create a dependence plot with an interaction variable not used in the model (and therefore a variable with no SHAP values)? 

### ISSUE THREAD

**Issue by nenzer** [shap/shap#2541]
I am creating "Model A" with various predictors (including "Variable A") and making a dependence plot for all the predictors with "Variable A" as an interaction variable. 

I am also creating "Model B" with various predictors (not including "Variable A"). 

Is it possible to create a dependence plot for the predictors of "Model B" using "Variable A" as an interaction variable? If so, what would be the best way? Thanks!

**Comment by j-adamczyk** [comment]
If the model does not use a particular variable, then it has no Shap value, or precisely the impact of that feature is always 0. If you included it in the dependence plot, it would never be plotted, as values with no impact are omitted.

**Comment by nenzer** [comment]
Thanks! That makes sense. I realize now that what I wanted wasn't a dependence plot, but moreso a scatter plot. Thanks again!
