### ISSUE TITLE
SHAP predictions not matching model predictions

### ISSUE THREAD

**Issue by vburb** [shap/shap#2544]
Hi @slundberg , 

I am loving the shap package but I am having difficult time find a answer to my question. Maybe I am missing something, so please advise if I am. 

I have a LightGBM regressor  model trained for a continuous outcome variable. I am using SHAP to explain local interpretability, however I am noticing the model prediction for a row of data does not match the model prediction SHAP gives me. The output my model is giving me is not matching the SHAP base value plus the sum of the feature individual SHAP values. 

![image](https://user-images.githubusercontent.com/94019407/167946179-60923cd4-4ddd-4cee-9ee4-241864c5db30.png)

**Comment by Rihab114** [comment]
You are predicting on test data (pred) so eventually, pred[0] is associated with y_test[0], in other words,  change to : 
```
print(f"y test data {np.array(y_test)[0]} model prediction: {pred[0]}")
```
and for the second part, this works for me : 
```
print(f"total sum of shap values:  {sum(shap_values[0])} shap prediction: {ex.expected_value+ sum(shap_values[0])}")

```

**Comment by vynlburb** [comment]
@Rihab114  Yes sorry, thanks for catching that train/test mistake. However I am still getting two different values from it from my model pred value and my shap prediction value. 

`print(f"raw labeled data {np.array(y_test)[0]} model pred {pred[0]}")`
`print(f"total sum of shap values:  {sum(shap_values.values[0])} shap prediction: {explainer.expected_value + sum(shap_values.values[0])}")`

raw labeled data 281.9032258064516 model pred 501.99916892124986
total sum of shap values:  -1027.040785589894 shap prediction: 413.09855088021914

**Comment by vburb** [comment]
Ah I think I found solution. Need to read into it more, but when I use `explainer.shap_values()` instead of `explainer()` and obtaining the shap_values by `shap_values.values` like I did above I get the correct prediction on both values. 

Will need to read into this more, any general idea on why this is? Does it have to do with the interaction affects it is calculating?

So full solution is this:
```
explainer = shap.Explainer(model)
shap_values = explainer.shap_values(X_test)
print(f"raw labeled data {np.array(y_test)[0]} model pred {pred[0]}")
print(f"total sum of shap values:  {sum(shap_values[0])} shap prediction: {explainer.expected_value + sum(shap_values[0])}")
```

raw labeled data 281.9032258064516 model pred 501.99916892124986
total sum of shap values:  -938.1401675488643 shap prediction: 501.99916892124895


instead of this:
```
explainer = shap.Explainer(model)
shap_values = explainer(X_test)
print(f"raw labeled data {np.array(y_test)[0]} model pred {pred[0]}")
print(f"total sum of shap values:  {sum(shap_values.values[0])} shap prediction: {explainer.expected_value + sum(shap_values.values[0])}")
```
raw labeled data 281.9032258064516 model pred 501.99916892124986
total sum of shap values:  -1027.040785589894 shap prediction: 413.09855088021914
