### ISSUE TITLE
method_name in local_accuracy

### ISSUE THREAD

**Issue by Rihab114** [shap/shap#2546]
Hey there, 
can anyone give me details about the method_name parameter in the metrics functions what it is about exactly and how we fix it?
Thanks in advance. 
```
def local_accuracy(X, y, model_generator, method_name):
```

**Comment by Rihab114** [comment]
Answer: method_name are methods listed in the shap/methods.py

**Comment by haochuan-li** [comment]
Hi, thanks for your answer. I also wonder what's the model_generator parameter?

**Comment by maayanorner** [comment]
> Hi, thanks for your answer. I also wonder what's the model_generator parameter?

Looking at the source code https://github.com/slundberg/shap/blob/b6e90c859fdfc6bc145242d9a8082d4ad844e995/shap/benchmark/metrics.py I think it would be a class ref to the local model you fit...?

**Comment by maayanorner** [comment]
> Hi, thanks for your answer. I also wonder what's the model_generator parameter?

I am not sure but I think (looking at the source code) it's:
metrics.local_accuracy(X, y, SomeSkleanModel, 'sampling_shap_1000')

It would be SomeSkleanModel (a class ref) of the local classifier you want to evaluate.

For example, for me metrics.consistency_guarantees(X, y, LinearRegression, 'sampling_shap_1000') gives some reasonable score (I do regression).

Full example:

```
from shap.benchmark import metrics
from shap.benchmark import methods
from sklearn.linear_model import LinearRegression

print(dir(methods))
... get X and y

print(metrics.consistency_guarantees(X, y, LinearRegression, 'sampling_shap_1000'))
```

Doing so for classification is the same (use another local model and another method from metrics).
