### ISSUE TITLE
shap values vs. data - length

### ISSUE THREAD

**Issue by Liatant1** [shap/shap#255]
Hi,

I am using shap kernel (but checked it also in your notebook 'Census income classification with scikit-learn') and I see that the length of shap_values is longer in one than the instance (X_train in your notebook).

Can you please explain this difference? I would like to use the results not with one of your plots and make sure which column names to use (first column in shap_values refer to the index in x_train and then I need to start from the second column in shap_values? or to the first column that is not the index?

Thanks alot

**Comment by slundberg** [comment]
Perhaps you have an older version of shap installed? After v0.20 the shape of the feature importance matrix is the same shape as the input sample matrix. The last column used to be the expected value of the model over the background dataset, but now that is stored in `explainer.expected_value`. This change was made to avoid the confusion you are mentioning.

**Comment by Liatant1** [comment]
Sorry for the delayed reply.
Thank you! It solved my problem (:
