### ISSUE TITLE
How to use Shap on ASR models

### ISSUE THREAD

**Issue by StephennFernandes** [shap/shap#2552]
Hey there, thanks for providing such an marvelous tool. I've been trying to find a way to interpret ASR models using Shap, but couldn't actually find anything in the docs. 
Would be great if could somehow use Shap on wav2vec2 type ASR models and interpret the audio sequence with the output char/word predictions.

**Comment by raaaouf** [comment]
hello did you find a way?

**Comment by StephennFernandes** [comment]
not yet. would surely post my findings here, if anything works out
