### ISSUE TITLE
Summary Plot - Diabetes regression

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#256]
Hi,

I just need to clarify that the way I am thinking is correct. In your  Diabetes regression example, in summary plots it explains that, when we are getting older we are less likely to suffer from Diabetes? Am I correct?

**Comment by slundberg** [comment]
If you are just looking at the linear model then I would say a *very qualified* "yes". It is one of the least important features, so it does not look like a strong effect. It is also likely not a causal effect.

**Comment by DiliSR** [comment]
It is shown in every model. Not only linear model.  So that conclusion is same foe others as well? right.

**Comment by DiliSR** [comment]
Thank you very much
