### ISSUE TITLE
Setting TreeExplainer Base Value to 0: possible? How?

### ISSUE THREAD

**Issue by Bakkat2** [shap/shap#257]
Hi, 
First thank u very much for this awesome library!

I am interested on the TreeExplainer described here https://github.com/slundberg/shap

![image](https://user-images.githubusercontent.com/3450005/45269990-ae175600-b46d-11e8-9018-6a60081f12d1.png)

**My question would be if it is possible to set in advance the "Base Value" to 0?** 

In the example mentioned (with Boston DS) what i would like to achieve it ll be the values that added sum the output from scratch, instead from the "Base Value". Is that possible? How?

**Comment by slundberg** [comment]
Hey! The base value is just expected value of the model. So you could
change the number of samples recorded in the tree (the training dataset
counts for the splits) or perhaps easier you could just draw a bar from
zero to the base value and name it “bias term” or “base rate bias” or
something similar.

**Comment by Bakkat2** [comment]
Thanks for your answer, and great to know it is possible :D

Sorry, but I did not get how to do it, u mean that i have to pass the "bias term" as a parameter of the
![image](https://user-images.githubusercontent.com/3450005/45295705-08e49800-b4d6-11e8-86b3-f5225e43b391.png)
?

**Comment by slundberg** [comment]
I mean attach a bias term as another column of the shap_values matrix that is equal to explainer.expected_value, then just pass 0 for the expected value when calling force_plot

**Comment by Bakkat2** [comment]
Thank u very much! I ll try that.

**Comment by Bakkat2** [comment]
HI,
I have tried what you sugested, but i think is not what i was looking for.

Sorry, i think i did not explain myself properly.

What i would need is that when the "TreeExplainer" fuction is called, and the contribution of each parameter to the output is calculated, the base value used was 0.

Would that be possible?

thank u very much

**Comment by slundberg** [comment]
Could you post code that shows what you did? That might help clarify things.

**Comment by Bakkat2** [comment]
What I did was:
h=pd.DataFrame(data=shap_values,columns=X.columns)
h["BV"]=explainer.expected_value
h=np.array(h)
shap.force_plot(0, h[0,:-1], X.iloc[0,:])


Since i got the error of "too many columns" y did not pass the "BV" to the force plot.
![image](https://user-images.githubusercontent.com/3450005/47256956-19394c80-d45e-11e8-8d44-5488081edae0.png)

But i gess that with that colum includded i would have got a huge "contribution" of the Base Value from 0 to the "Output", rigth? (in this particular case 14,2 of 16,4 that is the output), because the add up of the others variables contribution is just 2,17.

What i would like to get, would be a recalculated contribution of each variable in order to get their contribution mesured from 0 to the output.

Maybe i should distribute the expected value base value on each contribution amount? I mean a direct distribution. Contribution of CRIME, for example, would be: 0,2/2,17*16,40=1,51.

**Comment by slundberg** [comment]
Sorry for delay. If you want to divide up the credit for how you got from 0 to the current output, part of the responsibility is not specific to any given feature. That part is the amount in the expected value of your model. You could explicitly plot it by doing:
```
shap.force_plot(
    0,
    np.hstack([shap_values[0,:], explainer.expected_value]),
    pd.concat([X, pd.DataFrame({"Base value": [explainer.expected_value]})], axis=1).iloc[0,:]
)
```

**Comment by Bakkat2** [comment]
Please, don t mind. I really preciate your answers. They are very helpfull! Thank you very much for your time, i mean it.
I got it, its clear that theres a part of the output that is not explained by the variables and is razonable to have an expected value. 
But if i am not wrong , you define the expected value in advance (i mean before finding the shap values) as the mean of the target in the training data set. 
What i would like to do is to set it in advance as 0, or as 1, or another number and check the shap values generated. Probably this would be theorically wrong, since i would be asuming that the variables are capable of explaining the hole output (or a part arbitrary choosen), but I would like to use them, even under those strong asumptions.
Would that be possible?

**Comment by slundberg** [comment]
The way the SHAP values are computed in the code assumes we are using
conditional expectations, so they will always sum up across all features to
the difference in the model's mean output and current output (there is not
a way to simply change the definition of the conditional expectations to
sum from 0). You can however for plotting purposes change the "base value"
to 0 or 1 and then add the difference between the expected_value and 0 or 1
as an extra bar in the plot. That's the closest thing I can think of.

**Comment by cbeauhilton** [comment]
Just wanted to leave a note here: 

@slundberg's  solution works very well. Attached is an example of the output along with the complete code I used. 

![image](https://user-images.githubusercontent.com/34774299/53436309-edf4da00-39c8-11e9-9173-da35e0eefdf1.png)

```    
  shap.force_plot(
        0, # set base value to zero
        np.hstack([shap_values[0, :], explainer.expected_value]), # add expected value as a bar in the force plot
        pd.concat(
            [c_features, pd.DataFrame({"Base value": [explainer.expected_value]})],
            axis=1,
        ).iloc[0, :], # grabs the identities and values of components
        text_rotation=30, # easier to read
        matplotlib=True,
        show=False, # allows saving, etc.
    )
```

The features are whited out because they contain potentially sensitive info, not because there was a problem with SHAP's output. Also, in this example "base value" is obscured because "output value" is too close, but this is also something we can fix later for presentation.

P.S. I recommend closing this issue, if all are amenable.

**Comment by JyotiPrakashBal** [comment]
Has someone figured a way to change the base value to 0 so that the Shap values sum is equal to the predicted value?

**Comment by renshuliang-hh** [comment]
I think you can set the background, the model will set the basevalue based on the background.If the background has only one sample x, then the predicted value y of that sample is the basevalue. But I haven't found a way to change the basevalue directly.
