### ISSUE TITLE
[Action Requested] Erroneous dependency on Numpy<1.22 for Numba when Numba now allows Numpy==1.22

### ISSUE THREAD

**Issue by ikekilinc** [shap/shap#2571]
The current version of `master` includes a dependency on `Numpy<1.22` since the master branch of Numba used to allow for any Numpy version, while being untested and uncompiled into PyPi wheels for all versions>=1.22 and even breaking under certain edge cases for those versions.

[https://github.com/slundberg/shap/blob/690245c6ab043edf40cfce3d8438a62e29ab599f/setup.py#L227](https://github.com/slundberg/shap/blob/690245c6ab043edf40cfce3d8438a62e29ab599f/setup.py#L227)

While this decision made sense at the time, [Numba has recently published a new release (v0.55.2) that now works with `Numpy==1.22`.](https://github.com/numba/numba/issues/8025) However, the current version of SHAP has not yet been updated to allow for this version upgrade.

Could we please update `setup.py` on master to now accept `Numpy==1.22`?

**Comment by q-aaronzolnailucas** [comment]
Made a PR for this: #2569
