### ISSUE TITLE
shap_interaction_values for KernelExplainer

### ISSUE THREAD

**Issue by Pablomoreiragarcia** [shap/shap#2579]
Hi, I'm explaining models loaded on python from weka and I was trying to use the summary_plot with the shap_interaction_values, but when i try to do it:
shap_interaction_values = explainer.shap_interaction_values(X.iloc[:,:])

I receive this error:
AttributeError: 'Kernel' object has no attribute 'shap_interaction_values'

Are there plans to include this feature in the SHAP library? Or is there any form to calculate it by myself?

**Comment by raqueldias** [comment]
I'm having the same problem.

**Comment by cae67** [comment]
I have run into the same problem. Is there a plan to add the interaction functionality to explainers other than the TreeExplainer, or is there a way that we can obtain interaction values for SVMs or neural networks?
