### ISSUE TITLE
Force Plot doesn't generate graph

### ISSUE THREAD

**Issue by gponcec** [shap/shap#258]
Hi, I run the examples that use boston dataset (available in github) and I can run the dependence_plot and summary_plot functions without problems, but when I use force_plot it just run without showing errors but also it doesn't generate any graph. What can I do to resolve it? 

I am using ubuntu 16.04, python 3.6.5, shap 0.24.0, xgboost 0.80, matplotlib 2.2.2. Thank you a lot!

**Comment by slundberg** [comment]
What browser version are you using? I have heard people had trouble with IE.

**Comment by gponcec** [comment]
Hello Scott, thank you to answer inmediately. I am newbie in python, then I was running my code in my desktop using the terminal. When you mention the browser I try it with chrome and Jupyter and it run perfectly.

**Comment by nlassaux** [comment]
I had to use display(force_plot()) to visualize them if outputting multiple in the same cell. You are just used to have Jupyter Notebook outputting the last value returned in the cell automatically.

https://mpld3.github.io/modules/API.html#mpld3.display
