### ISSUE TITLE
Interprete categorical Feature values in a summary plot. Is it even possible?

### ISSUE THREAD

**Issue by nilslacroix** [shap/shap#2583]
Consider this picture of a summary plot for a dataset. The data is about the prediction of housing prices, but lets just consider the
feature "Postcode" and "PropertyType". They are both categorical data, which is encoded with a CatBoostEncoder and a JamesSteinEncoder, so in general they are target encoders.

![image](https://user-images.githubusercontent.com/56065345/172354411-4f555b8c-e505-49a3-928b-b29c922cedfe.png)

It is easy to interpret them regarding importance, but how should you interprete the Feature Value? Postcode
just behaves like you would expect it to be, it is basically saying "high feature value means a high increase in price prediction" which
is logical because it is target encoded, so high values produce a high prediction.

For property type [flat, townhouse, one family house, ...] it is not really possible to explain the Feature values for each property type.

For me this means, that the interpretation of feature values for categorical features is not possible in shap and depends on the type of encoding which is used. Is that wrong or can you  give me another hint in the right direction?

**Comment by CarlaFernandez** [comment]
It does depend on the type of encoding used. After all, that's all the model "sees". In your plot, it's probably difficult to see the differences among categories because they are very intertwined. It might help you to plot the shap.plots.scatter in order to see the behaviour of that specific variable.
