### ISSUE TITLE
Beeswarm plot colormap too small

### ISSUE THREAD

**Issue by jainraj** [shap/shap#2584]
The colormap which is plotted on the right side of the beeswarm plot is too small when the number of features are less, making for a very bad experience. Could it be set as a parameter from user's side?

**Comment by LiukDiihMieu** [comment]
Same problem. It works well with python 3.6, but recently I switched to python 3.9 and the color bar suddenly disappeared. (3.6 above and 3.9 below)

![python 3.6](https://user-images.githubusercontent.com/54393775/173014985-453826f4-feb7-4088-9e12-f26de93bc34e.png)

![python 3.9](https://user-images.githubusercontent.com/54393775/173015048-f7142913-57fa-4097-8e19-f66fb8de1588.png)

**Comment by LiukDiihMieu** [comment]
According to [a StackOverflow discussion](https://stackoverflow.com/questions/70294681/colormap-bar-on-shap-summary-plot-not-displaying-properly) Matplotlib should be downgraded below 3.5.

**Comment by jainraj** [comment]
Seems to be working fine now for me 
shap == 0.41.0 
matplotlib = 3.5.2
