### ISSUE TITLE
generating text plots with custom model BART model results in page unresponsive error

### ISSUE THREAD

**Issue by tannonk** [shap/shap#2591]
Hi,

I'd currently unable to generate visualisations with SHAP and a custom BART model.

Following [this tutorial](https://shap.readthedocs.io/en/latest/example_notebooks/text_examples/summarization/Abstractive%20Summarization%20Explanation%20Demo.html) seems to work fine, and swapping out the default `sshleifer/distilbart-xsum-12-6` model for [BART-large-xsum](https://huggingface.co/facebook/bart-large-xsum) also works as expected.

However, when I load a custom BART model, the output looks like the attached image and soon after hits a page unresponsive error. The problem occurs both locally and on Google Colab. Is there a trick for using models that are not available on Hugging Face?

<img width="1447" alt="Screen Shot 2022-06-13 at 18 09 56" src="https://user-images.githubusercontent.com/10764445/173400634-e5fad2c0-20cf-46d3-a215-bf258ccbdf79.png">

Thanks!

**Comment by LukasFides** [comment]
Hi, I am having the same Issue when using a custom BART model. Have you found out what could be the problem here?

**Comment by tannonk** [comment]
@LukasFides, no, unfortunately not 😕 but glad I'm not the only one with this issue 😉

**Comment by LukasFides** [comment]
Has anyone experienced the crossing out, I could not find anything in the documentation what the crossing out refers to.
