### ISSUE TITLE
number of samples in `Kernel` explainer

### ISSUE THREAD

**Issue by wei-enwang** [shap/shap#2592]
Hi, I was studying the code of Kernel explainer and found a potential bug here. I think it makes more sense to set `self.nsamples` to `2 ** self.M + 2 ** 11` instead of `2 * self.M + 2 ** 11`.
![Screen Shot 2022-06-14 at 10 32 21 AM](https://user-images.githubusercontent.com/22818610/173603837-a0264a16-9d84-4722-a298-0692247d890b.png)

**Comment by alexisdrakopoulos** [comment]
You wrote the same thing twice (`2 ** self.M + 2 ** 11`), what did you mean?

**Comment by wei-enwang** [comment]
I am suggesting to substitute `2*self.M`(one asterisk) with `2**self.M`(two asterisks)

**Comment by xiaohk** [comment]
I believe `2*self.M` here means sampling all combinations with 1 feature and all combinations with `self.M - 1` features. These combinations have the largest kernel weights.
