### ISSUE TITLE
dependency plot  right  side bar name 

### ISSUE THREAD

**Issue by kabirmdasraful** [shap/shap#260]
Is there any way that we can define the right side bar feature name ? Or is there any example I can look into?

Thanks
![image](https://user-images.githubusercontent.com/43246170/45500052-01dfb300-b77e-11e8-9905-255f7880cee1.png)

**Comment by slundberg** [comment]
If you pass `show=False` to the `dependence_plot` function then you can call matplotlib commands afterwards and then end with a call to matplotlib's `show` command. I don't recall off-hand the matplotlib command to change a color bar label after it has been created.

Another option would be to just change the name of the feature by passing the `feature_names` argument to `dependence_plot`.
