### ISSUE TITLE
Overalapping shap_values

### ISSUE THREAD

**Issue by Anytram** [shap/shap#2610]
Hi, I want to use your libarary to explain ResNet18 that I'm using for covid chest x-rays classification.
Here is my code: 

```
import shap

batch = next(iter(test_loader))
images, _ = batch

test_images = images[3:5].to(device)

e = shap.DeepExplainer(model, test_images)
shap_values, indexes = e.shap_values(test_images, ranked_outputs=2)
class_names={"0": "COVID-19", "1": "Normal"}
index_names = np.vectorize(lambda x: class_names[str(x)])(indexes.cpu())

shap_numpy = [np.array(s).transpose(0,2,3,1) for s in shap_values]

shap.image_plot(shap_numpy, -(test_images.cpu().numpy().transpose(0,2,3,1) * 70).astype(np.uint8), labels=index_names)
```

And here is output:
![tmp](https://user-images.githubusercontent.com/37418524/177339854-fe35622b-bb0a-4e7f-bbbc-7f7a36980b28.png)

You can see that shap values seems to render all at once (from first and second image) for each label and image, what have I done wrong? :( 

Test_images shape: 2x3x512x512
Shao_numpy shape: 2x2x512x512x3

**Comment by remo-help** [comment]
I haven't used the image plot before, but it looks to me like it generates fine. Look at the dots on the lung images. The colors represent shap values of the features located in those areas. The redder the dot, the higher the value.

**Comment by Anytram** [comment]
Yes but the shape of generated shap values does not match input image. :(

**Comment by Anytram** [comment]
If you look at the first image then shap values are wider than input image. This shap vealues "mask" doesnt match an image.

**Comment by remo-help** [comment]
hmm, I dont think I can help you there, image processing is not my domain and this seems like it's a pretty domain specific issue
