### ISSUE TITLE
shap.maskers.Partition does not work unless you manually import scipy.cluster

### ISSUE THREAD

**Issue by sfriedowitz** [shap/shap#2612]
As the title suggests. The caller must manually import scipy.cluster into scope for that masker to work. 

I believe this is a bug, as the library should handle importing all its necessary dependencies internally.

**Comment by thatlittleboy** [comment]
Shouldn't be an issue anymore in the latest master version (a0b5ff866e87a2ed0be7a91df621ad05e52df750). Please re-open if the issue persists.
