### ISSUE TITLE
Shap importances of explainers.Tree and explainers.Sampling for XGBoost are vastly different

### ISSUE THREAD

**Issue by manu675** [shap/shap#2613]
Hi, I am trying to do some XAI evaluation experiments using classifiers and various Shap explainer algorithms. 
I am using a breast_cancer binary classification toy data set in order to verify that the my odd results that I get with my own data also occur here. 

![Screen Shot 2022-07-08 at 1 09 08 PM](https://user-images.githubusercontent.com/58952659/177981505-422b341b-2d62-4743-b250-ace6ef890ddb.png)

![Screen Shot 2022-07-08 at 1 07 14 PM](https://user-images.githubusercontent.com/58952659/177982179-52fd0d02-df8b-48b1-a387-3afa3b830374.png)

![Screen Shot 2022-07-08 at 1 07 37 PM](https://user-images.githubusercontent.com/58952659/177981600-095aa87f-b83c-4f69-91c4-53b9e0fa52a7.png)

As you can see in the 3 attached screenshots the order of the shap feature importances that I can extract varies greatly from Tree to Sampling even though I have used 100,000 samples for evaluating each model prediction. 
Is there anything that I have done incorrectly or is it normal that the attributions are so vastly different?
Thank you very much in advance.

**Comment by remo-help** [comment]
Some deviance between explainers is to be expected, but what you are reporting here is a bit much. What model are you using?

Try and compare the `shap_values.base_values` of both your explainer objects, that will give you an idea whether your explainers are assuming a similar mean prediction for the model.

Have you tried disabling the `nsamples` param in your Sampling explainer?

**Comment by manu675** [comment]
Hi Remo, 
I am using the following functions to extract the feature ranking: # function to extract the SHAP feature ranking (with shap_values.values for some of the algorithms). 

```
def shapley_feature_ranking(shap_values, X):
    feature_order = np.argsort(np.mean(np.abs(shap_values), axis=0))
    return pd.DataFrame(
        {
            "features": [X.columns[i] for i in feature_order][::-1],
            "importance": [
                np.mean(np.abs(shap_values), axis=0)[i] for i in feature_order
            ][::-1],
        }
    )
```

The model that I am using is a simple xgbclassifier with the following configuration:

```
XGBClassifier(colsample_by_tree=0.8, max_depth=5, missing=nan, n_estimators=300,
              n_jobs=-1, random_state=123, reg_lambda=0, subsample=0.8,
              weights=array([0.60150376, 0.60150376, 0.60150376, ..., 0.60150376, 0.60150376,
       0.60150376]))
```

I have tried to leave the nsamples parameter out (i.e. using the default) but the shap importances were also quite low. Maybe the weights are the problem. However, I have just run the model without the weights parameter and I still get very similar shap importances. 

Regarding the base_values, I have extracted the following values (using no weights parameter): (there was no base_values object for the TreeExplainer though, only the base object was available).
![Screen Shot 2022-07-11 at 11 41 10 PM](https://user-images.githubusercontent.com/58952659/178364269-a3413ceb-edf3-45b9-87d6-967dcffe14b1.png)

![Screen Shot 2022-07-11 at 11 43 22 PM](https://user-images.githubusercontent.com/58952659/178364301-cda185ae-b720-48bb-ab1c-51eb916cd0b8.png)


When leaving the nsamples parameter out (default), I get the following shap importances:
![Screen Shot 2022-07-11 at 11 55 48 PM](https://user-images.githubusercontent.com/58952659/178365772-378dc173-92ad-49bd-92fa-d03dfccf0cc4.png)

**Comment by remo-help** [comment]
_I don't have any experience with decision tree based classification, so I have not used the Tree explainer. So take everything I say here with a grain of salt,_ but here is what I _think_ is going on:

The `Sampling` explainer is a model agnostic approach that assumes feature independence.

The `Tree` explainer is designed specifically for the type of model you are using, and according to the documentation can make assumptions about feature dependence.

The differences you see here, may be due to that. Again, my experience with this type of model is limited.

Here are two ways, I think you could do some sanity checks:

- Try if the `TreeMaple` explainer from shap, the documentation on it is pretty sparse, but I think it might work for gradient tree boosting. Compare the outputs to what you have.
- For a sanity check on your `Sampling` explainer, you can try the `Kernel` explainer. This one is also model agnostic and should give you fairly similar values as the `Sampling` explainer


Also, you can just call `shap.plots.bar(shap_values_tree_toy.abs.mean(0))` to get your ranking. It should do the same thing as the function you wrote. I would test that too, see if it gives you the same ranking.

**Comment by remo-help** [comment]
addendum: if you use the Kernel Explainer, you should use a kmeans sampling for the background distribution, like this:

`kernel_explainer = shap.KernelExplainer(model.predict, shap.kmeans(X_test, 100)`
`kernel_values = kernel_explainer.shap_values(X_test)`
`explanation = shap.Explanation(kernel_values, data=X_test, base_values=np.asarray([kernel_explainer.expected_value for i in kernel_values]), feature_names=names_of_your_features)
`

The Kernel explainer requires you to manually assemble an explanation object, which is what we're doing here. It is also very slow.

**Comment by manu675** [comment]
![Lundberg on sampling, kernel and tree explainer](https://user-images.githubusercontent.com/58952659/179949548-d7991f56-adab-4798-9ddc-9a0ac2f21cec.png)

My issue is that Scott said himself that the TreeExplainer and the other explainers should essentially lead to comparable results, which is unfortunately not what I observe. And my comparison/robustness studies would be of little value if the Treeexplainer leads to very different shap importances. TreeMaple is not supported for XGBoost unfortunately. shap.plots.bar(shap_values_tree_toy.abs.mean(0)) doesn't seem to work for me. it might have something to do with the fact that I am using numpy arrays as an input to the explainers. Some plot functions don't work in that case. Is there a way to set  custom  base values for the TreeExplainer that match the ones used for the other explainers?
