### ISSUE TITLE
From Explanation.values format to explainer.shap_values() format

### ISSUE THREAD

**Issue by CarlaFernandez** [shap/shap#2622]
Hi, I have an Explanation object which has (amongst others) the `values`, `base_values` and `data` attributes. I'm working with a **multiclass** model, and I would like to convert the Explanation.values attribute to the output format obtained from:
```python
explainer = shap.Explainer(model)
explanation = explainer.shap_values(X_test)
```
The output shape for `Explanation.values` is a numpy array with shape `(n_samples, n_variables, n_classes)`, while the format for the code above is a list of `n_classes` numpy arrays of shape `(n_samples, n_variables)`.

If anyone interested, my final objective is to be able to plot a multiclass shap.summary_plot from an Explanation object generated from the code:
```python
explainer = shap.Explainer(model)
explanation = explainer(X_test)
```
so that the results are similar to this:
![image](https://user-images.githubusercontent.com/9136877/179493961-4ce13ea1-6f85-4544-b8b8-12ab9f718bfb.png)

**Comment by rflameiro** [comment]
Hi Carla, if I understood your problem correctly, you want to obtain the following summary_plot:
```
explanation_val = explainer.shap_values(X)
shap.summary_plot(explanation_val)
```

From an Explanation object. 
explanation_val is a list which, converted into a numpy array, yields a (3, 150, 4) array.
So I was able to do it this way, using the iris dataset:
```
X, y = shap.datasets.iris()
model = xgboost.XGBClassifier(use_label_encoder=False).fit(X, y)

# Create Explanation object "explanation"
explainer = shap.Explainer(model)
explanation = explainer(X)
print(explanation.values.shape)  # as you said, this is a (150, 4, 3) np.array

# Transpose explanation.values to (3, 150, 4), same as explanation_val
z = explanation.values.transpose(2,0,1)

# Convert z to a list and create plot
shap.summary_plot(list(z))
```

**Comment by CarlaFernandez** [comment]
This is amazing @rflameiro , sorry for the late response. Thank you!

**Comment by FromNigeria** [comment]
> Hi Carla, if I understood your problem correctly, you want to obtain the following summary_plot:
> 
> ```
> explanation_val = explainer.shap_values(X)
> shap.summary_plot(explanation_val)
> ```
> 
> From an Explanation object. explanation_val is a list which, converted into a numpy array, yields a (3, 150, 4) array. So I was able to do it this way, using the iris dataset:
> 
> ```
> X, y = shap.datasets.iris()
> model = xgboost.XGBClassifier(use_label_encoder=False).fit(X, y)
> 
> # Create Explanation object "explanation"
> explainer = shap.Explainer(model)
> explanation = explainer(X)
> print(explanation.values.shape)  # as you said, this is a (150, 4, 3) np.array
> 
> # Transpose explanation.values to (3, 150, 4), same as explanation_val
> z = explanation.values.transpose(2,0,1)
> 
> # Convert z to a list and create plot
> shap.summary_plot(list(z))
> ```

please can i ask you a question about LIME?
