### ISSUE TITLE
Waterfall plot does not work with RandomForestRegressor

### ISSUE THREAD

**Issue by oliviern-cye** [shap/shap#2623]
Hi,

The Waterfall plot example from git does not work with RandomForestRegressor and throws this error:

`Exception: waterfall_plot requires a scalar base_values of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.base_values[0], values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.base_values[0], values[0][0], X[0]).`

This is the snippet of code I tried to run:

```
import sklearn
import xgboost
import shap

# train a Random Forest model
X, y = shap.datasets.boston()
# model = xgboost.XGBRegressor().fit(X, y) # ORIGINAL EXAMPLE
model = sklearn.ensemble.RandomForestRegressor().fit(X, y) # RANDOM FOREST REGRESSOR

# explain the model's predictions using SHAP
# (same syntax works for LightGBM, CatBoost, scikit-learn, transformers, Spark, etc.)
explainer = shap.Explainer(model)
shap_values = explainer(X)

shap.waterfall_plot(shap_values[0])
```

shap==0.41.0

**Comment by tomaszek0** [comment]
As a result of the above code snippets I gave the exception (Win10, anaconda, shap 0.41.0):
"Exception: waterfall_plot requires a scalar base_values of the model output as the first parameter, but you have passed an array as the first parameter! Try shap.waterfall_plot(explainer.base_values[0], values[0], X[0]) or for multi-output models try shap.waterfall_plot(explainer.base_values[0], values[0][0], X[0])."

The following code gave the desired output (a waterfall plot) after restarting the kernel:
import xgboost
import shap
import sklearn
# train a Random Forest model
X, y = shap.datasets.boston()
model = sklearn.ensemble.RandomForestRegressor().fit(X, y) # RANDOM FOREST REGRESSOR
explainer = shap.Explainer(model, X)
shap_values = explainer(X)
shap.waterfall_plot(shap_values[0])

The following code also generates a waterfall plot:
shap.plots.waterfall(shap_values[0], max_display=12, show=True)

**Comment by nathantrantham** [comment]
@tomaszek0  - I am receiving the exact same error. I have nearly the same code as you, but am not importing xgboost because I am using the base sklearn RandomForrestClassifier(). Is importing xgboost really necessary?
