### ISSUE TITLE
I can not find the proper place to insert SHAP

### ISSUE THREAD

**Issue by T-nfd** [shap/shap#2627]
Hi all,

There is an available code on GitHub in [this link](https://github.com/grip-unina/noiseprint).
It uses a Conv model which is defined in this path: noiseprint/network.py
And then call the Conv model in this file: noiseprint/noiseprint.py

All proposed examples for using SHAP are really simple and I'm confused about how to use SHAP in a real project.
I want to use DeepExplainer or GradientExplainer to explain the above code, but I don't know where I should exactly insert SHAP codes.
And what changes are needed?

@slundberg

**Comment by T-nfd** [comment]
Anybody has an idea how to match the article code with SHAP?

**Comment by remo-help** [comment]
Hi @Nima-pw, this is really a question for the Discussion board or stackoverflow, and should not be in the Issues section.

Regarding your question:
A shap explainer will need access to the model's predict function, or the model itself. It will also need access to either the vectorized features, or an embedding function that does the vectorization. I'm not familiar enough with the model you posted to tell you how to do it here specifically. This will depend on the model's architecture.

I think the better course of action here would be to contact the authors of the model paper. They are familiar with the code and can tell you where you will find what you are looking for.
