### ISSUE TITLE
Error while pickling kernal explainer from a trained StackingClassifier

### ISSUE THREAD

**Issue by tkmamidi** [shap/shap#2631]
Hello,
I've trained a StackingClassifier for a model and wanted to save the kernal explainer as a pickle file. I'm using the below code snippet

```
clf = sklearn.ensemble.StackingClassifier(
        estimators=[
            ("DecisionTree", DecisionTreeClassifier(class_weight="balanced")),
            (
                "RandomForest",
                RandomForestClassifier(class_weight="balanced", n_jobs=-1),
            ),
        ],
        cv=2,
        stack_method="predict_proba",
        n_jobs=-1,
        passthrough=False,
        final_estimator=LogisticRegression(n_jobs=-1),
        verbose=1,
    )
clf.fit(X_train, Y_train)
background = shap.kmeans(X_train, 10)
explainer = shap.KernelExplainer(clf.predict_proba, background)
```

When I try to save the `explainer` as a pickle object instead of training the model every time, I get the following error

```
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
/var/folders/x5/1jk7xryd0rg4d710y586kmvh0000gp/T/ipykernel_5414/1607415220.py in <module>
      1 import pickle
      2 filehandler = open("../data/explainer.pkl", 'wb')
----> 3 pickle.dump(explainer, filehandler)

PicklingError: Can't pickle <function StackingClassifier.predict_proba at 0x1a8edb550>: it's not the same object as sklearn.ensemble._stacking.StackingClassifier.predict_proba
``` 

Any help is much appreciated!
Thank you!

**Comment by remo-help** [comment]
Can you share the part of your code where you actually pickle the object?

**Comment by tkmamidi** [comment]
I tried using both `joblib` and `pickle` and got the same kind of error. Here's an example when using pickle:
```
pickle.dump(explainer, filehandler)
```

**Comment by remo-help** [comment]
I tried reproducing your issue with a dummy `KernelExplainer`, but I cannot generate this error.

If this is all about not having to retrain the model, I suggest you pickle your model instead.
Try that route. I suspect that may also throw an error, because looking at your log, it seems like the problem is the model itself. Try pickling the model and see what happens.

**Comment by tkmamidi** [comment]
I am able to pickle the model but I want to bypass loading my model every time and calculating explainer. Instead, I would like to load the pickled explainer and calculate shap values directly for SHAP plots. Is this possible?

**Comment by remo-help** [comment]
for whatever reason your shap explainer does not like being pickled


What you can do is pickle your `Explanation` object, so you can run your explainer on the data you need explained and then pickle the resulting output. Then you can load that somewhere else and create plots etc.

Alternatively you pickle the model and re-initialize the explainer. Initializing the explainer is low-cost, what actually takes compute time is calculating the values, so really you should be pickling the `Explanation` object

**Comment by eshirima** [comment]
I have experienced a similar issue to this recently and have tried other methods to save the explainer object with no success. I found a workaround to this by saving the computed Shapley values to a pickle file (takes around 26 hours on my end to fit the explainer) along with the `expected_value` as shown below.

```
explainer = shap.KernelExplainer(model.predict_proba, data, link='logit', feature_names=feature_names_)
shap_values_ = explainer.shap_values(X)
with open('kernel_shap.pickle', 'wb') as shap_: pickle.dump(shap_values_, shap_)
with open('expected_value.pickle', 'wb') as exp: pickle.dump(explainer.expected_value, exp)
```

Thereafter you can read them back and instantiate an Explanation object to plot the global and local Shapley features

    with open('kernel_shap.pickle', 'rb') as reader, open('expected_value.pickle', 'rb') as reader1:
        shap_values, expected_ = pickle.load(reader), pickle.load(reader1)

    explanation = shap.Explanation(shap_values, expected_, data, feature_names=features)
This is a temporary fix on my end until I am able to properly save and reload the fitted explainer object.

**PS: Here are some of the methods I have tried w/out any success, maybe something will work for you.**

    try:
        with open('explainer.pickle', 'wb') as exp_: pickle.dump(explainer, exp_)
    except Exception as error: print('First\n', error)

    try:
        with open('explainer1.sav', 'wb') as kernel: explainer.save(kernel, model_saver='auto', masker_saver='auto')
    except Exception as error: print('Second\n', error)

    try:
        with open('explainer2.sav', 'wb') as kernel: explainer.save(kernel)
    except Exception as error: print('Third\n', error)

    try:
        with open('explainer3.sav', 'wb') as kernel: pickle.dump(explainer, kernel)
    except Exception as error: print('4th\n', error)

    try:
        joblib.dump(explainer, 'explainer4.bz2')
    except Exception as error: print('5th\n', error)

    try:
        joblib.dump(explainer, 'explainer5.bz2', compress=('bz2', 9))
    except Exception as error: print('6th\n', error)

**Comment by tkmamidi** [comment]
Thanks for the suggestion!

For my use case, I don't have a test dataset to pre-run and get the shap values. Unfortunately, that method isn't suitable for my use case. I'm sorry that it is taking 26hrs for you. Hopefully, we can find a better solution soon!!

Also, I tried the above mentioned methods to pickle the explainer object and none of them worked for me :'( 
```
First
 Can't pickle <function StackingClassifier.predict_proba at 0x1adbbf310>: it's not the same object as sklearn.ensemble._stacking.StackingClassifier.predict_proba
Second
 'Kernel' object has no attribute 'masker'
Third
 'Model' object has no attribute 'save'
4th
 Can't pickle <function StackingClassifier.predict_proba at 0x1adbbf310>: it's not the same object as sklearn.ensemble._stacking.StackingClassifier.predict_proba
5th
 Can't pickle <function StackingClassifier.predict_proba at 0x1adbbf310>: it's not the same object as sklearn.ensemble._stacking.StackingClassifier.predict_proba
6th
 Can't pickle <function StackingClassifier.predict_proba at 0x1adbbf310>: it's not the same object as sklearn.ensemble._stacking.StackingClassifier.predict_proba
```

**Comment by remo-help** [comment]
@tkmamidi have you tried pickling the `Explanation` object? The `Explainer` and `Explanation` are two different classes.

Pickling the explainer itself does not save you any time with the `KernelExplainer`, as it loads quickly. What you want to pickle is the `Explanation` which is the output of the explainer. Maybe there was some confusion because the Kernel explainer only generates shap values and not a whole Explanation object, so you have to manually generate one:

```
explainer = shap.KernelExplainer(clf.predict_proba, background)
shap_values_ = explainer.shap_values(X)
base = np.asarray([explainer.expected_value for i in range(0,shap_values.shape[0])])
explanation = shap.Explanation(values=shap_values, data=X, base_values=base, feature_names=list(your_feature_names))
pickle.dump(explanation, filehandler)
```
With an `Explanation` object, you have access to the full range of plots that shap provides. Try this method and let me know if that works for you.

**Comment by tkmamidi** [comment]
@remo-help Thank you for the suggestion but I have a slightly different use case and I cannot compute `shap_values_` well ahead of time. Here's what I'm currently doing:

```
explainer = shap.KernelExplainer(clf.predict_proba, background)
shap_values = explainer.shap_values(df.iloc[1, :])
shap.force_plot(explainer.expected_value[1], shap_values[1], df.iloc[1,:])
```

Here, I'm using a completely different dataset that I'm calculating shap values for individually and then generating the SHAP plot. That is why I'm trying to pickle the `explainer` object instead of shap values. 

I hope this clarifies my question a bit more?

Thanks!

**Comment by eshirima** [comment]
@tkmamidi I am confused as to what you're trying to achieve then. If you can't compute shap values ahead of time then why do you need to save the explainer object when all you did is instantiate it? If what you care about is reproducibility then set a seed on the constructor method then run `explainer.shap_values` on a later dataset.

**Comment by tkmamidi** [comment]
@eshirima I apologize for the confusion. 
To make a prediction and SHAP plot of novel/unseen data, I'm currently loading the model and training data and reinstantiate the explainer every time I want to call the app/method/script to generate a plot. I'm trying to save the explainer object to bypass loading model and training data every time I run the script. Hope this clarifies!

**Comment by eshirima** [comment]
Then consider adapting the following layout:

1. Train your stacking classifier
2. Save the fitted classifier as a pickle file (this will avoid re-training for each run)

On your script that handles XAI:

1. Load fitted model and training set
2. Instantiate explainer and compute shapley values
3. Follow either @remo-help or my suggestions on saving the explainer attributes

From here onwards:
If you want to explain your model using say the test dataset, then all you have to do is load the saved explainer attributes along with the test dataset and visualise the plots. No need to re-train the model or re-compute shapley values.

_PS: If your Kernel Explainer takes near real-time to evaluate, then you don't even need to save the explainer attributes and can directly just plot out the Shapley values_
