### ISSUE TITLE
Metrics for Interpretability

### ISSUE THREAD

**Issue by polavarapu1** [shap/shap#2637]
Hi Dr. Lundberg: By any chance, do we have any metrics for interpretability like "interpretation trueness" and "global stability" defined in this paper https://arxiv.org/abs/2011.09903? Thank you.

**Comment by HajarHkm** [comment]
Hello,
There s something called average local fidelity. It was used by Adhikari et al.  here [https://arxiv.org/pdf/1812.09044.pdf].
