### ISSUE TITLE
Shap values interpretation for classification models

### ISSUE THREAD

**Issue by Yazmaz98** [shap/shap#2651]
It is unclear to me what is the interpretation of Shap values in a summary_plot for a classification/multiclassification problem.
I know that for regression, the shap value corresponds exactly to how much the variable j for observation i has contributed to the predicted value, but what is the interpretation for a classification problem please? 
I first tried to parallelize the reasoning and thought that the shap value corresponds to the difference in probability of belonging to a class (the class we visualize the summary_plot for), but then I sometimes got values that are outside of [0, 1]. Any clarification/insight would be much welcome.
Thank you.

**Comment by rflameiro** [comment]
The shap value produced for classification problems is a continuous value that ranges from - infinity to + infinity and is called log-odds. It is related to the probability by this formula:

log-odds = ln(P/(1–P))

The probability is a value between 0 and 1, and can be converted to the classes according to the model threshold. Usually, P > 0.5 = class 1, P < 0.5 = class 0.

This link may be useful: https://towardsdatascience.com/hey-model-why-do-you-say-this-is-spam-7c945cc531f

**Comment by Yazmaz98** [comment]
Thank you for your much appreciated reply! Does this mean that for one observation, the sum of the shap values of all the variables is equal to ln(P/1-P) where P is the final prediction? 
And what about the case of multi classification please? Thank you.

**Comment by rflameiro** [comment]
> the sum of the shap values of all the variables is equal to ln(P/1-P) where P is the final prediction?

Yes, but P is not the prediction, it is a probability value. The prediction will depend on your model's threshold.

> And what about the case of multi classification

It is the same, but for each class you will have a different value of log-odds. Converting they to P, they will sum to 1.0
