### ISSUE TITLE
Picture truncated when saving waterfall plot

### ISSUE THREAD

**Issue by pierrelouisbescond** [shap/shap#2664]
I am posting the issue I have experienced as well as the solution I have found.

```
import matplotlib.pyplot as plt

fig = plt.figure()
shap.plots.waterfall(shap_values[index], show=False)
plt.savefig("test.png")
```

The corresponding display in the notebook is well adjusted:

![image](https://user-images.githubusercontent.com/65066394/187078476-6e20b9c4-e7ca-4398-97aa-1f2536f5deba.png)

Whereas on the plot saved, the labels are truncated:

![image](https://user-images.githubusercontent.com/65066394/187078836-f0729e17-54ce-4d5b-98fc-4247dcdf3830.png)

**Comment by pierrelouisbescond** [comment]
```
import matplotlib.pyplot as plt

fig = plt.figure()
shap.plots.waterfall(shap_values[index], show=False)
plt.gcf().set_size_inches(10, 6)
plt.tight_layout()
plt.savefig("test.png")
```

Will by-pass the default plt dimensions (8, 6.5):

![image](https://user-images.githubusercontent.com/65066394/187079035-9b2e38c8-e05f-47f4-86cb-c0ff723c32e1.png)

**Comment by BecayeSoft** [comment]
> ```
> import matplotlib.pyplot as plt
> 
> fig = plt.figure()
> shap.plots.waterfall(shap_values[index], show=False)
> plt.gcf().set_size_inches(10, 6)
> plt.tight_layout()
> plt.savefig("test.png")
> ```
> 
> Will by-pass the default plt dimensions (8, 6.5):
> 
> ![image](https://user-images.githubusercontent.com/65066394/187079035-9b2e38c8-e05f-47f4-86cb-c0ff723c32e1.png)

Very useful Pierre, thank you!
