### ISSUE TITLE
shap_values deprecation warning throws error

### ISSUE THREAD

**Issue by JulienManulife1** [shap/shap#2668]
I am trying to run a DART booster using '0.41.0' and in using shap_values() I get an error 

warnings.warn("shap_values() is deprecated; use __call__().", warnings.DeprecationWarning)

AttributeError: module 'warnings' has no attribute 'DeprecationWarning'
![Snag_1ac4d05](https://user-images.githubusercontent.com/105056217/188227808-46276a98-c67a-4183-b0d0-2ed3aed821fc.png)

**Comment by JulienManulife1** [comment]
Just to comment, I found a similar bug report here: https://github.com/pytest-dev/pluggy/issues/75
Seems as though DeprecationWarning is a built-in and not part of warnings

**Comment by aniketsnv-1997** [comment]
@slundberg any fix on this? Not sure whether there is any workaround for this

**Comment by fmorenopino** [comment]
Any fix for this? I'm facing the same problem

**Comment by juanluisrto** [comment]
I'm facing the problem too

**Comment by napashkov** [comment]
same 😿

**Comment by den1ceee** [comment]
same problem

**Comment by rodrigo-92** [comment]
hi, facing the same problem when trying to run 
explainer = shap.Explainer(lambda x: pipe.named_steps["mlp"].predict(x), sample.values)
%time shap_values = explainer.shap_values(sample.values)

pipe is a Pipeline that contains a sklearn MLPClassifier trained

**Comment by ajavadov** [comment]
One temporary solution (until it is truly fixed) would be deleting that line from _permutations.py file, I guess. 

sed -i '/warnings.warn("shap_values() is deprecated; use __call__().", warnings.DeprecationWarning)/d' _permutations.py

**Comment by LiutongZhou** [comment]
Simple Fix: `warnings.DeprecationWarning` -> `DeprecationWarning`
```
# /lib/python3.9/site-packages/shap/explainers/_permutation.py:214
warnings.warn("shap_values() is deprecated; use __call__().", DeprecationWarning)
```

**Comment by Gronkykong** [comment]
Also facing this issue

**Comment by Winnieliu0504** [comment]
also facing this issue

**Comment by CatherineHao** [comment]
also facing this issue

**Comment by ronalds99** [comment]
also facing this issue - did anyone figure this out?

**Comment by JulienManulife1** [comment]
It is a simple fix but support seems to not be there

**Comment by lukeasteer** [comment]
I'm still having this issue, despite using the most recent version of the package.
