### ISSUE TITLE
Typo in the docs?

### ISSUE THREAD

**Issue by Jakobhenningjensen** [shap/shap#2670]
In the [docs](https://shap-lrjball.readthedocs.io/en/latest/example_notebooks/general/Explainable%20AI%20with%20Shapley%20Values.html#A-more-complete-picture-using-partial-dependence-plots) it is stated that

>  The vertical gray line represents the average value of the AGE feature. Note that the blue partial dependence plot line (which the is average value of the model output when we fix the AGE feature to a given value) [...]

but the plot and the code shows the `RM` feature and not the `AGE` feature.

Am I missing something here or is it a typo?

**Comment by thatlittleboy** [comment]
This issue has already been fixed (changed Boston -> California dataset).
