### ISSUE TITLE
feature_names parameter in summary_plots

### ISSUE THREAD

**Issue by JeyKJey** [shap/shap#268]
I expected that when I would use 'feature_names' in summary_plots() I would restrict the plot only to the feature_names I specified. Is it incorrect expectation?

Example:
I expect a plot only for two features.
```
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn import datasets
iris = datasets.load_iris()
data = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns = iris['feature_names'] + ['target'])
y = data.target
X = data.drop('target', axis=1)  # we only take the first two features.
clf = lgb.LGBMClassifier()
clf.fit(X, y)

explainer = shap.TreeExplainer(clf)
shap_values = explainer.shap_values(X)
shap.summary_plot(shap_values, X, feature_names = ['sepal length (cm)', 'sepal width (cm)'])
```

throws following error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-43-97ff0bab767e> in <module>()
     10 explainer = shap.TreeExplainer(clf)
     11 shap_values = explainer.shap_values(X)
---> 12 shap.summary_plot(shap_values, X, feature_names = ['sepal length (cm)', 'sepal width (cm)'])

~/anaconda3/lib/python3.6/site-packages/shap/plots/summary.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot, layered_violin_max_num_bins, class_names)
    355             left_pos += global_shap_values[feature_inds]
    356         pl.yticks(y_pos, fontsize=13)
--> 357         pl.gca().set_yticklabels([feature_names[i] for i in feature_inds])
    358         pl.legend(frameon=False, fontsize=12)
    359 

~/anaconda3/lib/python3.6/site-packages/shap/plots/summary.py in <listcomp>(.0)
    355             left_pos += global_shap_values[feature_inds]
    356         pl.yticks(y_pos, fontsize=13)
--> 357         pl.gca().set_yticklabels([feature_names[i] for i in feature_inds])
    358         pl.legend(frameon=False, fontsize=12)
    359 

IndexError: list index out of range
```

**Comment by slundberg** [comment]
The `feature_names` option is just a way to pass the names of the features for plotting. It is used for example if you want to override the column names of a panda data frame, or you are just passing a numpy array for your data. To only plot a subset of features you would need to only pass those columns from the `shap_values` and `X` arrays.

**Comment by canglangshushu** [comment]
Hi @slundberg 
my  len(feature_names)=47,and my X.shape=(n,47),
Only 20 feature names are displayed when I execute "shap.summary_plot(shap_values, X, feature_names = X.columns.tolist())"I wonder if there is any display limit for  len(feature_names)?

**Comment by slundberg** [comment]
@canglangshushu Just set the keyword argument `max_display=100` for example.

**Comment by canglangshushu** [comment]
@slundberg I see. Thank you for your quick reply

**Comment by MonkeyDNoppu** [comment]
I tried `max_display=100` and also `sort=False` but it's not work ...

**Comment by markusloecher** [comment]
Is there a way to suppress the feature names altogether? The reason I ask is that I want to create a side-by-side plot of global importance (type=barplot) and the beeswarm plot. Both of these plots show the same labels on the y axis, so I want to remove the redundancy
Thx

**Comment by chungkhy** [comment]
Hello! Is it possible to select the order of the features shown in a waterfall plot? Also, is it possible to "bundle"/add specfic features together? For example, in the [Explaining an additive regression model tutorial](https://shap.readthedocs.io/en/latest/example_notebooks/overviews/An%20introduction%20to%20explainable%20AI%20with%20Shapley%20values.html#Explaining-an-additive-regression-model), can we show AveOccup and Population before MedInc (see figure below)? Also, could we add Latitude and Longitude together to show as one combined feature? Thanks!

<img width="539" alt="waterfall_example" src="https://github.com/user-attachments/assets/7b1f9f09-91f8-4326-9d72-c74b3cf6eb9c">
