### ISSUE TITLE
Getting 3D shap_values for an autoencoder model using Kernel Explainer

### ISSUE THREAD

**Issue by SupriyaAsutkarIITB** [shap/shap#2685]
@slundberg 
Hello, 
I am using an autoencoder-based unsupervised model for anomaly detection. Input is the 2D vector comprising 22 features at different time stamps (Input shape: for e.g (100, 22)). The autoencoder model summary is attached below.
![autoencoder_model summary](https://user-images.githubusercontent.com/113603198/190398527-fc9b58ff-087d-477b-8085-3817fb5c0303.png). In the model, the input shape is reshaped before passing it through the convolution layer. The output of the model thus is (100, 22, 1) if an input vector of (100, 22) is given. 

My question is: When I am using Kernel explainer to interpret this autoencoder model, I am getting shap_values shape as (22, 100, 22) for an input of (100, 22)... which I am not understanding.
I mean if I provide 100-row data of 22 features, shouldn't I expect the generated shap values to be of the size (100, 22) instead of (22, 100, 22)? Why are the shape values in 3D?

**Comment by makovez** [comment]
Hi, did you find any solution?
