### ISSUE TITLE
summary plot not working with matplotlib v3.6.0

### ISSUE THREAD

**Issue by lssatvik** [shap/shap#2687]
shap v0.41.0 is throwing an error when used in conjunction with matplotlib v3.6.0. It works with versions v3.5.3 and below.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/3456652/190871179-0d00bda9-ad48-4436-ac47-483ea142fefb.png">
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/3456652/190871128-a7a07e12-50ff-47fb-95a3-64bd0e5a7065.png">

Am not sure how to resolve the issue other than fixing the older version.

**Comment by hrzn** [comment]
I'm observing the same issue with matplotlib 3.6.0. Things work fine with matplotlib 3.5.3.

**Comment by GioshTandoi** [comment]
I am having exactly the same issue!

**Comment by tkernr** [comment]
Here is a workaround using the plotly express method `strip`. The dataframe `df_shap` includes the attribute columns and columns containing the shap values for those attributes. The list `important_features` contains the features/attributes ordered from most important to least important.
```
def summary_plot(df_shap):
    list_ = list()
    for col in important_features:
        df_temp = df_shap.copy()
        if df_temp[col].dtypes in ['int', 'float']:
            df_temp['feature_value_quantile_bin'] = pd.qcut(df_temp[col], q=[0, .2, .4, .6, .8, 1], labels=False)
        else:
            df_temp['feature_value_quantile_bin'] = -1
        df_temp['attribute'] = col
        df_temp['shap_value'] = df_temp[f'shap_value_{col}']
        list_.append(df_temp[['attribute', 'shap_value', 'feature_value_quantile_bin']])
    
    df_ = pd.concat(list_, axis=0)
    df_ = df_.sort_values(['feature_value_quantile_bin'], ascending=False)
    
    fig = px.strip(df_, x='attribute', y='shap_value', color='feature_value_quantile_bin', 
                   category_orders={'attribute': important_features}, 
                   title=f"Summary plot for metric {metric_of_interest}", width=1000, height=600)
    fig.show()
```
