### ISSUE TITLE
SHAP plots with Explainer function

### ISSUE THREAD

**Issue by sucheta1794** [shap/shap#2691]
Hi,

I was trying to plot dependence and force plot with SHAP.Explainer() but it fails.I am attaching the code snippet for assistance.
Please guide me how to implement this in my model,

**Code:**
explainer = shap.Explainer(reg.predict,X)
shap_values = explainer.shap_values(X)
shap.initjs()
shap.dependence_plot("Age", shap_values , X)
shap.force_plot(explainer.expected_value, shap_values[0, :], X.iloc[0, :], matplotlib=True)

**Error pops up:**
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Thanks in advance,
Sucheta

**Comment by TomPham97** [comment]
Have you tried passing just the model itself instead of the function to predict?
```python
explainer = shap.Explainer(reg)
shap_values = explainer(X)
```
