### ISSUE TITLE
Issue with DeepExplainer when forward requires grad

### ISSUE THREAD

**Issue by fmorenopino** [shap/shap#2693]
Hello, 

I'm trying to use shap.DeepExplainer with a custom network whose forward function, at some point, requires to do "torch.autograd.grad(...)". 

Doing a forward of the network with some input X correctly returns the prediction ("net(X)") but, if I run "shap.DeepExplainer(net, X)", then I obtain a "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn".

Any suggestion about how should I proceed?

Thanks.

**Comment by bardhprenkaj** [comment]
Did you solve this issue? How?
