### ISSUE TITLE
Visualization libraries should be in a try catch

### ISSUE THREAD

**Issue by jack1728** [shap/shap#270]
Trying to use Shap, I don't want to use the visualizations, only the numerical results.  

If I never use the visualizations and matplot lib, I currently have to install the libraries even if I don't want them.    In particular matplot lib is asking for access to my root font directory, which I don't want to give it access to.

It would be great if it could pass through during import and only fail if I try to use the plot libraries.

_init_.py
try:
    from .plots.summary import summary_plot
    from .plots.dependence import dependence_plot
    from .plots.force import force_plot, initjs
    from .plots.image import image_plot
except ImportError:
    pass

**Comment by slundberg** [comment]
I tried to wrap matplotlib in try catch's when it was imported but I think a couple imports have since been added that are not wrapped. I like your idea of just wrapping all the plotting imports since that is simpler (and the need for JS plots without matplotlib plots seems unlikely).

**Comment by jack1728** [comment]
One other suggestion:
In setup.py 
install_requires=['numpy', 'scipy', 'scikit-learn', '**matplotlib**', 'pandas', 'tqdm', 'ipython'],

matplotlib is not strickly required, since you have all these try/catch statements around importing.

It might be a good idea to remove matplotlib from the install_requires list, so that people who are trying to use this library without the plotting and visualization functions don't need to install matplotlib

**Comment by gsbowlin** [comment]
In particular if you are just writing a CLI to make explanations for a particular model, having visualization dependancies all get installed is a lot of package bloat

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by slundberg** [comment]
I agree it would be nice to have an install without the viz libraries. However, I would like it by default to install the viz libraries and just have an option to not install them. This is the reverse of the "extras" in setuptools so I need to think about how to do that.

**Comment by slundberg** [comment]
Solved now, see #466
