### ISSUE TITLE
Unable to reproduce Textual Entailment Plot

### ISSUE THREAD

**Issue by sapchan** [shap/shap#2701]
Hi All,

I'm trying to recreate the input/output heatmap below, but I'm unable to reproduce it.
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/5719529/191823616-838a2ffa-b5af-45f1-8089-dbf94396d309.png">

 I ran all of the same cells in example provided: https://github.com/slundberg/shap/blob/master/notebooks/text_examples/text_entailment/Textual%20Entailment%20Explanation%20Demo.ipynb

The output that gets produced is the following:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/5719529/191823921-f657b187-35f5-44bb-84bc-fb55ed3209ed.png">

Thanks!

**Comment by NTDXYG** [comment]
How to solve this? Thanks!

**Comment by NTDXYG** [comment]
I have solved it!

```
from IPython.core.display import display as ipython_display, HTML

explainer = shap.Explainer(model,tokenizer)
shap_values = explainer(s)

ipython_display(HTML(shap.plots._text.saliency_plot(shap_values[0])))
```
