### ISSUE TITLE
how to save plot?

### ISSUE THREAD

**Issue by Turningl** [shap/shap#2718]
shap.partial_dependence_plot('TPSA', model=model.predict, data=dataset, ice=False, model_expected_value=False,feature_expected_value=False, ylabel='Avg EQE')
plt.tight_layout()
plt.savefig('TPSA_avg_EQE.svg', dpi=1080)

Hello I want to save the vector image, but the saved image is blank, why?

**Comment by Momentum-TN** [comment]
@Turningl I don't know if you still looking for a solution. you can use the following method:
with setting `show` parameter to `False`, you can do all your matplotlib operations before `plt.show()`

from the [docs](https://shap.readthedocs.io/en/latest/generated/shap.plots.image.html#shap.plots.image) :

> show: bool
>
>   Whether matplotlib.pyplot.show() is called before returning. Setting this to False allows the plot to be customized further after it has been created.

example: 
```py
shap.partial_dependence_plot('TPSA', model=model.predict, data=dataset, ice=False, model_expected_value=False,feature_expected_value=False, ylabel='Avg EQE')
# do all your matplotlib operations here before saving
plt.tight_layout()

# save your plot
plt.savefig('TPSA_avg_EQE.svg', dpi=1080)
# display your plot
plt.show()
```
I hope this is useful for you

**Comment by thatlittleboy** [comment]
Closing as the question has been answered.
