### ISSUE TITLE
beeswamplot value error

### ISSUE THREAD

**Issue by mengysun** [shap/shap#2721]
I attempt to plot the beeswarm plot with the following code:

shap_values = explainer(X_train)

shap.plots.bar(shap_values)

shap.plots.beeswarm(shap_values)

The barplot is fine. However, I come across the following error again and again:

"ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes."

And I can't quite understand how to fix this. I try the summary plot, same error message.

**Comment by lbertelo01** [comment]
I am getting the same error when plotting a summary plot even though I have been able to plot it without errors before. 
Have you been able to fix this yet?

**Comment by lwq-star** [comment]
I also encountered this problem in windows. I write code in Spyder to draw feature maps using Shap

**Comment by vbzvibin** [comment]
Just downgrade shap :)
! pip install shap==0.38.1 
or
! pip install shap==0.30.1

**Comment by lwq-star** [comment]
> 只是降级 :) ！pip install shap==0.38.1 或 ! pip install shap==0.30.1

I solved the problem successfully through this

**Comment by squangelo** [comment]
see PR #2697 for a fix 🤞🤞🤞

**Comment by lwq-star** [comment]
When I use shap 0.41.0 and matplotlib 3.6.0, it still has errors

ValueError: Unable to determine Axes to steal space for Colorbar. Either provide the *cax* argument to use as the Axes for the Colorbar, provide the *ax* argument to steal space from it, or add *mappable* to an Axes.

> 请参阅 PR #2697进行修复🤞🤞🤞

**Comment by squangelo** [comment]
@lwq-star  downgrading matplotlib works for me `pip install matplotlib==3.5.3`

**Comment by lwq-star** [comment]
>

you are right

> @lwq-star 降级 matplotlib 对我有用`pip install matplotlib==3.5.3`

**Comment by azinasg** [comment]
Downgrading to `shap==0.38.1` solved the issue for me!

**Comment by axnsantana** [comment]
As the error message said, we now need to pass the axis information.

https://github.com/slundberg/shap/blob/45b85c1837283fdaeed7440ec6365a886af4a333/shap/plots/_beeswarm.py#L859-L873

I resolved it on my Shap version by editing line 865 above:
`cb = pl.colorbar(m, ticks=[0, 1], aspect=80, ax=pl.gca())`

and it worked with python==3.10.6, matplotlib==3.6.0, and shap==0.41.0
There is already a PR for that problem: #2697

**Comment by mengysun** [comment]
Downgrade did not fix the issue for me. I still wonder what's going on.

**Comment by mengysun** [comment]
Downgrade matplotlib also does not work.

**Comment by liangagi** [comment]
@mengysun Try to upgrade matplotlib==3.6.2, below setting works for shap.summary_plot() for the bug reported
python==3.9.6, matplotlib==3.6.2, and shap==0.41.0

**Comment by tornshaw** [comment]
> @mengysun Try to upgrade matplotlib==3.6.2, below setting works for shap.summary_plot() for the bug reported python==3.9.6, matplotlib==3.6.2, and shap==0.41.0

Upgrading matplotlib just solves my problem.

**Comment by FandosA** [comment]
> As the error message said, we now need to pass the axis information.
> 
> https://github.com/slundberg/shap/blob/45b85c1837283fdaeed7440ec6365a886af4a333/shap/plots/_beeswarm.py#L859-L873
> 
> I resolved it on my Shap version by editing line 865 above: `cb = pl.colorbar(m, ticks=[0, 1], aspect=80, ax=pl.gca())`
> 
> and it worked with python==3.10.6, matplotlib==3.6.0, and shap==0.41.0 There is already a PR for that problem: #2697

This solved the problem for me,  thank you!

**Comment by dsgibbons** [comment]
Closed by #2943
