### ISSUE TITLE
waterfall plot shows wrong text(missing base value sign)

### ISSUE THREAD

**Issue by paper-cat** [shap/shap#2724]
When I use waterfall with huge base value, waterfall plot shows base value instead of f(x) or E[f(x)]

the base value is 287439900 in this case

check out image below

![Cap 2022-10-12 17-55-50-670](https://user-images.githubusercontent.com/60381519/195298265-9a369e00-72d6-4849-8e40-31c0d89e52b8.jpg)

**Comment by thatlittleboy** [comment]
Already fixed, and should be made available in the upcoming release (v0.42.0)
