### ISSUE TITLE
Feature importance interpretation

### ISSUE THREAD

**Issue by noklam** [shap/shap#274]
As far as I understand the SHAP value is a linear model, so the scale of the "SHAP value" itself should have a linear relation? It is right to say the difference between 3 and 2 is the same as 4 and 3 for SHAP values?

If the above statement is kind of true, do you think it is sensible if I tried to normalize the SHAP value in a percentage sense? 

![image](https://user-images.githubusercontent.com/18221871/46257061-5016e500-c4e6-11e8-9dcd-e8b1890a11a3.png)

```
# sum over each feature
fi_shap = abs(shap_values).sum(0)

# Normalize
fi_shap = fi_shap/fi_shap.sum() ; 
fi_shap.sum(),fi_shap.shape
```

**Comment by slundberg** [comment]
The short answer is yes. That results in values that represent the fraction of the model output variability attributable to each feature across the whole dataset.

**Comment by noklam** [comment]
got it, thanks.

**Comment by psathish-k** [comment]
@slundberg Hey! I've a similar query on interpretation but not for the whole dataset. What if I want to represent the SHAP values of a query point in terms of percentages so as to know which feature contributed more towards the model's prediction.
For example, given a query point, let the SHAP values for features(F) be (F1, F2, F3, F4, F5) = (-0.23, 0.11, 0.25, 0.23, 0.15). If I take the absolute value then it means treating -0.23 and 0.23 as same whereas intuitively they mean different. What would be the best work around in this case?
One approach I thought was to scale the SHAP values to lie between 0 and 1 (MinMaxScaling) and then represent as percentage. Please let me know if this will work. Thanks in advance.
