### ISSUE TITLE
NameError: name 'shap_values' is not defined. Did you mean: 'shap_value'?

### ISSUE THREAD

**Issue by arilwan** [shap/shap#2754]
How to reproduce:
```
explainer = shap.TreeExplainer(model)  # model is random forest model
shap_values = explainer.shap_values(Xtest)
shap.summary_plot(shap_values, Xtest)

# error
NameError: name 'shap_values' is not defined. Did you mean: 'shap_value'?
```

**Comment by thatlittleboy** [comment]
The code sample provided is not a reproducible example. Please provide a minimal working example that we can use to reproduce the problem on our own machines

**Comment by thatlittleboy** [comment]
Most likely a user error, please come back with a reproducible example and we can reopen the issue.
