### ISSUE TITLE
preserve indices and group by

### ISSUE THREAD

**Issue by nshahpazov** [shap/shap#2756]
I have a dataframe with index columns which I pass to the explain function, but when I get the results I loose the index information which I need for grouping and aggregating the shap values.

```python
indexed_features = features.set_index(['col1', 'col2'])
explain = shap.TreeExplainer(model.predictor, indexed_features)
explanation = explain(indexed_features)
```

The result I have is an explanation object with .data, .base_values, .values as np ndarrays. I still want to have information on the indices on those results, so that I can group or filter by them.
Is there a way this thing can happen?

**Comment by thatlittleboy** [comment]
@nshahpazov You still have access to your original `indexed_features` dataframe. You should be able to just build off of that,

```python
indexed_features.assign(
    shap_values=explanation.values,
)
```

and so on. Closing for now, feel free to re-open if you would like to follow up.
