### ISSUE TITLE
Heatmap colorbar is displayed wrong

### ISSUE THREAD

**Issue by leoyala** [shap/shap#2757]
Hi,

I tried to plot the heatmap of the SHAP values of all the samples in my data and noticed that the colorbar is not displaying properly. I have already tried to adjust the aspect ratio of the axis but that did not get me anywhere good.  I am using shap 0.41.0. It would be great if the colorbar could be made more visible, similar to the other plots. I also put here an example of how the colorbar looks like for other types of plots.

Heatmap plot:
![image](https://user-images.githubusercontent.com/23067352/201147339-ec2e52bf-36cc-4b9b-ab38-b4f758df097c.png)

Beeswarm plot:
![image](https://user-images.githubusercontent.com/23067352/201147901-f2ba202a-f44c-415d-b0b5-8ad9dc8f0921.png)

**Comment by dsgibbons** [comment]
I believe this has been fixed by #2942. Can you please try again with a pip install from the git repo?

**Comment by leoyala** [comment]
Unfortunately, I am not using this tool anymore.

**Comment by dsgibbons** [comment]
I believe this has been fixed by #2942 so I'll close this issue for now.
