### ISSUE TITLE
 warnings.warn("shap_values() is deprecated; use __call__().", warnings.DeprecationWarning)

### ISSUE THREAD

**Issue by priyankaiiit14** [shap/shap#2771]
While running explainer on my dataframe getting the below error.
explainer = shap.Explainer(model_predict, score_df)
shap_values = explainer.shap_values(score_df)

---> 36 shap_values = explainer.shap_values(score_df)
     
      

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/shap/explainers/_permutation.py in shap_values(self, X, npermutations, main_effects, error_bounds, batch_evals, silent)
    212             of such matrices, one for each output.
    213         """
--> 214         warnings.warn("shap_values() is deprecated; use __call__().", warnings.DeprecationWarning)
    215 
    216         explanation = self(X, max_evals=npermutations * X.shape[1], main_effects=main_effects)

AttributeError: module 'warnings' has no attribute 'DeprecationWarning'

**Comment by JulienManulife1** [comment]
see https://github.com/slundberg/shap/issues/2668
