### ISSUE TITLE
NameError: name 'model' is not defined

### ISSUE THREAD

**Issue by AshishDave123** [shap/shap#2773]
Please help anyone below is the issue?
============

def predict_review(text): #1. predict_review
  encoded_text = encoder.encode(text)
  encoded_text = tf.cast(encoded_text, tf.float32)
  prediction = model.predict(tf.expand_dims(encoded_text, 1))
  return prediction

review = ('Good movie') #1. predict_review 
pred = predict_review(review)
pred, pred.shape

Error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-31-3372c87beab7>](https://localhost:8080/#) in <module>
      1 review = ('Good movie') #1. predict_review
----> 2 pred = predict_review(review)
      3 pred, pred.shape

[<ipython-input-30-e5d0fd40fd0b>](https://localhost:8080/#) in predict_review(text)
      2   encoded_text = encoder.encode(text)
      3   encoded_text = tf.cast(encoded_text, tf.float32)
----> 4   prediction = model.predict(tf.expand_dims(encoded_text, 1))
      5   return prediction

NameError: name 'model' is not defined

**Comment by dsgibbons** [comment]
This is not a shap issue. You are attempting to call a variable named model that hasn't been defined.
