### ISSUE TITLE
Additivity check failed in TreeExplainer

### ISSUE THREAD

**Issue by surbhi-gupta-drishya** [shap/shap#2777]
Issue: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option. This check failed because for one of the samples the sum of the SHAP values was 5834.316962, while the model output was 4856.371386. If this difference is acceptable you can set check_additivity=False to disable this check.

The data matrix passed to the model is of right shape, as model.predict is working fine. still, getting this issue.
![image](https://user-images.githubusercontent.com/87317600/203568583-87c62d33-066a-4c3e-8bab-a2111c22afc8.png)

**Comment by ramirejs** [comment]
@surbhi-gupta-drishya Did you get this issue resolved? I am experiencing the same error and I am still puzzled, I have not found a solution. If you have any insight, please share it here. Thanks!

**Comment by surbhi-gupta-drishya** [comment]
@ramirejs Yes, issue solved. Try below code:

![image](https://user-images.githubusercontent.com/87317600/205614843-796f0e62-cd45-4c8d-bb0f-9af18b70a1cf.png)
or 
![image](https://user-images.githubusercontent.com/87317600/205615150-49cbe0a2-1bf8-4b59-84d2-94ed13681c48.png)

**Comment by leoncena** [comment]
I had the same issue. Is this workaround in fact safe to use?

**Comment by lizajivnani** [comment]
hello,

I faced the same issue. 
Here is what worked for me:

Understanding why does it happens: 
Since, SHAP values indicate the contribution of each feature in the overall prediction, check_additivity ensures that these values add up to the model's prediction. However, there can be minor differences. For example, I was dealing with statistical feats extracted from physiological signals which means the precision was quite high. 

Rounding/disabling the additivity check:
I rounded my samples to the order of 1e^-7 and that worked for most samples.
You can further decrease the precision if the issue persists or disable the additivity check by check_additivity = False

**Comment by renrihui8415** [comment]
@lizajivnani, your comment solved my problem using SHAP. Thanks. 
By the way, if I don't wish to disable check_additivity, I need to round my sample into the precision of 6. I think it depends on the data quantity and precisions of the original data.

**Comment by palomnyk** [comment]
@lizajivnani or @renrihui8415, Can you provide a code sample to how you rounded? I disabled check_additivity and I've still getting the exception, so I would appreciate seeing your work around.

**Comment by renrihui8415** [comment]
import shap

# Get the preprocessed data and round it
data_transform = best_pipeline.named_steps['preprocessing'].transform(data)
data_transform = np.round(data_transform, decimals=4)  # Control the number of decimal places to 4, for example

# Initialize SHAP explainer
explainer = shap.TreeExplainer(
    model,
    data_transform,
    feature_names=best_pipeline.named_steps['preprocessing'].get_feature_names_out(),
)

**Comment by renrihui8415** [comment]
@palomnyk 
Hope it helps.

```
import shap

# Get the preprocessed data and round it
data_transform = best_pipeline.named_steps['preprocessing'].transform(data)
data_transform = np.round(data_transform, decimals=4)  # Control the number of decimal places to 4, for example

# Initialize SHAP explainer
explainer = shap.TreeExplainer(
    model,
    data_transform,
    feature_names=best_pipeline.named_steps['preprocessing'].get_feature_names_out(),
)

```
