### ISSUE TITLE
SHAP -Additivity check fails only in TreeExplainer

### ISSUE THREAD

**Issue by sotgot** [shap/shap#2778]
I have a problem with implementing SHAP.
When I try random forest and TreeExplainer for SHAP in a specific dataset, I always get the same error:  Additivity check failed in TreeExplainer!

I looked some discussion through and found it seems related to rounding error or the version difference, so I try `round()` for the data frame and update of SHAP, but they didn't work. Also, using fewer data for SHAP value which comes from [https://github.com/slundberg/shap/issues/941](url) seems to work at first, but it leads to getting vectors for instances, and failures in getting waterfall, feature importance, and so on.

But I can use logistic regression and LinearExplainer for shap with the same dataset(why it happens?).

Could you give some comments about this problem?

I use bankruptcy prediction data set from kaggle: 
https://www.kaggle.com/datasets/fedesoriano/company-bankruptcy-prediction
and I use 20% undersampling

```
code: 
explainer = shap.TreeExplainer(
    model=rf,  
    data=X_test, 
    feature_perturbation="interventional",  
    masker=X_test
)

shap_values = explainer(X_test) 
shap_values[0]
```

the error:
ExplainerError: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. This check failed because for one of the samples the sum of the SHAP values was 0.929200, while the model output was 0.950000. If this difference is acceptable you can set check_additivity=False to disable this check.

**Comment by ramirejs** [comment]
@sotgot  I am also experiencing the same error, any resolution on your case? I see this issue is still open.

**Comment by sotgot** [comment]
@ramirejs 
I guess SHAP doesn't work in the random forest for classification though I can check it works for prediction even if you use the random forest.
The Additivity Error may come from that.
Thus, I compromise with feature importance
