### ISSUE TITLE
Remove matplotlib from install requirements in setup.py

### ISSUE THREAD

**Issue by jack1728** [shap/shap#278]
In setup.py
install_requires=['numpy', 'scipy', 'scikit-learn', 'matplotlib', 'pandas', 'tqdm', 'ipython'],

matplotlib is not strictly required, since you have all these try/catch statements around importing.

It might be a good idea to remove matplotlib from the install_requires list, so that people who are trying to use this library without the plotting and visualization functions don't need to install matplotlib

**Comment by slundberg** [comment]
Just a note, for others interested, follow the discussion in #270

**Comment by slundberg** [comment]
Solved now, see #466
