### ISSUE TITLE
Visualization omitted, Javascript library not loaded! in Google Colab

### ISSUE THREAD

**Issue by Nithanaroy** [shap/shap#279]
Code used,
```python
background = X_train
explainer = shap.DeepExplainer(yx_model, background)

data_for_prediction = X_test[1:2]
print( "Data for prediction: {}".format(data_for_prediction) )

shap_values = explainer.shap_values(data_for_prediction)
shap.force_plot(explainer.expected_value[0], shap_values[0], data_for_prediction)
```
Get this result,
```
Visualization omitted, Javascript library not loaded!
Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security. If you are using JupyterLab this error is because a JupyterLab extension has not yet been written.
```
How to solve?

**Comment by Nithanaroy** [comment]
Looks like Google Colab needs `shap.initjs()` in every cell where there is a visualization.

**Comment by slundberg** [comment]
Thanks for the heads up!

**Comment by shivam1702** [comment]
Does it work with using `shap.initjs()` in every cell in Google Colab?

**Comment by ShaunakSen** [comment]
> Does it work with using `shap.initjs()` in every cell in Google Colab?
Yes, it does work

**Comment by chetanbulla** [comment]
Error in Colab : Visualization omitted, Javascript library not loaded! Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security. If you are using JupyterLab this error is because a JupyterLab extension has not yet been written.

**Comment by ademarslan** [comment]
@slundberg @shivam1702 I got error 'Visualization omitted, Javascript library not loaded!' then I run shap.initjs() but still it did not work. Is there any code to run for databricks notebook to visualise the force_plot?

**Comment by cheikhb** [comment]
Yes it runs when you use shap.initjs() in the same cell as the visualization function it will run.
Like this for example:


shap.initjs(),
shap.force_plot(base_value=explainer_shap.expected_value,
              shap_values=shap_values[10,:],
              features=X_train.iloc[10,:])

**Comment by thedatadecoder** [comment]
> @slundberg @shivam1702 I got error 'Visualization omitted, Javascript library not loaded!' then I run shap.initjs() but still it did not work. Is there any code to run for databricks notebook to visualise the force_plot?

Facing the same problem with databricks notebook. Running shap.initjs() in the same/every cell doesn't solve the problem.

**Comment by thedatadecoder** [comment]
I got a solution for Databricks. You just need to get the HTML out of force_plot and use displayHTML to see the force_plot.
Try this:

force_plot = shap.force_plot(xgb_explainer.expected_value, xgb_shap_values, X_test, matplotlib=False)
shap_html = f"<head>{shap.getjs()}</head><body>{force_plot.html()}</body>"
displayHTML(shap_html)

more info: https://towardsdatascience.com/tutorial-on-displaying-shap-force-plots-in-python-html-4883aeb0ee7c

**Comment by abai05** [comment]
You need to import and provide matplotlib in the function call. Example:

import matplotlib
shap.force_plot(explainer.expected_value, shap_values[0, :], X_display.iloc[0, :], matplotlib=matplotlib)

**Comment by AyeshaSana08** [comment]
@abai05 it worked for me. Thank you so much!

**Comment by DLOVRIC2** [comment]
@abai05  legend! thanks
