### ISSUE TITLE
model is not defibed 

### ISSUE THREAD

**Issue by ERsam111** [shap/shap#2794]
NameError                                 Traceback (most recent call last)
<ipython-input-77-489eebefac0c> in <module>
     33 output = tf.keras.layers.Dot(axes=1)([vu, vm])
     34 # specify the inputs and output of the model
---> 35 model = Model([input_user, input_item], output)
     36 
     37 model.summary()

NameError: name 'Model' is not defined

**Comment by dsgibbons** [comment]
This is not a `shap` issue. Your variable is undefined.

**Comment by 57sagar57** [comment]
The error you faced could possibly be due to the import changes between tf
for me this code worked 
 from tensorflow.keras.models import Model
