### ISSUE TITLE
TypeError: predict() got an unexpected keyword argument 'pred_contribs'

### ISSUE THREAD

**Issue by oxsem** [shap/shap#28]
Hi everyone,

I'm using xgboost 0.6 (on Anaconda, python 2.7). When trying to run sample of code from the documentation (with boston dataset) I get an error -  **TypeError: predict() got an unexpected keyword argument 'pred_contribs'**
Could you advise please? 

Thank you!

**Comment by slundberg** [comment]
The SHAP value implementation in XGBoost is very recent, so the 0.6 release does not have them. You will need 0.7, or even better the latest master of XGBoost.

**Comment by ricoms** [comment]
I have the same error and this error happens when running the first and main example available at the README, the one below:

```
import xgboost
import shap

# load JS visualization code to notebook
shap.initjs()

# train XGBoost model
a,b = shap.datasets.boston()
model = xgboost.train({"learning_rate": 0.01}, xgboost.DMatrix(a, label=b), 100)

# explain the model's predictions using SHAP values
# (same syntax works for LightGBM, CatBoost, and scikit-learn models)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(a)

# visualize the first prediction's explanation (use matplotlib=True to avoid Javascript)
shap.force_plot(explainer.expected_value, shap_values[0,:], a.iloc[0,:])
```

My suggestion is to modify the example at the documentation.
I'm trying to solve the problem and if I get a solution I'll prepare a PR.

**Comment by slundberg** [comment]
For others who land here @ricoms mentioned that there may also be some issues with some versions of XGBoost 0.7. If you run into these try updated XGBoost to 0.8 :)
