### ISSUE TITLE
Front Page DeepExplainer MNIST Example is broken

### ISSUE THREAD

**Issue by ZviBaratz** [shap/shap#2819]
Hi maintainers,

Just wanted to report the "[Front Page DeepExplainer MNIST Example](https://shap.readthedocs.io/en/latest/example_notebooks/image_examples/image_classification/Front%20Page%20DeepExplainer%20MNIST%20Example.html)" is broken and showing the following exception:
![image](https://user-images.githubusercontent.com/22370149/210233700-27a1a401-1569-411c-9454-bb970c095c19.png)

Thank you very much for your awesome work on this project!
Zvi

**Comment by ribatsua** [comment]
I also encountered the Similar question when using TF1.x version, but this example works after changing the tensorflow version to 2.3.0.
![image](https://user-images.githubusercontent.com/97381556/210791503-16db3ca1-2b32-45a7-9b74-bb9e3e7d0041.png)
I wonder if you ran the first example successfully（Compute importance scores）.I tried different versions and still get errors
![image](https://user-images.githubusercontent.com/97381556/210792223-d9ff0d81-e78b-44ee-8701-880d3b434e77.png)
