### ISSUE TITLE
Displaying two beeswarm plots side by side in the same figure using matplotlib

### ISSUE THREAD

**Issue by pmoriano** [shap/shap#2822]
Hello,

I wonder how to place two independent beeswarm plots into the same figure but in different axes. I am using matplotlib version `3.4.2`, shap version `0.39.0`, and Python `3.8`. I am trying using a single figure and two axes but realize that the beeswarm method does not handle the axis as parameter (error: `TypeError: beeswarm() got an unexpected keyword argument 'ax'`). Any recommendation is welcome. Thanks in advance.

```
from matplotlib import pyplot as plt
import shap

fig, axes = plt.subplots(1, 2, figsize=(35, 7), gridspec_kw = {"wspace":1.0}) 

shap.plots.beeswarm(explainer_a(X_test_a), max_display=10, ax = axes[0])
shap.plots.beeswarm(explainer_b(X_test_b), max_display=10, ax = axes[1])

plt.show()
```

**Comment by bastidas** [comment]
The plots routines in Shap are all figure level and not axis level. This is inconvenient, unnecessary, and appears to have simply been an oversight. Locally I have started refactoring them to be optional axis level, for example you can pass a figure and axis optionals into beeswarm as you have done above, and if they are present it plots to those axis directly.

If other users have this problem I could make a PR for these changes, but I wonder if the developers would be amenable to this?

**Comment by thatlittleboy** [comment]
There was some discussion about this in the SHAP community fork, dsgibbons#5, so I think there's sufficient interest in such an API. I'm definitely open to reviewing such a PR if the work is already done. @bastidas
