### ISSUE TITLE
Some questions about the calculation using tree SHAP

### ISSUE THREAD

**Issue by ZiwenYeee** [shap/shap#283]
![image](https://user-images.githubusercontent.com/42403302/46842306-88c88f80-cdff-11e8-9c2e-0f441253fb6b.png)

Hi Scott,
I think it's easy for you but I'm still confused by the calculation :( , it's very appreciated if you can help me.

I'm trying to figure out how to calculate shapley value under tree model, and my calculation is as follow,do I understand shapley value in a right way? If I'm right, I have some questions about the expectation using in the calculation.

-----------------------------------------------------------------------------------
example with RM = 6.421 LSTAT = 9.14
-----------------------------------------------------------------------------------
the calculation of feature RM
----------------------------------------------------
S = {} / S = {LSTAT}

1. S = {}
f(S) = (46/506 * 32.113043 + 30/506 * 45.096667) + 255/506 * 23.349804 + 175/506 * 14.956
f(S^{RM}) = 255/430 * 23.349804 + 175/430 * 14.956
phi(RM)(0) = 1/2 * (255/430 * 23.349804 + 175/430 * 14.956 - ((46/506 * 32.113043 + 30/506 * 45.096667) + 255/506 * 23.349804 + 175/506 * 14.956))

2. S = {LSTAT}
f(S) = 430/506 * 23.349804 + (46/506 * 32.113043 + 30/506 * 45.096667)
f(S^{RM}) = 23.349804
phi(RM)(1) = 1/2 * (23.349804 - (430/506 * 23.349804 + (46/506 * 32.113043 + 30/506 * 45.096667)))

phi(RM)(0) + phi(RM)(1) = -2.342542

the calculation of feature LSTAT
----------------------------------------------------------------------------------------------
1. S = {}
f(S) = 430/506 * (0.593023 * 23.349804 + 0.406977 * 14.956)
     = 430/506 * (255/430 * 23.349804 + 175/430 * 14.956)
     
f(S^{LSTAT}) = 430/506 * (23.349804)
phi(LSTAT)(0) = 1/2 * [430/506 * (23.349804) - 430/560 * (0.593023 * 23.349804 + 0.406977 * 14.956)]
           = 1/2 * 430/506 * [23.349804 - (0.593023 * 23.349804 + 0.406977 * 14.956)]
           = 1/2 * 430/506 * [23.349804 - (255/430 * 23.349804 + 175/430 * 14.956)]
2. S= {RM}
f(S) = (0.593023 * 23.349804 + 0.406977 * 14.956)
f(S^{LSTAT}) = (23.349804)
phi(LSTAT){1} = 1/2 * (23.349804 - [0.593023 * 23.349804 + 0.406977 * 14.956])

phi(LSTAT) =  1/2 * 430/506 * [23.349804 - (255/430 * 23.349804 + 175/430 * 14.956)] 
           +  1/2 * (23.349804 - [0.593023 * 23.349804 + 0.406977 * 14.956]) = 3.159539

If I'm right, when I calculate the shapley value of feature RM, in the subset {LSTAT}, the effect of LSTAT is to decide whether the data point turn to left leaf or right leaf, so the f(S) can be replaced the expectation of left leaf or right leaf?  when I calculate the subset {LSTAT}, is it the same as the figure as follow?
![image](https://user-images.githubusercontent.com/42403302/46844390-62a7ed00-ce09-11e8-99b1-5298ae965d95.png)

Also, when I calculate the effects of subset {RM}, is it same as the figure as follow?
![image](https://user-images.githubusercontent.com/42403302/46844494-eb268d80-ce09-11e8-93ab-ebaf88a0575d.png)

Also, I've find out that the expectation is not as same as the value output from model, it's the expectation multiply weights(the all samples distributed in the each leaf/all samples), why do you multiply weights in each condition distribution? It seems reasonable but I'm still trying to persuade me in a theoretical way. 

Lastly, I think the shapley value of the data point distributed in the same region divided by tree is equal, is it right? 

Thanks & Regards.

**Comment by slundberg** [comment]
Hey! I can't vouch for all of the equations, but I think one issue is that f({LSTAT}) should the the expected value over all the leaves you can get to while fixing LSTAT to 9.14. This means the leaf with value 14.956 should not be part of that expectation, and you will not be dividing by all 506 samples. Hope that helps!
