### ISSUE TITLE
Can't install using python 3.11 or with numpy >= 1.24 on python < 3.11

### ISSUE THREAD

**Issue by kjyv** [shap/shap#2831]
I noticed this issue originally when trying to install mlflow on python 3.11 which depends on shap (see https://github.com/mlflow/mlflow/issues/7681). The reason that shap fails to install is that it depends on numba which in turn requires llvmlite which does not work with python 3.11 yet.
Numba 0.56.4 also requires numpy < 1.24 which is required for python 3.11. 
Not sure if numba is a hard requirement for shap or if it can be made optional to fix this. Otherwise this ticket could track the issue.

**Comment by martgra** [comment]
Shap also fails on M1 Macs due to llvmlite==0.34 dependency. Regardless of python version.

**Comment by kjyv** [comment]
Works ok here on M1 if used with 3.10.9 - it just can't seem to build llvmlite but if it's installed from a prebuilt package it's ok

**Comment by raphaelauv** [comment]
support for python 3.11 is for the next release ->

https://github.com/numba/numba/pull/8691

**Comment by mikulas1** [comment]
Numba 0.57.0 is now released and supports Python 3.11 and NumPy 1.24

https://numba.readthedocs.io/en/stable/release-notes.html#version-0-57-0-1-may-2023

**Comment by m-k-l-s** [comment]
Numba 0.57.0 is now released and supports Python 3.11 and NumPy 1.24

https://numba.readthedocs.io/en/stable/release-notes.html#version-0-57-0-1-may-2023
