### ISSUE TITLE
numpy dtypes have to be corrected for numpy version 1.24 

### ISSUE THREAD

**Issue by jvpeetz** [shap/shap#2837]
Hi,
since [numpy 1.24](https://numpy.org/doc/stable/release/1.24.0-notes.html) some `dtype` aliases have been removed. Therefore, in the code `np.bool` and `np.int` have to be replaced by `np.bool_` and `np.int_`, resp.
Regards, Jörg.

**Comment by simonangerbauer** [comment]
#1890 fixes this, would be cool if we could get that PR merged and released.

**Comment by arareko** [comment]
There's a PR that has been opened for a while to fix the Numpy deprecations https://github.com/slundberg/shap/pull/2048
