### ISSUE TITLE
What is the "nsamples" parameter in the shap_values function call? 

### ISSUE THREAD

**Issue by ZhouYu44** [shap/shap#284]
In this example below on the github page, there is an "nsamples" parameter. But I get an error msg
"TypeError: shap_values() got an unexpected keyword argument 'nsamples' "

I assume that is a pramemter for an older version? Thanks!  

import sklearn
import shap
from sklearn.model_selection import train_test_split
shap.initjs()
X_train,X_test,Y_train,Y_test = train_test_split(*shap.datasets.iris(), test_size=0.2, random_state=0)
svm = sklearn.svm.SVC(kernel='rbf', probability=True)
svm.fit(X_train, Y_train)
explainer = shap.KernelExplainer(svm.predict_proba, X_train, link="logit")
shap_values = explainer.shap_values(X_test, **nsamples**=100)

**Comment by slundberg** [comment]
Are you sure you are using the KernelExplainer? You would get that error if you tried to use `nsamples` when using TreeExplainer.

**Comment by ZhouYu44** [comment]
Ah, I was using TreeExplainer. Makes sense. Thank you!
