### ISSUE TITLE
SHAP R Package

### ISSUE THREAD

**Issue by shoaibkhanz** [shap/shap#285]
@slundberg , you guys plan to work on R package and create a similar interface and graphics, there is IML R package that does something similar but not exactly.

**Comment by slundberg** [comment]
As only an infrequent user of R I don't have plans to implement it right now. Though I should note that packages like XGBoost have Tree SHAP code integrated into their code-base and do have some R interfaces.

**Comment by pfilo8** [comment]
@shoaibkhanz , few days ago R wrapper for SHAP library was released. It is called Shapper and you can find more informations about that at this github: https://github.com/ModelOriented/shapper

**Comment by liuyanguu** [comment]
Here's a SHAP visualization package for xgboost in R that I released recently. It is called **SHAPforxgboost** and the github page serves as the vignette: https://github.com/liuyanguu/SHAPforxgboost

**Comment by slundberg** [comment]
@liuyanguu very nice!
