### ISSUE TITLE
shap.log_explanation error 

### ISSUE THREAD

**Issue by stb-f5c** [shap/shap#2851]
MLflow, xgboost 1.6.1

explainer_path = _download_artifact_from_uri(explainer_uri)

mlflow.shap.log_explanation(model.predict, X_pred)
returns error:

`Model is missing inputs [HERE is a list of input varialbe names]. Note that there were extra inputs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]`

Any tips what should I change to fix the issue here?

**Comment by dsgibbons** [comment]
Please provide a reproducible example in a code block. Are you sure that is a `shap` error and not `mlflow`?

**Comment by thatlittleboy** [comment]
Yeap, this is an mlflow exception, not shap. Please raise this issue with the mlflow team. Closing as not planned for now, feel free to re-open / raise another issue if you have follow-ups from that conversation.
