### ISSUE TITLE
Saving the partial depeance plot 

### ISSUE THREAD

**Issue by agen49** [shap/shap#2853]
How can I save the partial dependance plot as pdf? Thanks. 

The code below gives me a blank pdf:

`[shap.partial_dependence_plot(
    "N", model.predict, X100, ice=False,
    model_expected_value=True, feature_expected_value=True
)

plt.savefig('mygraph.pdf', format='pdf', dpi=600, bbox_inches='tight')
plt.show()](url)`

**Comment by garciadias** [comment]
Hi @agen49,

You would need to use `show=False` from `partial_dependence_plot` options.
This is because, in matplotlib, you need to save before doing `plt.show()`. 
If you don't use this option the `plt.show()` will be run internally to the function.

```Python
shap.partial_dependence_plot(
"N", model.predict, X100, ice=False,
model_expected_value=True, feature_expected_value=True, show=False
)

plt.savefig('mygraph.pdf', format='pdf', dpi=600, bbox_inches='tight')
plt.show()
```

I hope this is helpful. 👋🏾 🙌🏾

**Comment by thatlittleboy** [comment]
Closing as question has been answered.
