### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by lwq-star** [shap/shap#2855]
I encountered the following indexing error using SHAP to draw a dependency plot.
This is my code:
`shap.plots.scatter(shap_values[:,"DEM"], color=shap_values)`

I get this error:
`
Traceback (most recent call last):

  File "C:\Users\A1827\AppData\Local\Temp\ipykernel_27060\3083767016.py", line 1, in <cell line: 1>
    shap.plots.scatter(shap_values[:,"DEM"], color=shap_values)

  File "D:\Application\miniconda\lib\site-packages\shap\_explanation.py", line 350, in __getitem__
    t = np.argwhere(np.array(self.output_names) == t)[0][0]

IndexError: index 0 is out of bounds for axis 0 with size 0
`

Maybe it has to do with the matplotlib version? #326
My matplotlib was 3.5.3
My SHAP was 0.41.0

**Comment by davidggphy** [comment]
Looks like there is a confusion between `self.output_names` and `self.feature_names`. But even taking that into account I'm not able to make it work.

**Comment by lwq-star** [comment]
The strange thing is `shap.plots.scatter(shap_values[:,0], color=shap_values)` it worked, but `shap.plots.scatter(shap_values[:,1], color=shap_values)` failed.
When running `shap.plots.scatter(shap_values[:,1], color=shap_values)`,  error is reported as follows:
`Traceback (most recent call last):

  File "D:\Application\miniconda\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "d:\project\spatialization\deep_city.py", line 67, in <module>
    shap.plots.scatter(shap_values[:,1], color=shap_values)

  File "D:\Application\miniconda\lib\site-packages\shap\_explanation.py", line 421, in __getitem__
    new_self._s = new_self._s.__getitem__(item)

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer.py", line 112, in __getitem__
    sliced_o = tracked[slicer_index]

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer_internal.py", line 69, in __getitem__
    return UnifiedDataHandler.slice(self.o, index_tup, self.max_dim)

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer_internal.py", line 582, in slice
    is_element, sliced_o, cut = head_slice(o, index_tup, max_dim)

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer_internal.py", line 418, in head_slice
    sliced_o = o[cut_index]

IndexError: index 1 is out of bounds for axis 1 with size 1`

Maybe it has something to do with the base_values from the shap_values. #1801 
I running `shap_values.base_values = shap_values.base_values.ravel()` make the shape of the base_values from the shap_values is correct, but encountered this error:
`Traceback (most recent call last):

  File "C:\Users\A1827\AppData\Local\Temp\ipykernel_60448\564461483.py", line 1, in <cell line: 1>
    shap.plots.scatter(shap_values[:,1], color=shap_values)

  File "D:\Application\miniconda\lib\site-packages\shap\_explanation.py", line 421, in __getitem__
    new_self._s = new_self._s.__getitem__(item)

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer.py", line 112, in __getitem__
    sliced_o = tracked[slicer_index]

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer_internal.py", line 69, in __getitem__
    return UnifiedDataHandler.slice(self.o, index_tup, self.max_dim)

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer_internal.py", line 582, in slice
    is_element, sliced_o, cut = head_slice(o, index_tup, max_dim)

  File "D:\Application\miniconda\lib\site-packages\slicer\slicer_internal.py", line 535, in head_slice
    return True, o[head_index], 1

IndexError: list index out of range`

**Comment by dsgibbons** [comment]
Please provide a reproducible example in a code block.

**Comment by CarlaFernandez** [comment]
Hello @dsgibbons , I'm having the same error when slicing my Explanation object. It's never happened to me until now and I've been using shap for quite some time. I've checked the `data`, `values` and `base_values` attributes and they seem right. 
Here's the numpy object so that you can check it out (load it using `np.load(file_path, allow_pickle=True)`).
[explanation_error.zip](https://github.com/slundberg/shap/files/12013762/explanation_error.zip)

My version of shap is 0.42.0.

**Comment by thatlittleboy** [comment]
@CarlaFernandez Hi, sorry for the late reply. Thanks for providing the object. How are you slicing the object, can you provide some code samples?

**Comment by CarlaFernandez** [comment]
Hello @thatlittleboy , thanks for the help. I realize the previous file I uploaded could not be loaded correctly, so I've pickled the explanation object directly. Here you go: 
[explanation_error.zip](https://github.com/shap/shap/files/12093221/explanation_error.zip)

To load the file:
```python
import pickle

with open("explanation_error.pkl", "rb") as f:
    explanation = pickle.load(f)
```
### Code samples

This is an example of code that breaks with the error described in this issue:
**Code**
```python
print(explanation[:, "redacted_0"])
```
**Result**
`IndexError: index 0 is out of bounds for axis 0 with size 0`

---
The following code works:
**Code**
```python
print(explanation[:, 0])
```
**Result**
```
.values =
array([0., 0., 0., ..., 0., 0., 0.])

.base_values =
array([2.15020228, 2.15020228, 2.15020228, ..., 2.15020228, 2.15020228,
       2.15020228])

.data =
array([0., 0., 0., ..., 1., 0., 0.])
```
---
But this one doesn't:
**Code**
```python
print(explanation[:, 1])
```
**Result**
`IndexError: index 1 is out of bounds for axis 1 with size 1`

Hope this helps, thank you!!

**Comment by thatlittleboy** [comment]
@CarlaFernandez I really appreciate the detailed reproducible steps! <3

May I know how this Explanation was generated? (What Explainer, what model was being explained, whether it's a binary classification / regression task etc.)

Incidentally I am also recently looking into fixing this issue for TreeExplainer (PR not created yet), I just want to make sure I cover the Explainer that is causing this issue for you.

In the meantime, would something like this work as expected?

```python
import copy

import pickle

with open("explanation_error.pkl", "rb") as f:
    explanation = pickle.load(f)

ex2 = copy.copy(explanation)
ex2.base_values = explanation.base_values.squeeze()
print(ex2[:, 1])
```

**Comment by CarlaFernandez** [comment]
Hello again, the explainer is a TreeExplainer for a scikit-learn Random Forest regression model.
This is the code for the model definition (sorry, I can't upload the object):
```python
# split train test
X_train, X_test, y_train, y_test = train_test_split(
    my_dataset[x_cols], 
    my_dataset[target_col], 
    test_size=0.33,
    random_state=42
)

# create model
if categorical_cols:
    ct = ColumnTransformer(
        [("ohe", OneHotEncoder(handle_unknown="ignore"), categorical_cols)],
        remainder="passthrough"
    )
rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=8, 
    random_state=42
)
pipe = Pipeline([("rf", rf)])
if categorical_cols:
    print(f"categorical columns found: {categorical_cols}")
    pipe.steps.insert(0, ("ct", ct))
pipe = pipe.fit(X_train, y_train)
```

And this is how I generate the shap Explanation object for my whole dataset:
```python
explainer = shap.TreeExplainer(pipe.steps[-1][1])

fnames_out = pipe.steps[0][1].get_feature_names_out()
feature_names = [f.replace("remainder__", "") if "remainder" in f else f for f in fnames_out]
if categorical_cols:
    transformed_df = pd.DataFrame(
        pipe.steps[0][1].transform(my_dataset[x_cols]),
        columns=feature_names
    )
else:
    transformed_df = my_dataset[x_cols].copy()
shap_values = explainer(transformed_df)
```
I'm wondering if perhaps the OneHotEncoder is affecting somehow, but I've used it with other models without problems.

Regarding the temporal solution you provided, it does work! I actually found the slicing error when trying to plot a scatter plot, and your solution allows me to do it, so I think it is slicing correctly.

**Comment by thatlittleboy** [comment]
@CarlaFernandez Good to know, thanks for the feedback! I'll push up a fix this weekend.

---

Btw, regarding the first problem

> Code
> print(explanation[:, "redacted_0"])
> 
> Result
> IndexError: index 0 is out of bounds for axis 0 with size 0

This is occurring because your explanation has `output_names`, so **you should use the output names to index instead**. This works:

```python
explanation[:10, "Output 0"]
```

Result
```
.values =
array([-536.1772133 , -563.39272935, -563.0828114 , -575.05663811,
       -376.59685885, -388.98364773, -405.52481342, -405.88330206,
       -498.95396481, -504.20528962])

.base_values =
array([1572095.36160173, 1572095.36160173, 1572095.36160173,
       1572095.36160173, 1572095.36160173, 1572095.36160173,
       1572095.36160173, 1572095.36160173, 1572095.36160173,
       1572095.36160173])

.data =
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

**Comment by CarlaFernandez** [comment]
Thanks @thatlittleboy . Could you give me some insight as to why this specific Explanation object has output_names, and what is their use internally?

**Comment by thatlittleboy** [comment]
@CarlaFernandez 

> Could you give me some insight as to why this specific Explanation object has output_names

It's automatically assigned here during the instantiation of the Explanation object:

https://github.com/shap/shap/blob/b92aef0b6a3264574db31556ca26236b5994a387/shap/_explanation.py#L118-L119

And the problematic line is `len(self.output_dims)`. If you print it out for your Explanation object, it's 1 (again, it's due to the `Explanation.base_values` having 1 extra dimension it shouldn't have). -> I won't explain this any deeper, just know that the root of the problem is the same as your original problem.

With the base_values problem fixed, the Explanation object's `len(self.output_dims)` will be 0, `explanation.output_names` will be None, and so you'll be able to use feature names to index.

```python
print(ex2[:, "redacted_0"])  # should work after "squeezing" the base_values
```

---

> and what is their use internally?

I'm not 100% sure, but it seems to be used by the ImageExplainer, for example: https://shap.readthedocs.io/en/stable/example_notebooks/benchmarks/image/Image%20Multiclass%20Classification%20Benchmark%20Demo.html

It's not used, as far as I can tell, in a TreeExplainer context.

**Comment by thatlittleboy** [comment]
@CarlaFernandez So actually my "fix" wasn't actually that accurate (I didn't expect `output_names` to be affected as well!).

You should do this instead:

```python
import pickle
import shap

with open("explanation_error.pkl", "rb") as f:
    explanation = pickle.load(f)

ex2 = shap.Explanation(
    values=explanation.values,
    base_values=explanation.base_values.squeeze(),  # <-------
    data=explanation.data,
    feature_names=explanation.feature_names,
)
print(ex2[:, 1])
print(ex2[:, "redacted_0"])  # both should work now
```

**Comment by CarlaFernandez** [comment]
Really clarifying! I've never used shap in an image context, so perhaps that's when the output names come in handy. Thanks for all the help, I count this issue as solved for me now. And the PR you authored looks really nice :)
