### ISSUE TITLE
Dependance and summary plot notdrawing

### ISSUE THREAD

**Issue by cperezln** [shap/shap#2856]
Hello, I am new into shap library and I am having some issues with dependence_plot() and summary_plot(). They don't show up when I call the function, instead, if I use display(plot_from_dependence) what is shown up is `None`. 
This doesn't happen with the same fitted model in force_plot(), so I am wondering what it could be.

**Comment by thatlittleboy** [comment]
Can you show us the code that you used with `dependence_plot()` and `summary_plot()`? (A complete minimal working example)
