### ISSUE TITLE
About using deepexplainer question

### ISSUE THREAD

**Issue by qq492947833** [shap/shap#2862]
我想使用deepexplainer来计算我CNN模型中每个特征的贡献，但是使用您的团队创作的shap时，程序看起来无法运行下去。程序不占用cpu和gpu的使用率，就像崩溃了一样。而且无法通过任何方式查询到该程序的状态（不像tensorflow那样提示模型的训练进程）。如何解决这个问题？
I want to use deepexplainer to calculate the contribution of each feature in my CNN model, but when using the shap created by your team, the program seems to be unable to run. The program does not occupy the utilization rate of cpu and gpu, just like crashing. Moreover, the status of the program cannot be queried in any way (unlike TensorFlow, which prompts the training process of the model). How to solve this problem?

**Comment by dsgibbons** [comment]
There is not enough detail here. Please provide a minimal example that demonstrates this issue in a code block that I can run.

**Comment by dsgibbons** [comment]
Closing, as no feedback was received.

**Comment by qq492947833** [comment]
Sorry,I am not research CV,I am research deep learning in Atmosphere Science。I have more data，and it cant be upload，because it have more than 100GB。But I can give you my code，it look like too long，because I just want to pack my code。The code at 320 row to 332 row is used your function。The code ahead of 320 row are right，I use them many time。 
`
def Auto_CNN(vy,vx,model_list,test_size=0.25,ifrandom_split='yes',cov_padding='same',cov_strides=1,pooling_padding='valid',pooling_strides=2,if_weight_initialize='no',weight_initialize_method='TruncatedNormal',weight_initialize_parameter1=0.00,weight_initialize_parameter2=0.05,if_print_model='yes',loss_function='mean_squared_error',optimizer='SGD',metrics='MeanSquaredError',learning_rate=0.01,epochs=2000,batch_size=20,ifheatmap='yes',ifweight='yes',device='cpu'):
    from keras.models import Sequential
    import math
    from keras.layers.core import Activation,Dropout,Dense,Flatten
    from keras.initializers import TruncatedNormal,RandomNormal,RandomUniform
    from keras.layers import BatchNormalization,LayerNormalization,LocallyConnected2D,Conv2D,MaxPooling2D,AveragePooling2D
    from sklearn.model_selection import train_test_split
    import numpy as np
    import keras
    from tensorflow.keras.optimizers import SGD,Adam
    from scipy.stats import pearsonr
    import tensorflow as tf
    import os
    from keras import backend as K
    import shap
    tf.compat.v1.disable_eager_execution()
    
    heatmap=0
    model=0
    if device=='gpu':
        os.environ["CUDA_VISIBLE_DEVICES"] = "0"  
        tf.device('/gpu:0')
        config = tf.compat.v1.ConfigProto()
        config.gpu_options.allow_growth = True
        sess = tf.compat.v1.Session(config=config)
        model_list=np.array(model_list)
        if ifrandom_split=='yes':
            trainy,testy,trainx,testx = train_test_split(vy,vx,test_size=test_size,random_state=25)
        else:
            index=int((1-test_size)*vy.shape[0])
            trainy=vy[:index]
            testy=vy[index:]
            trainx=vx[:index,:,:,:]
            testx=vx[index:,:,:,:]
        model=Sequential()
        inputshape=(trainx.shape[1],trainx.shape[2],trainx.shape[3])
        j=0
        hight=trainx.shape[1]
        weight=trainx.shape[2]
        for i in range(model_list.shape[0]):
            if model_list[i][0] == 'cov':
                if cov_padding=='valid':
                    hight=math.ceil(1+((hight-model_list[i][1][1])/cov_strides))
                    weight=math.ceil(1+((weight-model_list[i][1][2])/cov_strides))
                    if hight < 1 or weight < 1:
                        print('卷积层数过多')
                        break
                if if_weight_initialize=='no':
                    if j==0:
                        model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape))
                    else:
                        model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding))
                else:
                    if j==0:
                        if weight_initialize_method=='RandomNormal':
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                        elif weight_initialize_method=='RandomUniform':
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                        elif weight_initialize_method=='TruncatedNormal':
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2,metrics='MeanSquaredError')))
                    else:
                        if weight_initialize_method=='RandomNormal':
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                        elif weight_initialize_method=='RandomUniform':
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                        elif weight_initialize_method=='TruncatedNormal':
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                j=j+1
            if model_list[i][0] == 'localcov':
                if cov_padding=='valid':
                    hight=math.ceil(1+((hight-model_list[i][1][1])/cov_strides))
                    weight=math.ceil(1+((weight-model_list[i][1][2])/cov_strides))
                    if hight < 1 or weight < 1:
                        print('卷积层数过多')
                        break
                if if_weight_initialize=='no':
                    if j==0:
                        model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape))
                    else:
                        model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding))
                else:
                    if j==0:
                        if weight_initialize_method=='RandomNormal':
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                        elif weight_initialize_method=='RandomUniform':
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                        elif weight_initialize_method=='TruncatedNormal':
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                    else:
                        if weight_initialize_method=='RandomNormal':
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1,1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                        elif weight_initialize_method=='RandomUniform':
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                        elif weight_initialize_method=='TruncatedNormal':
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                j=j+1
            elif model_list[i][0] == 'maxpooling':
                if pooling_padding=='valid':
                    hight=math.ceil(1+((hight-model_list[i][1][0])/pooling_strides))
                    weight=math.ceil(1+((weight-model_list[i][1][1])/pooling_strides))
                    if hight < 1 or weight < 1:
                        print('池化层数过多')
                        break
                model.add(MaxPooling2D(pool_size=(model_list[i][1][0],model_list[i][1][1]),strides=pooling_strides,padding=pooling_padding))
            elif model_list[i][0] == 'avepooling':
                if pooling_padding=='valid':
                    hight=math.ceil(1+((hight-model_list[i][1][0])/pooling_strides))
                    weight=math.ceil(1+((weight-model_list[i][1][1])/pooling_strides))
                    if hight < 1 or weight < 1:
                        print('池化层数过多')
                        break
                model.add(AveragePooling2D(pool_size=(model_list[i][1][0],model_list[i][1][1]),strides=pooling_strides,padding=pooling_padding))
            elif model_list[i][0] == 'batchnormalization':
                model.add(BatchNormalization(axis=-1))
            elif model_list[i][0] == 'layernormalization':
                model.add(LayerNormalization(axis=-1))
            elif model_list[i][0] == 'activation':
                model.add(Activation(model_list[i][1]))
            elif model_list[i][0] == 'flatten':
                model.add(Flatten())
            elif model_list[i][0] =='fc':
                if if_weight_initialize=='no':
                    model.add(Dense(model_list[i][1]))
                else:
                    if weight_initialize_method=='RandomNormal':
                        model.add(Dense(model_list[i][1],kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                    elif weight_initialize_method=='RandomUniform':
                        model.add(Dense(model_list[i][1],kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                    elif weight_initialize_method=='TruncatedNormal':
                        model.add(Dense(model_list[i][1],kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
            elif model_list[i][0] == 'dropout':
                model.add(Dropout(model_list[i][1]))
        if if_print_model=='yes':
            print(model.summary())
        trainx=np.nan_to_num(trainx,nan=0)
        testx=np.nan_to_num(testx,nan=0)
        if optimizer == 'SGD':
            opt = SGD(lr = learning_rate)
        elif optimizer == 'Adam':
            opt = Adam(lr = learning_rate)
        if metrics=='MeanSquaredError':
            model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.MeanSquaredError()])
        elif metrics=='RootMeanSquaredError':
            model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.RootMeanSquaredError()])
        elif metrics=='MeanAbsoluteError':
            model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.MeanAbsoluteError()])
        elif metrics=='MeanAbsolutePercentageError':
            model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.MeanAbsolutePercentageError()])
        H = model.fit(trainx,trainy,validation_data=(testx,testy),epochs = epochs,batch_size=batch_size)
        predicty = model.predict(testx)
        predicty = predicty.reshape(predicty.shape[0])
        r,p=pearsonr(predicty,testy)
        if ifheatmap=='yes':
            result=model.output
            first_layer=model.get_layer(index=0)
            grads = K.gradients(result,first_layer.output)[0]
            pooled_grads = K.mean(grads, axis=(0, 1, 2))
            iterate = K.function([model.input], [pooled_grads, first_layer.output[0]]) 
            pooled_grads_value, conv_layer_output_value = iterate([trainx])
            for i in range(vx.shape[3]):
                conv_layer_output_value[:, :, i] *= pooled_grads_value[i]
            heatmap = np.nanmean(conv_layer_output_value, axis=-1)
            heatmap = np.maximum(heatmap, 0)
            heatmap /= np.nanmax(heatmap)
        if ifweight=='yes':
            weights=[]
            weight_more=[]
            explainer=shap.DeepExplainer(model,trainx,session=tf.compat.v1.keras.backend.get_session())
            result=explainer.shap_values(trainx)
            weight=np.array(result)
            print(weight.shape)
            for i in range(len(weight)):
                weight_more.append(weight[i])
            weight_more=np.array(weight_more)
            for i in range(len(weight)):
                weights.append(((weight[i]/np.nansum(weight_more,axis=0))*100))
                print('预报因子',i+1,'的贡献：',np.array(weights[i]),'％')
    else:
        os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
        with tf.device('/cpu:0'):
            model_list=np.array(model_list)
            if ifrandom_split=='yes':
                trainy,testy,trainx,testx = train_test_split(vy,vx,test_size=test_size,random_state=25)
            else:
                index=int((1-test_size)*vy.shape[0])
                trainy=vy[:index]
                testy=vy[index:]
                trainx=vx[:index,:,:,:]
                testx=vx[index:,:,:,:]
            model=Sequential()
            inputshape=(trainx.shape[1],trainx.shape[2],trainx.shape[3])
            j=0
            hight=trainx.shape[1]
            weight=trainx.shape[2]
            for i in range(model_list.shape[0]):
                if model_list[i][0] == 'cov':
                    if cov_padding=='valid':
                        hight=math.ceil(1+((hight-model_list[i][1][1])/cov_strides))
                        weight=math.ceil(1+((weight-model_list[i][1][2])/cov_strides))
                        if hight < 1 or weight < 1:
                            print('卷积层数过多')
                            break
                    if if_weight_initialize=='no':
                        if j==0:
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape))
                        else:
                            model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding))
                    else:
                        if j==0:
                            if weight_initialize_method=='RandomNormal':
                                model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                            elif weight_initialize_method=='RandomUniform':
                                model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                            elif weight_initialize_method=='TruncatedNormal':
                                model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2,metrics='MeanSquaredError')))
                        else:
                            if weight_initialize_method=='RandomNormal':
                                model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                            elif weight_initialize_method=='RandomUniform':
                                model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                            elif weight_initialize_method=='TruncatedNormal':
                                model.add(Conv2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                    j=j+1
                if model_list[i][0] == 'localcov':
                    if cov_padding=='valid':
                        hight=math.ceil(1+((hight-model_list[i][1][1])/cov_strides))
                        weight=math.ceil(1+((weight-model_list[i][1][2])/cov_strides))
                        if hight < 1 or weight < 1:
                            print('卷积层数过多')
                            break
                    if if_weight_initialize=='no':
                        if j==0:
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape))
                        else:
                            model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding))
                    else:
                        if j==0:
                            if weight_initialize_method=='RandomNormal':
                                model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                            elif weight_initialize_method=='RandomUniform':
                                model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                            elif weight_initialize_method=='TruncatedNormal':
                                model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,input_shape=inputshape,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                        else:
                            if weight_initialize_method=='RandomNormal':
                                model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1,1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                            elif weight_initialize_method=='RandomUniform':
                                model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                            elif weight_initialize_method=='TruncatedNormal':
                                model.add(LocallyConnected2D(model_list[i][1][0],(model_list[i][1][1],model_list[i][1][2]),strides=cov_strides,padding=cov_padding,kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                    j=j+1
                elif model_list[i][0] == 'maxpooling':
                    if pooling_padding=='valid':
                        hight=math.ceil(1+((hight-model_list[i][1][0])/pooling_strides))
                        weight=math.ceil(1+((weight-model_list[i][1][1])/pooling_strides))
                        if hight < 1 or weight < 1:
                            print('池化层数过多')
                            break
                    model.add(MaxPooling2D(pool_size=(model_list[i][1][0],model_list[i][1][1]),strides=pooling_strides,padding=pooling_padding))
                elif model_list[i][0] == 'avepooling':
                    if pooling_padding=='valid':
                        hight=math.ceil(1+((hight-model_list[i][1][0])/pooling_strides))
                        weight=math.ceil(1+((weight-model_list[i][1][1])/pooling_strides))
                        if hight < 1 or weight < 1:
                            print('池化层数过多')
                            break
                    model.add(AveragePooling2D(pool_size=(model_list[i][1][0],model_list[i][1][1]),strides=pooling_strides,padding=pooling_padding))
                elif model_list[i][0] == 'batchnormalization':
                    model.add(BatchNormalization(axis=-1))
                elif model_list[i][0] == 'layernormalization':
                    model.add(LayerNormalization(axis=-1))
                elif model_list[i][0] == 'activation':
                    model.add(Activation(model_list[i][1]))
                elif model_list[i][0] == 'flatten':
                    model.add(Flatten())
                elif model_list[i][0] =='fc':
                    if if_weight_initialize=='no':
                        model.add(Dense(model_list[i][1]))
                    else:
                        if weight_initialize_method=='RandomNormal':
                            model.add(Dense(model_list[i][1],kernel_initializer = RandomNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                        elif weight_initialize_method=='RandomUniform':
                            model.add(Dense(model_list[i][1],kernel_initializer = RandomUniform(minval=weight_initialize_parameter1,maxval=weight_initialize_parameter2)))
                        elif weight_initialize_method=='TruncatedNormal':
                            model.add(Dense(model_list[i][1],kernel_initializer = TruncatedNormal(mean=weight_initialize_parameter1,stddev=weight_initialize_parameter2)))
                elif model_list[i][0] == 'dropout':
                    model.add(Dropout(model_list[i][1]))
            if if_print_model=='yes':
                print(model.summary())
            trainx=np.nan_to_num(trainx,nan=0)
            testx=np.nan_to_num(testx,nan=0)
            if optimizer == 'SGD':
                opt = SGD(lr = learning_rate)
            elif optimizer == 'Adam':
                opt = Adam(lr = learning_rate)
            if metrics=='MeanSquaredError':
                model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.MeanSquaredError()])
            elif metrics=='RootMeanSquaredError':
                model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.RootMeanSquaredError()])
            elif metrics=='MeanAbsoluteError':
                model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.MeanAbsoluteError()])
            elif metrics=='MeanAbsolutePercentageError':
                model.compile(loss=loss_function,optimizer=opt,metrics=[keras.metrics.MeanAbsolutePercentageError()])
            H = model.fit(trainx,trainy,validation_data=(testx,testy),epochs = epochs,batch_size=batch_size)
            predicty = model.predict(testx)
            predicty = predicty.reshape(predicty.shape[0])
            r,p=pearsonr(predicty,testy) 
            if ifheatmap=='yes':
                result=model.output
                first_layer=model.get_layer(index=0)
                grads = K.gradients(result,first_layer.output)[0]
                pooled_grads = K.mean(grads, axis=(0, 1, 2))
                iterate = K.function([model.input], [pooled_grads, first_layer.output[0]]) 
                pooled_grads_value, conv_layer_output_value = iterate([trainx])
                for i in range(vx.shape[3]):
                    conv_layer_output_value[:, :, i] *= pooled_grads_value[i]
                heatmap = np.nanmean(conv_layer_output_value, axis=-1)
                heatmap = np.maximum(heatmap, 0)
                heatmap /= np.nanmax(heatmap)
            if ifweight=='yes':
                weights=[]
                weight_more=[]
                explainer=shap.DeepExplainer(model,trainx)
                result=explainer.shap_values(trainx)
                weight=np.array(result)
                print(weight.shape)
                for i in range(len(weight)):
                    weight_more.append(weight[i])
                weight_more=np.array(weight_more)
                for i in range(len(weight)):
                    weights.append(((weight[i]/np.nansum(weight_more,axis=0))*100))
                    print('预报因子',i+1,'的贡献：',np.array(weights[i]),'％')
    return model,predicty,testy,r,p,heatmap`
This is a example to use my function，the vx is feature，the vy is label，you can use random data to replace vx and vy。The ifweight parameter must be 'yes' can use your function。If you dont have gpu to run this code，you can set the parameter 'device' to 'cpu'。Other parameter I dont suggest change them。

`model,predicty,testy,r,p,heatmap=Auto_CNN(vy,vx,[['cov',[16,3,3]],['batchnormalization'],['activation','tanh'],['cov',[64,3,3]],['batchnormalization'],['activation','tanh'],['maxpooling',[2,2]],['batchnormalization'],['activation','tanh'],['cov',[128,3,3]],['batchnormalization'],['activation','tanh'],['cov',[256,3,3]],['batchnormalization'],['activation','tanh'],['maxpooling',[2,2]],['batchnormalization'],['activation','tanh'],['flatten'],['fc',512],['batchnormalization'],['activation','tanh'],['fc',256],['batchnormalization'],['activation','tanh'],['fc',1],['batchnormalization'],['activation','tanh']],test_size=0.25,ifrandom_split='yes',cov_padding='same',cov_strides=1,pooling_padding='valid',pooling_strides=2,if_weight_initialize='no',weight_initialize_method='TruncatedNormal',weight_initialize_parameter1=0.00,weight_initialize_parameter2=0.05,if_print_model='yes',loss_function='mean_squared_error',optimizer='Adam',metrics='MeanSquaredError',learning_rate=0.001,epochs=1,batch_size=20,ifheatmap='no',ifweight='yes',device='gpu')`

If you can reply me，I will very appreciate that！Thank you very much！
