### ISSUE TITLE
Error on decision_plot.ipynb

### ISSUE THREAD

**Issue by waikoreaweatherpjt** [shap/shap#2882]
I am follwing this file, but there are error when i open data of [crime](https://archive.ics.uci.edu/ml/datasets/Communities+and+Crime+Unnormalized). this is not pickle file but txt file, and when i tried to open this, 

> UnpicklingError: pickle data was truncated

how can i solve this?

also 

force_plot needs  a, b, c are columns, values of 1st rows[list format], values of 2nd rows[list format]. is this right?

**Comment by dsgibbons** [comment]
Can you please provide a minimal reproducible example in a formatted code block?
