### ISSUE TITLE
lightgbm error

### ISSUE THREAD

**Issue by ganzhiruyi** [shap/shap#289]
Hi, thanks for the great job! I have a problem here.
First, I train a lightgbm model with a libsvm data with MPI interface. When I load the model, transform data from libsvm to dense, then  call the "shap_values = explainer.shap_values",  the problem below occur, I want to know why. Thanks.
![image](https://user-images.githubusercontent.com/4384420/47154128-031f7500-d314-11e8-9264-27d5eb12deae.png)

**Comment by slundberg** [comment]
Hmm...it looks like there might be an issue applying a model trained on sparse data to a dense data matrix. Could you try the following?

`model.predict(a, pred_contrib=True).shape`
and
`model.predict(train_x[:100], pred_contrib=True).shape`
and
`model.predict(d, pred_contrib=True).shape`

**Comment by ganzhiruyi** [comment]
> model.predict(d, pred_contrib=True).shape

Hi, thanks for your reply. I print what you ask, the shape of predict is (100,5058), it's wired, my model is a binary classifier.
![image](https://user-images.githubusercontent.com/4384420/47280764-7f62d280-d60a-11e8-9a30-85747a8a928b.png)

**Comment by slundberg** [comment]
Sorry for the slow reply, it looks like a problem in the LightGBM code base since the error happens even when you don't use shap.

**Comment by ganzhiruyi** [comment]
> Sorry for the slow reply, it looks like a problem in the LightGBM code base since the error happens even when you don't use shap.

Anyway, thank you for your patience. Okay, I'll look for the solution of LightGBM.

**Comment by slundberg** [comment]
Feel free to reopen if need be.
