### ISSUE TITLE
How to extract values from SHAP force plot or _waterfall.waterfall_legacy

### ISSUE THREAD

**Issue by theflyingali** [shap/shap#2895]
The plots produced by shap.plots.force and shap.plots._waterfall.waterfall_legacy are very interesting as they allow me to see the impact of each feature on an individual prediction. However, I would like to be able to extract these numbers and make my own graphs. For example, I get the following plots:
![force plot](https://user-images.githubusercontent.com/68812855/229953623-bf8015e1-ae8a-499c-a155-05940b0397f9.png)
![waterfall plot](https://user-images.githubusercontent.com/68812855/229953625-5bb289b2-10e5-4f8d-bbdf-7c2448c49ea2.png)

I would like to be able to not only print out these htmls with these graphs but to extract the numbers, into a dataframe or something of the sort, where it shows me feature 0 had an impact of -0.08, feature 14 an impact of -0.04, etc...

I tried going through the documentation of the plot for force plots but couldn't figure out how the numbers are calculated.

Is it possible to help me with this?

**Comment by thatlittleboy** [comment]
@theflyingali The values in the plots are all coming from the `Explanation` object (output of `shap.explainer(model)(X)`) or the shap values numpy array (output of `shap.explainer(model).shap_values(X)`).
For the former case, you want to inspect the `values` and `base_values` attributes.
