### ISSUE TITLE
plotting the scatter plot

### ISSUE THREAD

**Issue by RajdeepTarafder** [shap/shap#2897]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], line 2
      1 # Create a scatter plot of the SHAP values
----> 2 shap.plots.scatter(shap_values)

File ~\AppData\Roaming\Python\Python310\site-packages\shap\plots\_scatter.py:89, in scatter(shap_values, color, hist, axis_color, cmap, dot_size, x_jitter, alpha, title, xmin, xmax, ymin, ymax, overlay, ax, ylabel, show)
     87 f = pl.subplots(1, len(inds), figsize=(min(6 * len(inds), 15), 5))
     88 for i in inds:
---> 89     ax = pl.subplot(1,len(inds),i+1)
     90     scatter(shap_values[:,i], color=color, show=False, ax=ax, ymin=ymin, ymax=ymax)
     91     if overlay is not None:

File C:\ProgramData\anaconda3\lib\site-packages\matplotlib\pyplot.py:1296, in subplot(*args, **kwargs)
   1293 fig = gcf()
   1295 # First, search for an existing subplot with a matching spec.
-> 1296 key = SubplotSpec._from_subplot_args(fig, args)
   1298 for ax in fig.axes:
   1299     # if we found an Axes at the position sort out if we can re-use it
   1300     if ax.get_subplotspec() == key:
   1301         # if the user passed no kwargs, re-use

File C:\ProgramData\anaconda3\lib\site-packages\matplotlib\gridspec.py:594, in SubplotSpec._from_subplot_args(figure, args)
    592 else:
    593     if not isinstance(num, Integral) or num < 1 or num > rows*cols:
--> 594         raise ValueError(
    595             f"num must be an integer with 1 <= num <= {rows*cols}, "
    596             f"not {num!r}"
    597         )
    598     i = j = num
    599 return gs[i-1:j]

ValueError: num must be an integer with 1 <= num <= 4, not array([1, 3, 2], dtype=int64)

**Comment by dsgibbons** [comment]
Thank you for your interest in SHAP. Your example is not reproducible. Can you please post a full example so that I can check your implementation? Please use code block formatting.

**Comment by dsgibbons** [comment]
Closing, as no feedback was received.
