### ISSUE TITLE
ImportError: No module named deep

### ISSUE THREAD

**Issue by RiccardoTisseur** [shap/shap#291]
New to shap. I have installed it with pip without errors. When I try to import it I get the following error:
`
ImportError                               Traceback (most recent call last)
<ipython-input-2-efbb001a1501> in <module>()
----> 1 import shap

c:\users\s6j556\documentrt\anacondaenvs\jupyteranalysis\lib\site-packages\shap-0.25.0-py2.7-win-amd64.egg\shap\__init__.py in <module>()
      6 from .explainers.sampling import SamplingExplainer
      7 from .explainers.tree import TreeExplainer, Tree
----> 8 from .explainers.deep import DeepExplainer
      9 from .explainers.gradient import GradientExplainer
     10 from .explainers.linear import LinearExplainer

ImportError: No module named deep
`

**Comment by slundberg** [comment]
hmmm...I think that's because you have the latest version in github not the 0.24 which is latest on pypi. That is an error though that needs fixed before the 0.25 release gets pushed. Thanks!
