### ISSUE TITLE
Shap not compatible with numpy>=1.24.0

### ISSUE THREAD

**Issue by vincentl-met** [shap/shap#2911]
Since 1.24.0 numpy removed `np.bool` which will lead to various errors using `shap` repository.
On my case I fixed `numpy` version to 1.23.0 to make it work.

**Comment by detrin** [comment]
I am not sure about the version change in numpy

Here are another problematic lines 
https://github.com/slundberg/shap/blob/master/shap/utils/_general.py#L85
https://github.com/slundberg/shap/blob/master/shap/utils/_general.py#L137

THose could be changed to something like following https://github.com/slundberg/shap/blob/master/shap/utils/_general.py#L159

Alias `np.float` was deprecated in [numpy 1.20.0](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations).

**Comment by simonangerbauer** [comment]
Duplicate ticket #2837 
PR that fixes this #1890

**Comment by StatMixedML** [comment]
The incompatibility issue with numpy is still present (I am using the git-version of your package)

```python
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by AdJasper** [comment]
Replace `np.bool` by `np.bool_` and `np.int` by `np.int_` in all files in the `shap` package and it will work

**Comment by ricardobarroslourenco** [comment]
If the refactoring will take more time, at least it could be versioned a patch for shap with numpy < 1.24.0 as a dependency. This would provide a temporary fix, while the major refacing can be done.

**Comment by nicolasbetancourtc** [comment]
The incompatibility issue with numpy is still present 
```
def lars_path(X, y, Xy=None, Gram=None, max_iter=500, alpha_min=0,
---> 30               method='lar', copy_X=True, eps=np.finfo(np.float).eps,
     31               copy_Gram=True, verbose=0, return_path=True,
     32               return_n_iter=False, positive=False):
AttributeError: module 'numpy' has no attribute 'float'.
```
