### ISSUE TITLE
Keras functional model and SHAP

### ISSUE THREAD

**Issue by GiannisHaralabopoulos** [shap/shap#2913]
# I am loading a keras functional model but I am having the following error:

ValueError: Input ['[MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK] [MASK]'] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

# The code is this:

import tensorflow as tf
from transformers import BertTokenizer
import pandas as pd
from tensorflow import keras
import shap
import scipy as sp

model = keras.models.load_model("Models//ECG//55scipts_512maxlen_7epochs.h5")
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

df = pd.read_csv('twtud.csv')

def f(x):
    token = tokenizer.encode_plus(
        x,
        max_length=512,
        padding='max_length',
        return_tensors='tf'
    )
    probs = model.predict([tf.cast(token.input_ids, tf.int32),
                           tf.cast(token.attention_mask, tf.int32)],
                          verbose=0)[0]
    return sp.special.logit(probs[0])

X = df['text'][:10]
explainer = shap.Explainer(f, tokenizer)
shap_values = explainer(X)

**Comment by dsgibbons** [comment]
> model = keras.models.load_model("Models//ECG//55scipts_512maxlen_7epochs.h5")
> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
> df = pd.read_csv('twtud.csv')

This script references assets that I don't have access to. Can you please update your example to include the source code required to load these assets? Please format your example in a code block so it is easier to read.

**Comment by dsgibbons** [comment]
Closing, as no feedback was received.
