### ISSUE TITLE
Getting x_grad as None

### ISSUE THREAD

**Issue by princerajintSwiggy** [shap/shap#2922]
Hi, This error is coming because, here. in phi_symbolic function, x_grad is returning None. 
x_grad = tape.gradient(out, shap_rAnD)
tf.keras.backend.set_learning_phase(phase)
return x_grad

<ipython-input-14-fea432d6f494> in run(self, out, model_inputs, X)
     27 
     28                 return final_out
---> 29             return self.execute_with_overridden_gradients(anon)
     30 
     31 def custom_grad(self, op, *grads):

<ipython-input-14-fea432d6f494> in execute_with_overridden_gradients(self, f)
     84         return out
     85     else:
---> 86         return [v.numpy() for v in out]

<ipython-input-14-fea432d6f494> in <listcomp>(.0)
     84         return out
     85     else:
---> 86         return [v.numpy() for v in out]

AttributeError: 'NoneType' object has no attribute 'numpy'
I have checked the model. I am using all the differentiable functions.

**Comment by princerajintSwiggy** [comment]
..

**Comment by dsgibbons** [comment]
Thank you for your interest in SHAP. Your example is not reproducible. Can you please post a full example so that I can check your implementation? Please use code block formatting.

**Comment by dsgibbons** [comment]
Closing, as no feedback was received.
