### ISSUE TITLE
shap_values_interaction = shap.TreeExplainer(model).shap_interaction_values

### ISSUE THREAD

**Issue by daehwanahn** [shap/shap#293]
Hello, 

I got an error (**predict() got an unexpected keyword argument 'pred_interactions'**) when I tried to get an interaction values through TreeExplainer.

I already checked that it can be derived when I use old version of xgboost.
So I tried newest version of xgboost (0.72.1 and 0.8), but it is not still solved.

Do you have any idea for this?

ps. I used Google Colab for this test.

Thank you,
Daehwan Ahn

**Comment by slundberg** [comment]
Could you post the whole code snippet you are running? `pred_interactions` is supported in xgboost, so I am not sure where things are not working.

**Comment by daehwanahn** [comment]
Thank you for your reply.
It has been solved.
I think that there was some problems when I tested with repetitions of installing and uninstalling various versions of XGBoost at Colab.
Next day, I installed 0.72 and it worked well.

Many thanks to your package and efforts.
