### ISSUE TITLE
Shap for Large set of data points trained on DNN not working

### ISSUE THREAD

**Issue by mashirali** [shap/shap#2937]
X.shape, y.shape
((1341026, 81), (1341026,))

-------------------------------------------------------

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 dense (Dense)               (None, 78)                6396      
                                                                 
 dense_1 (Dense)             (None, 39)                3081      
                                                                 
 dense_2 (Dense)             (None, 19)                760       
                                                                 
 dense_3 (Dense)             (None, 8)                 160       
                                                                 
 dense_4 (Dense)             (None, 4)                 36        
                                                                 
 dense_5 (Dense)             (None, 1)                 5         
                                                                 
=================================================================
Total params: 10438 (40.77 KB)
Trainable params: 10438 (40.77 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
-------------------------------------------------------

# Step 1: Create a ShapKernel explainer
shap_kernel = ShapKernel(model, X_train)

# or in case i want to give few lines -> shap_kernel = ShapKernel(model, X_train[:50])

shap_local = shap_kernel.explain_local(X[:2],y[:2])

show(shap_local, 0)

---------------------------------------

This is giving an error

IndexError                                Traceback (most recent call last)
Cell In[107], line 1
----> 1 shap_local = shap_kernel.explain_local(X[:2],y[:2])
      3 show(shap_local, 0)

File c:\Users\mashi\anaconda3\lib\site-packages\interpret\blackbox\_shap.py:68, in ShapKernel.explain_local(self, X, y, name, **kwargs)
     55 def explain_local(self, X, y=None, name=None, **kwargs):
     56     """Provides local explanations for provided instances.
     57 
     58     Args:
   (...)
     66         for each instance as horizontal bar charts.
     67     """
---> 68     return shap_explain_local(self, X, y, name, False, **kwargs)

File c:\Users\mashi\anaconda3\lib\site-packages\interpret\utils\_shap_common.py:73, in shap_explain_local(explainer, X, y, name, is_treeshap, **kwargs)
     71 perf_dicts = gen_perf_dicts(predictions, y, False, classes)
     72 for i, instance in enumerate(X):
---> 73     shap_values = all_shap_values[i]
     74     perf_dict_obj = None if perf_dicts is None else perf_dicts[i]
     76     perf_list.append(perf_dict_obj)

IndexError: list index out of range

**Comment by dsgibbons** [comment]
Can you please format your example as a single code block that I can run?

**Comment by mashirali** [comment]
its the same black box code in the docs of interpretML for neural network for shap implementation 

The link for this is as follows,
https://interpret.ml/docs/shap.html
I have around one million data points from credit risk analysis dataset on kaggle.

**Comment by thatlittleboy** [comment]
@mashirali That example uses `iml` code, can you simplify it to only rely on `shap` code, please?

Also, does this problem only occur with the one million data points from kaggle? Or does it also occur if you have, say, 1000 data points? I.e., please scale your example down as far as possible to make reproducing your problem (and thus debugging), easier on us.

**Comment by dsgibbons** [comment]
The provided example with the breast cancer dataset worked fine on my machine. I can't speak to the larger Kaggle dataset without more input from @mashirali.

**Comment by connortann** [comment]
Closing this issue for now as we do not have enough information to reproduce the issue.
