### ISSUE TITLE
AssertionError: The SHAP explanations do not sum up to the model's output!

### ISSUE THREAD

**Issue by Jeffrey-Liu-prog** [shap/shap#2941]
TF version 2.8.2
SHAP version 0.41

I tried to apply SHAP for my binary classifier of deep residual shrinkage network (DRSN),

from tensorflow.keras import backend as K

def abs_backend(inputs):
    return K.abs(inputs)

def expand_dim_backend(inputs):
    return K.expand_dims(K.expand_dims(inputs,1),1)

def sign_backend(inputs):
    return K.sign(inputs)

def pad_backend(inputs, in_channels, out_channels):
    pad_dim = (out_channels - in_channels)//2
    inputs = K.expand_dims(inputs,-1)
    inputs = K.spatial_3d_padding(inputs, ((0,0),(0,0),(pad_dim,pad_dim)), 'channels_last')
    return K.squeeze(inputs, -1)

# Residual Shrinakge Block(CS)

    def residual_shrinkage_block(incoming, nb_blocks, out_channels, downsample=False,
                             downsample_strides=2):
    
    residual = incoming
    in_channels = incoming.get_shape().as_list()[-1]
    
    for i in range(nb_blocks):
        
        identity = residual
        
        if not downsample:
            downsample_strides = 1
        
        residual = BatchNormalization()(residual)
        residual = Activation('relu')(residual)
        residual = Conv2D(out_channels, 3, strides=(downsample_strides, downsample_strides), 
                          padding='same', kernel_initializer='he_normal', 
                          kernel_regularizer=l2(1e-4))(residual)
        
        residual = BatchNormalization()(residual)
        residual = Activation('relu')(residual)
        residual = Conv2D(out_channels, 3, padding='same', kernel_initializer='he_normal', 
                          kernel_regularizer=l2(1e-4))(residual)
        
        # Calculate global means
        residual_abs = Lambda(abs_backend)(residual)
        abs_mean = GlobalAveragePooling2D()(residual_abs)
        
        # Calculate scaling coefficients
        scales = Dense(out_channels, activation=None, kernel_initializer='he_normal', 
                       kernel_regularizer=l2(1e-4))(abs_mean)
        scales = BatchNormalization()(scales)
        scales = Activation('relu')(scales)
        scales = Dense(out_channels, activation='sigmoid', kernel_regularizer=l2(1e-4))(scales)
        scales = Lambda(expand_dim_backend)(scales)
        
        # Calculate thresholds
        thres = tf.keras.layers.multiply([abs_mean, scales])
        
        # Soft thresholding
        sub = tf.keras.layers.subtract([residual_abs, thres])
        zeros = tf.keras.layers.subtract([sub, sub])
        n_sub = tf.keras.layers.maximum([sub, zeros])
        residual = tf.keras.layers.multiply([Lambda(sign_backend)(residual), n_sub])
        
        # Downsampling using the pooL-size of (1, 1)
        if downsample_strides > 1:
            identity = AveragePooling2D(pool_size=(1,1), strides=(2,2))(identity)
            
        # Zero_padding to match channels
        if in_channels != out_channels:
            identity = Lambda(pad_backend, arguments={'in_channels':in_channels,'out_channels':out_channels})(identity)
        
        residual = tf.keras.layers.add([residual, identity])
    
    return residual

# define and train a model
#First conv layer
inputs = Input(shape=(3,3,14))
net = Conv2D(16, 3, 2)(inputs)
#RSBU-CS nets
net = Conv2D(16, 3, 2, padding='same', kernel_initializer='he_normal', kernel_regularizer=l2(1e-4))(net)
net = residual_shrinkage_block(net, 1, 16, downsample=True)

#BN RELU GAP
net = BatchNormalization()(net)
net = Activation('relu')(net)
# FC layer
net = GlobalAveragePooling2D()(net)
net = Dropout(0.3)(net)
outputs = Dense(2, activation='softmax', kernel_initializer='he_normal', kernel_regularizer=l2(1e-4))(net)
#compile model
DRSN = Model(inputs=inputs, outputs=outputs)
rlrop = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5)
DRSN.compile(loss='binary_crossentropy', 
             optimizer=Adam(learning_rate=0.01), 
             metrics=['accuracy', tf.keras.metrics.AUC()])

#SHAP
background = X_test[np.random.choice(X_test.shape[0], 1000, replace=False)]# we use the first 1000 examples as our background dataset to integrate over
shap.explainers._deep.deep_tf.op_handlers["FusedBatchNormV3"] = shap.explainers._deep.deep_tf.linearity_1d(0)
shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough
explainer = shap.DeepExplainer(DRSN,  background)
shap_values = explainer.shap_values(X_test[:1000])

 but it returned the error with:

AssertionError: The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. If the sum difference of 0.492149 is significant compared the scale of your model outputs please post as a github issue, with a reproducable example if possible so we can debug it.

Any idea what could be causing this? Thanks.

**Comment by thatlittleboy** [comment]
Hi, as the error message mentioned, we need a **reproducible** example in order to help. Also, kindly format your code in a code block so it is easier to read.

**Comment by connortann** [comment]
Closing this issue for now as we don't have sufficient information to reproduce the issue.
