### ISSUE TITLE
No force_matplotlib in current version

### ISSUE THREAD

**Issue by prenderc** [shap/shap#296]
The force matplotlib feature is awesome! Big thank you to who created it. When I do the pip install this feature is not in the package. Not sure why this is, I'm pretty new to this. Looks like there is a version 25 but the pip install gives version 24. I was able to get it to work by downloading the code from GIT and modifying the shap package directly. 

Just thought you may like to know that this awesome functionality is tough to get right now. That being said I could be doing something incorrectly on my end!

**Comment by slundberg** [comment]
That's because I still need to tag a new release for pip. I'll do that here shortly.

**Comment by prenderc** [comment]
Thank you!
