### ISSUE TITLE
xgboost ntree_limit deprecation warning

### ISSUE THREAD

**Issue by adnene-guessoum** [shap/shap#2984]
Hi,

Working on removing the boston dataset from the README.md (following https://github.com/slundberg/shap/pull/2873 ), I encountered this deprecation warning : 

**ntree_limit is deprecated, use `iteration_range` or model slicing instead.**

Here is the test example that triggered it: 

``` 
import xgboost
import shap

X, y = shap.datasets.california()                              
model = xgboost.XGBRegressor().fit(X, y)  

explainer = shap.Explainer(model)                                   
shap_values = explainer(X)
              
shap.plots.waterfall(shap_values[0])
```

This warning is due to ntree_limit being deprecated ( see : https://xgboost.readthedocs.io/en/stable/python/python_api.html ).

A fix for this is to use iteration_range instead of ntree_limit in _tree.py (and elsewhere). for instance, this :

https://github.com/slundberg/shap/blob/c24ff9ac72a2a21fc83f5097ffccf50f5429875d/shap/explainers/_tree.py#L347

would be : 

```try:                                                           
    phi = self.model.original_model.predict(                   
        X, iteration_range=(0, tree_limit), pred_contribs=True,
        approx_contribs=approximate, validate_features=False   
    )                                                          
```

This works in the previous case. If this is not an outrageous solution for some reasons, I would be happy to open a PR.

Let me know.

**Comment by thatlittleboy** [comment]
Hey @adnene-guessoum , thanks for raising this issue. I don't think that what you proposed is an unreasonable fix.

I'll just note that the `iteration_range` parameter is introduced in xgboost 1.4 ([released Apr 11, 2021](https://github.com/dmlc/xgboost/releases/tag/v1.4.0)), for the benefit of any future users stumbling across this PR/issue.

A PR would be very much appreciated!

**Comment by adnene-guessoum** [comment]
thanks for the reply @thatlittleboy . I am not entirely sure about the code coverage and the ci process. if you want to have a look.
