### ISSUE TITLE
BUG: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by 20032303092** [shap/shap#2993]
### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://github.com/slundberg/shap/releases) of shap.

- [X] I have confirmed this bug exists on the master branch of shap.
- [X] I'd be interested in making a PR to fix this bug

### Minimal Reproducible Example

```python
text = ["AG AC GC TG CG TG CA CC GG TT AC CC CA AA GC TG AG AC GC TG CG TG CA CC GG TT AC CC CA AA GC TG AG AC GC TG CG TG CA CC GG TT AC CC CA AA GC TG AG AC GC TG CG TG CA CC GG TT AC CC CA AA GC TG AG AC GC TG CG TG CA CC GG TT AC CC CA AA GC TG"]

inp = model.tokenizer(text, return_tensors='pt', add_special_tokens=False,
                             padding=True)["input_ids"]
explainer2 = shap.Explainer(modelIG)
shap_values2 = explainer2(inp)
shap.plots.text(shap_values2[:,:,1])
```

### Issue Description

modelIG is a model wrapper make my model to accept input_ids as input rather than a sentence.
my model uses longformer pre-trained model as embedding layer, and then uses cnn and lstm.
how to solve it?

### Expected Behavior

make the model with both transformers and pytorch modules interpretable by SHAP

### Installed Versions

the latested

**Comment by dsgibbons** [comment]
This is not a reproducible example. Please provide the source code required to define `model`.

Is this issue still a problem when you install via `pip install git+https://github.com/slundberg/shap.git`?

**Comment by connortann** [comment]
Closing this issue for now as we do not have sufficient information to reproduce the issue.
