### ISSUE TITLE
Huggingface timeout error in CI

### ISSUE THREAD

**Issue by thatlittleboy** [shap/shap#3002]
Once in a while we will encounter a `TimeoutError` to Huggingface servers in our CI's, e.g.

Logs: https://github.com/slundberg/shap/actions/runs/5260258100/jobs/9506925432
```
FAILED tests/explainers/test_partition.py::test_translation - requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10.0)
```

or 

Logs: https://github.com/slundberg/shap/actions/runs/5296501329/jobs/9587659229?pr=3001
```
FAILED tests/maskers/test_fixed_composite.py::test_serialization_fixedcomposite_masker - requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10.0)
```

It's probably because we are running multiple tests that download from HuggingFace at once. I suppose we could try fixing this with a fixture, but we must ensure that the fixture returns a fresh pretrained model everytime.

---

Or it could just be HuggingFace's servers being down for a while. But I think the issue still stands, we could _probably_ optimize our tests a little so we don't make too many requests to HuggingFace in our CI

**Comment by connortann** [comment]
I noticed another intermittent CI error today:

From [this job](https://github.com/slundberg/shap/actions/runs/5347119160/jobs/9695133180#step:5:75)
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    catboost from https://files.pythonhosted.org/packages/ab/ba/f5ede592b6ec19d51907ef11c8f444df6ce3396968e1f14e74a238e6ff5d/catboost-1.2-cp311-cp311-manylinux2014_x86_64.whl (from shap==0.41.0):
        Expected sha256 a0236f6328e33f1e2e5fd6ca619ea5f8759ade06d[70](https://github.com/slundberg/shap/actions/runs/5347119160/jobs/9695133180#step:5:71)9bd9c706443b20525fada
             Got        e27d876b5e38de0907c2df9bc255ec9ec62cd8abea933d53413babcedd07f010
```

It seems to be an intermittent PyPi issue, and can be fixed by re-running the relevant failed tests. If this persists for more than a day or so we should probably look in to it.
