### ISSUE TITLE
BUG: Tests fail when running from built wheel using cibuildwheel

### ISSUE THREAD

**Issue by connortann** [shap/shap#3012]
### Issue Description

The test suite does not fail when installling from the built package. Example [failing run](https://github.com/PrimozGodec/shap/actions/runs/5308945958/jobs/9608991484).

This was uncovered in #2995 , which updated the release action and added a test of the built wheel. This will need to be fixed for #2979.

### Minimal Reproducible Example

Run locally:

```bash
pip install cibuildwheel
cibuildwheel --platform linux
```

Or to run on CI, trigger the `build_wheels` GitHub Action. See previous runs [here](https://github.com/slundberg/shap/actions/workflows/build_wheels.yml).

The issue also arises if the `--editable / -e` flag is removed from the pip install step on CI, as seen in #3017

### Expected Behavior

Build should pass including pytest suite.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.

**Comment by connortann** [comment]
@dsgibbons @thatlittleboy FYI I created this issue to track the failing build uncovered by @PrimozGodec . This issue is blocking us from making a release, so I'd be grateful for any help debugging and fixing this.

Unforunately I haven't had any success debugging the root cause so far; I cannot run `cibuildwheel` on my local env due to issues with network proxies. I just triggered a `build wheels` workflow run manually from master [here](https://github.com/slundberg/shap/actions/runs/5333131372).

Once we have it fixed, I think we should also do a post-mortem to find out why the bug isn't caught in the main CI tests. I suspect the root cause may be that the tests are using the _local_ library rather than the _installed_ library, as referenced [here](https://stackoverflow.com/questions/56908227/how-to-test-python-wheels-on-ci). This could be a consequence of not using a `src` structure, as detailed [here](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure%3E).

**Comment by PrimozGodec** [comment]
@connortann, the build that you triggered failed (on macOS) because catboost cannot be built, and they do not have wheels for cp37 anymore. To test successfully, we would need to install Ninja before, but anyway, it would take a long time for catboost to be built (experiences from Orange3) project. I suggest not testing on cp37 since many packages (including Catboost) no longer provide wheels for this version, and cp37 will, as I understand, be dropped in the next release of Shap.

I also suggest skipping tests for cp38 on MacOS too since (I suspect) they are affected with this error (catboost again): https://github.com/catboost/catboost/issues/2371#issuecomment-1594282255

I can start the pull request, and anyone can contribute then.

**Comment by connortann** [comment]
That seems like a pragmatic way forward, presumably with the `test-skip` configuration option. A PR would be most welcome!

**Comment by connortann** [comment]
We can reproduce the error by removing the `--editable` flag from the `pip install` step on CI: see #3017

This seems like it would be a good thing to fix to prevent this kind of issue in future, although it may cause complications with code coverage checks.

**Comment by connortann** [comment]
I think an underlying issue is that the python module is being imported from the local repo rather than the installed location. This may explain why the `cext` module is not found.

After running `pip install .`, I tried these commands on CI:

```bash
echo "** Working directory:"
pwd
echo "** location of pip-installed shap:"
pip show shap
echo "** SHAP is being imported from:"
python -c "import shap;print(shap.__file__)"
```

Output:

```
** Working directory:
/home/runner/work/shap/shap
** location of pip-installed shap:
Name: shap
Version: 0.41.0
Summary: A unified approach to explain the output of any machine learning model.
Home-page: http://github.com/slundberg/shap
Author: Scott Lundberg
Author-email: slund1@cs.washington.edu
License: MIT
Location: /opt/hostedtoolcache/Python/3.11.4/x[64](https://github.com/slundberg/shap/actions/runs/5336797188/jobs/9671989749?pr=3017#step:6:65)/lib/python3.11/site-packages
Requires: cloudpickle, numba, numpy, packaging, pandas, scikit-learn, scipy, slicer, tqdm
Required-by: 
** SHAP is being imported from:
/home/runner/work/shap/shap/shap/__init__.py
```

So the library is built to `/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/shap`, but is being imported from `/home/runner/work/shap/shap/shap/__init__.py` .

**Comment by connortann** [comment]
After endless debugging runs with cibuildwheel, I think I know the root cause of our build problems.

It looks like mid-way through the pytest execution, the imported shap switches from the installed library (with the build extension) to the local project (without the extension).

I added a few lines to `shap/explainers/tree.py`:

```python
from pathlib import Path
root = Path(__file__).parent.parent.resolve()
print("shap project path:", root)

print("Contents of project:")
print(list(root.iterdir()))
```

Mid-way through the cibuildwheel test, note the change from `site-packages/shap` to `/project/shap` :

```
ontents of project:
  [PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/__init__.py'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/benchmark'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/_explanation.py'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/_serializable.py'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/models'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/datasets.py'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/__pycache__'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/cext'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/plots'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/_cext.cpython-38-x86_64-linux-gnu.so'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/maskers'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/utils'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/actions'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/explainers'), PosixPath('/tmp/tmp.FHIYFZ1hwL/venv/lib/python3.8/site-packages/shap/links.py')]
  ['__init__.py', 'benchmark', '_explanation.py', '_serializable.py', 'models', 'datasets.py', '__pycache__', 'cext', 'plots', '_cext.cpython-38-x86_64-linux-gnu.so', 'maskers', 'utils', 'actions', 'explainers', 'links.py']
  + echo Beginning tests...
  + pytest -v /project/tests -k test_simple_bar
  Beginning tests...
  ============================= test session starts ==============================
  platform linux -- Python 3.8.17, pytest-7.3.2, pluggy-1.2.0 -- /tmp/tmp.FHIYFZ1hwL/venv/bin/python
  cachedir: .pytest_cache
  Matplotlib: 3.7.1
  Freetype: 2.6.1
  rootdir: /project
  configfile: pyproject.toml
  plugins: cov-4.1.0, mpl-0.16.1
  collecting ... shap project path: /project/shap
  Contents of project:
  [PosixPath('/project/shap/__init__.py'), PosixPath('/project/shap/benchmark'), PosixPath('/project/shap/_explanation.py'), PosixPath('/project/shap/_serializable.py'), PosixPath('/project/shap/models'), PosixPath('/project/shap/datasets.py'), PosixPath('/project/shap/__pycache__'), PosixPath('/project/shap/cext'), PosixPath('/project/shap/plots'), PosixPath('/project/shap/maskers'), PosixPath('/project/shap/utils'), PosixPath('/project/shap/actions'), PosixPath('/project/shap/explainers'), PosixPath('/project/shap/links.py')]
  collected 0 items / 1 error
  
  ==================================== ERRORS ====================================
  ________________________ ERROR collecting test session _________________________
  /opt/python/cp38-cp38/lib/python3.8/importlib/__init__.py:127: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  <frozen importlib._bootstrap>:1014: in _gcd_import
      ???
  <frozen importlib._bootstrap>:991: in _find_and_load
      ???
  <frozen importlib._bootstrap>:975: in _find_and_load_unlocked
      ???
  <frozen importlib._bootstrap>:671: in _load_unlocked
      ???
  ../venv/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
      exec(co, module.__dict__)
  /project/tests/plots/conftest.py:7: in <module>
      import shap
  /project/shap/__init__.py:9: in <module>
      from .explainers._explainer import Explainer
  /project/shap/explainers/__init__.py:4: in <module>
      from ._gpu_tree import GPUTree
  /project/shap/explainers/_gpu_tree.py:5: in <module>
      from ._tree import Tree, feature_perturbation_codes, output_transform_codes
  /project/shap/explainers/_tree.py:34: in <module>
      import shap._cext as _cext
  E   ModuleNotFoundError: No module named 'shap._cext'
  =========================== short test summary info ============================
  ERROR ../../../project - ModuleNotFoundError: No module named 'shap._cext'
  !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
  =============================== 1 error in 3.29s ===============================
```

</details


This is yet another nefarious build issue that we've encountered due to confusion between local and installed packages. As per the discussion in #3020 , I think we should seriously consider migrating to a `src` layout as per the draft PR #3019
