### ISSUE TITLE
ENH: The linearExplaner model currently supports only sklearn-style code. However, it is possible to add support for torch.nn functionality to the linear interpreter model.

### ISSUE THREAD

**Issue by hanghangChen** [shap/shap#3023]
### Problem Description

![image](https://github.com/slundberg/shap/assets/63381192/b37c1535-687a-4918-8c94-db582d239126)
![image](https://github.com/slundberg/shap/assets/63381192/b69aedd5-15e0-4db4-8631-6eeefdb9ca9b)

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [ ] I'd be interested in making a PR to implement this feature

**Comment by connortann** [comment]
Please could you provide a bit more detail - for example, a minimal reproducible example of how you would like to invoke the LinearExplainer with a pytorch model?

**Comment by connortann** [comment]
Closing for now as we don't have enough information to proceed.
