### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by ikunpy** [shap/shap#3024]
### Issue Description

just in newest numpy version, the np.bool is replaced by np.bool_, np.int is replaced by np.int_, this question is very easy to fix, but I post it here to recommend shap to update, thank you.

### Minimal Reproducible Example

```python
np.int_
```

### Expected Behavior

fixed

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

newest

**Comment by dsgibbons** [comment]
This issue was addressed by #2943. Please use the master branch. A PyPI release is coming soon.
