### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by jokofa** [shap/shap#3035]
### Issue Description

np.int is deprecated since numpy 1.20 and should be replaced with python int or np.int64/np.int32 for compatibility with newer numpy versions.
In my case resulting in error in
`shap/explainers/_tree.py", line 1511, in __init__
    self.leaf_child_cnt.append(np.zeros(self.num_nodes[i], dtype=np.int))`

--> AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20;

### Minimal Reproducible Example

```python
from sklearn.datasets import fetch_california_housing
import xgboost as xgb
import shap

X, y = fetch_california_housing(return_X_y=True)
xgb_model = xgb.XGBRegressor(n_jobs=1)
xgb_model.fit(X, y)
shap.TreeExplainer(xgb_model, feature_perturbation="tree_path_dependent")
```

### Expected Behavior

No error for newer numpy versions, since there is no version dependency numpy < 1.20 defined.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

numpy     1.24.3
shap         0.41.0 
xgboost   1.7.3

**Comment by thatlittleboy** [comment]
This issue was addressed by https://github.com/slundberg/shap/pull/2943. Please use the master branch for the time being. A PyPI release is coming soon.

**Comment by jokofa** [comment]
Perfect thanks, great to hear!
