### ISSUE TITLE
Publish documentation on ReadTheDocs in PRs

### ISSUE THREAD

**Issue by thatlittleboy** [shap/shap#3038]
At the moment, we do not have ReadTheDocs (RtD) running during PRs. It only runs on latest (master).

This would be nice to have while we embark on #3036 to make PR reviews much easier.

It seems that we most likely need @slundberg to assist here, or we can only do so once we migrate to the SHAP org. (@dsgibbons could you help to bump Scott once again on this, since there are a couple blockers arising already because of this. Thanks!).

Similar in spirit to dsgibbons#83.

**Comment by dsgibbons** [comment]
I've just raised this with Scott. I'll let you know.

**Comment by connortann** [comment]
I've been added as a maintainer on readthedocs, and enabled building docs for PRs 🎉

Closing for now - will re-open if it does not work as expected in future PRs.

**Comment by connortann** [comment]
Re-opening as there is currently an issue with the readthedocs status checks:

![image](https://github.com/shap/shap/assets/71127464/599c8fad-6a89-4601-9a0d-ae528459b0f5)


This should be resovled by reapproving the readthedocs OAuth permission for the new `shap` org- I've requested the relevant permission, so waiting for Scott to approve.

In the meantime, the docs still are being built for new PRs. The URLs seem to follow this pattern:

`https://shap--<PRnum>.org.readthedocs.build/en/<PRnum>/`

For example for PR `3103`, the link is:

<https://shap--3103.org.readthedocs.build/en/3103/>

**Comment by connortann** [comment]
Closing as it's fixed now :)
