### ISSUE TITLE
BUG: AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by alessandrofilisetti** [shap/shap#3055]
### Issue Description

While trying to apply the package to a XGBoost model I obtained the following error 

> `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

numpy version = 1.24.4

the affected file is 

```
File ~/venv/lib/python3.10/site-packages/shap/explainers/_tree.py:1511, in XGBTreeModelLoader.__init__(self, xgb_model)
   1509 self.sum_hess.append(np.zeros(self.num_nodes[i], dtype=np.float32))
   1510 self.base_weight.append(np.zeros(self.num_nodes[i], dtype=np.float32))
-> 1511 self.leaf_child_cnt.append(np.zeros(self.num_nodes[i], dtype=np.int))
   1512 for j in range(self.num_nodes[i]):
   1513     self.loss_chg[-1][j] = self.read('f')
```

### Minimal Reproducible Example

```python
import shap
fit a XGBoost model xgb_classifier
from shap import TreeExplainer
explainer = TreeExplainer(xgb_classifier)
```

### Expected Behavior

...

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.41.0

**Comment by thatlittleboy** [comment]
This bug shouldn't exist on `master` branch. It's already fixed.
We're planning a release soon (see https://github.com/slundberg/shap/issues/2979).  in the meantime please install from master branch directly or downgrade your numpy <1.24.

**Comment by scholarazwa** [comment]
Need to downgrade numpy to 1.23.0 to make things work for now.

**Comment by thatlittleboy** [comment]
New version has been released to pypi and conda. Please give that a try.
