### ISSUE TITLE
IPython warning

### ISSUE THREAD

**Issue by LukeHankey** [shap/shap#3086]
### Issue Description

Is there any reason why the IPython warning could not be lazily imported into the function that requires it? This isn't a bug, more of an annoyance to see the warning when the function that requires it isn't used.

File: `shap/plots/_image.py`
Function: `image_to_text`

### Minimal Reproducible Example

```python
import shap
```

### Expected Behavior

No `IPython could not be loaded` warning in the terminal.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42

**Comment by connortann** [comment]
Thanks for the issue! I made a draft PR to explore how we could fix this.

Apologies, I just noticed you ticked the _"I'd be interested in making a PR to fix this bug"_ checkbox. Happy to leave it to you if you would like to raise your own PR. Or, I'd be grateful for a code review on my draft.

**Comment by LukeHankey** [comment]
> Thanks for the issue! I made a draft PR to explore how we could fix this.
> 
> Apologies, I just noticed you ticked the _"I'd be interested in making a PR to fix this bug"_ checkbox. Happy to leave it to you if you would like to raise your own PR. Or, I'd be grateful for a code review on my draft.

No worries. All good, will go have a look!
