### ISSUE TITLE
AdditiveForceVisualizer: doing more with explanation similarity (sort order, etc.)

### ISSUE THREAD

**Issue by dinicholson** [shap/shap#309]
I'm really loving the additive force graph. Is there an easy way to get the data from the html object, specifically the similarity ordering mapped to the original index for the entire sample dataset?

The alert is helpful: https://github.com/slundberg/shap/issues/195

But I'm hoping to grab all of the sort order values and then annotate clusters, similar to what you've done in your paper:

![image](https://user-images.githubusercontent.com/7265068/47922604-d465da80-de8d-11e8-8660-60827141f20a.png)

Currently I'm  grabbing the shap values and applying the distance calculation and hierarchical clustering separately, but it would be great if it were integrated.

More to that point, is there a plan to add more features related to the hierarchical clustering? It would be amazing if in addition to the sort order of the leaves, the AdditiveForceVisualizer also suggested clusters or even built a dendrogram.

**Comment by slundberg** [comment]
All great ideas. I don't have plans right now to add the ability to export the dendrogram, but if you are interested in contributing some improvements to do that I am happy to review and merge them. My one hesitation is that I don't want to force the plot function to do something unrelated to plotting, and I fear that it is not work wrapping what is just two lines of sklearn code. Perhaps just a notebook example would be best so anyone can see how to use the values to get clusters.

**Comment by CalebRolandWilkinson** [comment]
Scott,

Can you direct me to the code used to generate the clustering that you do in your paper in figure 6A? Was a notebook created to show how this was done? I would be happy to generate a notebook for this but I currently don't understand how the heatmap was generated. I have the clustering portion that you put in another issue around this same subject, but want to make sure I am not misusing the info when I display the clusters.

--code from other issue
D = scipy.spatial.distance.pdist(shap_values[:,:-1], 'sqeuclidean')
clustOrder = scipy.cluster.hierarchy.leaves_list(scipy.cluster.hierarchy.complete(D))

Thank you for any guidance you have. Please let me know if I can help with anything. I love this package and it has greatly helped to explain models at work!

**Comment by slundberg** [comment]
@CalebRolandWilkinson that notebook is in a repo specific to the paper: https://github.com/suinleelab/treeexplainer-study/blob/master/notebooks/mortality/NHANES%20I%20Analysis.ipynb

Hope that helps! Note that the clusters are annotated manually for that figure, but you could use any automated method you please as well.

For anyone else who lands here just looking for how to get the clustering ordering check out `shap.hclust_ordering`

**Comment by CalebRolandWilkinson** [comment]
Thank you for the direction this helps a lot!
