### ISSUE TITLE
DeepExplainer seems heavily dependent on optimizer

### ISSUE THREAD

**Issue by austinmw** [shap/shap#312]
Hi, this is probably working as intended, but I noticed that DeepExplainer plotting results on MNIST seems greatly effected by the type of optimizer chosen. For example it works well with Adadelta, but the visualizations are very poor with Adam. Does the addition of momentum in optimizers have a negative effect on visualization results? Any details about how choice of optimizer effects results would be greatly appreciated!

**Comment by slundberg** [comment]
Well the explainer has no knowledge of the optimizer and only depends on the final form of the model. What you are seeing then is that different optimizers find different models, some of which seem to have more reasonable looking feature dependencies.

**Comment by austinmw** [comment]
Thanks for clarifying!
