### ISSUE TITLE
BUG: Empty waterfall plot

### ISSUE THREAD

**Issue by CarlaFernandez** [shap/shap#3129]
### Issue Description

I'm trying to plot a waterfall plot from a (seemingly) correct Explanation object, but I'm obtaining an empty plot and the following exception:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<command-1167888546861017> in <module>
----> 1 shap.plots.waterfall(wrong[0])

/local_disk0/.ephemeral_nfs/envs/pythonEnv-1a2ab749-87b1-4ef4-bb01-f8a919e5acef/lib/python3.8/site-packages/shap/plots/_waterfall.py in waterfall(shap_values, max_display, show)
    156     points = pos_lefts + list(np.array(pos_lefts) + np.array(pos_widths)) + neg_lefts + \
    157         list(np.array(neg_lefts) + np.array(neg_widths))
--> 158     dataw = np.max(points) - np.min(points)
    159 
    160     # draw invisible bars just for sizing the axes

/local_disk0/.ephemeral_nfs/envs/pythonEnv-1a2ab749-87b1-4ef4-bb01-f8a919e5acef/lib/python3.8/site-packages/numpy/core/overrides.py in amax(*args, **kwargs)

/local_disk0/.ephemeral_nfs/envs/pythonEnv-1a2ab749-87b1-4ef4-bb01-f8a919e5acef/lib/python3.8/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims, initial, where)
   2789     5
   2790     """
-> 2791     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
   2792                           keepdims=keepdims, initial=initial, where=where)
   2793 

/local_disk0/.ephemeral_nfs/envs/pythonEnv-1a2ab749-87b1-4ef4-bb01-f8a919e5acef/lib/python3.8/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     84                 return reduction(axis=axis, out=out, **passkwargs)
     85 
---> 86     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     87 
     88 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
This is the resulting image, I assume it's incomplete due to the exception:
![image](https://github.com/shap/shap/assets/9136877/0ee36288-fec7-4031-ad3d-8a5c27d87c26)

I'm attaching here the **pickled Explanation object** so you can load it as the MRE. It is the result of explaining a single instance from the dataset:
[waterfall_explanation_error.zip](https://github.com/shap/shap/files/12145774/waterfall_explanation_error.zip)

**I can paint other plots just fine, I've tried a bar plot, a scatter plot, a force plot and a beeswarm plot**

### Minimal Reproducible Example

```python
import shap
import pickle

# load the pickled Explanation object
with open("path_to/waterfall_explanation_error.pkl", "rb") as f:
    explanation = pickle.load(f)

# paint waterfall plot
shap.plots.waterfall(explanation[0])
```

### Expected Behavior

A working waterfall plot.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

shap==0.42.1
scikit-learn==1.3.0

**Comment by connortann** [comment]
Hi Carla, thank you for the bug report!

It would be very helpful to have a minimal reproducible example that doesn't reply on unpicking an object. Are you able to provide a fully self-contained example, perhaps by creating the Explanation object from scratch?

**Comment by CarlaFernandez** [comment]
Hi, thanks for the quick response! This is a minimal reproducible example using the Adult Census Income dataset (and tweaking it to be a regression problem with a OneHotEncoder, just like my real data):

```python
import pandas as pd
import shap
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

# import the data
data, _ = fetch_openml(data_id=1590, return_X_y=True, as_frame=True)
target = data.loc[:, "age"]  # predict the age, just to make the problem a regression

# configuring variables
categorical_cols = ["race", "sex"]
cols_to_drop = ["workclass", "education", "native-country", "education-num", "marital-status", "occupation", "relationship"]
X = data.drop(columns=cols_to_drop) # fewer variables just to make it simpler
y = target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# creating model pipeline
ct = ColumnTransformer(
    [("ohe", OneHotEncoder(handle_unknown="error"), categorical_cols)],
    remainder="passthrough"
)
rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=8, 
    random_state=42
)
pipe = Pipeline([("ct", ct), ("rf", rf)])
pipe = pipe.fit(X_train, y_train)

# extract shap Explanation
fnames_out = pipe.steps[0][1].get_feature_names_out()
feature_names = [f.replace("remainder__", "") if "remainder" in f else f for f in fnames_out]
feature_names = [f.replace("ohe__", "") if "ohe" in f else f for f in feature_names]

explainer = shap.TreeExplainer(pipe.steps[-1][1])
# apply ohe before feeding it to shap
transformed_df = pd.DataFrame(
    pipe.steps[0][1].transform(X),
    columns=feature_names
)
explanation = explainer(transformed_df)
shap.plots.waterfall(explanation[0]) # this line generates the exception
```

**Comment by connortann** [comment]
Thanks! I reduced your example down to a more minimal example that still throws an exception:

```python
import pandas as pd
import shap
from sklearn.ensemble import RandomForestRegressor

X = pd.DataFrame({"A": [1, 2, 3], "B": [2, 1, 3]})
y = pd.Series([1, 2, 3])

model = RandomForestRegressor(n_estimators=2, max_depth=2, random_state=1)
model.fit(X, y)

explainer = shap.TreeExplainer(model)
explanation = explainer(X)

shap.plots.waterfall(explanation[0])  # this line generates the exception
```

**Comment by connortann** [comment]
@thatlittleboy FYI I believe this issue is related to your PR #3121 . It looks like `shap.plots.waterfall` throws an Exception if `Explanation.base_values` has shape `(N,1)`, rather than `(N,)`.

The waterfall plot expect a one-dimensional Explanation object corresponding to a single example, e.g. `explanation[0]`. It expects that `explanation[0].base_values` is a float. In the example above, it's actually an array of length one.

## Propagation of the error

Here's what I think is going on in terms of how the issue propages:

In `_waterfall.py` I think `base_values` is expected to be a float:
https://github.com/shap/shap/blob/6aa2eb50f86d5a039c45b5c0fa1d6dd6f3cb29df/shap/plots/_waterfall.py#L70

`loc` is expected to be a float:
https://github.com/shap/shap/blob/6aa2eb50f86d5a039c45b5c0fa1d6dd6f3cb29df/shap/plots/_waterfall.py#L102

`pos_lefts` should be a list of floats:
https://github.com/shap/shap/blob/6aa2eb50f86d5a039c45b5c0fa1d6dd6f3cb29df/shap/plots/_waterfall.py#L124

Finally, `points` should be a list of floats that can be passed to `np.max`:
https://github.com/shap/shap/blob/6aa2eb50f86d5a039c45b5c0fa1d6dd6f3cb29df/shap/plots/_waterfall.py#L156-L158

All of the types above are wrong if `base_values` is actually an array, and ultimately `np.max` throws an error. 

## Next steps

I'll make a PR #3138 to patch this particular issue in the waterfall plot, by casting `base_values` into a float explicitly. But, I think the fundamental fix of the root cause issue is #3121 .

**Comment by CarlaFernandez** [comment]
I was half expecting it to be related to thatlittleboy's PR. Happy to have it resolved as a hotfix in the meantime, thank you Connor!

**Comment by connortann** [comment]
In the meantime, a workaround could be to do the following:

```python
# Get explanation object as usual
explanation = explainer(....)

# Reshape base_values
explanation.base_values = explanation.base_values.reshape(-1)

# Now plot will work
shap.plots.waterfall(explanation[0])
```
