### ISSUE TITLE
shap 0.25.0 install fails with python 3.5

### ISSUE THREAD

**Issue by imatiach-msft** [shap/shap#315]
Installing the latest 0.25.0 version of shap with python 3.5 fails, the repro steps are:
create a new conda env with python 3.5:
conda create --name test_shap_35 python=3.5
conda activate test_shap_35
pip install shap

See error:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\ilmat\AppData\Local\Continuum\Miniconda3\envs\test_shap_35\include -IC:\Users\ilmat\AppData\Local\Continuum\Miniconda3\envs\test_shap_35\include -Ic:\users\ilmat\appdata\local\temp\pip-install-n30oieo7\shap\.eggs\numpy-1.15.4-py3.5-win-amd64.egg\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /EHsc /Tpshap/_cext.cc /Fobuild\temp.win-amd64-3.5\Release\shap/_cext.obj
  _cext.cc
  shap/_cext.cc(5): fatal error C1083: Cannot open include file: 'tree_shap.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX64\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for shap
  Running setup.py clean for shap
Failed to build shap

**Comment by slundberg** [comment]
That's not good. Appveyor was happy, so I thought we were safe, but I guess not. I won't be able to look at things until later today, but I'll check it out.

**Comment by imatiach-msft** [comment]
@slundberg thanks, we are able to work around the installation issue by pinning to an older version of shap (0.24)

**Comment by slundberg** [comment]
0.25.1 fixes the issue on my end. Let me know if you still have problems on your end. Surprising that it showed up in 0.25 and not 0.24 since I didn't change how the file was bundled.

**Comment by imatiach-msft** [comment]
thanks a lot for the fast response and quick fix, I verified the issue is fixed now
