### ISSUE TITLE
BUG: waterfall plot bug for sklearn RandomForestClassifier

### ISSUE THREAD

**Issue by fountaindive** [shap/shap#3172]
### Issue Description

I think this is a similar bug to https://github.com/shap/shap/issues/3129 (fixed in https://github.com/shap/shap/pull/3138)

When trying to use `shap.plots.waterfall` on a `sklearn.ensemble.RandomForestClassifier` model I get the following error:

```
ValueError: The waterfall plot can currently only plot a single explanation, but a matrix of explanations (shape (2, 2)) was passed! Perhaps try `shap.plots.waterfall(shap_values[0])` or for multi-output models, try `shap.plots.waterfall(shap_values[0, 0])`.
```

Upon examining the output of `explainer(X)` I noticed that the `.values` and `.base_values` potentially have an extra dimension. Could this come from using `model.predict_proba` which outputs two numbers in a binary classification setting, the first is the score for class 0 and the second is the score for class 1?

Thanks for any help!

### Minimal Reproducible Example

```python
import pandas as pd
import shap
from sklearn.ensemble import RandomForestClassifier

X = pd.DataFrame({"A": [1, 2, 3], "B": [2, 1, 3]})
y = pd.Series([1, 0, 0])

model = RandomForestClassifier(n_estimators=2, max_depth=2, random_state=1)
model.fit(X, y)

explainer = shap.TreeExplainer(model)
explanation = explainer(X)

shap.plots.waterfall(explanation[0])  # this line generates the exception
```

### Expected Behavior

The expected behaviour is a waterfall plot.

I was able to produce a waterfall plot if I make the following changes however, I'm not sure this is correct.

```
# code above is the same
explanation = explainer(X)

# two new lines
explanation.values = explanation.values[:,:,0]
explanation.base_values = explanation.base_values[0,1]

shap.plots.waterfall(explanation[0])
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

I have tried this on `0.42.1` and using `master` as of today (1/8/23)

**Comment by znacer** [comment]
Hello,
This is not really a bug. Waterfall plot is intended to plot an explanation (about only 1 row of X) considering only 1 output.
The `explanation` object contains explanations for all of the X rows, and for both outputs (0 or 1). 
A correct way is to select an explanation the following way : 
```py
id_to_explain = 0
output_to_explain = 1
shap.plots.waterfall(explanation[id_to_explain,:,output_to_explain])
```

**Comment by fountaindive** [comment]
Ah I see! Thanks very much!

**Comment by noahaus** [comment]
@znacer you are a GOAT! was trying to get shap working for myself but this was exactly the answer I needed! learned so much from one answer
