### ISSUE TITLE
BUG: Strange base value of exact explainer

### ISSUE THREAD

**Issue by mayer79** [shap/shap#3174]
### Issue Description

I expect the baseline of the exact explainer to equal the average prediction on the background data (masker). However, there are cases where this is not true, see example.

### Minimal Reproducible Example

```python
import numpy as np
import pandas as pd
import shap

n = 101
x = np.arange(n)
X = pd.DataFrame(dict(x1=x, x2=np.flip(x)))
print(X.x1.mean())  # 50
X.head()

def true_model(X):
    return X.x1

ex = shap.Explainer(true_model, masker=X, algorithm="exact")

ps = ex(X[0:3])
ps

# Output
#.values =
#array([[-50.06,   0.  ],
#       [-49.06,   0.  ],
#       [-48.06,   0.  ]])
#
#.base_values =
#array([50.06, 50.06, 50.06])
#
#.data =
#array([[  0, 100],
#       [  1,  99],
#       [  2,  98]])
```

### Expected Behavior

The average of 0, ..., 100 is 50, so I'd expect the baseline to equal 50.

Running above example with `n = 100` gives a baseline of 49.5 (as expected).

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42.1

**Comment by znacer** [comment]
Hi,
This seems to be caused by a hard coded limitation of the `masker` size.
The class handling Tabular maskers has a limitation (`max_samples`) set to 100. Above this limit, only a subsample of the masker dataset is considered.

A possible fix could be to add a property `max_samples` to `Explainer` make it possible for users to tune this limitation.

**Comment by mayer79** [comment]
You are right, it affects even linear explainers.

**Comment by CloseChoice** [comment]
@znacer I implemented your proposal. That sounds like a good approach to me.

**Comment by mayer79** [comment]
Awesome, thanks @znacer and @CloseChoice

**Comment by connortann** [comment]
> Hi, This seems to be caused by a hard coded limitation of the `masker` size. The class handling Tabular maskers has a limitation (`max_samples`) set to 100. Above this limit, only a subsample of the masker dataset is considered.
> 
> A possible fix could be to add a property `max_samples` to `Explainer` make it possible for users to tune this limitation.

The explainer object already accepts a `masker`, so I think it would be preferable to pass in a masker with the desired number of samples rather than expose more `masker` params in the `Explainer` class.

What do you think, would this be acceptable?

```python
ex = shap.Explainer(true_model, masker=maskers.Independent(X, max_samples=1000), algorithm="exact")
```

**Comment by mayer79** [comment]
Good idea, that would be quite elegant, indeed.

**Comment by connortann** [comment]
What do you think @CloseChoice , happy for me to close this issue for now with the approach above as a recommended way to set the masker params?

**Comment by CloseChoice** [comment]
@connortann, that's fine for me
