### ISSUE TITLE
ENH: Make documentation API names to match with there call names

### ISSUE THREAD

**Issue by znacer** [shap/shap#3244]
### Problem Description

Short names are usually use to call SHAP explainers. Those names are defined in the `shap/__init__.py` file : 
```py
from .explainers._additive import Additive as AdditiveExplainer
from .explainers._deep import Deep as DeepExplainer
from .explainers._explainer import Explainer
from .explainers._gpu_tree import GPUTree as GPUTreeExplainer
from .explainers._gradient import Gradient as GradientExplainer
from .explainers._kernel import Kernel as KernelExplainer
from .explainers._linear import Linear as LinearExplainer
from .explainers._partition import Partition as PartitionExplainer
from .explainers._permutation import Permutation as PermutationExplainer
from .explainers._sampling import Sampling as SamplingExplainer
from .explainers._tree import Tree as TreeExplainer
```
In the documentation tree, these names are not mentionned. Making it unclear where is documented the function called by users.

https://shap.readthedocs.io/en/latest/api.html#explanation
https://shap.readthedocs.io/en/latest/api_examples.html#explainers

### Alternative Solutions

I can suggest 2 solutions:
1- add the alias name of a function in the docstring. This would make it more clear and easier when using the search bar.
2- use the alias name in the sidebar tree ?

### Additional Context

I also found that at least `Kernel` and `Gradient` are missing in the documentation.

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [ ] I'd be interested in making a PR to implement this feature

**Comment by connortann** [comment]
Thanks for raising the issue! I think we can do a lot of tidying up.

### Two names for each class

The root issue seems to be that we have two names for each explainer in the current public API. For example, both of these two imports are allowed:

```python
from shap import TreeExplainer  # "long form"
from shap.explainers import Tree  # "short form"
```

To get a sense of the relative freqeuency of use of each form, here are two GitHub searches using regular expressions:
- `/from shap import \w*Explainer\b/` : 388 results
- `/from shap.explainers import/` : 8 results

Whilst this isn't a comprehensive scan of all uses, I think we can confidently conclude that the long form is used a lot more frequently than the short form.

### Next steps

At the very least, we could update the docs to consistently use the long form. I'm happy to take a look.

Moreover, we could also consider dropping the "short form" entirely from the public API, to be more consistent and to avoid confusion. This would be a breaking change, so we'd need to follow a deprecation cycle. That would probably be worth its own issue. @thatlittleboy  @dsgibbons  any thoughts?

**Comment by connortann** [comment]
One of the changes we'd need to make is at the bottom of `conf.py`, to overwrite the `__name__` and `__module__` of each class so that Sphinx uses the long name.

It looks like this was previously done, but the change was reverted a few years ago in [this commit](https://github.com/shap/shap/commit/3c5d8fb656c7e6e7a95825020565b34cc705b80e). I'm unclear why - perhaps that was just a temporary fix?

EDIT: another discrepancy is that these explainers are not available in the top-level namespace with a "long form" name:
```
shap.explainers.other.Coefficient
shap.explainers.other.Random
shap.explainers.other.LimeTabular
shap.explainers.other.Maple
shap.explainers.other.TreeMaple
shap.explainers.other.TreeGain
```

**Comment by dsgibbons** [comment]
> At the very least, we could update the docs to consistently use the long form. I'm happy to take a look.
> 
> Moreover, we could also consider dropping the "short form" entirely from the public API, to be more consistent and to avoid confusion. This would be a breaking change, so we'd need to follow a deprecation cycle. That would probably be worth its own issue. @thatlittleboy @dsgibbons any thoughts?

I agree that the long form should be the default in the docs. I don't have a strong opinion on whether the short form should be deprecated. A smaller API sounds nice but it could be an unnecessary breaking change.

In terms of those other non-long form names like `shap.explainers.other.Coefficent`, why don't we expose a similar long name for each? We can still support the short names but only reference the long names in the documentation. We will then have a consistent API for all explainers. The short-form deprecation issue can probably be delayed until later.

**Comment by connortann** [comment]
That sounds like a good plan, to improve consistency.

I think it might be simpler to rename the classes themselves to the "Long Name", so that Sphinx documentation will render as expected without any workarounds. We could back add in the "short-from" alias in `shap.explainers.__init__.py`, and it will be clear that they are just backwards-compatible aliases.
