### ISSUE TITLE
BUG: print uses for warnings instead of warnings.warn

### ISSUE THREAD

**Issue by znacer** [shap/shap#3252]
### Issue Description

Using DeepExplainer (PyTorch) with an unrecognized module leads to a warning.
This warning cannot be filtred, because it has been written as a print.
https://github.com/shap/shap/blob/e8a176e45a9677cf4faaaddf12cb693a6ee763d9/shap/explainers/_deep/deep_pytorch.py#L220C1-L232C26
### Minimal Reproducible Example

```python
import shap
import torch
import torch.nn as nn
import torch.nn.functional as F
import warnings
warnings.simplefilter("ignore")

class EntMax15(nn.Module):
    def __init__(self, dim=-1):
        super(EntMax15, self).__init__()
        self.dim = dim

    def forward(self, x):
        x_normalized = F.normalize(x, p=2, dim=self.dim)
        return 0.5 * (1 + torch.sign(x_normalized) * torch.sqrt(1 - torch.exp(-2 * x_normalized)))
    
class MyModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(MyModel, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.entmax = EntMax15()  # Use EntMax15 as the activation function

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        x = self.entmax(x)  # Apply EntMax15 activation here
        return x
    
model = MyModel(5,2,1)
deep_expl = shap.DeepExplainer(model, torch.rand((2,5)))
shap_values = deep_expl.shap_values(torch.rand((2,5)))
```

### Traceback

```shell
Warning: unrecognized nn.Module: EntMax15
Warning: unrecognized nn.Module: EntMax15
```

### Expected Behavior

Warnings should be filtered.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [x] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

shap == 0.42.1
python == 3.10.11

**Comment by connortann** [comment]
Thanks for the bug report! A PR to fix this would be welcome. As you say, changing `print` to `warnings.warn` on this line should do the trick:

https://github.com/shap/shap/blob/e8a176e45a9677cf4faaaddf12cb693a6ee763d9/shap/explainers/_deep/deep_pytorch.py#L231
