### ISSUE TITLE
BUG: test_ngboost fails with col_sample < 1

### ISSUE THREAD

**Issue by Penna88** [shap/shap#3261]
### Issue Description

The is a bug in shapley values for NGBoost when col_sample < 1. 
It seems that shapley values excludes some features when col_sample <1 though the the excluded feature is included in trees and has features importance.

![image](https://github.com/shap/shap/assets/46970557/520fadcc-24cc-43e8-9326-faa491018c4d)

model.feature_importances_

array([[7.51157818e-01, 2.93312779e-02, 2.81802693e-02, 0.00000000e+00,
        0.00000000e+00, 1.90468841e-01, 7.64777502e-04, 9.70170090e-05],
       [5.36576961e-01, 9.40885514e-02, 1.57119892e-03, 2.60296105e-02,
        3.21665665e-02, 2.49221611e-01, 4.92869891e-02, 1.10585114e-02]])

### Minimal Reproducible Example

```python
# %%
import shap 
import ngboost as ngb

def test_ngboost():

    X, y = shap.datasets.california(n_points=500)
    model = ngb.NGBRegressor(n_estimators=20, col_sample = 0.9).fit(X, y)
    predicted = model.predict(X)

    # explain the model's predictions using SHAP values
    explainer = shap.TreeExplainer(model, model_output=0)
    
    explanation = explainer(X)
    explanation.base_values = explanation.base_values.reshape(-1)
    # check the properties of Explanation object
    assert explanation.values.shape == (*X.shape,)
    assert explanation.base_values.shape == (len(X),)

    # check that SHAP values sum to model output
    assert (
        np.abs(explanation.values.sum(1) + explanation.base_values - predicted).max()
        < 1e-5
    )

shap.summary_plot(explanation, max_display=30, plot_type="bar")
model.feature_importances_
```

### Traceback

```shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[16], line 1
----> 1 test_ngboost()

\NGBoost_Example\Claim_Severity_ngboost.py in line 14, in test_ngboost()
     64 assert explanation.base_values.shape == (len(X),)
     65 # check that SHAP values sum to model output
     66 assert (
---> 67     np.abs(explanation.values.sum(1) + explanation.base_values - predicted).max()
     68     < 1e-5
     69 )

AssertionError:
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42.1

**Comment by connortann** [comment]
Thanks for the bug report! I can reproduce the error. The cause isn't immediately obvious to me, so any help identifying the underlying issue would be welcome.

**Comment by CloseChoice** [comment]
I would like to take this on. I suspect it has something to do with how the subsampling of the columns works in ngboost and shap does not account for that when fitting the treeensamble

**Comment by CloseChoice** [comment]
I found the problem, which is a dropping of features and reordering of the remaining in `ngboost` if col_sample < 1. I also created a PR where this problem is fixed IF one only uses one estimator. Fixing this for `n` estimators is a bit more difficult. I have an idea on how to do this but would need some guidance from a maintainer.
