### ISSUE TITLE
support for QuantileEstimator for sklearn gradient boosting regressor

### ISSUE THREAD

**Issue by miladclearmetal** [shap/shap#327]
Hi there, awesome package! Any plans to add support for Quantile Estimator for gradient boosting regressor?

**Comment by slundberg** [comment]
Thanks! I don't have any plans right now, but there is no reason I can see not to support it. It would just involve changing the following section to correctly get the base offset and then checking to make sure (with a unit test in test_tree.py) that everything checks out: https://github.com/slundberg/shap/blob/4bd41ea9592475370905eadd47f6b4879eeebf49/shap/explainers/tree.py#L422-L432 

I won't be able to get to it soon, but I'll leave it here as something to do. If anyone wants to send a short PR to add this that would be great!

**Comment by RadoslawB** [comment]
@slundberg  should this issue be closed/resolved? Seems to be implemented https://github.com/slundberg/shap/blob/4bd41ea9592475370905eadd47f6b4879eeebf49/shap/explainers/tree.py#L422-L432
