### ISSUE TITLE
ENH: replace linalg.inv and linalg.pinv by linalg.solve

### ISSUE THREAD

**Issue by lorentzenchr** [shap/shap#3270]
### Problem Description

Some code like https://github.com/shap/shap/blob/master/shap/explainers/_kernel.py#L644-L647 uses the logic
```python
A_inv = np.linalg.inv(A)
x = A_inv @ b
```
instead of the much more stable and (usually) faster
```python
x = np.linalg.solve(A, b)
```

### Additional Context

Originally spotted by @jjerphan.

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [X] I'd be interested in making a PR to implement this feature

**Comment by jjerphan** [comment]
Thank you for reporting it, @lorentzenchr!

I would like to work on this, but I unfortunately have enough contributions to track and to commit to.
