### ISSUE TITLE
BUG: python process crashed due to memory corruption - "malloc(): unsorted double linked list corrupted" when calling TreeExplainer.shap_values()

### ISSUE THREAD

**Issue by bloodlee** [shap/shap#3276]
### Issue Description

Python process was terminated suddenly when calling TreeExplainer.shap_values().
The error message is "malloc(): unsorted double linked list corrupted".

Then I did more testing. The behavior is not stable and hard to reproduce. Sometimes the API can be successfully finished.

Any idea about the root cause. Is there any randomness?

### Minimal Reproducible Example

```python
explainer = shap.TreeExplainer(model=model, data=train_x_.values)
shap_values = explainer.shap_values(X=test_x_.values, check_additivity=False)
```

### Traceback

```shell
No Traceback.
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42.1 and 0.41.0 with Python 3.7.9/3.7.17 under Debian Buster

**Comment by CloseChoice** [comment]
Thanks for the PR bloodlee. Could you provide us with a minimal reproducible example? You just copied the lines, where the error is thrown, but this does not make it reproducible, since executing these lines with a lot of datasets works fine.

**Comment by thatlittleboy** [comment]
I've not seen this error before, the issue is not actionable unless we can reproduce it , unfortunately. I encourage @bloodlee or anyone else encountering this issue to provide instructions to reproduce the problem in a semi-reliable way, along with environment/hardware information, then I promise we'll take a look at it.

**Comment by bloodlee** [comment]
Hi @CloseChoice and @thatlittleboy ,
Thanks for your replies. Later, our team figured the root cause which is in our code. Now, the weird memory issue is gone.
This issue can be closed.
