### ISSUE TITLE
SHAP values don't sum to the predicted value in regression

### ISSUE THREAD

**Issue by ekerazha** [shap/shap#328]
I'm using SHAP with LightGBM (lightgbm mode='rf') for some regressions.

The problem is that SHAP values don't always sum to the predicted value.

Predicted values are all in the 0 - 1000 range.

I have 5 features and for example I get a SHAP value around 0 for 3 features.
Then for the remaining features I have some samples with SHAP values < -15,000

There's no way for the remaining features to compensate a value of -15,000 in order to reach a prediction value in the 0 - 1000 range.

How is that possible? Thank you very much

**Comment by ekerazha** [comment]
@slundberg 

This is another example. Predicted values are in the 0 - 1000 range

How can I get SHAP values of over 100,000 ?

![temp](https://user-images.githubusercontent.com/944048/48495763-f74ea200-e830-11e8-80e2-21a2a3f8658b.png)

**Comment by ekerazha** [comment]
I believe there's a bug when we use LightGBM in Random Forest mode

    boosting_type='rf'

**Comment by slundberg** [comment]
I don't have a unit test for LightGBM in random forest mode, so it is possible something is different there. I'll check and see what I can find.

**Comment by ekerazha** [comment]
@slundberg 

There are not large numbers like with the "random forest" mode, but I have issues also with the default "gbdt" mode.

Example

![temp](https://user-images.githubusercontent.com/944048/48503803-75b43f80-e843-11e8-850b-9a22babc7806.png)

Here predicted values are in the "-1000" to "500" range. How can I have SHAP values near 1400?

**Comment by slundberg** [comment]
That is odd, but if LightGBM is relying on cancelation between features then that could happen.

**Comment by ekerazha** [comment]
@slundberg 

Thank you

Could you add some details about this?

If I have predictions between -1000 and 500, and 2 features (of 3 features) have a SHAP value near zero, I expect the remaining feature to have a SHAP value between -1000 and 500, while here I see a value between -50 and 1400. How should I interpret these values?

**Comment by ekerazha** [comment]
@slundberg 

I tried to change many LightGBM parameters (e.g. `enable_bundle=False` to disable Exclusive Feature Bundling) but without success.

So issues are:

* In Random Forest mode, I get insanely high SHAP values (the more I add trees, the higher they are).
* In GBDT mode (default mode), they show a less absurd scale, but they still don't sum to the predicted value (sometimes it's a value 10x-15x times lower, sometimes it's a value 3x-5x times higher).

In GBDT mode (RF mode gives absurd values), can I at least trust SHAP values on a relative scale (also if they don't sum to the predicted value) or are they (SHAP values generated by LightGBM) totally meaningless values?

Thank you for your help

**Comment by slundberg** [comment]
So I went back and re-ran the LightGBM example notebook and the SHAP values always summed to the raw model output for me, even in RF mode. Could you share what you get from the following line? It should produce a bunch of values that are essentially zero:
`shap_values.sum(1) + explainer.expected_value - model.predict(X, raw_score=True)`

I have not used LightGBM's RF mode before, so I don't know how the loss is computed, but I also get crazy high values from `model.predict(X, raw_score=True)` that make me think they are not in the log-odds space like in gbdt mode. The SHAP values still correctly sum to these larger values, but I would need to dig into LightGBM to check what the output of the trees means in RF mode.

**Comment by ekerazha** [comment]
@slundberg 
Ok, I get zeros. It wasn't clear to me that I had to sum `explainer.expected_value`.

~~About LightGBM's RF values, they are probably related to this issue: https://github.com/Microsoft/LightGBM/issues/1843~~ Probably not

I think I can close this issue. Thank you.

**Comment by ekerazha** [comment]
Well... that LightGBM issue explains why raw scores are not trasformed... still it doesn't explain why raw scores are so high...
