### ISSUE TITLE
ENH: Do not overwrite global warning formatter

### ISSUE THREAD

**Issue by connortann** [shap/shap#3287]
The global warnings formatter is overwritten here:

https://github.com/shap/shap/blob/e51a87db4c9355968524dd6f788f9ec781e81924/shap/explainers/_tree.py#L23

This pattern of overwriting the builtin implementation is actually recommended in the [docs](https://docs.python.org/3/library/warnings.html) of the builtin `warnings` module. However, this kind of import-time side-effect seems inappropriate for a package, as it will interfere with other packages' use of warnings.

A similar case caused issues in the pypdf2 package: https://github.com/py-pdf/pypdf/issues/67

**Comment by seminumber** [comment]
This decision of updating warnings package was very poor and it really hurt our development procedure. Our production code relies on many packages along and use heavily on `warnings` and all of the sudden, we got this issue and nobody could figure that out for about a year until we finally decide to delve into the issue. Our codebase is large and we cannot identify which makes this issue until today :(. I logged in to report this issue but it has already been reported. This issue should be more of a bug than an enhancement in my view.
