### ISSUE TITLE
BUG: waterfall color customisation

### ISSUE THREAD

**Issue by surbhi-gupta-drishya** [shap/shap#3293]
### Issue Description

This issue is same as raised in [here](https://github.com/shap/shap/pull/2807)
With default waterfall function, we are unable to change the color of waterfall plot.
With this implementation all the existing functions will work "as is" with the enhancement of color customization. With this, the users of shap library can change the waterfall plot color as per their wish/requirement.
Earlier they can see waterfall plot in Red and Blue color only:
![image](https://github.com/shap/shap/assets/87317600/fb41b934-fc16-43fb-969c-cf0ad8ed6bc8)

### Minimal Reproducible Example

```python
import pandas as pd
import numpy as np
import lightgbm as lgbm
import shap
temp = pd.DataFrame(np.random.randint(10,100,(100,10)),columns=["x_"+str(i) for i in range(10)])
temp["y"] = np.sum(temp.iloc[:,:8],axis=1) - np.sum(temp.iloc[:,8:],axis=1)

model = lgbm.LGBMRegressor(n_estimators=2, learning_rate=0.1)
X, y =temp.drop(["y"],axis=1), temp[["y"]]
model.fit(X,y )

explainer = shap.TreeExplainer(model)
idx=70
pred = model.predict(X.iloc[idx:idx+1])
shap_values = explainer(X.iloc[idx:idx+1])

shap.plots.waterfall(shap_values[0], max_display=10, show=False)
```

### Expected Behavior

Color of water fall as defined by user.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [x] I'd be interested in making a PR to fix this bug

### Installed Versions

'0.42.1'

**Comment by qzpthuhhu** [comment]
Do you know how to save the images generated by shap.plots.bar or shap.plots.waterfall locally and control the format or dpi?

**Comment by surbhi-gupta-drishya** [comment]
Yes

**Comment by qzpthuhhu** [comment]
Thanks for your reply. My problem has been solved by setting show=False and then plotting it myself.



> 是的
