### ISSUE TITLE
fmap=os.devnul is not needed and breaks on Windows

### ISSUE THREAD

**Issue by KOLANICH** [shap/shap#330]

**Comment by slundberg** [comment]
Working on fixing this one. It is needed to ensure the model parsing works for XGBoost when we extract the trees (since if XGBoost has feature names it uses those instead of feature indexes in the dump without fmap=os.devnull)

**Comment by slundberg** [comment]
The issue is that os.devnull exists on unix but not windows.

**Comment by KOLANICH** [comment]
It is not needed at all, I have removed it and this started working (except the problem with feature names in #331 )

**Comment by KOLANICH** [comment]
It seems we need to change the native API a little.

**Comment by slundberg** [comment]
I think I found a workaround where I force the feature_names attribute to be None during the function call and then restore it afterwards. This has the same effect as passing os.devnull but without the problem that on windows `os.file.exists(os.devnull) == False`.

**Comment by slundberg** [comment]
This is fixed now according to AppVeyor :)
