### ISSUE TITLE
BUG: incomprehensible error message from the explainer

### ISSUE THREAD

**Issue by guillaume-vignal** [shap/shap#3310]
### Issue Description

When I'm in case 1, which is good !shap warned me : 

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_15611/2554636134.py in <module>
----> 1 exp = shap.explainers.Permutation(regressor.predict_proba)

TypeError: __init__() missing 1 required positional argument: 'masker'`

When I'm in the case 2, shap through Explainer still choose the explainer: shap.explainers._permutation.Permutation but didn't warn me that 1 argument is missing. It doesn't crash at this step. It crashed at the second step when we try to retrieve the shap values with an error message difficult to understand.  

### Minimal Reproducible Example

```python
import shap
from sklearn.linear_model import LogisticRegression

regressor = LogisticRegression().fit(Xtrain,ytrain)

if test_case == 1:
    exp = shap.explainers.Permutation(regressor.predict_proba)
elif test_case == 2:
    exp = shap.Explainer(regressor.predict_proba)
    shap_values = exp(Xtest)
```

### Traceback

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_15611/2831618786.py in <module>
----> 1 shap_values = exp(Xtest)

~/.conda/envs/myenv_38/lib/python3.8/site-packages/shap/explainers/_explainer.py in __call__(self, max_evals, main_effects, error_bounds, batch_size, outputs, silent, *args, **kwargs)
    229             feature_names = [[] for _ in range(len(args))]
    230         for row_args in show_progress(zip(*args), num_rows, self.__class__.__name__+" explainer", silent):
--> 231             row_result = self.explain_row(
    232                 *row_args, max_evals=max_evals, main_effects=main_effects, error_bounds=error_bounds,
    233                 batch_size=batch_size, outputs=outputs, silent=silent, **kwargs

~/.conda/envs/myenv_38/lib/python3.8/site-packages/shap/explainers/_permutation.py in explain_row(self, max_evals, main_effects, error_bounds, batch_size, outputs, silent, *row_args)
     87 
     88                 # evaluate the masked model
---> 89                 outputs = fm(masks, batch_size=batch_size)
     90 
     91                 if row_values is None:

~/.conda/envs/myenv_38/lib/python3.8/site-packages/shap/utils/_masked_model.py in __call__(self, masks, batch_size)
     56                 full_masks = np.zeros((int(np.sum(masks >= 0)), self._masker_cols), dtype=np.bool)
     57                 _convert_delta_mask_to_full(masks, full_masks)
---> 58                 return self._full_masking_call(full_masks, batch_size=batch_size)
     59 
     60         else:

~/.conda/envs/myenv_38/lib/python3.8/site-packages/shap/utils/_masked_model.py in _full_masking_call(self, masks, batch_size)
     85                 masked_inputs = self.masker(delta_ind, *self.args).copy()
     86             else:
---> 87                 masked_inputs = self.masker(mask, *self.args)
     88 
     89             # wrap the masked inputs if they are not already in a tuple

TypeError: 'NoneType' object is not callable
```

### Expected Behavior

So I would expect in this case that using shap.explainers.Permutation or shap.Explainer I would have the same error message at same step:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_15611/2554636134.py in <module>
----> 1 exp = shap.explainers.Permutation(regressor.predict_proba)

TypeError: __init__() missing 1 required positional argument: 'masker'`

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

v0.42.1

**Comment by phongtheha-massmutual** [comment]
I think you need to pass masker=X_train in the shap_values step

**Comment by phongtheha** [comment]
I think you need to pass masker=X_train in the argument for shap_values = exp(Xtest)

**Comment by phongtheha** [comment]
I think you need to pass something to the masker argument in shap.Explainer, for example, `exp = shap.Explainer(regressor.predict_proba, masker = X_train).`
Here are some of their example notebooks:
https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/linear_models/Explaining%20a%20model%20that%20uses%20standardized%20features.html
https://shap.readthedocs.io/en/latest/example_notebooks/tabular_examples/model_agnostic/Iris%20classification%20with%20scikit-learn.html

The generic shap.Explainer did not throw an error at first because it is a generic wrapper for all explainers, and not all of them require a masker (e.g. TreeExplainer). If you look into the _explainer.py, the default for masker is None, which would cause an error if the algorithm decides the PermutationExplainer is the best one for the task

p/s: Feel free to correct me if anything I said above is not true :)

**Comment by guillaume-vignal** [comment]
Yes it's totally true, in my case I have to give a masker.
But it takes me time to understand what was wrong due to the fact that the generic shap.Explainer did not throw an error even if it chose PermutationExplainer, this is the problem.
