### ISSUE TITLE
BUG: XGboost binary format is being deprecated

### ISSUE THREAD

**Issue by thatlittleboy** [shap/shap#3321]
### Issue Description

Based on the roadmap here https://github.com/dmlc/xgboost/issues/7547,
the binary format for storing xgboost models is going to be deprecated in xgboost v2.2, when saving to raw format is no longer supported.

We currently rely on this in our `XGBTreeModelLoader` to load in xgboost models to our TreeExplainer.

Warnings are already starting to show up in our test logs,

![image](https://github.com/shap/shap/assets/30731072/f62da53d-7143-44fa-9766-c1a4170d3469)

so I think we need to prioritize this over the next couple of months. It's not clear when v2.2 will be released (xgb is on v2.0 as of time of writing the issue), if it does release before this issue is resolved, then we'll need to set an upper bound on the xgboost version we support.

(If anyone is interested in tackling this, feel free to holler, so we can assign the issue appropriately.)
The change required doesn't look trivial, though.

### Minimal Reproducible Example

```python
N.A.
```

### Traceback

```shell
N.A.
```

### Expected Behavior

N.A.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

master

**Comment by CloseChoice** [comment]
I looked into this a bit and would suggest the following procedure:
 1. write tests for the XGBTreeModelLoader
 2. implement loading with json format and make sure all tests pass

Note that taking on this issue means rewriting major chunks of the XGBTreeModelLoader

**Comment by CloseChoice** [comment]
I would like to tackle this. My plan would be to move to json, check if everything works correctly and file a draft PR and then we can discuss if we move to ubj if the performance decreased too much.

**Comment by thatlittleboy** [comment]
Thanks, much appreciated @CloseChoice

**Comment by CloseChoice** [comment]
I've got a branch with conversion to json that passes all tests but as [one of the comments](https://github.com/shap/shap/blob/master/shap/explainers/_tree.py#L1670C8-L1671) and my investigation show, json is somehow less precise and using ubj would probably be better. I will check that and file a PR once I consider it ready
