### ISSUE TITLE
BUG: ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.

### ISSUE THREAD

**Issue by gro1m** [shap/shap#3327]
### Issue Description

I get an import error, because on Databricks environment numpy==1.21.5 is installed.
As the shapley package installs numba, which depends on numpy, there should be a version constraint on numpy>1.21.

### Minimal Reproducible Example

```python
see description.
```

### Traceback

```shell
ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.
```

### Expected Behavior

No Import error

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [x] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.43.0

**Comment by CloseChoice** [comment]
To fix the problem on your environment you could just install an older numba version which works with numpy 1.21.

**Comment by gro1m** [comment]
@CloseChoice I do not want to do this, because numba gets installed by this library and then I would need to downgrade, although I do not use it elsewhere. But numpy I do. So I pinned numpy to 1.25.2. Still I think it would be good if the shap library could consider this version constraint, because it led to quite some transient behaviour: sometimes notebook execution, sometimes not.

**Comment by CloseChoice** [comment]
But that would break for people who use older versions of numpy. As shap is a library that has a lot of dependencies I think it is not suitable to define all versions of the dependencies but to let the users choose with what version combinations they want to work.

**Comment by gro1m** [comment]
Ok, so that means there are too many constraints for numpy x numba, so that they cannot be specified explicitly by the shap library

**Comment by connortann** [comment]
It looks like you have installed incompatible versions of numpy and numba. This is an issue with your local environment and package manager (pip or conda).  This doesn't seem like an issue with SHAP.

It is up to numba to specify its supported versions of numpy. Other packages that use numba do not have to repeat this information: it is out of scope for us to specify _transitive_ dependency constraints. That information is already available to package managers (pip or conda) when they solve for an environment. So, I'll close this issue as not planned.
