### ISSUE TITLE
AdaBoost Support

### ISSUE THREAD

**Issue by DNCoelho** [shap/shap#335]
Hello,

First of all, thank you very much for developing this amazing tool.

I just wanted to ask if there was any plans to add support to AdaBoost as the title implies.
Or if support is not planned and this is not a too great pain in the ass a quick explanation of how one could go about adding it.

Many thanks in advance.

**Comment by slundberg** [comment]
Thanks! I don't have plans to add support, but it shouldn't be too hard. TreeExplainer creates a TreeEnsemble object from whatever model type we are trying to explain, and then works with that downstream. So all you would need to do is and add another if statement in the TreeEnsemble constructor similar to the one for gradient boosting: https://github.com/slundberg/shap/blob/4bd41ea9592475370905eadd47f6b4879eeebf49/shap/explainers/tree.py#L433-L443

If you have specific questions let me know and I'll be happy to help.

**Comment by DNCoelho** [comment]
Tank you for the quick response!

**Comment by maxencebrochard** [comment]
Hi @DNCoelho,

Did you manage to implement Adaboost? If so, would be very interested :) 

Thanks

**Comment by hdnh2006** [comment]
I left an answer in this [link](https://stackoverflow.com/questions/60433389/how-to-calculate-shap-values-for-adaboost-model/61108156#61108156) that surely could help.

**Comment by slundberg** [comment]
@hdnh2006 if you added support for AdaBoost to your version please consider a PR :)

**Comment by M-Schreurs** [comment]
Since @hdnh2006 solution in the comments [here](https://stackoverflow.com/questions/60433389/how-to-calculate-shap-values-for-adaboost-model/61108156#61108156), the shap module has updated again.
Does someone know how to modify it to get it running again?

**Comment by tudstudent** [comment]
This has been fully implemented in #4271, which adds `AdaBoostClassifier` (SAMME) support to `TreeExplainer`.

The implementation correctly decomposes AdaBoost's weighted hard votes into per-leaf SHAP-compatible values and adds a new C++ softmax vector transform for the multiclass probability output. Both binary and multiclass are supported with `model_output="raw"` (decision function) and `model_output="predict_proba"` (probabilities), with full SHAP additivity verified in tests.
