### ISSUE TITLE
BUG: TreeExplainer assigns xgboost Dmatrix to Explanation.data

### ISSUE THREAD

**Issue by thatlittleboy** [shap/shap#3357]
### Issue Description

When `TreeExplainer.__call__()` is passed a DMatrix object (from `xgboost`), it gets stored as such in the resultant `Explanation` object in `Explanation.data`, but our `shap.plots` functions usually assumes `Explanation.data` is an array-like, e.g. it should have the `.shape` attribute available.

See example below.

### Minimal Reproducible Example

```python
import numpy as np
import xgboost
import shap

rs = np.random.RandomState(0)
X = rs.normal(size=(100, 7))
y = np.matmul(X, [-2, 1, 3, 5, 2, 20, -5])

# train a model with single tree
Xd = xgboost.DMatrix(X, label=y)
model = xgboost.train({'eta': 1, 'max_depth': 6, 'base_score': 0, "lambda": 0}, Xd, 1)

explainer = shap.TreeExplainer(model)
explanation = explainer(Xd)

print(explanation.data)  # <xgboost.core.DMatrix at 0x136020940>
shap.plots.beeswarm(explanation)  # AttributeError: 'DMatrix' object has no attribute 'shape'
```

### Traceback

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[21], line 13
     10 explanation = explainer(Xd)
     12 print(explanation.data)  # <xgboost.core.DMatrix at 0x136020940>
---> 13 shap.plots.beeswarm(explanation)

File ~/Documents/xxx/shap/plots/_beeswarm.py:134, in beeswarm(shap_values, max_display, order, clustering, cluster_threshold, color, axis_color, alpha, show, log_scale, color_bar, plot_size, color_bar_label)
    132         feature_names = features
    133     features = None
--> 134 elif (features is not None) and len(features.shape) == 1 and feature_names is None:
    135     feature_names = features
    136     features = None

AttributeError: 'DMatrix' object has no attribute 'shape'
```

### Expected Behavior

Expected behaviour is that `beeswarm` (or any other plots) should not fail when passed an `Explanation` object.

The cleaner solution should be ensuring the `Explanation.data` doesn't contain an xgboost dmatrix object , rather than modifying all the plots functions to handle dmatrix properly.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

shap master branch c3f2adb439582501c6d0f7ae65a9c56b9d32ce6c

**Comment by thatlittleboy** [comment]
It's a little more complicated than it seems, since it's not (generally) supported to extract out the data from `DMatrix`. It's been described as a one-way street by others: once you convert the data to DMatrix, you can't extract back out the data.

cf. https://github.com/dmlc/xgboost/issues/422 in 2015:

> Currently we cannot direct extract data matrix from DMatrix, mainly due to DMatrix is a internal data structure that may or maynot sit in memory.

And while since xgboost v1.7, there is now a method to extract out the data, via `DMatrix.get_data()` ([docs](https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.DMatrix.get_data)) into a scipy csr matrix, the docstring clearly mentions:

> Get the predictors from DMatrix as a CSR matrix. This getter is mostly for testing purposes.

So it might not be reliable to rely on this method.

ps: To hammer home the point, you can see the implementation of `DMatrix.get_data()` is not trivial, [LINK](https://github.com/dmlc/xgboost/blob/791de7789b269f43bf989e0af9fb0abc96768edb/python-package/xgboost/core.py#L1157).

---
That said,

I'm proposing that we:

* still go ahead with using `DMatrix.get_data()`, gating this functionality behind xgboost v1.7+ . Since this is the most ergonomic way of obtaining the data we require.
* If the user has a lower version of xgboost < v1.7, we raise a warning that we're unable to convert DMatrix to numpy/scipy array, and that we will set `Explanation.data` to be None. In which case, if the user is using our `shap.plots` API, they need to manually set `explanation.data = X` (where X is a numpy array of the underlying data in the DMatrix. Or they can update their xgboost version.
* And if they don't use our plots API, then it's purely a warning that they can safely ignore.

**Comment by connortann** [comment]
Thanks for the thorough explanation. I think your proposed solution makes sense as a pragmatic solution.
