### ISSUE TITLE
summary_plot not following given class_names order

### ISSUE THREAD

**Issue by johnnytam100** [shap/shap#3382]
### Issue Description

Hi, although `class_names` has been given by `all_class_list_format `

but still the class names order in the summary plot does not follow 1 -> 2 -> 3 -> 4 ->5

![image](https://github.com/shap/shap/assets/51283097/fa02e5aa-cd56-4736-8cd9-a934e7e19d9b)

### Minimal Reproducible Example

```python
!pip install shap
import shap

# SHAP
test_feature_df = test_df.loc[:,'res_density_hull':]
explainer = shap.TreeExplainer(best_model)
shap_values = explainer.shap_values(test_feature_df)

all_class_list_format = [1,2,3,4,5]

plt.close()
plt.figure(figsize=(6,6), dpi=600)
shap.summary_plot(shap_values, test_feature_df, plot_type="bar", class_names=all_class_list_format)        # bar plot
plt.xlabel('mean(|SHAP value|)', fontsize=12)
plt.tight_layout()
plt.savefig(test_path + '/' + best_run + '_SHAP_bar.png')
plt.close()
```

### Traceback

```shell
-
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.43.0

**Comment by Saksham093** [comment]
Thank You for Describing the Issue. I want to contribute to this.
Assign me ... Please @johnnytam100.

**Comment by johnnytam100** [comment]
Hi! How to assign you?

**Comment by connortann** [comment]
I encountered this issue before: I believe the solution is to pass `class_inds = "original"`. Does this work for you?

The parameter is used here to sort the classes:

https://github.com/shap/shap/blob/4fa04f89e00b54ac649a86b755873c953c208e3f/shap/plots/_beeswarm.py#L885-L888

I think the root issue here is that the arguments of `shap.summary_plot` are not documented. I think the reason for that might be this is a legacy plotting function and is not exposed in the [API documention](https://shap.readthedocs.io/en/latest/api.html#plots).  It's a mammoth function that seems to have a lot of duplication with other plotting functions such as bar or violin. 

The plot is imported from here:

https://github.com/shap/shap/blob/4fa04f89e00b54ac649a86b755873c953c208e3f/shap/__init__.py#L43

**Comment by xipq** [comment]
> I encountered this issue before: I believe the solution is to pass `class_inds = "original"`. Does this work for you?
> 
> The parameter is used here to sort the classes:
> 
> https://github.com/shap/shap/blob/4fa04f89e00b54ac649a86b755873c953c208e3f/shap/plots/_beeswarm.py#L885-L888
> 
> I think the root issue here is that the arguments of `shap.summary_plot` are not documented. I think the reason for that might be this is a legacy plotting function and is not exposed in the [API documention](https://shap.readthedocs.io/en/latest/api.html#plots). It's a mammoth function that seems to have a lot of duplication with other plotting functions such as bar or violin.
> 
> The plot is imported from here:
> 
> https://github.com/shap/shap/blob/4fa04f89e00b54ac649a86b755873c953c208e3f/shap/__init__.py#L43

This works well. I just met the same problem and everything solved with passing `class_inds="original"`
