### ISSUE TITLE
I don't understand the simple example for inconsistent feature attribution in the paper

### ISSUE THREAD

**Issue by ihadanny** [shap/shap#34]
![image](https://user-images.githubusercontent.com/953357/36073525-fc7e2cb6-0f3a-11e8-9e40-e281815f3e79.png)

even if I ignore the wrong labels in the left tree, still the expected value in the root is:
100 * 25% + 0 * 25% + 0 * 25% + 0 * 25% = 25
and cough=Y changes it to:
100 * 50% + 0 * 50% = 50
so the output task should assign it 25, and not 50 as written...

thanks again for your patience, Ido

**Comment by ihadanny** [comment]
oh I get it :) I think that the labels of the left tree were supposed to be "Fever" for the root, and "Cough" for the 2 lower nodes, right?

**Comment by slundberg** [comment]
You are right. Sorry for the typo, I will have a new arXiv version of the Tree SHAP paper up soon (a few days) that will be a lot cleaner.

**Comment by slundberg** [comment]
Here is the new arXiv version, it should make the example much clearer. If not let me know :)

https://arxiv.org/abs/1802.03888
