### ISSUE TITLE
DeepExplainer object has no attribute 'expected_value'

### ISSUE THREAD

**Issue by ankit0301** [shap/shap#342]
I am getting this error while plotting force plot in Keras LSTM for IMDB Sentiment Classification notebook

**Comment by slundberg** [comment]
When I run that notebook beginning to end I don't get any errors. Which version of shap are you using?

**Comment by vladmarinescu** [comment]
The error was fixed in this [commit](https://github.com/slundberg/shap/commit/dc189dc7f46dc04d5511269329fe8eb1849f170f#diff-71876371443afe91cbd30bcb7e74ec75) (line 29) but the pip version is not up to date.

**Comment by slundberg** [comment]
Thanks @vlaqtz. I just pushed a new version to pip so this should be resolved.
