### ISSUE TITLE
Video available for Presentations? 

### ISSUE THREAD

**Issue by ShubhamRathi** [shap/shap#344]
I see quite a few presentations given on this topic by the author: https://github.com/slundberg/shap/tree/master/docs/presentations 
Was wondering if any of these presentations have been recorded? 

Please do share if its available.

**Comment by slundberg** [comment]
The only one I am aware of that has been posted online is the NIPS 2017 Presentation video. The talk on SHAP starts at 18:00:
https://www.facebook.com/nipsfoundation/videos/1553537531404147/

**Comment by ShubhamRathi** [comment]
Thank you!

**Comment by ghost** [comment]
@slundberg  YOU HAVE DONE A VERY VERY GOOD JOB!! THANKS!
