### ISSUE TITLE
MAINT: notebooks job intermittently failing on CI

### ISSUE THREAD

**Issue by connortann** [shap/shap#3469]
From thread in #3460:

The new "notebooks" CI job appears to fail intermittently.

Recent failing job on master:
https://github.com/shap/shap/actions/runs/7640505479

EDIT: Interestingly a more recent job on master passes:
https://github.com/shap/shap/actions/runs/7642306906/job/20821620592

_Originally posted by @connortann in https://github.com/shap/shap/issues/3460#issuecomment-1908089105_

@CloseChoice  would you be happy to take a look?

**Comment by connortann** [comment]
If it helps, another recent failed job. It looks like something to do with the selection of the kernel:

https://github.com/shap/shap/actions/runs/7783874220/job/21223249560?pr=3483

**Comment by CloseChoice** [comment]
Is this still an issue? Have you encountered multiple runs with this? I have looked into the documentation a bit, but it does not look like it's super easy to specify the kernel.

**Comment by connortann** [comment]
Unfortunately this still does happen intermittently, maybe about 1 in 10 jobs. You can see the history of runs here:
https://github.com/shap/shap/actions/workflows/run_notebooks.yml

One option might be manually specifying the kernel. Or, perhaps, the job could simply skip if the expected kernel is not present?
