### ISSUE TITLE
Provided model function fails when applied to the provided data set.BUG: 

### ISSUE THREAD

**Issue by liboliba** [shap/shap#3474]
### Issue Description

I'm building a predictive function using Bayesian network bnlearn. I try to build a custom predict function similar to sklearn. The custom predict function does not work. 

As this is a non-standard predict function, any advise would be grateful. Thank you!

### Minimal Reproducible Example

```python
import numpy as np
import pandas as pd
import bnlearn as bn
from sklearn.model_selection import train_test_split

df = bn.import_example()
X=df[["Cloudy","Sprinkler","Rain"]]
y=df["Wet_Grass"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
model = bn.structure_learning.fit(df,root_node='Wet_Grass')

DAG = bn.make_DAG(model)
DAG = bn.parameter_learning.fit(DAG, X_train.join(y_train))
Pout = bn.predict(DAG, X_test.join(y_test), variables=['Wet_Grass'])

import shap
shap.initjs()
def bn_predict(X_test):
  Pout = bn.predict(DAG, X_test.join(y_test), variables=['Wet_Grass'])
  return Pout['p'].to_numpy()
explainer = shap.KernelExplainer(bn_predict,X_test)
```

### Traceback

```shell
Provided model function fails when applied to the provided data set.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-17-bcc432829ff4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 explainer = shap.KernelExplainer(bn_predict,X_test)

2 frames
[<ipython-input-16-ba8e4293ea0f>](https://localhost:8080/#) in bn_predict(X_test)
     17 shap.initjs()
     18 def bn_predict(X_test):
---> 19   Pout = bn.predict(DAG, X_test.join(y_test), variables=['Wet_Grass'])
     20   return Pout['p'].to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'join'
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

The latest

**Comment by CloseChoice** [comment]
Isn't this just a bug in your code? Your error happens before you use any of shap's code. I haven't run the code but I think after the `train_test_split` you are dealing with numpy arrays and not dataframes, so `.join` is not available.

Will close this, since this is not a shap bug.

**Comment by liboliba** [comment]
Apologies but I need to re-open it again. 
Actually the code does run until the shap bit, if you test it. 
The predict function does not go as the standard model.predict structure, rather it works a different structure: X_test.join(y_test) and then the variable of interest to predict. Hence I cannot figure out how shap package support this type of predict function. 
Writing a self-defined wrapper function in this case causes errors. 
Any advise would be grateful, thank you!
