### ISSUE TITLE
If a feature is NaN, the SHAP value is never shown on a dependency plot

### ISSUE THREAD

**Issue by ihopethiswillfi** [shap/shap#348]
For some models that can handle NaNs, such as LightGBM, we'll have SHAP values when a feature is NaN.  These are currently not plotted on a dependency plot.

A solution that I'm thinking of is:
- check whether the X-values are floats.
- if yes, sort these and then convert these to strings just before plotting.  
- Make sure 'nan' is on the far left.  Rename 'nan' to '[missing]'
- Plot it.

**Comment by slundberg** [comment]
Good point. That's a bit of a tricky issue. I am concerned that trying to reformat the xticks might cause problems when people customize them. Perhaps we could use the same gray that gets used in the summary plots for nans and draw them as tick marks on the inside of the left axis? I am not sure if there is a perfect solution here.
