### ISSUE TITLE
BUG: Problem of dimension during KernelExplainer

### ISSUE THREAD

**Issue by alice-petit** [shap/shap#3492]
### Issue Description

tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] and In[1] has different ndims: [144,1000] vs. [1000] [Op:MatMul]
Problem of dimension in the line w = np.linalg.solve(X.T @ WX, WX.T @ y) of the solve function in shap>explainers>kernel.
I have no issue with the previous solve function in shap version : '0.41.0'.

### Minimal Reproducible Example

```python
import shap

explainer = shap.KernelExplainer(model, data, nsamples, silent=True)

explainer.shap_values(data)
```

### Traceback

```shell
shap/explainers/_kernel.py", line 747, in solve
    w = np.linalg.solve(X.T @ WX, WX.T @ y)
tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] and In[1] has different ndims: [144,1000] vs. [1000] [Op:MatMul]
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.44.1

**Comment by connortann** [comment]
Thank you for the bug report. The example above is not reproducible; to allow us to investigate further, please would you provide a minimal reproducible example according to [this guide](https://shap.readthedocs.io/en/latest/contributing.html#writing-helpful-bug-reports)?

**Comment by connortann** [comment]
This could be a regression introduced by #3271

**Comment by alice-petit** [comment]
Yes I think it is exactly that because the only difference between the 2 versions are that :
Old version which work:
        tmp = np.transpose(np.transpose(etmp) * np.transpose(self.kernelWeights))
        etmp_dot = np.dot(np.transpose(tmp), etmp)
        try:
            tmp2 = np.linalg.inv(etmp_dot)
        except np.linalg.LinAlgError:
            tmp2 = np.linalg.pinv(etmp_dot)
New version:
        y = eyAdj2
        X = etmp
        WX = self.kernelWeights[:, None] * X
        try:
            w = np.linalg.solve(X.T @ WX, WX.T @ y)
        except np.linalg.LinAlgError:

**Comment by connortann** [comment]
@alice-petit , just to reiterate my comment above, please could you provide a **fully reproducible** minimal example? We need this to be able to investigate further.

**Comment by yuanx749** [comment]
Ran into the same problem. @connortann 

The cause is that when using tensorflow model, ``y`` is a tf.tensor, and ``WX.T @ y`` does not work.
Convert ``y`` to np.array would fix it. (``X`` and ``WX`` are already np.array).

https://github.com/shap/shap/blob/f6d77f8c1f6a871f86766f3fe2ed23d09c75d1ba/shap/explainers/_kernel.py#L662-L666

A simple reproducible example:
```python
import shap
import tensorflow as tf
from sklearn.datasets import make_classification

X, y = make_classification(100, 6)
model = tf.keras.Sequential([
        tf.keras.layers.Dense(10, input_shape=(6,), activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ])
model.compile(optimizer="adam", loss="binary_crossentropy")
explainer = shap.KernelExplainer(model, X)
shap_values = explainer.shap_values(X[:1])
```
PS: a quick workaround is to use ``explainer = shap.KernelExplainer(model.predict, X)``.

**Comment by connortann** [comment]
Thanks @yuanx749 , much appreciated! I can reproduce the issue, and your proposed fix looks good.
