### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by sbairishal** [shap/shap#35]
Traceback:
IndexError                                Traceback (most recent call last)
<ipython-input-69-bc20dc130a25> in <module>()
----> 1 shap.summary_plot(shap_values,z)

/usr/local/lib/python3.6/site-packages/shap/plots.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot)
    339     if sort:
    340         # order features by the sum of their effect magnitudes
--> 341         feature_order = np.argsort(np.sum(np.abs(shap_values), axis=0)[:-1])
    342         feature_order = feature_order[-min(max_display,len(feature_order)):]
    343     else:

IndexError: invalid index to scalar variable.

**Comment by slundberg** [comment]
A full example would be good, but it looks like you passed a vector instead of a matrix to the summary_plot function. I can add a warning for that

**Comment by Edwin-Xu** [comment]
# same problem！！！！！！！
