### ISSUE TITLE
ENH: Support SeLU activations for Tensorflow DeepExplainer

### ISSUE THREAD

**Issue by CloseChoice** [shap/shap#3502]
### Problem Description

Currently the tensorflow DeepExplainer does not support SeLU activation functions. See this discussion for how to implement it: https://github.com/shap/shap/discussions/3499. A test is also needed.

This might be related to: https://github.com/shap/shap/issues/739

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [X] I'd be interested in making a PR to implement this feature

**Comment by rathorexd** [comment]
is this issue still open can i contribute to it ?
