### ISSUE TITLE
Javascript visualisations are not working in 0.25.2 :  Javascript library not loaded

### ISSUE THREAD

**Issue by MaxwellLZH** [shap/shap#351]
Hi, thanks for the great package!

I wan't able to get the visualization working in jupyter notebook , and I checked the Chrome console it gives the following error:

```
Uncaught SyntaxError: Invalid regular expression: /<(!--|link|noscript|meta|script|style)[ \r\n\t\f\></n.length&&!t.isPropagationStopped();i++)u(t,e,n[i],r[i]);else>]/: Unmatched ')'
    at Object.<anonymous> (<anonymous>:14:82938)
    at n (<anonymous>:1:110)
    at Object.<anonymous> (<anonymous>:6:20386)
    at n (<anonymous>:1:110)
    at Object.<anonymous> (<anonymous>:28:762)
    at n (<anonymous>:1:110)
    at Object.<anonymous> (<anonymous>:28:135121)
    at n (<anonymous>:1:110)
    at Object.<anonymous> (<anonymous>:28:122865)
    at n (<anonymous>:1:110)
```
I'm working with a Windows PC, and using shap version 0.25.2.  Any help will be really appreciated!!

btw, I fixed it by copy pasting the bundle.js from 0.23.0 version. 

Thank you!

**Comment by adam-ah** [comment]
I second this, none of the interactive JS plots is working, they are displaying:
```
Visualization omitted, Javascript library not loaded!
Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security. If you are using JupyterLab this error is because a JupyterLab extension has not yet been written.
```

Jupyter version 5.7.2
```
$ pip list | grep jupy
jupyter                                1.0.0      
jupyter-client                         5.2.3      
jupyter-console                        5.2.0      
jupyter-core                           4.4.0
```

```
$ pip list | grep shap
shap                                   0.25.2 
```

Chrome console screenshot:

<img width="1730" alt="screen shot 2018-12-10 at 3 14 52 pm" src="https://user-images.githubusercontent.com/3745745/49710565-67184700-fc8e-11e8-81f2-bfb3e4f74c88.png">

I'm not sure whether it's Shap or ipython issue?

**Comment by adam-ah** [comment]
Update: it's a Shap issue, installing Shap 0.25.1 solves this and the graph appears. However, the JS errors are still visible on the console, so these two seem to be unrelated: 

```
$ pip install 'shap==0.25.1' --force-reinstall --user
...
$ pip list | grep shap
shap                                   0.25.1
```

<img width="1741" alt="screen shot 2018-12-10 at 3 29 25 pm" src="https://user-images.githubusercontent.com/3745745/49710912-7d270700-fc90-11e8-9c1f-91d717cdf824.png">

@Max1993Liu, it would be better to rename the bug to _"Javascript visualisations are not working in 0.25.2 : Visualization omitted, Javascript library not loaded!"_, as these issues seem unrelated.

**Comment by slundberg** [comment]
@adam-ah would you mind trying master and see if you get same issue?

**Comment by adam-ah** [comment]
@slundberg, happy to but please give me some step-by-step how to do it :)

**Comment by slundberg** [comment]
Ah! Just run `git clone https://github.com/slundberg/shap shap`. Then cd
into the shap directory and do `python setup.py install`

**Comment by underbc** [comment]
I was facing the same issue reported by @adam-ah and confirm that downgrading shap to version 0.25.1 fixes the problem.

Ubuntu 18.04

**Comment by adam-ah** [comment]
@slundberg, it works on 0.26 with last commit being # d5262ff3b5167b5ff728d5b5c58ce8443fd4ecd5

Depending on what other fixes 0.25.2 had, I would recommend pulling that from PIP asap.

*How do I uninstall what setup.py installed now? Halp*

FYI, In jupyter I had to manually add the folder, otherwise it "ImportError: No module named shap" (even though it worked fine on the command line).
```
import sys
sys.path.append('/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shap-0.26.0-py2.7-macosx-10.9-x86_64.egg')
import shap
```

**Comment by slundberg** [comment]
@adam-ah You should be able to just pip uninstall it I think. I have now pushed 0.26.0 to pip so that fixes this issue.

**Comment by jundongq** [comment]
I tried 0.24, 0.26 and 0.25.1 in JupyterLab with Ubuntu 16.04.1 on Google Cloud Platform. It still has the problem `Visualization omitted, Javascript library not loaded!
Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security. If you are using JupyterLab this error is because a JupyterLab extension has not yet been written.`

**Comment by slundberg** [comment]
hmm. Are you just running a Jupyter notebook on a compute instance?

**Comment by jundongq** [comment]
> hmm. Are you just running a Jupyter notebook on a compute instance?

Yes, I am running Jupyter notebook under Jupyterlab on a GCP compute instance. I had no problem with it on my Mac using Jupyter notebook under Jupyterlab.

**Comment by slundberg** [comment]
As long as you are running under the notebook server and not Jupyer lab I
don't know what would cause that. Unless you haven't "trusted" the notebook.

**Comment by thedatadecoder** [comment]
I got a solution for Databricks. You just need to get the HTML out of force_plot and use displayHTML to see the force_plot.
Try this:

force_plot = shap.force_plot(xgb_explainer.expected_value, xgb_shap_values, X_test, matplotlib=False)
shap_html = f"<head>{shap.getjs()}</head><body>{force_plot.html()}</body>"
displayHTML(shap_html)

more info: https://towardsdatascience.com/tutorial-on-displaying-shap-force-plots-in-python-html-4883aeb0ee7c
