### ISSUE TITLE
measure the strength of dependence between two variables using shap value

### ISSUE THREAD

**Issue by ZhouYu44** [shap/shap#354]
I didn't find any answer to this question so just post it here.

Is there any way to measure the dependence strength between two variables? It's like a correlation for linear variables. For example, I want to find the variables with the strongest dependence. This is easily doable by a correlation matrix but I am trying to find a shap value correlation matrix.

Thanks!

**Comment by slundberg** [comment]
I am not sure I understand the question. If you want to find the strongest interaction effects you can look at the SHAP interaction values. If you want to find variables that always have a similar impact on the model output you can just compute the correlation of the SHAP values.
