### ISSUE TITLE
Create a single feature against shap value

### ISSUE THREAD

**Issue by ZhouYu44** [shap/shap#355]
I didn't find a way to do this, but I just want to make a single feature against shap value across all my samples. How should I do it? It's like the dependence_plot but with only one variable. I don't need the two interactions. Something like below. 

Thank you!

![image](https://user-images.githubusercontent.com/37360216/49907974-5fdb6f80-fe2d-11e8-8bf9-4b5ebe9862c1.png)

**Comment by slundberg** [comment]
Ah. Just set `interaction_index=None` for the dependence_plot.

**Comment by ZhouYu44** [comment]
Thank you!
