### ISSUE TITLE
np.nan used as background data

### ISSUE THREAD

**Issue by fl2o** [shap/shap#357]
Hi, 

I want to explain the output of a special type of function.
For this function, "np.nan" values are the toggle off (they represent "we have no information about this feature"). Hence, for the init of KernelExplainer, my data argument is a vector of np.nan.

The issue arises with the "shap_values" method, inside the "varying_groups" function
`num_mismatches = np.sum(np.abs(x_group - self.data.data[:, inds]) > 1e-7)`

float - np.nan = np.nan, 
np.nan > 1e-7 is False, hence
num_mismatches = 0 despite my input is not nan anymore.

I made a dirty hack for my purpose only and the rest works nicely👍 
but it would be nice if you could handle the case of background data being nan properly.

Thanks in advance!

**Comment by slundberg** [comment]
Thanks for pointing that out! I fixed that particular issue, but I didn't test if any other problems come up with using nans.
