### ISSUE TITLE
ENH: Integrate Fasttreeshap speedup into SHAP

### ISSUE THREAD

**Issue by ReinierKoops** [shap/shap#3577]
### Problem Description

Currently, any (significant) speedup for SHAP I'd say is a big win since running the calculations can take quite long. In the case of Tree Explainers there is a package which provides some performance optimizations: https://github.com/linkedin/FastTreeSHAP , however, this package is not up to date with the latest SHAP (which has many bugfixes and so is preferable to be used). 

Is it feasible to integrate the speedups into SHAP, so I will make a PR.

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [X] I'd be interested in making a PR to implement this feature

**Comment by alexisdrakopoulos** [comment]
+1 on this, we saw a 15 - 20x speedup on some 20hr+ long workloads with our boosted models and larger datasets.

**Comment by ReinierKoops** [comment]
The license of the fasttreeshap repo is different from SHAP. I will close this and try update fasttreeshap repo.
