### ISSUE TITLE
BUG: Error using Falcon for text-generation

### ISSUE THREAD

**Issue by dyomed93** [shap/shap#3589]
### Issue Description

I'm trying to use SHAP with Falcon, but this issue comes out

### Minimal Reproducible Example

```python
!pip install shap
!pip install transformer
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    StoppingCriteria,
    StoppingCriteriaList,
    pipeline)
import shap

MODEL_NAME = "tiiuae/falcon-7b-instruct"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME, trust_remote_code=True, load_in_8bit=True, device_map="auto"
)
model = model.eval()

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)



s = ["I enjoy walking with my cute dog"]
gen_dict = dict(
    max_new_tokens=100,
    num_beams=5,
    renormalize_logits=True,
    no_repeat_ngram_size=8,
)


model.config.task_specific_params = dict()
model.config.task_specific_params["text-generation"] = gen_dict
shap_model = shap.models.TeacherForcing(model, tokenizer)

masker = shap.maskers.Text(tokenizer, mask_token="...", collapse_mask_token=True)
explainer = shap.Explainer(shap_model, tokenizer)
shap_values = explainer(s)
```

### Traceback

```shell
Setting `pad_token_id` to `eos_token_id`:11 for open-end generation.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-e22bc7645a11> in <cell line: 23>()
     21 explainer = shap.Explainer(shap_model, tokenizer)
     22 # explainer = shap.Explainer(pipeline)
---> 23 shap_values = explainer(s)

9 frames
/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py in new_forward(*args, **kwargs)
    163                 output = old_forward(*args, **kwargs)
    164         else:
--> 165             output = old_forward(*args, **kwargs)
    166         return module._hf_hook.post_forward(module, output)
    167 

TypeError: FalconForCausalLM.forward() got an unexpected keyword argument 'position_ids'
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

shap == 0.45.0

**Comment by CloseChoice** [comment]
Thanks for the report and the reproducible example, that's amazing. I can reproduce the error and found a fix. The falcon models do not expect the parameters we hand over currently.

**Comment by dyomed93** [comment]
I've tried to use the command 
!pip3 install git+https://github.com/CloseChoice/shap.git
to import shap, then i've installed Falcon and test the code i've used before, but the same error came back again, here is the traceback


FalconForCausalLM(
  (transformer): FalconModel(
    (word_embeddings): Embedding(65024, 4544)
    (h): ModuleList(
      (0-31): 32 x FalconDecoderLayer(
        (self_attention): FalconAttention(
          (maybe_rotary): FalconRotaryEmbedding()
          (query_key_value): Linear8bitLt(in_features=4544, out_features=4672, bias=False)
          (dense): Linear8bitLt(in_features=4544, out_features=4544, bias=False)
          (attention_dropout): Dropout(p=0.0, inplace=False)
        )
        (mlp): FalconMLP(
          (dense_h_to_4h): Linear8bitLt(in_features=4544, out_features=18176, bias=False)
          (act): GELU(approximate='none')
          (dense_4h_to_h): Linear8bitLt(in_features=18176, out_features=4544, bias=False)
        )
        (input_layernorm): LayerNorm((4544,), eps=1e-05, elementwise_affine=True)
      )
    )
    (ln_f): LayerNorm((4544,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=4544, out_features=65024, bias=False)
)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-14-54d52b59f1ca>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 explainer = shap.Explainer(shap_model, tokenizer)
----> 5 shap_values = explainer(s)

9 frames
[/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py](https://localhost:8080/#) in new_forward(*args, **kwargs)
    163                 output = old_forward(*args, **kwargs)
    164         else:
--> 165             output = old_forward(*args, **kwargs)
    166         return module._hf_hook.post_forward(module, output)
    167 

TypeError: FalconForCausalLM.forward() got an unexpected keyword argument 'position_ids'

maybe there is an error in the command pip, i'm using a colab notebook to run this code

**Comment by CloseChoice** [comment]
I think you need to specify the branch:
pip3 install  git+https://github.com/CloseChoice/shap.git@FIX-falcon

**Comment by dyomed93** [comment]
Ok thanks, now it works perfectly!
