### ISSUE TITLE
dependence_plot: scale axis, increase size, ...

### ISSUE THREAD

**Issue by vlavorini** [shap/shap#36]
Hello,

   it's not in documentation, and not in the example, but can we play somehow with the dependence_plot?

Thank you for this wonderful tool!

**Comment by slundberg** [comment]
Glad it's helpful! ...dependence_plot uses matplotlib, so if you pass show=False then you can keep calling matplotlib functions to adjust the figure:

```python
import matplotlib.pylab as pl
shap.dependence_plot("RM", shap_values, X, show=False)
pl.gcf().set_size_inches(12, 5)
pl.show()
```
