### ISSUE TITLE
C header file not found

### ISSUE THREAD

**Issue by agrepravin** [shap/shap#362]
I am trying to install `shap` inside `Python3` virtual environment by while doing so it throws below error.

Any clue what is going on?
<img width="1208" alt="screenshot 2018-12-21 at 5 18 51 pm" src="https://user-images.githubusercontent.com/12726996/50341371-880d5180-0544-11e9-8cfe-b010d32d63ab.png">

**Comment by agrepravin** [comment]
After doing `CFLAGS="-stdlib=libc++" python setup.py install` I am getting below error now. I am on MacOs Mojave.

```gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -stdlib=libc++ -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Users/praveenagre/churn_app/churn/lib/python3.6/site-packages/numpy/core/include -c shap/_cext.cc -o build/temp.macosx-10.6-intel-3.6/shap/_cext.o
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
error: command 'gcc' failed with exit status 1```

**Comment by slundberg** [comment]
The first error is due to a problem where setuputils tries to build with a C compiler and not a C++ one (even though the extension is .cc). The second one I don't know about, but you could also try and install a precompiled version from conda forge: `conda install -c conda-forge shap`

**Comment by thatlittleboy** [comment]
Closing as stale, please try the latest versions and open a new issue (link back to this one) if such problems still exist.
