### ISSUE TITLE
Changing the Additive force graph default grouping

### ISSUE THREAD

**Issue by BoredGeo** [shap/shap#363]
If I want the graph to be plotted by default as "sample order by output value" or by one of the categories and not grouped by similarity (referring to the top pull-down selection menu), how can I specify it in the shap.force_plot() call?
Sorry if this is the wrong place to ask.

**Comment by slundberg** [comment]
I can see how that would be useful, but unfortunately those options are not yet exposed in the python force_plot function call. Doing that would require passing more meta-data to the javascript renderer.
