### ISSUE TITLE
BUG: 'tuple' object has no attribute 'as_list'

### ISSUE THREAD

**Issue by Amirhossein4096** [shap/shap#3645]
### Issue Description

I used shap to interpret my cnn model. When shap tries to get the output shape in its internal function, i get error. **I know it's because of the tensorflow version**, how can I fix this error?
**There isn't problem in tensorflow==2.15.0
Please solve this problem for tensorflow==2.16.1**

### Minimal Reproducible Example

```python
import shap
explainer = shap.DeepExplainer(model=model, data = X_train[0:10])
shap_values = explainer.shap_values(X_test[0:10])
```

### Traceback

```shell
AttributeError
Traceback (most recent call last)
<ipython-input-9-5d9f53dcf3ce> in <cell line: 1>()
----> 1 explainer = shap.DeepExplainer(model=model, data = X_train[0:10])
      2 shap_values = explainer.shap_values(X_test[0:10])
1 frames
/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.
py in __init__(self, model, data, 
session, learning_phase_flags)
    170             self.phi_symbolics = [None]
    171         else:
--> 172             noutputs = self.model_output.shape.as_list()[1]
    173             if noutputs is not None:
    174                 self.phi_symbolics = [None for i in range(noutputs)]

AttributeError: 'tuple' object has no attribute 'as_list'
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

my package versions:
tensorflow==2.16.1
shap==0.45.1

**Comment by CloseChoice** [comment]
Thanks for reporting @Amirhossein4096 . Would you be so kind and provide an example that reproduces the issue? Your code is not complete since we cannot define the model in it. Would be great if you could trim your code down to the minimal steps needed to produce this bug.

**Comment by NanK77** [comment]
I am using same versions of TensorFlow and Shap. With a LSTM model, I've received same error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[51], line 11
      9 background=shap.sample(scaled_train_X,100)
     10 # Create the SHAP DeepExplainer using the model and the reshaped background dataset
---> 11 explainer = shap.DeepExplainer(model, background)
     13 # Calculate SHAP values for the reshaped test set
     14 shap_values = explainer.shap_values(scaled_test_X)

File ~\AppData\Local\anaconda3\Lib\site-packages\shap\explainers\_deep\__init__.py:90, in DeepExplainer.__init__(self, model, data, session, learning_phase_flags)
     87 super().__init__(model, masker)
     89 if framework == 'tensorflow':
---> 90     self.explainer = TFDeep(model, data, session, learning_phase_flags)
     91 elif framework == 'pytorch':
     92     self.explainer = PyTorchDeep(model, data)

File ~\AppData\Local\anaconda3\Lib\site-packages\shap\explainers\_deep\deep_tf.py:172, in TFDeep.__init__(self, model, data, session, learning_phase_flags)
    170     self.phi_symbolics = [None]
    171 else:
--> 172     noutputs = self.model_output.shape.as_list()[1]
    173     if noutputs is not None:
    174         self.phi_symbolics = [None for i in range(noutputs)]

AttributeError: 'tuple' object has no attribute 'as_list'

**Comment by CloseChoice** [comment]
@NanK77 would you be so kind to share code so that we can reproduce the issue? We need a definition of the data (at best a minimal set of row) and code to construct the model.

**Comment by macayla-donegan** [comment]
I'm also running into this issue- I can't really share code that reproduces the issue because I work in health tech, but the inputs to shap.DeepExplainer are a 3 layer model trained in tensorflow:
        simple_nn = Sequential()
        simple_nn.add(Dense(256, activation='relu', input_shape=(len(self.feature_names),)))
        simple_nn.add(Dense(256, activation='relu'))
        simple_nn.add(Dropout(0.2))
        simple_nn.add(Dense(256, activation='relu'))
        simple_nn.add(Dense(1, activation='sigmoid'))

and a dataframe of numerical features with no nans

can someone let me know if they found a workaround for this?

Here's the exact error I'm getting
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[60], line 3
      1 import shap
----> 3 explainer = shap.DeepExplainer(nn_model, X_train)
      4 shap_values = explainer.shap_values(X_test)

File /opt/conda/lib/python3.10/site-packages/shap/explainers/_deep/__init__.py:84, in DeepExplainer.__init__(self, model, data, session, learning_phase_flags)
     81         framework = 'tensorflow'
     83 if framework == 'tensorflow':
---> 84     self.explainer = TFDeep(model, data, session, learning_phase_flags)
     85 elif framework == 'pytorch':
     86     self.explainer = PyTorchDeep(model, data)

File /opt/conda/lib/python3.10/site-packages/shap/explainers/_deep/deep_tf.py:172, in TFDeep.__init__(self, model, data, session, learning_phase_flags)
    170     self.phi_symbolics = [None]
    171 else:
--> 172     noutputs = self.model_output.shape.as_list()[1]
    173     if noutputs is not None:
    174         self.phi_symbolics = [None for i in range(noutputs)]

AttributeError: 'tuple' object has no attribute 'as_list'

**Comment by CloseChoice** [comment]
Sorry, should have known this before, but we currently do not support tensorflow 2.16 right now. See https://github.com/shap/shap/blob/master/pyproject.toml#L74. Will close this here, since support of tf 2.16 and keras 3 is way more complicated than this here. See the mentioned issue #3672
