### ISSUE TITLE
Understanding Keras and TensorFlow Text Classification Outputs

### ISSUE THREAD

**Issue by ukamath** [shap/shap#366]
I have a deep learning model for Text Classification with CNN and multiple layers. I used shap and kernel explainer as given below.

```
import shap
# first 100 training as background
explainer = shap.KernelExplainer(multichannel_multifilter_cnn_model.predict, X_train_seq_trunc[:100])
shap_values = explainer.shap_values(X_test_seq_trunc[:100], nsamples=100)
shap.summary_plot(shap_values, X_test_seq_trunc[:100])

```
Am I using the API right with training as background and testing for explanation?
My Text Sequence has maximum length of 24. Does this mean in the samples, feature 22 and 23 have the highest influence on the model? 

![image](https://user-images.githubusercontent.com/4322740/50375029-293bec80-05c5-11e9-83dc-195f8ef245be.png)

shap.force_plot(explainer.expected_value[0], shap_values[0], X_test_seq_trunc[:100])
Out of three classes, This gives me visualization of first class?

The output shows
<img width="1106" alt="screen shot 2018-12-22 at 8 43 42 am" src="https://user-images.githubusercontent.com/4322740/50375067-cac33e00-05c5-11e9-8229-41f1e114c9c7.png">

How to interpret this model output probabilities with colors? Why is 0.64 thresholds chosen? 
If I select single feature, I get this, what to interpret from this?
<img width="1106" alt="screen shot 2018-12-22 at 8 45 33 am" src="https://user-images.githubusercontent.com/4322740/50375088-14138d80-05c6-11e9-8baa-47407c535891.png">

Thanks! And really appreciate the answers.

**Comment by slundberg** [comment]
Hey! It does look right, though for performance you might consider upping the number of samples to 1000 and just passing a single background reference (like all zeros). I am not sure why 23 and 22 are the most important but that is what that plot implies. The force plot is showing the explanations of the output for the first class and 0.64 is the base rate or expected value of the class 0 over the background set you passed. In the last plot when you only look at feature 23 you get to see just the effect of feature 23 on all the samples (again relative the to the base rate).

**Comment by ukamath** [comment]
@sbrugman thanks for the explanation, appreciate it! I am writing a book on NLP and Speech using Deep Learning and using shap for various "explanations", just giving my context. Few questions still wanted to verify or get answers-
1. In addition to 1000 samples from the training (instead of just 100), add one all zeroes to the background, is that right?
2. What does "blue" and "red" signify in the output values or in the individual feature impact? 
3. Is there any other plot(s) that will give me insight into the model behavior for text analysis? 

My Keras base model looks like 

```
def kim_cnn():
    
    text_seq_input = Input(shape=(MAX_LEN,), dtype='int32')
    text_embedding = Embedding(NB_WORDS+1,
                               GLOVE_DIM,
                               weights=[emb_matrix],
                               trainable=True,
                               input_length=MAX_LEN)(text_seq_input)

    filter_sizes = [3,4,5]
    convs = []
    for filter_size in filter_sizes:
        l_conv = Convolution1D(filters=128, kernel_size=filter_size, padding='same', activation='relu')(text_embedding)
        l_pool = MaxPooling1D(filter_size)(l_conv)
        convs.append(l_pool)

    merge = concatenate(convs, axis=1)
    convolution= Convolution1D(128, 5, activation='relu')(merge)
    pool1= GlobalMaxPooling1D()(convolution)
    dense = Dense(128, activation='relu',name='last_but_one')(pool1)
    out = Dense(3, activation='softmax')(dense)
    model = Model(inputs=[text_seq_input], outputs=out, name ="KimCNN")
    model.summary()
    return model
```

**Comment by slundberg** [comment]
Sorry for the slow reply, and sounds like a great book!

1. Right. I would consider just using a single background reference just for performance.
2. Red just means the value is positive and blue means negative, so the color encodes the sign of the SHAP value.
3. I have not done a lot of Deep NLP work myself, so I think this is an area that could be improved. You might look at https://slundberg.github.io/shap/notebooks/linear_explainer/Sentiment%20Analysis%20with%20Logistic%20Regression.html which just uses summary plots and explores the text examples one at a time for linear regression.

One other note, when using the model agnostic KernelExplainer you should run it more than once to observe the variability and make sure it is small enough (i.e. you have drawn enough samples).
