### ISSUE TITLE
ENH: integrated gradients

### ISSUE THREAD

**Issue by Jason-gsy** [shap/shap#3671]
### Problem Description

I hope to integrate the integration gradient method into shap, so that I can visually see the difference between the expected gradient and the integration gradient, I have tried to rewrite the existing GradientExplainer, but it is too difficult for me, I hope to provide the relevant code for calculating kpm and other metrics with integration gradient in your paper, thank you

### Feature request checklist

- [X] I have checked the issue tracker for duplicate issues.
- [ ] I'd be interested in making a PR to implement this feature

**Comment by CloseChoice** [comment]
There are currently no plans for implementing any alternatives to the current implementation.
