### ISSUE TITLE
BUG: AttributeError: 'tuple' object has no attribute 'as_list' (tensorflow 2.15.0)

### ISSUE THREAD

**Issue by htrier** [shap/shap#3681]
### Issue Description

Hello, I am seeing the same error message reported in the following links:

- [this closed issue](https://github.com/shap/shap/issues/3645): solution here was to use an earlier version of tensorflow, but I was not able to resolve it by downgrading my tensorflow version to 2.15.0
- [Same question on stackoverflow](https://stackoverflow.com/questions/78446157/shap-deepexplainer-error-tuple-object-has-no-attribute-as-list-device) is unanswered

To summarize the issue, I'm trying to use shap to interpret a neural network with `DeepExplainer`. From the docs [here](https://shap-lrjball.readthedocs.io/en/latest/generated/shap.DeepExplainer.html) it seems that when using tensorflow my data input should be np.array. However, calling shap.DeepExplainer(model, X_train) with a tensorflow model and np.array returns the error `AttributeError: 'tuple' object has no attribute 'as_list'`. I'd really appreciate any advice if you have an idea what's going wrong, thanks!

### Minimal Reproducible Example

```python
import numpy as np
import tensorflow as tf
import shap
from tensorflow.keras.layers import (
    LSTM,
    BatchNormalization,
    Bidirectional,
    Dense,
    InputLayer,
)
from tensorflow.keras.models import Sequential
from tensorflow.keras import regularizers


def bidirectional_lstm(
    input_shape, num_outputs: int = 1, layer_args={}, layers=[32, 32, 32]
):
    model = Sequential([InputLayer(input_shape=input_shape)])

    for i, layer_units in enumerate(layers):
        return_seq = False if (i == (len(layers) - 1)) else True
        next_layer = LSTM(
            layer_units, return_sequences=return_seq, name="lstm" + str(i), **layer_args
        )
        model.add(Bidirectional(next_layer, merge_mode="concat"))

    model.add(BatchNormalization())
    model.add(Dense(num_outputs, activation="sigmoid"))
    return model


# Get model
model = bidirectional_lstm(
    input_shape=(100, 10),
    layer_args={
        "dropout": 0.1,
        "activity_regularizer": regularizers.l2(0.1),
    },
    layers=[32, 32, 32],
    num_outputs=1,
)

# Generate training data and call DeepExplainer
X_train = np.random.rand(25, 100, 10)
explainer = shap.DeepExplainer(model, X_train)
```

### Traceback

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 14
     12 # Generate training data and call DeepExplainer
     13 X_train = np.random.rand(25, 100, 10)
---> 14 explainer = shap.DeepExplainer(model, X_train)

File ~/miniconda3/envs/myenv/lib/python3.10/site-packages/shap/explainers/_deep/__init__.py:90, in DeepExplainer.__init__(self, model, data, session, learning_phase_flags)
     87 super().__init__(model, masker)
     89 if framework == 'tensorflow':
---> 90     self.explainer = TFDeep(model, data, session, learning_phase_flags)
     91 elif framework == 'pytorch':
     92     self.explainer = PyTorchDeep(model, data)

File ~/miniconda3/envs/myenv/lib/python3.10/site-packages/shap/explainers/_deep/deep_tf.py:172, in TFDeep.__init__(self, model, data, session, learning_phase_flags)
    170     self.phi_symbolics = [None]
    171 else:
--> 172     noutputs = self.model_output.shape.as_list()[1]
    173     if noutputs is not None:
    174         self.phi_symbolics = [None for i in range(noutputs)]

AttributeError: 'tuple' object has no attribute 'as_list'
```

### Expected Behavior

No error.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

python==3.10.9
shap==0.45.1
tensorflow==2.15.0

**Comment by CloseChoice** [comment]
can't reproduce your issue with the versions you provided:

```python
keras==2.15.0
shap==0.45.1
tensorflow==2.15.0
tensorflow-estimator==2.15.0
tensorflow-io-gcs-filesystem==0.37.0
tf_keras==2.16.0
```
and python 3.10.12 (but this shouldn't be the problem).
Are you sure that you did use tf 2.15? What's your keras version?

**Comment by htrier** [comment]
Great question - I've looked into the keras version and I think that may have indeed been the issue! I think I downgraded tensorflow within an existing conda env without uninstalling and reinstalling keras, potentially resulting in a mismatch...I've created a new conda env and installed the versions you posted in your reply and I'm no longer seeing the error. Thanks for the help and sorry to have taken your time
