### ISSUE TITLE
Installation Issue in MAC

### ISSUE THREAD

**Issue by grbusiness18** [shap/shap#369]
In file included from shap/_cext.cc:5:
    shap/tree_shap.h:8:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command '/usr/local/opt/llvm/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/lk/gzyj3p9j2w30mj4gfb9cs_tm0000gn/T/pip-install-n2fhuso9/shap/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/lk/gzyj3p9j2w30mj4gfb9cs_tm0000gn/T/pip-record-4v8jk8kd/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/lk/gzyj3p9j2w30mj4gfb9cs_tm0000gn/T/pip-install-n2fhuso9/shap/

I always get this issue.. can you help. thanks !!

**Comment by slundberg** [comment]
Does #343 fix the issue?

**Comment by grbusiness18** [comment]
thanks a lot :-) it helps.
