### ISSUE TITLE
Precision of Kernel Explainer

### ISSUE THREAD

**Issue by andi-jo** [shap/shap#370]
Hi, the kernel explainer is exact to my understanding by summing over all terms in Eq 8 from the paper using Theorem 2. That is, it returns the exact Shapley values, if the background sample is representative, all features are independent from each other and no penalisation is used. Is this correct or am I missing some assumptions?

I tested the precision of the kernel explainer for two real world datasets of about 200 and 2000 observations and 10 features in a regression setting using a standard linear regression model and compared it with the analytical Shapley values (linear Shap). I found that subleading feature contributions are not exact and thought this being related to one or more of the above assumptions being violated. Could there be other reasons, like numerical approximations?

Regarding features dependence, can its effect be estimated? Probably using interaction terms to capture at least pairwise dependencies. 

Great work, thanks a lot!

**Comment by slundberg** [comment]
Hey! KernelExplainer converges to the exact solution, but it is only exact if you use enough samples to fully enumerate the space of feature subsets (2^M). It also assumes feature independence, which is not necessarily a bad thing. ...so comparing to LinearExplainer if you use the whole training set as the background and draw more than 1024 samples (if you have less than 10 features), then you should get exactly the same values.

Note that for scalability and consistency `v0.27.0` changes the default of LinearExplainer to assume feature independence. If you use `feature_dependence="correlation"` for LinearExplainer then you will no longer match the results of KernelExplainer.

**Comment by andi-jo** [comment]
Thanks! Would I also expect the same results from the Kernel and Linear explainer for a linear model with independent features if I use X_train.mean(0) as background, because in both cases "excluding" a feature in the sampling process results in a zero contribution from that term?

**Comment by slundberg** [comment]
That's correct. Because of linearity of expectations, you can take the expected value first and save a lot of time :)

**Comment by andi-jo** [comment]
Great, very helpful!
