### ISSUE TITLE
BUG: ImportError when using numpy2

### ISSUE THREAD

**Issue by ZacharieBuisson1** [shap/shap#3700]
### Issue Description

** Context ** 

With the new version of numpy 2.0.0, there is an issue in the initialization of the TreeExplainer. Here is my code : 

** Code ** 
from shap import TreeExplainer
from xgboost import XGBClassifier

model = XGBClassifier()
explainer = TreeExplainer(model=loaded_models.model, model_output="raw")

** Error **

_It returns the following error :_

C extension was not built during install!
[...]
ImportError: numpy.core.multiarray failed to import.

** Patch to solve it quickly **

I needed to downgrade my version of numpy from 2.0.0 to 1.26.4 and it works.

I'll let you check if something is wrong with this new version of numpy.

### Minimal Reproducible Example

```python
from shap import TreeExplainer
from xgboost import XGBClassifier

model = XGBClassifier()
explainer = TreeExplainer(model=loaded_models.model, model_output="raw")
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.45.1

**Comment by CloseChoice** [comment]
I can't reproduce this on master with an ubuntu machine. This also looks more like a numpy problem than a shap issue.

**Comment by CloseChoice** [comment]
we have issues with our test suite on numpy2, see here:
https://github.com/shap/shap/actions/runs/9619331932/job/26535218641

**Comment by CloseChoice** [comment]
we'll track numpy2 compatibility in this issue: #3707, therefore I close this issue
