### ISSUE TITLE
How to get the contribution of each features with a datashape (35087, 15, 103)?

### ISSUE THREAD

**Issue by ghost** [shap/shap#371]
How to deal with the following question : https://stats.stackexchange.com/questions/384830/how-to-get-the-contribution-of-each-features-with-a-datashape-35087-15-103

**Comment by slundberg** [comment]
I posted the answer there, but the basic idea is to use `.flatten()` or `.sum(some_dim)` to get a flat array before trying to use `force_plot`

**Comment by JeremieGauthier** [comment]
Are you up to display a little example how to use it according to the notebook linked in the question?

**Comment by ghost** [comment]
Ok, let me try an attempt. Let me know where I am wrong. 

So initially, I have 103 features and 3 labels. `X_train.shape` is `(35087, 15, 103)` and `X_test.shape` is `(11696, 15, 103)`. 

```
explainer = shap.DeepExplainer(Model.model, X_train[:100])
shap_values = explainer.shap_values(X_test[:10])
```
Here shap_values seems to be a list of three arrays of shape `(10, 15, 103)`.

```
X_test_flatten = X_test.flatten()
shap.summary_plot(shap_values, X_test_flatten, features_names=FEATURES)
```
From there I got the error `*** IndexError: index 40 is out of bounds for axis 0 with size 15`

Could anyone help me to get `summary_plot` with the above information?

**Comment by slundberg** [comment]
In order to use a summary plot you want `X_test_flatten` to be a 2D array (# samples by # features) with the same shape as the `shap_values` array. So I would do
```
X_test_flatten = X_test.reshape(X_test.shape[0], np.prod(X_test.shape[1:]))
shap_values_flatten = shap_values.reshape(shap_values.shape[0], np.prod(shap_values.shape[1:]))

shap.summary_plot(shap_values_flatten, X_test_flatten)
```
