### ISSUE TITLE
```suggestion

### ISSUE THREAD

**Issue by abhirajputnikku7** [shap/shap#3745]
```suggestion
    branches: [ "master" ]
    #Enable manual run
    workflow_dispatch:
```
Would be great if we could trigger this manually

https://user-images.githubusercontent.com/111535958/346664836-249ce5fe-fef2-4936-a1ab-357fe1d810eb.mp4

_Originally posted by @CloseChoice in https://github.com/shap/shap/pull/3696#discussion_r1643831435_

**Comment by connortann** [comment]
It is not clear from the description what this issue is about. If you have a bug report or feature request, please open a new issue and use the corresponding template so that we can understand the issue in more detail.

**Comment by abhirajputnikku7** [comment]
Focus on language Lane image and screen display images sanskrit language lyrics add on Frok
