### ISSUE TITLE
Reasonable Mean Shapley Value Across All Outputs

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#376]
Thanks for the help with #374 . I ran it on a small test set and was able to output shapley values.

I may need help interpreting the values that I got however, maybe related to #118 . 

For ~50 test samples x 300k features input array, I found shapley values for ~50 classes. Giving me a 50 x 50 x 300k shapley output array. I found the means of axis 1 (features) to find the mean shapley values for each feature for each output, leading to 50 outputs x 300k features mean shapley value array.

Then I grabbed the features with the highest shapley values for each output. As a sanity check, I searched for the maximum shapley value out of all the outputs, essentially taking the max of the 50 output x 300k feature array.

Quick question, should I be getting a maximum shapley value of 5.9467686111834765e-05 ? Is this significant, or should I be looking for a higher value? 

If features were of random importance, I'd be expecting a shapley value of order of magnitude 1/300k, though I have not read the mathematics behind shap in detail. But my gut tells me that this value should be higher. Why am I capped by order of magnitude 1e-5?

**Comment by slundberg** [comment]
The attribution values can be both positive and negative, and should be roughly centered if your background dataset is representative of the data you are explaining. So I would always expect the mean to be near 0. If you want the global importance of each feature take the mean absolute value.

**Comment by jlevy44** [comment]
Thanks. I'll go ahead and close this.
