### ISSUE TITLE
BUG: correct "approximate" parameter description in TreeExplainer

### ISSUE THREAD

**Issue by fingoldo** [shap/shap#3764]
### Issue Description

It seems like in the recent version of shap "approximate" parameter in TreeExplainer does nothing.

I tried setting it to both True and False and did not notice any difference in runtime, + outputs were exactly the same.
This is consistent across all possible values of feature_perturbation parameter, be it `interventional` or `tree_path_dependent.`

This experience is not aligned with the docs:

> approximate bool
> Run fast, but only roughly approximate the Tree SHAP values. This runs a method previously proposed by Saabas which only considers a single feature ordering. Take care since this does not have the consistency guarantees of Shapley values and places too much weight on lower splits in the tree.

### Minimal Reproducible Example

```python
for explainer in tqdmu([shap.explainers.TreeExplainer(full_model,X_val,feature_perturbation= "interventional",approximate=False),
                        shap.explainers.TreeExplainer(full_model,X_val,feature_perturbation= "interventional",approximate=True),
                        shap.explainers.TreeExplainer(full_model,feature_perturbation= "tree_path_dependent",approximate=False),
                        shap.explainers.TreeExplainer(full_model,feature_perturbation= "tree_path_dependent",approximate=True),]):
    
    start=timer()
    shap_values=explainer.shap_values(X_val)
    print(timer()-start,shap_values[:5,0])
```

### Traceback

```shell
100%|===================| 9997/9999 [09:10<00:00]        
550.7331977249996 [ 0.00150003  0.00044561  0.00491552 -0.00327678  0.00423344]
100%|===================| 9983/9999 [09:19<00:00]        
559.8140876140023 [ 0.00150003  0.00044561  0.00491552 -0.00327678  0.00423344]

0.7823838650001562 [ 0.00113404  0.00081992  0.0052229  -0.00292402  0.00476501]
0.8053742159972899 [ 0.00113404  0.00081992  0.0052229  -0.00292402  0.00476501]
```

### Expected Behavior

I'd expect timing and shap values to be different.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.46.0

**Comment by CloseChoice** [comment]
Thanks for pointing us to this. The problem is that we are not consistent with this paramater. There are 2 possibilities right now:
 - either you specify the `approximate=True` in the constructor, but then invoke the `__call__` method, e.g.
   ```python
      shap_values = explainer(X_val).values
   ```
- you specify the approximate argument in the shap_values function call, e.g.
   ```python
       shap_values = explainer.shap_values(X_val, approximate=False)
   ```
Here is an example that shows this live in action with the current implementation
```python
from sklearn.tree import DecisionTreeRegressor
import shap
import numpy as np

dtc = DecisionTreeRegressor(max_depth=2)

arr = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target = np.array([0, 0, 0, 80])
dtc.fit(arr, target)

exp_approx = shap.explainers.TreeExplainer(dtc, approximate=True)
explanations_approx_call = exp_approx(arr)
explanations_approx_shap_values = exp_approx.shap_values(arr, approximate=True)

assert np.allclose(explanations_approx_call.values, explanations_approx_shap_values)

exp = shap.explainers.TreeExplainer(dtc, approximate=False)
explanations_shap_values = exp.shap_values(arr, approximate=False)  
explanations_call_approx = exp(arr)  
assert np.allclose(explanations_shap_values, explanations_call_approx.values)
```

**Comment by fingoldo** [comment]
> Thanks for pointing us to this. The problem is that we are not consistent with this paramater. There are 2 possibilities right now:
> 
> * either you specify the `approximate=True` in the constructor, but then invoke the `__call__` method, e.g.
>   ```python
>      shap_values = explainer(X_val).values
>   ```
> * you specify the approximate argument in the shap_values function call, e.g.
>   ```python
>       shap_values = explainer.shap_values(X_val, approximate=False)
>   ```
> 
> Here is an example that shows this life in action with the current implementation
> 
> ```python
> from sklearn.tree import DecisionTreeRegressor
> import shap
> import numpy as np
> 
> dtc = DecisionTreeRegressor(max_depth=2)
> 
> arr = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
> target = np.array([0, 0, 0, 80])
> dtc.fit(arr, target)
> 
> exp_approx = shap.explainers.TreeExplainer(dtc, approximate=True)
> explanations_approx_call = exp_approx(arr)
> explanations_approx_shap_values = exp_approx.shap_values(arr, approximate=True)
> 
> assert np.allclose(explanations_approx_call.values, explanations_approx_shap_values)
> 
> exp = shap.explainers.TreeExplainer(dtc, approximate=False)
> explanations_shap_values = exp.shap_values(arr, approximate=False)  
> explanations_call_approx = exp(arr)  
> assert np.allclose(explanations_shap_values, explanations_call_approx.values)
> ```

Oh. I did not know the first version works. Somehow I saw no difference in my testing. Maybe the docs can be updated that it works both ways, to avoid future confusion?

**Comment by CloseChoice** [comment]
I didn't know this either and totally forgot that you would like to contribute a PR fixing this, so that I just created one myself which deprecates the parameter in the `shap_values`.
Since you are interested in contributing, would you be interested in other issues? We can support you in case of questions or if a discussion is needed.

**Comment by fingoldo** [comment]
> I didn't know this either and totally forgot that you would like to contribute a PR fixing this, so that I just created one myself which deprecates the parameter in the `shap_values`. Since you are interested in contributing, would you be interested in other issues? We can support you in case of questions or if a discussion is needed.

Thanks! Well. I have also noticed that GPUTree explainer basically [does not work](https://github.com/shap/shap/issues/3765), but I lack technical expertise in that particular field to contribute (
