### ISSUE TITLE
saving force_plot to html

### ISSUE THREAD

**Issue by mkaldoss** [shap/shap#377]
I am trying to save the output of force plot to html file so I can send it to someone who will be able to display it in a browser. is there anyway to do that?

**Comment by slundberg** [comment]
The easiest way would be to export the whole notebook as html.

**Comment by mkaldoss** [comment]
thanks, I'm trying to visualize the training set predictions and then save as html in a folder so another service can read the html file and render the plot. is that possible currently? I have tried many ways without luck

**Comment by suresk** [comment]
The way I have made this work is like this:

1. Grab the bundle.js from the project and include it in your page.
2. Output the shap_values and the explained_value from the explainer and plug them into the following JavaScript:

```
<div id='shap_plot'></div>
<script>
if (window.SHAP) SHAP.ReactDom.render(
SHAP.React.createElement(SHAP.AdditiveForceVisualizer, {"outNames": ["output value"], "baseValue": <explainer.expected_value>, "outValue": <predicted_value>, "link": "identity", "featureNames": ["foo"], "features": {"0": {"effect": 0.2812443847232262, "value": 512.0}}, "plot_cmap": "RdBu", "labelMargin": 20}),
document.getElementById('shap_plot')
);
</script>
```

Probably not officially supported and may break in the future, but it seems to work and is fairly easy.

**Comment by PrashantSaikia** [comment]
@slundberg 

> The easiest way would be to export the whole notebook as html.

I tried doing this, where I first plotted the force_plot graph, deleted all the other cells (as I just want the force_plot to be displayed on the browser, nothing else), and saved the notebook as html. But when I opened the downloaded html, it can't display the force_plot:

![image](https://user-images.githubusercontent.com/39755678/55139030-c2077880-516f-11e9-8f5d-014b0aed8e5d.png)

Is there any way by which I can get it to work?

**Comment by PrashantSaikia** [comment]
@suresk @mkaldoss  Scott added a [function](https://github.com/slundberg/shap/blob/master/shap/plots/force.py#L217) to save HTML plots [on 25 Jan](https://github.com/slundberg/shap/issues/3#ref-commit-668f2e5).

**Comment by vaibhavkumar049** [comment]
Hi, Is there any update on this Issue, 
I am trying to implement a REST API where we will give some input and the output of shap.force_plot() will be displayed in the front end , I was thinking to convert the graph into some image and then show it in front end
