### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by lilly-chen** [shap/shap#381]
Hi,

when i import shap, it shows me the error of numpy.core.multiarray failed to import

and when I ran "shap_values = shap.TreeExplainer(model).shap_values(X)", it gets the same error.

I tried to uninstall my numpy and reinstall it, to the latest version, does not seems to work

I also tried import numpy.core.multiarray directly, it does not work either

```
import numpy
import numpy.core.multiarray as multiarray
```

How can I fix this?

Thanks!

**Comment by slundberg** [comment]
Seems like a numpy issue more than a shap issue. Here is a thread where people are trying to fix the same issue when loading TensorFlow: https://github.com/tensorflow/tensorflow/issues/559
