### ISSUE TITLE
ModuleNotFoundError after importing shap

### ISSUE THREAD

**Issue by emahnovets** [shap/shap#382]
HI,

I've faced an issue, when got an error after importing shap module:
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

It works file on my local machine (macOs 10.14.2, python 3.6.5), but fails in docker container (python:3.6-jessie, python 3.6.8)

Steps to reproduce:
```
pip install shap
python -c "import shap" //ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
```

Output of `pip show shap`:
```
Name: shap
Version: 0.27.0
Summary: A unified approach to explain the output of any machine learning model.
Home-page: http://github.com/slundberg/shap
Author: Scott Lundberg
Author-email: slund1@cs.washington.edu
License: MIT
Location: /usr/local/lib/python3.6/site-packages
Requires: tqdm, pandas, ipython, numpy, scipy, matplotlib, scikit-learn
Required-by: 
```

Can anyone take a look?

**Comment by WilliamRaynaut** [comment]
Greetings. I get the exact same thing in a fresh venv with the following versions:
> absl-py==0.6.1
> astor==0.7.1
> backcall==0.1.0
> cycler==0.10.0
> decorator==4.3.0
> gast==0.2.1
> grpcio==1.17.1
> h5py==2.9.0
> ipython==7.2.0
> ipython-genutils==0.2.0
> jedi==0.13.2
> Keras-Applications==1.0.6
> Keras-Preprocessing==1.0.5
> kiwisolver==1.0.1
> Markdown==3.0.1
> matplotlib==3.0.2
> numpy==1.15.4
> pandas==0.23.4
> parso==0.3.1
> pexpect==4.6.0
> pickleshare==0.7.5
> prompt-toolkit==2.0.7
> protobuf==3.6.1
> psycopg2==2.7.6.1
> ptyprocess==0.6.0
> Pygments==2.3.1
> pyparsing==2.3.0
> python-dateutil==2.7.5
> pytz==2018.9
> scikit-learn==0.20.2
> scipy==1.2.0
> shap==0.27.0
> six==1.12.0
> tensorboard==1.12.2
> tensorflow==1.12.0
> termcolor==1.1.0
> tqdm==4.29.0
> traitlets==4.3.2
> wcwidth==0.1.7
> Werkzeug==0.14.1
> xgboost==0.81

Additionally, call to `shap.TreeExplainer` fails with a similar `ImportError: numpy.core.multiarray failed to import`...

In the same venv, simply importing `numpy.core.multiarray` succeeds, but importing `numpy.core._multiarray_umath` fails.

Any help appreciated...

**Comment by emahnovets** [comment]
@WilliamRaynaut  I've just found some dirty hack:
```
pip install shap==0.23.0
pip install -I shap
```
After that it works fine, but it's a hack and we shouldn't use it. ⚠️

**Comment by WilliamRaynaut** [comment]
Thanks !
I just tried it on a new venv though, and I get the exact same ImportErrors...

**Comment by slundberg** [comment]
Is this related to #381 (which seemed to be a general numpy issue)?

You can also always try a conda install.

**Comment by WilliamRaynaut** [comment]
The solution in [#96](https://github.com/slundberg/shap/issues/96#issuecomment-391093666) to install with `pip install git+https://github.com/slundberg/shap.git` solved this for me.

I spotted the message `C extension was not built during install!` at any call to TreeExplainer, which led me to believe that 0.27.0 had a problem with `_cext`. Directly installing 0.27.2 from the git seems to solve the issue.

**Comment by slundberg** [comment]
@WilliamRaynaut I can't think what would have changed since 0.27.0 to fix this, but glad it is working. Just post if it comes back.

**Comment by ghost** [comment]
Had the same issue. Updating Numpy to 1.16 solved it.

**Comment by faizan1990** [comment]
I already have numpy 1.16.4, but I am still getting
`ImportError: No module named 'shap'`

**Comment by slundberg** [comment]
@faizan1990 something probably wen't wrong in the install process. If you see some error message during the install that could help point in the right direction. (you also just try a conda install instead of pip)

**Comment by faizan1990** [comment]
Hi @slundberg, that's correct! I have documented the steps that worked for me:

My environment:
Running Jupyter notebooks in a Linux Docker container over a Mac

Steps to fix the problem:

1. Shell into container (`docker exec -it {container-name} /bin/bash`)
2. Run `pip3 install {missing-package-name}`
3. Restart {container-name}
4. `Shift + Enter` same cell again
5. Kernel should die temporarily. Wait for it to come back
6. `Shift + Enter` same cell again and it should work as expected

All the best!

**Comment by luisaporrasm** [comment]
Hi, I am getting the message: C extension was not built during install!

Any help is appreciated!!!

**Comment by ivan-marroquin** [comment]
Hi,

I have python 3.6.5 64 bits on a windows machine. I installed numpy 1.15.4 and shap 0.34.0. 

When I import shap package, I get this error message:

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During the installation using pip, I got these messages:
Collecting shap==0.34.0
  Using cached https://files.pythonhosted.org/packages/07/81/da8afdb67523f342600c1c2d360ac4e989eb845fbb75b1d29b9f5cf1dc29/shap-0.34.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: tqdm>4.25.0 in c:\temp\python\python_3.6.5\lib\site-packages (from shap==0.34.0)
Requirement already satisfied: pandas in c:\temp\python\python_3.6.5\lib\site-packages (from shap==0.34.0)
Requirement already satisfied: scipy in c:\temp\python\python_3.6.5\lib\site-packages (from shap==0.34.0)
Requirement already satisfied: numpy in c:\temp\python\python_3.6.5\lib\site-packages (from shap==0.34.0)
Requirement already satisfied: scikit-learn in c:\temp\python\python_3.6.5\lib\site-packages (from shap==0.34.0)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\temp\python\python_3.6.5\lib\site-packages (from pandas->shap==0.34.0)
Requirement already satisfied: pytz>=2011k in c:\temp\python\python_3.6.5\lib\site-packages (from pandas->shap==0.34.0)
Requirement already satisfied: six>=1.5 in c:\temp\python\python_3.6.5\lib\site-packages (from python-dateutil>=2.5.0->pandas->shap==0.34.0)
Installing collected packages: shap
Successfully installed shap-0.34.0
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Any suggestions?

Kind regards,

Ivan

**Comment by ivan-marroquin** [comment]
Hi,

I tried the following:  (1) downloaded the zip file and uncompressed it, and (2) run "python setup.py install". 

When I import shap, I don't get the reported numpy error message.

Hope this helps,

Ivan

**Comment by slundberg** [comment]
@ivan-marroquin glad that worked. The first problem looks like an issue with the numpy that was installed, and to debug would need to know the line that caused the error.

**Comment by ivan-marroquin** [comment]
Hi @slundberg . thanks for the quick response. I did the following: (1) Open a DOS window console, (2) run python, and (3) type the command "import shap"

If you need more information, please let me know.

Ivan

**Comment by slundberg** [comment]
My guess is that is was a package issue outside of SHAP.

**Comment by dylanlevine** [comment]
Receiving the same error when installing through Conda and using VScode.

Output of pip show shap:
```
Name: shap
Version: 0.37.0
Summary: A unified approach to explain the output of any machine learning model.
Home-page: http://github.com/slundberg/shap
Author: Scott Lundberg
Author-email: slund1@cs.washington.edu
License: MIT
Location: c:\users\dylan.levine\.conda\envs\mlprojects\lib\site-packages
Requires: numpy, scikit-learn, slicer, scipy, numba, pandas, tqdm
Required-by:
```

Out of conda show:
```
# Name                    Version                   Build  Channel
authlib                   0.15.3             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
brotlipy                  0.7.0           py36h2bbff1b_1003
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py36ha15d459_1    conda-forge
cffi                      1.14.4           py36hcd4344a_0
chardet                   4.0.0           py36haa95532_1003
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyhd3eb1b0_0
cryptography              3.3.1            py36hcd4344a_0
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py36h68aa20f_3    conda-forge
dask-core                 2021.1.1           pyhd8ed1ab_0    conda-forge
decorator                 4.4.2              pyhd3eb1b0_0
freetype                  2.10.4               h546665d_1    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.10               pyhd3eb1b0_0
imageio                   2.9.0                      py_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
ipykernel                 5.3.4            py36h5ca1d4c_0
ipython                   7.16.1           py36h5ca1d4c_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.17.0                   py36_0
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jupyter_client            6.1.7                      py_0
jupyter_core              4.7.0            py36haa95532_0
kiwisolver                1.3.1            py36he95197e_1    conda-forge
libblas                   3.9.0                     7_mkl    conda-forge
libcblas                  3.9.0                     7_mkl    conda-forge
liblapack                 3.9.0                     7_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h62dcd97_0
libtiff                   4.2.0                hc10be44_0    conda-forge
llvmlite                  0.35.0           py36haecd60e_1    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
matplotlib-base           3.3.4            py36h1abdf75_0    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mkl-service               2.3.0            py36h779f372_2    conda-forge
networkx                  2.5                        py_0    conda-forge
numba                     0.52.0           py36he38d939_0    conda-forge
numpy                     1.19.5           py36hd1b969e_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
pandas                    1.1.5            py36he38d939_0    conda-forge
parso                     0.8.1              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.1.0            py36h194931e_1    conda-forge
pip                       20.3.3           py36haa95532_0
prompt-toolkit            3.0.8                      py_0
pycparser                 2.20                       py_2
pygments                  2.7.4              pyhd3eb1b0_0
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py36haa95532_0
python                    3.6.12               h5500b2f_2
python-dateutil           2.8.1              pyhd3eb1b0_0
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py36h6434af4_3    conda-forge
pywin32                   227              py36he774522_1
pyyaml                    5.4.1            py36h68aa20f_0    conda-forge
pyzmq                     20.0.0           py36hd77b12b_1
requests                  2.25.1             pyhd3eb1b0_0
scikit-image              0.16.2           py36he350917_0    conda-forge
scikit-learn              0.24.1           py36h63cef00_0    conda-forge
scipy                     1.5.2            py36h9439919_0
setuptools                52.0.0           py36haa95532_0
shap                      0.37.0           py36he38d939_0    conda-forge
simple-salesforce         1.10.1                     py_1
six                       1.15.0           py36haa95532_0
slicer                    0.0.7              pyhd8ed1ab_0    conda-forge
sqlite                    3.33.0               h2a8f88b_0
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py36h2bbff1b_0
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 4.3.3                    py36_0
urllib3                   1.26.3             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py36haa95532_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.3                ha925a31_3
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.8                h4e2f164_1    conda-forge
```

For anyone running into a similar issue I did realize that when importing directly from python.exe there doesn't appear to be an issue. I have not yet figured out how to solve this with vscode:
```
>>> import shap
>>> import fakemodule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fakemodule'
```

**Comment by NikithaVenkat** [comment]
I have the same issue, shap  0.39.0, Shapely 1.7.1, installed via pip in pycharm terminal and in jupyter lab. But when I import shap, I get ModuleNotFoundError: No module named 'shap'. Any help is appreciated, been stuck at this for long time. my numpy version is > 1.17
PS: windows 10 64-bit

**Comment by Nath9319** [comment]
I get the same error, "C: extension was not... " and "ImportError: numpy.core.multiarray failed...".
I am using shap: 0.38.1, numpy: 1.18.4.

While importing shap, I get this error "runtimeerror: module compiled against api version 0xe but this version of numpy is 0xd"

These errors are only showing up when I try to run in a virtual env, these does not happen during manual execution in Jupyter Notebook. Only happens during containerization(e.g. Docker). 

Any suggestion??

**Comment by maniesh15** [comment]
use conda install shap .....it works fine

**Comment by ajalberd** [comment]
But that doesn't enable GPUTree right?

**Comment by bibinmjose** [comment]
Upgrade numpy to latest version, numpy>=1.21.

**Comment by angelicago** [comment]
I installed each package and it worked: 
tqdm, pandas, ipython, numpy, scipy, matplotlib, scikit-learn
