### ISSUE TITLE
BUG: Setup.py File Contains Python Errors

### ISSUE THREAD

**Issue by JBarsotti** [shap/shap#3823]
### Issue Description

When I try to run `setup.py` I get the following error:

###
  File "setup.py", line 20
    current_system: Version = parse(platform.mac_ver()[0])
                  ^
SyntaxError: invalid syntax
###

### Minimal Reproducible Example

```python
Run from command line:

`python setup.py install --user`
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

The latest version

**Comment by thatlittleboy** [comment]
Hi @JBarsotti , thanks for raising the issue. FYI, calling `python setup.py` directly has been deprecated for some time now, you may read https://setuptools.pypa.io/en/latest/deprecated/commands.html for more information.

Will close this as a won't fix.
