### ISSUE TITLE
BUG: ax Parameter in bar() function of not working

### ISSUE THREAD

**Issue by bspires** [shap/shap#3829]
### Issue Description

The ax parameter in the bar() function of the SHAP library is causing an error, despite being documented in the official SHAP documentation. When the ax parameter is used, the following error is raised:

TypeError: bar() got an unexpected keyword argument 'ax'

![image](https://github.com/user-attachments/assets/7c44857c-6f53-48cc-a970-94a06781e11b)

### Minimal Reproducible Example

```python
explainer = shap.Explainer(base_model)
shap_values = explainer(X_valid[selected_features])

fig, ax = plt.subplots(figsize=(8, 6))
shap.plots.bar(shap_values, max_display=15, ax=ax)
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.44.1

**Comment by thatlittleboy** [comment]
Hi @bspires Please install the latest version of SHAP, which is 0.46.0 as of time of writing. The `ax` parameter is accepted by the bar function since 0.45.0.
