### ISSUE TITLE
Keras LSTM for IMDB Sentiment Classification NoneType error

### ISSUE THREAD

**Issue by edwardjchou** [shap/shap#387]
I'm getting a TypeError: Fetch argument None has invalid type <type 'NoneType'> for the Keras LSTM for IMDB Sentiment Classification notebook (under deep explainer).  The error occurs on the line shap_values = explainer.shap_values(x_test[:10]).

**Comment by slundberg** [comment]
I don't get that error on my system, what version of Keras, TF, etc. do you have?

**Comment by Noohshiny** [comment]
I have keras 2.2.4 and I got the same error for LSTM for IMDB example

**Comment by Noohshiny** [comment]
And tensorflow 2.0

**Comment by forough71** [comment]
I also have this problem. Looks like I can't replicate that example. I have Keras 2.2.5 and Tensorflow 2.20rc2.
