### ISSUE TITLE
Add "good reads" label for highlighting insightful discussions

### ISSUE THREAD

**Issue by jesuinovieira** [shap/shap#3887]
I've noticed that there are many great discussions here in the issues, and I thought it would be helpful to create a "good reads" label. This way, we can easily flag and find insightful conversations for future reference.

**Comment by CloseChoice** [comment]
I appreciate it that you read along and find our discussions helpful. Created the label. Feel free to comment in discussions/issues that you consider a good read so that we can add the label

**Comment by CloseChoice** [comment]
@jesuinovieira thanks for raising this and pointing me towards some "good reads". Will close this issue
