### ISSUE TITLE
'LinearExplainer' object has no attribute 'mean'

### ISSUE THREAD

**Issue by ukamath** [shap/shap#389]
Using twitter sentiments of positive and negatives for text sentiment analysis have the basic code
to create a logistic regression
```
vectorizer = TfidfVectorizer(min_df=10)
X_train = vectorizer.fit_transform(train_text)
X_test = vectorizer.transform(test_text)
model = sklearn.linear_model.LogisticRegression(penalty="l1", C=0.1)
model.fit(X_train, training_labels)
explainer = shap.LinearExplainer(model, X_train, feature_dependence="independent")
shap_values = explainer.shap_values(X_test)
X_test_array = X_test.toarray()
```
I get this error 
AttributeError                            Traceback (most recent call last)
<ipython-input-9-dab24f86a52f> in <module>()
----> 1 explainer = shap.LinearExplainer(model, X_train, feature_dependence="independent")
      2 shap_values = explainer.shap_values(X_test)
      3 X_test_array = X_test.toarray()

~/anaconda3/lib/python3.6/site-packages/shap/explainers/linear.py in __init__(self, model, data, nsamples, feature_dependence)
     71             raise Exception("A background data distribution must be provided!")
     72 
---> 73         self.expected_value = np.dot(self.coef, self.mean) + self.intercept
     74 
     75         self.M = len(self.mean)

AttributeError: 'LinearExplainer' object has no attribute 'mean'

Any clue? 
Cheers

**Comment by slundberg** [comment]
Sorry for the slow reply. I have fixed a few things in there on master, could you see if the following code works for you?:
```
import shap
import sklearn
import numpy as np

X,y = shap.datasets.adult()
model = sklearn.linear_model.LogisticRegression(penalty="l1", C=0.1)
model.fit(X, y)
explainer = shap.LinearExplainer(model, X, feature_dependence="independent")
shap_values = explainer.shap_values(X)
```

**Comment by ukamath** [comment]
Thanks, Scott! I will test this tomorrow.
Also, is there a video or a tutorial of your talk on SHAP available? I want
to show that in a meetup here.
Cheers
Uday

**Comment by slundberg** [comment]
Great. The only videos I am aware of online are from NIPS 2017.

There is the short 2 min overview video: https://www.youtube.com/watch?v=wjd1G5bu_TY

And there is the actual 15 min talk, note that SHAP starts at 18:00:
https://www.facebook.com/nipsfoundation/videos/1553537531404147/

**Comment by ukamath** [comment]
Scott
Get this error when I execute the code

 X,y = shap.datasets.adult()

File
"/Users/udaykamath/anaconda3/lib/python3.6/site-packages/shap/datasets.py",
line 121, in <listcomp>

    data[k] = np.array([rcode[v.strip()] for v in data[k]])

AttributeError: 'float' object has no attribute 'strip'

**Comment by slundberg** [comment]
Strange. That code has been around a while, works for me, and just loads a data frame from https://github.com/slundberg/shap/raw/master/data/adult.data

I just double checked and that file does not have any float values in the Relationship column.

Perhaps your cached verison of the file in `shap/shap/cached_data/adult.data` is changed? Or perhaps your pandas install has some different default setting that is auto converting categories to numbers?

**Comment by ukamath** [comment]
Got the example working. It was an issue with the cached data that got corrupted while downloading. Should I try with Text Data with TFIDF? Using LR?

**Comment by slundberg** [comment]
That would be great. If it still breaks then I can check it out on Monday.

**Comment by ukamath** [comment]
That worked. Will close this!
