### ISSUE TITLE
BUG: Summary bar plot for classification does not work any more?

### ISSUE THREAD

**Issue by johann-petrak** [shap/shap#3894]
### Issue Description

I had code for showing a summary bar plot for a multiclass classification model (see code below). This worked fine and produced the expected output in version 0.43.0 and 0.44.0 and it looked like this:

![shap0 44 0](https://github.com/user-attachments/assets/a3ef8d9c-bb23-4f55-ad47-a1970717a279)

Running exactly the same code in version 0.44.0 or newer produces weird looking outputs:

![shap0 45 0](https://github.com/user-attachments/assets/79f22585-3cb7-492f-a422-cb0a9df63640)

### Minimal Reproducible Example

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import xgboost
import shap
print("shap version", shap.__version__)
df = pd.read_csv('log2.csv')  # https://www.kaggle.com/datasets/tunguz/internet-firewall-data-set?resource=download
y = df["Action"].values
class_names = ['drop', 'allow', 'deny', 'reset-both']
c_indep = list(df.columns)
c_indep.remove("Action")
X = df[c_indep].values
cls = RandomForestClassifier(max_depth=2, random_state=0)
cls.fit(X, y)
explainer = shap.TreeExplainer(cls)
shap_values = explainer.shap_values(X)
shap.summary_plot(shap_values, X, plot_type="bar", class_names= class_names, 
    feature_names = np.array(c_indep))  # a list worked in 0.43.0 but not in 0.44.0 or newer!
```

### Traceback

```shell
No traceback, this produces (to me) odd/wrong results.
```

### Expected Behavior

I would still expect to get the bar plot, but I do get a plot instead which does not make sense to me.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

See above, tried with version 0.43.0, 0.44.0, 0.45.0 and 0.46.0

**Comment by CloseChoice** [comment]
First bad commit: ea3bfc8

**Comment by yueli98** [comment]
May I ask if you have solved this problem? I also want to get this type bar chart, do I need to reduce the version of shap?

**Comment by johann-petrak** [comment]
The only "solution" for me was to go back to version 0.44.0, sadly

**Comment by CloseChoice** [comment]
@yueli98 it's not yet solved, so as of now, yes you need to reduce the shap version.

As a workaround you can do:
```python
shap.summary_plot([shap_values[:, :, i] for i in range(shap_values.shape[2])], 
                                     X, 
                                     plot_type="bar", 
                                     class_names= class_names, 
                                     feature_names = np.array(c_indep)
                                     ) 
```

**Comment by yueli98** [comment]
> The only "solution" for me was to go back to version 0.44.0, sadly



> The only "solution" for me was to go back to version 0.44.0, sadly

Thank you
