### ISSUE TITLE
AssertionError: <class 'keras.wrappers.scikit_learn.KerasClassifier'> is not currently a supported model type!

### ISSUE THREAD

**Issue by shekhart47** [shap/shap#390]
Hi 

I am using " from keras.wrappers.scikit_learn import KerasClassifier " to build my classification model, and when I try to apply shap package to calculate shapley values I get the above error. 

Can you please suggest  a possible solution for this problem, or add support for wrapper functionality.

I'd really appreciate your help here.

Thanks,
Shekhar

**Comment by slundberg** [comment]
KerasClassifier is not yet supported, but if someone is willing to add it for GradientExplainer and/or DeepExplainer that would be great. Adding support would mean looking at the constructors of the TF versions and figuring out the right way to pull out the input and output tensors: https://github.com/slundberg/shap/blob/00631d3f2bf8eb045ca3f3bf0f972b2c796adab6/shap/explainers/gradient.py#L130-L143
