### ISSUE TITLE
BUG: Python 3.12 runs failing

### ISSUE THREAD

**Issue by CloseChoice** [shap/shap#3910]
### Issue Description

I just saw that Python 3.12 pipelines are failing. 

 - [x] Check if this is reproducible
 - [x] Check for dependency issues

### Minimal Reproducible Example

```python
See: https://github.com/shap/shap/actions/runs/11749055613/job/32735088282#step:6:872.
```

### Expected Behavior

should run seemlessly

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

master

**Comment by CloseChoice** [comment]
Looks like an error with catboost, even though catboost seems to support Python 3.12 (see https://github.com/catboost/catboost/issues?q=is%3Aissue+python+3.12+is%3Aclosed).

**Comment by miriamgreis** [comment]
It seems to be related to the following issue on catboost: https://github.com/catboost/catboost/issues/2671
