### ISSUE TITLE
Shap with multiclass

### ISSUE THREAD

**Issue by ClintFeher** [shap/shap#393]
I am trying to use Shap for a multi-class problem. In the code below I generated a data of 1000 rows with 3 classes.
The shap_values function throws an exception:

_Traceback (most recent call last):
  File "C:/Users/clint.f/.PyCharmCE2018.2/config/scratches/scratch.py", line 15, in <module>
    shap_values = explainer.shap_values(X)
  File "C:\Users\clint.f\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\linear.py", line 212, in shap_values
    return np.array(X - self.mean) * self.coef
ValueError: operands could not be broadcast together with shapes (1000,3) (3,3)_ 

How should I use shap in multi-class problems ?

import pandas as pd
import numpy as np
import shap
from sklearn.linear_model import  LogisticRegression

shap.initjs()
X = pd.DataFrame(np.random.rand(1000,3), columns=["A","B","C"])
y = np.random.randint(0, 3, (1000,))
clf = LogisticRegression(penalty="l1", C=0.1)
clf.fit(X,y)
print(clf.predict_proba(X.iloc[0:1]))

explainer = shap.LinearExplainer(clf, X, feature_dependence="independent")
shap_values = explainer.shap_values(X)
shap.force_plot(explainer.expected_value, shap_values[1,:], X.iloc[1,:], show=False)

**Comment by slundberg** [comment]
Sorry that's a bug. I just pushed a fix to a branch, and will merge/release as soon as I can.

Thanks for pointing out the issue!

A full working example is below after the patch: (note the change to the force_plot call)
```
import pandas as pd
import numpy as np
import shap
from sklearn.linear_model import LogisticRegression

shap.initjs()
X = pd.DataFrame(np.random.rand(1000,3), columns=["A","B","C"])
y = np.random.randint(0, 3, (1000,))
clf = LogisticRegression(penalty="l1", C=10.1)
clf.fit(X,y)
print(clf.predict_proba(X.iloc[0:1]))

explainer = shap.LinearExplainer(clf, X, feature_dependence="independent")
shap_values = explainer.shap_values(X)
shap.force_plot(explainer.expected_value[0], shap_values[0][1,:], X.iloc[1,:], show=False)
```

**Comment by ClintFeher** [comment]
Thanks a lot for the prompt response, I really appreciate it.
How can I be updated to when the fix is available?

Have a nice day,
Thanks,
Clint

**Comment by slundberg** [comment]
It's on master now. You can watch the repo for the next release or just clone and use master right now.

**Comment by ClintFeher** [comment]
Thanks a lot,
Have a nice day:)
