### ISSUE TITLE
Regularization in SHAP values estimation

### ISSUE THREAD

**Issue by yramon** [shap/shap#394]
Hi,

I try to use shap for very high-dimensional (thousands of features) and sparse data. As reference value I use zero, as setting the feature to zero means "missing" in my setting. 

I have some questions on SHAP:
1. When I use l1_regularization for setting a maximum amount of features in the explanation, I never get values for SHAP (only zero values). However, when calculating all values (for all features), it works. Can someone explain this and how can I obtain an explanation with few features then?
2. How many samples are recommended to use in a setting with high-dimensional, sparse data?

Many thanks!

**Comment by slundberg** [comment]
Which model type are you using? Very high dimensional problems are challenging for KernelExplainer, but are fine for model specific implementations like LinearExplainer, TreeExplainer, GradientExplainer, etc.

Could you give an example of how you are using the l1_reg? It could be because of the way AIC or BIC works if you are using those. Re-running and observing the variability is the best way to tell if you have used enough samples (but that won't tell you if you have over-regularized).

**Comment by yramon** [comment]
Thanks for your quick response.

I would like to use the model-agnostic version as well as the LinearExplainer for my own research. 

You say it is challenging to use it for high dimensional problems, in what sense? For computing all SHAP values, it didn't take long. Or do you mean there is something wrong with the estimates values then?

I entered a number (l1_reg=10) for ensuring the explanation would contain only 10 shap values, but then it does return non-zero values. When I enter l1_reg=1000 for example, it still doesn't return non-zero values. Only when I don't regularize, it works. In the code (see below), I use 10000 samples, but it was just an arbitrary choice. I am not sure how to pick the right amount of samples.

My code is the following:

Reference_value=np.zeros(np.shape(X_test)[1])
RV=np.reshape(Reference_value,(1,len(Reference_value)))
explainer = shap.KernelExplainer(f, RV, link="identity")
shap_values = explainer.shap_values(X_test_instance, nsamples=10000,l1_reg=10)

Thanks a lot in advance,

Yanou

**Comment by slundberg** [comment]
The issue is that l1_reg=10 does not select the top 10 features, but instead passes an L1 regularization coefficient of 10 to the alpha parameter of sklearn.linear_model.Lasso. When you set a very high regularization then all the values are squished to zero.

The ability to just select the top 10 though does seem important, so I just went and finally implemented it in e14b78a :) If you clone master you can now use l1_reg="rank(10)" to get the effect you want.

**Comment by slundberg** [comment]
found a typo...master will have this option working shortly...

**Comment by haebichanjung** [comment]
Hi Scott, this is a somewhat related but separated question. Is there any way shap plots can connect to categorical variables? I'm using Catboost to avoid one-hot-encoding that'll generate thousands of bloated dimensions, but none of the shap plots can process categorical variables. Is there anyway I can bypass this issue?

**Comment by ClonedOne** [comment]
Hello, I am in the same situation - big, high dimensional (~2k features), dataset and need for model agnostic explainer.
Could you please give some more details on what is the difference between  `l1_reg="rank(10)"`  and `l1_reg='num_features(10)'`  with KernelExplainer?  

On the same model the first option leads to this error:

```
...                                                                                                     
  File "/python3.6/site-packages/shap/explainers/kernel.py", line 407, in explain                                                 
    vphi, vphi_var = self.solve(self.nsamples / self.max_samples, d)                                                                                                       
  File "/python3.6/site-packages/shap/explainers/kernel.py", line 580, in solve                                                   
    nonzero_inds = np.nonzero(Lasso(alpha=self.l1_reg).fit(mask_aug, eyAdj_aug).coef_)[0]                                                                                  
  File "/python3.6/site-packages/sklearn/linear_model/_coordinate_descent.py", line 751, in fit                                   
    check_input=False)                                                                                                                                                     
  File "/python3.6/site-packages/sklearn/linear_model/_coordinate_descent.py", line 454, in enet_path                             
    l1_reg = alpha * l1_ratio * n_samples                                                                                                                                  
TypeError: can't multiply sequence by non-int of type 'float'                                                 
```
while the seconds works. Thanks!
