### ISSUE TITLE
Interpretation on feature impact plot

### ISSUE THREAD

**Issue by YXSIO** [shap/shap#396]
In the following plot, if we look at the LSTAT feature, there is some vertical dispersion.

The value of the feature has already been coded into colors, does the vertical dispersion stand for the count of data points who share the same shap value for that feature?

![image](https://user-images.githubusercontent.com/6912870/51348909-b9504300-1a58-11e9-9fbb-b33ef1a28e08.png)

**Comment by slundberg** [comment]
Yes, that's right. The dots "pile up" to show the density of points along the axis (like a bee-swarm plot).

**Comment by YXSIO** [comment]
Got it. Thanks!
