### ISSUE TITLE
Error when doing shap dependence plot of a single variable

### ISSUE THREAD

**Issue by maxmatical** [shap/shap#398]
The model is a RandomForestClassifier from sklearn, when I try to create the dependence plot from a single value:

`shap.dependence_plot("S", shap_values, x_train)
`

I get the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-edb030e2d89c> in <module>()
----> 1 shap.dependence_plot("S", shap_values, x_train)

/usr/local/lib/python3.6/dist-packages/shap/plots/dependence.py in dependence_plot(ind, shap_values, features, feature_names, display_features, interaction_index, color, axis_color, dot_size, x_jitter, alpha, title, xmin, xmax, show)
     80 
     81     # allow vectors to be passed
---> 82     if len(shap_values.shape) == 1:
     83         shap_values = np.reshape(shap_values, len(shap_values), 1)
     84     if len(features.shape) == 1:

AttributeError: 'list' object has no attribute 'shape'
```

**Comment by slundberg** [comment]
It looks like the model has multiple outputs, which is why shap_values is a list. You have to pick a specific output when making a dependence plot (so shap_values[0] for the first one).

**Comment by maxmatical** [comment]
Is this only the case with a softmax output? So I would do shap_values[0] for class 1, shap_values[2] for class 2 and etc?

**Comment by slundberg** [comment]
That's right. It is most common with the softmax output, but the convention in the shap package is to return a list of explanation arrays whenever the model has multiple outputs.

**Comment by sucheta1794** [comment]
The model is Gaussian Process regressor(), error in plotting SHAP dependence plot:

Code is here-

explainer = shap.Explainer(reg.predict,X_train)
shap_values = explainer.shap_values(X_train)
shap.initjs()

shap.dependence_plot("EN_mean", shap_values[0], X_test)

**Error:** 
TypeError: order must be str, not int
