### ISSUE TITLE
question about 'algorithm' file not found

### ISSUE THREAD

**Issue by yanlele9654** [shap/shap#399]
when i am try to download the shap via pip install shap
I found that I have the following errors
In file included from shap/_cext.cc:5:
    shap/tree_shap.h:8:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1

could any one tell me what should I do

**Comment by dgremmell** [comment]
I am getting this error as well. Any guidance on how to resolve?

**Comment by slundberg** [comment]
See #343

**Comment by dgremmell** [comment]
The solution in #343 is not clear. Are there more detailed instructions for correcting this? The issue of this running in Mac is the issue I am experiencing but it is unclear how to fix.

**Comment by slundberg** [comment]
@dgremmell This impacted lots of packages, and I just found a solution pushed to pandas last month and merged it into master. So master should now work without having to set an env variable and so will v0.28 when it gets tagged.

**Comment by dgremmell** [comment]
Just so everyone knows, I was able to solve this by running conda update pandas since I use anaconda. It solved my environment and was then able to run pip install shap
