### ISSUE TITLE
Adjusting number of features shown

### ISSUE THREAD

**Issue by coulls** [shap/shap#4]
When visualizing a single prediction, it appears as though the IML visualizer decides how many feature names to put in the chart.  It would be great if we had more control over the features shown.  For instance, showing only the top-n features for both the positive and negative direction.

Is it possible to achieve this in the code as it stands or do it require deep changes to IML?

**Comment by slundberg** [comment]
That would not be a huge change, but it will need to be made in the JS code in IML. If it's important to you let me know, and I'll leave it here as a to-do when I get time. (or a PR to IML is also welcome)

**Comment by coulls** [comment]
Thanks!  I do think it would be super helpful.  Our model has nearly 3,000 features, so visualizing the whole range for a single prediction is kind of difficult to read.  I have tried to limit the number of features, though obviously that impacts the predicted score that is displayed, etc.

Something that essentially 'zooms in' on the area around the predicted score would be nice.

**Comment by slundberg** [comment]
Could you attach a quick screen grab of what you are seeing? That would
help me narrow down what will fix the layout issue. Currently the method
tries to prune labels that don't fit on the plot, but that calculation
could be improved.

**Comment by coulls** [comment]
Apologies for the delay in getting back to you.  Attached are two examples of the single prediction visualization using my ~3,000 features.  The predictions are the same sample with the same feature set under two different LightGBM models.

I've anonymized the one displayed feature name, so I hope that doesn't impact anything on your end.

As you can see, there is quite the long-tail of minor contributors in the visualization, so the amount of information that can be retrieved by the viewer at this level of detail is quite low.  It would be nice if there was a 'zoom' functionality that let us focus on the top-N features, or something similar to that.  As I said before, I tried to do this artificially by recreating a truncated SHAP vector, but then the totals are obviously incorrect -- I suppose I could just sum all of the remaining feature contributions up into a single catch-all feature for both sides of the force diagram, but that seems like something that perhaps should be handled under the hood (and certainly not something that will work in general).

Separately, there have been some issues with placement of the names, though I fully realize part of that is due to their length.  In this example, one model's visualization output can only fit a single name and the other didn't place any of the feature names. 

<img width="791" alt="screen shot 2017-10-30 at 10 30 02 pm" src="https://user-images.githubusercontent.com/3245674/32205199-5521f3a2-bdc4-11e7-8b69-f33db8af2c79.png">
<img width="792" alt="screen shot 2017-10-30 at 10 29 51 pm" src="https://user-images.githubusercontent.com/3245674/32205209-60578ade-bdc4-11e7-8f6e-d7d7d76c2652.png">

**Comment by slundberg** [comment]
Thanks for sharing! I'll think about how this should work. I have also used
this with thousands of features, but for our model individual predictions
were usually dominated by only a handful of features so I didn't run into
this issue.
