### ISSUE TITLE
shop value estimations based on the raw X or after preprocessed 

### ISSUE THREAD

**Issue by naarkhoo** [shap/shap#401]
After using pipeline scikit learn I am eager to look into the importance of variable through SHAP eyes

Following is the schematic of the process. I can make a dummy data if needed

```
    pipeline = Pipeline([
        ('reduce_dim', NonNAselector()),
        ('impute', SimpleImputer(missing_values = np.nan, strategy = 'mean')),
        ('normalize', StandardScaler()),
        ('clf', randomforest(random_state = 0)),
        ])
```

I understand the shap values are calculated as following 

`shap_values = explainer.shap_values(x_train)`

I wonder if x_train should be design matrix through all steps except random forest ? or just the raw x_train before the pipeline ? 

I have a lot of NAs and the values can be very large - that is why I need to use imputation as well as normalisation to make the data suitable for further analysis. So the question is 1) should I use the normalised x_train or the raw x_train ? 2) if normalised version are recommended, I wonder if you have suggestion on how to generate it through the pipeline ? (the data ends up without colnames as np array instead of data frame which is required for SHAP). I understand the 2nd question can be out of the scope for this forum. So I appreciate you comments on the first one.

**Comment by slundberg** [comment]
For future reference...
1. All univariate transformations of the inputs don't change the SHAP values. So just explain final model.
2. There is typically no need for normalization or imputation of features when using a Random forest.
