### ISSUE TITLE
shap.summary_plot displaying gray plot

### ISSUE THREAD

**Issue by terryyylim** [shap/shap#406]
![screen shot 2019-01-23 at 8 56 37 pm](https://user-images.githubusercontent.com/25025366/51649259-a4d8e280-1f51-11e9-9a78-3124b47d7fb6.png)

I'm facing this issue where the features are not getting the expected blue and red colors. Does anyone have any idea why this might be so? Thank you!

**Comment by dynamik1703** [comment]
I'm getting a mix of blue, red and grey lately.

Version: 0.18.2

**Comment by slundberg** [comment]
Grey is for NaN feature values (there are never NaN SHAP values), but I would be surprised if your whole dataset is NaN.

**Comment by dynamik1703** [comment]
I checked my feature values. There are no nans included.  Nevertheless, I get grey dots. This is only since the last update with me.

shap==0.28.2
numpy==1.16.0
Win

**Comment by xthomas8888** [comment]
I got similar displays to @dynamik1703 when plotting summary plot using SHAP. Specifically, I checked a feature which has no NaNs in values. But still got a mixture of blue, red and gray dots in the summary plot.

shap==0.28.2
numpy==1.16.0

Thanks,
Thomas

**Comment by dynamik1703** [comment]
I'm not 100% sure but it's probably been happening since I updated numpy to 1.16.0

**Comment by slundberg** [comment]
Thanks for pointing that out! ...it looks like the recent color range update to better plot NaN values in dependence_plots caused the dots outside of the color bar range to be gray in the summary plot. I am working on a fix now...

**Comment by slundberg** [comment]
0.28.3 now has this fixed.

**Comment by xthomas8888** [comment]
Thanks for the fix, @slundberg. Although this is closed, want to follow up with a question: if they are NaN values in the data, will they be marked in gray in the summary_plot? If not, will they be marked in blue (low values) or red(high values)? In my case, I did have NaN in my data, but I didn't see gray color indicated for NaN in summary plot. Thanks for your attention on this!

**Comment by slundberg** [comment]
@xthomas8888 they should be gray. If you have an example where they are not please share it and I can take a look.

**Comment by alvarosalgado** [comment]
Hi,

I know this is a closed issue, but this problem is happening to me and I don't know what might be causing it.
My dataset is a pd.DataFrame containing genomic data (n genomes vs. p nucleotides). The attributes contain categorial values, i.e., "A, C, T or G". Please see screen prints bellow.

![Screen Shot 2019-04-16 at 11 07 00](https://user-images.githubusercontent.com/26483025/56216491-e9978580-6037-11e9-8685-c5a72fd24841.png)
![Screen Shot 2019-04-16 at 11 07 16](https://user-images.githubusercontent.com/26483025/56216506-ee5c3980-6037-11e9-9288-79148f3d5ff2.png)

SHAP version is 0.28.5

Any ideas?
Thanks

**Comment by slundberg** [comment]
@alvarosalgado it is probably because the data is not numeric and so there is no notion of "high" or "low". For the sake of colors you could just convert the data to 0-4 instead of letters before passing it for plotting.

**Comment by alvarosalgado** [comment]
Problem solved, thanks for the reply!
And thank you for the amazing tool.

**Comment by ralanburnett** [comment]
I have a similar issue.  The output of shap.summary_plot(shap_values, X) is

<img width="501" alt="Shap Catboost example" src="https://user-images.githubusercontent.com/3154191/58773096-a73af100-8570-11e9-99e2-01582fc635ba.PNG">

This is from a CatBoost model, and most of my data is non-numeric categorical  values.  To get colors, does it make sense to convert my X values to numeric using something like target encoding?  I don't believe CatBoost provides a way to access the numeric version of X (the numeric converted data CatBoost is using behind the scenes).

**Comment by abrahami** [comment]
hi,
I'm having the same problem described above with only numeric features.
I'm attaching here a screen shot of the plot I'm getting.  All observations have a shap vlaue and a feature value (no NAN in the data)
SHAP version I'm using:  0.29.2

Any workaround to this?

![image](https://user-images.githubusercontent.com/19272958/61303697-a1336380-a7f0-11e9-9f50-759e1a64966c.png)

**Comment by slundberg** [comment]
@ralanburnett Sorry for the slow reply. Any numeric encoding will work, it does not have to match what CatBoost does since the only impact will be how the colors are allocated. Because of the way the coloring works by default, it will make the most sense to make "similar" categories near each other (if that is possible and worth the effort).

@abrahami It really looks like that are NaN values, if as you say there are not then I would ask you to share some notebook that reproduces the issue so we can take a look at it.

**Comment by abrahami** [comment]
thanks a lot for the quick reply!
Rechecked the details:
1. No NaN in the data
2. The grey dots appear only when I'm using the 'violin' option

Please see the print screen for both.
Could it be that the violin option only colors significant areas where it can "see" clear color type?

![image](https://user-images.githubusercontent.com/19272958/61351097-63771f00-a872-11e9-9648-94d2be5f530e.png)

**Comment by ralanburnett** [comment]
Hello Scott,

Thanks for your reply.  I have been sidetracked researching existing
references and writing my paper and haven't tried the approach you
suggested yet, but I agree that this should work (at least in theory).  I
wish that both Catboost and H2O exposed the numerical version of the data
that is being processed internally (when mixed numerical and non-numerical
categorical data is used as an input), which would make things so much
easier.  I'll let you know if it works once I try it.

Regards,

Alan

**Comment by jennykathambi90** [comment]
> @alvarosalgado it is probably because the data is not numeric and so there is no notion of "high" or "low". For the sake of colors you could just convert the data to 0-4 instead of letters before passing it for plotting.

Finally I thought the same too. My plot has a mixture of categorical and numerical, and there are no colors for the categorical but the numerical features have colors.

**Comment by Tych0n** [comment]
Hi, @slundberg! Having same issue as abrahami. Data and code to reproduce can be found [here](https://mega.nz/#!LpF0gY5J!OxEAw-Hh2AqwcJSGTXO09d4Hh7bQptoUoFrteuBBU3I). 

`shap.summary_plot(shap_values[0], Xtr)`

![dot](https://user-images.githubusercontent.com/3283584/66027339-5a0d6280-e503-11e9-9a70-f6ce29ab3a0c.png)

`shap.summary_plot(shap_values[0], Xtr, plot_type='violin')`

![violin](https://user-images.githubusercontent.com/3283584/66027368-65608e00-e503-11e9-8dc6-bd9b71526385.png)

**Comment by lordzuko** [comment]
I was passing a numpy array as features and I was getting the complete gray plot. There were no NaN values present in my data. I converted the numpy array of features to pandas dataframe and I got the plot with red and blue color. Please try this as well, this worked for me.

**Comment by christabella** [comment]
It would be nice to be able to display/peek at the actual color legend for categorical values.

If we know the integer encodings then we know the colors, e.g. "male", "female", "unknown" -> [0, 1, 2] -> blue, purple, and red

But this is difficult to keep track of, especially when the categories don't have any intrinsic order. How would we customize the color map for each feature, if necessary?

In the meantime I guess the best thing to do is to try to replicate the plot with another tool outside of this SHAP library! If anyone has custom code for, would be interested

**Comment by sumismyname** [comment]
Had this issue whenever I passed a **sparse** array to summary_plot. This simply fixed this:

shap.summary_plot(shap_values, X)
 
_changed to_

 shap.summary_plot(shap_values, X.toarray())

**Comment by valeria-io** [comment]
I'm also getting grey plots in `summary_plot`. In my case, I used a very large value to fill null (-999999). It seems that the value is so extreme that it gets greyed out. When using `plot_shap_dependence`, these large values do not even show up (the x axis starts at 0).  

I have some variables that are "day since user did X". I need to be able to distinguish (1) users who did did the action X today [value = 0], (2) users who did action X many days ago [value >0], (3) users who never did action X [value = -999999]. 

If the values of (1) and (3) are close to each other, I cannot distinguish them properly when using SHAP. 

Anyone facing this issue?

**Comment by snaiws** [comment]
![output](https://user-images.githubusercontent.com/54572026/175854052-a5177c80-7782-4b56-870c-be38c0b63c40.png)

I think non numeric values and np.nan get grey color

**Comment by aberges-grd** [comment]
it's still happening as of version 0.42.0

any ideas why? I restarted my notebook and it just happened, while previously it was OK.
Shap values contain no Nans, everything is gray.

**Comment by aberges-grd** [comment]
In my case it happened because the data was somehow marked as "object" by numpy instead of float (despite all features being numeric). After casting the type to float64, the problem was resolved.

(commenting just in case other people have the same issue)

**Comment by yama-yeah** [comment]
if you use torch, plot will grey out.
you have to use numpy.
