### ISSUE TITLE
force_plot matplotlib=True -> values are not rounded

### ISSUE THREAD

**Issue by dynamik1703** [shap/shap#408]
Example: 
![shap_372_error](https://user-images.githubusercontent.com/10382711/51677317-7f8fb700-1fd9-11e9-9ce1-fe0614cd5ec3.png)

**Comment by naarkhoo** [comment]
you can round them before passing them to the function 
for example

```
shap.force_plot(base_value = np.around(explainer.expected_value, decimals=2),
                    shap_values = np.around(shap_values[sample_id,:], decimals = 2),
                    features = np.around(one_sample, decimals=2),
                    matplotlib=True, show = False, feature_names=feat_names)
```

**Comment by dynamik1703** [comment]
I also tried manual rounding. It doesn't work. It seems that the number is converted again in the background.

**Comment by slundberg** [comment]
All the code for that is in: https://github.com/slundberg/shap/blob/master/shap/plots/force_matplotlib.py

I can't dig into it right now, but if you end up adding a fix for that please share as a PR :)

**Comment by dynamik1703** [comment]
Where would you start? At the def format_data(data) Method?

The data is available as a string at this point. I could convert it to float, round it and convert it back to string.

But this seems to me to be a cumbersome solution.

**Comment by slundberg** [comment]
I think that's the best place. The code uses the same JSON style api as the javascript so the data does come as a string. Rounding is best done as a string output anyway, since you are not rounding in base-2 but in printed base-10.

**Comment by naarkhoo** [comment]
@dynamik1703  can you do a favour and add an argument into the function to rotate the feature names  (ax.text) - so if the feature name is long they don't get into each other.

unfortunately, I don't know what would be the best practical way to contribute into SHAP. I don't know if I add the change, how I can troubleshoot and call (call me a scripter).

**Comment by dynamik1703** [comment]
@slundberg 
To be honest, the hint to the printed base 10 is not quite clear to me yet

In order to not change the data another simple way would be to adjust line 114 as follows:
old:
`text = feature[2] + ' = ' + feature[1]`
new:
`text = feature[2] + ' = ' + str(round(float(feature[1]),2))`

**Comment by slundberg** [comment]
I meant don't round the number in memory but rather during printing like:

`text = '{0:s} = {1:.6g}'.format(feature[2], float(feature[1]))`

**Comment by ChenChen960506** [comment]
@dynamik1703 
```
choosen_instance = dataset.loc[[1]].round(2)#The first line of the dataset
shap_values = explainer.shap_values(choosen_instance)
shap.initjs()
shap.force_plot(explainer.expected_value[1], shap_values[1], choosen_instance,matplotlib=True,show=False)
```

I hope it can help you, but when setting `matplotlib=True`, the picture cannot show the value of base value. If you can slove it, please reply to me. Thank you.

**Comment by VforV93** [comment]
I "solved" this issue by changing the function _**format_data(data)**_ in shap/plots/_force_matplotlib.py.

```
# Format negative features
    neg_features = np.array([[data['features'][x]['effect'],
                              round(data['features'][x]['value'],2) if isinstance(data['features'][x]['value'], float) else data['features'][x]['value'],  --> changed
                              data['featureNames'][x]]
                             for x in data['features'].keys() if data['features'][x]['effect'] < 0])
...
# Format postive features
    pos_features = np.array([[data['features'][x]['effect'],
                              round(data['features'][x]['value'],2) if isinstance(data['features'][x]['value'], float) else data['features'][x]['value'],  --> changed
                              data['featureNames'][x]]
                             for x in data['features'].keys() if data['features'][x]['effect'] >= 0])
```

I know it's not the most elegant way of doing that, but now I can read the graph.

**Comment by AndreaLK3** [comment]
The idea by @naarkhoo can work in some cases: rounding the features (i.e. the row(s) from the original data that get passed to the shap.plots.force(...) function) did it for me; neither the expected value nor the SHAP values had an influence.

**Comment by Loominarty** [comment]
Hello everyone in the thread. Coming late to the party, but ran into the same formatting issue and found the solution. Shapley always goes back to the original data shape, no matter the rounding operations performed previous to plotting. 
Rounding must be done within the force_plot function : 

`shap.force_plot(base_values_rounded[idx, i], shap_values_rounded[idx, :, i], X_full.iloc[idx].round(2), matplotlib=True, text_rotation =30)`

This will fix your rounding problem ! Note the text_rotation argument if elements of the plot are still overlapping.
