### ISSUE TITLE
Operational interpretation of shapley values

### ISSUE THREAD

**Issue by echo66** [shap/shap#409]
Greetings!

I'm trying to interpret the shapley values from a more **operational point of view**. Right now, when using any of the explainers, the value of each coefficient states how much the original feature attribution impacted in order to move the query output from the reference output. But what is the meaning of this reference? If we use `KernelExplainer`, the meaning would be something like 

*"The contribution of feature attribution of *f1* to move the output from the output mean of the reference dataset was _theta1_"*. 

But why the output mean and not, for example, the opposite class output mean or the output mean of the k closest outputs of the opposite class (assuming we are talking about a classification task)? For example, in the UCI breast cancer dataset, if our query belongs to the malignant class, we could use a (sub)set of the benign class to answer the question 

_"How important each feature value to classify a sample as malign?"_, 

right?

@slundberg

**Comment by slundberg** [comment]
Sorry for the slow reply, this made me think more than a few seconds, so it got pushed off :)

Interesting idea. There could be legitimate reasons to choose other background distributions that are different than just using the source training set. Your choice of background distribution captures what you consider as a normal baseline. If you are (as in your example) explaining the output probability of a two way cancer classifier, you could use just the benign examples as your background set. If you do that then you will be explaining how you got from benign, not how you got from typical. The practical result would be that you would see fewer "protective" features, and more "risk inducing" features in the explanations. It is application dependent if that is more helpful than seeing the difference from the whole population.

Using a background set that is representative of the whole population is motivated by the fact that you can think of the SHAP value as the impact of "learning" that feature's value. "Learning" anything is always with respect to some prior distribution, which for SHAP values is defined by the background dataset. I think as long as you can reasonably call your background your prior belief, then you can justifiably use it for SHAP values. (So for the cancer example you could ask what changes your prior belief from that it is benign to the current prediction)

**Comment by echo66** [comment]
Excellent answer, Scott.

I've been thinking about this for some time but I wanted to see if we arrived to the same conclusion. Also, Christoph Molnar also wrote about this use case in his book. 

Thanks for your time!

**Comment by gialmisi** [comment]
> Sorry for the slow reply, this made me think more than a few seconds, so it got pushed off :)
> 
> Interesting idea. There could be legitimate reasons to choose other background distributions that are different than just using the source training set. Your choice of background distribution captures what you consider as a normal baseline. If you are (as in your example) explaining the output probability of a two way cancer classifier, you could use just the benign examples as your background set. If you do that then you will be explaining how you got from benign, not how you got from typical. The practical result would be that you would see fewer "protective" features, and more "risk inducing" features in the explanations. It is application dependent if that is more helpful than seeing the difference from the whole population.
> 
> Using a background set that is representative of the whole population is motivated by the fact that you can think of the SHAP value as the impact of "learning" that feature's value. "Learning" anything is always with respect to some prior distribution, which for SHAP values is defined by the background dataset. I think as long as you can reasonably call your background your prior belief, then you can justifiably use it for SHAP values. (So for the cancer example you could ask what changes your prior belief from that it is benign to the current prediction)

Sorry to bump this old thread, but I am very much interested in using SHAP values in an operational sense as well. What I would like to achieve, is to explicitly set the baseline to a certain value against which I would like to explain the contributions of each feature to a given output. Right now, I have to basically formulate problem to find a subset of my background data that results in the desired background (a biased expected output). It would be so handy if I could just define the baseline. I am not sure if SHAP values could somehow be "shifted" a posteriori to be relative to a new baseline, likely not as far as I understand this issue. This becomes especially tricky with multi-output models.

An example on how I have used SHAP values in this context (but with a "global" background, can be be found in [this paper](https://link.springer.com/article/10.1007/s10458-022-09577-3) if you are interested. This is a more operational use of SHAP values in a decision-support and multiobjective optimization context. In this case, we have a very much defined set of values in reference to which we wish to explain the contribution of an input to an output. While the "global" background works most of the time, my approach could be improved a lot by using a tailored background, or just setting the baseline and somehow shifting the SHAP values (if it is possible) to reflect this new baseline.

Maybe there is some research in this direction? I have not come across any yet.
