### ISSUE TITLE
dependence_plot throw Error when specifying interaction_index=None

### ISSUE THREAD

**Issue by Barcavin** [shap/shap#411]
When I run `dependence_plot(index,shap_values, features,interaction_index=None)`, it will throw out error `UnboundLocalError: local variable 'xv_nan' referenced before assignment`. 
 
It is caused by 
https://github.com/slundberg/shap/blob/668f2e525f081d82e88b28aa5bee130b32584f7f/shap/plots/dependence.py#L182-L190 `xv_nan` is not assigned value if `interaction_index==None`.

**Comment by slundberg** [comment]
Thanks! Just pushed a fix, and a unit test to prevent any future regression.

**Comment by VinceFab** [comment]
Hi, this is still throwing the same error.
We just need to declare `xv_nan` at some point (probably line 199) in the case where `interaction_index==None`, otherwise line 249 won't work :) thanks!

**Comment by slundberg** [comment]
@VinceFab what version of shap do you have?

**Comment by klouisse** [comment]
Hi @slundberg I am experiencing the same error . 
![image](https://user-images.githubusercontent.com/48747069/54750231-ed3f1480-4c11-11e9-947a-65b82fd1de47.png)

**Comment by VinceFab** [comment]
my version is 0.28.3 as well

**Comment by slundberg** [comment]
Ah. This bug was fixed in version 0.28.4... so that's why you are still seeing it. You will need to update SHAP to fix it.
