### ISSUE TITLE
alternative simple force_plot

### ISSUE THREAD

**Issue by naarkhoo** [shap/shap#412]
I wonder how I can visualize the impact for one observation - but similar to the `summary_plot` (bar/dot) plot. 

I can try the following 

    shap.summary_plot(shap_values, x_train, plot_type="dot", show = False, feature_names=feat_names)

but this illustrates for the all datapoints. I tried x_train.iloc[0,:] but it expects a matrix rather than a one dimension. I hope I am not doing something wrong.

**Comment by slundberg** [comment]
You could always do `x_train.iloc[0:1,:]`
