### ISSUE TITLE
Different Value for Class Prediction and Force Plot

### ISSUE THREAD

**Issue by jordangarside** [shap/shap#414]
This may be related to #328, but here I'm using XGBoost.

The output for the 2nd class is 0.48 when run through XGBoost, but is 0.44 in the force plot.

![image](https://user-images.githubusercontent.com/6321824/51770803-8affe280-20ac-11e9-9cb0-cf53d8a98027.png)

Thanks!

**Comment by slundberg** [comment]
Can you try `output_margin=True` for the XGBoost prediction?

**Comment by jordangarside** [comment]
@slundberg `output_margin=True` returns the same value as SHAP. Is there any documentation on what margin refers to in XGBoost, and is this the intended output value for SHAP?

Thanks!

**Comment by slundberg** [comment]
For any others that land here the margin is the raw output of the trees in XGBoost, and the meaning of it varies for different objectives. For logistic loss it is the log odds ratio, for squared loss it is the same as the model's output.
