### ISSUE TITLE
multi-threading possible for summary_plot?

### ISSUE THREAD

**Issue by koomie** [shap/shap#415]
Hi there,

Very nice job with this software - thank you for making it available. One quick question - is it possible/conceivable to exercise `shap.summary_plot()` with multiple processors to improve runtime?

**Comment by slundberg** [comment]
Thanks! Not right now. Parallelizing matplotlib code seems tricky. You could always just plot fewer points of course to get a good idea of what is going on. After you have lots of points the patterns are not going to change all that much.
