### ISSUE TITLE
Understanding mapping functions

### ISSUE THREAD

**Issue by Mark531** [shap/shap#416]
I'm still struggling to understand the role of mapping functions defined in the SHAP paper. It is said that they link absence/presence of features to the original input space.
<img src="https://latex.codecogs.com/gif.latex?x=h_x\left(z'\right)"/>

For instance, if we have <a href="https://www.codecogs.com/eqnedit.php?latex=z'=\left(1,0,1\right)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?z'=\left(1,0,1\right)" title="z'=\left(1,0,1\right)" /></a>, do we have <img src="https://latex.codecogs.com/gif.latex?x=\{x_1,x_3\}"/>?

If that's the case, I'm wondering the meaning of the notation <img src="https://latex.codecogs.com/gif.latex?f\left(x\right)"/> since f takes M inputs as parameters.

I guess a simple example would make all this clear.

**Comment by echo66** [comment]
AFAIK, the *h_x* function takes a binary vector and returns a vector that contains values (1) from *x* or (2) from the domain *X*. I'm supporting my claim by both my interpretation of the NIPS 2017 paper and the code for Kernel Explainer.

**Comment by Mark531** [comment]
Since the expectation is computed on f(x), I guess x must be made of variables (=features), don't you think? The SHAP paper really lacks an example showing what all variables represent.

**Comment by slundberg** [comment]
Sorry this was unclear. `h_x` is meant as an abstraction for unifying several methods. When using a single background reference `r` in your example `z' = (1,0,1)` will become `z = h_x(z') = (x_1, r_2, x_3)`. For using the more general conditional expectation definition of SHAP values then `f(h_x(z')) = f(x_1, missing, x_3) \approx E[f(x) | x_1, x_3]`

**Comment by Mark531** [comment]
Ok, as I thought, it was an abstraction.
