### ISSUE TITLE
TreeExplainer throws error with lightgbm and model_output='probability' 

### ISSUE THREAD

**Issue by Rmwak** [shap/shap#417]
When creating a TreeExplainer to explain probabilities for a lightgbm model, this error is thrown: 

`AttributeError: 'TreeEnsemble' object has no attribute 'values'
`

I have faced the issue with other datasets, but for reproductibility, here's an example.

The example code provided in : https://github.com/slundberg/shap/issues/392#issuecomment-455734243  works correctly.

The following example is a slightly tweaked version with the boston dataset:

```
import lightgbm as lbm
import shap
import sklearn
import numpy as np

# load JS visualization code to notebook
shap.initjs()

# train XGBoost model
X,y = shap.datasets.boston()

# change the problem to categorical
y_cat = y < np.mean(y)
# go as usual

dtrain = lbm.Dataset(X, y_cat)

PARAM = {'task':'train', 'boosting_type': 'gbrt',
         'objective': 'binary',
         'metric': 'auc',
         'verbose':-1}

bst = lbm.train(PARAM, dtrain, num_boost_round=100, verbose_eval=False)
background = sklearn.utils.resample(X, n_samples=100, replace=False)
explainer = shap.TreeExplainer(bst, background, model_output='probability', feature_dependence='independent')
shap_values = explainer.shap_values(X)

# this outputs essentially zero
print(np.abs(explainer.expected_value + shap_values.sum(axis=1) - bst.predict(X)).max())
```

The complete error trace:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-023daf0b03f4> in <module>
     23 bst = lbm.train(PARAM, dtrain, num_boost_round=100, verbose_eval=False)
     24 background = sklearn.utils.resample(X, n_samples=100, replace=False)
---> 25 explainer = shap.TreeExplainer(bst, background, model_output='probability', feature_dependence='independent')
     26 shap_values = explainer.shap_values(X)
     27 

~/miniconda3/envs/shap-env/lib/python3.6/site-packages/shap/explainers/tree.py in __init__(self, model, data, model_output, feature_dependence)
    121             self.expected_value = self.__dynamic_expected_value
    122         elif data is not None:
--> 123             self.expected_value = self.model.predict(self.data, output=model_output).mean(0)
    124         elif hasattr(self.model, "node_sample_weight"):
    125             #proportions = self.model.node_sample_weight[:,0] / self.model.node_sample_weight[:,0].sum()

~/miniconda3/envs/shap-env/lib/python3.6/site-packages/shap/explainers/tree.py in predict(self, X, y, output, tree_limit)
    642 
    643         if tree_limit < 0 or tree_limit > self.values.shape[0]:
--> 644             tree_limit = self.values.shape[0]
    645 
    646         if output == "logloss":

AttributeError: 'TreeEnsemble' object has no attribute 'values'
```

The only diference I'm able to see is the array input vs dataframe input in lbm.Dataset()

**Comment by Rmwak** [comment]
After testing in a fresh new environment, can't reproduce the issue. I see no difference in library versions between them:

* New env:
      
      lightgbm                  2.2.2                     <pip>
      shap                      0.28.3                    <pip>
      scikit-learn              0.20.2                    <pip>
      numpy                     1.16.0                    <pip>

* Old env:

      lightgbm                  2.2.2                     <pip>
      numpy                     1.16.0                    <pip>
      scikit-learn              0.20.2                    <pip>
      shap                      0.28.3                    <pip>


I'm guessing there's some kind of conflict between other libraries or between conda  vs pip versions, but since I cannot find the difference and a fresh environment shows no issue, I'll close this one.

**Comment by nchaly** [comment]
@Rmwak - it reproduces with categorical features of LightGBM.

    import lightgbm as lbm
    import shap
    import sklearn
    import numpy as np

    # load JS visualization code to notebook
    shap.initjs()

    # train XGBoost model
    X,y = shap.datasets.boston()

    # Add Category variable with plenty of values.
    X['cat_column'] = np.random.choice(range(10), size=X.shape[0])
     y_cat = y < np.mean(y)
    # go as usual

    dtrain = lbm.Dataset(X, y_cat, categorical_feature=['cat_column'])

    PARAM = {'task':'train', 'boosting_type': 'gbrt',
             'objective': 'binary',
             'metric': 'auc',
             'verbose':-1
             }

    bst = lbm.train(PARAM, dtrain, num_boost_round=100, verbose_eval=False)
    background = sklearn.utils.resample(X, n_samples=100, replace=False)
    explainer = shap.TreeExplainer(bst, background, model_output='probability', feature_dependence='independent')
    shap_values = explainer.shap_values(X)

    # this outputs essentially zero
    print(np.abs(explainer.expected_value + shap_values.sum(axis=1) - bst.predict(X)).max())


The exception is `AttributeError: 'TreeEnsemble' object has no attribute 'values'`. I presume this is because 'threshold' in lgbm tree representation for such columns cannot be parsed to float.
