### ISSUE TITLE
Binding SHAP into HTML

### ISSUE THREAD

**Issue by ChaosPat23** [shap/shap#419]
Hi there,

I am fairly new to SHAP but I already fell in love with this software...
I am working on a project for which I want to visualize the explanations of my machine learning model with force_plot. First, I want save the SHAP values into a database in order to fetch the values and create the graph on the fly in the browser. 

Is there any way to bind SHAP to an HTML file like an URL to use the force_plot function?

**Comment by mamitiana** [comment]
Hi  @ChaosPat23 
how did you solve this please ?
