### ISSUE TITLE
Interpretation of explainer.expected_value for multiclass problem

### ISSUE THREAD

**Issue by Karthik1611** [shap/shap#420]
The expected value gives 5 values for my multiclass problem, but how to know to which class does each of the 5 values belong to?

**Comment by slundberg** [comment]
They should line up to the five outputs of your model (in order). But perhaps sharing more about your use case would help?

**Comment by ivan-marroquin** [comment]
Hi @slundberg 

I have a multi-class model generated using XGBClassifier from xgboost version 0.90. I am using shap version 0.34.0.

When I ran the command: shap_explainer.expected_value , I only get a single value. Based on previous discussion, I would expect a number of "expected_values" equal to the number of classes. Am I correct?

In the attached zip file, you will find a Python script and data necessary to duplicate the incident.

Many thanks,

Ivan



[multi-class_expected_value.zip](https://github.com/slundberg/shap/files/4159895/multi-class_expected_value.zip)

**Comment by ivan-marroquin** [comment]
I noticed that i forgot to add "import shap" in the script submitted in my previous comment.

I made the change in this new submission, please disregard the previous zip file



[multi-class_expected_value.zip](https://github.com/slundberg/shap/files/4160956/multi-class_expected_value.zip)

**Comment by slundberg** [comment]
@ivan-marroquin thanks for reporting the bug! I just pushed a fix.

**Comment by ivan-marroquin** [comment]
Hi @slundberg 

Good news, I just download the latest master version and installed using "python setup.py install" command. 

The expected values output is now an array with # elements equal to # classes

Ivan
