### ISSUE TITLE
CatBoost Ranking no supported

### ISSUE THREAD

**Issue by doramir** [shap/shap#425]
I saw in the code that shap is supporting only catboost classifier and catboost regression
```python
        elif str(type(model)).endswith("catboost.core.CatBoostRegressor'>"):
            assert_import("catboost")
            self.model_type = "catboost"
            self.original_model = model
        elif str(type(model)).endswith("catboost.core.CatBoostClassifier'>"):
            assert_import("catboost")
            self.model_type = "catboost"
            self.original_model = model
```

and when we use CatBoost for ranking the type of the model is:
`catboost.core.CatBoost`

by adding this:
```python
        elif str(type(model)).endswith("catboost.core.CatBoost'>"):
            assert_import("catboost")
            self.model_type = "catboost"
            self.original_model = model
```
It's start to support regular CatBoost model type
is there any thing else i should add?

shape version `__version__ = '0.28.3'`
mac os
python 3.6.5

**Comment by slundberg** [comment]
Nope, if that is working for you then that should be all you need. CatBoost does not have an internal implementation for SHAP, we just rely on the implementation of Tree SHAP the CatBoost team wrote in their own code: https://github.com/slundberg/shap/blob/dc53ee14340b6614cbe44c5cfad8a0897029c141/shap/explainers/tree.py#L188-L193

Mind sending the update as a PR? :)

**Comment by doramir** [comment]
sure i will send you :)
