### ISSUE TITLE
features change for each prediction? Keras LSTM for IMDB Sentiment Classification latest.ipynb

### ISSUE THREAD

**Issue by galenwilkerson** [shap/shap#427]
![index](https://user-images.githubusercontent.com/208536/52271185-49402900-2943-11e9-9ced-ae4fc9546b66.png)
![Uploading 4d7cec68-8fe4-4263-a08a-2b635c3406bc.png…]()

Hi, I'm interested in using shap for feature importance in an LSTM, but have a doubt about the features in Keras LSTM for IMDB Sentiment Classification latest.ipynb

When I generate a force-plot for the first 10 predictions,

`shap.force_plot(explainer.
                expected_value, 
                shap_values[0], 
                x_test_words)`

I get an image like the first attachment.

I also tried to plot the average feature importance,

`plt.figure()
shap.summary_plot(shap_values, features=x_test_words);`

**But when I take a look at x_test_words, it is different for each prediction.  This seems to indicate that the words corresponding to the predictions change for each prediction, rendering the shap values not very useful in this case.**

`x_test_words[0][79]
'sequence'`

`x_test_words[1][79]
'lessons'`

In my case, the features will not be words, and will not change on each prediction.

**Comment by slundberg** [comment]
Could you share the code you are using for explainer as well? The input features are considered as a vector by the explainers, so for sequential words in sentence you will get different words in each position at each sample. If you want to map it to something consistent you could try and map to the words yourself in separate dictionary.

**Comment by galenwilkerson** [comment]
Hi Scott,  I've just used your original notebook:

https://github.com/slundberg/shap/blob/master/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.ipynb

**Comment by galenwilkerson** [comment]
I've tried to find your email address to send you my notebook...

**Comment by slundberg** [comment]
Thanks. If you are using that notebook then it matches what I said above. Since SHAP values are local explanations they are specific to each prediction. If the meaning of your input features (as identified by index) changes between predictions then using summary plot directly is not helpful (since it tries to summarize the impact of features identified by index). You could manually group the credit though by word, just loop over all the explanations are add the absolute value of the explanation to the credit for each word you see.

**Comment by galenwilkerson** [comment]
Ok thanks, since that is your example notebook from deep explainer, you may
want to update it, otherwise it gives a confusing example of variable
importance.

Best

**Comment by slundberg** [comment]
Better late than never :) ...I added some clarification to that notebook to help future users.

**Comment by keyur-potdar** [comment]
Hi @slundberg, after grouping the SHAP values by words, is there a way in which we can use `summary_plot` to plot it? I was trying to do it using the same notebook that is discussed in this thread.
