### ISSUE TITLE
memory corruption error from TreeExplainer in latest release

### ISSUE THREAD

**Issue by imatiach-msft** [shap/shap#429]
When upgrading to latest release of shap some of our tests which use TreeExplainer started to fail in native layer randomly, causing python processes to fail.  I was able to reproduce snippets of the test cases in our library in shap and narrow down the issue to the native code in _cext.cc where the output tuple returned was using an object that had its reference counter decremented to 0 (so the object could be randomly garbage collected at any point in time, and it just so happened that some of our tests would hit this edge case).  It seems this error is more likely to be reproduced when using a large dataset.

**Comment by imatiach-msft** [comment]
Issue fixed with merge of PR #430

**Comment by ElSaico** [comment]
This consistently affects some of the models I try to create, which forces me to run the development version.
Would it be possible to make a new release?

**Comment by slundberg** [comment]
Done!
