### ISSUE TITLE
Should I use SHAP contributions for debugging why did my XGB classifier does not transfer to another population?

### ISSUE THREAD

**Issue by ihadanny** [shap/shap#44]
I trained a tree-ensemble classifier (XGBOOST) on population A, validated it and I'm satisfied with its accuracy (AUC 0.78). Now I'm trying to transfer it to a slightly different population B, and there the accuracy of the model deteriorates badly (AUC 0.68)

I tried isolating which of the features did not transfer well, both by simple univariate analysis (comparing distributions), and by comparing each feature correlation with the label, and couldn't find anything obvious.

I thought about comparing the label distributions at every node in every tree for the validation populations in A and B, thereby testing all conditional probabilities the model assumes are holding actually hold at B.

Could this be achieved by comparing the distributions of the feature contributions in A and B? If I'm looking for a bug in the specific classifier I trained, should I use SHAP for or the original "approximate tree-path contributions", as they are directly associated with what the classifier is actually doing (while SHAP contributions are designed to give the 'fair' contributions for each feature, not for debugging a specific classifier)?

**Comment by slundberg** [comment]
As you point out, debugging why model a model fails to generalize is
tricky. I would suggest that training a model on A and another model on B
would then allow you to compare the difference between how each model uses
the features. Any important trends might show up. You would also know then
if pop B is just "harder" if the model B is not much better than 0.68.

I should also point out that the "approximate tree-path contributions" are
not any more directly associated with what the classifier is actually
doing than the SHAP values. The approximate method is just a
faster-to-compute but less accurate representation of a feature's impact.
