### ISSUE TITLE
Explaining interactions impossible?

### ISSUE THREAD

**Issue by SkBlaz** [shap/shap#443]
Hello all,
I've been experimenting with:
`interactions = shap.TreeExplainer(model).shap_interaction_values(X)`
yet I seem to be getting:
`TypeError: predict() got an unexpected keyword argument 'pred_interactions'`
error. Am I doing something wrong?

**Comment by slundberg** [comment]
What version of (I assume) XGBoost are you using? My best guess is that it is an older one.

**Comment by SkBlaz** [comment]
Yes, you are correct. That was indeed the problem! Thanks, I was not aware
this is actually an XGB thing.

**Comment by slundberg** [comment]
Great. XGBoost and LightGBM have built-it versions of Tree SHAP, so we use them when possible.
