### ISSUE TITLE
One hot encoded example 

### ISSUE THREAD

**Issue by attibalazs** [shap/shap#45]
How would the **Census income classification with Keras.ipynb** example work if the features were one hot encoded ? I spent some time on trying to figure this out yesterday but couldn't get it to work any ideas would be really appreciated.

Thanks for a great paper and library this looks really useful.

**Comment by slundberg** [comment]
I am not looking at the source right now, but I think a one hot encoding
would be implemented with a one-dimensional embedding layer. (assuming the
1-hot input will go into a linear layer at first)

**Comment by attibalazs** [comment]
In your example you are doing Label encoding and then doing the vectorisation using Embedding layers in Keras. I have an example where i am using DictVectorizer which one-hot encodes my categorical features and the output is a regression maybe I should change over to using embedding layers like you are.

**Comment by germayneng** [comment]
@slundberg is there a solution to this? If there are categorical variables which i were to apply one hot encoding, is there a way for SHAP to know? From the examples, ( the ADULT data), the categorical variables are encoded using label encoding.

Is it that only label encoding works for SHAP interpretation?
