### ISSUE TITLE
A sad anniversary - matplotlib 3 introduces breaking change

### ISSUE THREAD

**Issue by EricSchles** [shap/shap#450]
I feel like this might be a known issue but I just want to raise it here:

I'm getting the following error:

AttributeError: module 'matplotlib.cbook' has no attribute 'is_string_like'

It appears to not be an issue with shap itself but in fact with skimage.  So I just thought I'd warn folks,

It appears as though you need to downgrade to matplotlib 2.x.x in order to get this to work.

**Comment by slundberg** [comment]
Thanks for the heads up. What specifically didn't work? (I have been using matplotlib 3 for a while with no issues)
