### ISSUE TITLE
IndexError in shap summary plot

### ISSUE THREAD

**Issue by Mark531** [shap/shap#453]
Hello,

I've just installed a fresh version of shap (0.27.0) with:
> conda install -c conda-forge shap

And I tried to display the global feature importance on a neural network:
```
import shap

explainer = shap.DeepExplainer(model, X)
shap_values = explainer.shap_values(X)
shap.summary_plot(shap_values, X)
```

But I get:
> Traceback (most recent call last):
> 
>   File "<ipython-input-159-6e791dffc370>", line 1, in <module>
>     shap.summary_plot(shap_values, X)
> 
>   File "C:\Users\I328807\AppData\Local\Continuum\Anaconda3\lib\site-packages\shap\plots\summary.py", line 357, in summary_plot
>     y_pos, global_shap_values[feature_inds], 0.7, left=left_pos, align='center',
> 
> IndexError: index 56 is out of bounds for axis 0 with size 1

Is it related to an outdated dependency package?

Mark

**Comment by slundberg** [comment]
Conda-forge had some issues and fell behind pypi, so that could be the problem. I'll post back here once that's fixed so conda will pull the latest 0.28.5 version.

**Comment by Mark531** [comment]
Ok, thank you.

**Comment by slundberg** [comment]
Conda forge is back running again, and finished with the build process, so 0.28.5 is now available there :)

**Comment by Mark531** [comment]
I tried:

> conda update -c conda-forge shap

But I got the message:

> All requested packages already installed.

**Comment by slundberg** [comment]
Hmm. https://anaconda.org/conda-forge/shap shows 0.28.5 is being served, perhaps some cache needs updated on your end?

**Comment by Mark531** [comment]
There are notorious issues problems with conda updating so I'll check with them and get back to you when I can retest the DeepExplainer with shap 0.28.5.

**Comment by jennykathambi90** [comment]
I get the same problem too

**Comment by Mark531** [comment]
@slundberg I tried with the 0.30.2 SHAP version on Google Colab and I get the same error. Do you need a minimal example to reproduce this issue?

**Comment by slundberg** [comment]
@Mark531 yes that would be great!

**Comment by Mark531** [comment]
The problem I initially entered was fixed with a newer version of shap (0.31.0). But I still have one issue when I call `summary_plot()` on complex tensors of SHAP values returned  by `shap_values()`. Here is a minimal snippet that reproduces the issue:
```
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, GRU
import shap

X = np.arange(-1, 1, 0.001).reshape(-1, 2, 2)
y = np.array([1 if _ % 2 == 0 else 0 for _ in range(len(X))])

model = Sequential()
model.add(GRU(32, activation='sigmoid'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X, y, epochs=10, batch_size=20)

explainer = shap.DeepExplainer(model, X)
shap_values = explainer.shap_values(X)
shap.summary_plot(shap_values, X, plot_type="bar")
```
The error is different:
> TypeError: only size-1 arrays can be converted to Python scalars

So tell me if you prefer that I enter a new issue.

**Comment by slundberg** [comment]
Interesting. When I run that with TF1.14 I get no problems on the master version.

**Comment by Mark531** [comment]
I ran it on Google Colab with the current libraries installed. I only had to install shap.
Here are the versions of the packages used by the snippet:
shap 0.31.0
tensorflow 1.15.0
keras 2.2.5
numpy 1.17.3
