### ISSUE TITLE
SHAP with top feature having no impact

### ISSUE THREAD

**Issue by vandanapriya** [shap/shap#455]
I used XGBoost to build a model and SHAP for looking into top SHAP features.
But surprisingly I got feature with no impact on the top. Is this a bug is SHAP?

**Comment by slundberg** [comment]
Could you share an example picture of what you mean? Summary plots for example sort by importance so the top feature will be the most impactful.

**Comment by vandanapriya** [comment]
Sure.
<img width="682" alt="shap_summaryplot" src="https://user-images.githubusercontent.com/47378350/53190215-124e6080-362f-11e9-8f58-072e6261539d.PNG">
<img width="848" alt="shap_summaryplot_1" src="https://user-images.githubusercontent.com/47378350/53190274-34e07980-362f-11e9-9846-17a62e3a6231.PNG">

**Comment by slundberg** [comment]
Hmmm...that does seem wrong. What does `shap.__version__` give? And are there any nan values in your shap_values array (there shouldn't be)?

**Comment by vandanapriya** [comment]
SHAP version is 0.15.0.  
No there is no nan values in shap_values array.

**Comment by slundberg** [comment]
Sorry for the slow reply. It could be that your SHAP version is very old, perhaps try updating?
