### ISSUE TITLE
DeepExplainer with RGB images

### ISSUE THREAD

**Issue by KyleYoung1997** [shap/shap#459]
Hi I'm trying to use the DeepExplainer on RGB images and have been following along the front page MNIST example but am running into this issue: 

`ValueError                                Traceback (most recent call last)
<ipython-input-57-d09e29becc3d> in <module>()
----> 1 shap_values_1 = e.shap_values(X_test[0])
      2 

/usr/local/lib/python3.6/dist-packages/shap/explainers/deep/__init__.py in shap_values(self, X, ranked_outputs, output_rank_order)
    117         were chosen as "top".
    118         """
--> 119         return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

/usr/local/lib/python3.6/dist-packages/shap/explainers/deep/deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order)
    257                 tiled_X = [np.tile(X[l][j:j+1], (bg_data[l].shape[0],) + tuple([1 for k in range(len(X[l].shape)-1)])) for l in range(len(X))]
    258                 # we use the first sample for the current sample and the rest for the references
--> 259                 joint_input = [np.concatenate([tiled_X[l], bg_data[l]], 0) for l in range(len(X))]
    260                 # run attribution computation graph
    261                 feature_ind = model_output_ranks[j,i]

/usr/local/lib/python3.6/dist-packages/shap/explainers/deep/deep_tf.py in <listcomp>(.0)
    257                 tiled_X = [np.tile(X[l][j:j+1], (bg_data[l].shape[0],) + tuple([1 for k in range(len(X[l].shape)-1)])) for l in range(len(X))]
    258                 # we use the first sample for the current sample and the rest for the references
--> 259                 joint_input = [np.concatenate([tiled_X[l], bg_data[l]], 0) for l in range(len(X))]
    260                 # run attribution computation graph
    261                 feature_ind = model_output_ranks[j,i]

ValueError: all the input arrays must have same number of dimensions`

I'm guessing thats because my images are RGB and am just wondering how I should format them so I can use DeepExplainer? Thanks for the great project as well!!

**Comment by slundberg** [comment]
Hmm...could you give a full example? It should work fine with arbitrarily shaped input tensors.

**Comment by linchundan88** [comment]
I'm using the DeepExplainer on RGB images, and the following code works:

shap_values = e.shap_values(img_preprocess, ranked_outputs=1)

data = shap_values[0][0][0][:,:,0]
# data = shap_values[0][0][0][:,:,0] + shap_values[0][0][0][:,:,1] \
#        +shap_values[0][0][0][:,:,2]

abs_max = np.percentile(np.abs(data), 100)
abs_min = abs_max

cmap = 'seismic'

from matplotlib import pylab as plt
plt.imshow(data, interpolation='none', cmap=cmap, vmin=-abs_min, vmax=abs_max)


However, shap.image_plot does not work.

**Comment by linchundan88** [comment]
shap_values return a list of (1,image_size,image_size,3).

**Comment by linchundan88** [comment]
The input image has RGB 3 channels.  I want to generate a saliency map with one channel.
Should I use shap_values[0][0][0][:,:,0] or  shap_values[0][0][0][:,:,0]+shap_values[0][0][0][:,:,1]+shap_values[0][0][0][:,:,2] ?

**Comment by linchundan88** [comment]
If background images(reference) contain a number of number , GPU memory error.
I suggest adding a mini-batch number parameter in shap_values function.

**Comment by slundberg** [comment]
@linchundan88 mini-batch would be nice, just takes work to implement it :) (GradientExplainer does have a mini-batch option)

As for the trouble with image_plot, have you tried running one the example notebooks that uses RGB images? I would then compare what you are passing to what is passed there and make sure the dimensions match.
