### ISSUE TITLE
Interaction contribution in lightgbm 

### ISSUE THREAD

**Issue by amir-ghasemi** [shap/shap#46]
Wondering if the interaction contribution calculation available in Xgboost is possible with lightgbm also. Had a quick look at the source but did not find anything. 

Thanks for the great library by the way!

**Comment by slundberg** [comment]
That has not been added to LightGBM yet unfortunately. The C++ from the
XGBoost version would need to be ported over.

**Comment by snowde** [comment]
Ooh this would be great!

**Comment by slundberg** [comment]
#116 now addresses this :) ...it just hasn't been pushed yet into a pip release.

**Comment by Mahdi-Hosseinali** [comment]
Wondering if feature interaction is available in pip

**Comment by Tachyon5** [comment]
What happened to this?  almost 3 years later and the commit https://github.com/slundberg/shap/pull/116 doesn't appear to be active.

**Comment by CloseChoice** [comment]
This is merged and working, see the test [here](https://github.com/shap/shap/blob/master/tests/explainers/test_tree.py#L1619)
