### ISSUE TITLE
Unable to run since version 0.27.0

### ISSUE THREAD

**Issue by pranut** [shap/shap#461]
Hi,

For some reason I cannot get TreeExplainer to run for anything greater than version 27. Version 27 still works perfect though, on Pycharm I just get return error code. I know this sound vague but I tried debugging and went pretty deep and then gave up. Any pointers? Otherwise I'll probably stick with 27.

**Comment by imatiach-msft** [comment]
@pranut 
Have you tried latest version: https://github.com/slundberg/shap/releases/tag/0.28.5
There was a fix for TreeExplainer in 0.28.4/0.28.5

**Comment by pranut** [comment]
@imatiach-msft 
Yes I tried all the versions one by one after 27 to identify which version the issue is cropping from, but was not able to figure it out.

**Comment by imatiach-msft** [comment]
@pranut are you sure you tried specifically 0.28.5?
This sounds very similar to the issue that I fixed here with a memory corruption error in TreeExplainer:
https://github.com/slundberg/shap/pull/430
Could you do a pip freeze and send the specific version of shap with the error?  Also, could you send us the error message?

**Comment by pranut** [comment]
`attrs==18.2.0
backcall==0.1.0
bleach==3.1.0
cloudpickle==0.8.0
colorama==0.4.1
cycler==0.10.0
dask==1.1.2
decorator==4.3.2
defusedxml==0.5.0
entrypoints==0.3
graphviz==0.10.1
ipykernel==5.1.0
ipython==7.3.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.3
Jinja2==2.10
jsonschema==3.0.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
kiwisolver==1.0.1
lime==0.1.1.32
MarkupSafe==1.1.1
matplotlib==3.0.2
mistune==0.8.4
nbconvert==5.4.1
nbformat==4.4.0
networkx==2.2
notebook==5.7.4
numpy==1.16.1
pandas==0.24.1
pandocfilters==1.4.2
parso==0.3.4
pickleshare==0.7.5
Pillow==5.4.1
prometheus-client==0.5.0
prompt-toolkit==2.0.8
Pygments==2.3.1
pyparsing==2.3.1
pyrsistent==0.14.11
python-dateutil==2.8.0
pytz==2018.9
PyWavelets==1.0.1
pywinpty==0.5.5
pyzmq==18.0.0
qtconsole==4.4.3
scikit-image==0.14.2
scikit-learn==0.20.2
scipy==1.2.1
Send2Trash==1.5.0
shap==0.28.5
six==1.12.0
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==5.1.1
tqdm==4.31.1
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
xgboost==0.81`


The error message is `Process finished with exit code -1073741571 (0xC00000FD)` on PyCharm

**Comment by imatiach-msft** [comment]
@pranut it looks like you are on the latest version.  Not sure what is causing the error.  Could you share the output before the error message:
```Process finished with exit code -1073741571 (0xC00000FD)```
Otherwise, I'm not seeing this issue with the latest package.
Also, could you try doing a pip uninstall shap/pip install shap, just to see if it makes any difference.

**Comment by pranut** [comment]
@imatiach-msft 
There is no error/output before the exit code, just typical script output until the TreeExplainer part.

I tried uninstalling and re-installing but still had the issue. How should I debug further to get the exact error?

**Comment by imatiach-msft** [comment]
@pranut probably the best way is to clone shap locally and create a test case that can reproduce the issue.  You can then add prints in the native code to track down where the issue is happening.  @slundberg might have better recommendations (eg increase verbosity for debugging?).

**Comment by pranut** [comment]
@imatiach-msft 
So, I found the point where it breaks:
`# we compute the expectations to make sure they follow the SHAP logic
        self.max_depth = _cext.compute_expectations(
            self.children_left, self.children_right, self.node_sample_weight,
            self.values
        )`

self = {Tree} <shap.explainers.tree.Tree object at 0x00000178B549C780>
 children_default = {ndarray} [1 0 3 0 0]
 children_left = {ndarray} [ 1 -1  3 -1 -1]
 children_right = {ndarray} [2 0 4 0 0]
 features = {ndarray} [74  0 52  0  0]
 node_sample_weight = {ndarray} [4753. 3387. 1366. 1344.   22.]
 thresholds = {ndarray} [  302355.        0. 13191834.        0.        0.]
 values = {ndarray} [[ 0.        ]\n [ 0.14995573]\n [ 0.        ]\n [-0.14877324]\n [-0.11739131]]

This is the value of the Tree object

**Comment by slundberg** [comment]
@pranut Sorry for the trouble. How did you train the model you are explaining? Someone mentioned some issues with a GPU version of an XGBoost model. When I get some time I can also reconstruct that tree and see if I get the same error.

**Comment by pranut** [comment]
@slundberg Hi Scott, I am training XGBoost using GPU Hist. I will try training without GPU and report back.

Thanks!

**Comment by pranut** [comment]
Hi, just wanted to give a quick update, I was running the same model again with the latest SHAP and it seems to have now been fixed in one of the updates after 0.28.5.

Thanks!
