### ISSUE TITLE
required dependencies -> optional dependencies?

### ISSUE THREAD

**Issue by jorgecarleitao** [shap/shap#466]
> pytz, pandas, PyWavelets, pillow, decorator, networkx, cloudpickle, toolz, dask, scikit-image, tqdm, pickleshare, ptyprocess, pexpect, appnope, parso, jedi, pygments, backcall, wcwidth, prompt-toolkit, ipython-genutils, traitlets, ipython, shap

I am not sure why should I need to install `pillow` or `scikit-image` `networkx` if I am not working with image data nor networks.

I understand that this rep contains everything, all methods and plotting. But it seems unreasonble to ask for all these dependencies if the user just wants shap for a specific problem.

For example, for me, the use-case is to compute the shap values for feature importance and instance interpretability on a restful API supporting a frontend containing vizualization (that does not depend on shap visualizations). The backend does not need any of the vizualisation, nor pandas, only numpy, tensorflow and spark. I do not want to expose data to third-party libraries that I do not trust (e.g. `appnope`) to a production system.

One way to approach this is to split the `install_requires` in multiple `extra_requires`, and make only the mandatory packages part of the `install_requires`, as per the [official recommendation to use `install_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires):

> “install_requires” should be used to specify what dependencies a project minimally needs to run.

**Comment by slundberg** [comment]
I bet many of those are driven by the use of 'scikit-image'. That package is only used for color space conversions, but those conversions are needed for all the plotting methods. We could pull out that dep by getting Lch color space methods another way

**Comment by afiodorov** [comment]
This currently make deployment of the library in production somewhat inconvenient. Would be nice to have the lean version that doesn't pull in plotting available.

**Comment by slundberg** [comment]
I can see why that would be nice. If anyone has ideas for an elegant way to do that without splitting up the repo and making maintenance harder please speak up.

**Comment by jorgecarleitao** [comment]
One way is to use [extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), that are supported by pip: `pip install shap[all]`, `pip install shap`, `pip install shap[images]`.

**Comment by jorgecarleitao** [comment]
I will take a look at this one.

**Comment by slundberg** [comment]
Okay, I finally got around to tackling this and have been able to remove skimage, matplotlib and ipython as required dependencies. The need for ipython is only in a notebook, and then people already have it, and matplotlib is so common that it seems reasonable to just have a warning if people try to use a plot without it installed
