### ISSUE TITLE
Notebook examples

### ISSUE THREAD

**Issue by sami-ka** [shap/shap#47]
Hi,

First of all, thank you for this interesting algorithm and code! 

I tried running the notebooks you provided, but it seems that some do not match the current version of the code (probably due to improvements you made the last 6 months). 

I tried **Diabetes regression.ipynb** which had for example a problem with the function `ShapExplainer` that does not exist anymore (probably now `KernelExplainer` from `shap.explainer`). I assume there are more issues like this for other notebooks.
I also tried a notebook updated 3 weeks ago which works fine. 
Could you commit an update of the notebooks? These are very useful to understand how we should/could use your code!

thanks,

**Comment by slundberg** [comment]
Thanks for pointing that out. I’ll push an update to the old notebooks soon

**Comment by slundberg** [comment]
Should all be fixed now, as I cleaned up the relevant notebooks and removed the irrelevant and potentially broken ones.
