### ISSUE TITLE
DeepExplainer does not correctly explain a linear model

### ISSUE THREAD

**Issue by jorgecarleitao** [shap/shap#471]
It seems that DeepExplainer is not correctly explaining a linear model fitted on linear data. I have written a unit-test demonstrating this behavior, #470. 

This test consists in:

    1. generate data with 2 independent features and a target `y = 1 + 2 x1 + x2 + small noise`
    2. define a linear model with Keras
    3. fit the model to the data
    4. confirm that the model fits the data correctly
    5. explain the fitted model
    6. confirm that the shap values correspond to the expected values of a linear model, namely, what is described in the docs as `"Assuming features are independent leads to interventional SHAP values which for a linear model are coef[i] * (x[i] - x.mean(0)[i]) for the ith feature"`.

This test currently fails: the model fits correctly, but the explanation is different from the equation above, see #470.

This hints for a potential bug on the source code, specially since #468 confirms that the `LinearExplainer` computes the shap values given by the equation above.

(I am assuming here that DeepExplainer with a linear model should give the same explanations as the LinearExplainer, when the data and fitted weights of both models are statistically the same)

**Comment by jorgecarleitao** [comment]
It seems that there is some discrepancy: in my machine it does not give the correct result, but travis gives. So, closing as resolved.

**Comment by jorgecarleitao** [comment]
Actually, the reason #470 passed was because the test was being skipped, because CI is skipping tests that fail to import tensorflow -.-'

**Comment by slundberg** [comment]
There was actually no error in DeepExplainer, just a typo in the layer passing for the test (see #470). However, this was great as it caught the issue with TF tests getting skipped :)
