### ISSUE TITLE
Different results for LinearExplainer and kernelExplainer for Logistic Regression

### ISSUE THREAD

**Issue by SaadAhmed96** [shap/shap#476]
I wanted to know is it a good idea to use LinearExplainer object for a logistic regression model.

I seem to be getting completely different results from the LinearExplainer and the KernelExplainer for the same prediction on the iris data set. The KernelExplainer results are more intuitive as the base and output value are within [0,1] while the results from the LinearExplainer are different numbers. 

Can anyone explain this to me why this is happening.
Thanks!

![image](https://user-images.githubusercontent.com/30757857/53799614-8f95a180-3f5c-11e9-8afc-4544d0fc674c.png)

**Comment by slundberg** [comment]
This is because the LinearExplainer is explaining the output of the linear model before the logistic transform (so log odds units). While the KernelExplainer is explaining the output after the transform (so in probability space). Log odds are a bit more natural to add together, but both are fine.

**Comment by SaadAhmed96** [comment]
Thanks for the quick response its clear now.
