### ISSUE TITLE
SHAP not equal to exact Shapley Value for ONLY two binary features?

### ISSUE THREAD

**Issue by kongwei9901** [shap/shap#478]
Hi Scott,

I was testing XGBoost SHAP on a simple data. (Only 2 dummy variables, Target is binary classification). Could NOT match SHAP value with exact Shapley Value. Can you shed some lights where the inconsistency came from?

- What the data looks like (Value to explain: -0.36088, feature1 = 0 AND feature2 = 1)
feature1	feature2	frequency 	log_odds
0	        0	         30,427 	    -0.33656
0	        1	         16,513 	    -0.36088
1	        0	         1,170 	    0.01878
1	        1	         477 	    -0.19547

- Base Value
E(f(x)) = Average model output = Total log_odds / Total Frequency = (30427*(-0.33656) + 16513*(-0.36088) + 1170*(0.01878) + 477*(-0.19547)) / (30427 + 16513 + 1170 + 477) = -0.3349

- Predicted Value
f(x) = f(feature1 = 0 AND feature2 = 1) = -0.36088

Shapley Value for {feature2 = 1}:

Sequence 1 - {} ==> {feature2 = 1}: S = {} (Subset), N = 2 (# of all features), |S| = 0, |S|! = 1, apply Shapley Value formula
(|S|!*(N-|S|-1)!/N!)*(v(s+{feature2=1})-v(s)) = ((1!*(2-0-1)!)/2!)*( E(f(z)|{feature2=1}) - Base Value)
= 1/2*( (Total log_odds of {feature2 = 1} / Total Frequency) - Base Value)
= 1/2*( (16513*(-0.3609)+477*(-0.1955)) / (16513+477) - (-0.3349) ) 
= 1/2*( (-0.35624) - (-0.3349) ) = -0.01066

Sequence 2 - {feature1 = 0} ==> {feature1 = 0 AND feature2 = 1}: S = {feature1 = 0} (Subset), N = 2 (# of all features), |S| = 1, |S|! = 1, apply Shapley Value formula
(|S|!*(N-|S|-1)!/N!)*(v(s+{feature2=1})-v(s)) = ((1!*(2-1-1)!)/2!)*( f(x) - E(f(z)|{feature1=0}) )
= 1/2*( f(x) - (Total log_odds of {feature1 = 0} / Total Frequency))
= 1/2*( (-0.36088) - (30427*(-0.3366)+16513*(-0.3609)) / (30427+16513) ) 
= 1/2*( (-0.36088) - (-0.34512) ) = -0.0079

So Shapley Value for {feature2 = 1} is: -0.01066+(-0.0079) = -0.01854

However this is slightly different from output form SHAP package (-0.0181). I followed the standard Shapley Value formula. What is causing the difference? Any insights or response would be appreciated! Thanks in advance!

Best Regards,
Wei

**Comment by slundberg** [comment]
I don't see an obvious problem with how you were doing it. but if you post a runnable example that compares how you are doing it and how that differs from TreeExplainer I can take a look.

**Comment by kongwei9901** [comment]
Thanks Scott! I will post a runnable example later. Also quick question - Could it be cause TreeExplainer did some approximation rather than calculate the exact Shapley Value? But I do see your default option is "approximate = False"...

def shap_values(self, X, y=None, tree_limit=None, approximate=False):

**Comment by kongwei9901** [comment]
Scott, Below is a runnable exmpale. Thanks in advance! Really appreciate your help!

#################  Part I  ###################################
import xgboost
import shap
import numpy as np
import pandas as pd
import math

from xgboost import XGBClassifier

# load JS visualization code to notebook
shap.initjs()

# prepare training data
X, y = shap.datasets.adult()

# create a dummy variable from Age
X['ind_age30'] = np.where(X['Age'] >= 30, 1, 0)

# create a simple training data with ONLY 2 dummy variables
X1 = X[['Sex', 'ind_age30']]

# check dummy variables distribution
print(X1['Sex'].value_counts())
print(X1['ind_age30'].value_counts())

# train XGBoost model
params = {'n_estimators': 1, 'max_depth': 2, 'learning_rate': 0.01}
xgb = XGBClassifier(**params).fit(X1, y)

# explain the model's predictions using SHAP values
explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X1)

# visualize the first prediction's explanation
shap.force_plot(explainer.expected_value, shap_values[0,:], X1.iloc[0,:])

#################  Part II  ###################################

# get probability
y_pred = xgb.predict_proba(X1)

# calculate log odds in training data
X1['prob'] = y_pred[:,1]
X1['odds'] = np.log(X1['prob']/(1-X1['prob']))

# base value or global mean (log odds) matches
print("base value from SHAP: {}".format(explainer.expected_value))

print("Global model mean: {}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

# output value from SHAP: 0.00 f(x) matches
# output value for first record (log odds)
print("log odds for observation No. 1: {}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

# global mean/base value: E(f(z))
print("Global Mean E(f(z)): {0}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

# output value for first record (log odds)
print("Value for Obs No. 1 f(x): {0}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

# Conditional Expectation E(f(z)|{Sex=1}): -0.007767
(X1[X1['Sex']==1].groupby(['Sex'])['odds'].mean().reset_index())

# Conditional Expectation E(f(z)|{ind_age30=1}): -0.007165
X1[X1['ind_age30']==1].groupby(['ind_age30'])['odds'].mean().reset_index()

# Calculate Shapley Value of Sex = 1 for observation No. 1
# Two possible sequences: 
# 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
# 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

# Sequence 1: (E(f(z)|{Sex=1}) - E(f(z)))*1/2
print("Sex = 1 - sequence 1: {}".format((-0.007767 - (-0.010360810455412144))*1/2))

# Sequence 2: f(x) - E(f(z)|{ind_age30=1})
print("Sex = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007165))*1/2))

print("Shapley Value of Sex = 1 for observation No. 1: {}".format(0.001296905227706072+0.0014012049602375302))

# Calculate Shapley Value of ind_age30 = 1 for observation No. 1
# Two possible sequences: 
# 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
# 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

# Sequence 1: (E(f(z)|{ind_age30=1}) - E(f(z)))*1/2
print("ind_age30 = 1 - sequence 1: {}".format((-0.007165 - (-0.010360810455412144))*1/2))

# Sequence 2: (f(x) - E(f(z)|{Sex=1}))*1/2
print("ind_age30 = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007767))*1/2))

print("Shapley Value of ind_age30 = 1 for observation No. 1: {}".format(0.0015979052277060716+0.0017022049602375298))

# SHAP value for the first record from SHAP: array([0.00246863, 0.0035299 ], dtype=float32)
print("Shapley Value calculated by SHAP: {}".format(shap_values[0,:]))

print("Shapley Value for observation No. 1: [{0},{1}]".format(0.00269811, 0.00330011))

**Comment by kongwei9901** [comment]
Hi Scott, below is a runnable example. The difference is not large. Let me know what you think. Thanks a lot for your help!

-----------------------  Part I  --------------------------------------
import xgboost
import shap
import numpy as np
import pandas as pd
import math

from xgboost import XGBClassifier

##### load JS visualization code to notebook
shap.initjs()

##### prepare training data
X, y = shap.datasets.adult()

##### create a dummy variable from Age
X['ind_age30'] = np.where(X['Age'] >= 30, 1, 0)

##### create a simple training data with ONLY 2 dummy variables
X1 = X[['Sex', 'ind_age30']]

##### check dummy variables distribution
print(X1['Sex'].value_counts())
print(X1['ind_age30'].value_counts())

##### train XGBoost model
params = {'n_estimators': 1, 'max_depth': 2, 'learning_rate': 0.01}
xgb = XGBClassifier(**params).fit(X1, y)

##### explain the model's predictions using SHAP values
explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X1)

##### visualize the first prediction's explanation
shap.force_plot(explainer.expected_value, shap_values[0,:], X1.iloc[0,:])

-----------------------  Part II  --------------------------------------

##### get probability
y_pred = xgb.predict_proba(X1)

###### calculate log odds in training data
X1['prob'] = y_pred[:,1]
X1['odds'] = np.log(X1['prob']/(1-X1['prob']))

###### base value or global mean (log odds) matches
print("base value from SHAP: {}".format(explainer.expected_value))

print("Global model mean: {}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

###### output value from SHAP: 0.00 f(x) matches
###### output value for first record (log odds)
print("log odds for observation No. 1: {}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

###### global mean/base value: E(f(z))
print("Global Mean E(f(z)): {0}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

###### output value for first record (log odds)
print("Value for Obs No. 1 f(x): {0}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

###### Conditional Expectation E(f(z)|{Sex=1}): -0.007767
(X1[X1['Sex']==1].groupby(['Sex'])['odds'].mean().reset_index())

###### Conditional Expectation E(f(z)|{ind_age30=1}): -0.007165
X1[X1['ind_age30']==1].groupby(['ind_age30'])['odds'].mean().reset_index()

###### Calculate Shapley Value of Sex = 1 for observation No. 1
###### Two possible sequences: 
###### 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
###### 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

###### Sequence 1: (E(f(z)|{Sex=1}) - E(f(z)))*1/2
print("Sex = 1 - sequence 1: {}".format((-0.007767 - (-0.010360810455412144))*1/2))

###### Sequence 2: f(x) - E(f(z)|{ind_age30=1})
print("Sex = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007165))*1/2))

print("Shapley Value of Sex = 1 for observation No. 1: {}".format(0.001296905227706072+0.0014012049602375302))

###### Calculate Shapley Value of ind_age30 = 1 for observation No. 1
###### Two possible sequences: 
###### 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
###### 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

###### Sequence 1: (E(f(z)|{ind_age30=1}) - E(f(z)))*1/2
print("ind_age30 = 1 - sequence 1: {}".format((-0.007165 - (-0.010360810455412144))*1/2))

###### Sequence 2: (f(x) - E(f(z)|{Sex=1}))*1/2
print("ind_age30 = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007767))*1/2))

print("Shapley Value of ind_age30 = 1 for observation No. 1: {}".format(0.0015979052277060716+0.0017022049602375298))

###### SHAP value for the first record from SHAP: array([0.00246863, 0.0035299 ], dtype=float32)
print("Shapley Value calculated by SHAP: {}".format(shap_values[0,:]))

print("Shapley Value for observation No. 1: [{0},{1}]".format(0.00269811, 0.00330011))

**Comment by kongwei9901** [comment]
Scott, below is a runnable example. Thanks a lot for your help!! Appreciate it!

-------------------------------  Part I  -------------------------------------------------

import xgboost
import shap
import numpy as np
import pandas as pd
import math

from xgboost import XGBClassifier

###### load JS visualization code to notebook
shap.initjs()

###### prepare training data
X, y = shap.datasets.adult()

###### create a dummy variable from Age
X['ind_age30'] = np.where(X['Age'] >= 30, 1, 0)

###### create a simple training data with ONLY 2 dummy variables
X1 = X[['Sex', 'ind_age30']]

###### check dummy variables distribution
print(X1['Sex'].value_counts())
print(X1['ind_age30'].value_counts())

###### train XGBoost model
params = {'n_estimators': 1, 'max_depth': 2, 'learning_rate': 0.01}
xgb = XGBClassifier(**params).fit(X1, y)

###### explain the model's predictions using SHAP values
explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X1)

###### visualize the first prediction's explanation
shap.force_plot(explainer.expected_value, shap_values[0,:], X1.iloc[0,:])


-------------------------------  Part II  -------------------------------------------------

##### get probability
y_pred = xgb.predict_proba(X1)

###### calculate log odds in training data
X1['prob'] = y_pred[:,1]
X1['odds'] = np.log(X1['prob']/(1-X1['prob']))

###### base value or global mean (log odds) matches
print("base value from SHAP: {}".format(explainer.expected_value))

print("Global model mean: {}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

###### output value from SHAP: 0.00 f(x) matches
###### output value for first record (log odds)
print("log odds for observation No. 1: {}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

###### global mean/base value: E(f(z))
print("Global Mean E(f(z)): {0}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

###### output value for first record (log odds)
print("Value for Obs No. 1 f(x): {0}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

###### Conditional Expectation E(f(z)|{Sex=1}): -0.007767
(X1[X1['Sex']==1].groupby(['Sex'])['odds'].mean().reset_index())

###### Conditional Expectation E(f(z)|{ind_age30=1}): -0.007165
X1[X1['ind_age30']==1].groupby(['ind_age30'])['odds'].mean().reset_index()

###### Calculate Shapley Value of Sex = 1 for observation No. 1
###### Two possible sequences: 
###### 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
###### 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

###### Sequence 1: (E(f(z)|{Sex=1}) - E(f(z)))*1/2
print("Sex = 1 - sequence 1: {}".format((-0.007767 - (-0.010360810455412144))*1/2))

###### Sequence 2: f(x) - E(f(z)|{ind_age30=1})
print("Sex = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007165))*1/2))

print("Shapley Value of Sex = 1 for observation No. 1: {}".format(0.001296905227706072+0.0014012049602375302))

###### Calculate Shapley Value of ind_age30 = 1 for observation No. 1
###### Two possible sequences: 
###### 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
###### 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

###### Sequence 1: (E(f(z)|{ind_age30=1}) - E(f(z)))*1/2
print("ind_age30 = 1 - sequence 1: {}".format((-0.007165 - (-0.010360810455412144))*1/2))

###### Sequence 2: (f(x) - E(f(z)|{Sex=1}))*1/2
print("ind_age30 = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007767))*1/2))

print("Shapley Value of ind_age30 = 1 for observation No. 1: {}".format(0.0015979052277060716+0.0017022049602375298))

###### SHAP value for the first record from SHAP: array([0.00246863, 0.0035299 ], dtype=float32)
print("Shapley Value calculated by SHAP: {}".format(shap_values[0,:]))

print("Shapley Value for observation No. 1: [{0},{1}]".format(0.00269811, 0.00330011))

**Comment by kongwei9901** [comment]
Scott, below is a runnable example. The difference is NOT big. Let me know what you think. Thanks a lot! Appreciate your help!

Shapley Value calculated by SHAP: [0.00246863 0.0035299 ]
Shapley Value for observation No. 1: [0.00269811,0.00330011]

------------------------------  Part I  --------------------------------------------

import xgboost
import shap
import numpy as np
import pandas as pd
import math

from xgboost import XGBClassifier

###### load JS visualization code to notebook
shap.initjs()

###### prepare training data
X, y = shap.datasets.adult()

###### create a dummy variable from Age
X['ind_age30'] = np.where(X['Age'] >= 30, 1, 0)

###### create a simple training data with ONLY 2 dummy variables
X1 = X[['Sex', 'ind_age30']]

###### check dummy variables distribution
print(X1['Sex'].value_counts())
print(X1['ind_age30'].value_counts())

###### train XGBoost model
params = {'n_estimators': 1, 'max_depth': 2, 'learning_rate': 0.01}
xgb = XGBClassifier(**params).fit(X1, y)

###### explain the model's predictions using SHAP values
explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X1)

###### visualize the first prediction's explanation
shap.force_plot(explainer.expected_value, shap_values[0,:], X1.iloc[0,:])

------------------------------  Part II  --------------------------------------------

##### get probability
y_pred = xgb.predict_proba(X1)

###### calculate log odds in training data
X1['prob'] = y_pred[:,1]
X1['odds'] = np.log(X1['prob']/(1-X1['prob']))

###### base value or global mean (log odds) matches
print("base value from SHAP: {}".format(explainer.expected_value))

print("Global model mean: {}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

###### output value from SHAP: 0.00 f(x) matches
###### output value for first record (log odds)
print("log odds for observation No. 1: {}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

###### global mean/base value: E(f(z))
print("Global Mean E(f(z)): {0}".format(np.log(np.average(y_pred[:,1])/(1-np.average(y_pred[:,1])))))

###### output value for first record (log odds)
print("Value for Obs No. 1 f(x): {0}".format(np.log(y_pred[0,1]/(1-y_pred[0,1]))))

###### Conditional Expectation E(f(z)|{Sex=1}): -0.007767
(X1[X1['Sex']==1].groupby(['Sex'])['odds'].mean().reset_index())

###### Conditional Expectation E(f(z)|{ind_age30=1}): -0.007165
X1[X1['ind_age30']==1].groupby(['ind_age30'])['odds'].mean().reset_index()

###### Calculate Shapley Value of Sex = 1 for observation No. 1
###### Two possible sequences: 
###### 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
###### 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

###### Sequence 1: (E(f(z)|{Sex=1}) - E(f(z)))*1/2
print("Sex = 1 - sequence 1: {}".format((-0.007767 - (-0.010360810455412144))*1/2))

###### Sequence 2: f(x) - E(f(z)|{ind_age30=1})
print("Sex = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007165))*1/2))

print("Shapley Value of Sex = 1 for observation No. 1: {}".format(0.001296905227706072+0.0014012049602375302))

###### Calculate Shapley Value of ind_age30 = 1 for observation No. 1
###### Two possible sequences: 
###### 1. {} => {Sex = 1} => {Sex = 1, ind_age30 = 1}
###### 2. {} => {ind_age30 = 1} => {ind_age30 = 1, Sex = 1}

###### Sequence 1: (E(f(z)|{ind_age30=1}) - E(f(z)))*1/2
print("ind_age30 = 1 - sequence 1: {}".format((-0.007165 - (-0.010360810455412144))*1/2))

###### Sequence 2: (f(x) - E(f(z)|{Sex=1}))*1/2
print("ind_age30 = 1 - sequence 2: {}".format((-0.00436259007952494 - (-0.007767))*1/2))

print("Shapley Value of ind_age30 = 1 for observation No. 1: {}".format(0.0015979052277060716+0.0017022049602375298))

###### SHAP value for the first record from SHAP: array([0.00246863, 0.0035299 ], dtype=float32)
print("Shapley Value calculated by SHAP: {}".format(shap_values[0,:]))

print("Shapley Value for observation No. 1: [{0},{1}]".format(0.00269811, 0.00330011))

**Comment by slundberg** [comment]
I think it is because XGBoost weights calculates the cover of nodes based on the sum of the hessians. For linear regression that is the same as just counting samples, but not for logistic regression. In your example check out: `print(xgb.get_booster().get_dump(with_stats=True)[0])`

**Comment by kongwei9901** [comment]
I tried the calculation with cover, the results are almost the same with using frequency -
Shapley Value calculated by SHAP: [0.00246863, 0.0035299]
Shapley Value calculated with frequency for observation No. 1: [0.00269811, 0.00330011]
Shapley Value calculated with cover for observation No. 1: [0.00269864, 0.003299886]

**Comment by slundberg** [comment]
Check out the brute force implementation I just added and see if you can use that to find the issue: https://github.com/slundberg/shap/blob/04e7e35bde07484243a783fee5f0c32d4d41571e/tests/explainers/test_tree.py#L72-L127

**Comment by kongwei9901** [comment]
Thanks Scott! Will let you know if I found the reason!

On a side note, for any given record, is it safe to claim that (XGBoost Tree): SHAP of any subset of features = sum of SHAP value of each feature? E.g. I have a record {A=1, B=1, C=1}, SHAP({A=1, B=1}) = SHAP({A=1})+SHAP({B=1}), no matter if feature A and feature B are correlated or not, right? Use an extreme case, if SHAP({A=1})+SHAP({B=1})=0, that means {A=1,B=1} has 0 contribution to the model output, right? Thanks for your time!

Best,
Wei

**Comment by kongwei9901** [comment]
Scott,

I figured out why the two numbers do not match (Between my calculation and brute force code). Its caused by the conditional expectation calculation ( R(node_ind): ). Let me create some codes to show you. Maybe I will send you an email first.

Best,
Wei

**Comment by kongwei9901** [comment]
Scott,

I sent you an email regarding this issue. Let me know what you think when you have a chance....


Best,
Wei

**Comment by slundberg** [comment]
I think the issue you are seeing is because TreeExplainer approximates conditional expectations by traversing a tree and following both branches when a split depends on a feature we are not conditioning on. When input features are not independent then this process is not exactly the same as a full conditional expectation. In other words, Tree SHAP ignores feature dependencies except for features on the ancestor path of a node. This is actually nice, since it prevents credit from getting spread between two features that are correlated but only one is used by the model. It also ensures we only follow valid proportions down the tree since everything matches the training data distribution. Note that without directly providing the original dataset and then building a joint model we cannot exactly compute conditional expectations with feature dependence.
