### ISSUE TITLE
Running out of memory when testing segmented images

### ISSUE THREAD

**Issue by arinbjornk** [shap/shap#48]
I'm using the _ImageNet VGG16 Model with Keras_ notebook as a guide to test my own TensorFlow model and set of images.

The problem is that I run out of memory when doing:
`shap_values = explainer.shap_values(np.ones((1,50)), nsamples=1000)`

I can fit only 10 samples in memory which is not enough to generate the SHAP values for all 50 segmentations. Is there a way to call the SHAP explainer on each image segment permutation individually, instead of fitting them all in one batch?

One idea I had is:
```
shap_values <- zeros(n_segments)
while minimum(shap_values) is 0
    new_values <- explainer.shap_values(np.ones((1,50)), nsamples=small_number)
    shap_values <- element-wise_maximum(shap_values, new_values)
```
However, this results in a lot of redundant computation and I'm not sure if SHAP values from different runs are directly comparable like this.

**Comment by slundberg** [comment]
Hmm...I think the easiest would be to have the predict function you pass to
the explainer do chunking during the prediction. So if it gets called
asking for a 1000 samples you just compute it in batches of 10. That make
sense?

**Comment by arinbjornk** [comment]
Yes it does, that sounds like a good way to solve it. I think my predict function should be able to handle re-batching of the samples.

Thanks for the help

**Comment by slundberg** [comment]
Great.

**Comment by olathors** [comment]
Hey! I know I'm incredibly late to the party, but I also had this problem recently.

It turns out that GradientExplainer actually has a batch size you can set; the default is 50!

So you can do like this, for example:

shap.GradientExplainer(model, data, batch_size=10)

This saved me! I don't know how I missed this in the docs. 

If someone stumbles over this thread, I hope this can be of help.

**Comment by olathors** [comment]
I had a similar issue, but my problem was that the default batch size used for the background samples was 50, which was way more than my MacBook could handle.

I fixed the problem by manually setting a lower batch size like this:

shap.GradientExplainer(model, data, batch_size=16)

I know I'm incredibly late to the party, but perhaps this can help someone!
