### ISSUE TITLE
Best way to use SHAP for text without losing word position

### ISSUE THREAD

**Issue by OanaMariaCamburu** [shap/shap#486]
Hi,

There are a few comments about using SHAP for text, such as https://github.com/slundberg/shap/issues/40 or the notebook https://slundberg.github.io/shap/notebooks/linear_explainer/Sentiment%20Analysis%20with%20Logistic%20Regression.html

However, it is still not clear to me what is the best way to input the text. 
It seems like with the notebook approach we lose the position of the words. The solution in https://github.com/slundberg/shap/issues/40 was to append the position to the word, but this seems to _lose the importance of a single word_ (which I don't fully understand but I guess it may come from the change in the reference value?). The alternative would be using a 1-hot vector, but it's not clear how to input it. Blindly trying to input a 1-hot vector would raise the following error:
```
Traceback (most recent call last):
  File "explain_one_hot.py", line 140, in <module>
    shap_values = explainer.shap_values(x_batch_one_hot, nsamples=num_samples)
  File "/home/anaconda2/envs/py27/lib/python2.7/site-packages/shap/explainers/kernel.py", line 179, in shap_values
    assert len(X.shape) == 1 or len(X.shape) == 2, "Instance must have 1 or 2 dimensions!"
AssertionError: Instance must have 1 or 2 dimensions!
```

@slundberg also mentioned the DeepExplainer (that is now implemented) as a way to deal with all of the above. If that's the case, does anyone have a notebook on how to use it on text?

Thanks,
Oana

**Comment by slundberg** [comment]
Check out https://slundberg.github.io/shap/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html
