### ISSUE TITLE
Treeinterpreter 

### ISSUE THREAD

**Issue by Nadu123** [shap/shap#49]
Hi
I have the question that might seem naïve
Lets say i want to use the part of shap where we use the treeinterpreter  ..is that possible?
I know this is a unified approach , but lets say if i want aonly to test how it works by adding or removing different methods?
Like if i want to remove the lime part and test how this will work unifying the other approaches (deeplift, treeinterpreter

**Comment by slundberg** [comment]
I am not sure if I totally understand, but it sounds like you want to compare the results of Tree SHAP with those from the tree interpreter package by swapping out tree interpreter for shap in a pipeline?

For a comparison of the methods check out our Tree SHAP arXiv paper linked to in the readme (Saabas is the method used by tree-interpreter). The `approx_contribs=True` option in XGBoost will also match the tree interpreter method. To actually replace tree interpreter in your pipeline you would need Tree SHAP on sklearn models, which is not implemented yet.

**Comment by slundberg** [comment]
Closing this as `shap` TreeExplainer now supports sklearn tree models.
