### ISSUE TITLE
Creating a Custom React Component for Shap Figures

### ISSUE THREAD

**Issue by nextthelemann** [shap/shap#492]
Is there anyway to integrate shap to be used with a webapp. I can only generate the figures using an jupyter notebook, but when trying to convert the figures from matplotlib figures to plotly figures it either doesn't work or outputs wrong. I've looked around quite a bit, and I'm pretty confused on how to integrate this into a web app.

**Comment by slundberg** [comment]
For matplotlib I would just export as an image. For the JS code you can check out the javascript dir and see the react components that are used for notebook display. Please share if you end up packaging things for easy reuse :)

**Comment by jaller94** [comment]
What were the reasons to implement some plots in matplotlib and others in React & D3?

**Comment by peterpoliwoda** [comment]
It's sort of there but you might need to hack a bit. The documentation isn't great yet but you can use this package:
https://www.npmjs.com/package/shapjs

```Shell
$ npm install shapjs --save
```

then in your React you can create a component like so:

```JavaScript
import React from 'react';
import { AdditiveForceVisualizer } from 'shapjs';

const plotData = {your: 'data', from: 'some-flask-api'};

function ForcePlot(props) {
    return (
        <AdditiveForceVisualizer
            features={plotData.features}
            featureNames={plotData.featureNames}
            plot_cmap={plotData.plot_cmap}
            outNames={plotData.outNames}
            baseValue={plotData.baseValue}
            outValue={plotData.outValue}
            link={plotData.link}
            labelMargin={plotData.labelMargin}
        />
    );
}

export default ForcePlot;

```

Your Flask API will need to return the data in a dodgy Html <script> format, which can however be utilised:

```Python
p = shap.force_plot(explainer.expected_value, shap_values, vis_X_test.iloc[myind,:])
return p.html()
```

Good luck! And if you find an easier way to get the nice plots, please share.
