### ISSUE TITLE
I am using DeepExplainer, I need mini-batch.

### ISSUE THREAD

**Issue by linchundan88** [shap/shap#498]
Because GPU memory limitation, I implement a mini-batch version, even though my codes are not elegant.

#define explainer
background = np.load('ref.npy')
background1 = background[0:NUM_REFERENCE, :, :, :]
background2 = background[NUM_REFERENCE:NUM_REFERENCE*2, :, :, :]

e_list1 = []
for i in range(len(dicts_models)):
    e = shap.DeepExplainer(dicts_models[0]['model'], background1) 
    e_list1.append(e)

e_list2 = []
for i in range(len(dicts_models)):
    e = shap.DeepExplainer(dicts_models[0]['model'], background2)  
    e_list2.append(e)

'''generating saliency maps:'''
   
 shap_values1 = e_list1[model_no].shap_values(img_preprocess, ranked_outputs=ranked_outputs)
    shap_values2 = e_list2[model_no].shap_values(img_preprocess, ranked_outputs=ranked_outputs)

    shap_values = copy.deepcopy(shap_values1)
    for i in range(ranked_outputs):
        shap_values[0][i] = (shap_values1[0][i] + shap_values2[0][i])/2

**Comment by linchundan88** [comment]
I hope you can implement mini-batch, so I do not need...

**Comment by slundberg** [comment]
Thanks for sharing! Can't promise when that will happen, but am adding help wanted in case someone else has the bandwidth to do it.

**Comment by mhamilton723** [comment]
@slundberg can you point us to a place in the code where this could be bubbled up? we would like to try our hand at adding it. Thanks!
