### ISSUE TITLE
KernelExplainer: Getting correct result with a small number of features

### ISSUE THREAD

**Issue by kaas66** [shap/shap#5]
I used the KernelExplainer for a dataset with only three independent features.  It then produces wrong results. According to Scott Lundberg the reason probably is that he has hardcoded BIC lasso feature selection as a preprocessing step in the code. This is likely failing for the small example by incorrectly not selecting all the features before doing the kernel estimate.  Scott is working on adding a parameter to control feature selection (or turn it off) and meanwhile he wanted me to open a github issue for this task.

**Comment by slundberg** [comment]
I forgot about the `use_l1` option which existed to turn this off. However to allow better control in 806ade5 I changed this option to be `l1_reg` so user's can now control if they want `l1_reg="bic"`, `l1_reg="aic"` or a number `l1_reg=2.3`. By default `l1_reg="auto"` turns on lasso feature selection only when the space of possible feature masks is not well sampled (< 20%).
