### ISSUE TITLE
Summary plot of SHAP interaction values ordered by feature importance

### ISSUE THREAD

**Issue by samy101** [shap/shap#501]
I got the SHAP interaction values, using TreeExplainer for a xgboost model, and able to plot them using summary_plot. 
```
shap_interaction_values = treeExplainer.shap_interaction_values(x1)
shap.summary_plot(shap_interaction_values, features=x1, max_display=4)
```
![image](https://user-images.githubusercontent.com/1528106/54739079-b48f4300-4bf1-11e9-9917-839a56e83af6.png)

Is thera an option in the `summary_plot` to plot the shap interaction values one per row, similar to the summary plot for ordinary shap values? In the current plot, it is difficult to understand the order of the most important features (both main and interaction effects). 

My try is
```
dim = shap_interaction_values.shape
shap_interaction_values_2d = np.reshape(np.ravel(shap_interaction_values), (dim[0], dim[1]*dim[2]))

# make all pairs of features
x2 = x1[np.repeat(x1.columns.tolist(), len(x1.columns))]
x2.columns =  [i+":"+str(j) for i in x1.columns for j in x1.columns]

shap.summary_plot(shap_interaction_values_2d, x2, sort=True)
```
![image](https://user-images.githubusercontent.com/1528106/54747976-4c4d5b00-4c0b-11e9-88b0-3df50c4e8ca6.png)

Am I doing everything correct? Can I conclude that the most important interact effect is F0:F3 after the main effects of F3, F2, F0 and F1?

**Comment by jlevy44** [comment]
I'll second this. Would be quite interesting to see this feature.

**Comment by hetspookjee** [comment]
I've written a little bit of rough code I used to plot the dummy feature importances. In the end it's just the ordering of the arrays and data. Below is my code. I'm off for 2 weeks and when I'll get back and this issue is still open I'll try to refine it and make a PR.  Can also be done without pandas, but now the column names are retained, which is nice.

```python

import numpy as np
import pandas as pd

feat_df = pd.DataFrame(sorted(model.get_fscore().items(), 
                              key = lambda x: x[1], 
                              reverse=True), 
                       columns = ['Feature', 
                                  'Importance'])

feats = feat_df.sort_values('Importance')[::-1]['Feature'].head(15)

column_index = []
new_shap_ar = []
new_X = []
for c in feats.values:
    column_index = list(X.columns).index(c)
    new_shap_ar.append(shap_values[:, column_index:column_index+1])
    new_X.append(X.iloc[:, column_index])

new_X = pd.concat(new_X, axis=1)
new_shap_ar = np.hstack(new_shap_ar)

shap.summary_plot(new_shap_ar, new_X)
```

**Comment by ZhouYu44** [comment]
Friendly ping on this one. It's something I am interested in too. That will be very cool.

To my understanding, we could do something like MEAN(SHAP|feature1 x feature2) to measure the feature importance of any pairwise interaction and sort them by descending order. That will be interesting if we could do that.

**Comment by slundberg** [comment]
Now `plot_type="compact_dot"` enables this behavior :)

**Comment by tahsin314** [comment]
Is there a `shap_interaction_values` available for `DeepExplainer`?
