### ISSUE TITLE
No module named 'xgboost'

### ISSUE THREAD

**Issue by cerlymarco** [shap/shap#503]
In Jupyter (Pyhton 3.6):

```
import shap
from xgboost import XGBClassifier
shap.initjs()

model = XGBClassifier(n_estimators=500)
model.fit(x_trainc, y_trainc)

shap_values = shap.TreeExplainer(model).shap_values(x_testc)
shap.summary_plot(shap_values, x_testc)
```

The model fit well but when execute 'shap.TreeExplainer' gives this error:

XGBoost could not be imported!
....
ModuleNotFoundError: No module named 'xgboost'

**Comment by aditsanghvi94** [comment]
That's weird - i have used shap successfully with xgboost. Are you sure you have installed the correct package?

**Comment by hravkin** [comment]
> In Jupyter (Pyhton 3.6):
> 
> ```
> import shap
> from xgboost import XGBClassifier
> shap.initjs()
> 
> model = XGBClassifier(n_estimators=500)
> model.fit(x_trainc, y_trainc)
> 
> shap_values = shap.TreeExplainer(model).shap_values(x_testc)
> shap.summary_plot(shap_values, x_testc)
> ```
> 
> The model fit well but when execute 'shap.TreeExplainer' gives this error:
> 
> XGBoost could not be imported!
> ....
> ModuleNotFoundError: No module named 'xgboost'

@cerlymarco I had a similar issue. After a lot of checking around and trying different solutions, the thing that made it work was just reinstalling shap.

**Comment by dkloving** [comment]
Strange, I had exactly the same issue (after installing / upgrading xgboost after installing shap, not sure it it's related). Like @hravkin, I simply reinstalled and it works. Thanks for saving me a ton of time!
