### ISSUE TITLE
Hi! I had same problem with other issue. it is about summary_plot displaying gray plot

### ISSUE THREAD

**Issue by youngjinss** [shap/shap#513]
![image](https://user-images.githubusercontent.com/22973446/55002985-d554ff80-501a-11e9-955a-cf13e16491c4.png)

I'm using numpy version 1.16.0 and I just have a little of NaN value. but it looks so weird. 
Can you help me?

**Comment by slundberg** [comment]
Can you share the version of shap you are using and a snippet of the code that made that plot?

**Comment by alexpyj** [comment]
import shap
explainer = shap.DeepExplainer(model, x_train)
shap_values = explainer.shap_values(x_test)
...
shap.summary_plot(shap_values, x_test, feature_nemes=num2word)


-> shap_values,shape = (983,45), x_test = (983,45), type(num2word) = list
-> shap.__version__ = 0.28.3

**Comment by youngjinss** [comment]
> import shap
> explainer = shap.DeepExplainer(model, x_train)
> shap_values = explainer.shap_values(x_test)
> ...
> shap.summary_plot(shap_values, x_test, feature_nemes=num2word)
> 
> -> shap_values,shape = (983,45), x_test = (983,45), type(num2word) = list
> -> shap.**version** = 0.28.3

@slundberg

**Comment by anushamohan** [comment]
Hi Alex,

I used to get the summary plot that looks like yours when I train the model on sparse matrix and use the same to generate SHAP values. But once I converted the sparse matrix to dense array before training the model, the summary plot looks good.

<img width="609" alt="Screen Shot 2019-05-17 at 11 07 33 AM" src="https://user-images.githubusercontent.com/12536060/58202254-dc4f6580-7c8b-11e9-93fa-37730bd2aebb.png">
<img width="610" alt="Screen Shot 2019-05-17 at 11 07 41 AM" src="https://user-images.githubusercontent.com/12536060/58202255-dc4f6580-7c8b-11e9-9543-4b5f707f434a.png">

**Comment by bluemandora** [comment]
For xgboost model, the zero values in sparse matrix are treated as missing value. Convert to dense array will change predict output. Is there any other way to get colored summary plot for sparse matrix?

**Comment by JackieZhuJZ** [comment]
This happens to me as well. If I didn't standardize my features, the shape.summary_plot() will become gray, but once I standardized it, the plot looks just fine.

**Comment by EwunateAssaye** [comment]
I am getting gray image on shap_summary plot; my features were standardized but it is not working
