### ISSUE TITLE
Multivariate multiple regression

### ISSUE THREAD

**Issue by cp9612** [shap/shap#518]
Hello,

I'm trying to use SHAP to interpret multivariate multiple regression model. The shape of the input is NxM, where N is the number of samples, and M is the number of features. The shape of the output is Nx2. 

I used the RandomForestRegressor in sklearn to fit the data. Then I passed the model to TreeExplainer:

explainer = shap.TreeExplainer(RandomForestRegressor)
shap_values = explainer.shap_values(x_train)

I expected the shap_values consists of two NxM matrices, each of them corresponds to one of the response variables, but the shap_values only had one NxM matrices corresponds to the first response variable. I wonder if SHAP supports mutilple regression.

Thanks,

**Comment by slundberg** [comment]
Hey! Could you give more details or a working example? What you describe could happen for binary classification for two classes if the original model only outputs the probability for class 1, but it should not happen for two variable standard regression.

**Comment by cp9612** [comment]
For example, x_train.shape is (5000, 20) and y_train.shape is (5000, 2).
```
rf_regressor = RandomForestRegressor()
rf_regressor.fit(x_train, y_train)
rf_pred = rf_regressor.predict(x_train)

explainer = shap.TreeExplainer(rf_regressor)
shap_values = explainer.shap_values(x_train)
```
rf_pred.shape is (5000, 2), but shap_values.shape is (5000,20), which corresponds to the first response variable of y_train. Do I expect to see a list consists of two numpy matrix, and each of them has the shape (5000, 20)?

I also did a test on the Iris dataset with RandomForestClassifier. In this case, the shap_values is a list consists of three (150, 4) numpy matrices. It seems that it works fine with the classifier.

Thanks!

**Comment by slundberg** [comment]
I found the issue. It was a bad assumption that I made about the way sklearn formats its trees. The result was that we only loaded the first output of multi-output regression models from sklearn. I just pushed a fix. Can you verify it fixed it for you?

Thank you for pointing this out!

**Comment by cp9612** [comment]
It's fixed. Now the output is a list of two numpy matrices. Thanks!
