### ISSUE TITLE
summary_plot o dependence_plot save plot as vectorial format (PDF) rasterizing the points. I'd like to save in a pure vectorial way.

### ISSUE THREAD

**Issue by juanramonua** [shap/shap#522]
When I use:

`import shap

shap.summary_plot(shap_values, X_test, feature_names=x_sel_en, show=False)
plt.savefig('importance_scatter.pdf', format='pdf', dpi=1000, bbox_inches='tight')`

While the text is editable and maintains a vectorial format, the points of the scatter plot are rasterized. The points of each feature is represented as a rectangle with a transparent background with all its points. So, I need to set dpi to 1000 to preserve the quality of image to include it in a paper.

I'd like to save the plot in a pure vectorial format (PDF/SVG) in order to preserve its quality.
There is any way to do that?

Regards,

**Comment by slundberg** [comment]
In my experience you will do better with high res rasterized versions for space vs. quality. Right now it switches to raster when you have more than 500 points: https://github.com/slundberg/shap/blob/049b76dea0a8755d5e3ae060612fc712f81c8ae7/shap/plots/dependence.py#L195

You could change the `rasterized` lines in your copy, or add an option to control the threshold as a PR :)
