### ISSUE TITLE
Image plot PyTorch

### ISSUE THREAD

**Issue by DavidRuhe** [shap/shap#524]
I'm trying to use the image plot function on a PyTorch DeepExplainer but I'm not sure if it's working correctly. I'm using the MNIST code from https://github.com/pytorch/examples/tree/master/mnist.

Then, to make the image plot I do:

```
import shap
import numpy as np

# select a set of background examples to take an expectation over
background = next(iter(train_loader))[0][:100]
# explain predictions of the model on four images
e = shap.DeepExplainer(model, background)

shap_values = e.shap_values(next(iter(test_loader))[0][:5])

sv_transposed = [shap_value.transpose(0, 2, 3, 1) for shap_value in shap_values]

shap.image_plot(sv_transposed, -next(iter(train_loader))[0][:5].permute(0, 2, 3, 1).numpy())
```

The result:
![image](https://user-images.githubusercontent.com/9398113/55311841-43a72100-5464-11e9-9c72-a961a7f6ea72.png)

This doesn't seem right, does it? If you compare it to the plots on the shap GitHub example.

Thanks for the help!

**Comment by slundberg** [comment]
It does seem less intuitive than what I have seen the in past. Could be an odd model. To debug it is helpful to check and make sure the sum of the SHAP values equals the model output they are explaining (plus the expected_value base). Another thing to consider is if the 100 background samples are actually random (if they are all from the same class that would change things).
