### ISSUE TITLE
Can you color dependance plot based on the samples binary label?

### ISSUE THREAD

**Issue by digivi13** [shap/shap#525]
I am trying to color the individual data points on a dependency plot based on their binary class label. Is this possible? I am using xgboost for my model.

**Comment by slundberg** [comment]
You could always just make your own plot. But if you want to use dependence_plot you could fake it by setting a feature column to the output label and then forcing that to be the interaction index.

**Comment by digivi13** [comment]
Thats exactly what i'm trying to do, i'm going to try and overwrite the last feature in my X_test dataframe with the values from y_test generated from xgboost test_train function, i'll report back my method. Your plots look great in my web app by the way :)

<img width="803" alt="Screen Shot xgboost" src="https://user-images.githubusercontent.com/33264428/55429987-e0e48100-555a-11e9-95f3-bb22c5710866.png">

**Comment by digivi13** [comment]
Your suggestion works great!
To achieve this just use the following:

//convert series object to pandas dataframe
y_testdf = pd.DataFrame({'Target':y_test.values})
//overwrite the values in the dummy feature
X_test['dummy feature value here'] = y_testdf['Target'].values
//get shap values as normal..

**Comment by slundberg** [comment]
Great! Nice work. You can also use feature_names to rename the label for the colorbar

**Comment by ocean8800v** [comment]
> Thats exactly what i'm trying to do, i'm going to try and overwrite the last feature in my X_test dataframe with the values from y_test generated from xgboost test_train function, i'll report back my method. Your plots look great in my web app by the way :)
> 
> <img alt="Screen Shot xgboost" width="803" src="https://user-images.githubusercontent.com/33264428/55429987-e0e48100-555a-11e9-95f3-bb22c5710866.png">

May I ask what this is made of?
