### ISSUE TITLE
dependence plot for interaction values

### ISSUE THREAD

**Issue by mirimo1995** [shap/shap#527]
![image](https://user-images.githubusercontent.com/29410989/55462819-f065d780-55f7-11e9-9ae2-cd514599322f.png)
 xmin value is assigned to xmax. it  hinders deleting outliers from my plot.

Could you please fix it ? 

Thank you.

**Comment by mirimo1995** [comment]
@slundberg  Could you please help me on this ?

Thank you.

**Comment by slundberg** [comment]
Thanks for reporting this! Sorry it took a while :)
