### ISSUE TITLE
force_plot for single sample gets cut off

### ISSUE THREAD

**Issue by KPLauritzen** [shap/shap#53]
I'm following the Census income classification with scikit-learn notebook(https://slundberg.github.io/shap/notebooks/Census+income+classification+with+scikit-learn.html) and when I try to plot the shap_values for a single sample in the notebook, I can't get the full plot out.

Here is the output:
![shap1](https://user-images.githubusercontent.com/814491/38305288-a0e8eb70-380c-11e8-85b8-0b122319ca54.png)

Surprisingly, if I try to plot many samples there is no problem. See output:
![shap2](https://user-images.githubusercontent.com/814491/38305340-de869acc-380c-11e8-9719-6bf9c25e4f83.png)

I'm using python3, pip installed shap (0.12.0) in a jupyter notebook on windows.

**Comment by KPLauritzen** [comment]
I just noticed https://github.com/slundberg/shap/issues/18#issuecomment-358886456 and setting `width:100%` solves the problem. 

However, the fix suggested in https://github.com/slundberg/shap/issues/18#issuecomment-359115977 does not solve the problem. I have `iml`version 0.5.0 (the latest on PyPI as of today), and the problem persists. 

I am using Firefox by the way.

**Comment by slundberg** [comment]
Interesting. I thought this was fixed on FF last I checked. This happens with any notebook I assume?

**Comment by slundberg** [comment]
I can see it now on my end as well. Interestingly only when I rerun the
notebook. I'll see if I can debug it.

**Comment by KPLauritzen** [comment]
I'm not sure what you mean by "any notebook". But it is not just the example notebook that has the problem. I just used that to rule out that I was doing something obviously wrong. 

I tested on another computer (macOS, Chrome) and I can't seem to reproduce the problem there.

**Comment by slundberg** [comment]
Looks like there was another "px" issue not caught in #18. It should be fixed now with 0.12.1

**Comment by VEZcoding** [comment]
How to save force_plot for multiple Samples?

**Comment by Corne173** [comment]
I have the same issue when running it locally using Pycharm. The top of the figure gets cut off.
![Figure_1](https://user-images.githubusercontent.com/62875534/162745054-8fa6f7d1-5966-4980-a97a-284573fe6945.png)

 Couldn't find a solution in code but I did find a work around using the subplot configurations. 
![Figure_2](https://user-images.githubusercontent.com/62875534/162747365-560239f3-5f36-44b9-bf7e-9e61ff2493e0.png)

**Comment by TabeaPreusser** [comment]
@Corne173 I'm struggling with the same problem,  could you share a code snippet?
