### ISSUE TITLE
`javascript/build` contains `IML.React.*`, should be `SHAP.React.*` 

### ISSUE THREAD

**Issue by rishacha** [shap/shap#533]
The `build` folder shouldn't be committed. If it needs to be committed, then the package name should be correct.

The visualization would require `window.SHAP` and not `window.IML`.

**Comment by detrin** [comment]
@rishacha I don't see it here https://github.com/shap/shap/blob/master/javascript/build/index.html

@thatlittleboy Maybe a candidate for closing?

**Comment by thatlittleboy** [comment]
@detrin Thanks.

Yea we are using `window.SHAP` in the repo now, don't see any instances of `window.IML`.

**Comment by detrin** [comment]
Now 1.4k more to go ![](https://as1.ftcdn.net/v2/jpg/01/61/91/22/1000_F_161912241_Lk6edWxCyOOtarNLoDMaCTQ5Zb11cBQo.jpg)
