### ISSUE TITLE
Cite SHAP package in academic paper

### ISSUE THREAD

**Issue by cbeauhilton** [shap/shap#535]
Hello again!

If we are using the SHAP package in an academic paper, do you have a way you'd like us to cite the package directly (a la https://matplotlib.org/citing.html or, for an example that wasn't published in a journal per se, https://zenodo.org/record/1173090/export/hx#.XKeUlphKhEZ) , or would you like us to just use one of your recent papers (such as the one linked in the readme)?

Thanks!

**Comment by slundberg** [comment]
Thanks for asking! I added a new section at the bottom of the readme that now addresses this. (the short answer is please cite one of our associated papers)

**Comment by cbeauhilton** [comment]
Perfect, thanks!
