### ISSUE TITLE
Magnitude of SHAP Values Favoring Larger Magnitude Predictions?

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#538]
If I have a model that is predicting a growing variable such as age for instance, say I want to find the most significant features across the entire dataset. Wouldn't the features with the highest magnitude SHAP scores correspond to the important features for the highest age group?

Eg. X1 contributes +80 for age 81, while for age 0.81 the highest contributing feature only contributes + 0.8 

If so, how would one adjust for this when calculating overall importance???

**Comment by jlevy44** [comment]
What if I wanted to say that those two features each contributed significantly to their predictions? Should some normalization of the SHAP matrix occur?

**Comment by SaadAhmed96** [comment]
I think as we can calculate shap values for each row/example in our data set therefore we can also calculate the importance of each feature and its total contribution towards the model prediction by just adding up the shap value for that feature for each row/example.  This will give us the feature importance at a global level.

In my opinion, the real advantage of shap values is that we can intuitively understand what each feature is contributing to our prediction at the micro level. I hope this helps.

P.S: @slundberg please comment if my  explanation is correct or not.

**Comment by jlevy44** [comment]
Sure I completely understand the importances on the micro level, what I am trying to say is that if aggregating to the macro level (someone may want to know if the features across a certain classification, or age group are meaningful, and won't trust individual predictions unless the coarser level is considered and meaningful first), the features that may have contributed to lower magnitude predictions have their signal drowned out by contributions of features to predictions with higher magnitude. I'm speculating this, but if this is true, then someone may not trust the macro-level interpretations and thus not want to even look at micro-level predictions.

**Comment by jlevy44** [comment]
I do trust the micro-level, but others I've spoken to in my field want to be sure that there is interpretability on the macro level before going micro. 

I speculate whether aggregating across all ages to find key drivers of age would pick up features that are mostly related to older age.

**Comment by slundberg** [comment]
Using `np.abs(shap_values).mean(0)` will summarize the global importance of a feature as the mean of the absolute change in the prediction caused by that feature over the entire dataset. If the feature really only matters to old people, then yes, those are the samples that will drive the importance, but I don't think that would be wrong. Not sure if that answers your question though.

Perhaps a useful way to think about this is to consider a linear model with SHAP values as phi__ij = beta_i * (x_ij - E[x_i]), then reason about that.

**Comment by jlevy44** [comment]
I am familiar. Just wanted to see if we could capture the importance from underrepresented features. Probably best to just bin into smaller intervals and aggregate across those for interpretability.

**Comment by slundberg** [comment]
That could help. As I am sure you know, typical measures of global feature importance depend on both the prevalence of an effect in a population and the magnitude of the effect. One nice thing about local explanations is that you have the opportunity to try and tease those two things apart (such as by just looking at a subset of the population as you suggest).

**Comment by jlevy44** [comment]
Yeah, the only problem is that if my dimensionality is 300k (with good degree of collinearity), interpreting on the individual level may be problematic for individuals unfamiliar with these methods. I just believe from a trust-perspective, some may want a birds-eye view before they dig into specific local explanations. I do wonder a bit how much to trust local explanations for predictions on 300k feature matrices.

**Comment by slundberg** [comment]
As for trusting 300k features, I wouldn't trust a model agnostic approach, but I would trust TreeExplainer or LinearExplainer. However, trusting the explanation just means you trust that it reflects the true behavior of the model, it does not mean you should trust that the model is a good reflection of the real data generating process. So I would have all the same reservations I would have about a lasso model trained on 300k inputs.

**Comment by jlevy44** [comment]
I'm using GradientExplainer because my model was built using pytorch. Should I trust this?

Or is it just a general skepticism about a high dimensional feature space.

**Comment by jlevy44** [comment]
I know that you mention violations of an independence assumption

**Comment by slundberg** [comment]
GradientExplainer is also fine for high dim, I was just saying you don't want to use a sampling approach that scales with the number of input dims (like KernelExplainer). But yes, I also have a general skepticism of high dimensional feature spaces.

While talking about limitations, I should mention that for very deep conv nets (like res nets) I think GradientExplainer needs to be better evaluated, since it can easily find important features that are only important when you go "off-manifold" like an adversarial example.
