### ISSUE TITLE
Hangs on pip install -r requirements.txt 

### ISSUE THREAD

**Issue by jabrennem** [shap/shap#541]
I love this library. I could not find another issue with the same problem, but I just wanted to bring attention to a difficulty I have been having when installing shap on a newly created virtual environment. When I try to install in a requirements.txt, it hangs on shap. 
`/pathto/.env/bin/pip install -r requirements.txt`

My requirement.txt is 
numpy==1.16.2
pandas==0.24.2
shap==0.28.5

I saw that in the shap setup.py, it includes `import numpy`. I found a related issue that addresses this issue with pip. https://stackoverflow.com/questions/11015692/pip-fails-to-install-packages-from-requirements-txt

I tried their solution
`pip install numpy`
`pip install -r requirements.txt`
and it worked perfectly. It is just that the purpose of the requirements.txt is to minimize the installation of all the packages into one pip install command.

Is there a way you can remove the numpy import from setup.py?

**Comment by thatlittleboy** [comment]
Shouldn't be an issue anymore. numpy is specified as a build requirement, so will be installed by pip automatically before build.
