### ISSUE TITLE
Format of shap_values tensor using KernelShap?

### ISSUE THREAD

**Issue by KyleYoung1997** [shap/shap#543]
Hi I was just wondering in what order are the Shap values returned from the kernel explainer? 

Are the values contained in the shap_values list in the same order as predictions returned by model.predict(..)? 

Thanks!!

**Comment by detrin** [comment]
@KyleYoung1997 

> Hi I was just wondering in what order are the Shap values returned from the kernel explainer?
> Are the values contained in the shap_values list in the same order as predictions returned by model.predict(..)?

See https://github.com/shap/shap/blob/master/shap/explainers/_kernel.py#L111 then https://github.com/shap/shap/blob/master/shap/explainers/_kernel.py#L161 and for example here you can see that the order is preserved https://github.com/shap/shap/blob/master/shap/explainers/_kernel.py#L251 of course there are more cases in `shap_values`.
