### ISSUE TITLE
fstr_type deprecated in Catboost

### ISSUE THREAD

**Issue by GeraudK** [shap/shap#544]
Hi,

I'm trying to run the following dummy example:
```python
from catboost import CatBoostRegressor
import shap
X,y = shap.datasets.boston()

model = CatBoostRegressor(iterations=300, learning_rate=0.1, random_seed=123)
model.fit(X, y, verbose=False, plot=False)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
```
But I get the following
```python

AttributeError                            Traceback (most recent call last)

<ipython-input-1-c119d4ef4c26> in <module>
      6 model.fit(X, y, verbose=False, plot=False)
      7 explainer = shap.TreeExplainer(model)
----> 8 shap_values = explainer.shap_values(X)

~/src/research-incubation/catboost-cvr/.venv/lib/python3.6/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate)
    195             # note we pull off the last column and keep it as our expected_value
    196             if phi is not None:
--> 197                 if len(phi.shape) == 3:
    198                     self.expected_value = [phi[0, i, -1] for i in range(phi.shape[1])]
    199                     return [phi[:, i, :-1] for i in range(phi.shape[1])]

AttributeError: 'list' object has no attribute 'shape'
```
Looking into this I see that keeping the [fstr_type](https://github.com/slundberg/shap/blob/master/shap/explainers/tree.py#L188) param leads the output to be a list:
```
> Xp = Pool(X)
> type(model.get_feature_importance(data=Xp, fstr_type='ShapValues'))
list
```
Where with the correct param name you have an array:
```
> type(model.get_feature_importance(data=Xp, type='ShapValues'))
numpy.ndarray
```
I'm using shap 0.28.5 and catboost 0.13 where apparently the fstr_type was [deprecacted](https://catboost.ai/docs/concepts/r-reference_catboost-get_feature_importance.html)

**Comment by slundberg** [comment]
@annaveronika do you know why this would have changed? I can change `fstr_type` to `type`, but it looks like that will break people using a version of CatBoost older than two months...

**Comment by annaveronika** [comment]
Actually this should be a synonym now, it was an unintentional breaking change, but we fixed it, please try updating to 0.14.0

**Comment by GeraudK** [comment]
Updating to 0.14.0 fixed the issue. Thank you for your quick response.

**Comment by ghost** [comment]
I am using catboost version 0.15 and shap version 0.29.1, I got the same problem with fstr_type, with the following code 
```python
categorical_features_indices = np.where(X_train.dtypes != 'float')[0]
clf = CatBoostClassifier(loss_function='Logloss', verbose=True)
pool = catboost.Pool(X_train, y_train, cat_features=categorical_features_indices)
clf.set_params(use_best_model=False, reg_lambda=1.0)
clf.fit(pool, use_best_model=False)
explainer = shap.TreeExplainer(clf)
shap_values = explainer.shap_values(pool)
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-d38046ecb5e1> in <module>
      1 explainer = shap.TreeExplainer(clf)
----> 2 shap_values = explainer.shap_values(pool)

~/anaconda/lib/python3.6/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate)
    189                 if type(X) != catboost.Pool:
    190                     X = catboost.Pool(X)
--> 191                 phi = self.model.original_model.get_feature_importance(data=X, fstr_type='ShapValues')
    192 
    193             # note we pull off the last column and keep it as our expected_value

TypeError: get_feature_importance() got an unexpected keyword argument 'fstr_type'

**Comment by annaveronika** [comment]
Sorry, we'll update the version of catboost today. For now use 0.14.2

**Comment by annaveronika** [comment]
Added back in catboost 0.15.1. Sorry again for inconvenience.
