### ISSUE TITLE
Using SHAP for mixed data

### ISSUE THREAD

**Issue by liuhh02** [shap/shap#546]
I have a model that is trained on both raw text and additional quantitative features, and the text is vectorized using tfidf with 20000 columns (similar to the sentiment analysis example). However, I am using 4 additional quantitative features, so when I try to run the code `shap.summary_plot(shap_values, Xtest_full, feature_names=tfidf.get_feature_names())` or `shap.summary_plot(shap_values, Xtest_full[0:20000], feature_names=tfidf.get_feature_names())` I get the error:
> Traceback (most recent call last):
 File "<ipython-input-62-967c39077dde>", line 1, in <module>
    shap.summary_plot(shap_values, Xtest_full[0:20000], feature_names=tfidf.get_feature_names()
 File "C:\ProgramData\Anaconda3\lib\site-packages\shap\plots\summary.py", line 399, in summary_plot
pl.yticks(range(len(feature_order)), [feature_names[i] for i in feature_order], fontsize=13)
File "C:\ProgramData\Anaconda3\lib\site-packages\shap\plots\summary.py", line 399, in <listcomp>
pl.yticks(range(len(feature_order)), [feature_names[i] for i in feature_order], fontsize=13)
IndexError: list index out of range

and I get chart with the numbers that looks like this https://imgur.com/ruGQjvL. What am I doing wrong? Thank you!

**Comment by mattivi** [comment]
Were you able to solve this? What was the approached followed?

**Comment by liuhh02** [comment]
> Were you able to solve this? What was the approached followed?

Unfortunately, I wasn't able to solve this. So what I did in the end was to just plot the values for the text and not the additional features.
