### ISSUE TITLE
Using SHAP for object detection (SSD)

### ISSUE THREAD

**Issue by Slyces** [shap/shap#550]
Hello, first of all thank you for your work.

**Context**
I am currently working on a machine learning model using the [SSD](https://github.com/balancap/SSD-Tensorflow) architecture (*Single Shot MultiBox Detector*), using Keras.
My network is already trained, and I do not have the training dataset.

I'd like to use SHAP to explain the output of the network on some test data.

**Problem**
The output of my network has a shape of (? x n_box x 14) where n_box is a large number corresponding to the different 'boxes' where an object could be detected.
The ? corresponds to the number of samples, and the 14 contains a bunch of data, but most importantly the first 2 elements corresponds to the score of my two classes.

How can I use SHAP in such a context ? SHAP throws me an error about output's shape.

Thank you for your time

**Comment by slundberg** [comment]
Hey! Sorry for the slow response. Currently you will have to flatten your output before SHAP can handle it. So you would have add an extra reshape operation to get a shape of `(? x n_box*14)` or `(? x n_box*2)` if you just want to explain the first two classes. Afterwards you can reshape the results back if you like.

**Comment by MaxwellHogan** [comment]
@Slyces How has your experimentation gone with this? have you produced any work on the matter?

**Comment by Slyces** [comment]
Unfortunately no. I was doing this as part of an internship, and I didn't
come up with a solution involving Shap. I did design a method of XAI for
object detection but it wasn't really good.

Le sam. 1 mai 2021 à 13:55, Maxwell Redacted ***@***.***> a
écrit :

**Comment by MaxwellHogan** [comment]
@Slyces are you willing to share your method?

**Comment by Slyces** [comment]
Unfortunately the source is now under the property of the company I was
doing my internship at.

Le sam. 1 mai 2021 à 14:26, Maxwell Redacted ***@***.***> a
écrit :

**Comment by MaxwellHogan** [comment]
Some examples:

https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9784772

https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10445187
