### ISSUE TITLE
Typo in TreeEnsemble class causes no "internal" models

### ISSUE THREAD

**Issue by deniederhut** [shap/shap#555]
In the initialization for TreeEnsemble, self.model_type is set to "internel" instead of "internal":

https://github.com/slundberg/shap/blob/df22240d5693c6296a85d279da06c81167eb21dd/shap/explainers/tree.py#L372

this causes misbehaviors downstream in predicting SHAP values when this attribute is checked:

https://github.com/slundberg/shap/blob/df22240d5693c6296a85d279da06c81167eb21dd/shap/explainers/tree.py#L160

**Comment by deniederhut** [comment]
Looks like this was fixed in master 🤦‍♀️. Sorry for the noise!

**Comment by slundberg** [comment]
no problem :)
