### ISSUE TITLE
ExtraTrees issue

### ISSUE THREAD

**Issue by CanML** [shap/shap#556]
When looking at SHAP force plots, I noticed that when I use an ExtraTrees (sklearn) model, the "predicted value" on the force plot is simply the actual target value in my training set. When I use any other tree-based model (sklearn random forest or any GBT model from sklearn, LGBM, XGB, CatBoost, etc.), the force plot will correctly show the model's predicted value rather than the true target (y) value.

I have used this library quite extensively and successfully but until now hadn't tried it with ExtraTrees and this is the first issue of any kind I've run across.

The only single line of code I change between runs to change my model type is this:
model = RandomForestRegressor(n_estimators=200, random_state=1234)
        #model = ExtraTreesRegressor(n_estimators=200, random_state=1234)
        #model = LGBMRegressor(n_estimators=200, random_state=1234)

(uncommenting one of the three lines to select the model type I want to use)

All models show a very similar CV MSE fitness.

In every case when ExtraTreesRegressor is used, the SHAP values on the force plots appear to be based on the true target values, and the "predicted value" shown on each force plot is the actual target value for every single row in the dataset. In every case when any other model type is used, the force plots work as expected.

I would guess that ExtraTrees falls under the realm of TreeExplainer and that's what I'm using to generate the SHAP values:

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_train)

I didn't notice any existing issues here mentioning ExtraTrees. Has anyone else had a similar experience?

**Comment by slundberg** [comment]
Could you share a simple complete example to debug? ExtraTreesRegressor was added recently but I haven't heard of any issues

**Comment by jimmywan** [comment]
@CanML any chance that's a direct result of ExtraTreeesRegressor's default config of `bootstrap=False`?

**Comment by CanML** [comment]
Setting bootstrap=True indeed moves the values away from the exact targets. I had forgotten this was the default setting of ExtraTrees.

Thank you @jimmywan

If the intended behavior when bootstrap=False is as I've indicated, then all is well. If not, then please indicate if I can be of further assistance.

**Comment by CanML** [comment]
As a follow-up, is there an explanation somewhere on how exactly the predictions (i.e. the ones displayed on the force plots) for a trained tree-based model are arrived at for, say, XGB and LGBM? Are they forced to be "out-of-bag" in some way, or are they simply the raw predictions?

**Comment by mm5631** [comment]
@CanML Per Scott's comment in #536, 

> by default TreeExplainer explains the margin of the model (before the link function). There is an option to explain the transformed version for probabilities (logit link)

So uses raw predictions if I'm not mistaken

**Comment by CanML** [comment]
@maximemerabet thank you very much for your reply. That makes sense.

I know we are outside the realm of an issue at this point but I will ask one more question in case anyone has a recommendation.

I am trying to generate CV predictions (via a method like cross_val_predict in sklearn) and would like to take those specific CV predictions and view the shap values for them. Is there a better way than to decompose each CV fold's specific fitted model and extract shap values from each one? If I have 10 folds, for example, this would require 10 calls of TreeExplainer I believe.

**Comment by mm5631** [comment]
You can usually retrieve the split indices from the sklearn cross validators (Kfold, etc) and then you’d be able to call an explainer on each fold to get your shap_values for each fittted fold, then average them. You could also write your own CV.

**Comment by CanML** [comment]
Thanks @maximemerabet . Again makes sense.

I will now close this as I don't think there are any issues here. Perhaps this discussion can be useful to others in the future.
