### ISSUE TITLE
Agnostic explanation without the model

### ISSUE THREAD

**Issue by AlbertoSabater** [shap/shap#56]
Hi! Is there any way to make an agnostic explanation (get shap values) without the trained model? I mean, just use the train/test dataset and its expected/obtained output, no model involved in the process of the explanation.

**Comment by echo66** [comment]
Im quite confused...what do you want to achieve with that?

**Comment by slundberg** [comment]
I assume you mean you don't have access to the original model, but just the outputs from some black box you can't run yourself. In that case, the best you can do is train some kind of mimic model, then explain the mimic model. Train XGBoost for example on the input output pairs you have from the original model, then explain that XGBoost mimic model for the inputs.

**Comment by AlbertoSabater** [comment]
Yes, I mean what @slundberg says. I would like to know if there is an alternative to building a mimic model. But I guess that is the best option.

**Comment by echo66** [comment]
@slundberg @AlbertoSabater after taking a look at one of the notebooks that uses KernelExplainer, I noticed that you don't actually need a model. Just pass some function, in the constructor, that calls your black box model in some way.

**Comment by AlbertoSabater** [comment]
Yes, you are right, but that is not what I am looking for.
I have some users clustered according to a small group of features (first set), but for each user, I have much more features (second set). I want to explore what are the differences on the second set of features for users from different clusters.
It would be great if there was any way to get the influence of the features from the second set given the cluster of each user. But I think that is not possible. The best way to do it is what you said, train a model (XGBoost) to classify users to each cluster given the second set of features.
