### ISSUE TITLE
shap values not adding up to margins 

### ISSUE THREAD

**Issue by abraham-abin13** [shap/shap#560]
Hi I am trying to get shap values however, when I check to make sure they add up to the margin they do not. 

Here is the code I am using: 

   ```
# load 
    input_df = pd.read_csv(input_file, sep="\t")
    best_model = pickle.load(open(model_file, 'rb'))
    
    
    # train and test 
    xtrain = input_df.loc[input_df['partition']=="grid_cv", input_df.columns[1:-2]].copy()
    xtest = input_df.loc[input_df['partition']=="held_out", input_df.columns[1:-2]].copy()
    ytrain = input_df.loc[input_df['partition']=="grid_cv", input_df.columns[-2]].copy()
    ytest = input_df.loc[input_df['partition']=="held_out", input_df.columns[-2]].copy()

    # get setting from hyperparamter tuned model 
    bst_params = best_model.get_params()
    best_xgb_rf = XGBClassifier(**bst_params)
    best_xgb_rf.fit(xtrain, ytrain)

    # get shap and comapre to output 
    boost_  = best_xgb_rf.get_booster()
    shap_matrix = boost_.predict(xgb.DMatrix(xtrain, label=ytrain), pred_contribs=True)
    margin = boost_.predict(xgb.DMatrix(xtrain, label=ytrain,  feature_names=input_df.columns[1:-2]), output_margin=True)
    
    assert np.all(np.round(margin) == np.round(np.sum(shap_matrix, 1))), "shap values don't add up to margins"
```

Here is what I have already tried: 
- fitting the model with the first five rows yields no error when checking to make sure the margin ==  sum of shap 
- I also calculated the shap values using the by importing the shap package and this results in the same error. The SHAP values are on the order of 1000s while the margins are under 10, the expected bias is ~0.0005. 

I am not sure why this is happening. Especially given the first five rows does not have a probelm. Any guidance on where to start debugging would be very helpful.

Thank you!

**Comment by tstearns26-zz** [comment]
what version of xgboost? i'm having the same problem...

**Comment by slundberg** [comment]
Could you share a complete example I can reproduce? There are unit tests for this summation, so it is certainly should work normally. Note however that you also need to add the expected margin value to get an exact match.
