### ISSUE TITLE
linear shap + error with sparse input 

### ISSUE THREAD

**Issue by yramon** [shap/shap#569]
Hi there,

I have two questions. 

1)

When using the function
**shap_values = explainer.shap_values(instance_idx, nsamples=5000)**
where instance_idx is a dense numpy array, SHAP works fine. 

However, when I use a **sparse** input I get the following error:

File "C:\Users\yramon\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\kernel.py", line 503, in addsample
    self.synth_data[offset:offset+self.N, groups] = x[0, groups]

ValueError: setting an array element with a sequence.

Does anyone has an idea how to fix this, because the current implementation should support sparse inputs, I suppose?

2)

I would like to use the linearSHAP as well. When I use as model a logistic regression (scikit), and as reference value zeros, I get the following error:

Reference_value=np.zeros(np.shape(x_test)[1])
RV=np.reshape(Reference_value,(1,len(Reference_value)))

explainer=shap.LinearExplainer(model,RV,feature_dependence="independent")
Traceback (most recent call last):

  File "<ipython-input-55-836f70b4a79d>", line 1, in <module>
    explainer=shap.LinearExplainer(model,RV,feature_dependence="independent")

  File "C:\Users\yramon\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\explainers\linear.py", line 76, in __init__
    self.valid_inds = np.where(np.diag(self.cov) > 1e-8)[0] #np.diag weggedaan

  File "C:\Users\yramon\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\twodim_base.py", line 265, in diag
    raise ValueError("Input must be 1- or 2-d.")

ValueError: Input must be 1- or 2-d.

Does anyone have an idea how I can fix this? 

Many thanks,

YR

**Comment by imatiach-msft** [comment]
@yramon  for the first issue, would you be able to send a repro?  You are correct that should work.

**Comment by yramon** [comment]
@imatiach-msft , I managed to solve this issue with the sparse input.
I forgot to change the reference value to a sparse format as well, so I added the this line to make the reference value have a sparse format as well

Reference_value=np.zeros(np.shape(x_test)[1])
RV=np.reshape(Reference_value,(1,len(Reference_value)))
RV=sparse.csr_matrix(RV)

Many thanks for your help.
