### ISSUE TITLE
Binary CatBoost classifier using TreeExplainer with model_output='probability' and tree_dependence='Independent'

### ISSUE THREAD

**Issue by jayantsahewal** [shap/shap#576]
I know there are similar issues already which talk about multi-class and/or not using feature_dependence='Independent'. I put a comment in one of the issues as well but that has been tagged with label "To Do". I wasn't sure whether someone will be looking at that issue or not. So, I thought of creating an issue here since it's slightly different.

In my case, I am getting the same issue even with a binary CatBoost classifier. Based on the code base, it looks like if model output is not margin and feature_dependence is set to "Independent" even then it will always throw an error because objective attribute for CatBoost classifiers hasn't been defined and it will always remain None. Is it possible to make it work for at least binary CatBoost classifiers?

```
if model_output != "margin":
    if self.model.objective is None and self.model.tree_output is None:
        raise Exception("Model does have a known objective or output type! When model_output is " \
"not \"margin\" then we need to know the model's objective or link function.")


elif str(type(model)).endswith("catboost.core.CatBoostClassifier'>"):
    assert_import("catboost")
    self.model_type = "catboost"
    self.original_model = model
```

**Comment by dvpolyakov** [comment]
@jayantsahewal , luckily I have implemented this feature) I have opened a pull request https://github.com/slundberg/shap/pull/578 and I hope that it will be merged by Scott soon, and the updates will be available in the closest release

**Comment by jayantsahewal** [comment]
@dvpolyakov Thanks for implementing it!

I looked at your code in the pull request and it looks fine to me. Just one comment, I would suggest using np.float64 instead of np.float32 for the dtype. I have experienced many issues with np.float32. Though, those are edge case. But, it's still better to avoid it if possible.

**Comment by pmeier-tiplu** [comment]
minor detail: it should be "probability" (with an `a`)
