### ISSUE TITLE
Reshap error for SHAP calculation

### ISSUE THREAD

**Issue by kongwei9901** [shap/shap#580]
Hi Scott,

We got a reshape error when trying to test SHAP on our data. Have you seen something similar?
    ValueError: cannot reshape array of size 207506055 into shape (255235,0,815)

Also please see similar errors reported here
https://github.com/dmlc/xgboost/issues/4276
https://discuss.xgboost.ai/t/scala-spark-xgboost-v0-81-shap-problem/817/2

Let me know if you need to more information to investigate.

Best,
Wei

**Comment by kongwei9901** [comment]
Error is pointing to the XGBoost code:

...anaconda3/lib/python3.7/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate)
    177                 phi = self.model.original_model.predict(
    178                     X, ntree_limit=tree_limit, pred_contribs=True,
--> 179                     approx_contribs=approximate, validate_features=False
    180                 )
    181 

.../anaconda3/lib/python3.7/site-packages/xgboost/core.py in predict(self, data, output_margin, ntree_limit, pred_leaf, pred_contribs, approx_contribs, pred_interactions, validate_features)
   1310                     preds = preds.reshape(nrow, data.num_col() + 1)
   1311                 else:
-> 1312                     preds = preds.reshape(nrow, ngroup, data.num_col() + 1)
   1313             else:
   1314                 preds = preds.reshape(nrow, chunk_size)

ValueError: cannot reshape array of size 207506055 into shape (255235,0,815)

**Comment by kyoungrok0517** [comment]
@devs Any updates??

**Comment by andreanuzzo** [comment]
Happened to me as well. ~~With a bigger impact dataset it does not happen, looks like there should be a reshape(nrow, ngroup, data.num_col() + 1, -1) to make lumpy figure out the third dimension automatically?~~ It's an xgboost issue

**Comment by slundberg** [comment]
Hey, thanks for reporting this! Sorry I lost track of the issue thread. I think this problem was fixed in the latest XGBoost master. If not though, I can look back into it. What versions are you using of XGboost when you see the problem?

**Comment by kongwei9901** [comment]
Hi Scott,

We were using xgboost 0.81 and 0.82. Let me know if you need more information to investigate. We will try xgboost 0.9 from our end as well. Thanks for your time!

Best,
Wei

**Comment by andreanuzzo** [comment]
I am using version 0.90 of xgboost (py3.6)

 Andy

**Comment by Lesley96** [comment]
I got the same reshape error.  Have you fixed the problem?

**Comment by msaitkulov** [comment]
@slundberg, same problem, with xgboost 0.90(py3.6), tried two version of shap  - 0.29.1 and 0.29.3
It's quite popular problem

**Comment by slundberg** [comment]
Can anyone share a simple notebook demonstrating the problem? I’ll try and debug anything I can reproduce. Thanks!

**Comment by MarineN1** [comment]
Hello, are there solutions to this issue ?
Thanks

**Comment by pyotam** [comment]
I'm not sure if this is related to: #743 
But as I mentioned, I am experiencing a similar issue with LightGBM:

`shap_values = shap.TreeExplainer(clf).shap_values(dataset.iloc[:10000,:])`
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/kaggle_env/lib/python3.7/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate)
    196                     phi = np.concatenate((-phi, phi), axis=-1)
    197                 if phi.shape[1] != X.shape[1] + 1:
--> 198                     phi = phi.reshape(X.shape[0], phi.shape[1]//(X.shape[1]+1), X.shape[1]+1)
    199 
    200             elif self.model.model_type == "catboost": # thanks to the CatBoost team for implementing this...

ValueError: cannot reshape array of size 23020000 into shape (10000,1,1155)
```
where dataset.shape is: (472432, 1154)

**Comment by saberian** [comment]
I am facing the same issue. The code works for one model and doesn't work for another one.

**Comment by slundberg** [comment]
@pyotam that looks like it is with a LightGBM model. I have not been able to reproduce this on my end, so if anyone has a notebook that shows this I would be happy to debug it.

**Comment by saberian** [comment]
@slundberg I sent you a small notebook.

**Comment by saberian** [comment]
In my case it turned out that I was removing some of the features during training and not removing them at the time of prediction + SHAP computation. It is strange that the model was able to do the prediction! but thankfully SHAP computation complained!

**Comment by gidonk** [comment]
Hey, maybe it will assist some of you guys.
I had the same error after installing altair and vega.
once uninstalling them everything worked just fine

**Comment by ianozsvald** [comment]
I'll +1 @saberian's comment, using XGBoost 0.9 and sklearn 0.22 I had the same error message in a complex Notebook, it turns out I was passing the raw `X` (with all features) to shap but had trained XGBoost on a _subset_ of features. 

The error message didn't make this clear:
```
shap_values = explainer.shap_values(X_train) # missing column mask
...
ValueError: cannot reshape array of size 93058 into shape (13294,0,33)
(from xgboost/core.py)
```

_Possibly_ it might help others to add a hint inside SHAP to spot this user-error?

**Comment by slundberg** [comment]
@ianozsvald good idea, I added note to the exception that points to this issue. Closing this since I think this problem now only comes from passing bad data matrices, and we now have a good error message for this.

**Comment by msaitkulov** [comment]
I cannot get.
Shap is adding 3 extra columns or who...
I have  a shape (1559458, 634), but Shap see it as (1559458, 637)..
<img width="706" alt="Screenshot 2020-01-10 at 15 02 27" src="https://user-images.githubusercontent.com/28587948/72152002-cdecc000-33ba-11ea-973c-0269457639d0.png">

**Comment by msaitkulov** [comment]
@slundberg , maybe you know how to solve above problem?🙏🏻

**Comment by msaitkulov** [comment]
> I cannot get.
> Shap is adding 3 extra columns or who...
> I have a shape (1559458, 634), but Shap see it as (1559458, 637)..
> <img alt="Screenshot 2020-01-10 at 15 02 27" width="706" src="https://user-images.githubusercontent.com/28587948/72152002-cdecc000-33ba-11ea-973c-0269457639d0.png">

looks like my booster from scala contains smth more than needed..

**Comment by gomcheol** [comment]
@msaitkulov I don't know 3 extra columns in shap_values. but, In my experience, I recommend you to use shap_values like this; Use iloc rather than specific column list (I don't know why... just experience, perhaps because of ndarray..?)
![image](https://user-images.githubusercontent.com/26731452/72326023-b6327600-36f1-11ea-969b-feb3964c0189.png)
![image](https://user-images.githubusercontent.com/26731452/72326147-f4c83080-36f1-11ea-8646-34cfcf0e631a.png)

**Comment by RaulRomero** [comment]
I had the same problem with LGBM and turned out to be pretty easy to solve: 

I was passing more columns than the ones the model was trained with.

**Comment by Bonnieliuliu** [comment]
Yes. The reason behind is that you are **passing** more columns in the explainer than the trained-model

**Comment by xxjgithub** [comment]
I faced the same problem with lightGBM， the reason is that the columns in the explainer is not the same as the trained_model, is it right?  If so, that means we must gaurantee  the length of  columns in the explainner equals to the length of columns in the trained model

**Comment by tushitdave** [comment]
look like this bug is still continued while doing SHAP on XGB Classifier. 

ValueError: This reshape error is often caused by passing a bad data matrix to SHAP. See https://github.com/slundberg/shap/issues/580
Traceback:
File "c:\users\tushi\anaconda3\lib\site-packages\streamlit\ScriptRunner.py", line 322, in _run_script
    exec(code, module.__dict__)
File "D:\Project_CGI_INSOFE\pickle\cgi.py", line 55, in <module>
    shap_values = explainer.shap_values(X_train_sample).reshape(-1,1)
File "c:\users\tushi\anaconda3\lib\site-packages\shap\explainers\_tree.py", line 278, in shap_values
    "See https://github.com/slundberg/shap/issues/580") from e

**Comment by LiWangSH** [comment]
Hi  @slundberg,

Thank you for the thread! I read through it and double checked the length of columns I passed to the shape.TreeExplainer as well as the length of columns in my trained XGBClassifier. They were the same. However, I still encountered the same error. Please see the screen shot below.
![Screen Shot 2020-12-08 at 1 13 40 PM](https://user-images.githubusercontent.com/60442885/101542125-317ac700-3957-11eb-83fa-f520d697b38e.png)

I checked the source code, https://github.com/slundberg/shap/blob/master/shap/explainers/_tree.py#L320-L339, but did not find anything else that could explain the error. 

What is your thought on it? Thank you so much for your help!

**Comment by VolodyaCO** [comment]
I confirm that this is a very strange error. I am particularly facing it when resampling:

```python
# Quick test that everything works ok:
dtest = xgb.DMatrix(features)
model.predict(dtest)
print('features are ok!')
print(features.shape)

# Shap implementation of model
explainer = shap.TreeExplainer(model)

X = shap.sample(features, 100)
print( type(X), X.shape )

model.predict(xgb.DMatrix(X))
shap_values = explainer.shap_values(xgb.DMatrix(X))
```

When I run it I get this:

```shell
features are ok!
(544401, 92)
<class 'pandas.core.frame.DataFrame'> (100, 92)
Traceback (most recent call last):
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-eS63OEPi/lib/python3.8/site-packages/shap/explainers/_tree.py", line 280, in shap_values
    phi = self.model.original_model.predict(
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-eS63OEPi/lib/python3.8/site-packages/xgboost/core.py", line 1397, in predict
    preds = preds.reshape(nrow, ngroup, data.num_col() + 1)
ValueError: cannot reshape array of size 23400 into shape (100,2,93)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "shapsummaryplots.py", line 122, in <module>
    shap_summary_plots(2014, 2)
  File "shapsummaryplots.py", line 97, in shap_summary_plots
    shap_values = explainer.shap_values(xgb.DMatrix(X))
  File "/home/vladimir/.local/share/virtualenvs/ICFES-SocioEconomico-eS63OEPi/lib/python3.8/site-packages/shap/explainers/_tree.py", line 285, in shap_values
    raise ValueError("This reshape error is often caused by passing a bad data matrix to SHAP. " \
ValueError: This reshape error is often caused by passing a bad data matrix to SHAP. See https://github.com/slundberg/shap/issues/580
```

so out of nowhere it seems that SHAP is passing new data to XGBoost? (`ValueError: cannot reshape array of size 23400 into shape (100,2,93)`)

Definitely I'm passing the correct number of columns, no matter if I sample or not the features dataframe, as `model.predict(xgb.DMatrix(X))` works ok, but then when getting the shap values with the explainer it fails!

My shap version is 0.37 and my xgboost version is 1.2.1

**Comment by PLPATENOTRE** [comment]
Hi there ! 

I come late to the battle but finally got the solution to the issue.

```python

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X, y=y.values)
```

This worked for me. And be careful that your model matches with your X_train, in term of number of columns.

Hope this helps ! 
Cheers

**Comment by green-slowmoe** [comment]
awesome, had the same problem. passing df.values instead of df did the trick for me too!

**Comment by neil-rubens** [comment]
# Problem
`num_features` of your `model ` and `X` may not the same (even if it appears that they are)

# Problem Origin

This happens due to the different data types used by:

- `xgboost` : `scipy.sparse.csr.csr_matrix`
-  `shap` :  `xgboost.DMatrix`

The problem is due to the following combination

1) potentially reduced dimensions when you call `xgb.DMatrix(X)` (sparse -> dense); if the higher numbered features are not present in data (in the sparse format).  e.g. if you have `100` features; and `100`'s feature is not present in your data; the dimension of DMatrix will become `99`

2) `shap`  throws an exception if data has lower dimensions than expected; a proper fix would be to add a parameter that would let `shap` assume that lower dimensional data doesn't have higher dimensional features

# Temporary Fix

In your sparse data file e.g. `.lsvm` add a row to the data with the highest dimension (you can delete it after conversion); e.g. for `100` dimensions:
```
0 99:0
``` 
p.s. first 0 is a label in my case; and 99 since it is 0-based

This fill force DMatrix to have `100` dim instead of a lower one.

# Code Sample

```py
import xgboost as xgb
import shap
from xgboost import Booster
import json
import sklearn

# load model
model = Booster()
model.load_model("xgb.model")
print(model.save_config())

model_config = json.loads( model.save_config() )
num_features = int( model_config["learner"]["learner_model_param"]["num_feature"] )
print(num_features)


X, y = sklearn.datasets.load_svmlight_file("sample_data.lsvm")
print( X.shape, type(X) )
print( y.shape, type(y) )

# IF NOT EQUAL WILL CAUSE SHAP EXCEPTION; then see Temporary Fix Section in this post on how to fix it
assert num_features == X.shape[1]   


explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(xgb.DMatrix(X))

shap.summary_plot(shap_values, X)
```

**Comment by nasirudeenraheem** [comment]
The problem is not about reshaping. if it is a binary classification it is expected to have 2 dimensions.
solution = pd.DataFrame(shap_values[0]) # prediction for shap values that are false.
solution = pd.DataFrame(shap_values[1]) # prediction for shap values that are true.

**Comment by inigoasensiorey** [comment]
is it fixed this bug? I cannot use shap values with XGBoost Classifier object?

**Comment by abu034004** [comment]
**Is it true that the SHAP value of a feature should be centered around 0?** I was going over the SHAP summary plot of the effects of all the features (`shap.plots.beeswarm(shap_values)`) from your Github link [https://github.com/slundberg/shap](url) but it looks like the SHAP values of all the features in that plot are centered around 0. It would be helpful if you please answer my question. Thank you!

**Comment by TiankangXie** [comment]
Is the bug fixed? It seems that I am still suffering from the problem of XGB, sparse data & shap values

**Comment by jortizta** [comment]
I was able to fix this issue by updating XGBoost. In my case the error was caused by this XGBoost bug (https://github.com/dmlc/xgboost/issues/7880) not by the shap library.

**Comment by arilwan** [comment]
All the walkaround mentioned here didn't work for me.
```
XGBClassifier version: 2.0.1
Shap version: 0.43.0
Model's number of features: 55
Number of features in test set: 55

ValueError: This reshape error is often caused by passing a bad data matrix to SHAP. See https://github.com/shap/shap/issues/580.
```

What helped me was downgrading to `xgboost==1.7.4`

**Comment by rajv96** [comment]
xgboost version == 2.0.1
shap version == 0.42.1

I'm getting this error which says "**ValueError: This reshape error is often caused by passing a bad data matrix to SHAP. See https://github.com/shap/shap/issues/580.**"

I checked the shape of train and test datasets. They are the same. Can anyone update me as to why am I getting this error?
I tried upgrading and downgrading both package versions but still it does not work.

**Comment by rajv96** [comment]
I was able to resolve the issue.

I used xgboost==1.6.2 and shap==0.42.1

I believe it has nothing to do with the version you use. The error is caused because you might be returning a numpy object or pandas object using xgboost and shap. This is not supported I believe by the xgboost library.
I converted the pandas dataframe I was using to a dictionary and the issue was resolved.

Thanks!

**Comment by Philipp3211** [comment]
For me the error happened if I put "too many" data points into `shap_values`. When I subsampled the data (fewer rows) I was able to circumvent the error.

**Comment by showkeyjar** [comment]
same problem, but XGBRegressor, 

python 3.11.6
xgboost 1.7.6
shap 0.44.1
