### ISSUE TITLE
Given a shap value for an interaction, how do i trace back the actual record?

### ISSUE THREAD

**Issue by jraju9** [shap/shap#583]
I'm trying to look at all the records with a specific shap value for an interaction.  I was wondering if there is an easy way to do it?

Thank you,
J

**Comment by detrin** [comment]
@jraju9 Thanks for the question. What do you exactly mean by "a specific shap value for an interaction".

**Comment by thatlittleboy** [comment]
The shap values array should be of size `(N, k)` where `N` is the number of rows, `k` is the number of features. (Or if you are working with SHAP interaction values, then `(N, k, k)`).

The first dimension (of length `N`) is in the same order as your original X (the data you were explaining), so something like

```python
X[shap_vals[:, feat_col_index] == "value_you_want", ...]
```

should give you all the rows in `X` with the same shap values  (just some basic numpy indexing).

**Comment by detrin** [comment]
Ah okay, he probably meant a specific value of shap.
