### ISSUE TITLE
Shap classification woes

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#584]
I’m performing a classification task, predicting 20 classes. First time I used SHAP, outputs were great. However, now when I’m running it, output interpretations do not make intuitive sense. Can you help explain why that might be so? What can I do to recover my original results (things to think about that could cause these issues and how to remedy) thanks!

**Comment by jlevy44** [comment]
I’m running a gradient based explainer. The problem is that two samples Embeddings are similar before the prediction layer, but their shap values are way off, and I can’t seem to figure out why.

**Comment by jlevy44** [comment]
Could selecting a layer help in this case? I did not choose a layer for the gradient based explainer. I think some of the deeper layers are better at discriminating.

**Comment by jlevy44** [comment]
Or perhaps the solution is to add more shap samples?

Right now, I'm calculating the SHAP scores for (20 classes, 300k features, 200 test samples), and doing this by averaging the scores from 10 batches of 30 SHAP samples. Is this the best way to go about it? Or should I increase the number of samples (how do I circumvent memory limitations)?

**Comment by slundberg** [comment]
If you are not getting the results you think you should with GradientExplainer the first step would be to draw 1000k samples and make sure that doesn't make a big difference.

What do you mean by 10 batches of 30 samples? You mean you have 300 samples and have set the batch size to 30?

**Comment by jlevy44** [comment]
What I meant to say is that my dataset size is 200 samples. I wanted to run 300 Shapley samples/iterations, and split them up into batches of 30 and averaged out the Shapley coefficients. It takes close to a day to run 300 Shapley iterations, so I can try to upscale to 1k. 

If I didn’t use batches, and instead tried 1k Shapley samples, how much more memory do you think this would require and what can I do to limit this constraint? Thanks!
