### ISSUE TITLE
cannot import name '_validate_lengths'

### ISSUE THREAD

**Issue by stylianos-kampakis** [shap/shap#585]
Hello,

I am getting the following error:

cannot import name '_validate_lengths'

**Comment by stylianos-kampakis** [comment]
I think it relates to scikit-image

**Comment by nickwan** [comment]
@stylianos-kampakis 
https://github.com/slundberg/shap/issues/206#issuecomment-495263043

**Comment by slundberg** [comment]
Thanks @nickwan! Currently we use skimage just for the color conversion code...so perhaps we can can find a way to do those conversions without getting the whole skimage dependency. That might be the best way to address these things long term.
