### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jimmywan** [shap/shap#589]
Hello, we've started playing around with this package, but we're relying upon some changes on master since 0.28.5 was released. Any chance you can cut a 0.28.6 release?

Apologies for posting a ticket as a question, but this seemed to be your preferred method of contact as per your personal website.

**Comment by slundberg** [comment]
Just pushed 0.29.0 :)

**Comment by jimmywan** [comment]
Awesome, thanks! Any idea when that will make it's way to pypi?

**Comment by slundberg** [comment]
Once a few builds get finished. There was a change to sklearn that stopped
the auto deploy.
