### ISSUE TITLE
default to violin in summary_plot

### ISSUE THREAD

**Issue by kodonnell** [shap/shap#59]
@slundberg - may I suggest defaulting to the violin plot for the distributed `summary_plot`? Generally they look better, and are more easily interpretable (i.e. the height means something, and the visualization isn't dependent on the order you draw the dots - which is always a problem for overlapping objects). That said, there's a chance the smoothing from the violin plot misleads people (though it should be easy to reduce that smoothing).

**Comment by slundberg** [comment]
hmmm...I originally switched from the violin plot because I felt like the smoothing was hiding features in the data, and that choosing the right kernel size was not foolproof. I'll compare the plots again and think about it. Your point about the order of drawing makes sense. As for the height being meaningful I think the same holds in both plots, just one is smoothed.

**Comment by kodonnell** [comment]
Cool, we understand each other. 

One thing I'll add is that the purpose of these graphs is visually summarizing a general trend, and smoothed violins are good for this, especially when communicating to clients. Dot plots add a lot more noise, and if you're trying to use these to identify specific features that are small enough to be hidden in the violin plot, then you should be using something more accurate than graphs anyway.

Also, this doesn't matter for people who know about both options. However, I'd posit that the average user is more interested in violin type plots, and will be less harmed by not knowing about dot plots. The technical user who might want dot plots is also more likely to know about them. Hence it might be safer to default to violin. (Of course, the opposite could easily be argued.)

Anyway - will leave you to close this as you see fit - I'm not personally worried either way. It just came up when I saw a blog by someone using our new graphs, and I just wished they'd used the violin plots as they look much nicer (in my opinion).

**Comment by slundberg** [comment]
I added a new notebook to compare the plot types: https://github.com/slundberg/shap/blob/master/notebooks/Scatter%20Density%20vs.%20Violin%20Plot%20Comparison.ipynb

Which type of violin plot were thinking of? (plain, colored, or layered)

**Comment by kodonnell** [comment]
I updated the notebook as part of #17 - see [here](https://github.com/awaregroup/shap/blob/98630d08d2026a11de1be9cf5c1dbd15e12fb07f/notebooks/Scatter%20Density%20vs.%20Violin%20Plot%20Comparison.ipynb). I'd personally be defaulting to the layered one (sorry, I hadn't realised there were now two), in red/blue - i.e. like this:

![image](https://user-images.githubusercontent.com/8204904/39046343-e9c9b114-44e9-11e8-9602-6a23a0ead67a.png)


The notebook goes through some pros/cons of each, though you may not agree with it all. As a general comment, I'm not sure of the need for the other violin plot.

**Comment by kodonnell** [comment]
@joelostblom continuing discussion from #919 

> I agree that the layered violins look very cool! I haven't encountered them previously so I need to test and think about if they represent data according to my expectations when using them.

They have a lot of information packed in them, which is great - but also means they take a bit of thinking if you haven't seen them before. That said, we actually found they were good for explaining to clients - we can see "look at this big red bit here which means X" - it's visually obvious to the client that something is different (compared to e.g. other violins), and they trust our interpretation of it.

> In the layered violins, the order of the layering means that blue (low values) will always pair up giving rise to a bigger continuous block of blue. Red (high values) layers are often separated, could this mean that the same amount of red and blue is perceived differently? I'm mostly thinking that there might appear to be more blue since they are joined together. A filled density curve/half violin, would not have this potential issue, but there will always be some difference between the layers since high and low values are plotted at different locations.

I'm actually not sure what you're referring to, sorry - do you have an example? Here's one from the above message and it seems to have similar red and blue.

![image](https://user-images.githubusercontent.com/8204904/70361433-7918cf80-1879-11ea-83d0-42cce7670db5.png)

It could totally be an issue though if it's percentile based (or not - whichever one means that each band doesn't correspond to area). In that case, disparities will depend on data distribution. Which is actually another bit of useful information in the graph!

> Wouldn't a traditional sequential colormap (such as viridis, BuPu or single color) be more appropriate for visualizing a sequence of feature values from low to high? Diverging maps are most often used for values with a natural center point (such as the shap values). Or is it intentionally selected to highlight extremes?

Either or works - I personally like a blue -> red diverging for appearance, and for highlighting extremes (which is mostly what I'm trying to communicate with these). E.g. in the above you can still see a little red on the edge of the left part of the (mostly blue) violin. But if you want to do e.g. white -> red (sequential - but really just the top half of the aforementioned diverging) that's fine. 

> Regarding violins not being suitable for a smaller number of observations, there could be a threshold of points which changes the default between dot and violin plot.

Sounds like a PR in the making = ) That said, it's easy for people to try both and see which they prefer.

> In general, I like swarm plots where the dots are stacked without overlapping, but I appreciate that there is no room for that in these plots.

Totally. You can play with transparency and all of that, but ultimately stacking dots means stacked dots. However, there are maybe some other (trickier) things you could do, such as:

- Just use smaller dots so they don't overlap (potentially forcing them not to overlap). This could look neat or not, depending on how it's done. It could also just end up looking like the layered violin = )
- Don't draw all the dots. If I know I'm going to be drawing 100 overlapped dots, then aggregate them together appropriately so I only draw eg. 10 non-overlapped dots. This would make it independent of the ordering the dots are drawn. Each aggregated dot could use different size (which would look really neat) or e.g. coloring left/right, etc. That sounds fun, actually, and maybe I'll have a play (though don't let that hold you up if you want to do it - I may also not find time!).

**Comment by slundberg** [comment]
> Don't draw all the dots. If I know I'm going to be drawing 100 overlapped dots, then aggregate them together appropriately so I only draw eg. 10 non-overlapped dots. This would make it independent of the ordering the dots are drawn. Each aggregated dot could use different size (which would look really neat) or e.g. coloring left/right, etc. That sounds fun, actually, and maybe I'll have a play (though don't let that hold you up if you want to do it - I may also not find time!).

One thing to keep in mind is that the trouble with getting dots to never overlap is that you have to alter their x-positions, so you no longer know exactly where they line up.

A related thing I have wanted to do for a long time is to average the feature value for each pixel with overlapping dots. This would naturally create a colored violin in the limit of infinite points, but also remain readable and exact for areas of low density.

**Comment by slundberg** [comment]
Also...we should add a documentation notebook and link it where the other "Documentation notebooks" are in the readme for the summary_plot function and highlight all these features.
