### ISSUE TITLE
Release source tarball too on pypi

### ISSUE THREAD

**Issue by marco-c** [shap/shap#590]
0.28.5 had the source tarball too.
Since 0.28.6 only the wheel is available.

**Comment by marco-c** [comment]
Thanks, I see it was released.

**Comment by slundberg** [comment]
Yep! Just got it out over the weekend, thanks for pointing it out.

**Comment by marco-c** [comment]
@slundberg it's missing again for 0.29.3.

**Comment by slundberg** [comment]
Thanks! This is a manual process right now that needs to automated from appveyor or Travis. I am going to make this as todo to record that this automation needs to be done (I did just push 0.29.3 source though).

**Comment by connortann** [comment]
Recent releases include the source tarball along with wheels.
