### ISSUE TITLE
Ability to manually pass in ylabel, xlabel, and figsize OR return the plot object rather than plotting

### ISSUE THREAD

**Issue by adam-ah** [shap/shap#594]
For publication, we would like to be able to customise the plots so it would be great if either:
- We could pass in the usual plot customisation parameters (figsize, xlablel, ylabel)
- Alternatively, the plot would be returned so we could add these to it (although I believe figsize has to be passed for plotting, while xlabel and ylabel can be changed after). Eg, just return pl: https://github.com/slundberg/shap/blob/f0188997b1b949d5ef70ff44baa422d8b0f4398e/shap/plots/dependence.py#L259

(Note: We looked into hacking the feature names but it's rather tedious and error-prone).

By the way, thanks for this amazing library!

**Comment by adam-ah** [comment]
Alternatively, the ability to turn off labels so we can add them manually later (in LaTeX).

**Comment by GarrettCGraham** [comment]
Hey @adam-ah! I had the exact same issue and used the following workaround:

`shap.summary_plot(shap_values, show=False)`

`# Get the current figure and axes objects.`
`fig, ax = plt.gcf(), plt.gca()`
 
`# Make the modifications that you want.  I wanted`
`# to resize the x-axis, but you can do anything that you'd like.`
`xlim = 0.01`
`ax.set_xlim(-xlim, xlim)`
`ax.set_title(ax_title, fontdict={"size":font_size})`

I agree, though: it'd be a nice feature if the plotting methods returned figure and axes objects.

**Comment by adam-ah** [comment]
Awesome, @GarrettCGraham, I might be able to customise it enough using this approach, thanks for the tip!!

**Comment by slundberg** [comment]
I think this is probably a common question so I just added a documentation notebook for the `dependence_plot` function: https://slundberg.github.io/shap/notebooks/plots/dependence_plot.html

**Comment by andreasmarxer** [comment]
> I think this is probably a common question so I just added a documentation notebook for the `dependence_plot` function: https://slundberg.github.io/shap/notebooks/plots/dependence_plot.html

Hi @slundberg 
I'm currently facing issues with the summary_plot.
Although setting the matplotlib parameters of the plot as follows:

` 
matplotlib.rcParams['axes.titlesize'] = 22

matplotlib.rcParams['axes.labelsize'] = 10

matplotlib.rcParams['legend.fontsize'] = 18

matplotlib.rcParams['lines.linewidth'] = 3

matplotlib.rcParams['xtick.labelsize'] = 18

matplotlib.rcParams['ytick.labelsize'] = 18
`

The labels on the y-axis don't have the same size as the xticks.
Ideally, I want the names of the features (y labels) the same size as the x ticks and also the color bar.
Do you know where I can set these sizes?

![105_within_test_fold_1_shap_summary](https://user-images.githubusercontent.com/45263298/86611968-b1b78d80-bfaf-11ea-978c-27a59a631dfd.png)

**Comment by wanaguirre** [comment]
To whom it may help, here is the code I have come up with to make the modifications that @andreasmarxer was asking about.

```
shap.summary_plot(shap_values, X_test, cmap=color_map, show=False)

# Get the current figure and axes objects. from @GarrettCGraham code
fig, ax = plt.gcf(), plt.gca()

# Modifying main plot parameters
ax.tick_params(labelsize=14)
ax.set_xlabel("SHAP value (impact on model output)", fontsize=14)
ax.set_title('Feature Importance - Life insurance price', fontsize=16)

# Get colorbar
cb_ax = fig.axes[1] 

# Modifying color bar parameters
cb_ax.tick_params(labelsize=15)
cb_ax.set_ylabel("Feature value", fontsize=20)

plt.show()
```

**Comment by carlacodes** [comment]
> To whom it may help, here is the code I have come up with to make the modifications that @andreasmarxer was asking about.
> 
> ```
> shap.summary_plot(shap_values, X_test, cmap=color_map, show=False)
> 
> # Get the current figure and axes objects. from @GarrettCGraham code
> fig, ax = plt.gcf(), plt.gca()
> 
> # Modifying main plot parameters
> ax.tick_params(labelsize=14)
> ax.set_xlabel("SHAP value (impact on model output)", fontsize=14)
> ax.set_title('Feature Importance - Life insurance price', fontsize=16)
> 
> # Get colorbar
> cb_ax = fig.axes[1] 
> 
> # Modifying color bar parameters
> cb_ax.tick_params(labelsize=15)
> cb_ax.set_ylabel("Feature value", fontsize=20)
> 
> plt.show()
> ```

Thank you for this, I realised today the color bar in SHAP is a non-standard object and was struggling to figure out which axis their color bar was on

**Comment by Gimba** [comment]
I would like to change the tick labels "high", "low" on the color bar to something else. I had a thorough look at the color bar object for that purpose but can't find the string "high" or "low". Could somebody help me out please?
