### ISSUE TITLE
Using DeepExplainer with torchtext

### ISSUE THREAD

**Issue by ghost** [shap/shap#595]
Hello,

I am using a simple pytorch RNN to train a sentiment detection model and am using torchtext to handle the data iteration (specifically data.BucketIterator).

When I try to use the DeepExplainer on the trained model, I get the error: `RuntimeError: only Tensors of floating point dtype can require gradients`.

The default type for tensors in the BucketIterator is torch.LongTensor, so I have experimented with changing this type to FloatTensor, but this stops the model from training.

I have also tried to change the type of tensors for the background and test cases being fed into the DeepExplainer to FloatTensor, but upon instantiating the DeepExplainer I get the error: `RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUType instead (while checking arguments for embedding)`

I'm at a bit of a loss and would appreciate any insight into what is causing the errors, and if there are known compatibility issues with torchtext.

Thanks!

**Comment by gabrieltseng** [comment]
Hi!

The error you get is from the embedding layer. Neither embedding layers or RNNs are supported by the PyTorch Deep Explainer right now.

Unfortunately, because of the error you get, it's difficult to backpropagate through an embedding layer, so the model also won't work with the Gradient Explainer.

Sorry about this! Embedding layers and RNNs are supported in the Tensorflow Deep Explainer, so that may be your best bet for now.

**Comment by ghost** [comment]
Thanks for the response and suggestion! 

To experiment with this, I have taken the code from this page https://slundberg.github.io/shap/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html and adpated it to run on tensorflow to check compatibility with tf as opposed to keras. All I have done to the code is insert `tensorflow.` before all the keras imported modules 

The model trains fine, but again when running `explainer.shap_values` I get an error, this time:
`TypeError: Fetch argument None has invalid type <class 'NoneType'>`

Do you have any idea why this is? Should I abandon the tf keras wrapper and go straight for 'pure' tensorflow?

Thanks

**Comment by jemaw** [comment]
Hi, I'm using pure tf with an architecture that has a stack of 2 bidirectional lstms and I am runing into the same error: `Fetch argument None has invalid type <class 'NoneType'>`
Here is more info regarding this issue: #324

**Comment by srn284** [comment]
@gabrieltseng, thank you for your response! Any ideas how I can begin perhaps solving it on my end - as in, if you were to fix it what steps would you take? I'm happy to take a stab at it on my local build perhaps.

or is there some fundamental issues in the pytorch deepExplainer code which does not allow for rnn/embeddings to work with it and needs solid work in redoing it?
 
Thank you much :)

**Comment by gabrieltseng** [comment]
Hi @srn284,

I think it would be very tricky to implement this for the embedding layer - PyTorch doesn't allow gradients to be calculated for Long Tensors, which is the tensor type which must be input into an embedding layer (see [this issue](https://github.com/pytorch/pytorch/issues/7021)).

It should be possible to implement the DeepExplainer for RNNs though - they would probably require a new function to be implemented, similar to what happened for the [maxpool module](https://github.com/slundberg/shap/blob/master/shap/explainers/deep/deep_pytorch.py#L305) (note that these functions are [backward hooks](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.register_backward_hook)).

Definitely happy to help in any way I can if you do decide to work on this!

**Comment by srn284** [comment]
@gabrieltseng  Thanks much! 

I indeed had the embedding problem of the two problems; I was going to attempt it using embedding matrix instead and matrix multiplication with one hot vectors. Right now i believe, pytorch uses a lookup table for embeddings.  

edit: of course, this means no edits on the actual shap's source code; just edits on my own model code but im quite curious if there's something i can do in shap's source code.  

Please let me know your thoughts and thank you for your time.

**Comment by tslevi-unbounce** [comment]
Has there been any progress on this? We're running into this trying to interpret a transformer based model built in pytorch (we're using it for something akin to sentiment, but with regression) and have hit a wall. We cannot get DeepExplainer or GradientExplainer to work.

**Comment by gabrieltseng** [comment]
> Has there been any progress on this? We're running into this trying to interpret a transformer based model built in pytorch (we're using it for something akin to sentiment, but with regression) and have hit a wall. We cannot get DeepExplainer or GradientExplainer to work.

A solution to backpropagate through embedding layer hasn't been added yet. For now, your best bet is probably to replace the embedding layer with a matrix multiplication using one hot vectors.

**Comment by srn284** [comment]
Hey everyone, we did some stuff for interpretability on transformer based models as well! And, indeed the embedding layers in transformers/rnn was why i followed this issues page this in the first place. I replaced embedding layers with embedding matrices and got some results. Not sure if I liked what I got so I dropped my work.

However, I moved to another method for interpretability using this paper (https://www.microsoft.com/en-us/research/uploads/prod/2019/05/camera_paper_with_supp_3.pdf) - they have source code as well. The authors use perturbation and mutual information based training protocol to get the contribution of every "token". I changed the paper's original modelling since the work is quite flexible and can be expanded/altered and it still worked, so it should definitely work for the regression task as well if you play with the source code.

source code: https://github.com/icml2019paper2428/Towards-A-Deep-and-Unified-Understanding-of-Deep-Neural-Models-in-NLP

**Comment by tslevi-unbounce** [comment]
@gabrieltseng I'm not sure how feasible replacing the layers is for us. We're using a base of a pretrained BERT model, which is then finetuned with a specialized head on top for a regression task. We'd have to somehow figure out how to both replace the layer architecture and mimic the trained weights we have.

**Comment by tesfagabir** [comment]
> > Has there been any progress on this? We're running into this trying to interpret a transformer based model built in pytorch (we're using it for something akin to sentiment, but with regression) and have hit a wall. We cannot get DeepExplainer or GradientExplainer to work.
> 
> A solution to backpropagate through embedding layer hasn't been added yet. For now, your best bet is probably to replace the embedding layer with a matrix multiplication using one hot vectors.

@gabrieltseng do you have any working code snippet to use it with matrix multiplication using one hot vectors? I tried it but I am still getting the same issue.

**Comment by enricoliscio** [comment]
Hi all, is this solved? I am having troubles with the DeepExplainer with PyTorch BERT.
