### ISSUE TITLE
Featuer name is not displayed in force plot

### ISSUE THREAD

**Issue by pranjaya** [shap/shap#597]
I have been trying to get the force plot to show me the names of the features and for some reason the feature names are displayed in the summary plot but not in the force plot

Below is the code I used 

shap.force_plot(explainer.expected_value, shap_values[2,:], valid_x.iloc[2,:],figsize=(30, 3),
               matplotlib = False)

<img width="891" alt="Screen Shot 2019-05-17 at 1 30 37 PM" src="https://user-images.githubusercontent.com/50715329/57945492-04b01c00-78a8-11e9-9499-a43a59e5ce00.png">

**Comment by maya-ami** [comment]
@pranjaya it seems like you've closed the issue. Have you found a solution? Would really appreciate if you let me know what was the problem. I've been stuck with that same thing

**Comment by pranjaya** [comment]
I just restarted the kernel and run all of the code again, everything worked fine this time
