### ISSUE TITLE
Is shap required python 3?

### ISSUE THREAD

**Issue by hluan-deloitte** [shap/shap#604]
Shap installation failed in pypy 2. I tried python 2.7 as well but got "AttributeError: 'module' object has no attribute 'red_blue'". Is there a shap version working for python 2?

Traceback for pypy as follows.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oHR5_T/scipy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oHR5_T/scipy/

Traceback for python 2.7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/shap/__init__.py", line 12, in <module>
    from .plots.dependence import dependence_plot
  File "/usr/lib64/python2.7/site-packages/shap/plots/dependence.py", line 17, in <module>
    color="#1E88E5", axis_color="#333333", cmap=colors.red_blue,
AttributeError: 'module' object has no attribute 'red_blue'

Thanks.

**Comment by GarrettCGraham** [comment]
Hey @hongwei-deloitte, it may be that your version of matplotlib is too outdated for shap.  The [colors.red_blue](https://github.com/slundberg/shap/blob/master/shap/plots/colors.py) object is a [matplotlib.colors.LinearSegmentedColormap](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.colors.LinearSegmentedColormap.html).   Updating your version of matplotlib might fix the problem.

**Comment by hluan-deloitte** [comment]
Hi @GarrettCGraham, thank you very much for your reply. It helps a lot. I can only use matplotlib 2.2 as it is the latest version compatible with python 2. I will try to use later version of matplotlib. Thanks

**Comment by slundberg** [comment]
I should note that official support for python 2 was dropped a couple of
months ago, in line with XGBoost and other prominate projects. Older
versions of SHAP should still of course work on python 2.

**Comment by dstromberg** [comment]
Have you tried installing python-tk (at least, that's the name of the package on my Mint 19.1 system)?

ISTR that the colors.red_blue problem was fixed by that.  It appeared that matplotlib was trying to get some info from TK.

**Comment by hluan-deloitte** [comment]
@dstromberg, thank you. I don't see the red_blue error after I installed tkinter. However, I saw a new error. 
I guess it is also a version conflict.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/shap/__init__.py", line 18, in <module>
    from . import benchmark
  File "/usr/lib64/python2.7/site-packages/shap/benchmark/__init__.py", line 1, in <module>
    from . import measures
  File "/usr/lib64/python2.7/site-packages/shap/benchmark/measures.py", line 123
    impute = mean_vals[impute_inds] + Cio @ Coo_inv @ (X_test[i, observe_inds] - mean_vals[observe_inds])
                                          ^
SyntaxError: invalid syntax

**Comment by dan-stromberg** [comment]
@hongwei-deloitte For that one, I had to specify an older version of shap in my requirements.txt.  The error is because the code is using the new @ operator which is Python 3.5+, and shap doesn't specify which versions of Python it works with (?).
