### ISSUE TITLE
Just a question about the similarity

### ISSUE THREAD

**Issue by alexandregerbeaux** [shap/shap#61]
Hi Slundberg,

Thank you for your awesome package.

Quick question: for your function force_plot with the js plot "order by similarity". May I ask you what method did you use to group the observations?

Best,

Alex

**Comment by bbennett36** [comment]
Here is the source for this - https://github.com/interpretable-ml/iml/blob/master/iml/visualizers.py
  
I think this is the code that you're looking for that is deciding the 'order by similarity'.
```
D = scipy.spatial.distance.pdist(np.vstack([e.effects for e in arr]), 'sqeuclidean')

clustOrder = scipy.cluster.hierarchy.leaves_list(scipy.cluster.hierarchy.complete(D))
```

**Comment by slundberg** [comment]
That's right. It minimizes the sum of squared differences between the SHAP
values.
