### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by dstromberg** [shap/shap#617]
Hi.

What's the story with regard to shap on Python 3.x?

We recently found that shap was using the new "@" (matrix multiplication) operator, which broke some of our Python 2.x code.  We pinned our shap to an older version to deal with it for now.

Shap's Pypi page doesn't appear to say anything about 2.x or 3.x compatibility.

Is shap moving toward Python 3.x compatibility?  Or is it already there?  We want to move our code to 3.x in the near future, and caniusepython3 suggested that we look at shap.

If the 3.x compatibility is a work in progress,  is there a test suite I can invoke to see how things are looking?

Thanks!

**Comment by jim-meyer** [comment]
Just FYI - I installed shap using python 3.6.7 and the tests run by `python -m nose tests` all pass after installing the test requirements. So it looks like shap is compatible with python3 to me.

**Comment by slundberg** [comment]
@dstromberg as of 0.29 shap is now just on python3 (this syncs with other major packages like XGBoost). So if you want to use py27 I would stick with 0.28.

This was discussed in a couple github issues, but I can also note it on PyPI.

**Comment by amirrezamafi** [comment]
@slundberg, Does Shap work with python 3.4?
