### ISSUE TITLE
TQDM for deep explainer?

### ISSUE THREAD

**Issue by akshayuppal3** [shap/shap#623]
Can we have a progress bar for SHAP explainer? Training time for deep explainer (I tried only deep) is quite quick but when it comes to explaining it takes a lot of time ("explaining each prediction requires 2 * background dataset size runs " [Quote from IMDB review using LSTM notebook]). So if there was a way to track the progress SHAP explainer, it would really help.

Thanks.

**Comment by juliusbierk** [comment]
You could just loop over data points, instead of running all datapoints at the same time, no?

Ala:

```
shap_list = []
batch_size = 256
idxs = list(map(int, np.linspace(0, X.shape[0] - 1, int(X.shape[0]/batch_size))))
for i1, i2 in zip(idxs[:-1], idxs[1:]):
    shaps = de.shap_values(torch.from_numpy(X[i1:i2, :]))
    shap_list.append(shaps)
shaps = np.concatenate(shap_list, axis=0)
```

Then you are free to print progress...

**Comment by niloofardadras** [comment]
hello,
could you find any progress bar for it by anychance?

**Comment by iskatrina** [comment]
+1 , hello,
could you find any progress bar for it by anychance?
