### ISSUE TITLE
SHAP plot not generated when called from within a loop

### ISSUE THREAD

**Issue by dzieciou** [shap/shap#628]
I've encountered a strange issue when playing with [shap][1] Python library in Kaggle learning course.

When [`shap.force_plot()`][2] is called within a loop it generates no plot:

    import shap  
    shap.initjs()
    for _ in [1]:
        data_for_prediction = val_X.iloc[0,:]
        explainer = shap.TreeExplainer(my_model)
        shap_values = explainer.shap_values(data_for_prediction)
        shap.force_plot(explainer.expected_value[0], shap_values[0], data_for_prediction)

However, when moving `shap.force_plot()` outside of the loop it works fine

    import shap  
    shap.initjs()
    for _ in [1]:
        data_for_prediction = val_X.iloc[0,:]
        explainer = shap.TreeExplainer(my_model)
        shap_values = explainer.shap_values(data_for_prediction)
   
    shap.force_plot(explainer.expected_value[0], shap_values[0], data_for_prediction)

[![Plot][3]][3]

Why is it so?

  [1]: https://github.com/slundberg/shap
  [2]: https://github.com/slundberg/shap/blob/master/shap/plots/force.py#L27-L60
  [3]: https://i.stack.imgur.com/z4Djc.png

**Comment by dzieciou** [comment]
Kaggle returns only values explictly returned.

```
import shap  
shap.initjs()
plots = []
for _ in [1]:
    data_for_prediction = val_X.iloc[0,:]
    explainer = shap.TreeExplainer(my_model)
    shap_values = explainer.shap_values(data_for_prediction)
    plots.append(shap.force_plot(explainer.expected_value[0], shap_values[0], data_for_prediction))
plots[0]
```

**Comment by slundberg** [comment]
Right. You would need to call `shap.plots.force.visualize` directly if you are inside a loop to get the html and then make sure that html gets outputted correctly.

**Comment by gijsvandinther** [comment]
Or use display() to display the visual:

```
import shap  
shap.initjs()
for _ in [1]:
    data_for_prediction = val_X.iloc[0,:]
    explainer = shap.TreeExplainer(my_model)
    shap_values = explainer.shap_values(data_for_prediction)
    display(shap.force_plot(explainer.expected_value[0], shap_values[0], data_for_prediction))
```
