### ISSUE TITLE
Shap tries to import LGBM?

### ISSUE THREAD

**Issue by sab** [shap/shap#63]
MacOS, LGBM 2.1.0 (latest), SHAP 0.14.1 (latest)

```import shap
shap.initjs()
shap.force_plot(shap_values[0,:], X.iloc[0,:])
```

_OSError                                   Traceback (most recent call last)
<ipython-input-12-79756c247a47> in <module>()
----> 1 import shap
      2 shap.initjs()
      3 shap.force_plot(shap_values[0,:], X.iloc[0,:])

/Users/sbrazhnik/anaconda/lib/python2.7/site-packages/shap/__init__.py in <module>()
      6 from iml.common import Instance, Model
      7 from .explainers.kernel import KernelExplainer, kmeans
----> 8 from .explainers.tree import TreeExplainer
      9 from .plots import visualize, plot, summary_plot, joint_plot, interaction_plot, dependence_plot, force_plot
     10 from iml.visualizers import initjs, SimpleListVisualizer, SimpleListVisualizer, AdditiveForceVisualizer, \

/Users/sbrazhnik/anaconda/lib/python2.7/site-packages/shap/explainers/tree.py in <module>()
     14 
     15 try:
---> 16     import lightgbm
     17 except ImportError:
     18     pass

/Users/sbrazhnik/anaconda/lib/python2.7/site-packages/lightgbm/__init__.py in <module>()
      6 from __future__ import absolute_import
      7 
----> 8 from .basic import Booster, Dataset
      9 from .callback import (early_stopping, print_evaluation, record_evaluation,
     10                        reset_parameter)

/Users/sbrazhnik/anaconda/lib/python2.7/site-packages/lightgbm/basic.py in <module>()
     30 
     31 
---> 32 _LIB = _load_lib()
     33 
     34 

/Users/sbrazhnik/anaconda/lib/python2.7/site-packages/lightgbm/basic.py in _load_lib()
     25     if len(lib_path) == 0:
     26         return None
---> 27     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     28     lib.LGBM_GetLastError.restype = ctypes.c_char_p
     29     return lib

/Users/sbrazhnik/anaconda/lib/python2.7/ctypes/__init__.pyc in LoadLibrary(self, name)
    438 
    439     def LoadLibrary(self, name):
--> 440         return self._dlltype(name)
    441 
    442 cdll = LibraryLoader(CDLL)

/Users/sbrazhnik/anaconda/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    360 
    361         if handle is None:
--> 362             self._handle = _dlopen(self._name, mode)
    363         else:
    364             self._handle = handle

OSError: dlopen(/Users/sbrazhnik/anaconda/lib/python2.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
  Referenced from: /Users/sbrazhnik/anaconda/lib/python2.7/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found_

**Comment by slundberg** [comment]
shap recently started importing lightgbm to support a consistent `TreeExplainer` interface across different model types (LGBM, XGB, sklearn, etc.)

It tried to fail gracefully by catching import errors, but it looks like this is an OSError. Does `import lightgbm` work for you in python? I'll also add a further fallback that catches all errors.

**Comment by slundberg** [comment]
I am going to close this as addressed by the extra error catching recently added
