### ISSUE TITLE
Documentation for  DeepExplainer/GradientExplainer

### ISSUE THREAD

**Issue by baluyotraf** [shap/shap#631]
The doc strings for ```DeepExplainer``` and ```GradientExplainer``` says that the ```__init___``` function accepts a tuple of ```tf.Operation```. When I used the library, ```tf.Operation``` gives an error and using ```tf.Tensor``` works.

It may also be a good idea to move the ```___init___``` docstring to the class name, but that's outside the scope of this issue.

**Comment by slundberg** [comment]
Thanks!
