### ISSUE TITLE
XGB independent tree shap for model loss

### ISSUE THREAD

**Issue by kk-leung** [shap/shap#634]
Hi! Just a question here as I don't know where to ask. I am wondering if there are plans to include the independent tree shap algorithm for model loss in the XGBoost official code (just like the shap values and shap interaction values)? Thanks

**Comment by slundberg** [comment]
There are not plans to port that into the XGBoost code base right now. I think it is better to focus on a single solid C++ implementation than try and maintain lots of implementations in each model library.
