### ISSUE TITLE
Restore predictions with KernelExplainer shap_values + logit link

### ISSUE THREAD

**Issue by AnastasiaTamazlykar** [shap/shap#636]
Hello. First of all, thanks @slundberg and all contributors for this library.
I have a question about KernelExplainer shap_values with non identity link. So 
(0)`sum(shap_values) + base_value = prediction`.
 If we apply link (say logit) then
(1) `sum(shap_values) + base_value = logit(prediction).`
Hence 
(2) `expit(sum(shap_values) + base_value) = prediction.`
With KernelExplainer should i take as base_value `logit(KernelExplainer.expected_value)` to restore predictions? Because it seems that expected_value is original model prediction, not transformed. Please, correct me if i m wrong here. 

Note: tried to follow `force_plot` logic to restore preds

Example:
```
X_train, X_test, Y_train, Y_test = train_test_split(*shap.datasets.iris(), test_size=0.1, random_state=0)
    svm = SVC(kernel='rbf', probability=True)
    svm.fit(X_train, Y_train)

    row = X_test[0]

    pred = svm.predict_proba(row)
    expl = KernelExplainer(svm.predict_proba, X_train, link='logit')
    shap = expl.shap_values(row, nsamples=100)
    shap_pred = expit(expl.expected_value[0] + shap[0].sum())
    assert not np.allclose(pred[0][0], shap_pred)

    shap_pred2 = expit(logit(expl.expected_value[0]) + shap[0].sum())
    assert np.allclose(pred[0][0],shap_pred2)
```
Thanks, Anastasiia

**Comment by slundberg** [comment]
Thanks! The expected value should have been transformed to the margin space. Not sure when this bug got introduced since the example in the readme clearly used to work since the figure is right, but anyway now it is fixed!
