### ISSUE TITLE
Can shap be used in unsupervised model?

### ISSUE THREAD

**Issue by ghost** [shap/shap#637]
Anyone knows it ? Or have other methods for unsupervised model?

**Comment by ghost** [comment]
By the way, there is no labelled data.

**Comment by NNikzad** [comment]
The KernelExplainer function should work with any kind of model, whether it be unsupervised or not.

See the readme for an example: https://github.com/slundberg/shap#model-agnostic-example-with-kernelexplainer-explains-any-function

**Comment by slundberg** [comment]
Same for the GradientExplainer and DeepExplainer. They explain the output of anything, no matter how is was trained.

**Comment by ghost** [comment]
Thanks for reply.  I have understood how to use shap  with any model. And now I close it.
