### ISSUE TITLE
 Paper experiment - Explainable machine-learning predictions for the prevention of hypoxaemia during surgery 

### ISSUE THREAD

**Issue by wabc1994** [shap/shap#639]
Dear,  Lundberg , can I  get the experiment code  from the nature shap paper ?

![Vc0df0.png](https://s2.ax1x.com/2019/06/11/Vc0df0.png)

**Comment by slundberg** [comment]
Because the results from the paper are based on private medical data you won't be able to re-run things, but some reference code is available at: https://gitlab.cs.washington.edu/prescience.

In terms of things you can run for explainability this shap repo has all that. Hope that's helpful!
