### ISSUE TITLE
shap.summary_plot(plot_type="layered_violin") error

### ISSUE THREAD

**Issue by sab** [shap/shap#64]
MacOS, SHAP 0.14.1

```shap.summary_plot(shap_values, X, plot_type="layered_violin", color='#cccccc')```

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-16-b7b00a2c209c> in <module>()
----> 1 shap.summary_plot(shap_values, X, plot_type="layered_violin", color='#cccccc')

/Users/sbrazhnik/anaconda/lib/python2.7/site-packages/shap/plots.pyc in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot)
    494     # draw the color bar
    495     if color_bar and features is not None:
--> 496         cb = pl.colorbar(ticks=[vmin, vmax], aspect=1000)
    497         cb.set_ticklabels(["Low", "High"])
    498         cb.set_label("Feature value", size=12, labelpad=0)

UnboundLocalError: local variable 'vmin' referenced before assignment

**Comment by slundberg** [comment]
Sorry for the slow reply. I needed to merge @kodonnell's PR to fix this. For small datasets I am still getting an error though.

@kodonnell if you run
```
import xgboost
import shap

X,y = shap.datasets.diabetes()
model = xgboost.train({}, xgboost.DMatrix(X, label=y), 100)
shap_values = shap.TreeExplainer(model).shap_values(X.iloc[:100,:])
shap.summary_plot(shap_values, X.iloc[:100,:], plot_type="layered_violin")
```

do you also get an error? If not perhaps something got messed up in the merge.

**Comment by kodonnell** [comment]
Hmmm, I don't see the above code (e.g. ` cb = pl.colorbar(ticks=[vmin, vmax], aspect=1000)`) in current master - @sab can you try with the current master?

@slundberg, I do get an error with your code, though it's because there isn't enough data, I think: increase `:100` to `:1000` and there's no error. I'll look at it now to see if it can do something sensible.
