### ISSUE TITLE
ImportError: cannot import name datasets on Databricks

### ISSUE THREAD

**Issue by brunobrito89** [shap/shap#641]
Hey,

I've installed shap on a Databricks cluster, but every time I try to import it, I get the error:
**ImportError: cannot import name datasets**.
My cluster is running Python 2.

![image](https://user-images.githubusercontent.com/12717468/59383079-9428dd80-8d35-11e9-939c-beb5c6df35e5.png)

Has anyone seen this issue before? 
I've tried installing differente versions, using PyPi and directly from Git, whichever I try I get the same error.

**Comment by slundberg** [comment]
We stopped supporting python2 recently so you might try an older version (like 0.28) and see if that helps?

**Comment by brunobrito89** [comment]
Hi @slundberg, I managed to get it working by installing 0.25.1
I didn't know python2 was no longer supported. 

Thanks!

**Comment by slundberg** [comment]
I added a warning message for others so it is more clear now that shap is moving to python 3 :)
