### ISSUE TITLE
Explaining stateful LSTM model

### ISSUE THREAD

**Issue by YMaks** [shap/shap#644]
Hello. I'm trying to use DeepExplainer and KernelExplainer to explain  stateful LSTM model (keras implementation) with batch_size = 1 and batch_shape = (1, 60).
Tested attempts:

1. DeepExplainer
`melting_train = melting_train[0].reshape(1, 60)`
 `explainer = shap.DeepExplainer(model, melting_train)`
`melting_test = melting_test[0].reshape(1, 60)`
`shap_values = explainer.shap_values(melting_test)`

Got `ValueError: Dimension size must be evenly divisible by 2 but is 1
Number of ways to split should evenly divide the split dimension for 'gradients/dense_2/Sigmoid_grad/split' (op: 'Split') with input shapes: [], [1,1] and with computed input tensors: input[0] = <0>`

2. KernelExplainer
`melting_train = melting_train[0].reshape(1, 60)`
`explainer = shap.KernelExplainer(model.predict_on_batch, melting_train)`
`melting_test = melting_test[0].reshape(1, 60)`
`shap_values = explainer.shap_values(melting_test, nsamples=1)`

Passed, but the result of plotting was empty plots.
`shap.force_plot(explainer.expected_value[0], shap_values[0][0], melting_test[0], feature_names=feature_names)`
`shap.summary_plot(shap_values, melting_test[0], plot_type='bar', feature_names=feature_names)`

I guess the reason is passing only one train example to explainer but according to the model architecture it cannot process more than one batch per run.

So, is there any way to create explainer and pass train data batch by batch or is there any other way to use shap for explaining stateful LSTM models?

Thanks.

**Comment by slundberg** [comment]
What is the dimension of the training dataset that you have? For example what is the shape of melting_test? It looks like something has gone wrong in DeepExplainer with the shapes.

**Comment by XinyuanHu** [comment]
@slundberg I have also encountered shape errors with my LSTM. I think the problem is that look back adds another dimension so it created an incompatible error.  I was able to bypass it by changing the model at the cost of performance. May I email you about this problem in more detail?

**Comment by YMaks** [comment]
> What is the dimension of the training dataset that you have? For example what is the shape of melting_test? It looks like something has gone wrong in DeepExplainer with the shapes.

melting_train shape is (568, 60)
melting_test.shape is (554, 60)

**Comment by YMaks** [comment]
> @slundberg I have also encountered shape errors with my LSTM. I think the problem is that look back adds another dimension so it created an incompatible error. I was able to bypass it by changing the model at the cost of performance. May I email you about this problem in more detail?

Yes, sure.

**Comment by jannine92** [comment]
Not exactly the same problem but probably related: 
For a stateful LSTM, you need to set a fixed batch size for the input layer (`batch_input_size`) which doesn't match the one calculated for the shap values (e.g. if the shape of my first layer is `(4, 2000, 11)` the shape of the joint input during the calculation of the shap values is` joint_input[0].shape: (8, 2000, 11)`). 
@YMaks how did you do that? Or how can I solve this problem, @slundberg? 

Thanks for your help!
