### ISSUE TITLE
Upgrade conda-forge package

### ISSUE THREAD

**Issue by dtom90** [shap/shap#646]
It seems that the latest package version in conda-forge is 0.28.5:
https://anaconda.org/conda-forge/shap

Could this be updated to the latest version, 0.29.1 ?

**Comment by slundberg** [comment]
Yep! Working on this... 0.29 dropped py27 support so I need to update the build process there.

**Comment by jamesmyatt** [comment]
I think this is resolved. (https://github.com/conda-forge/shap-feedstock)

**Comment by dtom90** [comment]
I see version 0.29.2 is now in conda-forge: https://anaconda.org/conda-forge/shap
Though the latest GitHub release seems to be 0.29.3: https://github.com/slundberg/shap/releases

**Comment by slundberg** [comment]
Now it is fixed and running. The build process is fixed, which was the core issue. Unfortunately I have still have to manually merge a PR on every update to keep conda in sync.
