### ISSUE TITLE
ax keyword argument not available for shap.dependence_plot

### ISSUE THREAD

**Issue by Trembles** [shap/shap#648]
I'm trying to use the shap.dependence_plot in a subplot and cannot access the ax keyword without this error,

> TypeError                                 Traceback (most recent call last)
> <ipython-input-2-393a069fd191> in <module>
>      14 # The second argument is the matrix of SHAP values (it is the same shape as the data matrix)
>      15 # The third argument is the data matrix (a pandas dataframe or numpy array)
> ---> 16 shap.dependence_plot(0, shap_values, X,ax=None)
> 
> TypeError: dependence_plot() got an unexpected keyword argument 'ax'

Even with this simple code in jupyter notbook the 'ax' keyword throws an error,

```
import xgboost
import shap

# train XGBoost model
X,y = shap.datasets.adult()
model = xgboost.XGBClassifier().fit(X, y)

# compute SHAP values
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)

shap.dependence_plot(0, shap_values, X,ax=None)
```

from
https://github.com/slundberg/shap/blob/master/shap/plots/dependence.py#L69

```
    ax : matplotlib Axes object
         Optionally specify an existing matplotlib Axes object, into which the plot will be placed.
         In this case we do not create a Figure, otherwise we do.
```

**Comment by slundberg** [comment]
What does `shap.__version__` print?

**Comment by Trembles** [comment]
0.28.5

**Comment by slundberg** [comment]
This is a recent feature. If you are using conda then #646 will fix this issue for you.

**Comment by Trembles** [comment]
It's working now with the latest version ( v0.29.2) in Anaconda.
