### ISSUE TITLE
Using SHAP for demographic data/social science

### ISSUE THREAD

**Issue by chaitjo** [shap/shap#654]
My collaborator and I recently used the SHAP framework to study social disadvantage in India, and published a short paper at the ICLR AI for Social Good workshop:
Paper: https://arxiv.org/abs/1905.03092
Code: https://github.com/chaitjo/working-women

As we're both junior researchers, there are several things we're not completely sure about and would love to get some feedback from the SHAP community: 

1. Is the SHAP framework designed for usage with any data domain (ex: demographic data) and are we using/interpreting it correctly in our analysis?

2. Is there a way to quantify how much we can trust the feature attributions from SHAP? Is it correct to say that the attributions from a less accurate model are doubtful whereas those of a more accurate model are conclusive? 

3. We currently use SHAP to determine how important Caste is for predicting employment of women in the year 2016 (we used mean(|SHAP(Caste)|)). We were advised to do a longitudinal survey for our problem statement: how important is Caste in 2016, 2010, 2006, etc. We are unsure of how we can compare SHAP values across different datasets:
(i) Train separate models (with the same hyperparams) for each dataset and look at the mean(|SHAP(Caste)|) for each model.
(ii) Train one model on all the datasets concatenated together, and compute mean(|SHAP(Caste)|) for samples from each dataset.
(iii) Something else?

**Comment by slundberg** [comment]
My high level thoughts without digging through your paper:

1. Shapley values are not domain dependent, though of course tree models that are great with TreeExplainer are best used for specific types of data (i.e. not images).
2. SHAP values only tell you what the model is doing, not if the model is doing the right thing. So you still need to answer that question other ways. For example one thing you can do to measure statistical variability is bootstrapping your training data and redoing the experiment to make sure you get the same results.
3. i, ii, and iii are all just different modeling assumptions. SHAP values can break out the explanations by year in all of those cases. I would step back and think about what is the best way to model the problem (how you think will give you the most accurate model) then do that, while also trying to understanding what biases your model may have (such as how XGBoost likes to make flat areas).
