### ISSUE TITLE
Errors in code of tutorial "Sentiment Analysis with Logistic Regression"

### ISSUE THREAD

**Issue by UrszulaCzerwinska** [shap/shap#657]
I followed the sample tutorial

https://slundberg.github.io/shap/notebooks/linear_explainer/Sentiment%20Analysis%20with%20Logistic%20Regression.html

When using `shap.force_plot` I encounter an error:
```shap_ind = 0
shap.force_plot(
    explainer.expected_value, shap_values[ind,:], X_test_array[ind,:],
    feature_names=vectorizer.get_feature_names()
)
```
`list indices must be integers or slices, not tuple`

Then if I try

```
ind = 0
shap.force_plot(
    explainer.expected_value, shap_values[0][ind,:], X_test_array[ind,:],
    feature_names=vectorizer.get_feature_names()
)
```
`Object of type matrix is not JSON serializable`

**Comment by slundberg** [comment]
Thanks! That's from some recent changes to LinearExplainer that I am working on making consistent with past behavior.

**Comment by UrszulaCzerwinska** [comment]
Do you know how it can be fixed? Is there a workaround to obtain the force_plot?

**Comment by slundberg** [comment]
It is now fixed on master...

**Comment by UrszulaCzerwinska** [comment]
I updated package downloading it from github and I am running in the same error...
