### ISSUE TITLE
how to get feature names from explainer

### ISSUE THREAD

**Issue by coderificly** [shap/shap#658]
Hi, I'm experimenting with SHAP and xgBoost. 

It's easy to get the Shapley values from explainer, but I can't seem to find any way to link them with the feature names. I see that force_plot can get the feature names. How can I get them?

Thanks,

Barry Feldman

**Comment by coderificly** [comment]
PS Actually, I can rephrase my question. Is the order of the features in the shap_values array the same as it is in the X data matrix?

**Comment by slundberg** [comment]
Yep! The matrix returned from a call to `shap_values(X)` is exactly parallel to `X` (same shape and layout).

**Comment by coderificly** [comment]
Thanks for the confirmation!
