### ISSUE TITLE
KernelExplainer really slow on sklearn RandomForest

### ISSUE THREAD

**Issue by brentonmallen1** [shap/shap#66]
I was trying to use the KernelExplainer on a random forest classifier as follows:

`explainer = shap.KernelExplainer(clf.predict_proba, sample_data)`

However, when I try to extract the shap values using

`shap_values = explainer.shap_values(sample_data)`

it seems to take a prohibitive amount of time.  

` 0%|          | 3/1000 [08:50<48:57:27, 176.78s/it]`

The sample data size is 1000 rows.

The TreeExplainer is much faster but doesn't allow for the `predict_proba` which is what I need to use since my class labels are reversed.  I was wondering if there was something I'm missing that would cause this to be significantly slower.

**Comment by slundberg** [comment]
`TreeExplainer` for a RandomForestClassifier will explain the `predict_proba` output by default, so you should be good to go to just use that (`shap_values.sum(1)` equals the output of `predict_proba`). Note that TreeExplainer will output an array of SHAP value matrices, one for each class. This is the best answer for your situation.

That being said, for the KernelExplainer I should put a warning message in when using large background samples. 1000 rows means the kernel explainer will be 1000 times slower than for 1 sample. For KernelExplainer I suggest using `shap.kmeans` to summarize those rows using a few examples like in: https://github.com/slundberg/shap/blob/master/notebooks/Diabetes%20regression.ipynb

**Comment by brentonmallen1** [comment]
That seems to have helped quite a bit.  Thank you.

**Comment by slundberg** [comment]
great!

**Comment by sultanoid** [comment]
> `TreeExplainer` for a RandomForestClassifier will explain the `predict_proba` output by default, so you should be good to go to just use that (`shap_values.sum(1)` equals the output of `predict_proba`). Note that TreeExplainer will output an array of SHAP value matrices, one for each class. This is the best answer for your situation.
> 
> That being said, for the KernelExplainer I should put a warning message in when using large background samples. 1000 rows means the kernel explainer will be 1000 times slower than for 1 sample. For KernelExplainer I suggest using `shap.kmeans` to summarize those rows using a few examples like in: https://github.com/slundberg/shap/blob/master/notebooks/Diabetes%20regression.ipynb

This link does not exists in the github repository. 
[https://github.com/slundberg/shap/blob/master/notebooks/Diabetes%20regression.ipynb](
https://github.com/slundberg/shap/blob/master/notebooks/Diabetes%20regression.ipynb)

**Comment by bhargav-srinivasan-upstart** [comment]
> > `TreeExplainer` for a RandomForestClassifier will explain the `predict_proba` output by default, so you should be good to go to just use that (`shap_values.sum(1)` equals the output of `predict_proba`). Note that TreeExplainer will output an array of SHAP value matrices, one for each class. This is the best answer for your situation.
> > That being said, for the KernelExplainer I should put a warning message in when using large background samples. 1000 rows means the kernel explainer will be 1000 times slower than for 1 sample. For KernelExplainer I suggest using `shap.kmeans` to summarize those rows using a few examples like in: https://github.com/slundberg/shap/blob/master/notebooks/Diabetes%20regression.ipynb
> 
> This link does not exists in the github repository. https://github.com/slundberg/shap/blob/master/notebooks/Diabetes%20regression.ipynb

This is the new link: https://github.com/shap/shap/blob/master/notebooks/tabular_examples/model_agnostic/Diabetes%20regression.ipynb
