### ISSUE TITLE
Question on Shap for CNN

### ISSUE THREAD

**Issue by kayuksel** [shap/shap#664]
Can you please let me know how exactly SHAP is superior to visualizing class activation maps? Thanks.

**Comment by slundberg** [comment]
The paper on class activation maps talks about using a specific type of global average pooling sitting on top of the last convolution layer. This means that you need to use that type of network structure for CAM to work. However, the more general idea of just assigning credit to the last convolutional layer and up sampling to get an influence map is something you can also do with SHAP, just without any assumptions about your network structure.

In general explaining the pixels is not as easy as explaining higher level convolutional layers, so I would recommend explaining the highest spatial conv layer you can while still getting enough resolution for what you want. (note the readme has an example of explaining such an internal layer)
