### ISSUE TITLE
save_html() - UnicodeEncodeError with Force Plot (Partial Solution Found)

### ISSUE THREAD

**Issue by cdpierse** [shap/shap#665]
Hi,

I've been trying to use the save_html() function to save a force plot returned from DeepExplainer. 
I have no problem saving the plot as such:
 `plot =shap.force_plot(
                    explainer.expected_value[0],
                    shap_values[0][0], features = original_feature_values,
                    feature_names= feature_names)`
It produces an ipython HTML object as expected.

However when I call `shap.save_html('explainer.html', plot)` on it I get the following error `UnicodeEncodeError: 'charmap' codec can't encode character '\u0100' in position 34699: character maps to <undefined>`

I looked into the error and it's usually the result of not explicitly encoding characters as 'utf-8' .
I went through the code in force.py and into the `save_html()` function on line 217 and found by changing the following:
`if type(out_file) == str:
        out_file = open(out_file, "w")
        internal_open = True
    out_file.write("<html><head><script>\n")`
on line 222 to:
`      if type(out_file) == str:
        out_file = open(out_file, "w",encoding='utf-8')
        internal_open = True
    out_file.write("<html><head><script>\n")`
I can get it to work again. 

This is has solved the error for me and the `explainer.html` file is now being generated, however I think this is only a partial solution as the force plot is rendering somewhat incorrectly (see the attached image) 
![Capture_new](https://user-images.githubusercontent.com/8831892/60099460-97699380-974f-11e9-9b65-bf6d412d57b2.PNG)

Any thoughts on what might be going on here ? Thanks.

**Comment by Rypo** [comment]
Fairly sure all you need to do is modify the opening `out_file.write` to meta charset utf-8.
e.g.: `out_file.write("<html><head><meta charset='utf-8'>\n")`
That should make the arrows display correctly.

Here is a rather hackish rewrite I wrote up:
```python
def save_html(out_file, plot_html, full_html=False):
    """ Save html plots to an output file.
    
    Parameters
    ----------
    out_file : str or file
        Location or file to be written to
    plot_html : HTML Object
        HTML object returned by shap.force_plot()
    full_html : boolean (default: False)
        If True, writes a complete HTML document starting 
        with an <html> tag. If False, only script and div
        tags are included.
    """

    internal_open = False
    if type(out_file) == str:
        out_file = open(out_file, "w", encoding="utf-8")
        internal_open = True
    
    if full_html:
        out_file.write("<html><head><meta charset='utf-8'>\n")
    
    out_file.write("<script>\n")

    # dump the js code
    bundle_path = "bundle.js" # os.path.join(os.path.split(__file__)[0], "resources", "bundle.js")
    with io.open(bundle_path, encoding="utf-8") as f:
        bundle_data = f.read()
    out_file.write(bundle_data)
    out_file.write("</script>")
    
    if full_html:
        out_file.write("</head><body>\n")

    out_file.write(plot_html.data)
    
    if full_html:
        out_file.write("</body></html>\n")

    if internal_open:
        out_file.close()
```
Note: this requires you having downloaded and saved the [bundle.js](https://github.com/slundberg/shap/blob/e55366c688b6985341b111de8a581e237578c44f/shap/plots/resources/bundle.js) to your local directory.

**Comment by cdpierse** [comment]
Thanks, that's done the trick for me. I'd used the save_html() feature on a Mac machine before with no problem but when I ported over to Windows I got that error. Any idea why there was two different behaviours previously? 

Thanks again for the fix!

**Comment by slundberg** [comment]
Thanks @Rypo! You mind sharing that as a PR?

**Comment by Rypo** [comment]
@slundberg PR issued! Cleaned it up a bit, but couldn't think of a good way to clean up the if statements without large modifications to the function, so I let it be.
