### ISSUE TITLE
How to get the importance for categorical features in Shap value

### ISSUE THREAD

**Issue by zongnansu1982** [shap/shap#679]
Hi, I have some questions regarding how to get the importance of the original the categorical feature in shap value.

I have some input data with both numeric and categorical features, to train a sklearn random forest mode, I change all the categorical into one-hot encoding. For example, if feature A has values ("a", "b"), the feature A will be changed to featureA_a and featureA_b. So for a sample has 'a' for feature A, it will goes [1,0]. When I have the shap values for all the importance of the features, how should I get the importance of the original feature A ? Sum up the importance of featureA_a and featureA_b?

Thanks for the help

**Comment by slundberg** [comment]
Yep. Summing up a set of features gives the importance of that group. I should also note, for many tree models you don't even need to do one-hot-encoding in the first place.

**Comment by jerry-appliedAIstudio** [comment]
I'm trying to use the kernel explainer to generate shap values. My input sample set contains categorical data and I'm getting an error: "ufunc 'isfinite' not supported for the input types..." Do you have a recommendation for how to fix this?

**Comment by MateusCichelero** [comment]
> I'm trying to use the kernel explainer to generate shap values. My input sample set contains categorical data and I'm getting an error: "ufunc 'isfinite' not supported for the input types..." Do you have a recommendation for how to fix this?

Same error here, I've trained a CatBoost model using categorical features.

**Comment by abhi-gm** [comment]
> I'm trying to use the kernel explainer to generate shap values. My input sample set contains categorical data and I'm getting an error: "ufunc 'isfinite' not supported for the input types..." Do you have a recommendation for how to fix this?

same issue I am Also facing the same issue

**Comment by vosilov** [comment]
> Yep. Summing up a set of features gives the importance of that group. I should also note, for many tree models you don't even need to do one-hot-encoding in the first place.

I'm not sure summing up the importances of individual one hot columns would make conceptual sense. This would be summing up the mean absolute contributions of individual columns. Instead, what would be more sound is to sum the contributions, and the take the absolute mean of that sum. It's a question of micro-averaging vs macro-averaging. Am I completely off or does this make sense?

**Comment by Justinas365** [comment]
> Yep. Summing up a set of features gives the importance of that group. I should also note, for many tree models you don't even need to do one-hot-encoding in the first place.

Could you hint on how to do so please? Should this be done before .shap_values() or after?
I tired to modify the df that .shap_values() return and feed that into .shap_summary(), but it is complaining about the size.
