### ISSUE TITLE
SHAP Values for ranking task?

### ISSUE THREAD

**Issue by tyler-romero** [shap/shap#685]
I am using LightGBM for a ranking task. My dataset has no missing values, but I note that for some features, the Expected SHAP value is negative or positive.

For ranking tasks, the ranking of a set of documents in a query is determined based on sorting the output values of a model. So model output values are on an arbitrary scale and are interpreted relative to other documents.

If a feature has a negative expected SHAP value, does it make sense to center the SHAP values for that feature before calculating Mean |SHAP| value? If so, should I center by Query or at the Corpus level?

My reasoning is that if a feature contributes a similar negative amount to all documents, then it may be assigned a disproportionately high importance when in fact it doesn't do much to separate documents.

Alternatively, should I be measuring the variance in SHAP values for each feature?

**Comment by tyler-romero** [comment]
@imatiach-msft reached out to me offline and answered some of my questions/cleared up my understanding of SHAP Values.

**Comment by francoismai** [comment]
Hi, I am having similar questions. What were the answers?

Thank you.

**Comment by Eli-m93** [comment]
What did @imatiach-msft tell you? Still interested @tyler-romero.
