### ISSUE TITLE
unable to import shap due to reaction with dependencies scikit-image & numpy

### ISSUE THREAD

**Issue by Talisberg** [shap/shap#693]
Hi ,

Can't import shap due to an import error
```
~\Anaconda3\lib\site-packages\skimage\util\__init__.py in <module>()
----> 1 from .dtype import (img_as_float32, img_as_float64, img_as_float,
      2                     img_as_int, img_as_uint, img_as_ubyte,
      3                     img_as_bool, dtype_limits)
      4 from .shape import view_as_blocks, view_as_windows
      5 from .noise import random_noise

ImportError: cannot import name 'img_as_float32'
```

scikit-image version is 0.15.0
numpy version 1.16.3

**Comment by svadams** [comment]
Possibly you could try updating your version of numpy? I have scikit-image 0.15.0 and numpy 1.17.0 (anaconda3 with python 3.6.8) and do not have this problem

**Comment by jonnor** [comment]
This is very likely resolved in newer versions. Proposing to close this issue. CC @slundberg

**Comment by detrin** [comment]
@dsgibbons Candidate for closing.
