### ISSUE TITLE
Dependence plot side bar sometimes out of scale?

### ISSUE THREAD

**Issue by grassoste** [shap/shap#695]
Hi, first of all tank you very much for this package, it's amazing! 

I found a minor issue, of which I am not sure since it has a strange behavior.
In the dependence plot, when plotting SHAP values with either a specific `interaction_index` or auto, sometimes the color bar is out of scale, only positive, starting from zero. The same feature when plotted on the X-axis has the correct scale.
Notably, this does not happen to all the features which have both positive and negative values. Neither seem to be related to the other parameters of the dependence plot. 
Do you have any idea why? 

As a workaround I would modify the image after passing the option `show=False`, but from the notebook does not work (despite `%matplotlib inline`), while from any script I have no problem (so by scripting can be a workaround for me). But do you know what else could be the cause?

I looked among the issues and tried a few things, but no luck. 
I am on shap 29.3 and matplotlib 3.0.3. 

Thank you!

**Comment by invokermain** [comment]
So I had this issue as well and found out what is causing it.

The relevant code from _dependence.py_
```
if interaction_index is not None:
        cv = features[:, interaction_index]
        cd = display_features[:, interaction_index]
        clow = np.nanpercentile(cv.astype(np.float), 5)
        chigh = np.nanpercentile(cv.astype(np.float), 95)
        if type(cd[0]) == str:
            cname_map = {}
            for i in range(len(cv)):
                cname_map[cd[i]] = cv[i]
            cnames = list(cname_map.keys())
            categorical_interaction = True
        elif clow % 1 == 0 and chigh % 1 == 0 and chigh - clow < 10:
            categorical_interaction = True

        if categorical_interaction and clow != chigh:
            clow = np.nanmin(cv.astype(np.float))
            chigh = np.nanmax(cv.astype(np.float))
            bounds = np.linspace(clow, chigh, int(chigh - clow + 2))
            color_norm = matplotlib.colors.BoundaryNorm(bounds, cmap.N-1)
```

So in my situation (not sure about teto's) I have a binary variable with around 3% of cases being True. So `chigh = np.nanpercentile(cv.astype(np.float), 95)` will set chigh to 0.

So, while `categorical_interaction` is correctly set to True by `elif clow % 1 == 0 and chigh % 1 == 0 and chigh - clow < 10`... this condition is not met ` if categorical_interaction and clow != chigh` as chigh == clow.

I believe a sensible fix for this might be to change:
`if categorical_interaction and clow != chigh`
to ->
`if categorical_interaction and min(cv) != max(cv)`?

I think there are some other potential changes to make to that part of the code to better determine if something is categorical, probably by checking the number on unique entries in the cv array, and maybe some warning when a variable is being treated as categorical with some documentation that it will be by default treated as continuous?

I can raise a pull request with whatever changes you want to this part as I think this is a brilliant package.

**Comment by slundberg** [comment]
@invokermain A PR would be great! I think the best change would be to check if clow and chigh are equal and if so set them to the min and max of the data instead of the 5th and 95th percentile. The point of the percentiles is to make sure outliers don't dominate the range of the color scale, but if the values are the same then they clearly are not needed and should just be the min and max values.

**Comment by invokermain** [comment]
I pull requested the minor change you requested.

**Comment by grassoste** [comment]
Has this been pulled? I think I still see the issue...

**Comment by slundberg** [comment]
@teto1991 a fix was merged. If you have a self-contained example (or PR) that would be great!

**Comment by grassoste** [comment]
@slundberg I totally missed your reply. Anyway I can show a very intuitive example. 
I have two features that should span from negative to positive results (one is charge, understandable from everyone, another one is hydrophobicity on the GRAVY scale). 
When I plot them on a `dependence_plot` the scale on the X-axis spans correctly (from a negative to a positive value), while on the "hue"-axis it always starts from 0. 
It is easy to show this by plotting the inverted graph.  
So for instance charge interacting with GRAVY (hydrophobicity) shows the correct charge range, but a "limited" hydrophobicity range. 
`shap.dependence_plot('Charge_SP', train_shap_values, X, alpha=0.5, interaction_index='gravy_SP')`
![image](https://user-images.githubusercontent.com/15910227/74830487-8dfeee00-5313-11ea-9f5d-6a79ebb799b9.png)
We now plot the opposite, and we see that hydrophobicity spans from negative to positive results, while the charged has been cut from 0 onward. 
`shap.dependence_plot('gravy_SP', train_shap_values, X, alpha=0.5, interaction_index='Charge_SP')`
![image](https://user-images.githubusercontent.com/15910227/74830979-96a3f400-5314-11ea-910b-3b3e042d9f3d.png)

For me this is an unexpected behavior. Given I plot all the data and thus the same points, I would expect to find also the negative ones, and thus the hue-axis accordingly. 
Would there be a workaround with matplotlib? I will soon need those for a publication so I need them correct :)

**Comment by slundberg** [comment]
I see what you are saying. My best guess is that the difference is from:
https://github.com/slundberg/shap/blob/59d40fc4b3233f983a2faa2f6a1f36d7cf3b9abb/shap/plots/dependence.py#L175-L176
where we trim the color bar range to the 5th and 95th percentile of the data so that outliers don't cause the color bar to be too broad. You could check this by seeing what percent of the data falls below the lower end of the color bar.

**Comment by grassoste** [comment]
It is in fact terribly correct. I checked the values of the 5th and 95th quantiles and they fit with the values on the color bar (which do not start perfectly on 0, while I thought it was just a graphic "illusion"). 
Would you have any suggestions (other than changing the source code) in order to have: 
```
clow = np.minimum(cv.astype(np.float))
cmax= np.maximum(cv.astype(np.float))
```
I don't think I can pass those values to the `dependence_plot` with the ax option. 
The idea would be to highlight the extremes rather than hide them.

Thank you very much for everything anyway :)
