### ISSUE TITLE
Capsule Neural Networks

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#710]
Is there planned support for Capsule Neural Networks or will they work with the existing framework (say I want to interpret on the capsule level and truncate the preceding layers)? Thanks!

**Comment by lrq3000** [comment]
You might try the KernelExplainer, this should work for any model.

**Comment by jlevy44** [comment]
Would this also work with the PartitionExplainer? How different of a Shapley output would I expect, kernel vs gradient or deep? And the features could be clustered in any way or does it have to purely be focused on feature correlation?
