### ISSUE TITLE
No module tqdm.auto found here

### ISSUE THREAD

**Issue by Anu-kriti** [shap/shap#714]
I believe this is the query being used with in shap package and it gave me this error 

<from tqdm.auto import tqdm >

I installed tqdm package but that didn't help

**Comment by slundberg** [comment]
What tqdm version do you have? I wonder if we need to specify a specific version dependency

**Comment by Anu-kriti** [comment]
Is this the way seems right to you 
From tqdm.auto import tqdm 
Or it should be other way round

**Comment by slundberg** [comment]
That form matches the tqdm docs

**Comment by johnmccain** [comment]
I am experiencing the same issue, using shap 0.29.3 and tqdm 4.26.0

Edit: downgrading to 0.29.1 fixed this for me.

**Comment by slundberg** [comment]
@johnmccain that's because the use of auto was added in 0.29.2. https://github.com/tqdm/tqdm has that option documented. But if it is breaking for people perhaps we should not be using it. Just to be clear `from tqdm.auto import tqdm` fails in a blank notebook for your install? How about `from tqdm.autonotebook import tqdm`?

**Comment by peiyaoli** [comment]
Same issue here...

**Comment by pyaf** [comment]
I had the same issue, upgrading `tqdm` fixed it.
`pip install tqdm --upgrade`

**Comment by dorcatty** [comment]
I still have the same issue with shap 0.35 and tqdm4.43.0
when i run the test script, got an error:

 from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm.auto'

pretty sure that shap 0.35 has been successfully install along with tqdm 4.43.0
under: /Library/Python/3.7/lib/python/site-packages/

please help

**Comment by feynmanma7** [comment]
> I had the same issue, upgrading `tqdm` fixed it.
> `pip install tqdm --upgrade`

Fit for me, thank you!

**Comment by jonnor** [comment]
Can someone find which exact version of tqdm is needed to have this fixed?

But even if not, a fix is available. So I believe this issue can be closed. CC @slundberg
