### ISSUE TITLE
Unable to apply SHAP on model results from XGboost 0.82

### ISSUE THREAD

**Issue by ahoosh** [shap/shap#716]
I am having difficulty when applying SHAP on XGB 0.82 model result. In particular, when using `explainer.shap_values`, I get the following error. This is very similar to issues reported [here](https://github.com/slundberg/shap/issues/28) and [here](https://github.com/slundberg/shap/issues/72) when older XGB bindings are used. However, I am using XGboost4J 0.82 and it looks like this shouldn't happen.

```
TypeErrorTraceback (most recent call last)
<ipython-input-146-fa0843a411c1> in <module>()
      1 explainer = shap.TreeExplainer(bst)
----> 2 shap_values = explainer.shap_values(df[feature_names_all].apply(pd.to_numeric).as_matrix())

/var/cache/udocker/phoenix-worker/gamma/python2/shap/explainers/tree.pyc in shap_values(self, X, y, tree_limit, approximate)
    177                 phi = self.model.original_model.predict(
    178                     X, ntree_limit=tree_limit, pred_contribs=True,
--> 179                     approx_contribs=approximate, validate_features=False
    180                 )
    181 

TypeError: predict() got an unexpected keyword argument 'pred_contribs'
```

**Comment by slundberg** [comment]
Hmm I have not used the Java version of XGB. It looks like you have a python object you are using. Can explain how you created or loaded it? And can you print the python XGB version?

**Comment by ahoosh** [comment]
So, it looks like the problem was NOT using `XGBoost4J 0.82`, not it was `SHAP`. The problem was that I was using `XGboost 0.6` in Python when loading the model (which needs to be saved in Native Booster format). Updating to `XGboost 0.9` fixed the issue.
