### ISSUE TITLE
KernelExplainer does not work with GaussianProcessRegressor from ScikitLearn

### ISSUE THREAD

**Issue by grechasneak** [shap/shap#717]
Hey all, 

Love your package, but it does not work with the GaussianProcessRegressor from ScikitLearn.
The error I get is: 
![image](https://user-images.githubusercontent.com/25159822/61900781-9016e080-aedb-11e9-809e-193ef99d4b1d.png)

**Comment by slundberg** [comment]
This is because KernelExplainer expects a python function (like gp.predict), not the model object.
