### ISSUE TITLE
Came across  error in shap_values

### ISSUE THREAD

**Issue by BLue1881euLB** [shap/shap#72]
"shap_values = shap.TreeExplainer(model).shap_values(X)"
Traceback (most recent call last):
  File "C:\Users\QF\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\shap\explainers\tree.py", line 78, in shap_values
    phi = self.trees.predict(X, pred_contribs=True)

TypeError: predict() got an unexpected keyword argument 'pred_contribs'

**Comment by slundberg** [comment]
What version of XGBoost do you have? (`xgboost.__version__`) It should be 0.7 to have SHAP value support. If that's not it could you post how the model object was built?
