### ISSUE TITLE
Shap throws back a tensor shape error for concatenate keras model

### ISSUE THREAD

**Issue by chattertonc09** [shap/shap#724]
Help, I keep receiving and error about my input tensor shape and output tensor shape when trying to use the DeepExplainer.

I built my network around the pseudo code from this article:
https://towardsdatascience.com/decoded-entity-embeddings-of-categorical-variables-in-neural-networks-1d2468311635

My X is a list of numpy arrays (1 array for each categorical type) and the layers are concat using the Keras functional API where the final output layer is sigmoid (classification problem) 

Submitting from my phone but will add a snapshot of error once I get on my laptop.

**Comment by dronshaw** [comment]
Hey, did you ever figure out your issue? I think we might have the same [issue](https://github.com/slundberg/shap/issues/964). I.e., SHAP doesn't support data input whereby it is a collection of arrays. I'm thinking about simply using LIME and then having a custom wrapper prediction

**Comment by chattertonc09** [comment]
> Hey, did you ever figure out your issue? I think we might have the same [issue](https://github.com/slundberg/shap/issues/964). I.e., SHAP doesn't support data input whereby it is a collection of arrays. I'm thinking about simply using LIME and then having a custom wrapper prediction

Yeah we def have the same issue.

**Comment by slundberg** [comment]
DeepExplainer should support multiple input models now. If you have a case where it fails let us know!
