### ISSUE TITLE
Different result from shap_summary_plot for each running of XGBoost

### ISSUE THREAD

**Issue by batunacun** [shap/shap#727]
Hi 
I used SHAP value to explain my XGBoost model, shap.summary_plot is helpful, but I found I am always get different predictor order when I running the model, even the predictor order is slight different, but it is effect my publication, because I would to sort the drivers of land use change.
Is there somebody can give gudiance?
Many many thanks in advance
Batu

**Comment by slundberg** [comment]
That likely means the order is not stable, meaning there is uncertainty about the ordering of the predictors. Usually I would recommend retraining a model on many bootstrap resamples of the training dataset and then observe the variability of the SHAP values (and associated plots) to get a feel for the random variability of the model training process. If the order changes during these retrains then you cannot make a statistically valid claim about that they have a specific order.

**Comment by batunacun** [comment]
Thank you so much for your response Dr.Slundberg @slundberg, I have benefit.
