### ISSUE TITLE
Keras example on KernelExplainer not working

### ISSUE THREAD

**Issue by doramir** [shap/shap#730]
I'm trying to run the example notebook `Census income classification with Keras` from this repo and I'm using shap version 0.29.3 and Keras 2.2.4
 im getting an error
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-a6b5b5903508> in <module>()
      1 explainer = shap.KernelExplainer(f, X.iloc[:50,:])
      2 shap_values = explainer.shap_values(X.iloc[299,:], nsamples=500)
----> 3 shap.force_plot(explainer.expected_value, shap_values, X_display.iloc[299,:])

/usr/local/lib/python3.7/site-packages/shap/plots/force.py in force_plot(base_value, shap_values, features, feature_names, out_names, link, plot_cmap, matplotlib, show, figsize, ordering_keys, ordering_keys_time_format, text_rotation)
     61 
     62     # auto unwrap the base_value
---> 63     if type(base_value) == np.ndarray and len(base_value) == 1:
     64         base_value = base_value[0]
     65 

TypeError: len() of unsized object

````

anyone know why? and how to solve it? 
Thanks!

**Comment by slundberg** [comment]
Does wrapping it like `float(explainer.expected_value)` help? I think it is because there is some zero-shaped ndarray that comes out of the model. If you have a simple working example of how to get this we could add a check to prevent this in the future.

**Comment by doramir** [comment]
working now thanks!

**Comment by naefl** [comment]
Btw, minimum working example:

**Does work:**

#%%
import sklearn
import shap
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

shap.initjs()
X, y = load_boston(return_X_y=True)

X = pd.DataFrame(X)
y = pd.DataFrame(y)
X_train,X_test,Y_train,Y_test = train_test_split(X,y, test_size=0.2, random_state=0)#%%

mod = sklearn.ensemble.GradientBoostingRegressor()
mod .fit(X_train, Y_train)
ex = shap.KernelExplainer(mod.predict, X_train)
shap_values = ex.shap_values(X_test.iloc[0,:])
shap.force_plot(float(ex.expected_value), shap_values, X_test.iloc[0,:])

#%%

**Doesn't work:**

#%%
import sklearn
import shap
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_boston

shap.initjs()
X, y = load_boston(return_X_y=True)

X = pd.DataFrame(X)
y = pd.DataFrame(y)
X_train,X_test,Y_train,Y_test = train_test_split(X,y, test_size=0.2, random_state=0)#%%

mod = sklearn.ensemble.GradientBoostingRegressor()
mod .fit(X_train, Y_train)
ex = shap.KernelExplainer(mod.predict, X_train)
shap_values = ex.shap_values(X_test.iloc[0,:])
shap.force_plot(ex.expected_value, shap_values, X_test.iloc[0,:])
