### ISSUE TITLE
May I ask what is problem in my code?

### ISSUE THREAD

**Issue by SeungJinWang** [shap/shap#734]
explainer = shap.DeepExplainer(combined_model, [X_train_emb, X_traina], session=None, learning_phase_flags=None)

AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v1'

**Comment by SeungJinWang** [comment]
I also have similar error at a different code as below


explainer = shap.DeepExplainer(final_model, [X_categorical, X_continuous, X_padded_docs], session=None, learning_phase_flags=None)
shap_values = explainer.shap_values([X_categorical_test, X_continuous_test, padded_docs_test], ranked_outputs=None, output_rank_order='max')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3077             try:
-> 3078                 return self._engine.get_loc(key)
   3079             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-25-2095d2fa0986> in <module>
----> 1 shap_values = explainer.shap_values([X_categorical_test, X_continuous_test, padded_docs_test], ranked_outputs=None, output_rank_order='max')

C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\__init__.py in shap_values(self, X, ranked_outputs, output_rank_order)
    117         were chosen as "top".
    118         """
--> 119         return self.explainer.shap_values(X, ranked_outputs, output_rank_order)

C:\ProgramData\Anaconda3\lib\site-packages\shap\explainers\deep\deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order)
    266                 # assign the attributions to the right part of the output arrays
    267                 for l in range(len(X)):
--> 268                     phis[l][j] = (sample_phis[l][bg_data[l].shape[0]:] * (X[l][j] - bg_data[l])).mean(0)
    269 
    270             output_phis.append(phis[0] if not self.multi_input else phis)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2686             return self._getitem_multilevel(key)
   2687         else:
-> 2688             return self._getitem_column(key)
   2689 
   2690     def _getitem_column(self, key):

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   2693         # get column
   2694         if self.columns.is_unique:
-> 2695             return self._get_item_cache(key)
   2696 
   2697         # duplicate columns & possible reduce dimensionality

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   2487         res = cache.get(item)
   2488         if res is None:
-> 2489             values = self._data.get(item)
   2490             res = self._box_item_values(item, values)
   2491             cache[item] = res

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals.py in get(self, item, fastpath)
   4113 
   4114             if not isna(item):
-> 4115                 loc = self.items.get_loc(item)
   4116             else:
   4117                 indexer = np.arange(len(self.items))[isna(self.items)]

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3078                 return self._engine.get_loc(key)
   3079             except KeyError:
-> 3080                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   3081 
   3082         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

**Comment by slundberg** [comment]
What version of tensor flow are you using?

**Comment by SeungJinWang** [comment]
Dear Scott,
Thank you for your interesting.
I'm using 1.12 version of tensorflow.

**Comment by slundberg** [comment]
Try TF 1.13 since that should fix it according to: https://github.com/tensorflow/tensorflow/issues/24524

As for the second error I would check into the pandas code you have since it seems like a pandas error not a SHAP error.

**Comment by SeungJinWang** [comment]
Dear Scott,

Thank you so much for your kind answer and time.
I really appreciate it.

**Comment by FrederickDeny** [comment]
Hello, I seem to have the same second error, and I realized it happens when using columns labels instead of indices. Am I supposed to specify that I have column labels? I use the 1.14 version of tensorflow, as well as shap 0.35.
