### ISSUE TITLE
Dependence plots are always shown in Jupyterlab Notebook

### ISSUE THREAD

**Issue by AllanLRH** [shap/shap#738]
Calling 
```python
fig, ax = plt.subplots()
shap.dependence_plot(some_index, shap_values, X, ax=ax, show=False)
```
always displays the resulting plot in my Jupyterlab Notebook. Is there a way around this, as I want to parallelize creating a bunch of plots using `multiprocessing.Pool` ?

EDIT: I have _not_ used the matplotlib-magic (`%matplotlib inline` ).

**Comment by slundberg** [comment]
This is something specific to matplotlib itself inside Jupyter. See: https://stackoverflow.com/questions/30878666/matplotlib-python-inline-on-off

Following the advice in that discussion you can just close the current figure to stop the display of the figure.

```python
shap.dependence_plot("rank(1)", shap_values, X, show=False)
pl.close(pl.gcf())
```
