### ISSUE TITLE
Partition Explainer for Deep Learning Models

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#740]
Hey there!

Awesome to see the partition explainer online! 

What would you recommend for integrating this explainer with pytorch?

**Comment by detrin** [comment]
@jlevy44  I believe there is no problem with using pytorch and shap. Please correct me if I am wrong.

@thatlittleboy I suggest closing for now as this issue seems outdated.

**Comment by thatlittleboy** [comment]
Closing due to staleness
