### ISSUE TITLE
Reshape error when calculating shap values

### ISSUE THREAD

**Issue by Lesley96** [shap/shap#743]
Hi Scott,

I got a reshape error when trying to test SHAP on my data. Have you seen something similar?

ValueError: cannot reshape array of size 41990490 into shape (5,7900484)

**Comment by Lesley96** [comment]
![shape_error](https://user-images.githubusercontent.com/40415251/62931560-2bbbb280-bdf1-11e9-8d39-0b62da705625.jpg)

**Comment by slundberg** [comment]
Hmm...that issue is showing up inside the XGBoost codebase. What version of XGBoost are you using? (I ask because something like this was fixed a while back)

**Comment by Lesley96** [comment]
> Hmm...that issue is showing up inside the XGBoost codebase. What version of XGBoost are you using? (I ask because something like this was fixed a while back)

I am using version 0.90 of xgboost (py3.7). I am confused because calculating shap values was successful on some models and datasets but failed on some other data. (All these models are logically correct).  Do I need to modify somewhere inside the XGBoost codebase?

Let me know if you need to more information to investigate.

**Comment by Lesley96** [comment]
@slundberg Sorry for interrupting you. But I have tried switching different versions of XGBoost, they all failed when calculating shap values.

**Comment by slundberg** [comment]
Sorry for the slow replies, I was away from cell service for a bit. If it is happening with newer versions then I don't know what the problem could be. You could try and force the SHAP package to use the SHAP C++ module and not the built in code for XGBoost...but I would really like to know the reason since we don't want some bug in the XGB version. Do you happen to have anything sharable that reproduces this?

**Comment by pyotam** [comment]
I am experiencing a similar issue with LightGBM:
`shap_values = shap.TreeExplainer(clf).shap_values(dataset.iloc[:10000,:])`
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/kaggle_env/lib/python3.7/site-packages/shap/explainers/tree.py in shap_values(self, X, y, tree_limit, approximate)
    196                     phi = np.concatenate((-phi, phi), axis=-1)
    197                 if phi.shape[1] != X.shape[1] + 1:
--> 198                     phi = phi.reshape(X.shape[0], phi.shape[1]//(X.shape[1]+1), X.shape[1]+1)
    199 
    200             elif self.model.model_type == "catboost": # thanks to the CatBoost team for implementing this...

ValueError: cannot reshape array of size 23020000 into shape (10000,1,1155)
```

where dataset.shape is: (472432, 1154)

**Comment by davidbetancur8** [comment]
Any updates on this??

**Comment by slundberg** [comment]
@davidbetancur8 check out the discussion at the end of #580, it looks like this error often happens when you pass the wrong sized matrix to SHAP.

**Comment by zzack8** [comment]
> @davidbetancur8 check out the discussion at the end of #580, it looks like this error often happens when you pass the wrong sized matrix to SHAP.

I have the same issue and I found many people got the same.
You meant that when  I put shap_values = explainer_shap.shap_values(X_test3)
X_test3 doesn't have the same size as the dataset used to train ?
