### ISSUE TITLE
TypeError in Pytorch DeepExplainer 

### ISSUE THREAD

**Issue by Hadar-Sha** [shap/shap#746]
Thanks for supplying this library!

I am facing a TypeError when running the "PyTorch Deep Explainer MNIST example" on a CPU via cmd (copy pasted the code from the notebook to a python file).
I'm using:
Python 3.5.5
torch version 1.1.0
shap version 0.26.0
win10

-----------------------------------------
the error is:

Traceback (most recent call last):
  File "Path\to\code\shap_example_original.py", line 103, in <module>
    shap_values = e.shap_values(test_images)
  File "Path\to\lib\Anaconda\Lib\site-packages\shap\explainers\deep\__init__.py", line 117, in shap_values
    return self.explainer.shap_values(X, ranked_outputs, output_rank_order)
  File "Path\to\lib\Anaconda\Lib\site-packages\shap\explainers\deep\deep_pytorch.py", line 234, in shap_values
    phis[l][j] = (sample_phis[l][self.data[l].shape[0]:] * (X[l][j: j + 1] - self.data[l])).mean(0)
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray

-----------------------------------------

**Comment by gabrieltseng** [comment]
Hi!

This has been fixed, and the notebook runs. It definitely works if you use the master branch, but I am fairly sure the latest release (0.29.3) will also work.

**Comment by Hadar-Sha** [comment]
Thanks. Also work for me after updating shap.
