### ISSUE TITLE
Intuitiveness of SHAP explanation based on example - some doubts and question about possible solution

### ISSUE THREAD

**Issue by MichalPorwisz** [shap/shap#747]
I have some doubts about intuitiveness of SHAP explanation in some of cases. Let me explain my point on an example.

Let's take a classifier trained on a Titanic dataset (predicting chance of survival). For simplicity, let's only take into account 2 features: age and sex. Let our sample have age=2 and sex=0, meaning a two-year old boy.

The fact is that children and women had higher chances of survival that adult men. Let's assume that there was no statistically relevant difference between boys and girls. A good classifier will be able to follow this pattern. Thus, the probability of survival for this sample will be higher than for an average sample. Main effect of "sex" will be negative, as there were more adult men than boys in the dataset, so that is what will be produced by integrating over background dataset. Interaction of age and sex will be positive, but only to counter the value of negative main effect, as the interaction itself is neutral (boys have similar survival rate as girls). The interaction will be split between sex and age, so actually the SHAP value for sex will still be negative.

Even though SHAP values for those features will be "fair", it seems to me that the explanation based on them won't be intuitive, because it will say that sex has negative impact on the prediction value. One could also provide the values of main effects and interaction value, but then again this may not be obvious that sex+age interaction only counters main effect of sex and that overall it's only important for this sample, that the passenger is a child.

An alternative explanation could be:
"Low age (being a child) contributes to higher chance of survival. Given low age, value of sex (being a boy) doesn't change he probability of survival."
This explanation doesn't change the main effects and interaction value coming from SHAP, it just "rearranges" those values - it presents main effect of age and then presents total result of main effect of sex and sex+age interaction. In other words, we choose to combine interaction value with opposite/contradictory main effect.

Combining age main effect and sex+age interaction is less intuitive, as this would say: "Value of sex (being a men) contributes to lower chance of survival. Given that value of sex, low age (being a child) makes the chance of survival increase (by more than was decreased by value of sex)". This explanation doesn't actually highlight the fact, that part of effect of age (interaction with sex) is only something that reduces negative main effect of sex.

Similar logic would hold, if feature _i_ has positive main effect, feature _j_ has negative main effect _x_ and their interaction would be positive _y_. In similar spirit, I would propose to provide the explanation that feature _i_ contributed _x_ to the prediction, and then "feature _j_ given _i_" contributed _y + x_. Either _y + x > 0_ meaning interaction nullifies the main effect (kind of like titanic example) or _y + x < 0_ - meaning feature _j_ still has negative impact, but it is reduced by the interaction.

In case interaction value is opposite to both main effects, one could sum their SHAP values and say that together these features contribute this sum. Clearly these features together lead to a completely opposite conclusion than separately, so it seems to me, that it's more intuitive to present them together.

The argument for this kind of explanations could be based on the way we explain decisions in natural language. For example one could say - "High income contributes positively to chance of loan approval" - I would say that speaker refers to the main effect of high income here. If one wanted to mean high income as well as it's interactions with all other factors (SHAP value), it would be stated explicitly.
Another example - "The fact that subject has 180 Systolic BP contributes only slightly to higher to the death risk, given that subject is 70 years old" - here I would say that speaker refers to the sum of Systolic BP main effect and Systolic BP+Age interaction value (in both directions - so i+j and j+i).

So it seems that indeed it's more intuitive to provide either main effects or main effect+ total interaction value (both _[i,j]_ and _[j,i]_), instead of providing all main effects and interactions separately or splitting the interaction between both features and providing SHAP values.

This is not very formal and I have presented it on a very simplified example. In reality, features may have multiple relevant interactions (we would maybe need to split the main effect between opposite interactions). Still, I would very much like to get your opinion, if there is any merit in my logic that would be worth pursuing. Let me know if there are any flaws in my logic or if, for some reason, you would think that there is not much value of that proposal in real life applications. Thanks for your time.

**Comment by slundberg** [comment]
Thanks for sharing your thoughts! If I understand correctly, the first example you give is essentially captured by an OR function: you live if you are young or female. You are right that given a young boy the SHAP values would be positive for the `is_young=True` feature and negative (but smaller) for the `is_female=False` feature. This reflects that overall being a boy is concerning, even though when conditioned on being young it doesn't matter.

It is important to note that this is when we use a background distribution of both young and old, male and female. If we instead used a background distribution of all old and male then all the credit would go to being young for a young boy. See the notebook I just added: https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Explaining%20a%20simple%20OR%20function.ipynb

As you suggest, you could certainly explain an OR function by stating the impact of the features as you observe them one at a time (conditioning on features that came before). SHAP values average over all such possible orderings, but you could just fix one of them. If you consider the ordering of first `is_young` then `is_female` you will see no effect for female when `is_young=True`.

It is important to note though that while this is a simple way to state an OR function, it is not necessarily the best way to state more complicated higher order interactions.

My gut reaction is that considering what background distribution you might want to use would be a better route than coming up with custom explanations for different function types, but I am sure there is more to dig into here :)
