### ISSUE TITLE
Trouble understanding SHAP values for missing features

### ISSUE THREAD

**Issue by grechasneak** [shap/shap#751]
Hello, I do not if this is the place to ask but here goes.
I am training my model on my entire dataset.

Then I am looking at the SHAP profiles for the cases that lack feature X. 

However, there is a SHAP value associated with feature X on the cases when X = 0.

Is this because of the SHAP model has to account for the absence of the feature?
Let's say feature X shifted the model up by 10% when it was present, and when it is gone the SHAP value must be shifted down 10% to account for the absence. 
Is this line of reasoning correct?

I have read through the paper a few times trying to figure this out, and I assume this is related to the missingness attribute. 

Thank you for the help!

**Comment by detrin** [comment]
@grechasneak If X is correlated to any feature by tiny bit, it will have nonzero shap importance value.

@thatlittleboy CFC
