### ISSUE TITLE
Can't use shap.decision_plot in the latest release of shap

### ISSUE THREAD

**Issue by Igorcortez** [shap/shap#752]
I am using the latest version ( shap 0.29.3) and i am having the following error when i try to run: 
shap.decision_plot(expected_value, shap_values, features_display, matplotlib=True)

error: module 'shap' has no attribute 'decision_plot'

**Comment by slundberg** [comment]
I need to make a new release (only master has that right now). It will be over a week though before I can do that.

**Comment by hiyamgh** [comment]
Hello, is this issue solved, I am still facing the same thing:

```
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

# use Kernel SHAP to explain test set predictions
explainer = shap.TreeExplainer(model, X_train, feature_dependence="independent")
shap_values = explainer.shap_values(X_test)
# X_test_array = X_test.toarray() # we need to pass a dense version for the plotting functions

ind = 25
shap.force_plot(
    explainer.expected_value, shap_values[ind,:], X_test[ind,:],
    feature_names=feat_names
)
shap.decision_plot(shap_values, X_test, features_display)
```
and the error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-23-ef99bd2de801> in <module>
----> 1 shap.decision_plot(shap_values, X_test, features_display)

AttributeError: module 'shap' has no attribute 'decision_plot'
```

**Comment by Sutanuka** [comment]
Facing the same issue in the latest shap 
AttributeError: module 'shap' has no attribute 'decision_plot'
Please let know when the new release will be made.

**Comment by jonnor** [comment]
This issue has been fixed. Works at least on shap 0.41.0

Minimal code to check
```
import shap
print(shap.__version__)
func = shap.decision_plot
print(func)
```

I believe this issue can be closed. CC @slundberg
