### ISSUE TITLE
Question about the calculation of the permutation weights

### ISSUE THREAD

**Issue by ZiqianXie** [shap/shap#760]
I am still trying to understand your algorithm but does your permutation weight calculation take into account the features not presented in a path?
If M is the total number of features and only L features are presented in a specific path from the root to a leaf. For any set of |S| features in this path, I think that the permutation weight is not just |S|!(M-1-|S|)!/M! but the sum of (|S|+k)!(M-1-|S|-k)/M! for k from 0 to M-L.

**Comment by slundberg** [comment]
It turns out that features that are not on the path have no impact on the output of the leaf, so we don't need to account for them or update them during the Tree SHAP algorithm. This important point saves a fair amount of time. Does that answer your question?
