### ISSUE TITLE
force_plot visualizing all predictions doesn't show the feature with highest shap values

### ISSUE THREAD

**Issue by ammubharatram** [shap/shap#762]
Hi, I used this amazing force_plot to display all instances by sample ordering. As seen below, for instance with index 3 in my dataset the key features displayed are : MF_MATCH_RESIDENCE, MF_MATCH_CITY,MF_FUZZY_FULLNAME_MATCH,MF_MATCH_NATIONALITY AND MF_EXACT_FN_MATCH. These can be seen in this screenshot below:
![image](https://user-images.githubusercontent.com/27764519/63340775-17733a80-c348-11e9-9a80-03141ec724ab.png)

Now, one would expect that these are probably the features with highest shap values in magnitude when I explain the index 3 right? But that's not the case. See screenshot below:
![image](https://user-images.githubusercontent.com/27764519/63340999-86509380-c348-11e9-9d18-554081f48f68.png)

As you can see, the top 3 contributing features namely MF_MATCH_DOB, MF_MATCH_YOB and GNM_DoBScore were not even displayed in the force plot above! What is more surprising is that when I tried to toggle through all the instances in the above force_plot, these top 3 features were not part of most of the displaying features. However, they are the highest contributing in almost all my instances, as they are the variables of highest importance by my Random Forest. I am wondering if there is some issue with the way this wonderful dynamic force_plot is built? Please help.

If needed for you to address this issue, I will then send subset of my data, my random forest model object and my code as they are confidential information.  Thanks in advance!

**Comment by slundberg** [comment]
Sorry for the slow reply! It looks to me like there is some mismatch between the column names. So either the names in the force_plot are not right or the ones you are checking in your dataframe are not right (which means one of them has the features mislabelled). Perhaps it has something to do with filtering the column names to only those of type int64?
