### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape' and TypeError: Object of type 'ndarray' is not JSON serializable

### ISSUE THREAD

**Issue by SeungJinWang** [shap/shap#766]
I tried to apply shap to my ensemble model(categorical, continuous, text), but I couldn't get summary plot and one of force plots. How can I get this? Please help me~

explainer_final = shap.DeepExplainer(final_model, [X_categorical_npary, X_continuous_npary, X_padded_docs, full_train_npary])
shap_values_final = explainer_final.shap_values([X_categorical_test_npary, X_continuous_test_npary, padded_docs_test, full_test_npary], ranked_outputs=None, output_rank_order='max')
shap.summary_plot(shap_values_final, [X_categorical_npary, X_continuous_npary, X_padded_docs, full_train_npary], plot_type="bar")

AttributeError                            Traceback (most recent call last)
<ipython-input-53-907067c1b5f7> in <module>
----> 1 shap.summary_plot(shap_values_final, [X_categorical_npary, X_continuous_npary, X_padded_docs,full_train_npary], plot_type="bar")

C:\ProgramData\Anaconda3\lib\site-packages\shap\plots\summary.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot, layered_violin_max_num_bins, class_names)
     73         features = None
     74 
---> 75     num_features = (shap_values[0].shape[1] if multi_class else shap_values.shape[1])
     76 
     77     if feature_names is None:

AttributeError: 'list' object has no attribute 'shape'

shap.force_plot(explainer_final.expected_value[0], [X_categorical_test_npary, X_continuous_test_npary, padded_docs_test, full_test_npary][0])  ==> this is OK

shap.force_plot(explainer_final.expected_value[0], [X_categorical_test_npary, X_continuous_test_npary, padded_docs_test, full_test_npary][0], shap_values_final[0])

TypeError                                 Traceback (most recent call last)
<ipython-input-67-5e28f2d44a82> in <module>
----> 1 shap.force_plot(explainer_final.expected_value[0], [X_categorical_test_npary, X_continuous_test_npary, padded_docs_test, full_test_npary][0], shap_values_final[0])

C:\ProgramData\Anaconda3\lib\site-packages\shap\plots\force.py in force_plot(base_value, shap_values, features, feature_names, out_names, link, plot_cmap, matplotlib, show, figsize, ordering_keys, ordering_keys_time_format, text_rotation)
    168                     ordering_keys=ordering_keys,
    169                     ordering_keys_time_format=ordering_keys_time_format,
--> 170                     text_rotation=text_rotation
    171                 )
    172 

C:\ProgramData\Anaconda3\lib\site-packages\shap\plots\force.py in visualize(e, plot_cmap, matplotlib, figsize, show, ordering_keys, ordering_keys_time_format, text_rotation)
    281             assert False, "Matplotlib plot is only supported for additive explanations"
    282         else:
--> 283             return AdditiveForceArrayVisualizer(e, plot_cmap=plot_cmap, ordering_keys=ordering_keys, ordering_keys_time_format=ordering_keys_time_format).html()
    284     else:
    285         assert False, "visualize() can only display Explanation objects (or arrays of them)!"

C:\ProgramData\Anaconda3\lib\site-packages\shap\plots\force.py in html(self)
    417     document.getElementById('{id}')
    418   );
--> 419 </script>""".format(err_msg=err_msg, data=json.dumps(self.data), id=id_generator()))

C:\ProgramData\Anaconda3\lib\json\__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

C:\ProgramData\Anaconda3\lib\json\encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

C:\ProgramData\Anaconda3\lib\json\encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

C:\ProgramData\Anaconda3\lib\json\encoder.py in default(self, o)
    178         """
    179         raise TypeError("Object of type '%s' is not JSON serializable" %
--> 180                         o.__class__.__name__)
    181 
    182     def encode(self, o):

TypeError: Object of type 'ndarray' is not JSON serializable

**Comment by slundberg** [comment]
I would have to dig in more to know for sure, but it could be that you have a multi-output model and so have lists of ndarrays. You need to chose one of the outputs (by indexing the lists) before plotting with `force_plot`.
