### ISSUE TITLE
LinAlgError: singular matrix

### ISSUE THREAD

**Issue by Robertaviola** [shap/shap#769]
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-2-a04f77a0c0f3> in <module>
     20 explainer = shap.TreeExplainer(classifier)
     21 shap_values = explainer.shap_values(Xv)
---> 22 shap.summary_plot(shap_values, Xv, feature_names=WANTED_COLUMNS, plot_type="violin")
     23 
     24 #shap.dependence_plot(0, shap_values, Xv, feature_names=WANTED_COLUMNS)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shap/plots/summary.py in summary_plot(shap_values, features, feature_names, max_display, plot_type, color, axis_color, title, alpha, show, sort, color_bar, auto_size_plot, layered_violin_max_num_bins, class_names)
    235                     ds = gaussian_kde(shaps + np.random.randn(len(shaps)) * (global_high - global_low) / 100)(xs)
    236                 else:
--> 237                     ds = gaussian_kde(shaps)(xs)
    238                 ds /= np.max(ds) * 3
    239 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/stats/kde.py in __init__(self, dataset, bw_method, weights)
    206             self._neff = 1/sum(self._weights**2)
    207 
--> 208         self.set_bandwidth(bw_method=bw_method)
    209 
    210     def evaluate(self, points):

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/stats/kde.py in set_bandwidth(self, bw_method)
    552             raise ValueError(msg)
    553 
--> 554         self._compute_covariance()
    555 
    556     def _compute_covariance(self):

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/stats/kde.py in _compute_covariance(self)
    564                                                bias=False,
    565                                                aweights=self.weights))
--> 566             self._data_inv_cov = linalg.inv(self._data_covariance)
    567 
    568         self.covariance = self._data_covariance * self.factor**2

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/linalg/basic.py in inv(a, overwrite_a, check_finite)
    972         inv_a, info = getri(lu, piv, lwork=lwork, overwrite_lu=1)
    973     if info > 0:
--> 974         raise LinAlgError("singular matrix")
    975     if info < 0:
    976         raise ValueError('illegal value in %d-th argument of internal '

LinAlgError: singular matrix

**Comment by jennykathambi90** [comment]
I am also getting the following error when I try to plot a violin plot. as follows:

```
# plot the feature importance
shap.summary_plot(shap_values, data_work_with, plot_type="violin", show=False)
```

> raise ValueError('illegal value in %d-th argument of internal 
> 
> LinAlgError: singular matrix

This error happens after I add all possible interaction terms to my training data, train the model then attempt to plot the violin plot as above.
