### ISSUE TITLE
unable to use force_plot

### ISSUE THREAD

**Issue by koyeli28** [shap/shap#771]
I am able to generate plots for individual observations but not as a whole. X_train is a df.
shap.force_plot(explainer.expected_value[1], shap_values[1], choosen_instance)##This is working
But,
shap.force_plot(explainer.expected_value, shap_values, X_train)  ##error
gives error.

AssertionError                            Traceback (most recent call last)
<ipython-input-21-8d7548528691> in <module>()
----> 1 shap.force_plot(explainer.expected_value, shap_values, X_train)

/usr/local/lib/python3.6/dist-packages/shap/plots/force.py in force_plot(base_value, shap_values, features, feature_names, out_names, link, plot_cmap, matplotlib, show, figsize, ordering_keys, ordering_keys_time_format, text_rotation)
     72 
     73 
---> 74     assert not type(shap_values) == list, "The shap_values arg looks looks multi output, try shap_values[i]."
     75 
     76     link = convert_to_link(link)

AssertionError: The shap_values arg looks looks multi output, try shap_values[i].

**Comment by slundberg** [comment]
It looks like shap_values is a list, which means it is a list of numpy arrays each of which is an explanation of a different output of the model. Have you tried the suggestion in the error? Does that only plot a single example?

**Comment by koyeli28** [comment]
Here is what i have already done.

explainer = shap.TreeExplainer(random_forest)
shap_values = explainer.shap_values(X_train) ###X_train is a df is it incorrect to pass a df for shap_values??

shap.force_plot(explainer.expected_value, shap_values[0,:], X_train.iloc[0,:]) ## gives below error

TypeError                                 Traceback (most recent call last)
<ipython-input-15-0bb1109ba046> in <module>()
----> 1 shap.force_plot(explainer.expected_value, shap_values[0,:], X_train.iloc[0,:])

TypeError: list indices must be integers or slices, not tuple

But the below visualization worked.
shap.initjs()
shap.force_plot(explainer.expected_value[0], shap_values[0], X_train) 

The above line gave the desired stacked plot but in your explanation i saw it was done with only 
shap.force_plot(explainer.expected_value, shap_values, X)
Why is it required to enter the index?

**Comment by slundberg** [comment]
It depends how many outputs the model has. If the model being explained has only one output then you get just a single explanation for that output, but if it has more than one output then it returns a list of explanations, once for each output of the model.

**Comment by PedroMartinez4** [comment]
> It depends how many outputs the model has. If the model being explained has only one output then you get just a single explanation for that output, but if it has more than one output then it returns a list of explanations, once for each output of the model.

@slundberg You gave a reason but not a fix, or am I missing something?
