### ISSUE TITLE
Using TreeExplainer with an ensemble

### ISSUE THREAD

**Issue by kjanko** [shap/shap#775]
Hi,

I have an ensemble that consists of 2n-1 xgb classifiers. The prediction probability is returned as an average of the probabilities that are returned by all the models. My question is, is there a way to use TreeExplainer instead of KernelExplainer to explain the output of such ensemble?

(the reason I can't use KernelExplainer is because of MemoryError, my dataset in memory is around 30GB and with 128GB RAM available it throws the exception)

**Comment by MichalPorwisz** [comment]
You can try using TreeExplainer to explain predictions of each classifier individually, and then just calculate average of those individual explanations to obtain final SHAP values.

See here:
https://github.com/slundberg/shap/issues/457#issuecomment-468857321

**Comment by kjanko** [comment]
Thanks!
