### ISSUE TITLE
Pytorch example for GradientExplainer 

### ISSUE THREAD

**Issue by mayurnewase** [shap/shap#776]
please provide a exampler how to use pytorch model with GradientExplainer,it is only present for keras.

**Comment by mayurnewase** [comment]
found it in examples

**Comment by MariaBjelikj** [comment]
Could you attach a link of the example you found?

**Comment by zmce2018** [comment]
@MariaBjelikj You can find it [here](https://notebook.community/slundberg/shap/notebooks/gradient_explainer/Explain%20an%20Intermediate%20Layer%20of%20VGG16%20on%20ImageNet%20%28PyTorch%29). I have tested it and it works really well.
