### ISSUE TITLE
How to define the neighbourhood and base value for the feature selection

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#78]
1.Could you please tell me how Kernel SHAP has implemented (or selected ) the neighbourhood for instance generation in the code.
2. Next question is, can you please describe how you have select the feature values for the base value E[f(z)] in the code.
3. Don't we need to do the discretization for the selected instances or the data here?
4. Could you please explain how Kernal SHAP has used the training set to generate new instances?

**Comment by slundberg** [comment]
Good questions. Some of which are best answered by looking at a bare bones brute force implementation of Kernel SHAP: https://github.com/slundberg/shap/blob/master/notebooks/Simple%20Kernel%20SHAP.ipynb

1. It enumerates all subsets below a certain size that can be fully covered by the chosen number of samples. Then is randomly draws the rest of the samples from the Shapley Kernel density.
2. The data matrix passed when constructing the `KernelExplainer` represents the background. So the base value is just the average output of the model applied to this matrix.
3. I think checking out the notebook I linked to above would help clarify this and question 4.

**Comment by Dilini-Sewwandi-Rajapaksha** [comment]
Thank you very much for your answer. 
In you code, for the question number 2, the base value is always the 1st value of the dataset. Is that so? Not the average?
`   def varying_groups(self, x):
        varying = np.zeros(len(self.data.groups))
        for i in range(0, len(self.data.groups)):
            inds = self.data.groups[i]
            num_matches = sum(np.abs(x[0, inds] - self.data.data[:, inds]) < 1e-7, 0)
            varying[i] = sum(num_matches != len(inds) * self.data.data.shape[0])
        return np.nonzero(varying)[0]`

I am very sorry if I am disturbing you. I just need to clarify this. 

Thank you.

**Comment by Dilini-Sewwandi-Rajapaksha** [comment]
I's better that if you add some comments to the code, in the link that you have provided. 

Thank you.

**Comment by DiliSR** [comment]
Thank you.
According to the basic idea of SHAP, base value is the value predicted by the model without any features. Am I right? So in the bare bones brute force implementation you have taken reference = np.zeros(M) as the base value. Am I right? Could you please tell me what is the variable in original kernel SHAP that you have used as the base value. I couldn't find that in your code.

Thank you.

**Comment by slundberg** [comment]
In the Kernel SHAP implementation the base dataset is provided by the user.
So whatever gets passed as the dataset in the KernelExplainer constructor
becomes the base dataset, and the average output of the model on this
dataset becomes the base value.

**Comment by DiliSR** [comment]
Thank you. I got the idea.
