### ISSUE TITLE
side-by-side summary_plots

### ISSUE THREAD

**Issue by ironv** [shap/shap#780]
Is it possible to create two `summary_plot`s side-by-side (in a Jupyter notebook)?  I tried the following:

```
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
shap.summary_plot(shap_mat, valid_mat, show=False)
plt.subplot(1,2,2)
shap.summary_plot(shap_unm, valid_unm, show=False)
plt.tight_layout()
plt.show()
```

This results in a figure where the individual subfigures are truncated.

**Comment by slundberg** [comment]
The plots don't get truncated when I try it. Perhaps it is due to some long labels/lack of space?

**Comment by ricardonsantos** [comment]
You should set plot_size=None
_i.e._: 
shap.summary_plot(shap_mat, valid_mat, plot_size=None, show=False)

**Comment by ricardonsantos** [comment]
Also, one could use   plt.subplots_adjust(wspace=6.0)
