### ISSUE TITLE
Visualizers in React: this.invLinkFunction may be undefined

### ISSUE THREAD

**Issue by jaller94** [shap/shap#785]
## Steps to reproduce
1. Move your mouse over a visualizer before the first draw (comment out draw() or be really fast)

## Expected
Nothing happens.

## Actual
A JavaScript error gets thrown that this.invLinkFunction is undefined.

## Explanation
`this.invLinkFunction` is first set in the `draw` methods of `AdditiveForceVisualizer` and `AdditiveForceArrayVisualizer`. The mouseOver listeners are set before draw is executed. Moving the mouse over a graph will spawn an error that invLinkFunction is undefined.

e.g.
https://github.com/slundberg/shap/blob/0c608c5d38e1e2e32d757c7759eee217d0f24af4/javascript/visualizers/AdditiveForceArrayVisualizer.jsx#L226

**Comment by slundberg** [comment]
Thanks for noting this! ...marking this as a todo.

**Comment by jaller94** [comment]
I've fixed this locally in a copy of the components. It's using a method on
the class for the function generation.
Furthermore, I used state & getDerivedStateFromProps for caching the
function as long as baseValue and link don't change.


A PR isn't just copy & paste because I made use of another babel plugin
(static on class) and we use a strict ESLint config for different
formatting, but I can send you a PR within a few days or so to review. If you
happen to not like it, you can still solve it differently.

**Comment by slundberg** [comment]
A PR would be great. Thanks!

**Comment by jaller94** [comment]
My priorities have shifted and I will likely not be able to submit a PR.
