### ISSUE TITLE
Interaction Values High Dimensional Data

### ISSUE THREAD

**Issue by jlevy44** [shap/shap#786]
Hi there!

I'm curious about the scalability and memory concerns for the interaction_values

If the number of samples is about 10k, number of features is 10k and number of outcomes is order of 10, the number of SHAP interaction values would be 10*10k^3=1e13  (order, you could divide this by 2).

This seems intractable. Is there anyway to compute this quickly and grab a subset for p > n and n is large? I'm just looking to sum the interactions up across individuals and classes but even n_features x n_features can be a bit. Do I just take subsets of the test set? Thanks!

**Comment by slundberg** [comment]
The interaction values are a matrix, but @jjanizek was working on allowing single rows of that matrix to be computed at a time. That would help you because then you would only need to compute the rows you want and ignore the rest. Not sure the status there though right now.

**Comment by jlevy44** [comment]
Ok thanks. I’m familiar with the output being a matrix. Please keep me posted, happy to help if needed. 

I’ll probably calculate interactions on a sample of individuals, calculate one sample at a time and sum for memory efficiency. How fast is the algorithm with high number of features? I may parallelize the computation.

**Comment by slundberg** [comment]
Sounds good. The algorithm essentially involves running the non-interaction version of Tree SHAP twice for each feature (for each row of the matrix). So it should be about p times slower.

**Comment by jlevy44** [comment]
Okay. Can that handle 10k features? It seems like the sweet spot is 100-1k features. I can't get it to run in reasonable time.

**Comment by jlevy44** [comment]
I'll close the issue. I think you've addressed the main concerns. Thanks!
