### ISSUE TITLE
Shap values are log-odds when using xgboost with objective='binary:logistic'

### ISSUE THREAD

**Issue by Toekan** [shap/shap#79]
Hi,

I'm looking into using shap to present results in projects that use an Xgboost in binary classification. (Very impressive btw, both the package as the publications, thanks for creating this!)

I would like to have shap values related to risk score/probability outputs, rather than log-odds. As far as I understand from reading here, shap values should be directly related to whatever the outputs of the model are. I thus choose to train XGboost (with the sklearn API) with objective set as 'binary:logistic', which according to xgboost readthedocs creates probabilities as the model output:
```
“binary:logistic” –logistic regression for binary classification, output probability
```
But the resulting shap values range between about -5 to +5. Any idea why?

Quick summary of my python code:

```python
param = dict(objective='binary:logistic',
            learning_rate=0.3,
            max_depth=6,
            n_estimators=150,
            base_score=0.5, 
            silent=0)
model = XGBClassifier(**param)
model.fit(X_train, y_train)

shap.TreeExplainer(model).shap_values(X_test)
```

Sorry if I'm doing something wrong related with SKlearn/Xgboost, but I've gone through all the XGboost documentation and didn't find anything clearing up my issue.

**Comment by Toekan** [comment]
Ow, seems I missed closed issues (only looked at the open ones apparently) concerning this question. I'll have a look at those first to see if they solve my problem.

Sorry!

Posted my updated question #29, so I guess this can close?

**Comment by slundberg** [comment]
Closing since the discussion is finished on #29
