### ISSUE TITLE
Overlapping points in a figure plot by "shap.dependence_plot"

### ISSUE THREAD

**Issue by wmmxk** [shap/shap#792]
I was wondering how the overlapping points are dealt with in the "shap.dependence_plot". It seems that late points might cover previous points in a scatter plot if I have thousands of datapoints. If that is true, I could not fully trust the color pattern in  a dependence plot. Am I right? BTW, I like the dependence plot.

**Comment by wmmxk** [comment]
I saw the data points were [randomly shuffled] (https://github.com/slundberg/shap/blob/26c88394e2e3f2ee5e6a6f34200eda99c1baa975/shap/plots/dependence.py#L140), so the overlapping should not matter.

**Comment by slundberg** [comment]
That's right, they are shuffled for exactly this reason, so that the overlapping is random (and so preserves the overall density patterns). If you have lots of points, it is sometimes helpful to use the `alpha` parameter for transparency.
