### ISSUE TITLE
to_list() usage breaks compatibility with pandas < 0.24.x

### ISSUE THREAD

**Issue by candalfigomoro** [shap/shap#797]
Hi,

is there a minimum required version for pandas?

Because at these lines:

https://github.com/slundberg/shap/blob/0c608c5d38e1e2e32d757c7759eee217d0f24af4/shap/plots/decision.py#L364

https://github.com/slundberg/shap/blob/0c608c5d38e1e2e32d757c7759eee217d0f24af4/shap/plots/decision.py#L368

You use the to_list() method, but it exists as alias for tolist() since pandas 0.24. For compatibility with pandas < 0.24, you should use tolist() without underscore instead of to_list()

**Comment by thatlittleboy** [comment]
Closing as not planned, this problem doesn't seem too relevant now that 4 years has passed.
