### ISSUE TITLE
0.30.1 released with dill import but without dill in requirements

### ISSUE THREAD

**Issue by marco-c** [shap/shap#802]
There's something wrong with the 0.30.1 release. The package you released does not correspond to the source code of the 0.30.1 tag.
For example, 6d6fcd1fb01c9254e266c93ff25fa8310e45b614 is missing, so the released package still has the `dill` import.

`dill` is not in the requirements, so projects using shap will have to manually install it.
Could you rectify the situation by making a new release?

**Comment by PhilipMay** [comment]
I have the same issue:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-d3f52b740e76> in <module>
      7 import sys
      8 import warnings
----> 9 import shap

~/miniconda3/envs/tf2-2/lib/python3.6/site-packages/shap/__init__.py in <module>
     18 from .plots.embedding import embedding_plot
     19 from . import datasets
---> 20 from . import benchmark
     21 from .explainers import other
     22 from .common import approximate_interactions, hclust_ordering

~/miniconda3/envs/tf2-2/lib/python3.6/site-packages/shap/benchmark/__init__.py in <module>
      1 from . import measures
----> 2 from . import metrics
      3 from . import methods
      4 from . import models
      5 from .. import datasets

~/miniconda3/envs/tf2-2/lib/python3.6/site-packages/shap/benchmark/metrics.py in <module>
     13 import hashlib
     14 import os
---> 15 import dill as pickle
     16 
     17 try:

ModuleNotFoundError: No module named 'dill'
```

**Comment by slundberg** [comment]
That's what I get for bumping a version and then traveling for a week. Sorry about that. It should only effect the source code package on pip (which is obviously an important version). I am pushing a 0.30.2 that makes the dill dependency optional (since it is only used for benchmark tests).

**Comment by marco-c** [comment]
@slundberg ping about 0.30.2 :)

**Comment by marco-c** [comment]
Thanks!
