### ISSUE TITLE
Aggregation of Shap Values for time-series (3D) data

### ISSUE THREAD

**Issue by cdpierse** [shap/shap#803]
I've been working on a time series problem of sorts and have been trying to use SHAP to interpret the results. Being a time series the data comes as a 3D array (#Samples, #Sequences, #Features)

I've come up with the below aggregation method to effectively create  mean shap values in the shape of (#Samples, #Features). 

The approach seems to be generally working so far in that the explanations are making sense, one thing I have noticed is that the force plot values for probabilities become weaker. I.e. it's very rare to see a prediction go close to 1 or 0. The force plots are still correct they just to tend to hover a bit above or below the base value. 

Does this sort of approach make sense to you and do you think there's a more intuitive way I could be handling the SHAP values?

Thanks!

```python
    def aggregate_shap_values(self):
        shap_array = np.array(self.shap_values[0]) # array of shap values computed for time series

        mean_shaps = []

        for i in range(shap_array.shape[0]):
            max_seq_length = shap_array.shape[1]
            for k in range(shap_array.shape[1]):
                if i != 0 and k != 0:  # buggy index I skip over
                    # boolean check for zeroed out padded rows
                    all_zero = not np.all(self.data[i, k, ] == 0)
                    if all_zero:  # if row k is all zero
                        max_seq_length = k
            mean_shaps.append(shap_array[i, :max_seq_length, :].mean(axis=0).tolist()) 
        self.shap_values = np.array(mean_shaps)
```

**Comment by zuzhaoye** [comment]
> 
> 
> I've been working on a time series problem of sorts and have been trying to use SHAP to interpret the results. Being a time series the data comes as a 3D array (#Samples, #Sequences, #Features)
> 
> I've come up with the below aggregation method to effectively create mean shap values in the shape of (#Samples, #Features).
> 
> The approach seems to be generally working so far in that the explanations are making sense, one thing I have noticed is that the force plot values for probabilities become weaker. I.e. it's very rare to see a prediction go close to 1 or 0. The force plots are still correct they just to tend to hover a bit above or below the base value.
> 
> Does this sort of approach make sense to you and do you think there's a more intuitive way I could be handling the SHAP values?
> 
> Thanks!
> 
> ```
> def aggregate_shap_values(self):
>     shap_array = np.array(self.shap_values[0]) # array of shap values computed for time series
> 
>     mean_shaps = []
> 
>     for i in range(shap_array.shape[0]):
>         max_seq_length = shap_array.shape[1]
>         for k in range(shap_array.shape[1]):
>             if i != 0 and k != 0:  # buggy index I skip over
>                 # boolean check for zeroed out padded rows
>                 all_zero = not np.all(self.data[i, k, ] == 0)
>                 if all_zero:  # if row k is all zero
>                     max_seq_length = k
>         mean_shaps.append(shap_array[i, :max_seq_length, :].mean(axis=0).tolist()) 
>     self.shap_values = np.array(mean_shaps)
> ```

I like this idea. If I understand correctly, you are getting the mean SHAP values in the sequence dimension. I am also interested if we can get the SHAP values for the same feature from different time steps, e.g. what are the SHAP values for x(t), x(t-1), and x(t-2) respectively? It is helpful to determine which lag x is more important. A similar task is easy for a fully connected net or a random forest, but not easy on LSTM.

**Comment by zuzhaoye** [comment]
I like this idea. If I understand correctly, you are getting the mean SHAP values in the sequence dimension. I am also interested if we can get the SHAP values for the same feature from different time steps, e.g. what are the SHAP values for x(t), x(t-1), and x(t-2) respectively? It is helpful to determine which lag x is more important. A similar task is easy for a fully connected net or a random forest, but not easy on LSTM.

**Comment by keyram** [comment]
@cdpierse Hi Charles, pretty late comment I guess :) I ran into your thread while searching for some ways to apply SHAP to LSTM time series model. I understand how you made the 3D shap values into 2D with aggregating the time sequences into one value. However I wonder how you could create the 3D shap values from the beginning. I have been using deepexplainer and this doesn't accept the 3D input (the training data from prediction model) to create shap values out of it. Which explainer did you use?
