### ISSUE TITLE
Brute Force linear explainer implementation

### ISSUE THREAD

**Issue by steremma** [shap/shap#805]
Hello.

In order to get an indication of how well the sampling approximation works as a function of `nsamples` in the `LinearExplainer`, I decided to calculate the pure shapley values using a brute force approach. I noticed a `ToDo` comment proposing exactly this approach for the case where `nsamples` is actually larger than the number of possible coalitions and would therefore be happy to submit a PR once its done.

However I have had some trouble understanding the `_estimate_transforms` method. Issue #573 seems to ask a similar question but is as of now unaddressed. I could submit a [WIP] PR to initiate some discussion but it would also be really helpful to get a reference for that method (be it a paper or an informal write-up). I did check several related papers including the [NIPS](https://papers.nips.cc/paper/7062-a-unified-approach-to-interpreting-model-predictions.pdf) one but there is nothing about linear models that consider correlation of input features. For example **section 4.2** of the linked paper only considers the independent case.

@slundberg since you are the author of the function is question (as well as the paper) maybe you could shed some light into this? Thanks in advance!

## EDIT: Potential Issue in the existing estimation

By going through the existing estimation code I observed that smaller coalitions have a greater effect on the estimation than larger ones. Please correct me if I am wrong but here is the reasoning:

Each of `nsamples` iterations will start with a coalition of size `1`, then build up towards bigger ones. So there is an equal additive effect on the estimation coming from coalitions of size `1`, as from coalitions of arbitrary size `s >> 1`. However this is not true for the number of unique coalitions. For example, if we have `10` features, then there are `10` coalitions of size `1` but `252` coalitions of size `5`. Therefore those coalitions of size `5` have individually a much smaller effect on the estimation than the coalitions of size `1` (some of them might never be explored when `nsamples` is small). This discrepancy will of course get much larger when `M` increases arbitrarily.

This could be a desired effect if we consider very small and very large coalitions more important (I have some intuition that supports this but can't quite formulate it yet). Since we currently lack documentation I am not sure that this is a feature and not a bug.

**Comment by swebs** [comment]
See link in this issue:
https://github.com/slundberg/shap/issues/952
