### ISSUE TITLE
is it possible to pass the second feature (used for coloring and on right y axist) as argument in depedence plot ?

### ISSUE THREAD

**Issue by mohit-shrma** [shap/shap#81]
Hi,

is it possible to pass the second feature which is used to color the instances in dependence plot? Currently, it choose the feature at random but it will be great if I can specify that feature as well as an additional argument.

**Comment by slundberg** [comment]
Yep, just use the interaction_index option. I should point out by default
it does its best to pick a feature that will create a clear color separation
