### ISSUE TITLE
SHAP VALUES created as list not np.ndarray

### ISSUE THREAD

**Issue by AbhinavMudgal** [shap/shap#810]
Hi I was trying shap for my dataset and xgboost model

This error coming
101     # allow vectors to be passed
--> 102     if len(shap_values.shape) == 1:
    103         shap_values = np.reshape(shap_values, len(shap_values), 1)
    104     if len(features.shape) == 1:

AttributeError: 'list' object has no attribute 'shape'

on  executing
shap.dependence_plot("fprice", shap_values, X)
shap_values turn outv to be list but in your example its numpy pls help

**Comment by slundberg** [comment]
If you get a list that means the model had multiple outputs and each list element is a matrix of explanations for one of the outputs.

**Comment by AbhinavMudgal** [comment]
Thank you
