### ISSUE TITLE
Can't get the "probability"  output after reload the lightgbm model

### ISSUE THREAD

**Issue by manoshape** [shap/shap#813]
I can get the "probability" output based on the lightgbm model i just trained like cell 49 shows in jupyter, but why i can't get the "probability"  output after reload the lightgbm model like the cell 51 shows ?

<img width="673" alt="shapbug" src="https://user-images.githubusercontent.com/22488919/65107292-a50a7e80-da09-11e9-8f8a-546dfe3fb6bb.png">

**Comment by slundberg** [comment]
Perhaps you are using a LGBMRegressor object? If so then there is no logit link and the output of the model does not need transformed.

**Comment by manoshape** [comment]
Thanks sir, my LightGBM 'objective': 'binary'.   When i reload the LightGBM model , it will lost the params, so i have to give the params dict to the reloaded model，or it will meet the bug like the picture shows. 

So when i want to use "probability" for output, should i have to use the TreeExplainer based on test_df which i pointed ?
On the other hand, explainer.expected_value and explainer.shap_values are both based on the 
mean of the "probability" output?

```python 
shap.TreeExplainer(gbm,data=test_df,feature_dependence="independent",model_output="probability")
```
