### ISSUE TITLE
Kernel SHAP and Deep SHAP values differ from true model coefficients

### ISSUE THREAD

**Issue by ArashSaeidpour** [shap/shap#814]
Hello SHAP folks,

I have been trying to use SHAP on a dummy linear regression model. here is the notebook:

https://github.com/ArashSaeidpour/model-agnostic-interp/blob/master/Kernel%20SHAP%20vs%20LIME.ipynb

I made 1000 random draws from 8 independent Gaussian RVs and used them as my features in a linear model, then I fitted a feedforward NN on the the data, and finally used SHAP and Deep SHAP values to see if they are the same as my linear model coefficients.

Here is my issue, local SHAP and Deep SHAP values differ from true coefficients of the model (which I defined):

![image](https://user-images.githubusercontent.com/26612570/65198006-7794f380-da50-11e9-9ee8-4e66b32418e1.png)

however, global SHAP and Deep SHAP values (mean of absolute local SHAPs) are very close to true model coefficients, but obviously with different signs:

![image](https://user-images.githubusercontent.com/26612570/65198318-aca14600-da50-11e9-818a-d1775f0860cb.png)

Any suggestions??

Thank you in advance

**Comment by jorgecarleitao** [comment]
The shapley values are not expected to be the same as the model coefficients on a linear model. See corollary 1 of https://arxiv.org/pdf/1705.07874.pdf or [this test](https://github.com/slundberg/shap/blob/3889109b47a8583901d82cba81913c6afa8e3886/tests/explainers/test_kernel.py#L186).

Also, note that shapley values are computed irrespectively of the input target. Therefore, the only thing that it can say is something about the ML model's coefficients, not something about the generating model's coefficients (the coefficients you put in `np.random....`)

**Comment by ArashSaeidpour** [comment]
Thanks that was really helpful.

I agree with your first point, I checked the corollary 1 and local shapely values are not supposed to be the linear model coefficients, however they can be calculated from local shapely values (see the last paragraph to see how). 

About your second point about shapely values being computed irrespectively of the input, local shapely value for a particular feature at a given instance is given by the change in the expected model prediction when conditioning on that feature, so they are conditioned on the local values of the feature (see Figure 1 in https://arxiv.org/pdf/1705.07874.pdf)

Going back to the first point, linear model coefficients for a given instance can be found by dividing the shapely values by xj-E[xj].

**Comment by jorgecarleitao** [comment]
@ArashSaeidpour, note that I wrote "irrespectively of the input **target**", not irrespectively of the input. What I am trying to say here is that shapley values do not say anything about `y`, they only say something about the prediction `f(x)`. Whether `f(x)` is close to `y` is not a concern of shapley. In this sense, if we generate data as 

```
x = np.random.normal(size=(2000, 2))
y = 2*x[:, 0] + 3*x[:, 1] + np.random.normal(size=2000, scale=0.1)
```
we cannot expect the shapley values to be `\phi_1 = 2*x` and `\phi_2 = 3*x`, since this only holds true if 1. we use a linear model and 2. if the model fits this data accordingly (e.g. correct fitting procedure and/or penalization).
