### ISSUE TITLE
ONLY SHAP VALUES NEEDED FOR XGBOOST Explainer

### ISSUE THREAD

**Issue by AbhinavMudgal** [shap/shap#818]
Can I just copy few files ,
I just need to get the shap values of an xgboost model through explainer.
Can this be done.
Please help and tell the files that I can copy and run

**Comment by stephenpardy** [comment]
If you just want to get the SHAP values of an XGBoost model, you can use the `pred_contribs` argument in the `predict` function directly in XGBoost: https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.Booster.predict
