### ISSUE TITLE
Doesn't seem to run in jupyter lab

### ISSUE THREAD

**Issue by JulioBarros** [shap/shap#82]
In jupyter lab the example cut and pasted from the read me results in the "Visualization omitted, Javascript library not loaded!" error message. However the exact same code works in jupyter notebook for me.

Is there a setting or something for jupyter lab or anything I can do to work around this? 

Thanks.

**Comment by akurniawan** [comment]
Same problem here, trying to run the example from README but got the error
![screen shot 2018-05-14 at 12 40 40](https://user-images.githubusercontent.com/4723643/39980054-149c1692-5774-11e8-95e9-ae3d74d45fd6.png)

**Comment by slundberg** [comment]
Unfortunately the JS force_plot Jupyter visualizations are blocked by new
security features in jupyter lab. At some point they need to be made into a
jupyter module I think, but I have not worked on that yet.

**Comment by chrisadas** [comment]
I think a note about Jupyter Lab should be added to the displayed error message.

**Comment by slundberg** [comment]
@chrisadas good point. Done.

**Comment by staplet14** [comment]
Any idea why this error also occurs when running in a Jupiter notebook?
python 3.7.1
jupyter 1.0.0

**Comment by slundberg** [comment]
@staplet14 I am not sure (other than the common reasons stated in the error message). My jupyter is version 4.4.0 perhaps 1.0 is a fairly old install?

**Comment by edjzhang** [comment]
@slundberg The example from the README works, but I'm on shap version 0.24.0 rather than 0.25.2. Could that be a reason for the error @staplet14 is seeing? Not sure what change could be driving it besides maybe commit 226be328a72239d6e99279d4137e5412d50169a5.

**Comment by staplet14** [comment]
@ezhangsfl and @slundberg, I got it to work by installing from conda-forge into a conda env, shap v0.25.1, Jupiter core v4.4.0, py 3.6. 

Previously I was pip installing into a conda env.

**Comment by Herm41** [comment]
Kernel dead when running:
shap_values = shap.TreeExplainer(model).shap_values(X)

**Comment by slundberg** [comment]
Thanks @Herm41, if you provide a self contained example I can run I'll look into it.
