### ISSUE TITLE
WHL File of SHAP for amazon linux 

### ISSUE THREAD

**Issue by AbhinavMudgal** [shap/shap#822]
Is there whl support for amazon linux .

**Comment by AbhinavMudgal** [comment]
Error: PythonPipBuilder:ResolveDependencies - {shap==0.30.1(wheel)}

This build error coming

**Comment by jonnor** [comment]
Hi @AbhinavMudgal. Can you please re-test this on latest version of shap? There are wheels built that should work on most current Linux distributions.

**Comment by detrin** [comment]
@thatlittleboy Candidate for closing because of lack of response.

@AbhinavMudgal if the issue is still active for you, the issue can be reopened.
