### ISSUE TITLE
Is there any shap lite VERSION ? One without graphs but just only shap values of model.

### ISSUE THREAD

**Issue by AbhinavMudgal** [shap/shap#823]
PLEASE HELP.

**Comment by AbdealiLoKo** [comment]
I would like this too, we just need the predictions and nothing else. 
The libraries that are doing plotting need to be approved for installation and it gets painful to get all the dependencies done. 

Can we use extra-requires to make it 
pip install shap[plots]

For the plots and keep the default light?

**Comment by slundberg** [comment]
This has already been done in the master version and will land once I push the next update :)

**Comment by AbdealiLoKo** [comment]
Awesome!

**Comment by jonnor** [comment]
Newer releases with this is now available. Testing would be welcomed @AbdealiJK and @AbhinavMudgal. If you find any specific problems, please open new issues for those.

I believe this issue can be closed now. CC @slundberg

**Comment by detrin** [comment]
@thatlittleboy Candidate for closing I believe.

That being said, I think the split of the repository into smaller chunks would really help. I will create an issue in future for that.
