### ISSUE TITLE
DeepExplainer Gets All 0 Shap_Value Outputs

### ISSUE THREAD

**Issue by bignuo** [shap/shap#827]
@slundberg 
Hi everyone, 

I tried to use the Shap DeepExplainer to interpret a Keras model. This model requests mixed inputs(image, categorical and numerical) and the output is a single float number. 
```python
model.predict([Blackout_0[0:1], Fnol_0[0:1]])
```
In the above code, Blackout_0[0:1] is a single picture and Fnol_0[0:1] contains some values for the categorical and numerical data.  Then I am able to get the output 0.88135. After that, I start the Shap part.
```python
e = shap.DeepExplainer(model, [Blackout_0[0:1], Fnol_0[0:1]])
shap_values = e.shap_values([Blackout_0[0:1], Fnol_0[0:1]])
```
I do notice that the output Shap value is actual a list cause I have mixed input. However, the entire Shap value list is filled by 0. My import image shape is (512,512,3) and my Fnol shape is (1,102). My output Shap value match these shapes but with all 0. Can somebody provides any help for that? Really appreciate it!

**Comment by daw454** [comment]
Hi, 

did you find a solution for that. I'm facing the same problem.
