### ISSUE TITLE
Can do the  multi-Progress when calculating the shap_values?

### ISSUE THREAD

**Issue by manoshape** [shap/shap#829]
My test dataset row is small about 4k, but the features of each sample is big about 400+ also my GBM tree is about 400. 

I found that calculating the 1k samples will use 12mins, but when calculating 4k samples will use about 300~500min as the tqdm showed!?

![image](https://user-images.githubusercontent.com/22488919/65494823-27061600-dee8-11e9-90db-4b57119ca987.png)

![image](https://user-images.githubusercontent.com/22488919/65494730-ee663c80-dee7-11e9-83c5-1482f58a1a9c.png)

Based on the paper , i think that shap_value has not relationship with other samples' feature values once i get the base_value of the whole dataset.

![image](https://user-images.githubusercontent.com/22488919/65494633-c4ad1580-dee7-11e9-9859-cccb862624b8.png)

So how can i speed up the calculation of  shap_values instead of setting the tree_limit & approximate=True because i don't like to get the approximate  value ? 

Another , can i use the multi-Progress when calculating the shap_values?

**Comment by slundberg** [comment]
I replied to this and another one in #838, so check there for the reply.

**Comment by slundberg** [comment]
Could you also clarify how you would like to use multi-Progress?
