### ISSUE TITLE
module 'shap' has no attribute 'TreeExplainer'

### ISSUE THREAD

**Issue by chandrad** [shap/shap#84]
When I tried to use tree based models from scikit-learn like trees, xgboost, random forest etc., I am getting the error.

**Comment by slundberg** [comment]
hmm...what version of shap do you have?

**Comment by chandrad** [comment]
v0.10.0. I used pip install shap in RHEL.

**Comment by chandrad** [comment]
KernelExplainer is working though!

**Comment by slundberg** [comment]
Interesting. If you post a self contained example it might help figure out
what's up.

**Comment by chandrad** [comment]
I think v0.10.0 of `shap` got fixed with new version. Is there a plan to put latest version of shap in PyPI. Currently, when I use `pip install shap` v0.10.0 package is deploying in the machine.

**Comment by slundberg** [comment]
Interesting. https://pypi.org/project/shap shows 0.15 right now. Are you using some mirror that doesn't get updated often?

**Comment by chandrad** [comment]
Yes, I am using mirror that has v0.10.0. I manually downloaded from github. I am closing the issue now. Thanks!
