### ISSUE TITLE
<IPython.core.display.HTML object>

### ISSUE THREAD

**Issue by mchirsa5** [shap/shap#846]
Hi,

I'm trying to run force_plot in IDLE. However, when I put the statement below (force_plot), I got <IPython.core.display.HTML object> in my python shell.

shap.force_plot(explainerXGB.expected_value, shap_values_XGB_test[j], X_test.iloc[[j]])

I'm trying to save it in html by using the code below.

html = shap.force_plot(explainerXGB.expected_value, shap_values_XGB_test[0], X_test.iloc[[0]]).data
with open('html_file.html', 'w') as f:
    f.write(html)

However, when I opened the file, it showed "Visualization omitted, Javascript library not loaded!". (Even though I already put "shap.initjs()")

**Comment by slundberg** [comment]
There is a nice function for just that :) `shap.save_html`
