### ISSUE TITLE
  shap.summary_plot + plt.savefig + PDF format = blue boxes artifacts in plot

### ISSUE THREAD

**Issue by juanramonua** [shap/shap#847]
To begin, thank you for this great tool.

versions: shap 0.31.0; matplotlib 3.0.3; Notebook (G. Colab)

when I try to save the plot in PDF format using:
```
shap.summary_plot(shap_values, X_test, feature_names=feature_names, show=False)
plt.savefig('importance_scatter_xgb.pdf', format='pdf', dpi=1200, bbox_inches='tight')
```
some strange blue rectangles appear above the data points.

I would appreciate any information to remove them.   

![shap_blue_boxes](https://user-images.githubusercontent.com/14908342/66704078-39ba8080-ed19-11e9-8a9e-100c9ea75a1e.jpg)

Greetings.

**Comment by slundberg** [comment]
Strange. Are you sure you don't have some other bar plot getting built somewhere? Do you get the same issue when you do?:
```
shap.summary_plot(shap_values, X_test, feature_names=feature_names, show=False)
plt.show()
```
If not then it seems like a matplotlib issue.

**Comment by juanramonua** [comment]
Thank you for your answer.

In the same cell of the Notebook I created two graphs. Using plt.close() after each graph works correctly.

```
shap.summary_plot(shap_values, X_test, feature_names=feature_names, plot_type="bar", show=False)
plt.savefig('importance_bar_xgb.pdf', format='pdf', dpi=1200, bbox_inches='tight')
plt.close()`

shap.summary_plot(shap_values, X_test, feature_names=feature_names, show=False)
plt.savefig('importance_scatter_xgb.pdf', format='pdf', dpi=1200, bbox_inches='tight')
plt.close()
```

Thank you.
