### ISSUE TITLE
Testing shap: Pure noise rank higher than the only meaningful feature

### ISSUE THREAD

**Issue by gorkemozkaya** [shap/shap#848]
I would like to share a simple test that I ran for testing shap, which gives counterintuitive results.

I generated data with 3 features. Two of them are pure noise and has no connection to the target. The third feature is a binary feature with 10% 1s and 90% 0s. This is the only feature that the target has a dependency on. However, shap ranks it after the pure noise features.

[* Link to colab notebook](https://colab.research.google.com/drive/1QujW37ANUWjFo4R1v-ifKxwPpT0xrEhn)

I am curious to understand what might be going on here and if a similar issue would impact importance scores with real data.

**Comment by christophM** [comment]
The xgboost model might actually rely on the noise feature, in case of overfitting. If overfitting happened, it would not be surprising when those features are ranked highly. SHAP is for explaining how the model makes predictions, and a bad model will show results that deviate from the true data generating process.

You could try to optimize xgboost number of iterations and see if it the ranking changes.

**Comment by gorkemozkaya** [comment]
Thanks for looking into this. After properly regularizing the XGBoost model, the ranking changed in the expected direction.
