### ISSUE TITLE
Confusion in multiclass shap output

### ISSUE THREAD

**Issue by sathyapramod-r** [shap/shap#851]
Hi,
I'm using a Tree Explainer with shap for a Random forest binary classification problem as follows:
rf = RandomForestClassifier()
RF = shap.TreeExplainer(rf)
shap_values_RF_test = RF.shap_values(X_test)

Now, I'll get two outputs shap_values_RF_test[0] and shap_values_RF_test[1] (which can be further used in the plots). I have two output classes 0 and 1. Can I be sure that shap_values_RF_test[0] corresponds to class 0 and shap_values_RF_test[1] corresponds to class 1? 

Particularly when I'm plotting summary plot (code below) to look at the impact of the features, I get confused which class the plot corresponds to?    
shap.summary_plot(shap_values_RF_test[0], X_test,class_names=rf.classes_)

**Comment by slundberg** [comment]
The order of the explanations exactly matches the order of the outputs of the model. If you want to double check this, just run `explainer.expected_value + shap_values_RF_test[0].sum(1)` and make sure that equals the output of your model (the margin output of your model if you are doing logistic regression).
