### ISSUE TITLE
Passing dictionary as a model

### ISSUE THREAD

**Issue by calathea22** [shap/shap#852]
Hey there! I made my own code for generating a binary decision tree, which is stored as a dictionary. 
See below for an example of how my tree looks like:

{'var': 'Duration of Credit (month)', 'cut_off_value': 36, 'left': (4, 5), 'right': {'var': 'Account Balance', 'cut_off_value': 3, 'left': (19, 2), 'right': (1, 0)}}

To explain a bit more: 'Duration of Credit (month)' and 'Account Balance' are both variable names corresponding to the nodes. The cut_off_values indicate the splitting point for the variables. Thus for the rootnode all instances with 'Duration of Credit'<= 36 go to the left side of the tree and all others to the right side. The leafs are stored as a tuple, showing how much instances belong to class 0 and class 1 in the decision problem respectively.

I'd like to get the local feature importances of this decision tree. The shap package now allows to pass dictionaries as a model, but I'm not sure how the dictionaries are expected to be set up. Can someone help me with that? Any help is very much appreciated!

**Comment by slundberg** [comment]
Have you checked out this example notebook?: https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Example%20of%20loading%20a%20custom%20tree%20model%20into%20SHAP.ipynb

It shows how to create the dictionary, which is essentially a set of parallel arrays that define the tree.

**Comment by calathea22** [comment]
Thanks a lot, I missed that one!
