### ISSUE TITLE
Comparing two datasets with SHAP

### ISSUE THREAD

**Issue by pasttense-ofdig** [shap/shap#854]
I would like to use SHAP to explain changes between datasets and how that affected the average predicted value.  For example, I have one dataset, collected from January to June, that has a mean predicted probability of success (from XGBClassifier) of 0.05.  I have another dataset, collected just in the month of October, that has a mean probability of 0.1.  I would like to use SHAP to explain the differences between these datasets (I.e. - what are the major factors causing the second dataset to have higher mean values, like a 50% increase in feature 1, 30 decrease in feature 3, etc.).  Is this something that can be done with the existing package, and if so, how?

**Comment by slundberg** [comment]
I would start by just comparing the global feature importances for the model on each dataset: `np.abs(shap_values_dataset1).mean(0) - np.abs(shap_values_dataset0).mean(0)`. Then digging into the features that have driven the largest changes.
