### ISSUE TITLE
Model Monitoring Plot: Inconsistency between Paper and GitHub

### ISSUE THREAD

**Issue by bereRadeck** [shap/shap#856]
Hello,

in your paper 'Explainable AI for Trees: From Local Explanations to Global Understanding' you presented in section 2.7.4 and Method 17 the SHAP monitoring plot as a tool to decompose the loss among the features. In figure 5 you plot 'SHAP loss values' on the y axis where a positive value means the feature increased the loss and the a negative value means the feature helped to improve the model, if I got you right. But the current monitoring plot on GitHub only plots the regular SHAP values on the y axis, as far as I understood it. So with this plot you can see whether the effect of the feature on the output changes over time, which indicates a change on it's impact on the loss, too, but you cannot directly see it's effect on the loss as described in the paper. 

How do you compute 'SHAP loss values'  or how can I use the monitoring plot as proposed in this paper? Or is there a misunderstanding from my part? (I'm aware that the current version of this plot is preliminary)

**Comment by slundberg** [comment]
Hey! The monitoring plot will plot any explanations you like over time. In the paper we plot explanations of the loss of the model's output and not just the output. To do that:
```python
explainer = shap.TreeExplainer(model, background, feature_dependence="independent", model_output="logloss")
shap_values = explainer.shap_values(X)
shap.monitoring_plot(feature_index_you_want_to_plot, shap_values, X)
```

**Comment by bereRadeck** [comment]
Okay, cool. Thanks a lot!
