### ISSUE TITLE
base value in IRIS dataset is error

### ISSUE THREAD

**Issue by silentteller** [shap/shap#858]
I ran the sample program for the iris data set, but I got different results on my computer.
![11](https://user-images.githubusercontent.com/43327942/67140123-ec469200-f289-11e9-89a9-f48bbf92429e.jpg)
The correct one should be like this.
![22](https://user-images.githubusercontent.com/43327942/67140143-1a2bd680-f28a-11e9-8094-58668bb69b4c.jpg)
the code is same,where is wrong???

**Comment by slundberg** [comment]
Past the code you used perhaps? I get something that looks like the second one when I run the iris example in the readme.
