### ISSUE TITLE
Question about SHAP value intuition

### ISSUE THREAD

**Issue by albertmishaan** [shap/shap#86]
Just had a question on SHAP values from the perspective of human intuition. I recently ran a KNN method on a non-linear dataset (a "XOR" dataset that resembles a 2x2 chessboard). There are four types of points, and two classifications:

1. (x > 0, y > 0) Output = 0
2. (x < 0, y < 0) Output = 0
3. (x > 0, y < 0) Output = 1
4. (x < 0, y > 0) Output = 1

The decision boundary would be the axes of the graph (ie x = 0 and y = 0). Given this, I would expect an explanation of the classification of any point to be the values of the x- and y-values themselves. For instance for a point (-3.4, 2.1), the reason why it should be classified as a "1" is because the x-value is 3.4 units to the left of the line x = 0 and the y-value is 2.1 units above the line y = 0. However, the SHAP value assigns all the value of the explanation to the x-value (ie the SHAP value of the y-value is 0). Why might this be? How can an explanation assign no effect to the y-value - after all, if it were negative, then the Output would be "0"?

Although this question is a little academic, I would appreciate any insight you might have into this. Thanks!

**Comment by slundberg** [comment]
I assume you are using the Kernel explainer. What is the background reference you gave it?

**Comment by albertmishaan** [comment]
Yes, I am using the Kernel explainer. What do you mean by background reference? Here is the line where I use the Kernel explainer:

shap_values = shap.KernelExplainer(knn.predict_proba, X_train).shap_values(X_test)

**Comment by slundberg** [comment]
I was thinking you might be using just a single example instead of `X_train`. But it seems you are not. You mind posting the full example you are using and I'll look it over?

**Comment by albertmishaan** [comment]
[XOR_dataset.txt](https://github.com/slundberg/shap/files/2014111/XOR_dataset.txt)

Here is the full XOR dataset

**Comment by slundberg** [comment]
When I run a sklearn knn on that dataset I get about +0.25 for both A and B as SHAP values (with a 0.5 base value) for positive examples, and -0.25 for A and B for negative examples. This matches what I would expect, but it does not match what you mentioned about getting a 0 SHAP value for the second axis.

**Comment by albertmishaan** [comment]
Hmmmm... Can you send me the code you ran to get those results? Here is what I run:

#KNN
print("KNN")
knn = sklearn.neighbors.KNeighborsClassifier()
knn.fit(X_train, Y_train)
print_accuracy(knn.predict)

shap_values = shap.KernelExplainer(knn.predict_proba, X_train).shap_values(X_test)
np.savetxt("X_test_KNN.csv", X_test, delimiter=",")
np.savetxt("Y_test_KNN.csv", Y_test)
np.savetxt("Shap_values_KNN.csv",shap_values[0], delimiter=",")
shap.force_plot(shap_values[0], X_test)

And these are the results found in "Shap_values_KNN.csv" - as you can see, the first example has SHAP values for both A and B, and the second example has a SHAP value of 0 for B, though other examples, such as the 3rd and 5th, seem to be matching our intuition to some degree (ie they aren't both .25/-.25, but both are contributing). Please let me know what you think, or if I am making a mistake somewhere. Thanks!

0.00E+00 | 0.00E+00 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
-2.35E-01 | -2.49E-01 | 4.84E-01
5.16E-01 | 0.00E+00 | 4.84E-01
-2.52E-01 | -2.32E-01 | 4.84E-01
2.23E-01 | 2.92E-01 | 4.84E-01
2.47E-01 | 2.69E-01 | 4.84E-01
1.16E-01 | 0.00E+00 | 4.84E-01
5.16E-01 | 0.00E+00 | 4.84E-01
0.00E+00 | -4.84E-01 | 4.84E-01
5.16E-01 | 0.00E+00 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
2.78E-01 | 2.37E-01 | 4.84E-01
-2.42E-01 | -2.42E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
-2.76E-01 | -2.08E-01 | 4.84E-01
2.53E-01 | 2.63E-01 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
-6.06E-02 | -2.37E-02 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
-2.84E-01 | 0.00E+00 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
2.65E-01 | 2.50E-01 | 4.84E-01
2.49E-01 | 2.67E-01 | 4.84E-01
0.00E+00 | -4.84E-01 | 4.84E-01
2.81E-01 | 2.35E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
0.00E+00 | -2.84E-01 | 4.84E-01
-2.37E-01 | -2.47E-01 | 4.84E-01
-1.96E-01 | -2.88E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
5.16E-01 | 0.00E+00 | 4.84E-01
2.12E-01 | 1.03E-01 | 4.84E-01
2.58E-01 | 2.57E-01 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
2.69E-01 | 2.47E-01 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
5.16E-01 | 0.00E+00 | 4.84E-01
0.00E+00 | -8.44E-02 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
2.82E-01 | 2.34E-01 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
-2.34E-01 | -2.50E-01 | 4.84E-01
5.16E-01 | 0.00E+00 | 4.84E-01
0.00E+00 | -4.84E-01 | 4.84E-01
2.55E-01 | 2.60E-01 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
1.16E-01 | 0.00E+00 | 4.84E-01
2.28E-01 | 2.88E-01 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
2.49E-01 | 2.67E-01 | 4.84E-01
5.16E-01 | 0.00E+00 | 4.84E-01
-2.21E-01 | -2.63E-01 | 4.84E-01
3.01E-01 | 2.15E-01 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
3.16E-01 | 0.00E+00 | 4.84E-01
-2.42E-01 | -2.43E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
-2.42E-01 | -2.42E-01 | 4.84E-01
2.65E-01 | 2.51E-01 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
9.81E-02 | 1.75E-02 | 4.84E-01
0.00E+00 | 5.16E-01 | 4.84E-01
0.00E+00 | 0.00E+00 | 4.84E-01
-2.28E-01 | -2.57E-01 | 4.84E-01
-2.84E-01 | 0.00E+00 | 4.84E-01
-4.84E-01 | 0.00E+00 | 4.84E-01

**Comment by slundberg** [comment]
I ran the following:
```
import pandas
import shap
import sklearn
X = pandas.read_csv("/Users/slund1/Downloads/XOR_dataset.txt", '\t')
knn = sklearn.neighbors.KNeighborsClassifier()
knn.fit(X.iloc[:,:2], X["label"])
shap_values = shap.KernelExplainer(knn.predict, X.iloc[:,:2]).shap_values(X.iloc[:,:2])
```

**Comment by albertmishaan** [comment]
I tried running this exactly and I got the following error:

ValueError: could not broadcast input array from shape (2,1) into shape (2)

Also, would it matter that you do not split this into testing and training data?

Finally, here is the code I used if that helps...

```
xor = pd.read_csv('chessboard_update.csv',header = 0)
X = (xor.iloc[:,[0,1]])
y = (xor.iloc[:,[2]]).values.ravel()
X_train,X_test,Y_train,Y_test = train_test_split(X,y , test_size=0.2, random_state=0)
knn = sklearn.neighbors.KNeighborsClassifier()
knn.fit(X_train, Y_train)
shap_values = shap.KernelExplainer(knn.predict_proba, X_train).shap_values(X_test)
np.savetxt("X_test_KNN.csv", X_test, delimiter=",")
np.savetxt("Y_test_KNN.csv", Y_test)
np.savetxt("Shap_values_KNN.csv",shap_values[0], delimiter=",")
shap.force_plot(shap_values[0], X_test)

```

**Comment by slundberg** [comment]
That's odd you got an error with my example. What version of SHAP do you have?

**Comment by albertmishaan** [comment]
I'm not sure. How can I see that?

**Comment by slundberg** [comment]
`pip show shap` is how I would check (assuming you installed from pip).

**Comment by albertmishaan** [comment]
Looks like 0.12.0

**Comment by slundberg** [comment]
The current version is 0.17, that might be part of the issue. Could you run `pip install shap --upgrade` and see if that fixes the error with my example?

**Comment by albertmishaan** [comment]
Sorry about the tardy reply. I updated SHAP and I got the SHAP values below. They fit better with our intuition, so I think this clears up my question (I also got the SHAP values for SVM linear and as expected the SHAP values were 0 for both labels as a linear model classifying a XOR is essentially guessing and should therefore not assign any value to either label).

I see that the default value of 0.48 is offset by the sum of the SHAP values for each label, with most sums either bringing the value to either 0 or 1. However, I also noticed that for some examples the sums bring 0.48 to a value between 0.48 and 0/1. In those cases the classifications were mostly correct, but how should I think about that intuitively? That those points were harder to classify with "complete certainty" but were determined to probably belong to one classification? This fits well with the fact that the two points misclassified belonged to this class of points.


0.16 | 0.15 | 0.48
-0.25 | -0.23 | 0.48
-0.23 | -0.25 | 0.48
0.24 | 0.28 | 0.48
-0.25 | -0.23 | 0.48
0.22 | 0.29 | 0.48
0.25 | 0.27 | 0.48
0.08 | 0.03 | 0.48
0.24 | 0.28 | 0.48
-0.22 | -0.26 | 0.48
0.26 | 0.25 | 0.48
0.28 | 0.24 | 0.48
0.28 | 0.24 | 0.48
-0.24 | -0.24 | 0.48
0.27 | 0.25 | 0.48
0.28 | 0.24 | 0.48
-0.28 | -0.21 | 0.48
0.25 | 0.26 | 0.48
-0.23 | -0.25 | 0.48
-0.28 | -0.21 | 0.48
0.28 | 0.23 | 0.48
-0.06 | -0.02 | 0.48
0.26 | 0.25 | 0.48
-0.14 | -0.15 | 0.48
0.28 | 0.24 | 0.48
-0.23 | -0.26 | 0.48
0.27 | 0.25 | 0.48
0.25 | 0.27 | 0.48
-0.26 | -0.23 | 0.48
0.28 | 0.24 | 0.48
0.25 | 0.27 | 0.48
-0.15 | -0.14 | 0.48
-0.24 | -0.25 | 0.48
-0.20 | -0.29 | 0.48
0.26 | 0.25 | 0.48
0.28 | 0.23 | 0.48
0.21 | 0.10 | 0.48
0.26 | 0.26 | 0.48
0.26 | 0.26 | 0.48
-0.23 | -0.25 | 0.48
0.27 | 0.25 | 0.48
0.04 | 0.07 | 0.48
0.25 | 0.27 | 0.48
0.28 | 0.23 | 0.48
-0.05 | -0.03 | 0.48
0.24 | 0.28 | 0.48
-0.25 | -0.23 | 0.48
-0.25 | -0.24 | 0.48
0.28 | 0.23 | 0.48
-0.25 | -0.23 | 0.48
-0.23 | -0.25 | 0.48
0.26 | 0.26 | 0.48
-0.28 | -0.21 | 0.48
0.26 | 0.26 | 0.48
-0.26 | -0.23 | 0.48
-0.27 | -0.22 | 0.48
0.05 | 0.06 | 0.48
0.23 | 0.29 | 0.48
0.27 | 0.24 | 0.48
0.25 | 0.27 | 0.48
0.24 | 0.28 | 0.48
-0.22 | -0.26 | 0.48
0.30 | 0.21 | 0.48
-0.23 | -0.25 | 0.48
0.16 | 0.16 | 0.48
-0.24 | -0.24 | 0.48
0.24 | 0.28 | 0.48
0.28 | 0.24 | 0.48
0.23 | 0.28 | 0.48
-0.25 | -0.23 | 0.48
0.22 | 0.29 | 0.48
-0.24 | -0.24 | 0.48
0.27 | 0.25 | 0.48
0.26 | 0.26 | 0.48
0.10 | 0.02 | 0.48
0.27 | 0.24 | 0.48
-0.23 | -0.25 | 0.48
-0.23 | -0.26 | 0.48
-0.14 | -0.15 | 0.48
-0.24 | -0.25 | 0.48

**Comment by slundberg** [comment]
Interesting that some of the point did not sum to 0/1. Does the model also output a value that is not 0/1 for those examples?

**Comment by albertmishaan** [comment]
No - the model outputs only 0 or 1 consistent with the following:
(x > 0, y > 0) Output = 0
(x < 0, y < 0) Output = 0
(x > 0, y < 0) Output = 1
(x < 0, y > 0) Output = 1

**Comment by slundberg** [comment]
If the SHAP values don't sum to the output of the model then there is a problem somewhere. I don't see that in the example I ran above, could you share a self-contained example where you don't see the sum of the SHAP values matching the model output? Thanks!

**Comment by Whamp** [comment]
I'm getting a similar problem where the base output and predicted output are on an entirely incorrect scale. My use case is an LGBbinary classification task so the output should be between 0 and 1. However the shap values I get are a base value of -1.99 and, for example, a specific individual force plot example shows a model output of -2.04 which is also incorrect. The predictions from the model outside of Shap make sense and continue to work in production. 

I'm running shap version 0.24 on Windows 10 Anaconda python 3.6

**Comment by slundberg** [comment]
@Whamp That is probably because LightGBM trees output log-odds values not raw probabilities, so the SHAP values from TreeExplainer will be in log odds units. If you use `force_plot` with the option `link="logit"` then it will display the values as probabilities (in case that is helpful).
