### ISSUE TITLE
TreeExplainer inconsistent parameter naming: 'log_loss' vs 'logloss'

### ISSUE THREAD

**Issue by bereRadeck** [shap/shap#860]
Hello,
this is just a small issue: In the doc-string of the TreeExplainer class the parameter values for "model_output" are given as  "margin", "probability", or "log_loss", but in the code "logloss" is used. Using the naming as proposed in the doc-string will give you e.g. an UnboundLocalError in the get_transform function of the TreeExplainer class, because checks like
`elif model_output == "logloss"`  will be False

**Comment by slundberg** [comment]
Thanks! Fixed now, and we also not have better errors for when the model_output is not recognized.
