### ISSUE TITLE
XGBRegressors new default objective name unknown to TreeExplainer

### ISSUE THREAD

**Issue by bereRadeck** [shap/shap#861]
The XGBRegressors default objective 'reg:linear' is now deprecated in favor of 'reg:squarrederror', but using the new default objective name will give you the Exception 'Model does not have a known objective or output type!'  when 
`model = xgb.XGBRegressor(gbtree='gbtree', objective='reg:squarederror').fit(x,y)`
`explainer = shap.TreeExplainer(model, x, feature_dependence="independent", model_output="logloss")`
I think this is because the objective_name_map of the TreeEnsemble class needs to be updated, it contains 'reg:linear' but not 'reg:squarrederror'.

**Comment by slundberg** [comment]
Thanks for the heads up! I just pushed a fix
