### ISSUE TITLE
Shap values and ranking depend on Y scaling

### ISSUE THREAD

**Issue by hlbkin** [shap/shap#876]
Hello!

Im using xgboost regression with no regularization

And my output Abs(Shap) values heavily depend on whether I multiply initial target by 1000 or not (initial target is of order of 0.00001)

Is it expected? Why is that?

**Comment by hlbkin** [comment]
Checked: xgboost is sensitive to that, and CatBoost is not

**Comment by slundberg** [comment]
XGBoost uses float32 so I would be careful with fitting very small values
near the precision of float32
