### ISSUE TITLE
How do you get the "classic" feature importance plot out? 

### ISSUE THREAD

**Issue by resdntalien** [shap/shap#88]
Is there a call to create the "standard" feature importance plot ala sklearn? 

I basically want this: 

![1_fc0q-o56b1kw8rzmq0bqnq](https://user-images.githubusercontent.com/4607845/40157899-519a7cbc-5956-11e8-964f-2a50f8c69665.png)

I'm doing it manually now by sorting and doing the abs, mean, and hbar. If this is not already implemented I'm happy to put in a PR.

**Comment by slundberg** [comment]
So far I have also just manually made those plots. But I think it would make sense to add another option to the `summary_plot` function for `plot_type="bar"`. If you want to add it, that would be great. Should just be another if statement.

**Comment by resdntalien** [comment]
@slundberg Sounds good. I'll try to get a PR in next week.

**Comment by slundberg** [comment]
I ended up wanting this myself so I added it, with a stacked bar extension for multiple output classes.
