### ISSUE TITLE
module 'shap' has no attribute 'visualize', required to reproduce Figure 4 of the tree SHAP paper

### ISSUE THREAD

**Issue by relaxedplan** [shap/shap#888]
The SHAP-based supervised clustering algorithm's output is summarised in Figure 4 of the tree SHAP paper, with this corresponding notebook: https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/tree_shap_paper/Figure%204%20-%20Supervised%20Clustering%20Adult%20Census%20Data.ipynb

I want to get the same visualisation for my own notebook, but running the line,
shap.visualize(shap_values[:2000,:], X_display.iloc[:2000,:], link=shap.LogitLink())

gives "AttributeError: module 'shap' has no attribute 'visualize'".

I cannot find this function in the library, so it may be missing

**Comment by slundberg** [comment]
Good catch. That's an old notebook with outdated syntax. I just committed a new version to master.
