### ISSUE TITLE
PyPI release of 0.32.1 only contains Windows wheels

### ISSUE THREAD

**Issue by sndrtj** [shap/shap#889]
The PyPI release of 0.32.1 only contains Windows wheels. There are no Mac wheels, and no source tarball either. 

This effectively means 0.32.1 is uninstallable through PyPI on any platform other than Windows. 

Version 0.32.0 _does_ have Mac wheels, as well as a source tarball.

See: https://pypi.org/project/shap/0.32.1/#files
and:  https://pypi.org/project/shap/0.32.0/#files

**Comment by slundberg** [comment]
Thanks for pointing this out! I was working on getting travis to post the source and wheels automatically, it failed I forgot to then post the tarball directly. Fixed now.

**Comment by sndrtj** [comment]
Thanks for the quick fix!
