### ISSUE TITLE
model missing predict_proba 

### ISSUE THREAD

**Issue by rafikg** [shap/shap#895]
Hey @slundberg 

Does it make sense that we can interpret a model without `predict_proba()` function using `KernelSHap`. 

Let's take the example of `kmeans cluster on scikitlearn`. By running it, I expect that I have to get an error  but everything was running well! I debug the code and I remark that you're using the `class Id (the ouput of kmens.predict)` which does not make sense (unless I missed something). Could you clarify!

**Comment by InterferencePattern** [comment]
I think your question (if I understand it correctly) relates to predictions on unsupervised models, which has a good answer here: #1052
