### ISSUE TITLE
Support for sklearn's CalibratedClassifierCV?

### ISSUE THREAD

**Issue by zoj613** [shap/shap#899]
Is there a way `CalibratedClassifierCV` can be supported if it is used to wrap any of the supported models by shap? I get an error anytime I try to use it. It would be great if someone knows a workaround to this:
```python
import shap
from sklearn.calibration import CalibratedClassifierCV
from sklearn.datasets import make_classification
from  sklearn.ensemble.gradient_boosting import GradientBoostingClassifier
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=500)
x_train, x_test, y_train, y_test = train_test_split(
    X, y, train_size=0.7
)
supported_clf = GradientBoostingClassifier()
calib_model = CalibratedClassifierCV(base_estimator=supported_clf, cv=5)
calib_model.fit(x_train, y_train)

explainer = shap.TreeExplainer(calib_model)
values = explainer.shap_values(x_test)
out = shap.force_plot(
    explainer.expected_value,
    values[1],
    x_test[[1]]
)
```

I get this error:
`Exception: Model type not yet supported by TreeExplainer: <class 'sklearn.calibration.CalibratedClassifierCV'>`

If I change the line `explainer = shap.TreeExplainer(calib_model)` to `explainer = shap.TreeExplainer(calib_model.base_estimator)`, shap will detect the supported classfier but then it will not be fit so I get a new error: `AttributeError: 'GradientBoostingClassifier' object has no attribute 'estimators_'` (since base_estimator has not been explicitly fitted.)

Even if option B worked, it still would defeat the purpose of of using the `CalibratedClassifierCV` class.

**Comment by zoj613** [comment]
Another approach I considered is using 
```python
explainer = shap.TreeExplainer(calib_model.calibrated_classifiers_[i].base_estimator)
```
 where `i` is an integer from 0 to `cv -1`, and `cv -1` is the number of cross-validation folds. This produces no error but all it does is use a fitted estimator from only one of the folds, which also makes the used of CalibratedClassifierCV meaningless.

**Comment by skocbek** [comment]
Hi zoj613, have you found any solution to this problem?

**Comment by zoj613** [comment]
> Hi zoj613, have you found any solution to this problem?

No, I haven't. I opted for the KernelExplainer since it supports any classifier then used kmeans to summarize the large input data I had as a way to reduce the run time.

**Comment by skocbek** [comment]
Thank you for your reply. Currently, I have the very same problem and haven't managed to make things work with Kernel Explainer.  Below is relevant code:

`model` = GradientBoostingClassifier()
calibrated = CalibratedClassifierCV(model, method='sigmoid', cv=10)
calibrated.fit(trainX, trainy)
explainer = shap.KernelExplainer(calibrated.predict_proba, trainX)
shap_values2 = explainer.shap_values(testX)`

With the last line I get the following error:
> TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'

Do you know what I am doing wrong? 
Also, is your code where you use KernelExplainer somewhere on GitHbub maybe?

**Comment by zoj613** [comment]
> Thank you for your reply. Currently, I have the very same problem and haven't managed to make things work with Kernel Explainer. Below is relevant code:
> 
> `model` = GradientBoostingClassifier()
> calibrated = CalibratedClassifierCV(model, method='sigmoid', cv=10)
> calibrated.fit(trainX, trainy)
> explainer = shap.KernelExplainer(calibrated.predict_proba, trainX)
> shap_values2 = explainer.shap_values(testX)`
> 
> With the last line I get the following error:
> 
> > TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'
> 
> Do you know what I am doing wrong?
> Also, is your code where you use KernelExplainer somewhere on GitHbub maybe?

Looks like the test/train data might be the problem. Thats how I did it too. Maybe double check if all your data has numerical values and no nans or strings? I think the kernelexplainer might expect all finite values and no missing data points

**Comment by cejwlim11** [comment]
I'm curious that this problem is solved!
Because I am struggle with same issue.

**Comment by squangelo** [comment]
See this related issue, the simplest (and recommended) way seems to be iterating over the calibrated classifiers and then taking the mean over the resulting shap values
 https://github.com/slundberg/shap/issues/337

```python
shap_values_list = []
for calibrated_classifier in calib_model.calibrated_classifiers_:
    explainer = shap.TreeExplainer(calibrated_classifier.base_estimator)
    shap_values = explainer.shap_values(x_test)
    shap_values_list.append(shap_values)

shap_values = np.array(shap_values_list).sum(axis=0) / len(shap_values_list)
```

**Comment by Abhishaike** [comment]
Bumping this, is there any way to use TreeExplainer with CalibratedClassifierCV? 

More specifically, is it possible to train a set of calibrators (say, 3), then retrieve the SHAP values from each of the base estimators, and then use those SHAP values as input to the calibrators? 

ex: 

```
for calibrated_classifier in calib_model.calibrated_classifiers_:
    all_explainers.append(shap.TreeExplainer(calibrated_classifier.base_estimator,
                                             data = train_df_kmeans.data,
                                             model_output='probability'))

all_calibrated_shap_vals = []

    # go through each explainer (3 in total)
for explainer, calibrated_classifier in zip(all_explainers, calib_model.calibrated_classifiers_):
    shap_vals = explainer.shap_values(train_df) # get the uncalibrated shap values from the explainer
    # go through each calibrator in the calibration object and use it to map the shap value to a 'calibrated'
    # version of it. This is always length 1, so just grab the first one
    all_calibrated_shap_vals.append([calibrated_classifier.calibrators[0].predict(i) for i in shap_vals])

calibrated_shap_values = np.array(all_calibrated_shap_vals).sum(axis=0) / len(all_calibrated_shap_vals)

```

**Comment by rdverse** [comment]
@Abhishaike Sometimes the classifiers properties change when calibrated. If you are explaining calibrated_classifier.base_estimator as mentioned in previous comments, you are esentially not getting the influence of the calibrated classifier but only the original classifier. 

One potential issue could be that treeexplainer is specifically trained for tree based algorithms such as random forest, xgboost. TreeExplainer takes advantage of their tree structure to reduce the complexity in shap value calculation and giving a boost in performance.

One quick fix to this issue was using the following:
1) If you use prefit=True in CalibratedClassifierCV then use shap.Explainer(calibratedClassifier.predict) instead of shap.TreeExplainer(calibrated_classifier) 
2) If you have set cv as an integer then probably take @squangelo 's approach with a slight change

for calibrated_classifier in calib_model.calibrated_classifiers_:
    explainer = shap.Explainer(calibrated_classifier.predict)
    shap_values = explainer(x_test).values
    shap_values_list.append(shap_values)

#shap_values = np.array(shap_values_list).sum(axis=0) / len(shap_values_list)

This might be slower than treeExplainer, but I have noticed it better explains the calibrated classifier.

**Comment by e-pet** [comment]
@rdverse Maybe I'm doing something stupid, but with both of your approaches, I get errors. :-(

With your option 1 (`prefit=True`), I can successfully create the Explainer, but it is then of type `shap.explainers._permutation.Permutation`  - as opposed to `shap.explainers._tree.Tree` - and when I try to call it (`explainer(X_test)`), I get a NoneType error.

With your option 2, I get an `AttributeError: '_CalibratedClassifier' object has no attribute 'predict'`. (And indeed, it doesn't...?)

My base classifier is an XGBoost model, and calling `shap.Explainer(calibratedClassifer.base_estimator)` works, but doesn't do what I want, of course.

**Comment by Ediebah** [comment]
Interesting! Before I found this I tried something similar but my kernel keeps dying. I see a few suggestions @zoj613 above I can try. Great issue!!

**Comment by y-melamed** [comment]
@e-pet, you need to change "predict" to predict_proba" in @rdverse answer and that it should work:
explainer = shap.Explainer(calibrated_classifier.predict_proba)

**Comment by Ediebah** [comment]
@zoj613 is there a way or solution to apply a similar approach for a survival model with "objective": "survival:cox"? I tried your approach using the NHANES I Survival Model example by @slundberg, I get the error "AttributeError: 'Booster' object has no attribute 'fit'".  I was even wondering if it makes sense to calibrate a survival model using isotonic or logistic regression. 
Any idea on how to calibrate such a model before calculating Shapley values? I want the output to be survival probabilities. Thank you!

**Comment by martinklamrowski** [comment]
I'm not sure it makes sense to explain the calibrated model using the uncalibrated model. Alternatively, you can explicitly use PermutationExplainer (model agnostic):
```
CAL_MODEL = derive_model(normed_train, normed_cal)

# build the explainer
CAL_MODEL_EXP = shap.PermutationExplainer(CAL_MODEL.predict_proba, pd.concat([normed_cal, normed_train]))

# explanations on some test data
CAL_MODEL_EXP(normed_test).values
```
