### ISSUE TITLE
Integration with React

### ISSUE THREAD

**Issue by JuanCorp** [shap/shap#9]
I was reading the comments on other issues, and noticed that the visualizations are made with D3.js and React. I was wondering if there's a way to render them directly in a React front-end. 

For example, a request is made from a React front-end for the explanation of a prediction. This calls a REST-API on the server, which returns the SHAP values, model feature names, and the data used to create the prediction (basically the shap.visualize() parameters). Finally, on React, the same visualization created on the notebooks is displayed on the app.  

One alternative to this is creating an image from the visualization, in the case of single explanations, like the one mentioned on #3 . But a native result would be preferable. ¿Is there currently a way to do this?

Thanks in advance!

**Comment by slundberg** [comment]
You can. If you look at the source of a Jupyter notebook with a visualization you will see that it prints out html with react (`initjs()` dumps the library code. The python from the iml library (which I made separate in case other's wanted to use it) as this code in it: 
```python
        return HTML("""
<div id='{id}'>{err_msg}</div>
 <script>
   if (window.IML) IML.ReactDom.render(
    IML.React.createElement(IML.AdditiveForceVisualizer, {data}),
    document.getElementById('{id}')
  );
</script>""".format(err_msg=err_msg, data=json.dumps(self.data), id=id_generator()))
```
https://github.com/interpretable-ml/iml/blob/master/iml/visualizers.py

So I am sure you could co-opt that into any react interface you want.

**Comment by JuanCorp** [comment]
Hey, thanks, I did just that a few days ago. Took a look at the source code for the ForceVisualizer JSX, and used it as a component for the application. Then I passed the parameters from the server using the Visualizer Python class, and passed those parameters as props to the ForceVisualizer. Worked like a charm!

Thanks!

**Comment by slundberg** [comment]
Great, glad it worked as expected!

**Comment by efraintorlo** [comment]
Hi guys,

I have exactly this same need to include an Explainer during a classification real-time system. It would be awesome if you could elaborate into the @JuanCorp 's solution. Is it posible to include the Explainer's visualisation into a non-react app (maybe a Angular front-end app) ?

@slundberg Thanks for your SHAP implementation and also the discussion you included in the paper!

**Comment by slundberg** [comment]
The meat of the visualization code is in D3, so you could rewrap it as an
angular component of you wanted, but it would take a bit of effort (how
much depends on your familiarity with D3 and React)

**Comment by rooom13** [comment]
> Hey, thanks, I did just that a few days ago. Took a look at the source code for the ForceVisualizer JSX, and used it as a component for the application. Then I passed the parameters from the server using the Visualizer Python class, and passed those parameters as props to the ForceVisualizer. Worked like a charm!
> 
> Thanks!

Great that you managed to do that. Could you share how did you do it? I'm trying to use it as a React component but having troubles.

Maybe an example of how does your `<AdditiveForceVisualizer ... >` does look like would help

**Comment by peterpoliwoda** [comment]
As above! Please write a documentation piece on how to integrate it with a react front-end! We're going to get it going soon so it would be great if there was something to lean on for help in integrating.

**Comment by pankaj1491** [comment]
@JuanCorp  Can you please provide source code where you used parameters from shap.visualise and passed to forceVisualizer JSX in react ?

**Comment by JuanCorp** [comment]
Hello! What I did back in the day is look at the iml and shap source code and prepare the data just like the iml library expected. I think the interface has changed since then, so this approach may be wrong. 

```python

def _explicar_instancia(shap_values, feature_names=None,
                        data=None, out_names=["peso recomendacion"]):
 
    if type(data) == np.ndarray:
        data = data.flatten()

    nans = np.argwhere(np.isnan(shap_values))
    indexes = nans[:, 1]
    shap_values = shap_values[:, ~np.isnan(shap_values).all(0)]
    shap_values = shap_values[~np.isnan(shap_values).all(1)]
    feature_names = [f for i, f in enumerate(
        feature_names) if i not in indexes]
    data = np.array([d for i, d in enumerate(data) if i not in indexes])
    instance = iml.Instance(np.zeros((1, len(feature_names))), data)
    exp = iml.AdditiveExplanation(
        shap_values[0, -1],
        np.sum(shap_values[0, :]),
        shap_values[0, :-1],
        None,
        instance,
        iml.IdentityLink(),
        iml.Model(None, out_names),
        iml.DenseData(np.zeros((1, len(feature_names))), feature_names)
    )
    visualizer = iml.AdditiveForceVisualizer(exp)
    visualizer.data["labelMargin"] = 20

    return visualizer.data
```

Since I don't think iml exists anymore, you'll have to take a look at how SHAP generates these visualizations today.

**Comment by pankaj1491** [comment]
And how did you consume this in React Project actually ? Can you give some guidance as per current Technology context , how do we go best about it. Basically there will be diff SHAP charts for every time user predicts , through API we can send those SHAP Visualization params to UI and but how does react consume it Actually. I tried to look at React D3 component but it dint seem to have native support for SHAP Charts.
@JuanCorp
