### ISSUE TITLE
TreeExplainer does not work for CatBoost

### ISSUE THREAD

**Issue by RobKuebler** [shap/shap#900]
Hi!

I trained a Ctaboost model and wanted to do

explainer = shap.TreeExplainer(c), which gives an error.

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-189-d8a756e7396d> in <module>
----> 1 explainer = shap.TreeExplainer(c, model_output='probability')
      2 #shap_values = explainer.shap_values(X_train)

/opt/conda/lib/python3.6/site-packages/shap/explainers/tree.py in __init__(self, model, data, model_output, feature_dependence)
     85         self.feature_dependence = feature_dependence
     86         self.expected_value = None
---> 87         self.model = TreeEnsemble(model, self.data, self.data_missing)
     88 
     89         assert feature_dependence in feature_dependence_codes, "Invalid feature_dependence option!"

/opt/conda/lib/python3.6/site-packages/shap/explainers/tree.py in __init__(self, model, data, data_missing)
    643             self.input_dtype = np.float32
    644             cb_loader = CatBoostTreeModelLoader(model)
--> 645             self.trees = cb_loader.get_trees(data=data, data_missing=data_missing)
    646             self.tree_output = "log_odds"
    647             self.objective = "binary_crossentropy"

/opt/conda/lib/python3.6/site-packages/shap/explainers/tree.py in get_trees(self, data, data_missing)
   1230 
   1231             # load the per-tree params
-> 1232             depth = len(self.loaded_cb_model['oblivious_trees'][tree_index]['splits'])
   1233 
   1234             # load the nodes

IndexError: list index out of range`

Shap version '0.31.0'
Catboost version '0.18'

**Comment by sky1122** [comment]
I got same problem. If you fix the problem please update! thanks a lot

**Comment by slundberg** [comment]
The following works for me:
```
import catboost
import shap
X,y = shap.datasets.boston()
model = catboost.CatBoostRegressor()
model.fit(X, y)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
```
Can you share a self contained example that does not work? Thanks!

**Comment by SNabii** [comment]
I am also facing same issue , i am clueless about the error.  
**IndexError: list index out of range`**

**Comment by RobKuebler** [comment]
Works perfectly for me now! Sorry for the late reply.

Thank you very much!
