### ISSUE TITLE
Error using shap.DeepExplainer

### ISSUE THREAD

**Issue by ahmedabbas81** [shap/shap#901]
Dear all,

I am trying to use deepShap,

background = np.zeros((1,X_train.shape[1]))
e = shap.DeepExplainer(model, background)

However, it gives me the following long error message

Any suggestion please?
TypeError                                 Traceback (most recent call last)
<ipython-input-149-19c985f3f8b7> in <module>
      1 background = np.zeros((1,X_train.shape[1]))
----> 2 e = shap.DeepExplainer(model, background)
      3 #background.shape[0]

~/miniconda3/envs/ahmed/lib/python3.7/site-packages/shap/explainers/deep/__init__.py in __init__(self, model, data, session, learning_phase_flags)
     78 
     79         if framework == 'tensorflow':
---> 80             self.explainer = TFDeepExplainer(model, data, session, learning_phase_flags)
     81         elif framework == 'pytorch':
     82             self.explainer = PyTorchDeepExplainer(model, data)

~/miniconda3/envs/ahmed/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py in __init__(self, model, data, session, learning_phase_flags)
    147             if self.data[0].shape[0] > 5000:
    148                 warnings.warn("You have provided over 5k background samples! For better performance consider using smaller random sample.")
--> 149             self.expected_value = self.run(self.model_output, self.model_inputs, self.data).mean(0)
    150 
    151         # find all the operations in the graph between our inputs and outputs

~/miniconda3/envs/ahmed/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py in run(self, out, model_inputs, X)
    287         """ Runs the model while also setting the learning phase flags to False.
    288         """
--> 289         feed_dict = dict(zip(model_inputs, X))
    290         for t in self.learning_phase_flags:
    291             feed_dict[t] = False

~/miniconda3/envs/ahmed/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py in __hash__(self)
    711     if (Tensor._USE_EQUALITY and executing_eagerly_outside_functions() and
    712         (g is None or g._building_function)):  # pylint: disable=protected-access
--> 713       raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
    714                       "Instead, use tensor.experimental_ref() as the key.")
    715     else:

TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by druzkaya** [comment]
same error. did you finally make it? thanks!

**Comment by ahmedabbas81** [comment]
It is now running with me. I think you may use older version of tensorflow.

**Comment by druzkaya** [comment]
ok, what are your versions of Tensorflow and SHAP? TF2.1 and SHAP 0.34 for me

**Comment by ahmedabbas81** [comment]
I am using TF 1.14 I think

**Comment by hs271095** [comment]
Is there a solution for the following error
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.
