### ISSUE TITLE
No output from shap.force_plot()?

### ISSUE THREAD

**Issue by RohinMahesh** [shap/shap#904]
I am trying to give the local explanation of a particular row on my testing dataset.

Got an error for V20, and it is requiring that I rewrite the function like this:
`shap.summary_plot(explainer.expected_value[0], shap_values[0])` 
 
My working code up to that point is:

`import shap` 
`explainer = shap.TreeExplainer(rfc)`
 `shap_values = explainer.shap_values(X_test)`

 `shap.force_plot(explainer.expected_value[1], shap_values[1])` 

The output of the second row (1) comes up with nothing.

**Comment by slundberg** [comment]
force_plot needs the JS code dumped into the notebook to run. Have you run `shap.initjs()` in the notebook somewhere?

**Comment by RohinMahesh** [comment]
Hello,

Thanks for the answer. Yes, the cell has shap.initjs() in the very first line.

Sincerely,



Rohin Mahesh

**Comment by RohinMahesh** [comment]
Hello slundberg,

I am unable to replicate your plot showing the local explainability (the very first visualization in your GitHub repository. I am getting the same error. Can you kindly help me with this?
