### ISSUE TITLE
Attribute error when I run the code of "Example of loading a custom tree model into SHAP" notebook

### ISSUE THREAD

**Issue by LeiTong02** [shap/shap#906]
Hi, I am trying to run the code of "Example of loading a custom tree model into SHAP" notebook, but get the following error from Sklearn GBM classifier which don't have the attribute of prior.
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/26090828/69196787-612a1780-0b27-11ea-9e6b-98b7b1396efe.png">
Any suggestions for this issue?

Environment: 
shap                 0.32.0 
scikit-learn         0.22.dev0
python              3.6.8

**Comment by slundberg** [comment]
Thanks! Must have been a version API change of some sort. Fixed now.
