### ISSUE TITLE
Shap and GBM

### ISSUE THREAD

**Issue by j-ghatak** [shap/shap#909]
Hello All, 

I know shap has implementation for XGBoost and LightGBM. But can shap be used for plain vanilla GBM as well?

**Comment by slundberg** [comment]
SHAP TreeExplainer also supports sklearn, and many other GBM implementations. To load your own custom GBM in you can follow: https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Example%20of%20loading%20a%20custom%20tree%20model%20into%20SHAP.ipynb

If you find a common GBM implementation that is not supported PR's are always welcome in: https://github.com/slundberg/shap/blob/fa3ec1be41b1d6ee308a29ab2b4d616a7f0e764c/shap/explainers/tree.py#L469-L735

**Comment by j-ghatak** [comment]
Thank you Scott!
