### ISSUE TITLE
SHAP DeepExplainer shap_values

### ISSUE THREAD

**Issue by agggaurav** [shap/shap#910]
I am currently using tensorflow == 1.13.1, python==3.5 , SHAP == 0.32.1 .
Getting the error - **typeerror: fetch argument none has invalid type <class 'nonetype'>**
while executing shap.DeepExplainer(model,data) function.

Could you please look  into it?

**Comment by farh33n** [comment]
I have used DeepExplainer() for LSTM and it works fine. Have you checked the type of both arguments?
