### ISSUE TITLE
dependence.py:  Redundant sort

### ISSUE THREAD

**Issue by koyurion** [shap/shap#913]
In the **dependence.py**, the process of **jitter** exists a operation of redundant sort，as showed in the follow image. As  np.unique() returns the sorted unique elements of an array. So the operation that **np.sort(xvals)** seems redundant.
![image](https://user-images.githubusercontent.com/32454333/69709534-8971d180-1138-11ea-8134-34f4a10b4faf.png)

**Comment by slundberg** [comment]
Thanks! I didn't realize that np.unique returned a sorted list. It is fixed now.
