### ISSUE TITLE
Error saving the summary plot output image

### ISSUE THREAD

**Issue by pablo-var** [shap/shap#914]
There is a problem in order to persist the summary plot returned by the method `summary_plot`. The error is related to matplotlib. I have copied an example of shapely values and features in order to replicate the error easily. 

```
import shap
import matplotlib.pyplot as plt
import numpy as np

shap_values = np.array([[-3.52528531e-02, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
         6.66592448e-02,  9.40882144e-03, -0.00000000e+00,
        -4.65822581e-02, -0.00000000e+00, -0.00000000e+00,
        -1.96588383e-02, -0.00000000e+00, -1.50642840e-01,
        -0.00000000e+00,  1.53519656e-03, -8.21487123e-02,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
         0.00000000e+00, -2.04150877e-01,  0.00000000e+00,
         0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -2.65342382e-03, -2.65342382e-03,
        -2.65342382e-03, -2.65342382e-03, -2.65342382e-03,
        -2.65342382e-03,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  5.62796974e-03,
        -6.45685756e-18, -0.00000000e+00,  0.00000000e+00,
        -0.00000000e+00,  8.83651397e-02,  2.50063405e-03,
         1.73311816e-02],
       [ 3.73826088e-02, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
         7.33286502e-01,  9.40882144e-03, -0.00000000e+00,
        -4.65822581e-02, -0.00000000e+00, -0.00000000e+00,
        -1.96588383e-02, -0.00000000e+00,  5.93518908e-01,
        -0.00000000e+00,  7.87303030e-03, -8.21487123e-02,
        -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00,  1.55095951e+00,  0.00000000e+00,
         0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00,  6.68144088e-02,  6.68144088e-02,
         6.68144088e-02,  6.68144088e-02,  6.68144088e-02,
         6.68144088e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  5.62796974e-03,
        -6.45685756e-18, -0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -1.57588031e-01,  2.50063405e-03,
         1.73311816e-02],
       [ 1.92999131e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
         6.66592448e-02,  9.40882144e-03, -0.00000000e+00,
        -4.65822581e-02, -0.00000000e+00, -0.00000000e+00,
        -1.96588383e-02, -0.00000000e+00,  7.08532346e-02,
         0.00000000e+00,  1.53519656e-03, -8.21487123e-02,
         0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        -0.00000000e+00,  4.96986783e-02, -0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        -0.00000000e+00, -2.65342382e-03, -2.65342382e-03,
        -2.65342382e-03, -2.65342382e-03, -2.65342382e-03,
        -2.65342382e-03,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  5.62796974e-03,
        -6.45685756e-18, -0.00000000e+00,  0.00000000e+00,
        -0.00000000e+00,  8.83651397e-02,  2.50063405e-03,
         1.73311816e-02]])

X = np.array([[-2.92870087e-01, -1.76292702e-01, -6.65522870e-01,
        -6.97774658e-01, -5.81717698e-01, -5.58035614e-01,
        -4.56307053e-01, -7.36903089e-01, -6.44679190e-01,
         1.77826542e+00, -4.07209039e-01, -4.60330652e-02,
        -8.39745115e-02, -6.72488689e-02, -3.94426780e-02,
        -3.68810705e-01, -1.46637323e-01,  4.31717123e-03,
        -1.84050056e+00,  1.41583947e+00, -4.49539186e-01,
        -1.98762259e+00, -1.47396792e+00, -7.95766336e-01,
        -9.63958373e-02, -9.64157091e-02, -1.01738576e+00,
        -6.04674503e-01,  8.42989080e-01,  1.47832551e+00,
        -3.48381637e-01, -3.58933956e-02, -4.41531609e-02,
        -4.41531609e-02, -1.10734561e-01, -1.10734561e-01,
        -1.10734561e-01, -1.10734561e-01, -1.10734561e-01,
        -1.10734561e-01,  4.20975455e-01,  4.20975455e-01,
         4.20923799e-01,  4.20975455e-01,  4.20975455e-01,
         4.20975455e-01,  4.20975455e-01,  4.10592119e-01,
        -1.94367856e-01, -3.16418766e-01,  3.16418766e-01,
        -1.40712008e+00,  1.54499549e+00, -2.04990070e-01,
        -3.97665281e-01],
       [-1.04787538e+00, -2.26236956e-01, -4.77792824e-01,
        -4.80746445e-01, -4.94588512e-01, -4.11090895e-01,
        -3.11594730e-01, -6.27708379e-01,  5.29899223e-01,
         7.99785594e+00, -4.07209039e-01, -4.60330652e-02,
        -8.39745115e-02, -6.72488689e-02, -3.94426780e-02,
        -3.68810705e-01, -1.49122457e-01, -5.51716576e+00,
        -8.34304886e-01,  3.56390172e+00, -4.49539186e-01,
        -6.69236410e-01, -2.57338421e-01, -9.10216041e-02,
        -2.32691673e-01, -6.88540205e-02, -1.05389468e-01,
        -8.09387927e-01,  7.40732759e+00,  2.42780115e+00,
        -6.33310711e-01, -3.58933956e-02, -4.41531609e-02,
        -4.41531609e-02,  9.03060427e+00,  9.03060427e+00,
         9.03060427e+00,  9.03060427e+00,  9.03060427e+00,
         9.03060427e+00,  4.20975455e-01,  4.20975455e-01,
         4.20923799e-01,  4.20975455e-01,  4.20975455e-01,
         4.20975455e-01,  4.20975455e-01,  4.10592119e-01,
        -1.94367856e-01, -3.16418766e-01,  3.16418766e-01,
         7.10671404e-01, -6.47251082e-01, -2.04990070e-01,
        -3.97665281e-01],
       [-8.59915799e-01,  1.37354369e-02,  2.91787253e+00,
         2.78630081e+00,  3.08392983e+00,  3.34866017e+00,
         3.33324658e+00, -4.46825420e-01,  2.70689398e-01,
         1.77826542e+00, -4.07209039e-01, -4.60330652e-02,
        -8.39745115e-02, -6.72488689e-02, -3.94426780e-02,
        -3.68810705e-01, -1.46637323e-01, -1.63912499e+00,
        -3.27984778e-01,  1.41583947e+00, -4.49539186e-01,
        -5.61927435e-02, -2.72397074e-01, -9.47364582e-01,
        -9.63958373e-02,  1.00110317e-01,  1.29277186e+00,
        -1.22694204e+00,  1.79241906e+00,  6.26030838e-01,
        -6.93455893e-01, -3.58933956e-02, -4.41531609e-02,
        -4.41531609e-02, -1.10734561e-01, -1.10734561e-01,
        -1.10734561e-01, -1.10734561e-01, -1.10734561e-01,
        -1.10734561e-01,  4.20975455e-01,  4.20975455e-01,
         4.20923799e-01,  4.20975455e-01,  4.20975455e-01,
         4.20975455e-01,  4.20975455e-01,  4.10592119e-01,
        -1.94367856e-01, -3.16418766e-01,  3.16418766e-01,
        -1.40712008e+00,  1.54499549e+00, -2.04990070e-01,
        -3.97665281e-01]])

# Error
shap.summary_plot(shap_values, X, show=False)
plt.savefig('global_summary.jpg')
```

Thank you in advance.

**Comment by slundberg** [comment]
Thanks! This was due to a numerical precision issue where `np.nanpercentile(values, 5) > np.nanpercentile(values, 95)` was true (crazily enough). I fixed this on master now with a simple followup check.

**Comment by jinxzed** [comment]
Hi, I am having the same error as mentioned. Please help!!!

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

/opt/conda/lib/python3.7/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

/opt/conda/lib/python3.7/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

/opt/conda/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2077                             print_method, dpi=dpi, orientation=orientation),
   2078                         draw_disabled=True)
-> 2079                     self.figure.draw(renderer)
   2080                     bbox_artists = kwargs.pop("bbox_extra_artists", None)
   2081                     bbox_inches = self.figure.get_tightbbox(renderer,

/opt/conda/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

/opt/conda/lib/python3.7/site-packages/matplotlib/figure.py in draw(self, renderer)
   1734             self.patch.draw(renderer)
   1735             mimage._draw_list_compositing_images(
-> 1736                 renderer, self, artists, self.suppressComposite)
   1737 
   1738             renderer.close_group('figure')

/opt/conda/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    135     if not_composite or not has_images:
    136         for a in artists:
--> 137             a.draw(renderer)
    138     else:
    139         # Composite any adjacent images together

/opt/conda/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

/opt/conda/lib/python3.7/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2628             renderer.stop_rasterizing()
   2629 
-> 2630         mimage._draw_list_compositing_images(renderer, self, artists)
   2631 
   2632         renderer.close_group('axes')

/opt/conda/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    135     if not_composite or not has_images:
    136         for a in artists:
--> 137             a.draw(renderer)
    138     else:
    139         # Composite any adjacent images together

/opt/conda/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

/opt/conda/lib/python3.7/site-packages/matplotlib/collections.py in draw(self, renderer)
    893     def draw(self, renderer):
    894         self.set_sizes(self._sizes, self.figure.dpi)
--> 895         Collection.draw(self, renderer)
    896 
    897 

/opt/conda/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

/opt/conda/lib/python3.7/site-packages/matplotlib/collections.py in draw(self, renderer)
    295         renderer.open_group(self.__class__.__name__, self.get_gid())
    296 
--> 297         self.update_scalarmappable()
    298 
    299         transform, transOffset, offsets, paths = self._prepare_points()

/opt/conda/lib/python3.7/site-packages/matplotlib/collections.py in update_scalarmappable(self)
    790             return
    791         if self._is_filled:
--> 792             self._facecolors = self.to_rgba(self._A, self._alpha)
    793         elif self._is_stroked:
    794             self._edgecolors = self.to_rgba(self._A, self._alpha)

/opt/conda/lib/python3.7/site-packages/matplotlib/cm.py in to_rgba(self, x, alpha, bytes, norm)
    242         x = ma.asarray(x)
    243         if norm:
--> 244             x = self.norm(x)
    245         rgba = self.cmap(x, alpha=alpha, bytes=bytes)
    246         return rgba

/opt/conda/lib/python3.7/site-packages/matplotlib/colors.py in __call__(self, value, clip)
   1015             result.fill(0)   # Or should it be all masked?  Or 0.5?
   1016         elif vmin > vmax:
-> 1017             raise ValueError("minvalue must be less than or equal to maxvalue")
   1018         else:
   1019             if clip:

**ValueError: minvalue must be less than or equal to maxvalue**
