### ISSUE TITLE
How to get the contribution of each features? (Force plot)

### ISSUE THREAD

**Issue by cejwlim11** [shap/shap#921]
Hello, I am trying to calculate the contribution of each features.
My model is LightGBM Classifier.

For example,
How can I get the contribution of feature 'PAY_0' ?  (below figure's length)

Code is below.
shap.force_plot( explainer.expected_value[1], shap_values[1][n], feature_names = test_X.columns,
                     features = test_X.iloc[n,:], link = 'logit', matplotlib = False )

![image](https://user-images.githubusercontent.com/58390417/69925679-bc2f1780-14f4-11ea-94d9-194cb9e094ac.png)

**Comment by slundberg** [comment]
In SHAP version 0.33.0 you can try `waterfall_plot`, or you can just look at the shap_values array directly. `shap_values[1][n][index]` will give you the value, where `index` is the column index of the feature `PAY_0`

**Comment by cejwlim11** [comment]
Thanks very much slundberg!
I found it!
