### ISSUE TITLE
DeepExplainer AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_SESSION'

### ISSUE THREAD

**Issue by shilpibhattacharyya** [shap/shap#924]
Hi @slundberg ,

When I am running this code, I am getting the following error. I have tried installing/uninstalling few combinations of tensorflow/keras. Nothing seems to resolve it. Can you kindly advise? Thank you.

Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-127-04f2c525c382> in <module>
      3 
      4 # we use the first 100 training examples as our background dataset to integrate over
----> 5 explainer = shap.DeepExplainer(classifier, X_train[:100])
      6 
      7 # explain the first 10 predictions

/usr/local/lib/python3.7/site-packages/shap/explainers/deep/__init__.py in __init__(self, model, data, session, learning_phase_flags)
     78 
     79         if framework == 'tensorflow':
---> 80             self.explainer = TFDeepExplainer(model, data, session, learning_phase_flags)
     81         elif framework == 'pytorch':
     82             self.explainer = PyTorchDeepExplainer(model, data)

/usr/local/lib/python3.7/site-packages/shap/explainers/deep/deep_tf.py in __init__(self, model, data, session, learning_phase_flags)
    113         if session is None:
    114             # if keras is installed and already has a session then use it
--> 115             if keras is not None and keras.backend.tensorflow_backend._SESSION is not None:
    116                 session = keras.backend.get_session()
    117             else:

AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_SESSION'

Code:
=======
import shap
import tensorflow.keras.backend 
explainer = shap.DeepExplainer(classifier, X_train[:100])
shap_values = explainer.shap_values(X_test[:10])

**Comment by slundberg** [comment]
DeepExplainer does not support TF 2.0, which seems to be the issue there. We are working on that, but you can use GradientExplainer for TF 2.0 for now if you like.

**Comment by GZuin** [comment]
I would like to add that GradientExplainer raises the same error message. Solved this issue by downgrading Keras to 2.2.4 (the release just before integration with TF 2.0 in 2018).

However, I'm now facing the error:
**TypeError: Fetch argument None has invalid type <class 'NoneType'>**

I'm getting this even when I'm attempting to reproduce the example from:
https://slundberg.github.io/shap/notebooks/deep_explainer/Keras%20LSTM%20for%20IMDB%20Sentiment%20Classification.html

Any tips?

**Comment by deepgradient** [comment]
@slundberg Hi Scott, do you have any idea as to when the support for DeepExplainer would be added to Shap?

**Comment by slundberg** [comment]
@deepgradient hard to predict since it depends on fixing a few issues in TF 2. could be this week though

**Comment by dupsys** [comment]
@slundberg can TensorFlow 2.0 support shap.DeepExplainer because I still got the same error:TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by su-park** [comment]
I got this error too and even GradientExplainer didn't work for me.

**Comment by Vibek** [comment]
@slundberg  I came here with a small doubt, Currently, I am using your shape libraries. I have built an integrated stacked model made out of three individual models (using transfer learning approach) and train them with my dataset. Later I am trying to explain the model output using GradientExplainer, but facing errors, however, when I used the same approach on individual methods it does work for me. Below is the error, I have faced. Maybe, I am doing silly mistakes, can you please verify. 

#Explainability of the model
explainer = GradientExplainer(stacked_model[members], data=X_train[:100])
print(explainer)
shap_values = explainer.shap_values(X_val[:10])
shap_values = shap_values[0]
pd.DataFrame(shap_values).head()
shap.summary_plot(shap_values, X_val[:10])
shap.summary_plot(shap_values, X_val[:10], plot_type="bar")

 assert type(X) == list, "Expected a list of model inputs!"
AssertionError: Expected a list of model inputs!

Here are highlights of the model code,

# define ensemble model
stacked_model = define_stacked_model(members)
print(stacked_model)
# fit stacked model on test dataset
fit_integrated_stacked_model(stacked_model, train_data_iot, test_data_iot)

# define filename for this ensemble
filename = '/home/vibek/Anomanly_detection_packages/DNN_Package/Model_IoT/stacked_model.h5'
# load model from file
model_f = load_model(filename)
#model.load_weights(filename)
print('>loaded stacked_model %s' % filename)

# make predictions and evaluate
yhat = predict_stacked_model(stacked_model, train_labels_iot)
yhat = np.argmax(yhat, axis=1)
print(yhat)
acc = accuracy_score(test_label_iot_original, yhat)

# fit a stacked model
def fit_integrated_stacked_model(model, inputX, inputy):
	# prepare input data
	X = [inputX for _ in range(len(model.input))]
	# encode output data
	#inputy_enc = to_categorical(inputy)
	cb = TimingCallback()
	# fit model
	model.fit(X, inputy, batch_size=batch_size, epochs=epochs, verbose=1, callbacks=[cb])
	print('Total Training time (seconds):',sum(cb.logs))

	filename = '/home/vibek/Anomanly_detection_packages/DNN_Package/Model_IoT/stacked_model.h5'
	model.save(filename)
	print('>Saved %s' % filename)

# make a prediction with a stacked model
def predict_stacked_model(model, inputX):
	# prepare input data
	X = [inputX for _ in range(len(model.input))]
	# make prediction
	return model.predict(X, verbose=0)
