### ISSUE TITLE
DeepExplainer TypeError: shap_values() takes from 2 to 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by fdaiki** [shap/shap#927]
Hi,
Thanks for so nice packeges,

I tried the example script:
[shap/notebooks/gradient_explainer/Explain an Intermediate Layer of VGG16 on ImageNet (PyTorch).ipynb](url)

I got the Error in third cell:
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-fa6059837c9c> in <module>()
     15 
     16 e = shap.GradientExplainer((model, model.features[7]), normalize(X))
---> 17 shap_values,indexes = e.shap_values(normalize(to_explain), ranked_outputs=2, nsamples=200)
     18 
     19 # get the names for the classes

~/.local/lib/python3.5/site-packages/shap/explainers/gradient.py in shap_values(self, X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
    103         were chosen as "top".
    104         """
--> 105         return self.explainer.shap_values(X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
    106 
    107 

TypeError: shap_values() takes from 2 to 6 positional arguments but 7 were given
`

My local environment:
・torch 1.0.1
・torchvision 0.2.1
・shap 0.32.1

Could you give me the answer? Thanks very much,I'm looking forward your rely.

**Comment by slundberg** [comment]
This should be fixed now by #873 in SHAP 0.33.0. Can you try again with the new version?

**Comment by fdaiki** [comment]
I upgrade the version to 0.33. It woks ,thank you very much!
