### ISSUE TITLE
Recent sklearn 0.22 update breaks TreeExplainer

### ISSUE THREAD

**Issue by wamartin-aml** [shap/shap#928]
`Model type not yet supported by TreeExplainer: <class 'sklearn.ensemble._forest.RandomForestClassifier'>` is just one fun example. Models that previously worked fine are broken. Haven't yet looked into what's actually broken.

**Comment by slundberg** [comment]
Ah...fun. Taking a look at it now.

**Comment by lemon-yellow** [comment]
I updated the `safe_isinstance` checks here- https://github.com/slundberg/shap/pull/929
