### ISSUE TITLE
What is happening in solve function in Kernel SHAP

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#93]
Could you please explain in brief what is happening in the solve function in Kernel SHAP in brief.

**Comment by slundberg** [comment]
The brief summary is that we use lasso feature selection if the space is not well sampled (to find which features have non-zero impact). Then we solve a least squares regression to estimate the SHAP values, where we eliminate one variable using the constraint that all SHAP values must sum to the function output. (This constraint is an infinite weighted sample in the paper's notation).

Note that the `l1_reg` parameter passed to `shap_values` controls the lasso feature selection.

**Comment by DiliSR** [comment]
Thank you so much.

**Comment by mizukasai** [comment]
I also had a question about the solve function in kernel shap, I don't understand the fact that the fraction argument is always nsamples/2**30 this fraction will always be really small for little datasets.
For example I used the titanic dataset with 4 features (so nsamples < 14) and it does go into the feature selection. Can you explain why we use 2**30 for every dataset ?

**Comment by slundberg** [comment]
@mizukasai I am not sure I follow your question. `max_samples = 2**30` is the maximum number of samples we want to draw which is not the actual number we use (which is `nsamples`). It is used to know how much of the sample space we have enumerated. When there are more than 30 features we just cap it at `2**30`. If we have not well covered the sample space then we use lasso feature selection.

**Comment by mizukasai** [comment]
@slundberg I see that this is what the comments on the code hint to. But there's one case where there's a problem  `M<=30 and nsamples <=  2 ** self.M - 2` : So if M=4 the Max should be 14 but if we input let's say nsamples=13 we never get to the code that changes max_samples and we end up with `max_samples = 2**30` I hope I made myself clear

**Comment by slundberg** [comment]
Ah!! Now I see what you are getting at. Thank you for pointing that out! That is indeed a bug, and incorrectly causes the feature selection code to get run for small sample sizes. I bet the bug got added when the second part of the if statement got added.
