### ISSUE TITLE
Documentation on shap.GradientExplainer

### ISSUE THREAD

**Issue by bmffb** [shap/shap#932]
I would appreciate if there would be more documentation on the shap.GradientExplainer function.
Where are the **indexes** coming from (here from the example) and what do they mean?

shap_values,**indexes** = e.shap_values(map2layer(to_explain, 7), ranked_outputs=2)

How is this working for a binary classification?

**Comment by slundberg** [comment]
Happy to add more there if it is helpful. What parts of the description in `help(e.shap_values)` is confusing/I should improve?

**Comment by bmffb** [comment]
With **help(e.shap_values)** you mean this: https://shap.readthedocs.io/en/latest/# ?
But on this documentation I cannot find any specific doumentation for the **shap.GradientExplainer**.

I am also very much interested if this would work for a binary image classification.

Regards.

**Comment by slundberg** [comment]
Ah, I see. `help()` is the python documentation function that prints docs for any object. ReadTheDocs was not including GradientExplainer and so I have not fixed that. thanks!

**Comment by bmffb** [comment]
Great, thanks for adding the documentation.
