### ISSUE TITLE
Questions regarding the solve function in Kernel SHAP

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#94]
1. Why we we eliminate one variable in Kernel SHAP solve function.
2. When estimating phi you have used weighted square equation. But in weighted square equation weight matrix should be a diagonal matrix. In brute force Kernel SHAP you have used a diagonal matrix. But not in here. Why is that? Or is that a mistake of mine. 

In weighted least square equation
inverse(X.T.WX).X.TWY
X- etmp
X.T.W-transpose(tmp)
Y-eyAdj2

I have assigned the variables in solve function to the Weighted Least Square equation. Could you please tell me whether that assignment is correct?

Thank you.

**Comment by Dilini-Sewwandi-Rajapaksha** [comment]
Did you understand my question. Do I need to elaborate this.

**Comment by Dilini-Sewwandi-Rajapaksha** [comment]
Is this a normalization step?

**Comment by DiliSR** [comment]
The reason for 1st question is that to avoid the neighbourhood goes to infinity?

**Comment by slundberg** [comment]
1 - right we can't sample correctly if one element has infinite weight. 2 - I just didn't create the diagonal matrix, but instead leave kernelWeights as a vector and multiply it the way it would happen if it was a diagonal matrix.

**Comment by Dilini-Sewwandi-Rajapaksha** [comment]
Why you didn't eliminate one variable in brute force kernel SHAP?

**Comment by DiliSR** [comment]
Thank you very much
