### ISSUE TITLE
Improved coloring of summary_plot 'dot' type

### ISSUE THREAD

**Issue by kodonnell** [shap/shap#95]
As discussed in #59, one of the problems with the dot plot is it's easy to end up being misleading when dots overlap each other e.g. depending on the order dots are plotted, you might end up with things appearing blue when they should 'actually' be red. More specifically, say there are 10 dots to appear, which are located in very similar places on the graph (so basically fully overlap) and 1 is blue, while 9 are red. If the blue one gets plotted last, then this area will look blue, not red, as it 'should' be. Note that, for a large graph this would be less of an issue, as the dots are much less likely to overlap - but with small graphs like these (and comparatively large dots - a single dot can often be 10% of the colored area), it's more likely to be a problem

Two possible solutions:

1. make sure we plot the dots in random order. This won't fix it for small graphs (as above), but will reduce the chance of e.g. the blue dot always being drawn over the red ones (in the 10 dot example). So, random error instead of systematic.
2. If a dot is standing alone, there's nothing to be done, but if there are two or more dots overlapping, we adjust their colors to give a more representative view. Detecting overlaps is relatively easy (either numerically, or just doing the trick of heatmaps will grayscales and opacity etc.). Choosing the colors appropriately is harder, but the simplest solution is to use opacity. This doesn't work normally, as if we say opacity=0.1 to make the overlaps clearer, it means all the standalone dots are hard to see. So, what we can do is make the opacity inversely proportional to the amount of overlapping occurring. Then everything should appear around about opacity 1 (after adding up overlaps), and the colors in overlapping areas should merge. This might end up with unpleasant colors (red + brown = yuck), but it's a start. Another similar options is to use unfilled circles (i.e. just a line, not filled) - these should overlap more nicely.

**Comment by slundberg** [comment]
Great suggestions. 1 is already implemented via a shuffle operation, so
that's done. I actually started on something similar to 2 but decided it
took more time than I had right now. I think we want an "average" blend
mode that sets every pixel to the average of it's overlapping dots, then
map that through the color scale. One way to do this would be to plot using
a pure green-red color scale and a 0.001 opacity. Then extract the raster
image and recolor by green/(green + red) color channels.

**Comment by kodonnell** [comment]
> I think we want an "average" blend mode that sets every pixel to the average of it's overlapping dots, then map that through the color scale. 

Yup, that's what I was thinking too.

> One way to do this would be to plot using a pure green-red color scale and a 0.001 opacity. Then extract the raster image and recolor by green/(green + red) color channels.

I think that's also what I was thinking - though when I've done it before (for proper heatmaps - not matrix grids) you use a low opacity greyscale image, and draw everything on that first, then extract the final opacity from that (which builds up under overlaps etc.). However, it can get quite fiddly - e.g. your 0.001 suggestion may only work if opacity is stored as a float, and not clamped to one of 255 values etc. Also, there's smoothing to consider. Anyway, I'd probably be more tempted to do this in a manually created x/y numpy array representing the grid - 'plot' everything into it (just points, not circle) and then do a basic gaussian filter to convert to colors. This could be an interesting plot in itself - or one could randomly sample colors from it to draw dots.

Another possible solution: instead of one big dot, draw e.g. 10 small dots randomly centered around the main dot - the idea being that in the case of two overlapping big dots, the 10 dots for each won't overlap, and hence you'll get an approximate averaging of color. Alternatively, if there's enough data, just use dots of a single pixel in size, with slightly randomised positions - with the shuffling, this should also give an average color. This will fail for really small graphs (which there often are) - so a sneaky option would be to simply draw bigger graphs first, then shrink them to fit into the existing graph.

But yes, agreed - it might take a bit of time. I probably won't look into it unless I want something fun to play with (and I'm a fan of the layered violin plot, which kind of solves it anyway).
