### ISSUE TITLE
AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option.

### ISSUE THREAD

**Issue by jjstarn-usgs** [shap/shap#950]
Tried with the option suggested and received the same error message.  I'm using shap in python version 0.33.  Previously, a model very similar to the failed model (same features and targets) ran successfully in shap.  I can provide data sets if necessary.

**Comment by slundberg** [comment]
Thanks for posting. Please share a complete example for debugging and we can look into it.

**Comment by jjstarn-usgs** [comment]
It will take me some time to extract a working example of the error.  I tried the same model with shap version = 0.29.2 and it worked fine.   The error happens with shap version=0.33.  The error occurs with no options and with , feature_perturbation='interventional'. I'm using shap with an xgboost regression model, version 0.90.  Hope that helps.  I will continue to work on an example.

**Comment by slundberg** [comment]
Thanks! That check was added recently to catch any unexpected corner case problems, so if you find a place where it fails I would appreciate an example we can reproduce.

**Comment by jjstarn-usgs** [comment]
data sets to reproduce the error--let me know if you have 
[Notebooks.zip](https://github.com/slundberg/shap/files/3962560/Notebooks.zip)
questions

**Comment by parrt** [comment]
Hi @slundberg, I just got the same error with 0.33 and xgboost 0.90 using your [league of legends notebook](https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/League%20of%20Legends%20Win%20Prediction%20with%20XGBoost.ipynb).  I downloaded the Kaggle data and copied the first part of the notebook to a standalone py file. Got the error

```
[0]	train-logloss:0.543193	valid-logloss:0.541947
Multiple eval metrics have been passed: 'valid-logloss' will be used for early stopping.

Will train until valid-logloss hasn't improved in 5 rounds.
[25]	train-logloss:0.286065	valid-logloss:0.286603
[50]	train-logloss:0.251781	valid-logloss:0.253591
[75]	train-logloss:0.233638	valid-logloss:0.236202
[100]	train-logloss:0.221021	valid-logloss:0.2243
[125]	train-logloss:0.211856	valid-logloss:0.215922
[150]	train-logloss:0.2028	valid-logloss:0.207597
[175]	train-logloss:0.195752	valid-logloss:0.2011
[200]	train-logloss:0.1898	valid-logloss:0.195689
[225]	train-logloss:0.183355	valid-logloss:0.189494
[250]	train-logloss:0.1781	valid-logloss:0.184515
[275]	train-logloss:0.172431	valid-logloss:0.179242
[299]	train-logloss:0.167329	valid-logloss:0.174417
Setting feature_perturbation = "tree_path_dependent" because no background data was given.
Traceback (most recent call last):
  File "league.py", line 119, in <module>
    shap_values = explainer.shap_values(Xv)
  File "/Users/parrt/anaconda3/lib/python3.7/site-packages/shap/explainers/tree.py", line 254, in shap_values
    self.assert_additivity(out, model_output_vals)
  File "/Users/parrt/anaconda3/lib/python3.7/site-packages/shap/explainers/tree.py", line 433, in assert_additivity
    assert np.max(np.abs(val - model_output) / (np.abs(val) + 1e-4)) < 1e-2, err_msg
AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub. Consider retrying with the feature_perturbation='interventional' option.
```

**Comment by parrt** [comment]
Currently trying with `feature_perturbation='interventional'` and gave it X training data. Seems to be too much data I think.  Changed 300 to 100 here `xgb.train(params, dt, 100, ...)` and pass data to explainer:

```
explainer = shap.TreeExplainer(model, data=shap.sample(Xt, 100), feature_perturbation='interventional')
```

Error received:

```
[0]	train-logloss:0.543193	valid-logloss:0.541947
Multiple eval metrics have been passed: 'valid-logloss' will be used for early stopping.

Will train until valid-logloss hasn't improved in 5 rounds.
[25]	train-logloss:0.286065	valid-logloss:0.286603
[50]	train-logloss:0.251781	valid-logloss:0.253591
[75]	train-logloss:0.233638	valid-logloss:0.236202
[99]	train-logloss:0.221568	valid-logloss:0.224798
100%|===================| 307359/307427 [07:24<00:00]       Traceback (most recent call last):
  File "league.py", line 119, in <module>
    shap_values = explainer.shap_values(Xv)
  File "/Users/parrt/anaconda3/lib/python3.7/site-packages/shap/explainers/tree.py", line 322, in shap_values
    self.assert_additivity(out, self.model.predict(X))
  File "/Users/parrt/anaconda3/lib/python3.7/site-packages/shap/explainers/tree.py", line 433, in assert_additivity
    assert np.max(np.abs(val - model_output) / (np.abs(val) + 1e-4)) < 1e-2, err_msg
AssertionError: Additivity check failed in TreeExplainer! Please report this on GitHub.
```

Enclosed python file (as text so it'd upload).

[league.py.txt](https://github.com/slundberg/shap/files/3963072/league.py.txt)

**Comment by sebnieh** [comment]
Are there any news?

**Comment by varshakirani** [comment]
Hello @slundberg ,
Even I am getting the same error. 
Versions used are:
xgboost : 0.90
shap : 0.33.0

My code looks like this:
![image](https://user-images.githubusercontent.com/3057235/70922900-2b455980-2027-11ea-8581-6098bd231d0a.png)

The same error occurs without using `background_data` in `TreeExplainer` function.

**Comment by slundberg** [comment]
Sorry I was traveling over the weekend and just now had a chance to address this. I used the League of Legends failure example and found it was due to a mismatch of 1.5475228e-04 vs. 1.49990987e-04. Because of the normalization I was doing in the test this showed up as a significant difference (even though it is just the expected variation from numerical precision). I just fixed this so we won't be overly sensitive for very small model outputs. It is now fixed for me, let me know if you still have issues using the master version of SHAP.

Thanks again for posting this!

**Comment by parrt** [comment]
My pleasure. Cool. I'll try from master when I can. Ok. @slundberg, I can confirm that 0.33.0.dev0 fixes additivity check for another dataset I'm working on (Kaggle rent dataset). Got a league example to avoid this error but now I'm getting bus error as [before](https://github.com/slundberg/shap/issues/954). Thanks for looking into this!  Uh oh. It appears intermittent. Tried again on the the rent dataset and same test got additivity check failure.

**Comment by grantstephens** [comment]
I just got this error with v0.44.0, so I don't think it is fixes yet.

**Comment by slundberg** [comment]
This check has proved more tricky to tune than I expected. I just pushed an improved error message that prints out the exact values that triggered the failure. @grantstephens would you mind trying again with the master version and sharing what values triggered the failure?

**Comment by grantstephens** [comment]
Hmm, that's slightly tricky, but I'll see what I can do. 

I was upgrading from 0.28 and everything above 0.31 fails, i.e. 0.31 is the latest one that worked for me- don't know if that helps.

**Comment by slundberg** [comment]
That's because this check was added in 0.32 as an extra layer of computational correctness assurance. You can just wait until 0.35 comes out to get the better error messages, for now setting check_additivity=False will revert the behavior to the pre 0.32 state.

**Comment by arashtayyebi** [comment]
> That's because this check was added in 0.32 as an extra layer of computational correctness assurance. You can just wait until 0.35 comes out to get the better error messages, for now setting check_additivity=False will revert the behavior to the pre 0.32 state.

I got the same error, I am wondering if you can tell me how can I fix this issue.
