### ISSUE TITLE
Numpy deprecation warning

### ISSUE THREAD

**Issue by fmazzasc** [shap/shap#951]
Hi, 
when running pytest for the function 

`shap.TreeExplainer()`

I have the following deprecation warning:

`NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INPUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.`

I think that the issue is related to the following lines:
https://github.com/slundberg/shap/blob/c7beff31d2ed2673d1a1b7c2a29f94aacc89c50e/shap/_cext.cc#L75
https://github.com/slundberg/shap/blob/c7beff31d2ed2673d1a1b7c2a29f94aacc89c50e/shap/_cext.cc#L159
https://github.com/slundberg/shap/blob/c7beff31d2ed2673d1a1b7c2a29f94aacc89c50e/shap/_cext.cc#L281
https://github.com/slundberg/shap/blob/c7beff31d2ed2673d1a1b7c2a29f94aacc89c50e/shap/_cext.cc#L376

Thanks for your attention!

**Comment by slundberg** [comment]
Thanks for highlighting this. Since it is just a warning I have been putting it on the back burner. Help is always appreciate though :)

**Comment by akshayparanjape** [comment]
Has anybody come up with a solution? It no more a warning and the SHAP computation crashes

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Some more context: the actual deprecation warning comes from here: https://github.com/mattip/numpy/blob/d3881b360367d2e5b1e44efcb6653c82c36ca68c/numpy/core/src/multiarray/ctors.c#L2003-L2008

It seems to have been removed as of numpy 1.23: https://github.com/numpy/numpy/pull/20589

Not sure what effect this has on shap

**Comment by javadba** [comment]
I am seeing several _hundred_ of these in the output.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Related: I also see this warning:

```
UPDATEIFCOPY detected in array_dealloc.  Required call to PyArray_ResolveWritebackIfCopy or PyArray_DiscardWritebackIfCopy is missing
```

https://github.com/numpy/numpy/blob/ef0ec786fd4c7622ad2fa0e54d3881f3b9bbd792/numpy/core/src/multiarray/arrayobject.c#L467-L469

**Comment by dsgibbons** [comment]
Is this still a problem now that #2943 has been merged? Note these changes have not been released on PyPI yet.

**Comment by thatlittleboy** [comment]
Closing as this should not be an issue anymore. Please raise a new ticket if there are follow-up concerns.
