### ISSUE TITLE
Linear explainer: Background of the "_estimate_transforms" function

### ISSUE THREAD

**Issue by florentin-r** [shap/shap#952]
Hi Scott, 

could you please explain the underlying theory of the "_estimate_transforms" function within the linear explainer? The rows 147 – 175 are relatively clear, whereas the calculations of rows 177 – 195 are not easily comprehensible, especially the meaning of the coefficients Q(bar(Sui), Q(bar(S), coef_R_Si, and coef_R_S as well as the calculation of the "mean_transform" matrix. The row numbers refer to the row numbers in your Git repository.
 
Thanks for your support!
 
Best regards

Florentin

**Comment by slundberg** [comment]
I just cleaned up an expanded a Notebook that I had describing the derivation of this math. It is now available at: https://github.com/slundberg/shap/blob/master/notebooks/linear_explainer/Math%20behind%20LinearExplainer%20with%20correlation%20feature%20perturbation.ipynb

Keep in mind that the linear algebra is pretty dense, so it is not a light read, or as well documented as if it was wrapped up into a nice paper (it hasn't yet been published).
