### ISSUE TITLE
Question: Non-negative Shapley Values

### ISSUE THREAD

**Issue by 1989-juliana-h** [shap/shap#956]
From the theory it is clear that Shapley value attribution leads to negative values for observations where the outcome shows a smaller value than the average prediction.
Further I understand that we don't get beta coefficients from ML models. 
However, I was wondering whether it could be possible to determine the intercepts for every feature to enable the model to only attribute positive values, thereby summing up to the prediction and not the difference between the prediction and the expected value. 
Would be cool if someone thought about this issue as well or could contribute anything to the solution.

**Comment by slundberg** [comment]
Well one way would be to define a prior background distribution that has an expected model output of 0. Then you will always sum up to the prediction value (though it will not guarantee that all the SHAP values will be positive, since some might still lower the output and others might raise it).
