### ISSUE TITLE
ImportError: cannot import name 'lobpcg'

### ISSUE THREAD

**Issue by Niloofar-mni** [shap/shap#957]
I just updated shap-0.33.0 via project interpreter (Python 3.6) in pycharm. When importing shap I get the following error:

---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-33-8cfbc26c443e> in <module>
----> 1 import shap
      2 

~/venv3/lib/python3.6/site-packages/shap/__init__.py in <module>
      6 
      7 # explainers
----> 8 from .explainers.kernel import KernelExplainer, kmeans
      9 from .explainers.sampling import SamplingExplainer
     10 from .explainers.tree import TreeExplainer, Tree

~/venv3/lib/python3.6/site-packages/shap/explainers/kernel.py in <module>
      9 import warnings
     10 from sklearn.linear_model import LassoLarsIC, Lasso, lars_path
---> 11 from sklearn.cluster import KMeans
     12 from tqdm.auto import tqdm
     13 from .explainer import Explainer

~/venv3/lib/python3.6/site-packages/sklearn/cluster/__init__.py in <module>
      4 """
      5 
----> 6 from ._spectral import spectral_clustering, SpectralClustering
      7 from ._mean_shift import (mean_shift, MeanShift,
      8                           estimate_bandwidth, get_bin_seeds)

~/venv3/lib/python3.6/site-packages/sklearn/cluster/_spectral.py in <module>
     15 from ..metrics.pairwise import pairwise_kernels
     16 from ..neighbors import kneighbors_graph, NearestNeighbors
---> 17 from ..manifold import spectral_embedding
     18 from ._k_means import k_means
     19 

~/venv3/lib/python3.6/site-packages/sklearn/manifold/__init__.py in <module>
      6 from ._isomap import Isomap
      7 from ._mds import MDS, smacof
----> 8 from ._spectral_embedding import SpectralEmbedding, spectral_embedding
      9 from ._t_sne import TSNE, trustworthiness
     10 

~/venv3/lib/python3.6/site-packages/sklearn/manifold/_spectral_embedding.py in <module>
     18 from ..utils import check_random_state, check_array, check_symmetric
     19 from ..utils.extmath import _deterministic_vector_sign_flip
---> 20 from ..utils.fixes import lobpcg
     21 from ..metrics.pairwise import rbf_kernel
     22 from ..neighbors import kneighbors_graph, NearestNeighbors

ImportError: cannot import name 'lobpcg'

**Comment by slundberg** [comment]
Try executing `from sklearn.cluster import KMeans`. It looks like something is messed up in your sklearn install.

**Comment by rahul-raoniar** [comment]
Not able to import shap


Got the following error while importing the shap package

cannot import name 'lobpcg' from 'sklearn.utils.fixes' (D:\Software_Installation\envs\Python3_ML\lib\site-packages\sklearn\utils\fixes.py)
