### ISSUE TITLE
Can TreeExplainer be used with tf.estimator.BoostedTreesClassifier?

### ISSUE THREAD

**Issue by shendiaomo** [shap/shap#958]
I can't see `BoostedTreesEstimator` in the source code of `TreeExplainer`, but `BoostedTreesEstimator` is an important part of TensorFlow canned estimators and should be supported by `TreeExplainer`.

**Comment by ThuongCroud** [comment]
hi shendiaomo,
I've tried using the TreeExplainer with Tensorflow's Boosted Trees Estimator before, but unfortunately it's not compatible.
As a plan B, I ended up following this guide here to build something similar using LGBM instead: https://towardsdatascience.com/prediction-and-inference-with-boosted-trees-and-shapley-values-4ffef46b969a

It would be great if TreeExplainer was compatible with Tensorflow, though!

**Comment by slundberg** [comment]
I agree it would be great to support this directly. There is no fundamental reason we couldn't add these bindings, but the TF BoostedTreesEstimator is very tightly bound to the input formats of TF tensors so it might be a bit more work than some other sklearn models. (since the BoostedTreesEstimator does not just take in a standard dataframe by default).

Tagging this since I don't have the bandwidth to tackle it at the moment.

**Comment by shendiaomo** [comment]
> hi shendiaomo,
> I've tried using the TreeExplainer with Tensorflow's Boosted Trees Estimator before, but unfortunately it's not compatible.
> As a plan B, I ended up following this guide here to build something similar using LGBM instead: https://towardsdatascience.com/prediction-and-inference-with-boosted-trees-and-shapley-values-4ffef46b969a
> 
> It would be great if TreeExplainer was compatible with Tensorflow, though!

At last, I managed to support explaining TF estimators using KernelExplainer, thanks to the discussion here and at https://github.com/slundberg/shap/issues/280.

Directly supporting `BoostedTreesEstimator` with `TreeExplainer` is still wanted because `shap.TreeExplainer(model).shap_interaction_values(X) ` is rather useful.

**Comment by zhangxiang390** [comment]
> > hi shendiaomo,
> > I've tried using the TreeExplainer with Tensorflow's Boosted Trees Estimator before, but unfortunately it's not compatible.
> > As a plan B, I ended up following this guide here to build something similar using LGBM instead: https://towardsdatascience.com/prediction-and-inference-with-boosted-trees-and-shapley-values-4ffef46b969a
> > It would be great if TreeExplainer was compatible with Tensorflow, though!
> 
> At last, I managed to support explaining TF estimators using KernelExplainer, thanks to the discussion here and at #280.
> 
> Directly supporting `BoostedTreesEstimator` with `TreeExplainer` is still wanted because `shap.TreeExplainer(model).shap_interaction_values(X) ` is rather useful.

hi, would you show me some demo code here how can use SHAP with tensorflow Estimator, Thanks a million.

**Comment by bbakernoaa** [comment]
I would also be interested in this

**Comment by ShuyangenFrance** [comment]
I am interested in this and I would like to see if I can contribute.
