### ISSUE TITLE
Implementation of DeepLift in DeepShap

### ISSUE THREAD

**Issue by farh33n** [shap/shap#959]
Is DeepShap(DeepLift + Shapley values) implemented in your current implementation? I am unable to find the computation of DeepLift's multipliers(as given on page 7 of [paper](http://papers.nips.cc/paper/7062-a-unified-approach-to-interpreting-model-predictions.pdf)) in your current implementation.
Also is this current implementation of DeepShap suitable for Recurrent Neural Networks?

**Comment by slundberg** [comment]
DeepExplainer uses these multipliers implicitly by overriding the built-in gradient back propagation routine of deep learning libraries. As for the suitability for recurrent networks, it certainly can work and we have seen some results that it seems to work https://arxiv.org/abs/1911.11888, but we would like to extend these tests to our benchmark code in SHAP. Getting this benchmark scaled up is something I am trying to get going in the new year.
