### ISSUE TITLE
Decision plot issue

### ISSUE THREAD

**Issue by prathyushapatel** [shap/shap#961]
When I tried running the below line, I have got the error along with the output plot.
`shap.decision_plot(explainer.expected_value[0], shap_values[0], X, link="logit")`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-1f7da4b1e61e> in <module>()
----> 1 shap.decision_plot(explainer.expected_value[0], shap_values[0], X, link="logit")

~\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\plots\decision.py in decision_plot(base_value, shap_values, features, feature_names, feature_order, feature_display_range, highlight, link, plot_color, axis_color, y_demarc_color, alpha, color_bar, auto_size_plot, title, xlim, show, return_objects, ignore_warnings, new_base_value, legend_labels, legend_location)
    538         show,
    539         legend_labels,
--> 540         legend_location,
    541     )
    542 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\shap\plots\decision.py in __decision_plot_matplotlib(base_value, cumsum, ascending, feature_display_count, features, feature_names, highlight, plot_color, axis_color, y_demarc_color, xlim, alpha, color_bar, auto_size_plot, title, show, legend_labels, legend_location)
    146         # place the colorbar
    147         pl.ylim(0, feature_display_count + 0.25)
--> 148         ax_cb = ax.inset_axes([xlim[0], feature_display_count, xlim[1] - xlim[0], 0.25], transform=ax.transData)
    149         cb = pl.colorbar(m, ticks=[0, 1], orientation="horizontal", cax=ax_cb)
    150         cb.set_ticklabels([])

AttributeError: 'AxesSubplot' object has no attribute 'inset_axes'

**Comment by prathyushapatel** [comment]
![image](https://user-images.githubusercontent.com/24317890/71068014-ba737e00-219b-11ea-93ce-a2fee9f802fc.png)

**Comment by ibuda** [comment]
Could you please provide more code? That would help to reproduce the error you're dealing with. Thank you.

**Comment by prathyushapatel** [comment]
import pandas as pd
import numpy as np
import shap
from xgboost import XGBClassifier
data = pd.read_csv("C:/Users/765204/Downloads/Iris.csv")
X = data.iloc[:,:4]  
y = data.iloc[:,-1]  
model =XGBClassifier()
model.fit(X,y)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
shap.initjs()
shap.decision_plot(explainer.expected_value[0], shap_values[0], X, link="logit")

**Comment by ibuda** [comment]
The code runs fine on my machine. I googled it, and it seems that the error comes from your `matplotlib` package. Make sure it is the newest one and/or upgrade it. 
Come back if the error persists after upgrading.

**Comment by nsood-ai** [comment]
Hey,
I am facing the same problem. I was wondering if you got any solution for this error.
Error encountered : "AttributeError: 'AxesSubplot' object has no attribute 'inset_axes'"

Thanks.

**Comment by Frank-LSY** [comment]
Same Problem, too...... 
What's the specific version of `matplotlib` package are you using?

**Comment by astro313** [comment]
I have similar issue.
Python 3.6, matplotlib 2.1.2.

This should be fixable by updating matplotlib to version 3.0 and above. A quick fix for those who don't want to mess around with mpl version:

Locate the decision.py file in your shap package: `shap/plots/decision.py`, and inside `__decision_plot_matplotlib`, update the relevant lines to:
```
        # place the colorbar
        pl.ylim(0, feature_display_count + 0.25)
        try:
            ax_cb = ax.inset_axes([xlim[0], feature_display_count, xlim[1] - xlim[0], 0.25], transform=ax.transData)
        except AttributeError:
            from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable
            ax_divider = make_axes_locatable(ax)
            ax_cb = ax_divider.append_axes("top", size="7%", pad="8%")

        cb = pl.colorbar(m, ticks=[0, 1], orientation="horizontal", cax=ax_cb)
        cb.set_ticklabels([])
        cb.ax.tick_params(labelsize=11, length=0)
        cb.set_alpha(alpha)
        cb.outline.set_visible(False)
```
