### ISSUE TITLE
Unable to run for a Keras wide & deep-type model 

### ISSUE THREAD

**Issue by dronshaw** [shap/shap#964]
- Popular [wide & deep model](https://arxiv.org/pdf/1606.07792.pdf) is the combination of two networks
- Assume the wide network is represented as one entire array, while the deep network contains one or more word embeddings
- Then, the input into a Keras model could be formed like so
```
combined_model = keras.Model([numeric_wide_input,embed_input_1,embed_input_2,embed_input_3], merged_out)
combined_model.compile(optimizer = 'adam', loss = 'binary_crossentropy')
combined_model.fit(x=[x_train,train_embed_1,train_embed_2,train_embed_3], 
                                   y = y_train)
# where x_train is of type pd.DataFrame
# where train_embed_1,2,3 are of type numpy.ndarray
```
- A keras network like this (from what I can tell) cannot be used within Shap
```
import shap
# example data
foo_train = [x_train[new_numeric_features][1:10],
                                train_pad_dv[1:10],train_pad_prch[1:10],train_pad_div[1:10]]

# form explainer
explainer = shap.KernelExplainer(combined_model,data=foo_train)

# get shap values
shap_values = explainer.shap_values(foo_train)

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-37-4469b5a632da> in <module>()
      5 
      6 # form explainer
----> 7 explainer = shap.KernelExplainer(combined_model,data=foo_train)
      8 
      9 # get shap values

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/shap/explainers/kernel.py in __init__(self, model, data, link, **kwargs)
     94         self.keep_index = kwargs.get("keep_index", False)
     95         self.keep_index_ordered = kwargs.get("keep_index_ordered", False)
---> 96         self.data = convert_to_data(data, keep_index=self.keep_index)
     97         model_null = match_model_to_data(self.model, self.data)
     98 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/shap/common.py in convert_to_data(val, keep_index)
    176         return SparseData(val)
    177     else:
--> 178         assert False, "Unknown type passed as data object: "+str(type(val))
    179 
    180 class Link:

AssertionError: Unknown type passed as data object: <class 'list'>
```
- Obviously due to the fact that the input data is not in an expected dataframe but is several arrays.

**Comment by slundberg** [comment]
A list of arrays is a supported input format for GradientExplainer and DeepExplainer, but not KernelExplainer right now. I have added a todo to note that this would be nice so as to eliminate the need for a custom wrapper function.

Hope that helps!

**Comment by dronshaw** [comment]
Thanks @slundberg - still getting some errors using 0.34.0 installed from pip. Should this be working in this version?

**Comment by dronshaw** [comment]
@slunberg when updating to master, I see that the fix here [1] has resolved my issue. Thanks!

[1] https://github.com/slundberg/shap/commit/5c80cf674d6da5d19f83c6879fdcf9af824558cc#diff-ae7e6bcf781952177c085a813f45c816

**Comment by admodadmod** [comment]
> @slunberg when updating to master, I see that the fix here [1] has resolved my issue. Thanks!
> 
> [1] [5c80cf6#diff-ae7e6bcf781952177c085a813f45c816](https://github.com/slundberg/shap/commit/5c80cf674d6da5d19f83c6879fdcf9af824558cc#diff-ae7e6bcf781952177c085a813f45c816)

Hi
How do you solve the problem? I use 0.39.0 and KernelExplainer. I got :
AssertionError: Unknown type passed as data object: <class 'list'>
