### ISSUE TITLE
Unable to view features of low/zero importance

### ISSUE THREAD

**Issue by SSMK-wq** [shap/shap#969]
Hello Everyone,

I am new to shap and trying to understand the model predictions through shap plot as shown below. 

q1)   As you can see in the below graph that only 12-13 features are visible in the plot. But my dataset has around 42-44 features? Does shap plot show only the important features or am I making any mistake here?

q2)  Is there any other shap plot that I should use to see all the features?

Please find the code below that I wrote

`shap.summary_plot(shap_values, features=X_train, feature_names=X_train.columns)`

![image](https://user-images.githubusercontent.com/30723825/71360900-4c302080-25cc-11ea-970e-b7eb7ee18375.png)

**Comment by ibuda** [comment]
Have you tried the ` max_display` parameter? By default, `summary_plot` displays top 20 features, which is exactly your case. If you need more, add this parameter with the value of the number of top features you would like to see. Exampe:
```
shap.summary_plot(shap_values, features=X_train, feature_names=X_train.columns, max_display=44)
```
will display the plot for all your 44 features.
