### ISSUE TITLE
Question about sample generation

### ISSUE THREAD

**Issue by DiliSR** [shap/shap#97]
Without just getting the all the combinations from the feature set, what is the logic that you have used using num_subset_sizes and num_paired_subset_sizes ect to  generate new samples in Kernel SHAP? 

In Brute Force Kernel SHAP you have made the powerset by taking all the combinations. In real code what is the logic behind that?

**Comment by slundberg** [comment]
The idea is that very small and very large subsets have higher weight than other subsets. There are also fewer of them, so we enumerate all of them that we can, and then randomly sample from the rest. Not sure if that answers your question.

**Comment by DiliSR** [comment]
Thank you.
My next questions are,
1.) Is there a bias between the shapley values generated considering the whole subsets and considering the subsets taken by the criteria that you have mentioned before? 
2.) In your kernel SHAP code until the number of impacted features are equal to 11, it will consider all the subsets combinations. Is that correct. 
3.) nsamples = self.M - 2; this 2 is subset with all zeros and all ones?

**Comment by slundberg** [comment]
1) If I understand your question correctly, no, both approaches should have estimates with variance centered around the same values.
2) Since the default number of samples is just over 2k then yes.
3) That's right!

**Comment by DiliSR** [comment]
Thank you.

1.what do you mean by num_paired_subset_sizes? As I understood it is used to find the complement subsets of the sizes that cannot be taken from the num_subset_sizes. (Then what happen when num_paied_subset size == num_subset_sizes) Always num_paired_subset_sizes is less than or equal to the subset size. When the num_paired_subset size is equal to the subset size, size of the complement subset is equal to the  maximum size of num_subset_sizes.

2.  why do we double the weight of the weight vector up to the indices  of num_paired_subset size? Is that the original subset and the complement of it?

**Comment by slundberg** [comment]
Sorry for the late reply. 
1. Some subset sizes are paired, meaning there is a complement subset that has the same number of zeros as this subset has ones. But if there are an odd number of subset sizes then we one of them won't be paired, hence why num_paired_subset_sizes can be smaller. We keep track of pairing to as to explore the part of the space we can exhaustively enumerate in a symmetric way.
2. Yes!

**Comment by rameshbkrishnan** [comment]
Hi,

 I am facing issue related to KernelExplainer and number of samples it generates for getting shapValues and so using this existing thread. I have custom ML models for which i wanted to enable shap. I have combination of tree based and non-tree based models for which we want to enable SHAP. I created function which takes input data and outputs the probability of each class (similar to what is expected in LIME for custom models) and was successfully able to get SHAP Values and visualizations. But explainer.shap_values is generating too many samples and is taking long. 

For IRIS dataset(120 rows and 4 features), it generates 1680 points for each training record and so custom predict_proba function is called 120 times (1680x100) and shap_values and plots are generated. But for income dataset, where I had 20K records and around 14 features, the sample points generated are around 200K and this is taking too long for each point to get predict_proba function. Also this has to be called for all 20K records to get summary_plot. I tried provide nsamples but it did not help. 

Can you please provide any pointers on how to handle this situation with KernelExplainer.
Also, for custom tree model, can i implement TreeSHAP and will it have better performance and results. If so, how do we do it. I saw the below notebook, but not sure if that's the right path and if so how to use it.

https://github.com/slundberg/shap/blob/master/notebooks/tree_explainer/Python%20Version%20of%20Tree%20SHAP.ipynb

Thanks

**Comment by slundberg** [comment]
@rameshbkrishnan For KernelExplainer you don't want to pass the whole dataset for the background. Try using just a single reference value, or using shap.kmeans to summarize the dataset as just a few weighted points.

For Tree SHAP take a look at the first constructor for the `Tree` class in `explainers/tree.py`. It takes a tree definition in the same format sklearn uses and you can use that to explain any custom tree model you have.
