### ISSUE TITLE
TypeError Shap Value

### ISSUE THREAD

**Issue by santiagovasquez99** [shap/shap#973]
I have training Decision Tree model:  

`clf = DecisionTreeClassifier(random_state=1)
param_grid = {'classifier__max_depth':np.arange(5, 15),
              'classifier__criterion':['gini', 'entropy'],
              'classifier__min_samples_leaf':np.arange(5, 20, 5)}
grid_search = GridSearchCV(model_pipeline,
                           param_grid=param_grid,
                           n_jobs=5,
                           cv = 3,
                           verbose=2)
grid_search.fit(X_train, y_train)` 

`k_explainer = shap.KernelExplainer(clf.predict,
                                   X_train.iloc[row_to_show],
                                   feature_dependence="independent",
                                   model_output="probability")`

`shap_values = k_explainer.shap_values(np.array(X_train.iloc[row_to_show]), l1_reg="bic")`

And I have this error 

![Screenshot from 2019-12-26 13-32-52](https://user-images.githubusercontent.com/59267103/71492744-a832b900-2807-11ea-99fc-a92bb89f65ec.png)
url)

@slundberg Your help is much appreciated.
Thanks

**Comment by slundberg** [comment]
I would first recommend TreeExplainer for a `DecisionTreeClassifier` model...but as to why KernelExplainer is not working, I am not sure. Could you share a self contained example? Something seems to have made numpy unhappy.

**Comment by santiagovasquez99** [comment]
Hello @slundberg I have solved this error. 

Thanks
