### ISSUE TITLE
no output after shap.initjs() no js symbol

### ISSUE THREAD

**Issue by rollinglyj** [shap/shap#974]
thanks for this fantastic tool
but I can not see any figure after shap.force_plot() ,with no error or warning 
I am using anaconda ipynotebook ,py3.6 
![WX20191227-183914](https://user-images.githubusercontent.com/8487563/71514132-3c6c5100-28d8-11ea-977c-d11e71175485.png)

**Comment by slundberg** [comment]
Interesting. Is this just a session from a `jupyter notebook` server?

**Comment by rollinglyj** [comment]
yes, I don't know why. other output is normal. matplotlib works well . But no js pic.

**Comment by rollinglyj** [comment]
after i reboot my macbook, it works well . It is so mysterious
