### ISSUE TITLE
Labels are not rendered properly

### ISSUE THREAD

**Issue by prathyushapatel** [shap/shap#978]
![summary](https://user-images.githubusercontent.com/24317890/71655665-d2cbc700-2d5d-11ea-8b35-93173e72eddc.png)

**Comment by ibuda** [comment]
I tried to reproduce this issue with the latest shap version and very long names in the feature_names parameter, but the plot works fine (please see attached screenshot).
I would advise you to try playing with the plot_size parameter. Try setting high values for it, i.e. (25, 25) and see if the plot visualizes the feature names in full length. If that does not help, please come back with both `shap` and `matplotlib` package versions you are currently using. 
![Screenshot from 2020-01-02 11-14-20](https://user-images.githubusercontent.com/42291858/71659825-aa3dd000-2d51-11ea-81c9-3a5776737940.png)

**Comment by prathyushapatel** [comment]
plot_size attribute worked. Thanks

**Comment by prathyushapatel** [comment]
But the whole size of plot is increasing. I just want the labels to be shown completely.
shap - 0.33.0
matplotlib - 3.1.1

**Comment by ibuda** [comment]
Did you try different values for plto_size tuple? Give it a big enough value for x (horizontal) and set a suitable value for y (height). I would suggest for example (10, 5), or (15, 10), or (12, 7), etc...

**Comment by prathyushapatel** [comment]
I've used plot_size =(30,10) which worked fined for large column names. 
But that's not the solution because I want all the plots to look alike(same bar width). It may work fine in 1st case but in 2nd case the bars appear large.

Is there any way I can get complete label names without using plot_size


![image](https://user-images.githubusercontent.com/24317890/71687075-f543fb80-2dc2-11ea-9c41-e01e6cb7b563.png)

![image](https://user-images.githubusercontent.com/24317890/71687142-2290a980-2dc3-11ea-88ee-046e44925e49.png)

**Comment by ibuda** [comment]
Can you paste the output here of the following command in the terminal:
```
pip freeze
```

**Comment by prathyushapatel** [comment]
I'm actually using it docker. So I can't actually do pip freeze. I've checked the shap and matplotlib versions and commented it above

**Comment by ibuda** [comment]
Try installing matplotlib 3.1.0 version, or even 3.0.1. I've seen people complaining about bugs in the most recent versions.

**Comment by marchezinixd** [comment]
I'm having the same issue. Tried to install matplotlib  3.0.1. but the problem still remains. 
I can't increase more the plot_size, because some of my labels are really big and the image is losing it's visibility.

**Comment by marchezinixd** [comment]
https://discuss.streamlit.io/t/display-shap-diagrams-with-streamlit/1029 
The awnser for this question is in this link. Basically use 
`st.pyplot(bbox_inches='tight')
 plt.clf()`
instead of st.write()
