### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ibuda** [shap/shap#979]
I updated the package to the latest version 0.34 to reproduce some of the newly reported issues and noticed that for some reason the fix #745 is not included in current package.  

https://github.com/slundberg/shap/blob/cf4e9b04bd369be0949d67cc15a1743f8a5c1b1b/shap/explainers/tree.py#L1362

For those who face this same issue, you can install the latest version from git repository by running:
```
pip install git+https://github.com/slundberg/shap
```

**Comment by slundberg** [comment]
Thanks for noting this. I'll push a new version here soon, I was hoping to wrap up a couple other changes into it first.

**Comment by yoavweg** [comment]
Hi, any news with the IndexError progression? Does manually changing line 1362 in tree.py as @ibuda  actually resolves the issue?

**Comment by ibuda** [comment]
@yoavweg as of today, the latest version on pypi and conda does not have the fix.
You can use the command I specified above to install latets version from git:
```
pip install git+https://github.com/slundberg/shap
```
This one solves the issue.

**Comment by ibuda** [comment]
Fixed, closing.
