### ISSUE TITLE
Deep Shap implementation

### ISSUE THREAD

**Issue by leexa90** [shap/shap#99]
Hi Scott,

I was wondering if there is an implementation on Deep SHAP which i believe is also termed as "new Deeplift" in the paper. I was hoping it would work faster for a 50 super pixel image compared to sampling 5000 times. 

# use Kernel SHAP to explain the network's predictions
explainer = shap.KernelExplainer(f, np.zeros((1,50)))
shap_values = explainer.shap_values(np.ones((1,50)), nsamples=5000) # runs VGG16 1000 times

**Comment by slundberg** [comment]
Good question. I have not released a general code base for that yet. How to best support different deep learning packages is something that will take some work. I'll post here if it looks like this is something that will happen.

**Comment by AvantiShri** [comment]
Came across this issue while googling DeepSHAP - just wanted to add a note for @leexa90 that "new DeepLIFT" in the paper actually referred to DeepLIFT with the RevealCancel rule (rather than the Rescale rule). The distinction is in the DeepLIFT paper.
