### ISSUE TITLE
Waterfall_plot info

### ISSUE THREAD

**Issue by grassoste** [shap/shap#991]
I was eager to try the new waterfall plot feature and I got no problem creating the plot with one sample:

`shap.waterfall_plot(explainer.expected_value, shap_values[0,:], feature_names=X.columns.values, max_display=5, show=True)`
![image](https://user-images.githubusercontent.com/15910227/72086203-d1267400-3306-11ea-9d46-2aa8430d2be0.png)

Then I wanted to try it over multiple samples, e.g.: 
`shap.waterfall_plot(explainer.expected_value, shap_values[:10,:], feature_names=X.columns.values, max_display=20, show=True)`
or
`shap.waterfall_plot(explainer.expected_value, train_shap_values[:10,:], features=X.iloc[:10,:], max_display=20, show=True)`
but both return errors (despite being different errors).

Since there is no clear info about the waterfall plot, I was wandering if it is actually possible to produce this type of plot for multiple samples. I couldn't find any info neither among the issues nor in readthedocs. 

Thank you for any hints, and great job to all the people that contributed to SHAP!

**Comment by slundberg** [comment]
I added more docs and a better error message. Right now waterfall_plot can only do a single explanation at a time. ...not sure what a multi-explanation version would look like.

**Comment by grassoste** [comment]
Thanks a lot @slundberg!
