### ISSUE TITLE
marginal effect dependence plot error

### ISSUE THREAD

**Issue by aymoawad** [shap/shap#992]
Minor issue, just bringing it to your attention: it looks like the `shap.dependence_plot(("feat_name","feat_name"), shap_interaction_values, X)` to extract marginal effect (or interactional effects) does not work anymore in 0.34. It was a convenient syntax.

**Comment by grassoste** [comment]
Same issue here. I just wanted to plot a few and keep getting error.
Of note, out of the same model and dataset I had no issue previously (TreeExplainer). 

Errror is:

```
shap.dependence_plot(("G_H","G_H"), interaction_vals, X)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-63a1e4ca3aa4> in <module>
----> 1 shap.dependence_plot(("G_H","G_H"), train_interaction_vals, X)

/usr/local/lib/python3.7/dist-packages/shap/plots/dependence.py in dependence_plot(ind, shap_values, features, feature_names, display_features, interaction_index, color, axis_color, cmap, dot_size, x_jitter, alpha, title, xmin, xmax, ax, show)
    103     # guess what other feature as the stongest interaction with the plotted feature
    104     if interaction_index == "auto":
--> 105         interaction_index = approximate_interactions(ind, shap_values, features)[0]
    106     interaction_index = convert_name(interaction_index, shap_values, feature_names)
    107     categorical_interaction = False

/usr/local/lib/python3.7/dist-packages/shap/common.py in approximate_interactions(index, shap_values, X, feature_names)
    298         inds = np.arange(X.shape[0])
    299 
--> 300     x = X[inds, index]
    301     srt = np.argsort(x)
    302     shap_ref = shap_values[inds, index]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

P.S. Just to clarify, also the syntax `"rank(0)"` or simply the index are not working. I checked the information inside the `decision_plot.py` file and actually it is not mentioned anymore. Same in the new notebook, nor in the novel Nature ML paper. It is still described only in the old NHANES notebook. Is it a feature that has been removed?

**Comment by slundberg** [comment]
Thanks for noting this! I just pushed a fix :)

**Comment by grassoste** [comment]
Thanks a lot @slundberg!

**Comment by RobinDoesUnity** [comment]
I copied the code from the NHANES notebook and still getting the error, sadly on v. 0.35.0.
Is there a workaround?

**Comment by grassoste** [comment]
I updated to version 0.35 as well and the error is gone when doing `shap.dependence_plot(("feat_name","feat_name"), shap_interaction_values, X)`. 
Are you sure the error is not about something else?

**Comment by RobinDoesUnity** [comment]
Ahh, my mistake - I forgot to restart the notebook after updating the package. It works now.
Thank you for the quick answer!

**Comment by grassoste** [comment]
No problem :)
