### ISSUE TITLE
Error using custom rank on GradientExplainer:  IndexError: tuple index out of range

### ISSUE THREAD

**Issue by jaschil2** [shap/shap#994]
Hello I am trying to use/test out the GradientExplainer with custom output and I have the following code:

```
explainer = shap.GradientExplainer(flat_model,images)
shap_values = explainer.shap_values(
    images[0][np.newaxis,...],
    nsamples=5000,
    output_rank_order='custom',
    ranked_outputs=np.array([0]))
```
which gives me the error:

```
~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/shap/explainers/gradient.py in shap_values(self, X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
    258             rseed = np.random.randint(0, 1e6)
    259 
--> 260         for i in range(model_output_ranks.shape[1]):
    261             np.random.seed(rseed) # so we get the same noise patterns for each output class
    262             phis = []

IndexError: tuple index out of range
```

Note: I originally used a list for the ranked_outputs but that gave me an error as well:

```
~/.pyenv/versions/3.7.2/lib/python3.7/site-packages/shap/explainers/gradient.py in shap_values(self, X, nsamples, ranked_outputs, output_rank_order, rseed, return_variances)
    258             rseed = np.random.randint(0, 1e6)
    259 
--> 260         for i in range(model_output_ranks.shape[1]):
    261             np.random.seed(rseed) # so we get the same noise patterns for each output class
    262             phis = []

AttributeError: 'list' object has no attribute 'shape'
```

This would not be an issue if I could just store shap values for all outputs, but there are too many outputs and I do not have enough memory. Do you have any idea how I could fix this? Am I making a mistake somewhere?

**Comment by orilan93** [comment]
ranked_outputs needs to be a 2D array where shape[0] is the size of the samples you send in. I am not certain what the indices we pass in refer to though.

I find the documentation a bit unclear here. The documentation of ranked_outputs does not explain the case where an array is passed and output_rank_order says it requires a list, which is wrong.
