### ISSUE TITLE
how to larger the text size of feature name  in a shap force plot

### ISSUE THREAD

**Issue by batunacun** [shap/shap#995]
Dear all friends
I am just asking how to amplify the text size of feature name in my shap force plot?
Thank you so much in advance.
looking forward your guidance.
Kind regards
Batu

**Comment by batunacun** [comment]
I used the latest shap version: '0.34.0'

**Comment by niloofardadras** [comment]
Hello,
I am looking for the same thing. the text size is too small for features, values and all texts generally.

**Comment by slundberg** [comment]
That would require exposing an option to update the CSS font size (or you could do it manually using the web browser DOM inspector). I am happy to merge any PR for this :)

**Comment by katcheng** [comment]
For anyone suffering like I have, here is how I solved the problem in a very inelegant manner:
Go into the SHAP documentation and find the file "_force_matplotlib.py"
Search for "fontsize" and update all fontsize values to desired fontsize, I updated them all to 20.
Reload shap package and do further customization with techniques from this thread for any specific variables such as tick label size:  #594

**Comment by boykoot01** [comment]
Chat gave me the following workaround that works for me in a waterfall plot: 
`fig = plt.gcf()`
`for text in fig.findobj(match=plt.Text):`
 `     text.set_fontsize(8)`
it just rewrites all text within your figure to size 8. Also not elegant but a quick fix when working with subplots etc.
